### ISSUE TITLE
[FEATURE] Custom wallpaper

### ISSUE THREAD

**Issue by digambar-t7** [EddieHubCommunity/LinkFree#1003]
### Description

I want to have a custom wallpaper on each profile page.
For the old profiles we can have a default wallpaper .
Can I proceed with this?

**Comment by emmalearnscode** [comment]
There are several discussions about custom themes for profiles , see #616 #133 ,  but as yet we are not sure how to ensure things like accessibility with color contrast etc can be kept to the required standard we have not gone ahead with any profile themes so far. I'll close this issue as a duplicate but feel free to comment in 616 or 133 if you have any design suggestions which will uphold accesibility requirements
