### ISSUE TITLE
Adding DEV as social icon 

### ISSUE THREAD

**Issue by lavakush07** [EddieHubCommunity/LinkFree#1005]
### Description

- We can add the [DEV](https://dev.to/) in the social icons.
- The reason behind adding the **DEV** is these days, the dev is acting as a social media for most of the developer communities.
- In _dev_ the people posts their blogs,podcasts,videos etc..

- I want to work upon this issue..

**Comment by schmelto** [comment]
Ups messed a little bit with the tittle 😅

I assigned you :)

**Comment by lavakush07** [comment]
Hey @schmelto , Sorry the dev social icon is already present.I came to know this,just now while I was looking into the code.U can close this issue.Thank u for your presence and sry for wasting ur time.
