### ISSUE TITLE
Change <h4> in Profile.js to meet A11Y requirements

### ISSUE THREAD

**Issue by YuriDevAT** [EddieHubCommunity/LinkFree#1007]
### Description

**Problem**
In the Profile.js component, the name surrounded by `<h1>` tags is followed by the username surrounded by `<h4>` tags.

W3C points out that it is necessary to keep the rank of headings in descending order and not skip a rank.

> Skipping heading ranks can be confusing and should be avoided where possible: Make sure that a `<h2>` is not followed directly by an `<h4>`, for example.

For more information about A11Y in the context of headings, see the official documentation of [W3C](https://www.w3.org/WAI/tutorials/page-structure/headings/).

**Solution**
Change `<h4>` to `<p>` and add `font-bold` class to retain the styling and increase the percentage of lighthouse results.

### Screenshots

Profile of a contributor
<img width="429" alt="Avatar, name and username of a contributor" src="https://user-images.githubusercontent.com/54622834/150184958-00c14761-4fea-47df-9314-fb40b77d56de.png">

LIghthouse results
<img width="731" alt="Lighthouse results with 95%" src="https://user-images.githubusercontent.com/54622834/150184983-e5790969-0cb4-4683-bfd8-bf1787bfe79c.png">

**Comment by emmalearnscode** [comment]
This is already fixed. Thanks for raising an issue and if you notice anything else that needs fixing don’t hesitate to raise another.
