### ISSUE TITLE
Add HackerRank Icon

### ISSUE THREAD

**Issue by Susmita-Dey** [EddieHubCommunity/LinkFree#1010]
### Description

I wanted to add my **HackerRank profile** link to my **LinkFree** page but I found there's no such icon present in the README.md file to be used . I request to add the HackerRank icon to the README.md file so that people like me can use it.

**Comment by emmalearnscode** [comment]
It will need adding in 3 places
1. GetIcons.js component 
2. Config/links.json
3. Readme

Do you want to be assigned?

**Comment by Susmita-Dey** [comment]
> It will need adding in 3 places
> 
> 1. GetIcons.js component
> 2. Config/links.json
> 3. Readme
> 
> Do you want to be assigned?

Yes sure. It would be great.
