### ISSUE TITLE
[FEATURE] Change buttons to links

### ISSUE THREAD

**Issue by jcubic** [EddieHubCommunity/LinkFree#1016]
### Description

I have experience with SEO and buttons are bad for

* UX
* Accessibility
* SEO

If something is a link to another website it should be a real link, not a button.

Also, real links (without `rel="nofollow"`) can really help Open Source projects. If someone will create a profile with links to his project's official websites.

I'm not sure how much in this community are actual FOSS authors and maintainers.

**Comment by emmalearnscode** [comment]
They are buttons due to using prime react components but they have an aria role of link so they should be rendered as links in the dom and be accessible.

**Comment by jcubic** [comment]
@emmalearnscode ok, what about SEO. The button is useless. What about UX, there is no link at bottom of the page, you have no idea where the link will point. This is not how you create links on the web platform. If something is a link it should be `<a href="...">`.

**Comment by emmalearnscode** [comment]
I hadn’t noticed that the url preview was missing, well spotted. I do agree that it should be a link, I’m not sure how easy it is to keep the prime react styling if we change it though.

**Comment by jcubic** [comment]
I can try to read the code and create PR. if this is something that will be accepted.

**Comment by jcubic** [comment]
I've just checked on https://bit.dev/primefaces/primereact/button in dev tools, Changing

`<button>` from generated HTML into `<a>` make no difference in the look of a button.

The only issue is with `:hover` effect. The CSS uses `:enabled` pseudo-class that doesn't work with links.

**Comment by nhcarrigan** [comment]
I agree with jcubic here - buttons should be buttons, links should be links. We can style an `a` element however we want, but using a `button` isn't semantic.

**Comment by emmalearnscode** [comment]
Did you want to be assigned to this issue @jcubic ?

**Comment by jcubic** [comment]
@emmalearnscode Ok, If everyone agrees to this change. I can change buttons to links.
