### ISSUE TITLE
Bad level of autoindent on GitPod link

### ISSUE THREAD

**Issue by jcubic** [EddieHubCommunity/LinkFree#1031]
### Description

When you open the GitPod link it has all set up in the container but the linter for the code is 2 spaces but the auto-indent in the editor is 4 spaces so it's hard to write proper code. Small changes (like #1025) are not the issue but bigger changes can drive you crazy and can lead to abandoning the editing.

**Comment by eddiejaoude** [comment]
Thanks for letting us know 👍

**Comment by jcubic** [comment]
Looking at the issue description and GitPod it seems this is fixed.

**Comment by eddiejaoude** [comment]
thank you @jcubic 👍 This is now done 👍 so I will close this issue
