### ISSUE TITLE
[FEATURE] Light/Dark Mode

### ISSUE THREAD

**Issue by vish-han** [EddieHubCommunity/LinkFree#1032]
### Description

Hey Everyone👋!
I think there should be a switch to toggle between light And dark mode.

I'm willing to work in this issue if the maintainers are happy to assign me😀.

**Comment by KendallDoesCoding** [comment]
Do you think something like on my website will work for this or do you want another kinda of design like a moon or something?

https://mogulchristmas.kendalldoescoding.gq/

There's a toggle between dark and light mode in the top right of the website.

**Comment by VaibhavArora19** [comment]
Can I work on this issue.

**Comment by schmelto** [comment]
Sure @VaibhavArora19

**Comment by VaibhavArora19** [comment]
Hey I am a beginner with react so I wanted to ask that I can do this by manipulating DOM with javascript right.. like adding or removing css classes based on value that can be changed using useState or is there any other approach I should use?

**Comment by VaibhavArora19** [comment]
@schmelto

**Comment by schmelto** [comment]
> @schmelto
 I would suggest try to look for a standard approach for Prime react which we are using in this project. I found something like this not sure if it works https://stackoverflow.com/questions/68327342/how-can-one-have-a-theme-switcher-in-primereact
Maybe someone else can give some guidance.

**Comment by VaibhavArora19** [comment]
Okay... I'll try this.

**Comment by VaibhavArora19** [comment]
Hey!! Can you assign this issue to someone else I tried this method but did not get the specified result. I think someone much more experience in React should work on this issue as it requires theme changing in runtime.

**Comment by schmelto** [comment]
@VaibhavArora19 no worries feel free to check out one of our other issues if you want :)

**Comment by Dhruv-Gajjar** [comment]
Hey @schmelto i would like to know if this issue is still open.?

**Comment by schmelto** [comment]
Sure go for it @Dhruv-Gajjar

**Comment by Dhruv-Gajjar** [comment]
@schmelto i am really new to open source can you guide me a bit about in which file do i have to add this feature? It would be of great help.

**Comment by schmelto** [comment]
> > @schmelto
> 
>  I would suggest try to look for a standard approach for Prime react which we are using in this project. I found something like this not sure if it works https://stackoverflow.com/questions/68327342/how-can-one-have-a-theme-switcher-in-primereact
> Maybe someone else can give some guidance. 

@Dhruv-Gajjar maybe this helps also nur completely sure where and how to implement this

**Comment by Shivam-Katare** [comment]
Hey! @schmelto I want to try this issue.So, can I work on this issue?

**Comment by cperezcapote** [comment]
Hey @schmelto I would like to work on this issue.

**Comment by Aniket1026** [comment]
can I also work on this issue ? would love to contribute in this issue

**Comment by Vedant-Manjrekar** [comment]
Hello! I tried implementing the toggle button for Dark and Light mode and it works well also passes all the test cases.
So if the maintainers allow i can make a pull request for the same.

Button is placed next to the version indicator.

**ScreenShots of the Implementation:**

<img width="1439" alt="Screenshot 2022-08-20 at 1 37 04 PM" src="https://user-images.githubusercontent.com/93585735/185735794-85295466-dbbe-4fa4-ab2f-4c05379b16f1.png">

<img width="1431" alt="Screenshot 2022-08-20 at 1 37 17 PM" src="https://user-images.githubusercontent.com/93585735/185735798-c067c7f2-3a16-46a9-b21f-2892ea8d699b.png">

<img width="1225" alt="Screenshot 2022-08-20 at 1 38 01 PM" src="https://user-images.githubusercontent.com/93585735/185735805-9c5b3baa-2658-4edb-b0a1-450e6b352d61.png">

<img width="1435" alt="Screenshot 2022-08-20 at 1 40 56 PM" src="https://user-images.githubusercontent.com/93585735/185735811-2336bb3d-ea2d-4d74-a377-1bb49c41b91f.png">
