### ISSUE TITLE
It Worked, But how? 🤔

### ISSUE THREAD

**Issue by orama254** [EddieHubCommunity/LinkFree#104]
Add a brief walkthrough of how you solved the github pages deployment bug from the last stream. It ended without a solution so maybe you can add how you tackled it in a separate video.

### The video mentioned
[Linktree alternative Youtube Livestream(starts at 3:01:00)](https://youtu.be/Jorl_vcp-Ew?t=10917)

**Comment by nhcarrigan** [comment]
Restricting this issue to `staff only` as Eddie will need to create the video.

**Comment by Panquesito7** [comment]
Ping. @eddiejaoude.

**Comment by krishguptadev** [comment]
> Restricting this issue to `staff only` as Eddie will need to create the video.

Also can you assign @eddiejaoude
