### ISSUE TITLE
[FEATURE] [Add gitlab icon to linktree]

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/LinkFree#1045]
### Description

Add gitlab icon to linktree

**Comment by KendallDoesCoding** [comment]
I dont think a lot of people will be using Gitlab though? So, I don't think yall NEED to add this, coz people can use website links to the svg for now: https://about.gitlab.com/images/press/press-kit-icon.svg, but yall can take a call on this.

**Comment by Panquesito7** [comment]
> I dont think a lot of people will be using Gitlab though? So, I don't think yall NEED to add this, coz people can use website links to the svg for now: https://about.gitlab.com/images/press/press-kit-icon.svg, but yall can take a call on this.

That won't work as excepted, we don't use icons that way.
Many people use GitLab, though. For example, I use it.

**Comment by emmalearnscode** [comment]
Sure, this can be added. To add it needs importing from react icons in getIcons.js and adding to the switch statement in alphabetical order, a colour needs adding in config/links.json (also alphabetical) and it needs adding to the readme

**Comment by KendallDoesCoding** [comment]
> > I dont think a lot of people will be using Gitlab though? So, I don't think yall NEED to add this, coz people can use website links to the svg for now: https://about.gitlab.com/images/press/press-kit-icon.svg, but yall can take a call on this.
> 
> That won't work as excepted, we don't use icons that way. Many people use GitLab, though. For example, I use it.

Ok, then maybe I use it less lol

**Comment by KendallDoesCoding** [comment]
> Sure, this can be added. To add it needs importing from react icons in getIcons.js and adding to the switch statement in alphabetical order, a colour needs adding in config/links.json (also alphabetical) and it needs adding to the readme

Do I need to do this?

**Comment by emmalearnscode** [comment]
> Do I need to do this?

If you want to do this issue then you will need to do all the steps, if you want to leave the issue for someone else to be assigned then that's also fine :)

**Comment by KendallDoesCoding** [comment]
> > Do I need to do this?
> 
> If you want to do this issue then you will need to do all the steps, if you want to leave the issue for someone else to be assigned then that's also fine :)

Ok cool! I'm not too good at react stuff so I'll leave this to someone else to do.

**Comment by kaxada** [comment]
@KendallDoesCoding I can jump onto this. Do I need to first get assigned or its a matter of first fix pull request!?

**Comment by emmalearnscode** [comment]
@kaxada Go ahead, I will assign you :)

**Comment by kaxada** [comment]
@emmalearnscode interesting. let me navigate this

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding I can jump onto this. can this be assigned to me @emmalearnscode ?

Thanks
