### ISSUE TITLE
[OTHER] CSS not formatted

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/LinkFree#1055]
### What would you like to share?

Css not formatted properly

**Comment by emmalearnscode** [comment]
Can you please share a screenshot to show what you mean?

**Comment by KendallDoesCoding** [comment]
> Can you please share a screenshot to show what you mean?

Its formatted but can be formatted better, I made a PR to work on this #1054

**Comment by emmalearnscode** [comment]
We already have a linter in place with formatting rules to make it consistent across different users. If you format it according to other rules the builds will fail.

**Comment by KendallDoesCoding** [comment]
> We already have a linter in place with formatting rules to make it consistent across different users. If you format it according to other rules the builds will fail.

True. Closing
