### ISSUE TITLE
Add more links like linkedIn, Instagram in the LinkFree

### ISSUE THREAD

**Issue by Pulkit007** [EddieHubCommunity/LinkFree#106]
We should add support for additional social platforms such as:

- LinkedIn
- Instagram
- Discord

Each social should have support for the platform's icon.

**Comment by StarTrooper08** [comment]
Dev.to forem link can be added can I add it??

**Comment by Soham041201** [comment]
Anybody working on this?

**Comment by StarTrooper08** [comment]
yep I m working to add devto forem

**Comment by Omkar845** [comment]
i would like to contribute

**Comment by Sejal-16** [comment]
can i work on this ?

**Comment by StarTrooper08** [comment]
Discord link PR is ready and also ready to merge I guess.
And Instagram link is added .
Any other social media link in your mind and if you are Confused how to make first open source contribution I m there to help.

Tag me ( @StarTrooper08 )

**Comment by StarTrooper08** [comment]
> Can i add discord link

LinkedIn link is remaining I guess check for the closed PR.
If no one added linkedin you can add it😃

**Comment by Zishan-7** [comment]
Hey @Vyvy-vi , I see that instagram and Linkedin links haven't been added yet. Can you assign me this issue?

**Comment by krishguptadev** [comment]
> Hey @Vyvy-vi , I see that instagram and Linkedin links haven't been added yet. Can you assign me this issue?

#675 doesn't this add the LinkedIn icon

**Comment by Zishan-7** [comment]
> > Hey @Vyvy-vi , I see that instagram and Linkedin links haven't been added yet. Can you assign me this issue?
> 
> #675 doesn't this add the LinkedIn icon

No one has added Linkedin icon yet.

**Comment by krishguptadev** [comment]
> > > Hey @Vyvy-vi , I see that instagram and Linkedin links haven't been added yet. Can you assign me this issue?
> > 
> > 
> > #675 doesn't this add the LinkedIn icon
> 
> No one has added Linkedin icon yet.

But there is a open PR for this 😅 Let's wait for the maintainers

**Comment by Zishan-7** [comment]
> > > > Hey @Vyvy-vi , I see that instagram and Linkedin links haven't been added yet. Can you assign me this issue?
> > > 
> > > 
> > > #675 doesn't this add the LinkedIn icon
> > 
> > 
> > No one has added Linkedin icon yet.
> 
> But there is a open PR for this 😅 Let's wait for the maintainers

yea, sure, 😄

**Comment by vr513** [comment]
If Nobody's working on this I am willing to contribute

**Comment by krishguptadev** [comment]
WIP: https://github.com/EddieHubCommunity/LinkFree/pull/823

**Comment by emmalearnscode** [comment]
React icons was added with PR #823 I'm going to close this issue as it encompasses a lot of different icons but if any icons are still missing please open individual issues for each one :)
