### ISSUE TITLE
[FEATURE] Random User Profile

### ISSUE THREAD

**Issue by PhilipBDev** [EddieHubCommunity/LinkFree#1062]
### Description

Hello! 👋 I've never contributed to an open source project before, but I had an idea for LinkFree.

A button next to search that brings up a random user profile! I always love the random page feature of wiki sites, so I thought this would be a fun way to browse each other's profiles on the site. The link will update every time the page is refreshed.

Let me know what you think! I do have it done already (I just wanted to practice understanding someone else's code) and it did pass all the Cypress tests, so if it's approved I can immediately do a pull request so I can get some feedback, but if not that's okay too since I just wanted to see if I could make it happen. 😁 Thank you!

### Screenshots

![Random1](https://user-images.githubusercontent.com/26912166/152594025-1d17bccc-f999-4ec2-8508-7e9c7e86c38b.png)
![Random2](https://user-images.githubusercontent.com/26912166/152594028-ec934c0e-b40a-41e8-8b20-601861f608b5.png)
![Random3](https://user-images.githubusercontent.com/26912166/152594030-9f6150a2-909f-4391-82d6-058e74dce5ce.png)

**Comment by emmalearnscode** [comment]
I really like this idea! However, I would reconsider the design of the button next to the search because to me it does not communicate the purpose and It shouldn’t need a hover tooltip.

it would be great to see what others think too.

**Comment by KendallDoesCoding** [comment]
i like the idea too

**Comment by viroopaksh-utrayak** [comment]
yea this idea is cool but what about the searching history

**Comment by vasantisuthar** [comment]
yeah the idea is good

**Comment by CodingSpecies** [comment]
@PhilipBDev maybe icons like these could be used: 
![0D6218F2-E3F2-4A72-A14B-B893A495AD12](https://user-images.githubusercontent.com/70807500/155399316-e8f7d296-ec65-4032-b5a8-aaece3a91fcb.png)

**Comment by CodingSpecies** [comment]
or maybe to make it more obvious that it is a random user @PhilipBDev :
<img src="https://www.kindpng.com/picc/m/80-800188_random-user-random-icon-png-transparent-png.png" height=200 />

**Comment by emmalearnscode** [comment]
To me something like Google’s I’m feeling lucky button comes to mind, maybe we should create a few mock-ups with different texts/icons (we have anything from react icons and prime react buttons to play with)

**Comment by eddiejaoude** [comment]
We are planning on removing the list of people from the homepage, I wonder if we could pick some random users to display on the homepage?

**Comment by schmelto** [comment]
> We are planning on removing the list of people from the homepage, I wonder if we could pick some random users to display on the homepage?

What about displaying some kind of demo of linkfree in the homepage and in this wrapper use every time a new random profile

**Comment by eddiejaoude** [comment]
@schmelto do you have an example of what you mean by demo? I initially thought a video, but if we are to have a random profile each time could you elaborate a bit more

**Comment by schmelto** [comment]
> @schmelto do you have an example of what you mean by demo? I initially thought a video, but if we are to have a random profile each time could you elaborate a bit more

Will provide some feedback after my vacation

**Comment by eddiejaoude** [comment]
Thanks Tom! Enjoy your adventures!

**Comment by schmelto** [comment]
> Thanks Tom! Enjoy your adventures!

I assumed a landing page / homepage like this with some explanation text what linkfree is ( how to add a profile etc) and a sample "screenshot" of the random profile as live demo of how linkfree for you will look like when you create a profile there.

![image](https://user-images.githubusercontent.com/30869493/170954334-111d4e2c-22af-43aa-93d5-8369bf25a082.png)

**Comment by eddiejaoude** [comment]
Thanks Tom! Great idea 👍

**Comment by eddiejaoude** [comment]
Something like this for the demo ....
![device_mock-up_1](https://user-images.githubusercontent.com/624760/171043860-8a3705bd-0568-43a2-b430-9b723cc24b7f.png)

**Comment by krshkun** [comment]
Don't we already have a Random Profiles on discover? Maybe this can be closed

**Comment by eddiejaoude** [comment]
yes this is done 👍 

This is now done 👍 so I will close this issue
