### ISSUE TITLE
Update github icon color on main page

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/LinkFree#1072]
### Description

On the site, in instances "Contribute on <github icon> v0.62.3" the <github icon> is purple, while that looks good, the original github icon is black, so it is better if it's black right?

### Additional information

Will see if I can work on this, but I'm not sure so if someone else wants to take this up, please go ahead. Thanks

**Comment by KendallDoesCoding** [comment]
> @BSlaven You only fixed this in one instance of the website, please do it in the other too
> 
> @emmalearnscode Please re-open this issue, I cannot reopen the issue, as you a mod of EddieHubCommunity closed it so GitHub doesn't let me.
> 
> Thanks, KendallDoesCoding

Information on the other instance:
@BSlaven You've not it in the footer in #1081 but not on the top.

Screenshot: 
![image](https://user-images.githubusercontent.com/84712013/153548695-9340450a-007e-486f-a99f-ea3dc66bb930.png)

Please do the needful because the github icon is black not purple 😆 .

Thanks a lot!
Kendall Does Coding

**Comment by emmalearnscode** [comment]
@KendallDoesCoding maybe you could have been more specific when you opened the issue. Please don’t ping BSlaven telling them to do more in case they don’t have time, anyone is able to help resolve the issue.

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding maybe you could have been more specific when you opened the issue. Please don’t ping BSlaven telling them to do more in case they don’t have time, anyone is able to help resolve the issue.

Sorry about that, I meant in both locations/instances. Sorry for pinging BSlaven too.

**Comment by BSlaven** [comment]
No problem @KendallDoesCoding. I am on it.

**Comment by KendallDoesCoding** [comment]
> No problem @KendallDoesCoding. I am on it.

Thanks, Sorry for the inconvenience.
