### ISSUE TITLE
[OTHER] Site marked as not secure

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/LinkFree#1075]
### What would you like to share?

For some reason, the site doesn't have ```https://``` it has ```http://`` missing the s at the end. It can be coz the site was made a long time ago, so the site is marked as "Not Secure" at least for google (idk about other browsers. The site works if you add s in the end though, but that's a even worse not secure, so idk who has permissions with the hosting stuff (i think its @eddiejaoude) so please have a look and see if the page can be made secure again.

**Comment by emmalearnscode** [comment]
Eddie is working on this, it will be coming but has something to do with the kubernetes cluster IIRC

**Comment by KendallDoesCoding** [comment]
> kubernetes cluster IIRC

Ok, so should I keep this issue open or should I close it?

**Comment by emmalearnscode** [comment]
You can leave it open as I don’t think there’s a duplicate, it just won’t get assigned to anyone yet

**Comment by KendallDoesCoding** [comment]
> You can leave it open as I don’t think there’s a duplicate, it just won’t get assigned to anyone yet

Yeah, nobody can do this except the EddieHub team anyway, and as I said in the description, I think only @eddiejaoude has access to the hosting.

**Comment by emmalearnscode** [comment]
Duplicate #197
