### ISSUE TITLE
[OTHER] Deploy after every commit.

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/LinkFree#1076]
### What would you like to share?

According to me, it would be better if the site deploys after every commit in this repo, I use that for my personal projects, and it's very good. I think it will be better, instead of users creating their profiles and waiting for 2-7 days at max for it to show up on the site.

### Additional information

Idk if this is possible with the hosting, which I believe is **DigitalOcean, LLC** becuase I use Netlify, but if this is possible it would be great.

**Comment by emmalearnscode** [comment]
It has to do with the versions. Adding a profile counts as a chore and doesn’t bump the version number, fixes and features bump the version number and therefore trigger the site to deploy.

**Comment by KendallDoesCoding** [comment]
> It has to do with the versions. Adding a profile counts as a chore and doesn’t bump the version number, fixes and features bump the version number and therefore trigger the site to deploy.

Ok
