### ISSUE TITLE
Copy Link Option [NOT WORKING]

### ISSUE THREAD

**Issue by aroramrinaal** [EddieHubCommunity/LinkFree#1079]
### Description

The **Copy Link** option which appears after clicking the share option is not working.

### Screenshots

<img width="1438" alt="Screenshot 2022-02-07 at 1 11 02 PM" src="https://user-images.githubusercontent.com/90490253/152745897-b8a47766-f4c3-4ba2-a85c-a3dfdf88143f.png">

### Additional information

This is My First Open Source Issue.

**Comment by emmalearnscode** [comment]
Thanks for noticing, this is a duplicate so I’ll close it for now.

**Comment by KendallDoesCoding** [comment]
> Thanks for noticing, this is a duplicate so I’ll close it for now.

I'll see if I can fix this, can you please mention the original issue?

**Comment by emmalearnscode** [comment]
> > Thanks for noticing, this is a duplicate so I’ll close it for now.
> 
> I'll see if I can fix this, can you please mention the original issue?

It's because of the http not secure issue, the copy/paste API only works on https so it's blocked until that is fixed.

**Comment by KendallDoesCoding** [comment]
Ok, cool

**Comment by aroramrinaal** [comment]
Ok , Thanks for letting me know.
