### ISSUE TITLE
[ FEAT ] FAVICON LOGO ( LINKFREE LOGO ) 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [EddieHubCommunity/LinkFree#109]
We will be needing one logo which we can add on favicon and also in readme

**Comment by nhcarrigan** [comment]
We should use this issue to discuss potential favicon options. Once an icon has been chosen, we can open this up for contributions.

**Comment by rohan-kulkarni-25** [comment]
# Closing Issue will shift to [Discussion](https://github.com/EddieHubCommunity/LinkFree/discussions/206#discussion-3575864)
