### ISSUE TITLE
[FEATURE] Infinite scroll

### ISSUE THREAD

**Issue by MassiiNechiche** [EddieHubCommunity/LinkFree#1091]
### Description

the first page loads all the users at a time, would be cool to add Infinite Scroll that automatically adds the next page when hiting the bottom, saving users from a full page load if there is plenty of users to diplay.

**Comment by KendallDoesCoding** [comment]
> ### Description
> the first page loads all the users at a time, would be cool to add Infinite Scroll that automatically adds the next page when hiting the bottom, saving users from a full page load if there is plenty of users to diplay.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

I like the idea.

**Comment by Hugher256** [comment]
I am pretty new to open source but I think I can handle this task. Can this be assigned to me?

**Comment by schmelto** [comment]
@Hugher256 feel free to takle this issue! I assigned you

**Comment by emmalearnscode** [comment]
We have decided to take the project in a different direction and therefore no longer plan to implement this feature at this time. Thanks for taking the time to raise the issue and we look forward to collaborating in the future.
