### ISSUE TITLE
Change the profile photo opacity on hover

### ISSUE THREAD

**Issue by SaNsK11** [EddieHubCommunity/LinkFree#110]
We can add a `:hover` CSS selector to fade the avatar in/out on hover.

**Comment by guptasajal411** [comment]
Nice idea, can I work on this?

**Comment by ZaidKhan2002** [comment]
I would like to work on this issue. Can I work ?

**Comment by ravi-varma-ankam** [comment]
Can I work on this issue for hacktoberfest??

**Comment by Krishnapro** [comment]
Hey I would like to work on this issue #110 can you assign me this @eddiejaoude

**Comment by krishguptadev** [comment]
I would like to work on this.
