### ISSUE TITLE
[FEATURE] CODEOWNERS

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/LinkFree#1111]
### Description

Assign people in the @EddieHubCommunity to be a reviewer for PR's automatically using the Codeowners file. 

For eg, if it has to do with public/data directory, assigns the main people that review add profile PR's, @emmalearnscode @Panquesito7 @schmelto @krshdev .

This will help organize everything in this repo.

### Additional information

Only con I can see with doing this, is the email notifications, if yall haven't disabled them, otherwise, I think its a good idea.

**Comment by emmalearnscode** [comment]
RIP to our notifications 😂 Anyone is open to review code on eddiehub, and as all maintainers are volunteers they dedicate the time they can which sometimes means some patience is required until we can get round to it. I personally prefer not to be tagged in every PR, I check often enough to see updates and being tagged all the time causes extra noise that might mean something important gets missed. Just my opinion, others might think differently

**Comment by krshdev** [comment]
Yes, I agree with emma, you don't need to mention us all the time, we will triage the issue 🙂  and I'm not a maintainer (letting you know because you mentioned me 😳) .

Also I don't think this is needed, unless we want the project to be like => The PR won't get merged until the code owner reviews.

**Comment by nhcarrigan** [comment]
Actually, this isn't a terrible idea. We could use the CODEOWNERS file to assign the LinkFree team, and pair that with the [repo settings](https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team) to enable round robin review.

This way, we could set it so one of the team members gets assigned to a PR, but it'll cycle through and we won't get hammered with notifications.

**Comment by krshdev** [comment]
> Actually, this isn't a terrible idea. We could use the CODEOWNERS file to assign the LinkFree team, and pair that with the [repo settings](https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team) to enable round robin review.
> 
> This way, we could set it so one of the team members gets assigned to a PR, but it'll cycle through and we won't get hammered with notifications.

Maintainers still get notifs because they are subbed to the repo

**Comment by nhcarrigan** [comment]
I'm not lol

It would also help us designate a specific maintainer to spearhead each PR - so we aren't getting conflicting reviews.

**Comment by KendallDoesCoding** [comment]
> Yes, I agree with emma, you don't need to mention us all the time, we will triage the issue 🙂 and I'm not a maintainer (letting you know because you mentioned me 😳) .
> 
> Also I don't think this is needed, unless we want the project to be like => The PR won't get merged until the code owner reviews.

Yeah, I wont ping yall next time, ik yall read all the PR's.

Closing this with everyones comments, anyone is welcome to review PRs in EddieHubCommunity.
