### ISSUE TITLE
Issue with GitHub Avatar URLs

### ISSUE THREAD

**Issue by nhcarrigan** [EddieHubCommunity/LinkFree#1113]
### Description

Refreshing the page results in 429 errors from GitHub on all of the avatars we are fetching. We may need a better approach for this.

### Screenshots

<img width="837" alt="image" src="https://user-images.githubusercontent.com/63889819/153528168-2c232966-5877-47e3-acc5-2ce25a1611a5.png">

<img width="1860" alt="image" src="https://user-images.githubusercontent.com/63889819/153528309-67d54a80-4d40-4cab-876f-fd210142f552.png">

**Comment by krshdev** [comment]
Duplicate of #1085

**Comment by nhcarrigan** [comment]
Thanks for catching that!

**Comment by KendallDoesCoding** [comment]
> ### Description
> Refreshing the page results in 429 errors from GitHub on all of the avatars we are fetching. We may need a better approach for this.
> 
> ### Screenshots
> <img alt="image" width="837" src="https://user-images.githubusercontent.com/63889819/153528168-2c232966-5877-47e3-acc5-2ce25a1611a5.png">
> 
> <img alt="image" width="1860" src="https://user-images.githubusercontent.com/63889819/153528309-67d54a80-4d40-4cab-876f-fd210142f552.png">
> 
> ### Additional information
> _No response_

I'm only getting the error for https://github.com/Recognizeyourself.png..
