### ISSUE TITLE
[OTHER] Which profile uses this icon?

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/LinkFree#1114]
### What would you like to share?

The GitHub user whoose username was Recognizeyourself changed their username and now it's updated and giving a error in console. Can someone, in their free time help me find whose GitHub username was Recognizeyourself before/icon link was https://github.com/Recognizeyourself.png ?. Thanks

**Comment by emmalearnscode** [comment]
I have contacted them via their Twitter profile and asked them to update

**Comment by KendallDoesCoding** [comment]
> 

Thank you but what is the users name? I would like to debug something.

**Comment by emmalearnscode** [comment]
The file is recognizeyourself.json, name Yash Verma

**Comment by KendallDoesCoding** [comment]
Ok, thanks

**Comment by emmalearnscode** [comment]
Is there an actual issue here or can this be closed? I have contacted the account owner via Twitter and they are aware of the problem and will fix it when they get time

**Comment by KendallDoesCoding** [comment]
> Is there an actual issue here or can this be closed? I have contacted the account owner via Twitter and they are aware of the problem and will fix it when they get time

Ok cool, let me just do a final check and will close accordingly

**Comment by KendallDoesCoding** [comment]
Yup, the only issue that seems to be there is that his pfp, github url and maybe insta account urls don't work... So, let them update it when their free....... Closing
