### ISSUE TITLE
Icons not working

### ISSUE THREAD

**Issue by abdussalam02** [EddieHubCommunity/LinkFree#1119]
### Description

Graduation Hat and Dev.to icon is not rendering on the website and globe icon is rendering instead of graduation hat..

### Screenshots

![Screenshot (42)](https://user-images.githubusercontent.com/87809119/153712570-56b298e6-7891-4f3c-9f75-30b5f636ab8f.png)

**Comment by krshdev** [comment]
I've made a PR for fixture about grad hat, unsure about dev.to

**Comment by KendallDoesCoding** [comment]
Ig we can merge this issue with #1085? Cause, that's reporting render issues too. But this is a different kinda issue altogether, so let me know.

**Comment by KendallDoesCoding** [comment]
If you reload the page, does it render? That's what I faced for #1085

**Comment by abdussalam02** [comment]
> 

you can see the screenshot but maybe the icon and background color are same maybe that's why it's showing white bg

**Comment by abdussalam02** [comment]
> Ig we can merge this issue with #1085? Cause, that's reporting render issues too. But this is a different kinda issue altogether, so let me know.

i don't think it's the same problem #1085

**Comment by KendallDoesCoding** [comment]
> > 
> 
> you can see the screenshot but maybe the icon and background color are same maybe that's why it's showing white bg

there is a icon call out issue with one icon, i think, it has a space instead of a -

**Comment by KendallDoesCoding** [comment]
> > Ig we can merge this issue with #1085? Cause, that's reporting render issues too. But this is a different kinda issue altogether, so let me know.
> 
> i don't think it's the same problem #1085

Neither do I, let it remain in this repo.
