### ISSUE TITLE
[FEATURE] Center the links

### ISSUE THREAD

**Issue by abdussalam02** [EddieHubCommunity/LinkFree#1122]
### Description

I think we should center the social link and icon it will look much better

### Screenshots

![Screenshot (43)](https://user-images.githubusercontent.com/87809119/153719308-a3853e5d-0eac-4662-8bbc-b52c08c56302.png)

**Comment by emmalearnscode** [comment]
In terms of accessibility it’s better to have them left aligned as it makes it easier to read for people with visual impairments or dyslexia

**Comment by KendallDoesCoding** [comment]
> ### Description
> I think we should center the social link and icon it will look much better
> 
> ### Screenshots
> ![Screenshot (43)](https://user-images.githubusercontent.com/87809119/153719308-a3853e5d-0eac-4662-8bbc-b52c08c56302.png)
> 
> ### Additional information
> _No response_

I think this way it will look better, yeah.

**Comment by abdussalam02** [comment]
Should I close the issue if the matter is decided..?

**Comment by KendallDoesCoding** [comment]
> Should I close the issue if the matter is decided..?

Keep it open even if its decided coz someone will commit/make a PR and when merged this will auto get closed.

**Comment by schmelto** [comment]
> In terms of accessibility it’s better to have them left aligned as it makes it easier to read for people with visual impairments or dyslexia

> Should I close the issue if the matter is decided..?

Closing this due to comment of emma https://github.com/EddieHubCommunity/LinkFree/issues/1122#issuecomment-1037358252
