### ISSUE TITLE
[FEATURE] Add text on main page

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/LinkFree#1123]
### Description

The reason I created #1077 was because I had a idea, the icon can show up here with the text "Linkfree" in a epic font:

![image](https://user-images.githubusercontent.com/84712013/153721781-4cca418e-994c-4f71-9f22-375b0418231e.png)

I only think this will be good on the MAIN/HOME page. 

### Additional information

If, there's coding needed in HTML for this, I can help, if in Node, won't be possible.

**Comment by Vyvy-vi** [comment]
That could be a neat place to have the title in, however, we might need to check how this gets rendered in mobile mode first.

**Comment by KendallDoesCoding** [comment]
> That could be a neat place to have the title in, however, we might need to check how this gets rendered in mobile mode first.

Using css (This is what I know, it may be possible with JS or Node too), you can set it to not show the text on mobile if it's rendering bad, but will show on desktop, laptop, maybe iPad coz I think it will look great if we include this.

**Comment by santhoshbala0178** [comment]
@KendallDoesCoding  @Vyvy-vi  I can work on this issue, and check the responsiveness as well.

**Comment by schmelto** [comment]
@santhoshbala0178 go for it :)

**Comment by eddiejaoude** [comment]
I will closing this issue as we have a whole new version of the app, a new issue can be created if required
