### ISSUE TITLE
[FEATURE] Auto-update github if username changes.

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/LinkFree#1127]
### Description

A api or something to have a look every 10 minutes if the github username exists, if it doesn't create a issue thread and a PR fixing the issue thread, updating the github avatar url and github url, according to new username, using commit history.

### Additional information

It may be confusing coz I didn't explain well lol.

**Comment by Vyvy-vi** [comment]
I think this could be an option, but Idk feels weird that we'd be tracking and updating people's data without asking them first.
Maybe when we switch to data stored in the API, this type of tracking can be added to the API...

**Comment by KendallDoesCoding** [comment]
> I think this could be an option, but Idk feels weird that we'd be tracking and updating people's data without asking them first. Maybe when we switch to data stored in the API, this type of tracking can be added to the API...

Yeah, but the issue is, many people forget to update their pfp when the change their github username, and until 1-2 months later, its as it is, and their pfp isn't working.. If the pfp doesn't work even the profile sometimes gets messed up (see #1139 )

**Comment by Nnadivictory25** [comment]
You can still update to your latest profile info anytime in the json file

**Comment by kiritocode1** [comment]
ask them beforehand , same as facebook , just put up " we use some data "

**Comment by eddiejaoude** [comment]
I think usernames don't change that often, plus when we finish GitHub OAuth, it can auto update when they login, so I am going to close this issue
