### ISSUE TITLE
feat: Home Page for LinkFree Project

### ISSUE THREAD

**Issue by Soham041201** [EddieHubCommunity/LinkFree#113]

**Comment by nhcarrigan** [comment]
Going to open this one up for discussion for what we would like the content of the home page to be.

**Comment by Soham041201** [comment]
A basic nav-bar and a body to start with. We can also add a horizontal scroll bar or something to search through the profiles

**Comment by Soham041201** [comment]
Should I raise a PR for the Nav Bar?

**Comment by Soham041201** [comment]
Added a basic Nav bar in the home Page. Contains two basic  links home and links.
