### ISSUE TITLE
Incorrect names displaying

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/LinkFree#1139]
### Description

There are a bunch of incorrect names displaying.. I searched for "Kendall" to make sure my profile was deleted properly and Aayush showed under my name for one time, reloaded the page, did it again and Aayush showed under Lokesh Digari.. If tapped it takes to the correct profile but why is Aayush's pfp showing?

### Screenshots

Aayush: 
![image](https://user-images.githubusercontent.com/84712013/154841315-1756da1b-f63a-4cce-a37e-dfd0e97eb652.png)

Aayush showing under Lokesh Digari:
(SS CAPTURED BUT NOW LOST)

### Additional information

Problem seems to be fixed, it only caused it around 3 times, but creating this issue just for a heads up.

**Comment by emmalearnscode** [comment]
What operating system/browser are you getting this error on? And what are the exact steps to make it happen? I haven't been able to replicate it yet but that doesn't mean there isn't something wrong.

**Comment by emmalearnscode** [comment]
We can leave it open for a while to see if anyone else reports something similar

**Comment by KendallDoesCoding** [comment]
> We can leave it open for a while to see if anyone else reports something similar

Ok cool

**Comment by KendallDoesCoding** [comment]
> We can leave it open for a while to see if anyone else reports something similar

Got another instance of this error when I turned on my vpn (when i turn on the vpn my internet is very slow so I believe this issue is cause when internet is slow the pfps get messed up a bit?)

**Comment by KendallDoesCoding** [comment]
> > We can leave it open for a while to see if anyone else reports something similar
> 
> Got another instance of this error when I turned on my vpn (when i turn on the vpn my internet is very slow so I believe this issue is cause when internet is slow the pfps get messed up a bit?)

On the site, it loads and shows the other pfp for 2 mins and then shows the actual pfp.. I believe this issue is because when it loads the pfp loads, when I search for a certain profile, sometimes the pfp displays of the profile that was there before I typed the text for 1-3 secs, even tho it's not really a BAD issue. We should work on a fix for it.

**Comment by KendallDoesCoding** [comment]
Got a snapshot fast, this time the issue lasted around 5-6 secs.
Eddie incorrect pfp: 
![image](https://user-images.githubusercontent.com/84712013/155673155-90e24e33-bba5-45bb-a4c7-515ba4834a98.png)

Eddie's pfp: 
![image](https://user-images.githubusercontent.com/84712013/155673215-e4ae6de9-f5c8-4065-9357-84f49316e692.png)

**Comment by adityaraute** [comment]
Would there be a way to clear Cache at every reload? And is that ideal?

**Comment by schmelto** [comment]
I think we can close this now as no one else reported similar issues and due to the refactor of the page pictures are also not displayed anymore on the search page

**Comment by schmelto** [comment]
feel free to reopen if the issue still occurs
