### ISSUE TITLE
Copy link feature not working

### ISSUE THREAD

**Issue by Pranav016** [EddieHubCommunity/LinkFree#1140]
### Description

Copy link feature not working and neither is the toast showing up (that I saw in the code) after the link was to be copied.

I would like to try and fix this, please assign.

### Screenshots

![image](https://user-images.githubusercontent.com/54665036/154855219-de77934a-aa31-4e16-95b3-0a3cacf7590d.png)

**Comment by emmalearnscode** [comment]
This is a duplicate and also blocked by the need to upgrade to https. Thanks for noticing but I’ll close it for now.

**Comment by Pranav016** [comment]
> This is a duplicate and also blocked by the need to upgrade to https. Thanks for noticing but I’ll close it for now.

Can you please direct me to the copy of this issue? I couldn't find the issue that is why asking..

Also I have found that this code here is returning a javascript promise that acc to me is not being handled correctly and this info might be useful for someone trying to fix the issue.
![image](https://user-images.githubusercontent.com/54665036/154856471-e473969e-9b28-41d2-ace0-8f918fe11f8b.png)

Can you tag the duplicate issue number here so I can help and let others know?

**Comment by emmalearnscode** [comment]
It is #946
