### ISSUE TITLE
Can We have GIF's in Profile Picture

### ISSUE THREAD

**Issue by Recognizeyourself** [EddieHubCommunity/LinkFree#116]
Like the way we have png file in Profile Pic, We can use Dynamic gifs in the profile picture.

**Comment by nhcarrigan** [comment]
Because we are using GitHub's `username.png` format for avatars, we will not be able to support GIF formats as GitHub does not support GIF formats.

**Comment by Recognizeyourself** [comment]
Thanks for Clarifying !! 😅🙌
