### ISSUE TITLE
[FEATURE] <Copy the link button>

### ISSUE THREAD

**Issue by Kazybekkh** [EddieHubCommunity/LinkFree#1161]
### Description

User can tap a button that copies the link of (for example, Twitter) to the clipboard

**Comment by Vallejoanderson** [comment]
Sounds interesting. I am new here. I would like to help but I would maybe need some guidance too since I'm learning React (not sure if it's good to show some weakness in these scenarios :) ).

**Comment by emmalearnscode** [comment]
Can you explain more about what you mean? Which button? As far as I know you can already right click the ‘follow me on…’ buttons and copy the link

**Comment by Kazybekkh** [comment]
Hey! Thanks for your comment! The issue is solved. I have thought maybe we could add a button like on GitHub where you just copy the link instead of going to the website but after trying out the demo, quickly realized it’s pointless. 
I was thinking that the website will immediately switch to the app without my permission, leaving me without the ability to copy the link and share it someone. I apologize for the clumsiness of this issue
