### ISSUE TITLE
[Name Recomendations] <correct the name recommendation feature of linkfree>

### ISSUE THREAD

**Issue by DeepanshuDaksh77** [EddieHubCommunity/LinkFree#1185]
### Description

in linkfree the name recommendation is not working properly , like for word B it is recommending all the names that include the word b instead of recommending those profiles that start with the word B

### Screenshots

![Screenshot 2022-03-17 at 11-39-28 LinkFree](https://user-images.githubusercontent.com/97582830/158747651-17b6635e-673b-4946-99a0-83f48d7d83a2.png)
![Screenshot 2022-03-17 at 11-39-08 LinkFree](https://user-images.githubusercontent.com/97582830/158747684-8cd51f2e-6af5-4edb-a9ff-2e468f970b56.png)

### Additional information

I think it will be cool if linkfree can have this recommendation feature.

**Comment by emmalearnscode** [comment]
I’m not sure if this is a good idea. Say that I want to search for someone but I only remember their last name, or a part of their name, then they won’t show up in the search if it only matches the beginning.

**Comment by DeepanshuDaksh77** [comment]
> I’m not sure if this is a good idea. Say that I want to search for someone but I only remember their last name, or a part of their name, then they won’t show up in the search if it only matches the beginning.

oh yeah! i never thought about that . That's a good point.
