### ISSUE TITLE
Add margin on top 

### ISSUE THREAD

**Issue by SaNsK11** [EddieHubCommunity/LinkFree#119]
We should add a small margin on the top of the page to create spacing between the content and the browser window.

**Comment by spy-1234** [comment]
I want to do this issue for development

**Comment by ZaidKhan2002** [comment]
> I want to work on this issue.

**Comment by amittri1025** [comment]
Can I work on this issue ?

**Comment by AwsmNinad25** [comment]
I would like to work on this issue.

**Comment by Omkar845** [comment]
i would like to contribute

**Comment by Krishnapro** [comment]
Hey I would like to work on #119 this issue can you assign me this, I'm beginner so I want to start with this type of issue.

**Comment by Krishnapro** [comment]
Hey please assign to me @eddiejaoude

**Comment by CodingSpecies** [comment]
@Vyvy-vi I think this issue can be closed, as this pr which is merged - #603 - covers it.
Thank you.

**Comment by Vyvy-vi** [comment]
Thank you @CodingSpecies
