### ISSUE TITLE
[DOCS] Move the supported Icons to a seprate file.

### ISSUE THREAD

**Issue by Pradumnasaraf** [EddieHubCommunity/LinkFree#1195]
### Description

- Move the [Available Icons](https://github.com/EddieHubCommunity/LinkFree#available-icons) section from the README to a file name `icons.md`

- Also, add a message in the README for the contributors to check the available icon file.
It can something like this, and hyperlink the icon's file.
_"Check [`Icons.md`]() for the all the supported icons"_

### Screenshots

Section to be moved
![Screenshot from 2022-03-23 09-59-56](https://user-images.githubusercontent.com/51878265/159624863-1d8689c2-4dbe-4736-8cf2-56c057b922b7.png)

**Comment by vikasganiga05** [comment]
Hi Pradumna, that's a great idea. When icons are moved to their separate file (ICONS.md) the README.md file will look minimal. Thanks for the idea :)

**Comment by kishoreandra** [comment]
Dear @Pradumnasaraf, as per your suggestion moved it to a separate file and added a link ... 

How about the text as "Check [Icons.md](https://github.com/EddieHubCommunity/LinkFree/issues/1195) for the all the **_supported_** icons" instead "Check [Icons.md](https://github.com/EddieHubCommunity/LinkFree/issues/1195) for the all the **_available_** icons"

please suggest, btw its my first contribution 😃  so happy !

**Comment by Pradumnasaraf** [comment]
> Dear @Pradumnasaraf, as per your suggestion moved it to a separate file and added a link ... 
> 
> How about the text as "Check [Icons.md](https://github.com/EddieHubCommunity/LinkFree/issues/1195) for the all the **_supported_** icons" instead "Check [Icons.md](https://github.com/EddieHubCommunity/LinkFree/issues/1195) for the all the **_available_** icons"
> 
> please suggest, btw its my first contribution 😃  so happy !

Absolutely, it was just an suggestion, go ahead with is best suitable 😄,
Welcome to Open Source
