### ISSUE TITLE
Sharing the status along with links

### ISSUE THREAD

**Issue by Yash-verma18** [EddieHubCommunity/LinkFree#122]
Like When someone hovers over Twitter link, We can show Twitter Followers and bio, following.

And When someone hovers over Github link, We can show Most popular Repositories of him, Total contribution, Github Stats.

**Comment by rohan-kulkarni-25** [comment]
> Like When someone hovers over Twitter link, We can show Twitter Followers and bio, following.
> 
> And When someone hovers over Github link, We can show Most popular Repositories of him, Total contribution, Github Stats.

Idea is good but can you please explain how can we implement the following or not feature ?

**Comment by FayasNoushad** [comment]
Already #107

**Comment by nhcarrigan** [comment]
This is achievable, but would require that we add an API to the project and set up API keys and endpoints to fetch this data. 

Going to leave this open for @eddiejaoude to discuss if this is within the intended scope of the project.

**Comment by Recognizeyourself** [comment]
Unfortunately, I am too noob in the front end to actually implement this. but @nhcarrigan comment made me confident.
