### ISSUE TITLE
[DOCS] Add a Wiki for documentations

### ISSUE THREAD

**Issue by KarlGusta** [EddieHubCommunity/LinkFree#1225]
### Description

Add a Github Wiki tab where we can have links to the documentation, contributing links, and the youtube page.

**Comment by emmalearnscode** [comment]
We tend not to use the wiki section in eddiehub repos. If this is specific to linkfree then it should have its own md file, if it’s more generic then maybe it should be part of the support repo and something we can link to from all other repos.

**Comment by eddiejaoude** [comment]
We have new documentation that is part of the web app, so I will close this issue as it is now done
https://linkfree.eddiehub.io/docs
