### ISSUE TITLE
Points explanation 

### ISSUE THREAD

**Issue by EmmaDawsonDev** [EddieHubCommunity/LinkFree#1227]
### Description

Add an explanation of what the points system means to the contributing.md

**Comment by kartikgajjar7** [comment]
hey Emma i would like to work on this issue can you assign it to me ?

**Comment by kartikgajjar7** [comment]
hey  Emma can you give me context about what i ve to add

**Comment by EmmaDawsonDev** [comment]
If you look at the labels that can be applied to each issue they range from points: 1, 2, 3, 5, 8, 13. This means that issues labeled with 1 or 2 take the least amount of time and knowledge up to 13 which is much more complex and expected to require much more time, knowledge and expertise in order to complete. 1 point might be expected to take less than an hour whereas 13 could take several days to a couple of weeks.

**Comment by SaraJaoude** [comment]
I am helping out the documentation so I will add this to my list of things to do

**Comment by hirentimbadiya** [comment]
can i work on this issue if this is still opened and unassigned??

**Comment by SaraJaoude** [comment]
@hirentimbadiya this issue has been assigned to me and I am working on it

**Comment by hirentimbadiya** [comment]
> @hirentimbadiya this issue has been assigned to me and I am working on it

in this issue justwe have to changing contributing.md or we have to show that in linkfree documentation web page in website also?

**Comment by eddiejaoude** [comment]
This can now be closed as we have docs on labels and points https://linkfree.eddiehub.io/docs/contributing/labels
