### ISSUE TITLE
Add a dark theme for night

### ISSUE THREAD

**Issue by SaNsK11** [EddieHubCommunity/LinkFree#123]
We should add a toggle for users to switch between dark and light mode.

**Comment by rohan-kulkarni-25** [comment]
Yes that can be done !! Thanks for idea @SaNsK11

**Comment by spy-1234** [comment]
I want to do the issue.

**Comment by RagibAjmal** [comment]
@spy-1234  Are you working  on this  issue ?
If not can I work on this issue

**Comment by RagibAjmal** [comment]
@SaNsK11 I woulld like to work on this can you assign this to me

**Comment by ZaidKhan2002** [comment]
I would like to work on this issue. Can I work?

**Comment by SaNsK11** [comment]
@RagibAjmal sure go ahead.

**Comment by Shivansh-yadav13** [comment]
I would also like to work on this.

**Comment by Vyvy-vi** [comment]
Hey, @spy-1234 and @RagibAjmal and @Shivansh-yadav13!
Has any one of you started working on this?

**Comment by Shivansh-yadav13** [comment]
> Hey, @spy-1234 and @RagibAjmal and @Shivansh-yadav13!
> Has any one of you started working on this?

Yes
