### ISSUE TITLE
[DOCS] package-lock.json changes

### ISSUE THREAD

**Issue by ezinneanne** [EddieHubCommunity/LinkFree#1244]
### Description

**There should be information concerning the package-lock.json.** 
**The modification in the package-lock.json is automatic, I think users should be informed to revert the changes before creating a pull request.**
**Maybe not everyone encounters it but for those who do, I think they should be informed on time.**

### Screenshots

![My own case](https://user-images.githubusercontent.com/79814820/164910861-730681d0-57d2-4e5d-94b3-5d4cc872674b.png)
**This is in my own case**

![Another User](https://user-images.githubusercontent.com/79814820/164910885-c078a1be-759b-4b0a-a466-28df309d015b.png)
**This is another user**

![Another User](https://user-images.githubusercontent.com/79814820/164910976-8da1a716-ed6d-4e30-89a6-3e5e438af3eb.png)
**This is another user too**

### Additional information

**The changes in the package-lock.json are automatic**
**There should be information about it in the README.MD file**

**Comment by schmelto** [comment]
https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md
In the point 8 there is a warning that package lock json should not be committed but I think this can be easily not seen

**Comment by emmalearnscode** [comment]
Yes, the warning is already there but how to make it more visible?

**Comment by donmarvex** [comment]
Should it be explicitly stated that users should **_untrack_** the **package-lock.json** file before pushing changes to the repo?
This should prevent maintainers from having to remind users about this, avoid repetition essentially.

Would that serve the purpose? Since point 8 in the docs already pretty much informs everyone about this. I also believe it's the duty of every contributor to **_unconditionally_** follow all guidelines as required.

**Comment by donmarvex** [comment]
> Yes, the warning is already there but how to make it more visible?

Perhaps after running npm install, contributors should be required to immediately untrack changes made to the package.json and package-lock.json files?

This could be done with one line of code:

```Git
git rm --cached package-lock.json
```

The implication of this would be to include it in the Installation Steps after step 4.
4. _Install dependencies with npm install_
5.  In the CLI, run 
```Git
git rm --cached package-lock.json
```
This should make it more visible should it be implemented.

**Comment by donmarvex** [comment]
> Should it be explicitly stated that users should **_untrack_** the **package-lock.json** file before pushing changes to the repo? This should prevent maintainers from having to remind users about this, avoid repetition essentially.
> 
> Would that serve the purpose? Since point 8 in the docs already pretty much informs everyone about this. I also believe it's the duty of every contributor to **_unconditionally_** follow all guidelines as required.

Untracking the file will always prevent any changes or modifications to be staged. Although, contributors will still have to avoid using "git add" or "git add ."

> Yes, the warning is already there but how to make it more visible?

I think indicating contributors should untrack the file immediately after running _npm install_ in step 4 of **_Installation Steps_** in **_README.md_** should solve this and in addition include this notice/caution ⚠️ among the bullet points in the _**How to Contribute**_ section of **_CONTRIBUTING.md_**. So every new contributor sees this before going through the steps and also come across it again in step 8.

**Comment by ezinneanne** [comment]
> > Should it be explicitly stated that users should **_untrack_** the **package-lock.json** file before pushing changes to the repo? This should prevent maintainers from having to remind users about this, avoid repetition essentially.
> > Would that serve the purpose? Since point 8 in the docs already pretty much informs everyone about this. I also believe it's the duty of every contributor to **_unconditionally_** follow all guidelines as required.
> 
> Untracking the file will always prevent any changes or modifications to be staged. Although, contributors will still have to avoid using "git add" or "git add ."
> 
> > Yes, the warning is already there but how to make it more visible?
> 
> I think indicating contributors should untrack the file immediately after running _npm install_ in step 4 of **_Installation Steps_** in **_README.md_** should solve this and in addition include this notice/caution ⚠️ among the bullet points in the _**How to Contribute**_ section of **_CONTRIBUTING.md_**. So every new contributor sees this before going through the steps and also come across it again in step 8.

Yes I agree

**Comment by mylonjones** [comment]
Why not add package-lock.json in the .gitignore file?

**Comment by ezinneanne** [comment]
> Why not add package-lock.json in the .gitignore file?

This is a good idea, can it be done

**Comment by donmarvex** [comment]
> > > Why not add package-lock.json in the .gitignore file?
> > 
> > This is a good idea, can it be done
> 
> I think it can be done, but package-lock.json would have to be removed from git so it wouldn't be tracked.

Also it's important for every contributor to have the exact dependency trees replicated from `package-lock.json` anytime `npm install` is run.

Adding it to `.gitignore` would not automatically stop the file from being tracked, so the reason why any changes to the lock file should not be committed.

**Comment by emmalearnscode** [comment]
It’s not recommended to add package-lock to gitignore. However, I’ve just been reading that using ‘npm ci’ instead of ‘npm I’ can prevent the problem. But that would also require that people read the instructions carefully, which seems to be the main problem here.

**Comment by eddiejaoude** [comment]
We have improved the documentation so people should not get this issue anymore
