### ISSUE TITLE
[FEATURE] references/links to external resources to support download & using LinkFree

### ISSUE THREAD

**Issue by goobric** [EddieHubCommunity/LinkFree#1245]
### Description

Reference to external links to resources, to support the new user to download and install LinkFree

### Additional information

Here is a file I have created. Please adjust/amend as necessary
[linkfree.md](https://github.com/EddieHubCommunity/LinkFree/files/8550341/linkfree.md)
.

**Comment by Jai-Solania-29** [comment]
I would love to work on this issue. Can you please guide me on how to get started ?

**Comment by eddiejaoude** [comment]
We have new documentation part of the web app itself, please have a look and let's know what is missing and raise specific issues for anything
https://linkfree.eddiehub.io/docs
