### ISSUE TITLE
[DOCS] Change organization of README.md

### ISSUE THREAD

**Issue by goobric** [EddieHubCommunity/LinkFree#1247]
### Description

Changed the organization of the README.md

### Screenshots

![220425_EHC_LF_readme01](https://user-images.githubusercontent.com/23141638/165100282-db1b1950-295e-4ad6-afaf-0ef1b73befb3.PNG)
![220425_EHC_LF_readme02](https://user-images.githubusercontent.com/23141638/165100289-7eb3f739-34fe-44f0-9070-f1e26f5818a2.PNG)
![220425_EHC_LF_readme03](https://user-images.githubusercontent.com/23141638/165100292-6d97dcac-4490-4fa8-a67b-a6e7c6c8c847.PNG)

### Additional information

Added information, to improve the instructional flow of the process to install/use LinkFree App.
[README.md](https://github.com/EddieHubCommunity/LinkFree/files/8554938/README.md)

**Comment by emmalearnscode** [comment]
Thanks Mikel for your suggestions. Did you want to make a pr for this too?

**Comment by goobric** [comment]
hi Emma,
Is this regarded as an 'issue' that needs to have a pr?
If so, how do I submit a pr for this issue? Do I re-write the linkfree readme file and then submit it?

**Comment by emmalearnscode** [comment]
Hi Mikal, yes you got it, to update the documentation you fork and clone the repository, make a new branch, make changes to the readme.md file in your branch, then commit and push your changes and finally make a pull request. If you want to have a go and get stuck at any stage just let us know

**Comment by oxyli6z** [comment]
Hello everyone, can i be assigned to do it? It will be my first pr and i think its a nice starting point

**Comment by goobric** [comment]
issue is now closed
