### ISSUE TITLE
[FEATURE] Revamp Home Page

### ISSUE THREAD

**Issue by nhcarrigan** [EddieHubCommunity/LinkFree#1264]
### Description

Currently, the home page loads a bunch of avatars from GitHub. If you refresh this, you'll hit rate limits on the avatars.

This rate limit impacts your GitHub use as well - I was locked out of GitHub for about 20 minutes today.

We want to fix this in two steps:

- [x] First, we want to update the home page to no longer display avatars. This should be a relatively quick fix.
- [ ] Our ultimate goal is to stop displaying the full list of profiles on the home page, and instead show a description of what LinkFree is, how to add your profile, and how to share your profile with your friends.

**Comment by eddiejaoude** [comment]
Great idea 👍 I like the idea of having udseful info there!

We could always have it display 10 random ones as examples later, maybe the mods?

**Comment by emmalearnscode** [comment]
If someone wants to do the first issue only should they just remove all the avatars from the chips?

**Comment by nhcarrigan** [comment]
> If someone wants to do the first issue only should they just remove all the avatars from the chips?

Yes, if someone wants to help but isn't ready to write the copy for the new home page, removing the avatars would be the key change.

> And should we split this into 2 issues so that they can be worked on independently?

IMHO, this isn't necessary - given that the goal is to rewrite the homepage. Removing the avatar icons is really just a bandaid to resolve the rate limit issues until we have the time to do the full revamp.

**Comment by ekand** [comment]
I'm going to give this a try.

**Comment by emmalearnscode** [comment]
Question: should we keep the search functionality in some form or remove that too since the profiles will no longer be shown on the main page?

**Comment by eddiejaoude** [comment]
What about a search page which only displays search results rather than all the results at first?

**Comment by emmalearnscode** [comment]
Sounds like a good idea 👍

**Comment by KarlGusta** [comment]
@nhcarrigan 
Our ultimate goal:
1. Show a description of what LinkFree is. This can be a text?
2. How to add a profile. This can be thumbnails of videos on how to add a profile?
3. How to share with a friend. This can be a video too?
