### ISSUE TITLE
[OTHER]

### ISSUE THREAD

**Issue by SohamRatnaparkhi** [EddieHubCommunity/LinkFree#1272]
### What would you like to share?

My pull request (#1271) has been merged but the LinkFree link hasn't been generated yet as to when I go to the link provided in README and join my username to it - it says 'Profile not found'. Am I supposed to do something more or will the LinkFree link be generated in the future? Actually, I am new in this domain and have no idea how it works. 
Thank you!

**Comment by emmalearnscode** [comment]
Hi Soham, thanks for contributing. The website doesn’t get automatically deployed when a profile is added so it can take some time for profiles to appear as the maintainers either have to trigger it manually.

**Comment by SohamRatnaparkhi** [comment]
Okay, thank you!
