### ISSUE TITLE
Add icons to icons.md

### ISSUE THREAD

**Issue by ihtishamKhan** [EddieHubCommunity/LinkFree#1273]
### Description

Add programming language icons to icons.md, I have used a couple of icons in my PR, someone suggested adding an issue so it can be added to the documentation

**Comment by emmalearnscode** [comment]
Can you be specific about which icons you would like added?

**Comment by ihtishamKhan** [comment]
I needed node js and laravel
I already added that in my PR but reverted back, I am waiting so one of my PR accepted

**Comment by emmalearnscode** [comment]
Anyone taking this issue should:
1) import the icons in the components/icons/getIcons file
2) add colour codes for the icons in config/links.json
3) add icons to icon.md

(All the icons should be placed alphabetically)

**Comment by dev-vinny** [comment]
can I add font awesome's node.js and laravel icons in icons.md?

**Comment by emmalearnscode** [comment]
@dev-vinny yes, of course. But please add them to all three files as I mentioned in my previous comment. The font awesome icons can be imported directly from react icons.

**Comment by dev-vinny** [comment]
> @dev-vinny yes, of course. But please add them to all three files as I mentioned in my previous comment. The font awesome icons can be imported directly from react icons.

Hey!
I just added icons and wrote code in mentioned files. Kindly point out my mistakes and corrections I should.

**Comment by Santosh1176** [comment]
> @dev-vinny yes, of course. But please add them to all three files as I mentioned in my previous comment. The font awesome icons can be imported directly from react icons.

Hi, I am trying to add icons to respective files. I have couple of doubts: 
Are these icons from font awesome library?
The url in icons.md doesn't appear to be a FA url. could you please help me on this.
