### ISSUE TITLE
add your youtube link- below the links 

### ISSUE THREAD

**Issue by lavanyayangala** [EddieHubCommunity/LinkFree#128]
###  Youtube link in the link below -follow me on youtube
**#first **pr****
![image](https://user-images.githubusercontent.com/74892542/133124148-436c33a3-3137-481a-ad80-a568381cef8e.png)

**Comment by voidz7** [comment]
![image](https://user-images.githubusercontent.com/62803658/133124383-11077faa-3de2-4539-8ff5-593f00f3aa4f.png)

You can do that using 
![image](https://user-images.githubusercontent.com/62803658/133124537-b229f4c9-ac23-48f7-9046-7f805ba90f72.png)

in your data.json file 🍔

**Comment by lavanyayangala** [comment]
ok thankyou! @voidz7

**Comment by nhcarrigan** [comment]
Closing this as resolved then. 🙂
