### ISSUE TITLE
[DOCS] Update links in readme

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/LinkFree#1297]
**this issue is first timer friendly**

### Description

Links in the readme are outdated due Domain changed. 

New domain https://linkfree.eddiehub.io/

### Screenshots

![175044A1-6F48-4E41-86B6-E59DBFBDD39E](https://user-images.githubusercontent.com/30869493/168552256-4a412055-05c3-4aae-8cc6-c37fb57a5113.jpeg)

**Comment by ioanat94** [comment]
I should be able to tackle this. Can this be assigned to me? :)

**Comment by schmelto** [comment]
sure @ioanat94
