### ISSUE TITLE
Add linkedIn Profile with logo

### ISSUE THREAD

**Issue by smirwtb** [EddieHubCommunity/LinkFree#130]
It will be great to connect more social profiles to follow as per the viewer feasibility

**Comment by kishoreandra** [comment]
I see there is no linkedin icon yet [issue reference](https://github.com/primefaces/primeicons/issues/477)

**Comment by smirwtb** [comment]
Adding Discord/Slack will also be great !!

**Comment by ShlokMohanty** [comment]
adding mailing lists and IRC's will that be helpful or no need of that?

**Comment by Vyvy-vi** [comment]
closing this issue in favour of duplicates - #554 #106

Thanks for contributing to LinkFree!
