### ISSUE TITLE
[FEATURE] Add a skeleton loader to the avatar

### ISSUE THREAD

**Issue by Kemmie001** [EddieHubCommunity/LinkFree#1303]
### Description

While the avatar is still been fetched a skeleton loader CSS can be displayed in place of the avatar text just like when the other details are still been fetched.

### Screenshots

![loading avatar](https://user-images.githubusercontent.com/60070132/168778377-ecbde06c-7f79-4e8c-96c0-91697f3d17df.png)

**Comment by emmalearnscode** [comment]
Thanks for the suggestion. However, we’ve actually decided to remove the image as it’s maxing out the GitHub api rate limit too quickly (there is an open issue for it) and will eventually be replacing the chips entirely on the front page with something else
