### ISSUE TITLE
More Animation and Reactive web elements. 

### ISSUE THREAD

**Issue by Recognizeyourself** [EddieHubCommunity/LinkFree#131]
Some dynamic animation. Whenever user scrolls, click on the link,

**Comment by nhcarrigan** [comment]
Animations are great! However, we need to ensure that any animations we add are not detrimental to the accessibility and UX of the website.

I think this issue would be a great place to discuss planned animations.

**Comment by Recognizeyourself** [comment]
For sure !! Excited for where it will go now!!

**Comment by krishguptadev** [comment]
Why was this issue closed? Let us know if you need any help 🙂

**Comment by Recognizeyourself** [comment]
> Why was this issue closed? Let us know if you need any help 🙂  

I have too much on my plate, that's why. If you want to do something go  ahead.

**Comment by krishguptadev** [comment]
I think we do have some animations like buttons, avatar and links hover 👍 I think this is fixed...

**Comment by CodingSpecies** [comment]
@Recognizeyourself @krishguptadev if this issue doesn't need covering, can it be closed? 
Thanks.
