### ISSUE TITLE
Add showwcase icon in icons.md

### ISSUE THREAD

**Issue by hasnainmakada-99** [EddieHubCommunity/LinkFree#1320]
### What would you like to share?

Please add Showwcase icon, Showwcase is a network built for developers so it will be great if anyone adds the showwcase icon in icons.md we can add the showwcase icon in our linkfree also

If you want to checkout showwcase here is the [link](https://showwcase.com)

**Comment by vikasganiga05** [comment]
Hi @hasnainmakada-99 , There is already an issue was created for the addition of showcase icon #1043 . Thank You :pray:

**Comment by hasnainmakada-99** [comment]
Ok @vikasganiga05 I'm closing this one
