### ISSUE TITLE
[BUG] Graduation Hat icon missing a hyphen

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/LinkFree#1324]
### Description

There are plenty of profiles using the graduation hat without a hyphen (similar to `Graduation Hat`). The correct syntax is `graduation-hat`. This bug should be fixed as fast as possible.

Search for `Graduation Hat` on this repository, and you will find the profiles using the graduation hat wrongly.
If you have any questions/comments or need any help, let us know below! 🙂

### Additional information

We as maintainers should check more carefully the PRs (in this case the profile additions), especially checking the icons, verifying all links work fine, making sure the feature/addition is working fine, and any other suggestions/improvements we can make. :)

**Comment by emmalearnscode** [comment]
Maybe we could add the alternative without the hyphen to the icons file so it doesn’t matter which is used?

**Comment by DenseOriginal** [comment]
I can knock this one out quickly, do you guys have any preference as to what solution should be implemented? Replacing `Graduation Hat` with `graduation-hat`, or adding `Graduation Hat` as valid icon?

**Comment by EmmaDawsonDev** [comment]
I think adding the alternative version to the icons file is better than changing lots of profiles. Feel free to take a look
