### ISSUE TITLE
[FEATURE] Allow hyperlinks in profile's bio section

### ISSUE THREAD

**Issue by vikasganiga05** [EddieHubCommunity/LinkFree#1328]
### Description

It will be a nice feature that allows users to add hyperlinks in their bio section. Users can add links to their previous & current works, contributions, etc. 

### Screenshots

A user profile data, Which has a link in bio :point_down: 
```json
{
  "name": "Eddie Jaoude",
  "type": "personal",
  "bio": "Founder of <a href='https://github.com/EddieHubCommunity'>@EddieHubCommunity</a>",
  "avatar": "https://github.com/eddiejaoude.png",
  "links": ["..."]
}
```

![image](https://user-images.githubusercontent.com/74750414/170501011-9434d32c-9b4d-4b14-bda2-c104b6d1e067.png)

![image](https://user-images.githubusercontent.com/74750414/170500936-6ac92a9a-b689-44ba-b36f-23649341911e.png)

### Additional information

> #### My solution :-

In `src/Components/Profile.js` component, Check `bio` prop contains hyperlinks(anchor tags) using the below regex :point_down: 

```js
const regex = /<a[\s]+([^>]+)>((?:.(?!\<\/a\>))*.)<\/a>/gi;
```

If it does not contain hyperlinks render the `bio`. If it contains the hyperlink render a new component, which converts the string hyperlinks to the anchor tags.

**Comment by emmalearnscode** [comment]
Isn’t this the purpose of all the links and milestones under the bio though?

**Comment by vikasganiga05** [comment]
> Isn’t this the purpose of all the links and milestones under the bio though?

Yes, your right. But in some cases, the user decides to include links in his bio. Then it will render as a text.

**Comment by AakashRaj20** [comment]
> > Isn’t this the purpose of all the links and milestones under the bio though?
> 
> Yes, your right. But in some cases, the user decides to include links in his bio. Then it will render as a text. So, there are two ways we can fix this issue, allowing users to add links in their bio section or preventing them.

Hey is this issue fixed or can I try this?

**Comment by Njong392** [comment]
> > Isn’t this the purpose of all the links and milestones under the bio though?
> 
> Yes, your right. But in some cases, the user decides to include links in his bio. Then it will render as a text. So, there are two ways we can fix this issue, allowing users to add links in their bio section or preventing them.

I think what Emma means is that there is already a section for links below the bio section. Adding hypertext in the bio would maybe seem like redundancy in my opinion...

**Comment by vikasganiga05** [comment]
> 

Yes, should i close this issue?

**Comment by eddiejaoude** [comment]
This is now allowed with the use of markdown in the bio 👍
