### ISSUE TITLE
links property is not optional. generate.js breaks when links are not defined.

### ISSUE THREAD

**Issue by kalijonn** [EddieHubCommunity/LinkFree#1334]
### Description

Hi,

README says that links is optional. But not having 'links' property at all, breaks generate.js. Looks like this is addressed in ProfilePage where we check if 'links' exist before mapping.

This currently doesn't break because there are no profiles without the 'links' property.

Also, upon further inspection, I've noticed that the 'linkCount' property generated is unused. This was implemented as a part of user profiles in home page. However, as a part of #1264 this was removed.

If the idea is to reimplement linkCount, we can keep it while adding an optional flag during generation. If not, we can remove it entirely.

Let me know what you think.

**Comment by SquatCub** [comment]
Hello there, I like your suggestion. I have already notice about that issue and I'd like to work to solve it if possible.

**Comment by kabir0x23** [comment]
This is LinkFree, where we can share our links in one place,
if there will be no links, then why would anyone like to use these apps?

will update the readme.MD
