### ISSUE TITLE
Add personal portofolio website and Newsletter

### ISSUE THREAD

**Issue by smirwtb** [EddieHubCommunity/LinkFree#134]
It will be great if viewers get more about ongoing and developed projects along with the Newsletter (optional) for a regular updates to subscribers.

**Comment by nhcarrigan** [comment]
Having another think about this, I think for the portfolio pages we need a slightly different approach.

The JSON should have a `websites` property (note the plural) which is an **array** of objects in the following structure:

```json
{
 name: "Text to display on button",
 url: "Link to visit on button click"
}
```


Then the front end needs to iterate over this array and generate a button for each object in the array.

This approach will allow us to use custom URLs for multiple things, such as a dev.to link, a profile link, a link to your paypal, whatever relevant links you want to add.

**Comment by ravi-varma-ankam** [comment]
Can I work on this issue for #hacktoberfest?

**Comment by Flolight** [comment]
Aggree indeed that it should something more generic but isn't this already the "links" array?
What would be the difference if not?

**Comment by StarTrooper08** [comment]
Is anyone working on this issue?

**Comment by CodingSpecies** [comment]
Isn't this issue sorted, as we are now able to add links for our own websites and portfolios:
![image](https://user-images.githubusercontent.com/70807500/143778781-515f9e5d-29dc-49b6-bf6d-046e1ff32ba4.png)
I have added my own website:
![image](https://user-images.githubusercontent.com/70807500/143778792-42e13015-8412-471b-88b2-94b8e94dc9db.png)

**Comment by Vyvy-vi** [comment]
I think it is, however do we need anything custom for newsletter links?

**Comment by krishguptadev** [comment]
the envelope icon works for newsletters and emails.

![image](https://user-images.githubusercontent.com/91655303/143802765-e87eedee-7a77-4a1c-97a1-761c59c2b1d7.png)

**Comment by Vyvy-vi** [comment]
Looks fine...
I guess we can close the issue for now


Thanks for contributing to LinkFree!
