### ISSUE TITLE
[FEATURE] Consistency in profile names

### ISSUE THREAD

**Issue by KarlGusta** [EddieHubCommunity/LinkFree#1343]
### Description

- Names appearing on the profile need to be consistent. For instance, John Doe not JOHN DOE or J.D or j123.
- Also, it should be two names instead of one e.g. Eddie Jaoude instead of Jaoude.

**Comment by emmalearnscode** [comment]
I think this is down to personal preference. Not everyone is comfortable sharing all of their names for example.
