### ISSUE TITLE
Increase `scale` of buttons on hover

### ISSUE THREAD

**Issue by guptasajal411** [EddieHubCommunity/LinkFree#135]
When hovered, the links will get a little bigger which looks cool and interactive as well! 💥 
If you like the idea, can you please assign me this issue, I'd love to work on this 🥳 

Check out this GIF: 
![linkfree-hover](https://user-images.githubusercontent.com/70312106/133126728-ae25d709-3f1b-4659-9402-ab720aad6626.gif)

**Comment by guptasajal411** [comment]
Done with the changes, looks like this:
![linkfree-hover](https://user-images.githubusercontent.com/70312106/133126728-ae25d709-3f1b-4659-9402-ab720aad6626.gif)

**Comment by rohan-kulkarni-25** [comment]
> Done with the changes, looks like this:
> ![linkfree-hover](https://user-images.githubusercontent.com/70312106/133126728-ae25d709-3f1b-4659-9402-ab720aad6626.gif)

Yes nice idea but will like to suggest you something try to make a change that if one button is scaled then other should not have impact of scale on it

**Comment by guptasajal411** [comment]
Pull Request: https://github.com/EddieHubCommunity/LinkFree/pull/140
