### ISSUE TITLE
[DOCS] Where is the table of icons in the README?

### ISSUE THREAD

**Issue by CodingSpecies** [EddieHubCommunity/LinkFree#1352]
### Description

I have not been on LinkFree repo for a while, but now when I try to see where the table of icons you could add (the github icon, the twitter and codewars etc.) I can not seem to find it. Has it moved somewhere else? I would like to know where it is so I could update my profile. Thank you.

**Comment by emmalearnscode** [comment]
There is a link to available icons in the readme file, but for quick access you can find the table in the icons.md file.

**Comment by CodingSpecies** [comment]
Thank you @emmalearnscode .
