### ISSUE TITLE
add labelling to guide where profiles are 

### ISSUE THREAD

**Issue by CodingSpecies** [EddieHubCommunity/LinkFree#1353]
### What would you like to share?

I don't know if it is in process, but on the website when I tried to find where the list of profiles are, and it wasn't clearly labelled to be where the magnifying glass is. Maybe there should be a text label saying `Search Profiles`: Maybe it should go where the red highlight is on the screenshot below:
![image](https://user-images.githubusercontent.com/70807500/171485076-899ae0b7-b0ac-43ca-8591-019284e14896.png)

Thank you.

**Comment by CodingSpecies** [comment]
@skirianov yeah, the point of LinkFree is not only to have your own profile, but to explore and find out about others profiles too. But when I checked the website, a home page had been added, and had replaced the list of profiles. After looking around, the search icon took me to the profiles.

However, I do not think that the search icon displays/means : "see the profiles here".

**Comment by skirianov** [comment]
Two things I can think of here: 

- we can implement something similar https://codepen.io/MarcoGuglielmelli/pen/bGxJee and in the expanded field to add the button "See all users" (idea is, that I don't see a point to see the list of **all** users especially if it will grow to thousands)
- replace the search Icon with other more self-descriptive icon and keep same functionality

**Comment by CodingSpecies** [comment]
Maybe we should have a more self explanatory icon to display the profiles.

**Comment by 03amir** [comment]
@CodingSpecies  can I work on this issue?

**Comment by CodingSpecies** [comment]
@03amir yes feel free to work on this! Thank you.

**Comment by Kartik2220** [comment]
> @03amir yes feel free to work on this! Thank you.

in which file i have to change for this issue?

**Comment by eddiejaoude** [comment]
Thank you 👍 Great collaboration

This has now be completed
