### ISSUE TITLE
What is single user mode?

### ISSUE THREAD

**Issue by CodingSpecies** [EddieHubCommunity/LinkFree#1354]
### What would you like to share?

Please can someone explain to me what the single user mode will do because I don't know whether I should add my username, but first I would like to know what it will do. Thank you.

![image](https://user-images.githubusercontent.com/70807500/171485504-d04a2eff-08d9-45ad-bb5c-a54be64e1664.png)

**Comment by schmelto** [comment]
If you want to host linkfree by yourself and only display your portfolio I'm single user mode is the way to go

**Comment by CodingSpecies** [comment]
Thank you for clarifying @schmelto .

**Comment by schmelto** [comment]
> Thank you for clarifying @schmelto .

If the documentation is not clear maybe we have to adjust it.

**Comment by CodingSpecies** [comment]
Maybe we should put what you explained to me into the documentation, and it would be clearer:

> If you want to host linkfree by yourself and only display your portfolio, single user mode is the way to go, this means only your profile will be available on your linkfree page.
