### ISSUE TITLE
[FEATURE] Add OpenGraph meta information to main app

### ISSUE THREAD

**Issue by skirianov** [EddieHubCommunity/LinkFree#1366]
### Description

It would be great to add OpenGraph protocol (https://ogp.me/) to the existing app, so we can have beautiful cards when we share on Twitter / Facebook/ etc. 

Unfortunately, we can not have it personal for every user, because of Client-Side Rendering. 

But at least we can have generic OG meta information. 

### Screenshots

<img width="438" alt="Screenshot 2022-06-07 at 21 02 06" src="https://user-images.githubusercontent.com/74229951/172471910-6557492b-d67b-48b3-8aae-8551878d0487.png">

Current State

**Comment by KarlGusta** [comment]
Interesting idea to have it show more info on the card. I have tried it on Telegram too. I think it is something worth working on.
