### ISSUE TITLE
Aligning the number partially on top of the profile picture

### ISSUE THREAD

**Issue by Nikhil-1503** [EddieHubCommunity/LinkFree#139]
It would look better if the number showing would be partially on top of the profile picture.

**Comment by nhcarrigan** [comment]
![image](https://user-images.githubusercontent.com/63889819/133129747-1397c947-0b59-4b79-bc22-bae58d206962.png)

CSS could be used to position this so it has a wee bit of an overlap, akin to the red notification badges you get on mobile.

**Comment by Flolight** [comment]
Nice idea indeed!
I proposed a PR for the following here: https://github.com/EddieHubCommunity/LinkFree/pull/181
<img width="323" alt="image" src="https://user-images.githubusercontent.com/9541039/133286811-d41b8ea6-e065-4586-9d35-f952280d9847.png">
