### ISSUE TITLE
[OTHER] PR merged, Can't see profile

### ISSUE THREAD

**Issue by RakeshSangem** [EddieHubCommunity/LinkFree#1407]
## Yesterday PR merged successfully without any errors

![Screenshot (38)](https://user-images.githubusercontent.com/107752425/175755523-944c22eb-7230-4261-b9c8-97b4215da4c2.png)

## I can't see my profile at https://linkfree.eddiehub.io/search
 Could you take a look at the issue
![Screenshot (39)](https://user-images.githubusercontent.com/107752425/175755626-94ba1d64-b781-48b3-916a-9f092085313b.png)

**Comment by AnshuPathak-88825** [comment]
I think it will available soon it was also happen with me  too now my profile is visible

**Comment by RakeshSangem** [comment]
>  I think it will available soon it was also happen with me  too now my profile is visible 

Does it take some time to update?

**Comment by AnshuPathak-88825** [comment]
yes

**Comment by RakeshSangem** [comment]
My PR was merged 15 hours ago. Does it take this much time to update?

**Comment by AnshuPathak-88825** [comment]
My PR was merged 3 days ago now i can access my profile

**Comment by eddiejaoude** [comment]
We try to collect some profiles together then deploy.

Is the documentation not clear, can we improve this?

**Comment by AnshuPathak-88825** [comment]
![Screenshot from 2022-06-25 16-56-44](https://user-images.githubusercontent.com/78332454/175771485-d53438ca-5894-44cf-982b-ec0a9d531d50.png)
yes I had same query 
@eddiejaoude can I raise issue to improve readme file ?

**Comment by eddiejaoude** [comment]
Sure 👍 

We currently have this in the docs
> Note: after your PR is merged, the project still needs to be deployed for your profile to be displayed

**Comment by RakeshSangem** [comment]
> then deploy.
> 
> Is the documentation not clear, can we improve

Yeah! Thanks for letting me know Eddie!

I went back to the documentation and read about it. 

My suggestion:

**Note: your profile might not be displayed after your PR is merged because we collect some profiles together and deploy the project.**

Make it highlight to grab attention

**Comment by eddiejaoude** [comment]
Sure, submit a PR and one of the maintainers can review it 👍 

Please reference this issue in the PR

**Comment by AnshuPathak-88825** [comment]
Done pls merge it @eddiejaoude
