### ISSUE TITLE
[improve]: add error handling and loading states 

### ISSUE THREAD

**Issue by anuraghazra** [EddieHubCommunity/LinkFree#141]
Currently there is no error handling logic in the fetch requests and no loading states in the application. 

TODO: 
- Add catch clauses in fetch
- Add loading state to render a progressbar

**Comment by toth2000** [comment]
Can I work on this issue?

**Comment by FayasNoushad** [comment]
> Can I work on this issue?

Ofcourse. Owner saying contribution first collaboration second. 👍
