### ISSUE TITLE
[README] adding gitpod directions to the INSTALLATION STEPS section

### ISSUE THREAD

**Issue by AshMudra** [EddieHubCommunity/LinkFree#1417]
### Description

At the bottom of the Installation Steps section is a line that says "Alternatively, skip all the steps by using gitpod."

I attempted to install and use Gitpod. It seemed to be working but I got confused when trying to commit my changes. So I closed the Gitpod session and started over to make my change in Github.

I'm not sure what the steps are, or how to successfully bridge the gitpod use, but I believe it could be clearer. I can give it a go as I learn more about gitpod.

### Screenshots

![installsteps](https://user-images.githubusercontent.com/91898827/176568963-5deb2fee-e56a-4eb9-89f9-16b1d5fbb5f3.png)

### Additional information

Would love to know other's thoughts!

**Comment by emmalearnscode** [comment]
I agree, the instructions could definitely be made clearer

**Comment by eddiejaoude** [comment]
We have new documentation https://linkfree.eddiehub.io/docs

I will close this issue and please raise a new issue if anything missing from the docs
