### ISSUE TITLE
Mobile view error when text is to long

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/LinkFree#1418]
### Description

When viewing for example eddies profile the website looks like in the screenshot below. In my opinion it is because of the long text for the yt channel. 

### Screenshots

![2F4AB263-8912-46AB-8E09-7CE7D1073820](https://user-images.githubusercontent.com/30869493/176618749-5342d7f3-7d7c-4e9e-920e-332c1f507666.jpeg)

### Additional information

Device: iPhone 13 mini
Browser: Safari latest version

**Comment by thevinitgupta** [comment]
I would like to work on this issue @eddiejaoude
