### ISSUE TITLE
[FEATURE] Profile Hover Effect

### ISSUE THREAD

**Issue by Shivam-Katare** [EddieHubCommunity/LinkFree#1432]
### Description

It would be great if we hover on "LinkFree" profiles and we can see their profile picture too.  This feature will help us to find the profile easily that we are looking for and it will enhance the UI of the project too. 

### Screenshots

![Untitled design](https://user-images.githubusercontent.com/91705825/177004519-c6b2fda8-5a08-479b-a3a6-12291ddd0958.png)

It is the sample screenshot. We can make something like this. The profile picture is only visible when someone hovers over the profile.

**Comment by emmalearnscode** [comment]
We removed the profile pictures because they were causing us to hit the github API rate limit too often. If we had this kind of functionality on hover then we would start making lots of unnecessary API calls again.

**Comment by Shivam-Katare** [comment]
> We removed the profile pictures because they were causing us to hit the GitHub API rate limit too often. If we had this kind of functionality on hover then we would start making lots of unnecessary API calls again.

Okay, I had one more thing on my mind that is it would be good if we put "Linkfree Profile Details" into an interactive eye-catching card? We can also add some hovering effects too. I am talking about the user's name, profile picture, and social links.

**Comment by sanyamgandhak** [comment]
Hi there , Assign it to me

**Comment by eddiejaoude** [comment]
This has now been added back but only shows results after 3 search characters are added
