### ISSUE TITLE
Add visually hidden info to learn more buttons

### ISSUE THREAD

**Issue by EmmaDawsonDev** [EddieHubCommunity/LinkFree#1438]
### What would you like to share?

On the profile pages with milestones, there are several buttons/links which say learn more. This is not very helpful to screen reader users. We could add some visually hidden text so that screen reader users get more context about what they will learn more about when clicking on the button.

**Comment by 87prashant** [comment]
I think possible the solution could be:
- Adding extra brief text with lean more
  e.g. Learn more (visit Youtube channel/Github profile)

@emmalearnscode could you suggest other effective ways to achieve this.

**Comment by msabirz** [comment]
There can be couple of things:
1. Add small tooltip popover for short info
2.  Small one liner beside the button element.

**Comment by Yoshemith** [comment]
Hi everyone 🙋🏻‍♂️, I'm a newcomer trying to contribute in this OSS project and I was thinking if i can work on this issue. I'm planning on adding a small tooltip popover just as @msabirz suggested with the extra info as @87prashant mentioned.

**Comment by emmalearnscode** [comment]
Unfortunately a tooltip pop up will only make this more inaccessible.

**Comment by msabirz** [comment]
Another way is we can have small 'i' icon which will have toggle functionality and on click it will show small desp.

**Comment by Yoshemith** [comment]
Like @msabirz mentioned, that could be another way to do it. What I was doing was something like this, look:

<img width="599" alt="Screen Shot 2022-07-08 at 13 09 04" src="https://user-images.githubusercontent.com/87047389/178047385-1cc83a28-1052-477f-aeaf-edca9807a475.png">

Basically a small one liner describing where we're going (like on hover). But another solution would be something like this:

<img width="855" alt="Screen Shot 2022-07-08 at 13 20 27" src="https://user-images.githubusercontent.com/87047389/178048772-8f1e88cb-f045-4521-98ed-aad4a924b85a.png">

Or wouldn't it be better a "Check it out here" button instead of "Learn more"?

<img width="385" alt="Screen Shot 2022-07-08 at 13 23 25" src="https://user-images.githubusercontent.com/87047389/178049197-b5ddbfc4-dc58-4ac9-84c0-60efbee474eb.png">

What do you think @emmalearnscode?

**Comment by emmalearnscode** [comment]
Ideally the buttons will say where the link leads as in the second image. But I’m not sure if we have something in the data that could be used already as the text. 

‘Check it out here’ is no more useful than ‘learn more’. Imagine you cannot see the page and are cycling through a list of links. 5 links all titled ‘check it out here’ mean nothing without the visual context clues, just as ‘learn more’ needs visual context to be understood.

**Comment by Yoshemith** [comment]
Ohh, I finally see what you mean. Reading some documentation of [Prime React](https://www.primefaces.org/primereact/button/) it seems that right now there is no accessibility support for the buttons. But I was thinking in using just a normal button and using the attribute `aria-label` for accessibility and work from there.

Regarding the text, I didn't find something in the data to use it as the displayed text. What I did was, basically doing something similar as the `GetIcons.js` component passing the icon name and with a switch function returned the required text, e.g. if the icon is github the displayed text would be "Learn more visiting the Github profile", etc.

Let me know what you think @emmalearnscode.

**Comment by Yoshemith** [comment]
So far, what I've been doing is creating a normal button (no libraries) and making the UI of the button as similar as the prior button (primereact/button). Check it out:

<img width="412" alt="Screen Shot 2022-07-08 at 15 10 47" src="https://user-images.githubusercontent.com/87047389/178064087-a57e4cfb-b2ee-4bc2-9aec-080616993c91.png">

How it looks like:

<img width="368" alt="Screen Shot 2022-07-08 at 15 10 59" src="https://user-images.githubusercontent.com/87047389/178064143-607ae160-c7ed-4d7d-94c4-42f7e29cca8f.png">

I'd like to know if I'm on the right track or if you have more suggestions @emmalearnscode

**Comment by emmalearnscode** [comment]
> So far, what I've been doing is creating a normal button (no libraries) and making the UI of the button as similar as the prior button (primereact/button). Check it out:
> 
> <img alt="Screen Shot 2022-07-08 at 15 10 47" width="412" src="https://user-images.githubusercontent.com/87047389/178064087-a57e4cfb-b2ee-4bc2-9aec-080616993c91.png">
> 
> How it looks like:
> 
> <img alt="Screen Shot 2022-07-08 at 15 10 59" width="368" src="https://user-images.githubusercontent.com/87047389/178064143-607ae160-c7ed-4d7d-94c4-42f7e29cca8f.png">
> 
> I'd like to know if I'm on the right track or if you have more suggestions @emmalearnscode

It’s an interesting idea but I think we will run into trouble with things like dollar, globe, book etc as that won’t make sense.


 We are considering moving away from prime react although I think it should be possible to add an aria label. we should also be using links not buttons. 
 
This is a tricky little problem, let’s keep thinking and discussing

**Comment by Yoshemith** [comment]
You're right, it is possible to use `aria-label` attribute of the button just as it was before (my bad, didn't try that til' now). Now, I'm thinking of using a default text for things like dollar, globe, book, etc. The default text could be "Learn more on this website". It's just a thought, I'd like to know what you think.

**Comment by eddiejaoude** [comment]
hey everyone, apologies for my slow reply. The new version of the LinkFree project is out now using NextJS and TailWind

Now the whole block is clickable, not sure if this is better? I will close this issue and we can create a new one that is more relevant to the latest app version
