### ISSUE TITLE
Links need distiguishing

### ISSUE THREAD

**Issue by emmalearnscode** [EddieHubCommunity/LinkFree#1439]
### What would you like to share?

On the homepage there are two text links: Eddie Jaoude and instructions. However, they are not visually marked as links aside from color which means people who don't perceive color can't tell that they are links. The links should stand out from the rest of the text either with underlines or bold text or some other styling that indicates that these are clickable.

**Comment by 87prashant** [comment]
Yes, a little bit of focus needs to find out that they are links for normal people too.
