### ISSUE TITLE
Add Responsive Card type hover effect in the home where all member's profile are showing...

### ISSUE THREAD

**Issue by itsarghyadas** [EddieHubCommunity/LinkFree#144]
So,
     1. When we hover in the main home page where all member's profile are showing...
     2. The pointed profile will hover with responsive card hover effect with the profile photo and the username.

**Comment by SriSatyaT** [comment]
@itsarghyadas I want to give it a shot for this issue.

**Comment by krishguptadev** [comment]
Hey if this issue hasn't been fixed yet, I would like to know more and see If I can help.
