### ISSUE TITLE
Links flash red when clicked

### ISSUE THREAD

**Issue by EmmaDawsonDev** [EddieHubCommunity/LinkFree#1440]
### Description

The links seem to have an active state which briefly turns them red when clicked which doesn't really fit with the rest of the design. The color should be removed.

**Comment by PeroHub** [comment]
> ### Description
> The links seem to have an active state which briefly turns them red when clicked which doesn't really fit with the rest of the design. The color should be removed.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

Yes, the color flashes very fast... I'll fix this
