### ISSUE TITLE
Linter is unable to find cypress global variable

### ISSUE THREAD

**Issue by cperezcapote** [EddieHubCommunity/LinkFree#1453]
### Description

When I edit file `cypress/integration/common/actions.js`, I get the `eslint` error showed on the screenshot.

This issue is preventing me from actually commit my changes because of the `pre-commit` instructions.

I also noticed that the `cypress` folder is not included on the `lint` command in `package.json`, I think it would be a nice addition.

### Screenshots

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/35213792/177442883-eb3882ff-ce2c-4de5-952d-7ed6e961f3e0.png">

### Additional information

After some investigation I found https://stackoverflow.com/a/60154342/5170922. It suggests that we should include [eslint-plugin-cypress](https://github.com/cypress-io/eslint-plugin-cypress) to solve this issue.

**Comment by eddiejaoude** [comment]
This is great, thank you 👍
