### ISSUE TITLE
[FEATURE] Add revealing animations to links

### ISSUE THREAD

**Issue by Aayushd18** [EddieHubCommunity/LinkFree#1455]
### Description

We can add some animations to links when we open a profile. It will enhance the look of the page.

> react-awesome-reveal is a npm package which provides one line code to add animations.

### Screenshots

![Slide animation](https://media.giphy.com/media/B8K0335IwQwakORVhq/giphy.gif)

### Additional information

[Link to package](https://www.npmjs.com/package/react-awesome-reveal).

I would like to work on it.

**Comment by Aayushd18** [comment]
> Sounds interesting. Can it be turned on and off for each profile per user preference?

One way is to have a preference variable in the user's json file because I only see the user's data is saved in that file only. We can retrieve the preference from there and set the animations on/off. If you have any suggestions, it will be great to know.

**Comment by Aayushd18** [comment]
@emmalearnscode your thoughts about it.

**Comment by vaib1343** [comment]
Hey, I can work on this issue.

**Comment by Aayushd18** [comment]
> Hey, I can work on this issue.thanks

Hey I had some progress on this, you can enhance it further if you want. I have made a pull request, you can work on it from there.

**Comment by eddiejaoude** [comment]
this has now been merged
