### ISSUE TITLE
Fails to Compile with react-scripts 4.0.3

### ISSUE THREAD

**Issue by aditya172926** [EddieHubCommunity/LinkFree#1465]
### Description

The LinkFree site is failing to compile with `npm start` when using `react-scripts=="^4.0.3"`, installed with the command `npm install` on package.json

When the version of `react-scripts` is downgraded to 4.0.1, the compilation works just fine.

### Screenshots

<img width="960" alt="compile_fail" src="https://user-images.githubusercontent.com/54861484/178056150-51e4d3b7-e615-4597-8e40-5ebbaf33f74a.PNG">

**Comment by eddiejaoude** [comment]
Thank you for raising the issue 👍 , I now see more people having the issue. 

I have updated the major version and push to branch `update-deps` for people to test

```
➜  LinkFree.react git:(main) ✗ npm list react-scripts
linkfree@0.70.1 /Users/ej/Downloads/repos/EddieHub/LinkFree.react
└── react-scripts@5.0.1
```
