### ISSUE TITLE
[FEATURE] Migrate to Next.js

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/LinkFree#1470]
### Description

By moving to next.js we could add and use several features by benefiting from the server component: 

1. Use SSR to prerender our pages on the server for performance optimization
1. Maybe use [ISR](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration) to dynamically re-render the index page to highlight a different profile every day on the index page
1. Use a database connection to store how often a page got clicked
1. Don't use PrimeReact, but use Tailwind for creating our custom components

wdyt @eddiejaoude 

Things like adding Cypress and/or other addition could come in future PRs. I think for us it's important to migrate with an MVP first.

We could use a `staging` branch, similar on how we did it for the API rewrite, to have things a bit more atomic, and not just a single big-bang

## TO DO

- [ ] by default hide stats and enable with json config

**Comment by eddiejaoude** [comment]
Great ideas! 👍

**Comment by Cahllagerfeld** [comment]
When displaying the amount of clicks, we can't use Static-Side-Geneartion, as this data needs to be dynamic and can't be prefetched

**Comment by JealousGx** [comment]
Hey @eddiejaoude, is this migration open source as well? Means can I, and anybody contribute to the nextjs branch?

**Comment by eddiejaoude** [comment]
hi @JealousGx , yes it is, here is the (draft) work in progress Pull Request https://github.com/EddieHubCommunity/LinkFree/pull/1471

**Comment by JealousGx** [comment]
@eddiejaoude Mind providing MongoDB URI for the db connection? The connection is null and thus the data...

**Comment by eddiejaoude** [comment]
> Mind providing MongoDB URI for the db connection

I just pushed to this PR the updated the docs in the README and added an `.env.example` file where you can copy this file to `.env` (update the connection as required)

Thank you for the feedback 👍

**Comment by MadhuSaini22** [comment]
@eddiejaoude Thanks for running this mind blowing community :)

**Comment by eddiejaoude** [comment]
Thank you @MadhuSaini22 for the great feedback ❤️ To be honest, the mods, ambassadors and members run the community and they are amazing 🔥

**Comment by joshi-kaushal** [comment]
I would love to help with this issue. I glanced through https://github.com/EddieHubCommunity/LinkFree/pull/1471 and the [nextjs](https://github.com/EddieHubCommunity/LinkFree/tree/nextjs) branch. Is there anything that I can do here?

**Comment by eddiejaoude** [comment]
hey @joshi-kaushal we have a lot to do, I need to create some issues for this, but for now, here are some ideas

- search codebase in `nextjs` branch for `@TODO`
- improve documentation to get project running with mongo db (gitpod config probably needs updating also)
- fix failing tests
- check for missing features (main features ones only, as I am keen to deploy this soon)
