### ISSUE TITLE
bug: Back arrow navigates to wrong page

### ISSUE THREAD

**Issue by emmalearnscode** [EddieHubCommunity/LinkFree#1478]
### Description

If you search for a profile from the search page, choose a profile page then click the arrow icon in the menu on the profile page to back it takes you directly to the home page and not back to the search page.

**Comment by andrewkykoo** [comment]
@emmalearnscode Hi! Can I work on this issue? Thanks!

**Comment by emmalearnscode** [comment]
Sure!
