### ISSUE TITLE
Border Radius 

### ISSUE THREAD

**Issue by ShorunTech** [EddieHubCommunity/LinkFree#1480]
### Description

Adding Border Radius to the Milestone Card holder.

### Screenshots

![Screenshot (41)](https://user-images.githubusercontent.com/61280687/178345600-50dceb26-f74e-4300-9416-c1167a9c1ca5.png)

**Comment by andrewkykoo** [comment]
Hi! I would like to work on this issue. Thanks!

**Comment by vaib1343** [comment]
Hi can I work on issue. If nobody is working on it.

**Comment by kiritocode1** [comment]
hey Can i Work on this Issue , ill finish it asap ,

**Comment by jasham** [comment]
@ShorunTech if this issue is not fixed can you please assign it to me.

**Comment by eddiejaoude** [comment]
this has now been merged
