### ISSUE TITLE
[DOCS] Add workflow diagrams and description

### ISSUE THREAD

**Issue by ArkaprabhaChakraborty** [EddieHubCommunity/LinkFree#1497]
> yep at the high level, so not the individual workflow, but a diagram/docs covering all the workflows of the project and maybe the event triggers - we could use mermaid as now it is supportive natively by GitHub https://mermaid-js.github.io/mermaid/#/

### Description

As per the discussion on EddieHub discord, we can add the documentation about Linkfree's github actions. Overall workflow documentation would help users/contributors find out how each event is triggered during the deployment and release phases.

**Comment by ArkaprabhaChakraborty** [comment]
Can I be assigned this?

**Comment by eddiejaoude** [comment]
sure

**Comment by rudrakshkarpe** [comment]
I'd like to work on this issue if it's not don yet?

**Comment by ArkaprabhaChakraborty** [comment]
Well, I have been a bit busy lately, sorry  :). You can take it tho as :)

**Comment by schmelto** [comment]
> I'd like to work on this issue if it's not don yet?

Sure @rudrakshkarpe

**Comment by MadhuSaini22** [comment]
@rudrakshkarpe Are you working on this issue?

**Comment by eddiejaoude** [comment]
This issue doesn't seem to be working on, so we can reassign it

**Comment by ChayanSD** [comment]
I am complete beginner in opesource.
Can anyone give me some resource . I want contribute in thsi project.

**Comment by AmitRaj0704** [comment]
Same as @ChayanSD said, I'm a newbie too and eager to learn. So if anyone can help here then that would be great!

**Comment by eddiejaoude** [comment]
I am going to close this because things are changing fast on the automation side and this will get out of date very quickly

We can revisit this in the future
