### ISSUE TITLE
[OTHER] Optimize Images

### ISSUE THREAD

**Issue by loftwah** [EddieHubCommunity/LinkFree#1524]
### What would you like to share?

ImgBot runs on my account and I spotted some optimization opportunities in LinkFree. You can check them out [here](https://github.com/loftwah/LinkFree/pull/2), I am pretty sure that ImgBot is free for open source projects. It will give you a total reduction in image size of 17%

**Comment by RayanAbid** [comment]
Hi. So do you mean that we need to replace the images that are currently not optimized?

**Comment by loftwah** [comment]
They are in the LinkFree repository, I have imgbot setup by default and it picked it up when I made a fork. I thought I should raise an issue to let everyone know that there is an opportunity to reduce the current image sizes if they would like to. It doesn't have to be done by a bot, [Squoosh](https://squoosh.app/) is a free web app that will do the same thing. It will increase loading times for those images by about 15%.

**Comment by MadhuSaini22** [comment]
Does anyone is working on his issue?

**Comment by eddiejaoude** [comment]
Now we have NextJS it has image optimisation so I don't think this is needed anymore - also we don't have many images in the project
