### ISSUE TITLE
The profile hover does not work properly on mobile screens.

### ISSUE THREAD

**Issue by code-with-onye** [EddieHubCommunity/LinkFree#1570]
### Description

When you hover over a profile card on a mobile device, the background turns white, rendering the text invisible.

### Screenshots

![ezgif com-gif-maker](https://user-images.githubusercontent.com/85189857/182911691-10069f67-356b-49a4-a08b-f7d157549b56.gif)

**Comment by RayanAbid** [comment]
Hi, can you please share a screenshot?  I would love to work on this issue. If it can be assigned to me. 

Are you talking about this? Seems to be working fine.

<img width="392" alt="Screen Shot 2022-08-04 at 10 54 52 PM" src="https://user-images.githubusercontent.com/68749736/182918216-74bfd200-ffd4-4700-b5a0-8c9b5aa97d1a.png">

**Comment by RayanAbid** [comment]
Well, I tried to solve it. But we seem to be using onMouseOver and onMouseOut that's why it's behaving like that on mobile.

**Comment by code-with-onye** [comment]
yea, i noticed that also

**Comment by code-with-onye** [comment]
There has to be a better way, in my opinion. is not in fact user friendly

**Comment by EmmaDawsonDev** [comment]
We’re in the process of migrating from prime react css to tailwind. Hopefully it’s something that will be solved by that.

**Comment by RayanAbid** [comment]
CAn I be assigned something in the migration process? I'm familiar with Reactjs and tailwind css. Just something to get me started. Looking to contribute to open source. @EmmaDawsonDev  Thanks.

**Comment by code-with-onye** [comment]
This is fantastic, and I'd love to help with the migration as well.

**Comment by EmmaDawsonDev** [comment]
Feel free to take a look at the nextjs branch. Eddie is working on it so probably best to ask them if there’s anything you can help with or if you notice something in the branch you can make a PR to that branch instead of to main

**Comment by RayanAbid** [comment]
Thanks.

**Comment by code-with-onye** [comment]
Notes, thanks

**Comment by eddiejaoude** [comment]
hey everyone, apologies for my slow reply. The new version of the LinkFree project is out now using NextJS and TailWind

I will close this issue, but please feel free to create a new issue and we can assign it to you
