### ISSUE TITLE
[OTHER] Add RealSollyM Profile

### ISSUE THREAD

**Issue by RealSollyM** [EddieHubCommunity/LinkFree#1589]
### What would you like to share?

I would like to add my profile here on LinkFree, thank you.

**Comment by kumarsonsoff3** [comment]
Hi @RealSollyM, to add your profile to LinkFree, follow the steps given in the [Readme.md](https://github.com/EddieHubCommunity/LinkFree#-prerequisites) file. 
And then, create a PR, including your profile data! Let us know if you need any help with this! :)
