### ISSUE TITLE
feat: Automate the process of adding the data to the data/_list.json file

### ISSUE THREAD

**Issue by Soham041201** [EddieHubCommunity/LinkFree#159]
After adding the links in the data folder, Another extra step is required (adding the avatar and username in data/_link.json file) to show the data on the home page. Is there a way to automate that or add the recently added JSON data to the _link.json file?

![Screenshot from 2021-09-14 10-44-31](https://user-images.githubusercontent.com/79072777/133199032-e3c50b71-cab2-4bea-ad8a-19e11c7aef98.png)

**Comment by schmelto** [comment]
already closed in https://github.com/EddieHubCommunity/LinkFree/pull/168
