### ISSUE TITLE
[FEATURE] Add Showwcase icon to the icons list.

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [EddieHubCommunity/LinkFree#1592]
### Description

**Showwcase** is a professional networking platform for coders to connect and look for new opportunities.
I request to add **showwcase** icon.

### Additional information

Showwcase link : https://www.showwcase.com/

**Comment by SaptarshiSarkar12** [comment]
## I have worked on this issue and made a [PR](https://github.com/EddieHubCommunity/LinkFree/pull/1593)
Please check that out.

**Comment by kumarsonsoff3** [comment]
I'm closing this issue because it is a duplicate issue of #1043. 
As per my knowledge [Vasanti Suthar](https://github.com/vasantisuthar) is already working on this one! You can have a look there at #1043, conversation there might help you in someway!
