### ISSUE TITLE
[FEATURE] Share profile icon need hover effect

### ISSUE THREAD

**Issue by Amyx000** [EddieHubCommunity/LinkFree#1596]
### Description

Share profile icon don't give the feel of a clickable item. It needs some kind of hover effect like increasing its size.

**Comment by PritamSarbajna** [comment]
Hey I'd like to work on it

**Comment by krshkodes** [comment]
Sure @PritamSarbajna!

**Comment by Amyx000** [comment]
I have already made if, check te pull request
https://github.com/EddieHubCommunity/LinkFree/pull/1597

**Comment by krshkodes** [comment]
Oh sorry @Amyx000 @PritamSarbajna! There is already a PR 👍

**Comment by Vedant-Manjrekar** [comment]
Is this issue closed? If not I would like to work on it.

**Comment by Amyx000** [comment]
@Vedant-Manjrekar I have already worked on the issue, the PR is in process.

**Comment by Vedant-Manjrekar** [comment]
@Amyx000 Ok, No Problem
