### ISSUE TITLE
[DOCS] <Improve documentation>

### ISSUE THREAD

**Issue by aryans1319** [EddieHubCommunity/LinkFree#1601]
### Description

We could improve the starting line of documentation to be more catchy in first sight!

### Screenshots

![asd](https://user-images.githubusercontent.com/72180855/184523913-a2b6ed2c-a86d-4ca7-ba00-ddb73f12d6ba.jpg)

**Comment by eddiejaoude** [comment]
I don't think we should add a link to LinkTree
