### ISSUE TITLE
nextjs: Eddie's profile doesn't load due to a missing property

### ISSUE THREAD

**Issue by thamerla** [EddieHubCommunity/LinkFree#1606]
### Description

Steps taken:
- Cloned the full repo
- Switched to nextjs branch
- Followed the quickstart of the branch
- Went to Eddie's profile at localhost:3000/eddiejaoude

### Screenshots

![image_bug](https://user-images.githubusercontent.com/18537226/184544583-3a7128f7-82f6-4a09-9047-2cd36a2f2a2e.png)

**Comment by eddiejaoude** [comment]
Thanks for raising. 

Q. Did you start a mongo DB?
Q. Did you copy the `.env.example` file to `.env` and add the mongo url

I did have a bug, that I fixed recently, try pulling the latest changes in `nextjs` branch

**Comment by thamerla** [comment]
Thanks for the reply
Q. Did you start a mongo DB?
-> Yes
Q. Did you copy the .env.example file to .env and add the mongo url
 -> Yes

I already had the newest changes. It turned out that the variable MONGODB_URI wasn't parsed correctly. After adjusting it worked. 

How about providing a sample value in ``.env.example`` so that the  format of the mongodb variable is clear to the developer - i.e.  ``MONGODB_URI=mongodb://127.0.0.1:27017`` ?

**Comment by eddiejaoude** [comment]
Oh, sorry the `.env.example` is empty 🤦‍♂️ let me put something in there.

Btw I have this in mine...
```
MONGODB_URI="mongodb://localhost:27017/linkfree"
```

**Comment by eddiejaoude** [comment]
The new version of the LinkFree project is out now using NextJS and TailWind

I will close this issue, but please feel free to create a new issue if still needed
