### ISSUE TITLE
Change the LinkTree in About Section.

### ISSUE THREAD

**Issue by Sin-Sumit** [EddieHubCommunity/LinkFree#161]
In the About section, it is mentioned as LinkTree, it should be LinkFree.

**Comment by schmelto** [comment]
Yes that is right.
![image](https://user-images.githubusercontent.com/30869493/133247793-b42f54b8-6a5a-4109-aa03-3f3f6384cdfa.png)
but linkfree should be an alternative to linktree so the about section seems to be fine from my side.

**Comment by Sin-Sumit** [comment]
Yes, it is an alternative to LinkTree.
I get this.
Closing this issue.
