### ISSUE TITLE
[DOCS] Links shouldn't be optional

### ISSUE THREAD

**Issue by kabir0x23** [EddieHubCommunity/LinkFree#1611]
### Description

Links shouldn't be optional

This app is called LinkFree, if there will be no links in the user profile, 
then what will be the use case for apps like LinkFree

### Screenshots

![image](https://user-images.githubusercontent.com/44284877/184674384-74934cfd-a1cf-4c3a-b3f4-444c61b51558.png)

**Comment by SaiRev0** [comment]
Hey!! If this issue is still open I would like to work on the issue. If its not assigned to anyone please assign it to me

**Comment by eddiejaoude** [comment]
It will be a profile page, especially as people can now use markdown (or they could use milestones or events section)
