### ISSUE TITLE
[OTHER] Adapt the gitpod environment to work with nextjs

### ISSUE THREAD

**Issue by thamerla** [EddieHubCommunity/LinkFree#1612]
### What would you like to share?

Current gitpod environment is tailored to work with the react version, but not the nextjs version - i.e. it lacks mongodb. Also, there's  no warning about that in the README,

### Additional information

Related to #1606 (issues around creating your own dev environment) and #1601 (improving the docs)

**Comment by eddiejaoude** [comment]
Thank you! I think this has now been solved
