### ISSUE TITLE
DB connection not initiated in api/statistics/total.js for next.js.

### ISSUE THREAD

**Issue by jasham** [EddieHubCommunity/LinkFree#1614]
### Description

When user opens localhost:3000 of next.js version in index.js file have /api/statistics/totals url which is calling api/statistics/total.js and in this file db connection is not made due to which getting MongooseError: Operation `stats.findOne()` buffering timed out after 10000ms error.

### Screenshots

![image](https://user-images.githubusercontent.com/23471755/184793314-a0a6e3fe-5bfa-4ee7-b338-f8ef5384b2d0.png)

**Comment by eddiejaoude** [comment]
Good spot, thank you 👍 

Would you like to fix it or I can do it?

**Comment by jasham** [comment]
Please assign it to me I will fix it.

**Comment by eddiejaoude** [comment]
Sure, assigned to you 👍

**Comment by prajapati55** [comment]
Hi @eddiejaoude,
If @jasham not working on this issue. Can I pick this issue?

**Comment by jasham** [comment]
Hello @prajapati55 this issue is fixed please have a look https://github.com/EddieHubCommunity/LinkFree/pull/1615

**Comment by schmelto** [comment]
Resolved in #1615

**Comment by prajapati55** [comment]
@jasham Thanks for informing.
