### ISSUE TITLE
[DOCS] update npm clean install

### ISSUE THREAD

**Issue by RakeshSangem** [EddieHubCommunity/LinkFree#1629]
### Description

Changed `npm install` to `npm ci` for clean installation of the dependencies.

**Comment by kartikgajjar7** [comment]
hey  rakesh i would like to work on this issue can you explain briefly in which file i should make changes?

**Comment by RakeshSangem** [comment]
Hey @kartikgajjar7, Someone has already brought up the issue, and it was merged. 

That is why my PR was closed.

**Comment by kumarsonsoff3** [comment]
Closing this one, as it's already resolved by #1628 and #1642
