### ISSUE TITLE
[FEATURE] Add linkfree-cli support

### ISSUE THREAD

**Issue by Pradumnasaraf** [EddieHubCommunity/LinkFree#1686]
#### 1) Add `linkfree-cli` as devDependencies

Steps: 

- Fork the repo
- Then run 
```
npm run linkfree-cli -D
```
---

#### 2) Add a script in the `package.json` file.

```json
"create": "npx linkfree-cli"
```

### Additional information

Link to CLI repo - https://github.com/Pradumnasaraf/LinkFree-CLI
Link to NPM rej - https://www.npmjs.com/package/linkfree-cli

**Comment by Dun-sin** [comment]
hi, can i work on this?

Also adding it as a dev dependency should mean right? correct me if i'm wrong

```bash
npm i linkfree-cli --save-dev
```

**Comment by maharshi-sinha** [comment]
> hi, can i work on this?
> 
> Also adding it as a dev dependency should mean right? correct me if i'm wrong
> 
> ```shell
> npm i linkfree-cli --save-dev
> ```

+1
