### ISSUE TITLE
[BUG] Update the Discord icon in the readme

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/LinkFree#1698]
### Description

The Discord icon in the `icons.md` file is currently outdated. It should be fixed immediately.
You can get the Discord logo from here: https://discord.com/branding

### Screenshots

![image](https://user-images.githubusercontent.com/51391473/187696973-58e4e2d0-0157-4a0f-92f2-1f6baa292299.png)

### Additional information

This is a good first issue. Please leave it open to beginners or first-time contributors. 🙂
Do let us know if you're having any problems or any questions.

**Comment by Pathholder1806** [comment]
Hey @Panquesito7 !
I would like to contribute to this issue

**Comment by Pathholder1806** [comment]
Hey @Panquesito7 
I would like to contribute to this issue.

**Comment by Pathholder1806** [comment]
Hey @Panquesito7 !
I have opened a PR kindly review it!

**Comment by Pathholder1806** [comment]
Hey @Panquesito7 !
Is the issue up for merging or will it to stay open? 😀

**Comment by ChinmayMhatre** [comment]
> Hey @Panquesito7 ! Is the issue up for merging or will it to stay open? 😀

Once the PR is merged, issue will be closed.
