### ISSUE TITLE
[FEATURE] Use reviewpad to fail a pull request when changing someone else profile

### ISSUE THREAD

**Issue by ferreiratiago** [EddieHubCommunity/LinkFree#1706]
### Description

A user should be able to **only** change his own profile and not someone else profile.

If this happens the pull request should fail.

We can use [reviewpad](https://github.com/reviewpad/reviewpad) for that.

### Additional information

Update [reviewpad](https://github.com/EddieHubCommunity/LinkFree/blob/main/reviewpad.yml) configuration.

**Comment by ChinmayMhatre** [comment]
Could you explain a bit how this could be done. I could give it a try.

**Comment by Favalcodes** [comment]
@eddiejaoude can I give this a try?

**Comment by eddiejaoude** [comment]
Great idea, yes please give it a go 👍

**Comment by eddiejaoude** [comment]
This is now done, well kind of, a label `LGTM` is added when people change their own profile
