### ISSUE TITLE
[FEATURE] Integrate LinkFree with Twitter lists

### ISSUE THREAD

**Issue by thamerla** [EddieHubCommunity/LinkFree#1712]
### Description

[Twitter lists](https://help.twitter.com/en/using-twitter/twitter-lists) is a feature that enables one to create a separate list of users and see their content. Basically, think about it as a custom social media timeline.

The idea 💡 here is to to programmatically create a Twitter list of LinkFree users who have their Twitter handle:
- Preprocess the data that's already in the repo
- Write code to add new people to the list as they add their profiles

Why?
- Twitter visibility motivating people to contribute to LinkFree
- Integrate EddieHub community on Twitter
- Learn & geek out with the Twitter API

**Comment by anirudhp26** [comment]
I would Like to work on this feature

**Comment by anirudhp26** [comment]
@thamerla

**Comment by anirudhp26** [comment]
@Pradumnasaraf @eddiejaoude I would like to work on this feature, but this requires moderators or code owners consent for making "Twitter Developer's" Account on behalf of linktree
What should i do?

**Comment by eddiejaoude** [comment]
Thank you for your energy! I think we should wait a bit and discuss this, because some people may not want this, so it would need to be an opt in

Let's wait for others to share their thoughts on it.

In the meantime have a look at our NextJS branch in the LinkFree project as we are migrating to that and any help appreciated

**Comment by anirudhp26** [comment]
@eddiejaoude Sure

**Comment by eddiejaoude** [comment]
I am going to close this because we don't want to integrate directly with Twitter just yet
