### ISSUE TITLE
[DOCS] Add the LinkFree CLI step in README 

### ISSUE THREAD

**Issue by Pradumnasaraf** [EddieHubCommunity/LinkFree#1728]
### Description

Add LinkFree CLI option to create your JSON file in `To Add Your Profile in the README. Something like creating an option for manual and CLI.

The addition should also include the command and the explanation of how to create the file through CLI
 
```
npx linkfree-cli
```

![Screenshot from 2022-09-10 21-48-39](https://user-images.githubusercontent.com/51878265/189492331-c7e7e07d-0fcc-426c-8689-7f50b1d7fc9d.png)

**Comment by HondaChan14** [comment]
Hello can I be assigned to this?

**Comment by Panquesito7** [comment]
> Hello can I be assigned to this?

Sure, feel free to work on it! 🙂

**Comment by Saha-7** [comment]
Hello maintainers can you assigned me to this issue, I have already progressed a lot & pushed it into my forked repo.

**Comment by Saha-7** [comment]
It will be really helpful for the beginners to add their profile in the LinkFree project by reading the Readme.MD file.
waiting for your reply.

**Comment by Pradumnasaraf** [comment]
Hey, @Saha-7 this issue is already assigned to @HondaChan14. Please look for some other issues.

**Comment by HondaChan14** [comment]
> 

No worries if he has already has it sent. I have no issues with letting him take this :)

**Comment by Pradumnasaraf** [comment]
> > 
> 
> No worries if he has already has it sent. I have no issues with letting him take this :)

You can work on it. No worries. Will be waiting for your PR. If you have any issue let us know!

**Comment by VG-1** [comment]
Hey @Pradumnasaraf can you please assign this to me?

**Comment by Pradumnasaraf** [comment]
Hey @HondaChan14 are you still working on the issue?

**Comment by Saha-7** [comment]
@Pradumnasaraf If he is not working on this issue, then I am available immediately.

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf can you please assign this to me?

Hey, @VG-1 you can go ahead. 

@Saha-7 try finding some other issues as requested 1st.

**Comment by LinuxGamer** [comment]
Is this being worked on still?

**Comment by Pradumnasaraf** [comment]
This is a duplicate and someone is already assigned, you can look for other issues
