### ISSUE TITLE
[Number of Filter Results] <Enhancing the Search Experience>

### ISSUE THREAD

**Issue by Ann-design-max** [EddieHubCommunity/LinkFree#1732]
### Description

As number of profiles expand, adding the no of profiles showing based on searched keyword and filter applied. Here is a simple UI solution I thought about. I am more inclined to the A view (single row) arrangement cause this way the profiles wont be pushed down the viewport as compared to the B view where it's a two row arrangement.

 I will be happy to work on this if assigned
 
 I would just need a confirmation on which arrangement is agreed on

### Screenshots

![All A](https://user-images.githubusercontent.com/62697124/189084950-85c05dfb-8082-4350-a636-f6d7ee8457f4.png)
![All B](https://user-images.githubusercontent.com/62697124/189084955-20efbd7d-5453-4b86-8a97-82b77ec3ca0b.png)
![Community A](https://user-images.githubusercontent.com/62697124/189084961-8301ceee-8181-421b-a54b-6ccaea9f0814.png)
![Community B](https://user-images.githubusercontent.com/62697124/189084966-1c249fc1-e5c5-43b4-9830-93145a6d0801.png)

### Additional information

As we grow, we can have more advanced filter options to enhance the search experience.  
@eddiejaoude

**Comment by eddiejaoude** [comment]
Thank you for the suggestion Ann! 👍 We are migrating the project from React + PrimeReact to NextJS + TailwindCSS, so you might want to look at the branch/pull request with the on going work and contribute there, here is the link https://github.com/EddieHubCommunity/LinkFree/pull/1471

**Comment by EmmaDawsonDev** [comment]
Nice idea. I like the idea of having them all in one line like in sample A but I wonder if it would be more logical to have the search/dropdown on the left and then number of profiles on the right.

**Comment by eddiejaoude** [comment]
This issue is now out of date, as we have rewritten the app
