### ISSUE TITLE
[DOCS] <Add a direct link to add profile for Linkfree in Readme File>

### ISSUE THREAD

**Issue by izzarzn** [EddieHubCommunity/LinkFree#1736]
### Description

We can make adding of profile more accessible by adding a link in Readme File to add user profile directly.a 

### Screenshots

![Screenshot 2022-09-08 at 9 40 12 PM](https://user-images.githubusercontent.com/65058286/189172659-a4c36103-514f-4428-b203-d9c8b6b161d8.png)

**Comment by izzarzn** [comment]
![Screenshot 2022-09-08 at 10 11 30 PM](https://user-images.githubusercontent.com/65058286/189178551-afdbf891-c851-4378-a549-28cb314bbc04.png)

**Comment by data2kinyungu** [comment]
That would be great. However I think that hide the abstraction of adding the profile for Linkfree

**Comment by data2kinyungu** [comment]
That would be great. However I think that hide the abstraction of adding the profile for Linkfree

**Comment by sanyamgandhak** [comment]
Hi there , Please assign this task to me

**Comment by eddiejaoude** [comment]
We have refactored the whole project, so I will close this issue - feel free to raise a new specific issue if needed
