### ISSUE TITLE
Update the UI design in the `README` file

### ISSUE THREAD

**Issue by siddhantprateek** [EddieHubCommunity/LinkFree#176]
**Current State:**
![Screenshot from 2021-09-14 18-40-04](https://user-images.githubusercontent.com/43869046/133264018-0ba2a79a-3cb8-4c06-b1cc-f8269e58fc1d.png)

**Desired State:**
![Screenshot from 2021-09-14 18-38-52](https://user-images.githubusercontent.com/43869046/133264110-2d1debf6-225e-4dd6-b90a-d9f548976204.png)

**Comment by Aayushi-Mittal** [comment]
Hi, Can I take up this issue?

**Comment by qwe123coder** [comment]
yea go ahead

**Comment by rohan-kulkarni-25** [comment]
Folks ! Please ask the issue author if they want to work on this issue or not ! IF not then you can go ahead. No issues this time it is small work but keep in mind always.
