### ISSUE TITLE
`share` icon in not aligned properly

### ISSUE THREAD

**Issue by Rounak-28** [EddieHubCommunity/LinkFree#1770]
### Description

In profile eg. `linkfree.eddiehub.io/eddiejaoude`  the share icon is not aligned properly.

### Screenshots

![linkfree](https://user-images.githubusercontent.com/95576871/191014380-7f41bf64-0fd3-4595-b289-0e21e9b0313e.jpg)

**Comment by abitsalihu** [comment]
Hey, I would like to help with this issue. :)

**Comment by Rajeevjewar** [comment]
I want to work on it.
