### ISSUE TITLE
[FEATURE] User to list events they are going to

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#1796]
### Description

It would be great to see what events people are going to, some field ideas

- date + time
- title
- description
- link
- location (or virtual and type: space, live etc)

Then later on we can display all up and coming events for everyone on the platform

**Comment by anirudhp26** [comment]
Hey there, @eddiejaoude , I would like to contribute to this feature!

**Comment by anirudhp26** [comment]
@imlakshay08 Hey I just got assigned, now I want to know should we make users edit their profiles whenever they get to know about any event or we should make separate directory ( public/events ) where users will save the events they are attending in the format of json files ( username_eventname.json )

**Comment by imlakshay08** [comment]
> @imlakshay08 Hey I just got assigned, now I want to know should we make users edit their profiles whenever they get to know about any event or we should make separate directory ( public/events ) where users will save the events they are attending in the format of json files ( username_eventname.json )
> 
> @eddiejaoude Sir it would be great to hear your insights on this

Seperate directory sounds good.

**Comment by anirudhp26** [comment]
Great then let's wait for approval

**Comment by anirudhp26** [comment]
I already made the route and Event Page

**Comment by anirudhp26** [comment]
![image](https://user-images.githubusercontent.com/107875381/192158050-8b0ae57c-0140-4da6-a349-7c2afae50148.png)

Does this button look good? @imlakshay08

**Comment by imlakshay08** [comment]
> Great then let's wait for approval

Yes. Sure.

**Comment by imlakshay08** [comment]
> ![image](https://user-images.githubusercontent.com/107875381/192158050-8b0ae57c-0140-4da6-a349-7c2afae50148.png)
> 
> Does this button look good? @imlakshay08

This is looks awesome.

**Comment by eddiejaoude** [comment]
Thank you all for the collaboration, the initial idea was so that each person can add events to their data and it be displayed on their profile, then we can also collect the data to show what events are coming up on a separate page.

Something like this...

```json
{
  "name": "Eddie Jaoude",
  "type": "personal",
  "bio": "Open Source DevRel | Founder of EddieHub | GitHub Star",
  "avatar": "https://github.com/eddiejaoude.png",
  "links": [ ],
  "milestones": [
      {
         "name": "Open source event",
         "description": "Great open source event where we can all learn together",
         "link": "http://eddiehub.org",
         "date": "2023-01-01 18:00:00",
         "type": "virtual",
         "location": "http://discord.eddiehub.org"
      }
   ]
}
```

This data would appear on my profile page in this situation. Then there could be an overall events page to display everyone's events together.

**Comment by anirudhp26** [comment]
Sure! I'll implement the idea you suggested @eddiejaoude

**Comment by eddiejaoude** [comment]
Great 👍 , it would be better if you did it from the `nextjs` branch, so it is not lost when we migrate to v2

Some tips
- keep the pull requests very small, we can merge little and often 
- create the pull request early using `draft` pull request to save you wasting any time

**Comment by anirudhp26** [comment]
@imlakshay08 Do you have experience using Next.js?

**Comment by imlakshay08** [comment]
> @imlakshay08 Do you have experience using Next.js?

Nope buddy. But, I can try.

**Comment by anirudhp26** [comment]
@imlakshay08 Hey I completed the Feature can you check if it's good?

**Comment by eddiejaoude** [comment]
Feature completed in v2 of LinkFree
