### ISSUE TITLE
[FEATURE] To add google tracking id for user profile.

### ISSUE THREAD

**Issue by Shubhdeep12** [EddieHubCommunity/LinkFree#1798]
### Description

It would be helpful for a user to see the analytics and if we support adding google analytics tracking id in json file.
It would be helpful.

Please confirm if this is a valid feature. 
I would love to do this.

---

By Eddie

- I think the field `gAnalytics` can be added to people's profiles
- if `gAnalytics` is available in the profile, then add to their profile page

**Comment by anirudhp26** [comment]
Can I know more about this feature you suggested?

**Comment by AgniveshChaubey** [comment]
Hey @Shubhdeep12, I wanna work on this issue! I am new to opensource contribution, so it'd be more helpful to me if some more info is provided.

**Comment by Shubhdeep12** [comment]
Hi @anirudhp26 @AgniveshChaubey 
Thanks for the interest in the feature.
I also want to do this but want to confirm whether this is valid or not.
Explanation - In order to create a linkfree page, we need to create a json file, so what i am suggesting is the support to have a google analytics tracking id in the json file, so that user can have the analytics of his/her linkfree page.
@eddiejaoude sorry to mention.
But any comments from your end would be helpful here.

**Comment by anirudhp26** [comment]
@Shubhdeep12 ohh so you mean to track info like whose profile is viewed more, all ?
This can be a great feature as well

**Comment by eddiejaoude** [comment]
We now have stats for the profile page and links

Can we have individual google analytics for each page?

**Comment by Shubhdeep12** [comment]
Hey @eddiejaoude sorry for late reply. Seems like it is considered as valid feature. Should i start work on this? Or anyone else is working on this right now?

Here is my plan:
1. As you also mentioned above,  in json file there would be a new key gAnalytics where user can add his/her GTM tag.
2. And we will add that particular tag in head tag for the particular page. 

Please confirm, then I'll start work on this.
Thanks

**Comment by eddiejaoude** [comment]
No problem. I have now assigned it two you @Shubhdeep12

**Comment by SaraJaoude** [comment]
> We removed `nextjs-google-analytics` as we are using Vercel analytics. I think this feature will come as part of the Premium version on LinkFree, so I will block it for a few more weeks until that part is finished

I have changed the label to `status: blocked` given the the discussion on the Pull Request (quoted above): https://github.com/EddieHubCommunity/LinkFree/pull/5724

**Comment by eddiejaoude** [comment]
Going to close this for now as it is not a highly requested feature plus has some legal complications
