### ISSUE TITLE
Improve the .dockerignore file to reduce the build image size

### ISSUE THREAD

**Issue by Pradumnasaraf** [EddieHubCommunity/LinkFree#1829]
### Description

improve the .dockerignore file to reduce the build size

**Comment by OmAvhad** [comment]
Hello @Pradumnasaraf,
I am a newbie want to start to contribute for opensource and want to participate for hacktober fest.

Can I work on this issue ?

**Comment by OmAvhad** [comment]
@Pradumnasaraf and could you please mark other issues hacktober label

**Comment by FrancescoXX** [comment]
@Pradumnasaraf  I can work on this one , if you need help

**Comment by Pradumnasaraf** [comment]
Thank you @FrancescoXX . The PR is already out.
