### ISSUE TITLE
[FEATURE] Timeline animation major update

### ISSUE THREAD

**Issue by vasucp1207** [EddieHubCommunity/LinkFree#1854]
### Description

Hey, after spending hours on implementing the new timeline feature see how it looks after the updating.

https://user-images.githubusercontent.com/85363195/193411579-ce8f0fc7-24c9-4240-ac4a-5288a6437476.mov

It looks great, assign me this issue for the update.

**Comment by EmmaDawsonDev** [comment]
I think there is already an open PR for this. Might be best to check the comments there and what the progress status is

**Comment by vasucp1207** [comment]
Hey, @EmmaDawsonDev I did not find any issue like this can you link that issue.

**Comment by EmmaDawsonDev** [comment]
I just looked at it again and they were animating the links not the timeline so ignore me :)

**Comment by vasucp1207** [comment]
Ok, Thanks for assigning the issue to me.

**Comment by vasucp1207** [comment]
Hey @EmmaDawsonDev, I make the PR let me know for any further discussion.

**Comment by kartikgajjar7** [comment]
> implementing the new timeline feature see how it looks after the updating.
> 
>  Screen.Recording.2022-10-01.at.6.52.34.PM.mov
 hey @vasucp1207  you raised pr for this ?

**Comment by vasucp1207** [comment]
Yes

**Comment by eddiejaoude** [comment]
This was merged in 👍
