### ISSUE TITLE
Update the hover effect and background colors of links

### ISSUE THREAD

**Issue by Kunal0007** [EddieHubCommunity/LinkFree#186]
Before :
![image](https://user-images.githubusercontent.com/73381050/133451899-e8cc35e9-d248-403a-ad3a-adb5b57faca6.png)

After :
![image](https://user-images.githubusercontent.com/73381050/133312042-fe693072-0c44-4d88-be6a-8d1f99803839.png)
![image](https://user-images.githubusercontent.com/73381050/133312137-3aca7dc5-a90d-44be-8d31-843f3b4f88e9.png)
![image](https://user-images.githubusercontent.com/73381050/133312270-d476545a-261d-404a-92b5-fef7183cd4ea.png)

**Comment by Kunal0007** [comment]
Should I make a PR for this update?

**Comment by rohan-kulkarni-25** [comment]
### Just a suggestion 
- Do mention the before and after with words while adding two screenshots 
- You can also use Markdown table

**Comment by eddiejaoude** [comment]
Looks good, left some comments on the PR 👍
