### ISSUE TITLE
[OTHER] Shareicons color changing in version 0.76.5

### ISSUE THREAD

**Issue by vasucp1207** [EddieHubCommunity/LinkFree#1862]
### What would you like to share?

Why ShareIcons not changing the color accordingly on hovering in the latest version

https://user-images.githubusercontent.com/85363195/193450340-0ddc2218-082b-4057-ac1e-47f286f30330.mov

Inform me for any required help

**Comment by RedHeadphone** [comment]
there is hover effect CSS for it but it's not working
https://github.com/EddieHubCommunity/LinkFree/blob/536787f1af539c764f253234d1ebcd42d5ff72ca/src/Components/Profile.css#L44
I would like to fix this

**Comment by RedHeadphone** [comment]
seems to be working fine in localhost

**Comment by vasucp1207** [comment]
Yeah, but it is not working on live site.

**Comment by RedHeadphone** [comment]
Not sure but is this causing an issue?
https://github.com/EddieHubCommunity/LinkFree/blob/main/package.json#L28

**Comment by RedHeadphone** [comment]
I can try updating this library version
https://github.com/EddieHubCommunity/LinkFree/blob/main/package.json#L57
to latest 5.0.0 version 
https://www.npmjs.com/package/@fullhuman/postcss-purgecss

or we can use this https://www.npmjs.com/package/purgecss

waiting for reply! let me know what should I do?
