### ISSUE TITLE
Add green squares as a background image with low opacity on users page 

### ISSUE THREAD

**Issue by rajivransom** [EddieHubCommunity/LinkFree#187]
![Screenshot 2021-09-15 001524](https://user-images.githubusercontent.com/67317263/133316130-c9be29bf-1b1e-4623-a035-6b7ef4d641ba.png)

**Comment by rohan-kulkarni-25** [comment]
Hey, Thanks for Suggesting but I personally think this will look cluttered and will destroy our objective to keep the shape of image as circle ( as we can keep that square also ). 
( PERSONAL OPINION )

**Comment by rohan-kulkarni-25** [comment]
Duplicate of #146

**Comment by eddiejaoude** [comment]
Thank you for the suggestion 👍 

We are removing the list of users on the home page as there are too many, so I will close this for now
