### ISSUE TITLE
[ FEAT ] Way to Add user Data 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [EddieHubCommunity/LinkFree#188]
### Current Way 
- We ask the user to create a PR and add their data into json file. 

### New Way 
- We can get that data from POST req through form. That will avoid the PR for data addition and we can focus more on productivity.

### Detailed Explanation 
- We can write a script ( Node ) in that when the user submits data we will take a post req from that route and write that using fs module. 
- Currently we have single file for each user ( That can also be implemented with this feature ) But I suggest to keep all data in single file so sorting will be easy and as we are doing in json so hanling objects is not a difficult task for us. 

#### Do let me know your views on this !! I will like to work on this issue if accepted

**Comment by schmelto** [comment]
Do you also thought about deleting users, delete links, update links, add links for current users? And how you want to achive this?

**Comment by rohan-kulkarni-25** [comment]
> Do you also thought about deleting users, delete links, update links, add links for current users? And how you want to achive this?

Yes we can do that with help of CRUD operations. ! I will make one repository where will implement the same feature if that work well then we will use the same logic for our project.

**Comment by schmelto** [comment]
One other thougth of my side. Is a review process necessary? What about a reviewing process of the newly added links? In Github we have a PR review process. Do we need something similar when using CRUD operations?

**Comment by rohan-kulkarni-25** [comment]
> One other thougth of my side. Is a review process necessary? What about a reviewing process of the newly added links? In Github we have a PR review process. Do we need something similar when using [CRUD](https://en.wikipedia.org/wiki/Create,_read,_update_and_delete) operations?

I think we can ignore that as we can make a validation while crud but I got a new point here that if we allow to edit or delete request then anyone can delete anyone's data. I am thinking on it. Because if we are able to do this then all PR with data addition can be handled here and we can focus on applications features.

**Comment by rohan-kulkarni-25** [comment]
Yes got a solution for this 

- From the automated CRUD process we will just add new user.
- for Update Del the data we can raise PR as that will be more appropriate so we can review them and the number of PR will be less so we can manage that.

**Comment by rohan-kulkarni-25** [comment]
## Closing This Issue 

- As While working on this I got to know that we can't use fs package to create a new file in repository.
