### ISSUE TITLE
[FEATURE] Accessibility: Announce search results size while typing in the search box

### ISSUE THREAD

**Issue by SavvasStephanides** [EddieHubCommunity/LinkFree#1881]
### Description

Currently there's no way for a user relying on a screen reader to know how many results are visible while typing in the search bar. It would be nice if this would be announced. For example "6 search results".

### Additional information

This can be accomplished with a ["live region"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions)

**Comment by kiritocode1** [comment]
Id love to work on this issue , assign me this pweese 😄

**Comment by SaraJaoude** [comment]
Thank you for this suggestion.  As this has now been implemented I am going to close this issue.
<img width="1310" alt="Screenshot 2023-02-03 at 14 27 06" src="https://user-images.githubusercontent.com/82668196/216538490-52074b46-308d-4ecc-8bf6-bb95d3f6ebe4.png">
