### ISSUE TITLE
[DOCS] Create DOCS folder

### ISSUE THREAD

**Issue by EmmaDawsonDev** [EddieHubCommunity/LinkFree#1883]
### Description

Create a folder named docs in the root of the project. 
Inside the docs folder create a folder named contributing. 
Move the contributing.md file into the contributing folder.
Update links to contributing.md in the readme with correct file path.

**Comment by ShorunTech** [comment]
can this be assign to me, i will work on it

**Comment by EmmaDawsonDev** [comment]
Go ahead @ShorunTech

**Comment by shorya258** [comment]
if they're not working on this issue, can I?

**Comment by EmmaDawsonDev** [comment]
@restacksyj please stop making new PRs and let @ShorunTech solve the issue,thanks.

**Comment by vaibhavmishra4g** [comment]
Could you assign this to me if still available?

**Comment by EmmaDawsonDev** [comment]
It’s already assigned, but don’t worry as more issues will be posted in the coming days.

**Comment by vaibhavmishra4g** [comment]
sorry for not reading I'm cancelling my pr

**Comment by ShorunTech** [comment]
Successful make the PR from another branch. Thank you Emma for your help.

**Comment by EmmaDawsonDev** [comment]
> can someone assign me this , ill work on it 😄

It’s already assigned and a PR made. More issues will be posted in the coming days

**Comment by ShorunTech** [comment]
👍❤️
