### ISSUE TITLE
[FEATURE] Add functionality to change hamburger menu icon status

### ISSUE THREAD

**Issue by chints87** [EddieHubCommunity/LinkFree#1901]
### Description

For mobile view (Next.js), click on hamburger item should transform from hamburger menu icon to close icon

### Screenshots

**Before Clicking Hamburger Menu Icon** 
![image](https://user-images.githubusercontent.com/10020129/194027326-b60d9daa-521c-4b03-a3ad-28073597813a.png)

**After Clicking Hamburger Menu Icon** 
![image](https://user-images.githubusercontent.com/10020129/194027928-6d250060-7d5d-4dc5-a174-be5c2663b775.png)

### Additional information

On clicking the menu hamburger icon

1) Overlay component should display (not seen in the above images)
2) Within that overlay component the menu  (not seen in the above images)

**Comment by Dhruv1969Karnwal** [comment]
Please Sir, assign me this issue i can do it as early as possible.

**Comment by chints87** [comment]
I already have worked on it, but am ok if @Dhruv1969Karnwal wants to give it a try. Happy to help if you run into issues. :)

**Comment by eddiejaoude** [comment]
I think there is a PR for this https://github.com/EddieHubCommunity/LinkFree/pull/3202

**Comment by eddiejaoude** [comment]
There are issues for this already, so I will close this
