### ISSUE TITLE
[DOCS] Contributing icons docs

### ISSUE THREAD

**Issue by EmmaDawsonDev** [EddieHubCommunity/LinkFree#1907]
### Description

Add a file to the docs/contributing folder called contributing-icons.md

In the file give full instructions for how to fork and clone the project, add the icons to the following 3 files:
icons.md
GetIcons.js
links.json

Then add instuctions for how to commit and add the correct files and make a pull request

**Comment by shambashib20** [comment]
Can I do it? Can I work on this issue?

**Comment by virtual-designer** [comment]
I've been already working on it

**Comment by EmmaDawsonDev** [comment]
@virtual-designer in the future it’s best to ask to be assigned before making a PR. It prevents 2 or more people working on the same task unnecessarily

**Comment by asdsyd** [comment]
Is this issue still open for contribution? thanks.

**Comment by EmmaDawsonDev** [comment]
@asdsyd There's currently an open PR
