### ISSUE TITLE
[DOCS] Contributing to next js branch

### ISSUE THREAD

**Issue by EmmaDawsonDev** [EddieHubCommunity/LinkFree#1908]
### Description

In the docs/contributing folder create a file called contributing-to-nextJS-branch.md

Provide full instructions for how to fork, clone, contribute and make a pull request to contribute to the nextJS branch (use contributing.md but modify to fit the needs of this particular contribution.

Provide a screenshot highlighting folks to uncheck the 'Fork main branch only' option when forking the repo.

**Comment by irfanariyaz** [comment]
Can I try  this issue?

**Comment by vasucp1207** [comment]
Hey, @EmmaDawsonDev I just submit the PR regarding this issue take a look at that and tell me about any further changes.

**Comment by EmmaDawsonDev** [comment]
@vasucp1207 please see that someone asked to assigned 11hours ago. It’s not good etiquette to make a PR on an issue someone else was hoping to do.

**Comment by vasucp1207** [comment]
I close the PR

**Comment by irfanariyaz** [comment]
Thanks for assigning me this issue @EmmaDawsonDev

**Comment by eddiejaoude** [comment]
I think we can close this as there `nextjs` has been merged
