### ISSUE TITLE
Number of links appear on hover on homepage itself

### ISSUE THREAD

**Issue by subhodynamics** [EddieHubCommunity/LinkFree#191]
The number of links added now can be seen only when someone gets into the profile, that number can be made more useful to one when it appears on the homepage when hovered over the profile logo, along with the user name.
![image](https://user-images.githubusercontent.com/75271901/133393890-075fd8d1-7759-4ef7-9018-3793f775274c.png)

![image](https://user-images.githubusercontent.com/75271901/133393910-1ad53504-0504-4fb6-858b-fab89f96f0f1.png)

**Comment by kishoreandra** [comment]
I see there is no property like `onMouseEnter`, for primereact - may be other ways too

**Comment by amittri1025** [comment]
Can I work on this issue ?

**Comment by Vyvy-vi** [comment]
Names do appear on the main page right now.

**Comment by nathgoutam93** [comment]
hey, is anyone working on this issue? if not, i would like to work on it .
