### ISSUE TITLE
[FEATURE] Add Modal Component

### ISSUE THREAD

**Issue by chints87** [EddieHubCommunity/LinkFree#1910]
### Description

Modal component would be used to display navigation menu in mobile view and then also used to insert child components for success , error messages etc.

**Comment by chints87** [comment]
Could this be assigned to me

**Comment by eddiejaoude** [comment]
Thank you for suggestion. If this is not for a specific requirement, let's not create dead components. We are using Tailwind which has a model built in and we can create a component for it when it is required, so I will close this for now
