### ISSUE TITLE
[OTHER] My PR got merged but still my LinkTree link is not working

### ISSUE THREAD

**Issue by Ayush-Kanduri** [EddieHubCommunity/LinkFree#1915]
### What would you like to share?

My PR got Merged successfully but still, my profile is not available with LinkTree under my name. It has the following error as mentioned below with the image.

![err](https://user-images.githubusercontent.com/76626529/194529706-5bbe52c9-4f2f-4903-847b-05728c4ceb69.png)

Name: Ayush Kanduri
Username: Ayush-Kanduri
LinkTree Link: https://linkfree.eddiehub.io/Ayush-Kanduri

Kindly help.

**Comment by EmmaDawsonDev** [comment]
Please wait for manual deployment 😊
