### ISSUE TITLE
[FEATURE] Move from Cypress to Playwright

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#1920]
### Description

Currently the tests are written in [Cypress with Cucumber](https://github.com/EddieHubCommunity/LinkFree/tree/main/cypress/integration), however these need to be moved to Playwright (similar to the [Finder](https://github.com/EddieHubCommunity/good-first-issue-finder) project)

http://playwright.dev

> **Warning**
> this is for the `nextjs` branch

> **Note**
> You don't need to do all the tests, different people can do individual tests in a new PR

**Comment by petercr** [comment]
Hey Eddie 🙋🏻‍♂️ is no one is on this issue, I would be happy to do it.

I've been meaning to play around with Playwright, and this seems like a good opportunity.

Thanks and cool project 👍🏻

**Comment by eddiejaoude** [comment]
Hi Peter, sure sounds great 👍

**Comment by petercr** [comment]
Eddie,

Okay I went and joined the EddieHub so I should be good to go with the Org and the assignment 👍🏻

I'll go ahead and start planning this one out.

Thanks

**Comment by eddiejaoude** [comment]
Thanks @petercr , please create the issue for the test you will do, and we can assign that to you - this issue is an `epic` and won't be assigned as it is too big

**Comment by petercr** [comment]
Thanks Eddie 🙌🏻 yeah this does _seem_ like it might be a little big for just one issue/PR.

Then I'd have to think of if you wanted me to squash the **18 commits** in that PR... 😂

I will just open an issue for a specific test and make a PR for that issue 👍🏻

**Comment by petercr** [comment]
Eddie,

It looks like there is an implementation of Cucumber and Playwright together already on GitHub && NPM. 
[Link to the cucumber-playwright repo](https://github.com/Tallyb/cucumber-playwright)

There is the possibility that we could port all of the existing cypress tests written in cucumber and just switch out cypress for playwright.  Instead of re-writing all the tests. 

Is that something you would be interested in, or would you rather go the route of re-writing the tests from scratch?
Either way works 👍 

Thanks

**Comment by eddiejaoude** [comment]
Thanks Peter for doing that research. The community were not keen on Cucumber, so we decided to rewrite using vanilla Playwrght

**Comment by petercr** [comment]
Awesome 👍🏻 cucumber looks great...
but if you are used to writing tests in JS/TS it does seems like an extra step.

If you _can write_ the tests, you **probably should** write the tests 😂

Thanks for all the info 🙌🏻

**Comment by eddiejaoude** [comment]
I am going to close this epic, there are still more tests to be written though
