### ISSUE TITLE
Links can't be seen in dark mode

### ISSUE THREAD

**Issue by EmmaDawsonDev** [EddieHubCommunity/LinkFree#1926]
### Description

The links are almost invisible on the homepage when dark mode is activated. Provide a different color for the links when dark mode is activated

### Screenshots

<img width="469" alt="image" src="https://user-images.githubusercontent.com/57045550/194723707-8ff643f3-fe9f-4c5a-bfa0-8b871569a522.png">

**Comment by dhruvdabhi101** [comment]
I would like to contribute to this issue.

**Comment by EmmaDawsonDev** [comment]
Sure, go ahead @dhruvdabhi101
