### ISSUE TITLE
Profile names are not visible on hovering 

### ISSUE THREAD

**Issue by Shivam-Katare** [EddieHubCommunity/LinkFree#1928]
### Description

The profile names are not visible in dark mode. The color of the name should be black but it is white because of that, the names are not visible.

### Screenshots

![Screenshot (87)](https://user-images.githubusercontent.com/91705825/194724453-9082c9f6-ae5a-459f-b339-43d400aa2616.png)
![Screenshot (88)](https://user-images.githubusercontent.com/91705825/194724455-b3a00d91-b0a3-49d0-97d6-6d31cdf1f5e5.png)

### Additional information

Can I take start working on this issue?

**Comment by EmmaDawsonDev** [comment]
Sure, go ahead

**Comment by eddiejaoude** [comment]
Merged
