### ISSUE TITLE
[FEATURE] Add component UserPreview to Storybook 

### ISSUE THREAD

**Issue by dunnjacoba** [EddieHubCommunity/LinkFree#1945]
### Description

All React components and pages need to be added to Storybook (in the nextjs branch)

>  Note
>Each item listed below for component/page should be in a new Issue and PR 

- [ ] <code>component/user/UserPreview.js</code>

Steps to follow...

1. Create story file in stories/components with the same filename as the component but add .stories.js
2. Import the component into the story file
3. Set the default arguments by looking at the requirements from the component
4. Run npm run storybook to see the added components and interact with them

### Additional information

#1944 Addresses UserPreview in the nextjs branch for storybook.

**Comment by dunnjacoba** [comment]
Can I get assigned this task to complete?

**Comment by EmmaDawsonDev** [comment]
Closed by #1946
