### ISSUE TITLE
[FEATURE] Add NavLink to the Storybook in nextjs branch

### ISSUE THREAD

**Issue by vasucp1207** [EddieHubCommunity/LinkFree#1948]
### Description

- Hey, Kindly assign this issue to me, so that I can start to work on this.

**Comment by EmmaDawsonDev** [comment]
Sure, go ahead.

**Comment by vasucp1207** [comment]
Thanks for assigning this issue to me.

**Comment by EmmaDawsonDev** [comment]
Apologies @vasucp1207 but there’s already a pr made for this as Eddie assigned it to someone else in another issue.

**Comment by EmmaDawsonDev** [comment]
Closing as duplicate
