### ISSUE TITLE
UPDATE README.md

### ISSUE THREAD

**Issue by Purva2803** [EddieHubCommunity/LinkFree#1956]
### What would you like to share?

hey, Eddie, I want to contribute  by adding some documentation in README.md please give me a chance to make it more interesting and I can show my technical writing skills as well.

**Comment by EmmaDawsonDev** [comment]
Please be specific about what you would like to add and where. Currently there is too much information in the readme and we are trying to slim it down and provide links to more specific documentation elsewhere

**Comment by Purva2803** [comment]
hello @EmmaDawsonDev, the README.md contains so much information I want to make it more specific about the project and I also want to add some resources which are new for the folks or they don't know much about it like Kubernetes, and docker so they can get some idea about and also they will be aware of the main purpose of the project and get to know how things actually work, I will work on it if you like it then please merge it.

**Comment by eddiejaoude** [comment]
The new version of LinkFree is out, I will close this issue, feel free to create a new issue for the new version if still relevant

Please make new issues that are specific to each change - small and often is better
