### ISSUE TITLE
[FEATURE]   Add component NavLink to Storybook 

### ISSUE THREAD

**Issue by Prasundas99** [EddieHubCommunity/LinkFree#1957]
### Description
 All React components and pages need to be added to Storybook (in the nextjs branch)
 
 > Note
 > Each item listed below for component/page should be in a new Issue and PR
 
 * [x]  `components/navbar/NavLink.js`
 
 Steps to follow...
 
1. Create story file in stories/components with the same filename as the component but add .stories.js
 2. Import the component into the story file
 3. Set the default arguments by looking at the requirements from the component
 4. Run npm run storybook to see the added components and interact with them
 
 ### Screenshots
 _No response_
 
 ### Additional information
 #1944 Addresses UserPreview in the nextjs branch for storybook.

**Comment by EmmaDawsonDev** [comment]
Closing as this is a duplicate

**Comment by Prasundas99** [comment]
Hi, should I close my PR too? I got a  goahead from Eddie to work in this issue

**Comment by EmmaDawsonDev** [comment]
Oh, sorry then there’s been a mixup.

**Comment by EmmaDawsonDev** [comment]
No, don’t close it. I’ll tell the other person to stop working on it. I don’t think they made a pr yet.

**Comment by eddiejaoude** [comment]
Closing as complete
