### ISSUE TITLE
[FEATURE] Add Component Footer to NextJs Project

### ISSUE THREAD

**Issue by ranjankuldeep** [EddieHubCommunity/LinkFree#1958]
### Description

#1944 

# ```components/footer.js ```
Please assign it to me.

### Screenshots

<img width="783" alt="Screenshot 2022-10-13 at 5 41 54 PM" src="https://user-images.githubusercontent.com/95350799/195592813-3535c11d-6705-47d3-bba5-f83381ec364d.png">

**Comment by VedanthB** [comment]
I'd like to work on this

**Comment by DeeptanshuDas** [comment]
can i work on this issue

**Comment by eddiejaoude** [comment]
Footer component has been added to Storybook

Please create specific issues for any future work
