### ISSUE TITLE
[FEATURE] Add Pages/Popular component to Storybook

### ISSUE THREAD

**Issue by itsagift** [EddieHubCommunity/LinkFree#1959]
### Description

pages/popular.js in [#1944](https://github.com/EddieHubCommunity/LinkFree/issues/1944)

Would love to be assigned to add pages/popular.js.

**Comment by itsagift** [comment]
@eddiejaoude Can you add the hacktoberfest label to this one somehow since it was on the original issue?

**Comment by eddiejaoude** [comment]
The whole repo is part of hacktoberfest, no extra label is required 🤓 - I will close this issue as the PR has been merged

**Comment by itsagift** [comment]
@eddiejaoude Ah sorry I'm still new to the rules! thanks so much
