### ISSUE TITLE
[FEATURE] adding image inline to GitHub username when searching user 

### ISSUE THREAD

**Issue by Aladdin4u** [EddieHubCommunity/LinkFree#1962]
### Description

Show the user image inline with username inside the search component

### Screenshots

![download](https://user-images.githubusercontent.com/101972392/195794476-7fc52323-684b-435e-806c-f26784b19e70.png)

**Comment by KlausMikhaelson** [comment]
@Aladdin4u Hey is this issue approved ? if yes than are you looking forward to work on it ? if no than would really like to work on it ! can you assign it to me ?

**Comment by Aladdin4u** [comment]
You can work it @KlausMikhaelson

**Comment by EmmaDawsonDev** [comment]
Hi! We had images before but it ended up maxing out the GitHub api which is why we removed them. Unless we can find a way to not hit the rate limit then unfortunately we can’t show images on the small name chips.

**Comment by eddiejaoude** [comment]
The new version of the project has images 👍
