### ISSUE TITLE
Search icon not properly aligned

### ISSUE THREAD

**Issue by Atharv181** [EddieHubCommunity/LinkFree#1972]
### What would you like to share?

Icons are not properly aligned in navbar
![image](https://user-images.githubusercontent.com/73999654/195923809-93e5727e-c36e-49b1-94f7-be8947eb74ca.png)
![image](https://user-images.githubusercontent.com/73999654/195923843-a00a81ab-d530-4e3c-baf1-707f3f25ac95.png)

**Comment by DenysLins** [comment]
Hey guys, can I work on this?

**Comment by deepanshu1334** [comment]
can you assign this to time
