### ISSUE TITLE
Menu on Mobile Devices

### ISSUE THREAD

**Issue by Akshu-on-github** [EddieHubCommunity/LinkFree#1980]
### Description

The navigation menu is permanently open on mobile devices. The hamburger menu seems to be broken as well, as clicking on it gives no observable response.

### Screenshots

![image](https://user-images.githubusercontent.com/61582763/196057991-df9858f8-9774-45e3-808d-82cf6e255315.png)

**Comment by LinuxGamer** [comment]
Can I be assigned to this.

**Comment by Supratim30** [comment]
Hey, would like to fix the issue.

**Comment by k99sharma** [comment]
Hey, Is this issue still open?

**Comment by k99sharma** [comment]
Are you still working on it? I can make a PR for this issue.

**Comment by LinuxGamer** [comment]
Yes I'm working on this ATM, but idk whether I'll be able to fix it so if I can't, I'll tag you and let you know. :)

**Comment by LinuxGamer** [comment]
Hi, @k99sharma @eddiejaoude , I would like to step away from this issue please, I've got a lot of things happening in my personal life and in my brain with other projects, and I'd like to offer ksharma the opportunity to take over, they showed interest the other day. I don't want to hold up a bug fix which could be worked on by someone else.
Thanks,
CJ

**Comment by k99sharma** [comment]
Maybe you can checkout other issues after sometime @LinuxGamer.

**Comment by LinuxGamer** [comment]
Yes, I plan to once I've sorted out scheduling and prioritising things XD

**Comment by eddiejaoude** [comment]
This issue has been resolved. Thank you everyone for your support and collaboration
