### ISSUE TITLE
NextJS - name not displayed correctly 

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/LinkFree#1984]
### Description

Name not displayed correctly on mobile 

### Screenshots

![6606DDFC-23E4-46CF-AD15-9342709172E1](https://user-images.githubusercontent.com/30869493/196108763-66f56db0-9fb8-4fbf-a45b-6ff1d2a8df72.jpeg)

### Additional information

I’m using an iPhone 13 mini

**Comment by k99sharma** [comment]
Hey, I looked in the code. This is happening because of the text size. We can reduce the text size from `text-2xl` to `text-xl` and it will fit perfectly.

![Screenshot (36)](https://user-images.githubusercontent.com/54969439/196148183-c5fd851c-f079-404c-91cd-e8043e7ab669.png)

**Comment by schmelto** [comment]
@k99sharma is it also looking good in desktop mode?

**Comment by k99sharma** [comment]
It seems good to me in the desktop too. I'll open a PR to fix this issue. 

![Screenshot (59)](https://user-images.githubusercontent.com/54969439/196177047-9827caf6-9de3-4f35-aa1d-0fa3917538eb.png)

**Comment by Tharunkumar001** [comment]
Can I work on this issue? @k99sharma

**Comment by k99sharma** [comment]
This issue is already fixed. You can look for other issues 👍🏻. @Tharunkumar001

**Comment by eddiejaoude** [comment]
Issue is fixed, I will close
