### ISSUE TITLE
[FEATURE] NextJS - bump React to 18

### ISSUE THREAD

**Issue by dan-mba** [EddieHubCommunity/LinkFree#1987]
### Description

React 18 has been out for 6 months.
It is compatible with [NextJS](https://nextjs.org/docs/advanced-features/react-18/overview) & [Storybook](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react18-new-root-api).

With a major redevelopment in progress, now would be a good time to migrate React.
Are there any known blockers for React 18?

I would like to work on this.

**Comment by kumarsonsoff3** [comment]
Closing this issue, since it's fixed by #2007 .
