### ISSUE TITLE
[FEATURE] Add page pages/search.js to Storybook

### ISSUE THREAD

**Issue by RKC3000** [EddieHubCommunity/LinkFree#1989]
### Description
All React components and pages need to be added to Storybook (in the nextjs branch)

> Note
> Each item listed below for component/page should be in a new Issue and PR

- [ ] pages/search.js

### Additional information

#1944 search component in the nextjs branch for storybook.

**Comment by k99sharma** [comment]
Hey, Is this issue still open?

**Comment by RKC3000** [comment]
Yes, I am working on this 
You can select one from #1944

**Comment by k99sharma** [comment]
Sure

**Comment by ThePiyushAggarwal** [comment]
Anyone working on this issue?

**Comment by krshkun** [comment]
There has not been any updates on this PR since a long time 🤔 You can go ahead @ThePiyushAggarwal

**Comment by ThePiyushAggarwal** [comment]
Thanks! I am taking up this issue. 
I saw that we are using Storybook 7 beta version now, so I am thinking of looking into that a bit and raise PR for this issue by Friday 17th

**Comment by ThePiyushAggarwal** [comment]
I am not able to make this work because there is a logger being used in the main page `search.js`

It is not allowing me to create a story based on the page.

 
![image](https://user-images.githubusercontent.com/27003616/229373149-bdf0b995-c9fb-4b91-b683-e71407723e34.png)

**Comment by Nanak360** [comment]
I see that pages/search.js have not been added to storybooks yet. I can take it up and start working on it.

**Comment by SaraJaoude** [comment]
> I see that pages/search.js have not been added to storybooks yet. As nobody is working on this issue, I can take it up and start working on it.

@Nanak360 I will assign this to you

**Comment by ThePiyushAggarwal** [comment]
When I started on this issue, I didn't read the description properly and just went into it.
I raised a couple of PRs creating a story for the Search Input component not the whole page. At the end, I realized they want the whole page in storybook.
I don't have much experience with storybook but I think storybook is used for managing and developing our components separately. Not the whole page. That is why I just unassigned myself. I may be wrong.

**Comment by Nanak360** [comment]
One possible solution for this issue is to divide the search page into child components
![image](https://github.com/EddieHubCommunity/LinkFree/assets/36790357/2f6f48db-90f2-4e05-98f5-cd04786ee78f)

### Page can be divided into 3 components (highlighted with yellow border)
- Tags
- Search bar
- RandomUsersGroup (optional)

We can have separate storybooks for each Component and if needed, one story with all 3 components combined to look like the stories page

**Comment by SaraJaoude** [comment]
We are looking to redesign the site so refactoring into components will happen at that stage - as a result I will close this Issue for now.
