### ISSUE TITLE
Update react-router-dom v6

### ISSUE THREAD

**Issue by E-fais** [EddieHubCommunity/LinkFree#1994]
### Description

Update react router dom to latest version.
Change “Switch” to Routes.

**Comment by aayushbisen** [comment]
Can I work on this issue? @E-fais

**Comment by E-fais** [comment]
> Can I work on this issue? @E-fais

Btw i am not a maintainer here, but still all your genuine PR will get merged. 
Go ahead and create a PR !

**Comment by E-fais** [comment]
@aayushbisen what is the status, are you working on it ?

**Comment by aayushbisen** [comment]
Sorry I don't have the time right now.

Someone else can take if they want.

**Comment by E-fais** [comment]
It’s completely fine , let me do it then 👍

**Comment by eddiejaoude** [comment]
The new version of LinkFree is out that uses NextJS
