### ISSUE TITLE
[FEATURE] Add cross button to close ShareProfile Pop-up

### ISSUE THREAD

**Issue by pavandeveloperr** [EddieHubCommunity/LinkFree#1995]
### Description

Below attached image describes that shareProfile dialog box doesn't have close button or cross icon to close the dialog box. I would love to work on this feature , please assign  me to contribute on this feature.

cons - Without Close icon this dialog box doesn't close and the user has to click come other side on the screen to close the dialog box.

### Screenshots

<img width="954" alt="linkfree_issue_feat" src="https://user-images.githubusercontent.com/63870995/196630972-0826d921-093c-4306-af1a-03fd5776053f.png">

### Additional information
[UPDATE] -> I have added the close button feature which closes ShareProfile dialog box while clicking upon the cross icon. Please do let me know if this feature is allowed to implement on this project . Thank you :) 
<img width="953" alt="linkfree_feat_added" src="https://user-images.githubusercontent.com/63870995/196673475-03c4bbe4-cafa-4fd1-9136-3a6f45db7bee.png">
_No response_

**Comment by ManishBisht777** [comment]
hi i can fix this issue can you assign it to me

**Comment by pavandeveloperr** [comment]
> hi i can fix this issue can you assign it to me

i alread fixed it ... i am waiting maintainers to assign me

**Comment by ManishBisht777** [comment]
Ok

**Comment by eddiejaoude** [comment]
Pull request merged
