### ISSUE TITLE
In Dark Theme,White Glow causes eye-strain while seeing the  Profile names in component/Search

### ISSUE THREAD

**Issue by Anuj-Kumar-AJ** [EddieHubCommunity/LinkFree#1999]
### Description

For the dark Themes, In Component/Search, when we hover over the profile lists, the white glow causes the text to not be visible easily because the text is the same as white color. 

### Screenshots

![2022-10-19](https://user-images.githubusercontent.com/45460554/196753195-d2408d6d-15dd-403d-905f-47c55be6d742.jpg)

**Comment by Anuj-Kumar-AJ** [comment]
I would like to work on it, can you assign this to me :)

**Comment by eddiejaoude** [comment]
@Anuj-Kumar-AJ sorry people already created PRs
