### ISSUE TITLE
[OTHER] Licensing of user profile data

### ISSUE THREAD

**Issue by thamerla** [EddieHubCommunity/LinkFree#2019]
### What would you like to share?

So, as I was reflecting on #1712 - I was thinking about the issue that currently the user profile data hasn't been licensed separately to the project. Since the project is licensed under MIT - that's not just a permissive license to the code, but also to the data, including processing of it.

What are your thoughts on it? Move the data to a dedicated data license? Make the data licensing more restricted? (But then - what about the data before the license change?) Create an info sign ℹ️ in the readme to inform people that their data is open?

**Comment by Akshu-on-github** [comment]
Nice catch, thanks for pointing this out!

> (...) Move the data to a dedicated data license? Make the data licensing more restricted?

I think that either of these would be best. I'm not sure how it'll affect previously collected data, but I think protecting the data that we have rn is paramount

> (...) Create an info sign ℹ️ in the readme to inform people that their data is open?

I think we should have this whether we choose to update our licence(s) or not - after all, those who add their data are obviously doing so on a platform where their data is openly available. I think there are workarounds like self-hosting, but they might not have thought it through 🤔

That being said, maybe this Issue would be better as a discussion?

**Comment by Panquesito7** [comment]
> I'm not sure how it'll affect previously collected data...

AFAIK, we would need to ask all those who added a profile of theirs if they accept to license their profile under a certain license.

**Comment by SaraJaoude** [comment]
Following the GitHub Accelerator workshop on this subject, this does not seem to be a main concern.  We will explore adding to the Contributing Guide a "Developer's Certificate of Origin" for those profiles which are created by raising a PR, given that when forms are introduced as a way to create your profile the date will no longer be held publicly but in a database.  We must remember also that the data in the profiles is publicly available. Therefore, I will be closing this issue.
