### ISSUE TITLE
[FEATURE] Add Font to Profile

### ISSUE THREAD

**Issue by rsinghcodes** [EddieHubCommunity/LinkFree#2023]
### Description

I want to add fonts to profile. Currently, the website is using the default web browser font, however we can use a custom font.

### Additional information

So, please assign it to me, I'll add a google font that will look good.

**Comment by Vishrut19** [comment]
Can I take this issue ? @eddiejaoude

**Comment by eddiejaoude** [comment]
I think we need to discuss the pros/cons of adding a not default font

**Comment by 0x2811aryan** [comment]
Can I take this issue ? @eddiejaoude

**Comment by Vishrut19** [comment]
yes @eddiejaoude I will discuss with you on discord

**Comment by rsinghcodes** [comment]
@eddiejaoude, I would love to discuss. Thanks!

**Comment by eddiejaoude** [comment]
It would be interesting to see the performance of the app before/after - I see some sites loading 7MB for fonts and I just leave

But TBH for now I think let's focus on performance and other improvements

**Comment by eddiejaoude** [comment]
Going to close this as we have many other more features being requested
