### ISSUE TITLE
[FEATURE] adding profile picture of users in chip

### ISSUE THREAD

**Issue by kartikgajjar7** [EddieHubCommunity/LinkFree#2025]
### Description

add profile picture of user with the name in chip with presentable look

review PR for this : #2024

thank you.

### Screenshots

![197398631-0e45664d-9657-4156-bea7-96cf0f3289f4](https://user-images.githubusercontent.com/97971066/197398853-ecb8d122-627f-4c14-ae71-ab14a14d6970.jpg)
![new](https://user-images.githubusercontent.com/97971066/197398477-81228c29-b0fc-4eff-a3d3-fec18d45de32.jpg)
<img width="304" alt="197398515-54886eb5-354f-4822-a884-18713d9c5ab1" src="https://user-images.githubusercontent.com/97971066/197398863-fbb2fff8-63ae-4eab-82c3-838de43075c9.png">

**Comment by Vishrut19** [comment]
I would like to checkout this issue ! @eddiejaoude

**Comment by eddiejaoude** [comment]
The images were removed because it hit the rate limit of GitHub's API. So we need to think of a solution before implementation. Maybe on the search it needs on show no one at first and only when people start typing

**Comment by kartikgajjar7** [comment]
> The images were removed because it hit the rate limit of GitHub's API. So we need to think of a solution before implementation. Maybe on the search it needs on show no one at first and only when people start typing

mean only  when we start typing on searchbar only then pictures should be present ?and normally only username will be there when searchbar is empty

**Comment by eddiejaoude** [comment]
I mean something like... after people type 3 characters then the results start appearing, this should reduce the requests to GitHub

**Comment by kartikgajjar7** [comment]
oh yes this is working well....now chips will come if user add at least 3 characters only....

https://user-images.githubusercontent.com/97971066/197415993-cd39df59-20ee-4efa-aa85-e47887990d48.mp4

**Comment by eddiejaoude** [comment]
can you raise a PR and we can take a better look

**Comment by kartikgajjar7** [comment]
> can you raise a PR and we can take a better look

yes sure

**Comment by kartikgajjar7** [comment]
> can you raise a PR and we can take a better look

kindly check pr related this issue #2024
thanks
