### ISSUE TITLE
In Dark Mode in Search section white Box-shadow creates eye strain

### ISSUE THREAD

**Issue by MAX-786** [EddieHubCommunity/LinkFree#2027]
## Issue
In Dark mode in the search section while hovering over the user component white box-shadow creates eye strain and the user name is not visible.
## Solution
We can simply fix this by adding this `color:black !important` in `.p-chip:hover` pseudo class .

### Screenshots

This is the issue:
![Screenshot (23)](https://user-images.githubusercontent.com/99530996/197406073-0c64c024-18ab-4910-82b7-9c1318401028.png)
And this is the after adding the above line of code :
![Screenshot (25)](https://user-images.githubusercontent.com/99530996/197406118-2bfc14d2-4e3f-4c92-b12b-58c4559d9d35.png)

**Comment by MAX-786** [comment]
Hi @eddiejaoude, can you please assign this issue to me? Thanks

**Comment by eddiejaoude** [comment]
sure @MAX-786  👍

**Comment by skarthikeyan96** [comment]
We already seem to have issue created for the above mentioned problem and also the PR has been raised for the same

https://github.com/EddieHubCommunity/LinkFree/issues/1999
https://github.com/EddieHubCommunity/LinkFree/pull/2014

cc @eddiejaoude

**Comment by eddiejaoude** [comment]
oh thank you @skarthikeyan96 , sorry I missed this, let me look now
