### ISSUE TITLE
Missing commas in Notes section 

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/LinkFree#2033]
### Description

Hi there! I was reading through the Notes section and noticed that the introductory phrases are missing commas after them (see screenshot for reference). Can I be assigned with this task please? Making those changes, will make the directions a bit more clearer. 

### Screenshots

![31629B30-F717-4C6E-90AB-B084F0570CB6](https://user-images.githubusercontent.com/105683440/198051558-4bc83c16-cc11-43d6-98e1-e2a9b009bec1.jpeg)

**Comment by eddiejaoude** [comment]
I think this section has now be removed, as we only have a single branch because `nextjs` was merged into `main`
