### ISSUE TITLE
[ BUG ] Github Actions failing when we review or request changes in PR 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [EddieHubCommunity/LinkFree#204]
![image](https://user-images.githubusercontent.com/76584243/133547132-a6669a07-a696-44b9-b4a0-30bfa6f0737b.png)

## I think this are the runs when I reviewed PR or asked for changes. I don't know why this happens ? Please let me know the possible reason for this

**Comment by schmelto** [comment]
Issue is because of invalid firebase key. We no longer use firebase in our projects. Thus means we can remove it form the statistics workflow.

**Comment by schmelto** [comment]
An example log can be found here https://github.com/EddieHubCommunity/LinkFree/runs/3619349397?check_suite_focus=true

**Comment by rohan-kulkarni-25** [comment]
> An example log can be found here https://github.com/EddieHubCommunity/LinkFree/runs/3619349397?check_suite_focus=true

yeah ! 
If I am not wrong then we need to remove this line right 
https://github.com/EddieHubCommunity/LinkFree/blob/e5192ba99e4ab45e811578a1dc97e146cb19e699/.github/workflows/community.yml#L33

**Comment by ashutosh887** [comment]
I wanted to start contributing to this project
Could someone guide me a bit

**Comment by schmelto** [comment]
> > An example log can be found here https://github.com/EddieHubCommunity/LinkFree/runs/3619349397?check_suite_focus=true
> 
> yeah ! 
> If I am not wrong then we need to remove this line right 
> https://github.com/EddieHubCommunity/LinkFree/blob/e5192ba99e4ab45e811578a1dc97e146cb19e699/.github/workflows/community.yml#L33

Yes from line 26 until 33 it should be removed

**Comment by schmelto** [comment]
> I wanted to start contributing to this project
> Could someone guide me a bit

You can work on this issue if you want as described above the issue here is the failing github action workflow due there is the statistics workflow we no longer need.

**What you have to do:**

Remove the line 26 until 33 from the yml file

If you need some help please let us know

**Comment by rohan-kulkarni-25** [comment]
Hey @ashutosh887 As Tom suggested you can follow the steps below ⬇️ 

- Fork Repository 
- Clone 
- Create new branch ( suggested name : Community Action ) 
- Navigate to `.github/workflows/community.yml` in your version 
- Edit the file 
https://github.com/EddieHubCommunity/LinkFree/blob/e5192ba99e4ab45e811578a1dc97e146cb19e699/.github/workflows/community.yml#L26
https://github.com/EddieHubCommunity/LinkFree/blob/e5192ba99e4ab45e811578a1dc97e146cb19e699/.github/workflows/community.yml#L26
https://github.com/EddieHubCommunity/LinkFree/blob/e5192ba99e4ab45e811578a1dc97e146cb19e699/.github/workflows/community.yml#L26
https://github.com/EddieHubCommunity/LinkFree/blob/e5192ba99e4ab45e811578a1dc97e146cb19e699/.github/workflows/community.yml#L26
https://github.com/EddieHubCommunity/LinkFree/blob/e5192ba99e4ab45e811578a1dc97e146cb19e699/.github/workflows/community.yml#L26

**Comment by kkhitesh** [comment]
Is anyone working on it, if not can I?

**Comment by AbhijithGanesh** [comment]
![image](https://user-images.githubusercontent.com/67182544/133972561-d58b98c3-fc98-4f98-941c-7931d85fdc7f.png)
I think it is acting in a circular manner where the firebase key would be needed to check the same PR ultimately causing actions to fail.
