### ISSUE TITLE
[UI] Remove underline from title in pages

### ISSUE THREAD

**Issue by k99sharma** [EddieHubCommunity/LinkFree#2044]
### Description

The underlined title can be mistaken for links. We can remove the underline and make the title a bit large.

### Screenshots

![Screenshot (69)](https://user-images.githubusercontent.com/54969439/198329043-8e658a0e-03c3-4948-9794-04542937a783.png)

**Comment by dhruvdabhi101** [comment]
I would like to work on this issue

**Comment by k99sharma** [comment]
@dhruvdabhi101 I already have a PR ready, maybe you can look for other issues.

**Comment by k99sharma** [comment]
@eddiejaoude What do you think?

**Comment by dhruvdabhi101** [comment]
> @dhruvdabhi101 I already have a PR ready, maybe you can look for other issues.

okay sir.

**Comment by eddiejaoude** [comment]
Sounds good, please open the PR, I didn't see it?
