### ISSUE TITLE
[NextJS] Migrate to new Image components

### ISSUE THREAD

**Issue by dan-mba** [EddieHubCommunity/LinkFree#2052]
### Description

#2042 migrated the NextJS branch to version 13.
This release created a new [Image](https://nextjs.org/blog/next-13#nextimage) component.
The migration to Next 13 uses the legacy Image component.
There is a [codemod](https://nextjs.org/docs/advanced-features/codemods#next-image-experimental-experimental) available to do most of the work, but it might be preferable to use tailwind classes over the style prop.

**Comment by eddiejaoude** [comment]
I think we can close this now @dan-mba ? There is 1 image apparently remaining, a specific issue got raised here for it https://github.com/EddieHubCommunity/LinkFree/issues/4626

**Comment by dan-mba** [comment]
Closing. Will track in new issue.
