### ISSUE TITLE
[FEATURE] Profile description to use markdown

### ISSUE THREAD

**Issue by DivvSaxena** [EddieHubCommunity/LinkFree#2067]
### Description

Create Profile description.

**Comment by eddiejaoude** [comment]
Great idea! Thanks @Cahllagerfeld 

Q. how do we handle markdown in the json? (idea: have a markdown file for the bio, e.g. `eddiejaoude.md`)

**Comment by Cahllagerfeld** [comment]
potential package that we can use: [react-markdown](https://github.com/remarkjs/react-markdown)

**Comment by eddiejaoude** [comment]
Completed 

<img width="883" alt="Screenshot 2022-11-04 at 20 05 14" src="https://user-images.githubusercontent.com/624760/200065041-400c72b6-5337-4268-a193-f3e6d3b1fbfa.png">

**Comment by Cahllagerfeld** [comment]
Nice, wouldn't have thought that I would be such a low-hanging fruit 🎉
