### ISSUE TITLE
[FEATURE] LinkFree new domain (shorter)

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2068]
### Description

Please check the domain is available first

Example: `link.free`

**Comment by dan-mba** [comment]
FYI `.free` seems to be exclusive to Amazon, but is not available in Route 53 (AWS domain registration service).

`.fr` for France & `.ee` for Estonia seem to have some citizenship specific requirements.

**Comment by schmelto** [comment]
linkfree.org is still available

**Comment by eddiejaoude** [comment]
what about `linkfree.io`?

**Comment by Pradumnasaraf** [comment]
> what about `linkfree.io`? 

Sounds good.

**Comment by eddiejaoude** [comment]
This is now done https://linkfree.io/eddiejaoude

<img width="1671" alt="Screenshot 2023-03-10 at 07 57 15" src="https://user-images.githubusercontent.com/624760/224180177-1f24dcb9-17e9-49ec-9104-636e5c0e6c92.png">
