### ISSUE TITLE
[OTHER] Competitors

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2069]
### What would you like to share?

LinkFree competitors...

- https://limey.io
- https://linktr.ee
- https://bio.link
- https://bio.fm

**Comment by vijay-jaisankar** [comment]
- https://tap.bio/@tap.bio
- https://lnk.bio/
- https://shorby.com/

**Comment by SaraJaoude** [comment]
closing as no actions to be taken
