### ISSUE TITLE
Mobile hover on link buttons

### ISSUE THREAD

**Issue by LinuxGamer** [EddieHubCommunity/LinkFree#2070]
### Description

When hovering on link buttons on mobile it doesn't show right.

### Screenshots

![31504B75-A9B2-42CC-B705-9EBB64BA9365](https://user-images.githubusercontent.com/83363242/198901422-1f6209ea-6a79-446f-aee4-27df06651c82.png)

**Comment by marioenpi1012** [comment]
Hello LinuxGamer, I fixed the issue with the links. I hope they accept the pull request. Have a great day
