### ISSUE TITLE
[UI] Change footer position to bottom of page

### ISSUE THREAD

**Issue by k99sharma** [EddieHubCommunity/LinkFree#2072]
### What would you like to share?

The footer should be at the bottom of the page.  

![Screenshot (79)](https://user-images.githubusercontent.com/54969439/198935666-17e3bace-cba1-4937-8b28-d46ec46d93ae.png)

**Comment by k99sharma** [comment]
@eddiejaoude What do you think? I made a PR to fix this issue.

**Comment by eddiejaoude** [comment]
Great idea 👍 Yes raise the PR
