### ISSUE TITLE
[ Improvement ] Adding Max-width to Links Bar

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [EddieHubCommunity/LinkFree#208]
When we see the links of profile in full screen the width don't look good. We can add a property max width so the width will not go beyond that and will be responsive also 

![image](https://user-images.githubusercontent.com/76584243/133564938-b4b3a0d4-a19c-454a-b25c-db301a8b9d38.png)

I will like to fix it

**Comment by technophile-04** [comment]
can i try to fix this ??

**Comment by FayasNoushad** [comment]
> can i try to fix this ??

@rohan-kulkarni-25 adding that.

**Comment by technophile-04** [comment]
ohh ok so its already taken

**Comment by rohan-kulkarni-25** [comment]
> ohh ok so its already taken

Yes actually PR #209 is for this issue
