### ISSUE TITLE
[OTHER] Test for popular profile. 

### ISSUE THREAD

**Issue by jaynarayan-vaishnav** [EddieHubCommunity/LinkFree#2084]
### What would you like to share?

Test for the most popular profile  to appear at the top of the list when opening the popular page.

**Comment by vasucp1207** [comment]
Hey, @jaynarayan-vaishnav I am interested in this assign this to me.

**Comment by jaynarayan-vaishnav** [comment]
Ig this issue is already merged maybe you could reach out to the project maintainers and ask them about this @vasucp1207

**Comment by krshkun** [comment]
I think #2088 fixed this?

**Comment by eddiejaoude** [comment]
Thanks @krshkun that was for the skeleton but we need the test itself written

**Comment by SaraJaoude** [comment]
This page has now been removed so I will be closing this Issue.
