### ISSUE TITLE
[FEATURE] Google analytics

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2106]
### Description

Add google analytics to the project to track where people come from.

Use environment variable to inject in analytics code

**Comment by vijay-jaisankar** [comment]
Here are some links that might be helpful in this endeavour:

- https://www.npmjs.com/package/@google-analytics/data
- https://support.google.com/sites/answer/97459?hl=en

**Comment by eddiejaoude** [comment]
Thank you @vijay-jaisankar 👍

**Comment by eddiejaoude** [comment]
Feature added in https://github.com/EddieHubCommunity/LinkFree/commit/a89e6e5bb147d4e63ad70eb8a9d1ac616dc9de77
