### ISSUE TITLE
[FEATURE] Repo size badge

### ISSUE THREAD

**Issue by vijay-jaisankar** [EddieHubCommunity/LinkFree#2116]
### Description

In the README an icon that specifies how large the repo size is would be great for people looking to clone the repo.

### Screenshots

For example: ![repo-size](https://camo.githubusercontent.com/0e2bfc14dfa1b2d010cdda8f2b4d4ae92e333c66aab25e98183078984335dcc7/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f7265706f2d73697a652f65636c697073652f73756d6f2e737667)

**Comment by satyamkale27** [comment]
I would like to add this feature please assign it to me
