### ISSUE TITLE
[FEATURE] Social icons

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2132]
### Description

- Display social icons at the top of the profile under the bio text

<img width="1042" alt="Screenshot_2022-11-09_at_9 09 40_AM" src="https://user-images.githubusercontent.com/624760/200786847-ca8f1e51-8f59-4e61-b777-4ea65e9cbd0c.png">

- The profile json will need new field for each socials, here are 2 examples

```json
"socials": {
   "twitter": "..."
   "linkedin": "..."
}
```

**Comment by vasucp1207** [comment]
Hey, @eddiejaoude, I am interested to work on this assign this to me.

**Comment by eddiejaoude** [comment]
Sure, something like this...

<img width="378" alt="Screenshot 2022-11-06 at 11 47 47" src="https://user-images.githubusercontent.com/624760/200168758-b8f9a675-3d7e-4b15-acad-1ec108524505.png">

**Comment by ManishBisht777** [comment]
@eddiejaoude can you elaborate it a little?

**Comment by eddiejaoude** [comment]
btw @ManishBisht777 this is assigned to @vasucp1207

**Comment by ManishBisht777** [comment]
ohh , i didn't notice sorry @eddiejaoude

**Comment by eddiejaoude** [comment]
Discussion from EddieHub Discord, to be more flexible and can support the same icons as the links

```json
"socials": [
   {
       "platform": "twitter",
       "url": "..."
   }
]
```

**Comment by eddiejaoude** [comment]
This was completed and merged 👍
