### ISSUE TITLE
Profile page customization 

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/LinkFree#2133]
### Description

Hi @eddiejaoude! I did some more research on Linkfree and noticed that a common complaint is that free users can’t customize [their landing page ](https://www.producthunt.com/questions/what-are-the-pros-and-cons-of-using-linktree). Maybe we could add this feature to stand out?

**Comment by eddiejaoude** [comment]
Thanks Chrissy! What sort of customisations do you think would be a good idea?

**Comment by CBID2** [comment]
> Thanks Chrissy! What sort of customisations do you think would be a good idea?

Different colors, button shapes, and an option to upload a background that they already have. Lol, that's all I can think of for the moment.

**Comment by thevinitgupta** [comment]
Themes can be added as well for customization.

**Comment by eddiejaoude** [comment]
I think themes might be the best way to go, as with colour clashes it could make their pages unusable

I will close this general issue for now and we can make some more specific ones later on
