### ISSUE TITLE
Deploy app on a cron job

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/LinkFree#2134]
### Description

GitHub Action to deploy the changes from that day

- Digital Ocean CLI to deploy not from changes on `main` (existing GitHub in the marketplace?)
- Digital Ocean Token required in the Org's Secrets

https://docs.digitalocean.com/reference/doctl/reference/apps/create-deployment/

**Comment by Harrish-Selvarajah** [comment]
Hi @eddiejaoude, is this issue open to be taken up ?

**Comment by eddiejaoude** [comment]
Hi @Harrish-Selvarajah, actually I am going to close this issue for the moment, as we are looking to change where we host the app, so this might no longer be needed. Thanks for the reminder, sorry for the inconvenience
