### ISSUE TITLE
[FEATURE] New design for profile section

### ISSUE THREAD

**Issue by ManishBisht777** [EddieHubCommunity/LinkFree#2141]
### Description

 we can have a new design for profile section instead of a plain one to make our profiles look more promising 

although i am not clear with the idea but here is something which is in my head

### Screenshots

![image](https://user-images.githubusercontent.com/89926834/200152385-a1c64c6a-4f96-4253-bad3-839e6223edae.png)

**Comment by CBID2** [comment]
This looks great so far @ManishBisht777! The design is simple yet attractive. Have you thought of anything for the milestone section?

**Comment by ManishBisht777** [comment]
i created a design for milestones section also , here is the rough idea for that 

![image](https://user-images.githubusercontent.com/89926834/200157423-38a5f290-facd-452e-a649-c91246f70c7a.png)

**Comment by ManishBisht777** [comment]
there is also a lot of possibilities by playing with colors

**Comment by ManishBisht777** [comment]
i want to work on this

**Comment by eddiejaoude** [comment]
I would recommend doing each small improvement at a time, it is very difficult to review big changes

Smaller and more PRs are best

**Comment by ManishBisht777** [comment]
Thanks @eddiejaoude 
This issue can be divided into many parts

1) profile section
      1.1) make layout and style it
      1.2) integrated to existing ui
2) socials section
      2.1) make ui for individual social component
      2.2) combine it with the main container
      2.3) Integra it to existing system 
3) milestones section
      3.1) make layout and style it
      3.2) integrate it with system

I will be working on profile section first

**Comment by eddiejaoude** [comment]
I would recommend creating an issue for each section, so that it can be reviewed and merged as we go along

**Comment by ManishBisht777** [comment]
Sure i am planning to do the same

**Comment by ManishBisht777** [comment]
closing this one this has been spilt into multiple issues
