### ISSUE TITLE
[DOCS] Step-by-Guide-for adding Linkfree to GH profile

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/LinkFree#2143]
### Description

I was scrolling through the Linkfree website to see if there was a guide on how to add the link of my Linkfree profile to my GitHub and Linkedin profiles, and I didn’t see one. I think it’ll be beneficial to add this section there.

**Comment by pratushrai0309** [comment]
Hi can someone guide me on this issue?

**Comment by CBID2** [comment]
> Hi can someone guide me on this issue?
> 
> 
Maybe you can look at the format of the current guides and use them as a reference for creating the guide?

**Comment by pratushrai0309** [comment]
> > Hi can someone guide me on this issue?
> > 
> > 
> Hi @pratushrai0309. Do you need clarity or an idea on how to write the guide? 

Would be helpful 🙂

**Comment by CBID2** [comment]
> > > Hi can someone guide me on this issue?
> > 
> > 
> > Hi @pratushrai0309. Do you need clarity or an idea on how to write the guide?
> 
> Would be helpful 🙂
I'm visualizing a written guide with screenshots that show users how they can add a link to their Linkfree profile on their Github profile, social media accounts, Linkedin, and their website.  I came up with this because I was trying to do this myself and thought that other members might be having the same problem. Does that make sense now?

**Comment by pratushrai0309** [comment]
Actually I was asking if you could help me how to write the guide?

**Comment by CBID2** [comment]
> Actually I was asking if you could help me how to write the guide?

Sure! Formatting wise, I think we could do something like this[Getting Started](https://help.twitter.com/en/resources/twitter-guide/twitter-101/how-to-set-up-your-twitter-account-twitter-help)

**Comment by CBID2** [comment]
Here's what I have so far: https://docs.google.com/document/d/1UfYuyhEvpVCTY3B1v74WjIH94KiPaHmUfNPf32jf8d4/edit

**Comment by eddiejaoude** [comment]
Thanks everyone 👍 

We have started making a big push on the docs, there is an open Pull Request that we are working on, and hopefully release the first version of the new docs in about 1 week https://github.com/EddieHubCommunity/LinkFree/pull/2208

You can see what it will look like on the beta deployment (this could break at anytime, so please don't use these links for your profile) https://beta.linkfree.eddiehub.io/docs/quickstart

**Comment by yashsharma8433** [comment]
hey! can i contribute to this

**Comment by yashsharma8433** [comment]
@eddiejaoude can u guide me on this issue , i need some clarity please provide me it would be a great help!

**Comment by eddiejaoude** [comment]
After some thought, we can't write docs for every platform, they have their own docs that are up to date. So I will close this issue.
