### ISSUE TITLE
User not found 

### ISSUE THREAD

**Issue by ManishBisht777** [EddieHubCommunity/LinkFree#2146]
### Description

# Issue 
If someone try to access page with the url like - "https://linkfree.eddiehub.io/manishbisht" there is actually no user in the database with the name so it only shows a empty page with a image "AA"

# Expected
If a user is not found in the database then it " User not found " should be visible on the screen

### Screenshots

![Uploading image.png…]()

**Comment by ManishBisht777** [comment]
I looked into the code and instead of using logical expression ( && )  we can we a ternary expression  ( User ? ( ) : ( ) )    to handle the user not found edge case

![image](https://user-images.githubusercontent.com/89926834/200160791-988587a4-2ba2-4b12-b691-877b70c72646.png)

**Comment by ManishBisht777** [comment]
I looked into the code and instead of using logical expression ( && )  we can we a ternary expression  ( User ? ( ) : ( ) )    to handle the user not found edge case

![image](https://user-images.githubusercontent.com/89926834/200160791-988587a4-2ba2-4b12-b691-877b70c72646.png)

**Comment by eddiejaoude** [comment]
Thanks for creating the issue 👍 a 404 page is important

**Comment by eddiejaoude** [comment]
We redirect to the search page with a message

**Comment by ManishBisht777** [comment]
can i work in this issue?

**Comment by eddiejaoude** [comment]
Sorry Manish, I just saw your comment. I started it already, we can both pair on it. Are you in the EddieHub Discord, let's chat in there?

**Comment by eddiejaoude** [comment]
I think this issue can be split up into a few sections

- [x] redirect to search page if profile not found (Eddie)
- [ ] alert box on the search page
- [ ] condition for alert box on search page... (Eddie)
   - [ ] profile not found (query param trigger)
   - [ ] when searching and no results found
- [ ] automated testing to test both
   - [ ] no results displayed, type 3 wrong characters, still no results display but alert box shown
   - [ ] navigate to an invalid user page and check redirects to search page with alert box
