### ISSUE TITLE
LinkFree name not clear on home page

### ISSUE THREAD

**Issue by CodingSpecies** [EddieHubCommunity/LinkFree#2155]
### What would you like to share?

I don't think think that on the homepage it is very clear the that the site is called Linkfree.
In the screenshot below it says: `It is an open-source alternative to Linktree implemented in JavaScript`. The use of `it is` makes it seem a bit vague and not clear that what is trying to be described it actually Linkfree.

And on the homepage, it doesn't actually state the actual name Linkfree anywhere that can clearly be seen.

![image](https://user-images.githubusercontent.com/70807500/200171161-45f0f7eb-8c3f-4cfa-9785-e9626616d52a.png)

**Comment by eddiejaoude** [comment]
Great point! It should say `LinkFree is an Open Source ...`

**Comment by CodingSpecies** [comment]
However, I can say that LinkFree looks amazing now. I remember when LinkFree was first established, and when I see it now, there is such a positive difference and change.

**Comment by eddiejaoude** [comment]
Thank you @CodingSpecies ! We have more features coming soon too

Don't forget to enable your profile so you can see the stats

**Comment by CodingSpecies** [comment]
@eddiejaoude how do I enable my profile? I have already made a profile, but I am not sure if I need to do anything else to enable the stats. Thanks.

**Comment by eddiejaoude** [comment]
yes you need to add another json property to `true`, because it is off by default, more info in the readme, but any questions lets chat in EddieHub Discord so we don't pollute this issue
