### ISSUE TITLE
Links returning 404 pages in README.md

### ISSUE THREAD

**Issue by CodingSpecies** [EddieHubCommunity/LinkFree#2156]
### Description

The profile links, where it says add your profile, are returning 404 pages when clicked.
https://github.com/EddieHubCommunity/LinkFree#-to-add-your-profile

![image](https://user-images.githubusercontent.com/70807500/200171910-7c399f61-0a7e-45f9-be48-ec558c002157.png)

**Comment by eddiejaoude** [comment]
Great spot! Thank you! The files have moved directories, they are no longer in the `public/data` folder but in the root of the project in `data/`

**Comment by eddiejaoude** [comment]
Closing as a duplicate! Thank you @CodingSpecies
