### ISSUE TITLE
GitHub link open in same page

### ISSUE THREAD

**Issue by Atharv181** [EddieHubCommunity/LinkFree#2159]
### What would you like to share?

When we click on GitHub (present on navigation bar) the repo is opening in same tab. We should open new tab for opening github repo.
![image](https://user-images.githubusercontent.com/73999654/200175943-5da2d43d-6d22-44c3-acf9-100a91929c4d.png)

**Comment by LinuxGamer** [comment]
Can I be assigned to this issue?

**Comment by eddiejaoude** [comment]
Sure, done

**Comment by Atharv181** [comment]
Thank you!
