### ISSUE TITLE
Profile views number not appearing 

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/LinkFree#2162]
### Description

Hi there! I noticed that the profile views number only appears on @eddiejaoude’s profile (see screenshots below). Could this possibly be a bug?

### Screenshots

![6448987D-C176-443A-8173-369645898DDC](https://user-images.githubusercontent.com/105683440/200181151-b841ecba-d921-46f9-a616-572495c6af76.jpeg)
![0AACD105-7842-459C-8710-B964B2536F09](https://user-images.githubusercontent.com/105683440/200181154-e0eb9403-56f5-4fa2-80ee-3c37354ea9b3.jpeg)

**Comment by eddiejaoude** [comment]
By default the data is kept private, you need to enable in your profile for it to be made visible

```json
"displayStatsPublic": true,
```

Here is the full example in the README https://github.com/EddieHubCommunity/LinkFree#-to-add-your-profile
