### ISSUE TITLE
[BUG] Links to inspirational profiles are broken

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/LinkFree#2163]
### Description

Due to the new update, the links to [three inspirational profiles](https://github.com/EddieHubCommunity/LinkFree#-to-add-your-profile) are broken now. This must be fixed as soon as possible.

**Steps to contribute**

_If you've already forked the repository, skip to step 3_

1. Fork the repository [**here**](https://github.com/EddieHubCommunity/LinkFree/fork).
2. Make a new branch named `fix_links`.
3. Open the `README.md` file.
4. From line 98 to 100, replace the current code with the following code:

```markdown
- [Eddie Jaoude](https://github.com/EddieHubCommunity/LinkFree/blob/main/data/eddiejaoude.json)
- [Naomi Carrigan](https://github.com/EddieHubCommunity/LinkFree/blob/main/data/nhcarrigan.json)
- [Kaiwalya Koparkar](https://github.com/EddieHubCommunity/LinkFree/blob/main/data/kaiwalyakoparkar.json)
```

5. Commit and push your changes.
6. Make a [pull request](https://github.com/EddieHubCommunity/LinkFree/compare) in the LinkFree repository.
7. You're done now! You just need to wait until a maintainer reviews your PR.

### Additional information

This is a good first issue. Please leave it open to first-timers and beginners.

**Comment by CodingSpecies** [comment]
@Panquesito7 should #2156 be closed now you have opened a new issue with instructions?
Thank you.

**Comment by Akshu-on-github** [comment]
Is this issue up for grabs? If so, I'd love to help out!

**Comment by eddiejaoude** [comment]
I think so 👍  Yes go for it @Akshu-on-github

**Comment by Akshu-on-github** [comment]
Awesome, I'll open a PR soon

**Comment by Akshu-on-github** [comment]
And it should be done!

**Comment by eddiejaoude** [comment]
Merged, thank you 👍
