### ISSUE TITLE
[FEATURE] Show number of Events

### ISSUE THREAD

**Issue by Shivam-Katare** [EddieHubCommunity/LinkFree#2168]
### Description

 - In the events section, there is a blank page showing whenever there are no events. Instead of this, some message or text should be shown whenever there are no events available

### Example

![Blue Red and Yellow typhography Welcome To Graphic Design Facebook Cover (1600 × 840 px) (1600 × 840 px) (1600 × 840 px) (1)](https://user-images.githubusercontent.com/91705825/200216666-e34fabcf-9beb-41f7-af37-f3e4eb60e47c.png)

This is just an example 👆

**Comment by MeetHrishii** [comment]
Thanks for notifying. I will work on this and resolve this issue ASAP.

**Comment by eddiejaoude** [comment]
This is a great idea 👍 

We have just added something similar for the search page when there are no result, we could move that alert to a component and re-use that - so it is consistent https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/search.js#L65

**Comment by Shivam-Katare** [comment]
> This is a great idea 👍
> 
> We have just added something similar for the search page when there are no result, we could move that alert to a component and re-use that - so it is consistent https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/search.js#L65

Hey @eddiejaoude, can I try to work on this issue?

**Comment by eddiejaoude** [comment]
Sure I will assign it to you
