### ISSUE TITLE
[FEATURE] A video and documented guide to make website

### ISSUE THREAD

**Issue by Ekj0t** [EddieHubCommunity/LinkFree#2173]
### Video and Documentation
A proper video and well documented guide on how non-tech users can make a their portfolio website using LinkFree and make their online presence using the tools of the community out there.

Hope to see this feature available for all soon.

**Comment by ShuvamChatterjee28** [comment]
Hello @eddiejaoude, can I please work on this issue? I can make a video and documentation to use this website.

**Comment by eddiejaoude** [comment]
Thank you, but I have already assigned it to me and I have almost finished it

**Comment by SaraJaoude** [comment]
This has been completed in the QuickStart section of the docs: https://linkfree.eddiehub.io/docs/quickstart

And full docs here: https://linkfree.eddiehub.io/docs
