### ISSUE TITLE
Change number of views for large numbers eq 1000 -> 1k

### ISSUE THREAD

**Issue by ManishBisht777** [EddieHubCommunity/LinkFree#2174]
### Description

# issue
if views go up very much its hard to actually view how much view it actually has instead we can use 1k, 2k, 3k, 1m

## from 
![image](https://user-images.githubusercontent.com/89926834/200347664-506c5810-7b87-4c2b-83c0-48787882b4d1.png)

## to
![image](https://user-images.githubusercontent.com/89926834/200348196-5efe91dc-a733-4b4f-9bff-a1abe8550523.png)

it is a bit more cleaner and coincise

**Comment by vasucp1207** [comment]
@schmelto I am working on this.

**Comment by eddiejaoude** [comment]
@vasucp1207 please only work on 1 issue at a time, this one is currently assigned to you https://github.com/EddieHubCommunity/LinkFree/issues/2132

**Comment by vasucp1207** [comment]
Hey, @eddiejaoude but I completed this one.
