### ISSUE TITLE
[FEATURE] Issue template form that creates the json file with a GitHub Action

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2175]
### Description

1. Issue template
2. GitHub Action creates json and writes file using GitHub username

Note: I don't think this is flexible enough as the form is fixed, for example 3 links

**Comment by vasucp1207** [comment]
@Hey, @eddiejaoude I want to work on this, but can you explain more about this issue to me.

**Comment by eddiejaoude** [comment]
@vasucp1207 you already have another ticket assigned to you, please only do 1 issue at a time

**Comment by deepoa** [comment]
@Hey @eddiejaoude  I want to work on this can u explain me the issue

**Comment by eddiejaoude** [comment]
I think this issue needs more thought, as there are some limitations - please select another issue for now

**Comment by SaraJaoude** [comment]
Due to limitation and expectation to move this to a form, I am closing this issue.
