### ISSUE TITLE
Add custom favicon

### ISSUE THREAD

**Issue by CodingSpecies** [EddieHubCommunity/LinkFree#218]
In the `public` folder, maybe we could add a custom favicon, than the pdefault react logo? Thank you.

**Comment by ShlokMohanty** [comment]
@CodingSpecies is this issue being done or still we need to add the favicon ?

**Comment by CodingSpecies** [comment]
@ShlokMohanty this issue I have not began working on. Thanks

**Comment by CodingSpecies** [comment]
If you want I can, but I will have to find a favicon, that won't affect copy right, unless we use something by eddiehub?

**Comment by CodingSpecies** [comment]
maybe using something like this for the branding repo?

<img src="https://user-images.githubusercontent.com/624760/114314271-ea156a80-9af1-11eb-97ca-977be7565aa6.png" height="100" />

**Comment by ShlokMohanty** [comment]
> If you want I can, but I will have to find a favicon, that won't affect copy right, unless we use something by Eddiehub?

@CodingSpecies can we take the permission on this from @eddiejaoude ?

**Comment by CodingSpecies** [comment]
Yes, That is a good idea @ShlokMohanty

**Comment by Cahllagerfeld** [comment]
I'd say you can just do it. In case eddie isnt fine with it, the PR will get closed but you still get your green squares for it (: So go for it 😄

**Comment by rohan-kulkarni-25** [comment]
Please discuss here :- https://github.com/EddieHubCommunity/LinkFree/discussions/206

**Comment by eddiejaoude** [comment]
Great discussion everyone 👍 , I think using the EddieHub mascot for the favicon is a great idea, until we have something more specific

**Comment by Yash621** [comment]
@CodingSpecies can I work on this issue ? I am a beginner and want to start my journey in open source ,so can you assign me this issue ?

**Comment by CodingSpecies** [comment]
@Yash621 I have begun adding this to a pr, but what we need is a real favicon that is suitable to this project, as what I am doing is a temporary favicon. If you would like, you could find a favicon that doesn’t go against copyright and we can use. Thank you!

**Comment by Yash621** [comment]
okay ,I will try to do it ,thank you!!

**Comment by schmelto** [comment]
Reopening due we only have added a temporary favicon

**Comment by krishguptadev** [comment]
Could I be assigned to this issue? btw is their a specific reason for the favicon being temporary so that I can take care of it?

**Comment by krshdev** [comment]
Not stale yet (comment to remove stale)

**Comment by darkknight20032001** [comment]
is there anyone available???i need to contribute to this project

**Comment by CodingSpecies** [comment]
@darkknight20032001 yes, we are here to help. If you wish to contribute, feel free. See the discussion, as there is favicons and inspirations there: https://github.com/EddieHubCommunity/LinkFree/discussions/206

Any help or questions feel free to ask.

**Comment by KendallDoesCoding** [comment]
Why is the label as "[🚧 status: blocked](https://github.com/EddieHubCommunity/LinkFree/labels/%F0%9F%9A%A7%20status%3A%20blocked)". Is this issue not being worked on as of now?

**Comment by CodingSpecies** [comment]
@KendallDoesCoding this issue is blocked as we have a discussion #206 
Where we are making logos for this project. Once we finalise on a logo, this issue will no longer be blocked!

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding this issue is blocked as we have a discussion #206 Where we are making logos for this project. Once we finalise on a logo, this issue will no longer be blocked!

Ok cool!

**Comment by eddiejaoude** [comment]
We have one of the EddieHub mascots for the favicon, so I will close this for now
