### ISSUE TITLE
[FEATURE] New design for socials section

### ISSUE THREAD

**Issue by ManishBisht777** [EddieHubCommunity/LinkFree#2182]
### Description

this issue is with continuity with #2171 

the links section design can be changed from horizontal to grid-type style like

### Screenshots

![image](https://user-images.githubusercontent.com/89926834/200618098-95e3e2d6-8022-4390-b778-e931f86c93ca.png)

**Comment by ManishBisht777** [comment]
i am working on this

**Comment by SwapnilPatle01** [comment]
looking nice

**Comment by SaraJaoude** [comment]
This can come as part of the layout theme later on, so I will close this Issue for now and a new one could be created later.
