### ISSUE TITLE
[FEATURE] QR code page from profile 

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2187]
### Description

It would be great to have a page that generates a QR for people to use to share their profile link that others can scan

- link from profile page to unique QR code page
- QR code page to have only the name, bio, pic, and then the QR code big
- QR code to be url to users profile page

**Comment by Vishrut19** [comment]
@eddiejaoude so basically you need a qr code generator to generate unique QR code for each user ?

**Comment by eddiejaoude** [comment]
@Vishrut19 yes, I added more info to the description

**Comment by furkanmutlu** [comment]
Hi @eddiejaoude , can you assign me to work on this issue ?

**Comment by eddiejaoude** [comment]
Sure 👍
