### ISSUE TITLE
Horizontal Scroll Bar on landing page

### ISSUE THREAD

**Issue by developer-diganta** [EddieHubCommunity/LinkFree#2194]
### Description

An overflow results in a scroll bar on the landing page.

### Screenshots

![image](https://user-images.githubusercontent.com/65999534/200935151-75c1f64f-f472-419b-9caf-04bfdf10820a.png)

### Additional information

If this seems relevant, can I work on it?

**Comment by dan-mba** [comment]
I found the problem.

In Chrome, the vertical scrollbar causes the width of 100vw to overflow.

Adding a class of `max-w-[100%]` to the div that is the parent of the img should fix the problem.

Go ahead and submit a Pull Request for this

**Comment by eddiejaoude** [comment]
@dan-mba thank you 👍

**Comment by dan-mba** [comment]
> @dan-mba thank you 👍

@eddiejaoude Well it was my PR that caused this issue, so i wanted to know why.
I normally use Firefox, so I didn't know the difference in how it & Chrome handle 100vw & scroll bars.

**Comment by Rishav1707** [comment]
@developer-diganta Will you assign this problem to me??
