### ISSUE TITLE
When adding more commits to a PR labeling is not correct

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/LinkFree#2197]
### Description

When adding more commits to a PR the label action for using label `small`, `medium` etc. is not removing the old label if the state changes from for example small to medium.

**Comment by dan-mba** [comment]
In the label-pull-request-with-size section of [reviewpad.yml](https://github.com/EddieHubCommunity/LinkFree/blob/a09b120bc29259e950a0ccd0d977e67b4bf5b7de/reviewpad.yml#L28) the actions need to be modified to remove labels.

There is an example in the Reviewpad [removeLavels](https://docs.reviewpad.com/guides/built-ins#removelabels) documentation.

**Comment by Harsh-Daga** [comment]
Hey . I would like to work on this issue :)

**Comment by Harsh-Daga** [comment]
Hey , 
I would like to work on this issue if it is not resolved yet :)

**Comment by schmelto** [comment]
@Harsh-Daga go for it

**Comment by Rishav-12** [comment]
Hey, I was looking at the open issues and noticed that this issue has been resolved by PR #2230. I think this can be closed now.
