### ISSUE TITLE
[FEATURE] Automated tests to move to PageObject model

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2199]
### Description

Automated tests to move to PageObject model

Official Playwright documentation https://playwright.dev/docs/pom

**Comment by arpitapandya** [comment]
Hey, @eddiejaoude can you assign me to work on this issue?:blush:

**Comment by eddiejaoude** [comment]
Sure @arpitapandya 👍

**Comment by arpitapandya** [comment]
Hey, @eddiejaoude I am sorry for taking longer than I expected, Almost ready, I will submit PR by next week.

**Comment by eddiejaoude** [comment]
no problem @arpitapandya , when you get time. 

Remember you don't need to do it all, you can do 1 example - actually it is best to keep it small, make a small improvement and submit a pull request

**Comment by arpitapandya** [comment]
> no problem @arpitapandya , when you get time. 
> 
> 
> 
> Remember you don't need to do it all, you can do 1 example - actually it is best to keep it small, make a small improvement and submit a pull request

Oh Thanks @eddiejaoude I thought I have to write all the test cases

**Comment by eddiejaoude** [comment]
oh no, not at all, it is better if you don't as it is much more difficult to review so many changes - maybe select 1 test file
