### ISSUE TITLE
[FEATURE] Accessibility checks to run as part of automated testing

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2200]
### Description

Playwright has accessibility testing built in, but we need to config it https://playwright.dev/docs/accessibility-testing

**Comment by eddiejaoude** [comment]
YES please, that would be great 👍 I will assign it to you

**Comment by YuriDevAT** [comment]
Hey Eddie! 👋🏽   May you assign someone else for this issue? I am still facing problems with connecting to the DB, storybook complaining that it is not installed after several removes, reinstalled, and completely new forks of the project itself, the same is for playwright. 

If the ticket it still available in January, I would come back to it. 😇

**Comment by money8203** [comment]
Hey can someone tell me what it is about and how can I contribute to it ?

**Comment by eddiejaoude** [comment]
@YuriDevAT sounds like it is something we need to fix/improve on the project, let me know if you want to work through together, because I am sure others are having similar challenges and I would like to improve the developer experience on the project

**Comment by YuriDevAT** [comment]
I do face problems with another OS project as well, everything was working fine during Hacktober, but now.. I think it has something to do with my node. Should I have time this weekend, I will let your team know in Discord if someone has time to help me via screen sharing. I hope this is fine with you. Sorry for the inconvenience.

**Comment by eddiejaoude** [comment]
Yes let us know in EddieHub Discord and we can help 👍  no problem, it happens to us all
