### ISSUE TITLE
[FEATURE] Documentation to be loaded into the app

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2203]
### Description

Markdown files could be loaded into the app, so they can be seen directly on there

**Comment by SaraJaoude** [comment]
Adding Basic Profile
<img width="1647" alt="Screenshot 2022-12-17 at 15 50 51" src="https://user-images.githubusercontent.com/82668196/208292174-4aabccc8-39d8-4554-8e7c-9d2d14c270bf.png">
<img width="1657" alt="Screenshot 2022-12-17 at 15 51 10" src="https://user-images.githubusercontent.com/82668196/208292176-fb2bedf9-8dd1-4fff-b422-30d54f2fdd48.png">
<img width="1676" alt="Screenshot 2022-12-17 at 15 51 28" src="https://user-images.githubusercontent.com/82668196/208292177-7f1fe62e-a73d-4070-8a57-ca3ec47812fc.png">
<img width="1668" alt="Screenshot 2022-12-17 at 15 52 04" src="https://user-images.githubusercontent.com/82668196/208292178-92daccad-293d-407a-9d8d-0a86b63d6bd7.png">
<img width="1651" alt="Screenshot 2022-12-17 at 16 09 08" src="https://user-images.githubusercontent.com/82668196/208292180-e0caee14-5eb3-42f1-9035-dabae4ce84f6.png">
<img width="1666" alt="Screenshot 2022-12-17 at 16 34 17" src="https://user-images.githubusercontent.com/82668196/208292185-743dc114-5699-4b58-bf5c-c5fc74f0248d.png">
<img width="1668" alt="Screenshot 2022-12-17 at 16 36 25" src="https://user-images.githubusercontent.com/82668196/208292186-d954f0e5-bdb0-4177-ac14-eb5d99b329dd.png">
<img width="840" alt="Screenshot 2022-12-17 at 16 36 58" src="https://user-images.githubusercontent.com/82668196/208292189-513b4213-a3a7-4a45-a834-ac6ce6b9217a.png">
<img width="1678" alt="Screenshot 2022-12-17 at 16 42 42" src="https://user-images.githubusercontent.com/82668196/208292191-3138b90c-ed2e-4da5-8a33-ca645dff3661.png">
<img width="1679" alt="Screenshot 2022-12-17 at 16 47 39" src="https://user-images.githubusercontent.com/82668196/208292192-704402e7-c2d6-432e-8dab-cb6a678866c1.png">
<img width="1677" alt="Screenshot 2022-12-17 at 16 48 07" src="https://user-images.githubusercontent.com/82668196/208292196-c374d328-6bed-4f7b-adbc-b55c29b7c367.png">
<img width="1671" alt="Screenshot 2022-12-17 at 16 51 12" src="https://user-images.githubusercontent.com/82668196/208292199-e7a01541-5356-4b2f-8b3e-94be121c661f.png">

**Comment by SaraJaoude** [comment]
Edit Basic Profile
<img width="1670" alt="Screenshot 2022-12-18 at 10 14 38" src="https://user-images.githubusercontent.com/82668196/208293646-6fbbabe6-f6c6-429f-aaa4-fc77876ce691.png">
<img width="1669" alt="Screenshot 2022-12-18 at 10 16 03" src="https://user-images.githubusercontent.com/82668196/208293648-efd3e4ef-2094-4e42-ad33-3e09286c8809.png">
<img width="1669" alt="Screenshot 2022-12-18 at 10 16 03" src="https://user-images.githubusercontent.com/82668196/208293651-c9710673-8b77-4544-a0ac-ff9a22dd4603.png">
<img width="1662" alt="Screenshot 2022-12-18 at 10 17 13" src="https://user-images.githubusercontent.com/82668196/208293657-8e0508c7-f8aa-45db-9f98-2ce9662ac1d8.png">
<img width="1672" alt="Screenshot 2022-12-18 at 10 20 08" src="https://user-images.githubusercontent.com/82668196/208293664-85ac522b-6fc4-4e79-863f-389d8a337f43.png">
<img width="1663" alt="Screenshot 2022-12-18 at 10 21 56" src="https://user-images.githubusercontent.com/82668196/208293668-a531c53e-0706-49c0-bac0-b665c9d8fecc.png">
<img width="1664" alt="Screenshot 2022-12-18 at 10 29 21" src="https://user-images.githubusercontent.com/82668196/208293672-3c9480d3-9cf0-452c-8f5f-48559246bc2e.png">
<img width="1663" alt="Screenshot 2022-12-18 at 10 32 24" src="https://user-images.githubusercontent.com/82668196/208293677-79bd2bb8-ee23-4aed-bfef-ea438a9ef3c5.png">
<img width="1671" alt="Screenshot 2022-12-18 at 10 34 19" src="https://user-images.githubusercontent.com/82668196/208293679-822b4d1e-ecc9-49f5-b363-4a0ecf9922f4.png">

**Comment by eddiejaoude** [comment]
Statistics

<img width="1305" alt="Screenshot 2022-12-21 at 11 52 41" src="https://user-images.githubusercontent.com/624760/208899278-98cd94ee-3d13-4d27-80ee-c7ae0b1e737e.png">

**Comment by eddiejaoude** [comment]
Social shortcut icons

<img width="1292" alt="Screenshot 2022-12-21 at 17 59 51" src="https://user-images.githubusercontent.com/624760/208973239-cc6a8541-3e34-47fd-8f76-104a3cf6ee4f.png">

**Comment by SaraJaoude** [comment]
GitHub Action fail
![Screenshot 2022-12-21 at 18 21 06](https://user-images.githubusercontent.com/82668196/208976820-242c8b87-2108-480a-9882-a1f8dc652e89.png)

**Comment by eddiejaoude** [comment]
Tags

<img width="1325" alt="Screenshot 2022-12-21 at 18 51 28" src="https://user-images.githubusercontent.com/624760/208981563-7cab5d55-8996-4e90-9af1-6dd3edba0235.png">

**Comment by eddiejaoude** [comment]
Markdown in bio

<img width="607" alt="Screenshot 2022-12-21 at 19 13 32" src="https://user-images.githubusercontent.com/624760/208985171-9f337433-92c6-43b7-86a4-05d6af691690.png">

**Comment by eddiejaoude** [comment]
Milestones

<img width="1263" alt="Screenshot 2022-12-22 at 19 13 15" src="https://user-images.githubusercontent.com/624760/209209651-87e4f75f-425d-4837-82d0-84030e82ae6f.png">

**Comment by eddiejaoude** [comment]
Events

<img width="1269" alt="Screenshot 2022-12-23 at 15 13 12" src="https://user-images.githubusercontent.com/624760/209358117-84f3d893-065e-4ff3-a5e7-6533752306c5.png">
<img width="1270" alt="Screenshot 2022-12-23 at 15 13 04" src="https://user-images.githubusercontent.com/624760/209358132-0a3e20a8-a996-4a9f-b9c3-90d3056d2cf3.png">

**Comment by eddiejaoude** [comment]
Sara's profile
<img width="1269" alt="Screenshot 2022-12-23 at 15 37 43" src="https://user-images.githubusercontent.com/624760/209361460-61d05252-24ce-4417-86b4-72e18f8fec54.png">
