### ISSUE TITLE
[DOCS] Add Linkfree-CLI project to ReadMe file

### ISSUE THREAD

**Issue by krupalitrivedi** [EddieHubCommunity/LinkFree#2206]
### Description

Adding @Pradumnasaraf 's Linkfree profile generator in CLI will be great. 
The link to repo can be found here: https://github.com/Pradumnasaraf/LinkFree-CLI

Suggestions discussed on live stream:

- Add a *note* above the existing note with the following content: (you can use your content)
"You can generate the code for your profile using Pradumna's Linkfree-CLI profile generator." 

You can also look at a parallel issue raised here to add Tom's repo: #2207 
(Don't forget to add the link to the repo)

![image](https://user-images.githubusercontent.com/99717469/201387887-06dfc73d-7aba-4e02-849f-27806a772422.png)

**Comment by krupalitrivedi** [comment]
I'd like to get assigned with this issue :)

**Comment by Pradumnasaraf** [comment]
Sure, thank you.
