### ISSUE TITLE
[DOCS] Add Linkfree_profile generator: UI version to ReadMe

### ISSUE THREAD

**Issue by krupalitrivedi** [EddieHubCommunity/LinkFree#2207]
### Description

Adding @schmelto 's Linkfree profile generator to the ReadMe will be amazing!
The link to the repo can be found here: https://github.com/schmelto/LinkFree_generator

Suggestions discussed on the live stream:
- Add a *note* above the existing note with the following content: (you can use your content)
"You can generate the code for your profile using Tom's Linkfree profile generator." 

You can also look at a parallel issue raised here to add Pradumna's repo: #2206 
(Don't forget to add the link to the repo)

![image](https://user-images.githubusercontent.com/99717469/201387887-06dfc73d-7aba-4e02-849f-27806a772422.png)the

**Comment by SaraJaoude** [comment]
Log in and form will be added soon to the project, so this is no longer required.
