### ISSUE TITLE
[FEATURE] Timeline for latest version

### ISSUE THREAD

**Issue by vasucp1207** [EddieHubCommunity/LinkFree#2213]
### Description

- Improve user timeline for the user version.

### Screenshots

https://user-images.githubusercontent.com/85363195/201461094-88e303e3-ec59-4286-803b-89deb7d0ed84.mov

#### @eddiejaoude assign this to me the implementation is almost complete.

**Comment by eddiejaoude** [comment]
It looks good, I think this takes a lot of vertical space, and we have more information coming. We should probably discuss it, maybe if you have started the changes, can you create a draft PR so it can be discussed

**Comment by eddiejaoude** [comment]
This has been refactored with Tailwind UI components
