### ISSUE TITLE
Getting Username on Hover over Avatar

### ISSUE THREAD

**Issue by aayush89890** [EddieHubCommunity/LinkFree#222]
We can show the username once a person hover over an Avatar.

## Expected Behaviour
![Screenshot (59)](https://user-images.githubusercontent.com/37421316/133723100-809ef0af-d92e-4279-bf1e-837e21e8f20c.png)

**Comment by ShlokMohanty** [comment]
@aayush89890 , @eddiejaoude is this showing name when hovered over done or still needs to be done ?

**Comment by aayush89890** [comment]
> @aayush89890 , @eddiejaoude is this showing name when hovered over done or still needs to be done ?

Hi @ShlokMohanty this issue needs to be fixed.
If you want to give it a try go ahead.

**Comment by Cahllagerfeld** [comment]
its a duplicate of #96

**Comment by Cahllagerfeld** [comment]
closed, reason see above (:
