### ISSUE TITLE
[FEATURE] Popular Page styles

### ISSUE THREAD

**Issue by ManishBisht777** [EddieHubCommunity/LinkFree#2221]
### Description

Changing popular styles section to a more compact grid style view to fit more profiles in the same space like

### Screenshots

![image](https://user-images.githubusercontent.com/89926834/201471568-5b55fdeb-4e19-47a5-90d2-b9eba9ab79df.png)

**Comment by ManishBisht777** [comment]
i am working on this

**Comment by ManishBisht777** [comment]
@eddiejaoude this is how it is looking for now
![image](https://user-images.githubusercontent.com/89926834/201474257-1f1ef5f7-b9d3-402a-ab8d-4b5689f30a0a.png)

**Comment by ManishBisht777** [comment]
Also, the search page is also affected by the same I will address that after this pr gets merged
![image](https://user-images.githubusercontent.com/89926834/201474318-df78b737-07ab-48e2-acff-f08228bfceb1.png)

**Comment by eddiejaoude** [comment]
> Also, the search page is also affected by the same I will address that after this pr gets merged

@ManishBisht777 it looks good, but we cannot fix after the merge because it will break the search page

**Comment by ManishBisht777** [comment]
@eddiejoude should i fix that i this pr itself?

**Comment by ManishBisht777** [comment]
@eddiejaoude i update the following changes to a new component and reverted the changes in prev component
