### ISSUE TITLE
[DOCS] Add Missing Preposition & Change in Guidelines

### ISSUE THREAD

**Issue by Sriparno08** [EddieHubCommunity/LinkFree#2229]
### Description

Hey EddieHub, I have found an issue in the **README.md** file!

In the below screenshot, we can see an arrow under the **A Note for Hacktoberfest Participants** section, located in README.md. This arrow suggests that the "Maintainers will opt-in these PRs" portion should be changed to "Maintainers will opt-in **to** these PRs" as the preposition "**to**" is missing from the portion.

Moreover, the line says, "Maintainers will opt-in these PRs by applying the `hacktoberfest-accepted` label." This needs to change as the project now contains the `hacktoberfest` topic, so the PRs will be automatically counted towards Hacktoberfest. However, profile update PRs that have the label `invalid` will not be counted towards Hacktoberfest.

### Screenshots

![Missing-Preposition](https://user-images.githubusercontent.com/89148144/201511900-2a2f6f58-ef7c-4e85-b459-24775bc6c3d6.jpg)

**Comment by Sriparno08** [comment]
I would also like to work on this issue!

**Comment by eddiejaoude** [comment]
Thank you raising the issue 👍 

The project has the `hackatobefest` topic, so it is all opt in now, but profile update PRs have the label `invalid` as not to count for hackatoberfest - if you could update the message to explain this, that would be great 👍

**Comment by Sriparno08** [comment]
Thanks for interacting, @eddiejaoude 👍

I have updated the message! Please have a look!

**Comment by eddiejaoude** [comment]
Thanks for updating 👍

**Comment by Sriparno08** [comment]
You're welcome, Eddie!

Also, can I work on this issue please?

**Comment by LinuxGamer** [comment]
Is anyone working on this?

**Comment by eddiejaoude** [comment]
@Sriparno08 are you working on this issue? If not we can assign it to @LinuxGamer

**Comment by Sriparno08** [comment]
Yes, I have just started working on this issue, @eddiejaoude!
