### ISSUE TITLE
[OTHER] Improvement: Update Github link to icon instead of text

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#2249]
### What would you like to share?

In the header of the linkfree page to the right, the Github link is currently text.  This should be updated to the Octocat icon.

Exact location in a red box in the ss below
![Image of linkfree site cropped to show Github as text in upper right corner](https://user-images.githubusercontent.com/97615019/202914510-c26eb8d8-ba5b-4bd5-8929-d6cc52df7560.png)

**Comment by eddiejaoude** [comment]
Thank you Amanda! 👍 

Just to let you know we have an Icon component that you might be able to use or use it's code for ideas
https://github.com/EddieHubCommunity/LinkFree/blob/main/components/Icon.js

**Comment by amandamartin-dev** [comment]
Fantastic! And happy to take on  this issue as well as my first

**Comment by eddiejaoude** [comment]
Great! I will assign it to you 👍

**Comment by amandamartin-dev** [comment]
My code is complete, but I am having a terrible time getting the tests to run.  I am very unfamiliar with how to debug playwright tests, but after many warnings about dependencies and then finally getting the tests to run - they all timeout. Any thoughts are welcome here!
I am working in gitpod, macOS 12.5.1, chrome - current

**Comment by eddiejaoude** [comment]
Oh no sorry to hear you had issues running the tests @amandamartin-dev - can you share a screenshot and we can try to solve it for you and the next person

I would recommend pushing your changes to a pull request and let Github Actions run the tests because I think they will pass

**Comment by amandamartin-dev** [comment]
@eddiejaoude You were correct! Just more configuration issues likely but this was certainly low risk to PR.  Let me know if I have missed anything if you (or to any other reviewer) notice something I should have done differently in this process or my code choices.  

Here are the screenshots, definitely config related so I can surely take another stab next time I work on an issue and see if i can get further.
![db_connect_error](https://user-images.githubusercontent.com/97615019/202927079-54f8031e-6958-4527-9062-b72f4c1a4992.jpg)
![test_error_example](https://user-images.githubusercontent.com/97615019/202927095-193205cd-818f-4adf-84b0-3d28b466b9f6.jpg)

**Comment by eddiejaoude** [comment]
Oh it looks like it cannot get access to MongoDB, we should raise a bug for that (would you like another green square?)

**Comment by amandamartin-dev** [comment]
Ahhh, I thought it was me! I will open that up soon.

**Comment by eddiejaoude** [comment]
Great, thank you 👍
