### ISSUE TITLE
Need To Increase margin right and bottom of Avatars To decrease White Space

### ISSUE THREAD

**Issue by aayush89890** [EddieHubCommunity/LinkFree#225]
Bottom half of the home page is blank we can increase some margin to fill this gap.

## Actual Behavior

![image](https://user-images.githubusercontent.com/37421316/133748357-ef0e4132-892d-4da0-89ad-9cbf1ca9f457.png)

## Expected Behavior

![image](https://user-images.githubusercontent.com/37421316/133748730-f84badb9-d62e-43a6-b802-c9ad058d513a.png)

Example : 
```
.margin {
  margin-bottom: 1em;
  margin-right: 1em;
}
```

**Comment by voidz7** [comment]
What if we add some kind of welcome screen or search system or @EddieHubCommunity logo etc on the home page 🤔 ?

**Comment by aayush89890** [comment]
> What if we add some kind of welcome screen or search system or @EddieHubCommunity logo etc on the home page 🤔 ?

That's a great idea! Go ahead and create a issue for that.

**Comment by eddiejaoude** [comment]
@voidz7 I think search would be difficult now, but easier when we move it to the API? But if there is an easy way I am not away of, then we can try it 👍 Maybe started a new issue/discussion as it is not related to this one

@aayush89890 we use PrimeReact, so we use prebuilt classes where possible

**Comment by aayush89890** [comment]
Ok than, should I close this issue? @eddiejaoude

**Comment by eddiejaoude** [comment]
Personally I think the spacing is ok. Probably best and you can create other issues and PRs 🤓 - thank you for the suggestion

**Comment by aayush89890** [comment]
Sure. Thanks for you feedback @eddiejaoude .
Closing this issue.
