### ISSUE TITLE
[OTHER] Improvement: Increase discoverability of clickable QR code

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#2250]
### What would you like to share?

The animated QR code on the user image is clickable, but this is not obvious.  It would increase the UX of the site to make it easier to know that this is a link

Image shows the location of the QR code at the bottom left of the user profile image
![screenshot of linkfree page with a red arrow pointing to the qr code location](https://user-images.githubusercontent.com/97615019/202914956-64e8d9ef-a19c-4bc2-b4ee-37669e9995a1.jpg)

**Comment by DeeptanshuDas** [comment]
Hi can I work on this issue?

**Comment by amandamartin-dev** [comment]
@DeeptanshuDas Sorry for the delay in responding, I missed your comment.  I am fine with you taking this issue if you are still looking to work on it, but I do not have permissions to assign.

**Comment by akash19coder** [comment]
@amandamartin-dev It seems this issue is still open and @DeeptanshuDas  hasn't replied. I would like to work on this issue.

**Comment by eddiejaoude** [comment]
Sure I have assigned it to you @akash19coder as I think they are no longer interested

**Comment by akash19coder** [comment]
@eddiejaoude I have forked and cloned the repo but I am not sure where to start from?

**Comment by eddiejaoude** [comment]
@akash19coder what ideas do you have? maybe making it larger?

**Comment by akash19coder** [comment]
@eddiejaoude How about making a little shift? 😄 
![Eddie Jaoude](https://user-images.githubusercontent.com/72060440/211452971-eb063ee2-a070-4c38-b05f-62ba2fb0321c.JPG)

**Comment by eddiejaoude** [comment]
I think that is too confusing, this section is for social icons, keeping it separate would be better

**Comment by arun-kushwaha04** [comment]
Hey @eddiejaoude can i work on this feature. i would suggest that we can add some box shadow so that it catches users attention and also we can make it a little bit bigger.

**Comment by amandamartin-dev** [comment]
Hey @arun-kushwaha04 , I see that @akash19coder is currently assigned to this issue. Let's see if they are still interested and working on it first.  You both can also collaborate if you like!

**Comment by akash19coder** [comment]
@eddiejaoude I have increased the size and changed its color into red 😃

**Comment by SaraJaoude** [comment]
We suggest making the icon size bigger and possibly having a faded background.

**Comment by ThePiyushAggarwal** [comment]
Hello!

Can someone please assign this issue to me?

I have already experimented with it. I haven't increased the size of the component. I have just given it a faded background.
I feel the size is alright. Please let me know if you think we should increase it. The image below is captured after zooming into the browser.

![image](https://user-images.githubusercontent.com/27003616/218312225-da981cef-41de-41d3-bd12-86030103d7db.png)

**Comment by krshkun** [comment]
Would it not make sense to just have it on the dashboard 🤔 Why would someone else need to have a QR code to my profile. Just my opinion though.

Also @ThePiyushAggarwal we only assign contributors to 1 issue at a time  afaik

**Comment by ThePiyushAggarwal** [comment]
Eddie worked on this issue himself today. PR #4479 
![image](https://user-images.githubusercontent.com/27003616/218324169-a20a659e-ea06-46ae-a855-2b4559129c61.png)

**Comment by eddiejaoude** [comment]
I moved all badges to a single reusable component. There might be further improvements to the QR code badge?

**Comment by amandamartin-dev** [comment]
> I moved all badges to a single reusable component. There might be further improvements to the QR code badge?

I think it's much more visible now with the orange background but not sure how others feel

**Comment by eddiejaoude** [comment]
Maybe let's close it for now and the issue could be created again if required

@ThePiyushAggarwal thank you for contributing, have a look at our other issues that have the label `ready for dev` and are not assigned yet
