### ISSUE TITLE
Remove outdated Gitpod demo from the README

### ISSUE THREAD

**Issue by Pradumnasaraf** [EddieHubCommunity/LinkFree#2255]
### Description

Remove the outdated Gitpod demo from the README. The demo was based on v1 of the project

Things to remove
- Heading along with the GIF

<img width="1191" alt="Screenshot 2022-11-21 at 4 07 17 PM" src="https://user-images.githubusercontent.com/51878265/203030107-eae5be6e-3658-44a0-a8be-7b20b728d5aa.png">

**Comment by ShorunTech** [comment]
Let me work on this right away.

**Comment by Pradumnasaraf** [comment]
I have assigned you the issue @ShorunTech. You can start working on it.
Thank you

**Comment by ShorunTech** [comment]
I deleted the previous fork project, which I don't have to in the first place but because it was bringing conflict for me.
I had to create new PR and also create new branch. but I guess it's resolved now.

**Comment by Pradumnasaraf** [comment]
Fix #2371
