### ISSUE TITLE
Unable to connect to DB in gitpod - tests failing

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#2257]
### Description

When running tests in gitpod in the browser IDE, tests fail due to no DB connection.  Suspect a configuration issue.

**Steps to recreate:**
1. create a branch
2. run project in gitpod
3. in terminal, run command: npm test

See error in SS below

![db_connect_error](https://user-images.githubusercontent.com/97615019/203057266-3b25ae9a-9229-4b57-b0dd-cfafa013e770.jpg)

**Comment by amandamartin-dev** [comment]
Please see the screenshots below for example errors

test failure
![test_error_example](https://user-images.githubusercontent.com/97615019/203062927-558bcd3b-2d61-4b44-b845-23b384063dbb.jpg)

DB error
![db_connect_error](https://user-images.githubusercontent.com/97615019/203063000-f76d19ba-04b2-4f2a-b5da-5e88e7f2c5f6.jpg)

**Comment by dan-mba** [comment]
I opened a PR that should fix this.

It installs all the Playwright dependencies & runs tests one at a time because our size Gitpod instance can't handle parallel tests.

**Comment by eddiejaoude** [comment]
Thank you all, great to have been made aware of this bug and now it is fixed 🔥
