### ISSUE TITLE
Add Tiktok

### ISSUE THREAD

**Issue by hellodeborahuk** [EddieHubCommunity/LinkFree#227]
Add Tiktok as an additional social network option with it's icon and primary colour.

Whether that's #010101, #69c9d0 or #ee1d52.

**Comment by rohan-kulkarni-25** [comment]
> Add Tiktok as an additional social network option with it's icon and primary colour.
> 
> Whether that's #10101, #69c9d0 or #ee1d52.

Hey !! Thanks for suggestions but I think this app or API will be mostly used for professional contact so adding TikTok to it is not required. **( It's also banned in Some countries )** 
( Just a suggestion )

**Comment by ShlokMohanty** [comment]
@rohan-kulkarni-25 so can we close this pr?

**Comment by hellodeborahuk** [comment]
I guess I was seeing it from a developer content creator point of view like Instagram and Twitter.

**Comment by rohan-kulkarni-25** [comment]
> I guess I was seeing it from a developer content creator point of view like Instagram and Twitter.

Yeah we can go with Instagram and twitter but I think TikTok will go a little out of the way. Still I request maintainers to have a look here once

**Comment by eddiejaoude** [comment]
I think there are developers using tiktok for knowledge sharing, so we should probably add it as an option then the user can decide if they want to use that feature

**Comment by ShlokMohanty** [comment]
@eddiejaoude so we need to add the tiktok logo or the icon when we visit the page of the contributors and there we are able to see the facebook and LinkedIn handles so we should add the tictok there ?
![image](https://user-images.githubusercontent.com/59838234/134808327-634a1aef-aad0-4d4b-b4aa-e2f109ed141e.png)
like below the twitter handle?

**Comment by san-coding** [comment]
neither does it have a `codewars` token, but an issue is open on this repo for adding `codewars`, so what do we do about it

> @eddiejaoude @hellodeborahuk
> Adding TikTok is not possible since the framework used is PrimeReact which does not have tiktok icon

**Comment by ankityadavhere** [comment]
[React Icons](https://react-icons.github.io/react-icons/icons) can be a great choice, as it has almost every icon the user will ever need!
I'd like to make a PR if the maintainers approve 😄  @eddiejaoude

**Comment by san-coding** [comment]
@ankityadavhere a PR is already open for this issue #245

**Comment by krishguptadev** [comment]
We are still choosing a icon library, currently that icon is not supported so this issue can be closed

**Comment by hellodeborahuk** [comment]
Can I try please?

**Comment by emmalearnscode** [comment]
> Can I try please @emmalearnscode? Is it editing LinkFree/src/Components/Icons/GetIcons.js ?

Yes, that's the file. You will need to import it then add it to the switch statement. I'll assign it to you, just let us know if you get stuck with anything and we'll gladly help :)
