### ISSUE TITLE
[FEATURE] PWA version of Linkfree

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/LinkFree#2277]
### Description

Hi there. I think it would be great for there to be a mobile version of Linkfree, just in case if users need to make changes to their profile but via their smartphone or tablet.

**Comment by mohit1607** [comment]
I would like to work on this issue adding pwa for mobile -view.

**Comment by CBID2** [comment]
> I would like to work on this issue adding pwa for mobile -view.

Great @mohit1607. I’ll create a file on Replit we can do to a rough draft.

**Comment by eddiejaoude** [comment]
Closing this as a duplicate of this issue https://github.com/EddieHubCommunity/LinkFree/issues/2278
