### ISSUE TITLE
[FEATURE] offline version of Linkfree (PWA)

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/LinkFree#2278]
### Description

Having access to user profiles offline would be great when there is limited internet.

We can make LinkFree into a PWA https://www.npmjs.com/package/next-pwa

**Comment by thevinitgupta** [comment]
Could you please explain about this?
I would like to contribute.

**Comment by eddiejaoude** [comment]
@thevinitgupta I have updated the description with more information

**Comment by mohit1607** [comment]
Progressive web app a good idea, It will allow us to install the webapp on our pc and also will give the fast access to linkfree website. It also caches the assets(images).

**Comment by mohit1607** [comment]
I would like to work on this, If someone like to assist me then welcome.

**Comment by mohit1607** [comment]
If Anybody is not assigned then I can do this.

**Comment by eddiejaoude** [comment]
Sure @mohit1607 👍

**Comment by CBID2** [comment]
> I would like to work on this, If someone like to assist me then welcome.

I’ll assist you @mohit1607! :)

**Comment by mohit1607** [comment]
Thank you very much @CBID2  I am stuck right now on something I successfully created the pwa but I am having trouble in making it offline. Glad to get help

**Comment by CBID2** [comment]
> Thank you very much @CBID2  I am stuck right now on something I successfully created the pwa but I am having trouble in making it offline. Glad to get help 

Okay what have you done so far?

**Comment by mohit1607** [comment]
Right now it is installable but not caching the url I provided and is displaying blank page, maybe it is due to I dont cached the bundled files but I am unaware of that completely.

**Comment by mohit1607** [comment]
"/docs" is just a cached url but not displaying when offline

**Comment by mohit1607** [comment]
I am awaiting for your response @CBID2

**Comment by CBID2** [comment]
> I am awaiting for your response @CBID2 

Hey @mohit1607.

**Comment by stevenovak123** [comment]
`https://web.dev/learn/pwa/caching/` Read this for caching in pwa . This article should help. I'll go through the above screenshots as well. I will be a little slow on replying cuz I'm usually on here during weekends.

**Comment by mohit1607** [comment]
Hi @stevenovak123  I am glad to hear from you but now I am not having any idea what to do next and According to me I had made it installable but was not sure to cache the pages so I am quitting this task and hoping for someone to find it and to evaluate it myself. Thanks Glad to be part of this team.

**Comment by stevenovak123** [comment]
Oh, alright no worries. Glad you tried and I hope you got to learn something. @CBID2  I'll read up on this on the weekends and let you know if I can help you make this.

**Comment by loftwah** [comment]
I can probably help but this looks like it is more in @krshkun's domain. I'd definitely be keen to be involve but it isn't my area of expertise.

**Comment by krshkun** [comment]
I don't think this will work because views will not workout this way

**Comment by loftwah** [comment]
I think your solution kind of beats this anyway doesn't it?

**Comment by krshkun** [comment]
> I think your solution kind of beats this anyway doesn't it?

Which solution? Can you be specific

**Comment by loftwah** [comment]
Your self-hosted version of LinkFree is fast enough that PWA isn't significant?

**Comment by krshkun** [comment]
Yes, I can implement this on linkfree as well 👍🏻 but the build times will increase a little

**Comment by CBID2** [comment]
> Yes, I can implement this on linkfree as well 👍🏻 but the build times will increase a little

How does your self-hosted version of Linkfree look @krshkun?

**Comment by loftwah** [comment]
[Krish's profile](https://links.krsh.eu.org/)

**Comment by CBID2** [comment]
> Krish's profile

Thanks. I agree with @loftwah. @krshkun’s self-hosted version is effective

**Comment by SaraJaoude** [comment]
Thanks everyone for the collaboration, but as this conversation has gone off-topic, let's close this issue for now and revisit in the future.

**Comment by mohit1607** [comment]
> I don't think this will work because views will not workout this way

Views ?

**Comment by krshkun** [comment]
> > I don't think this will work because views will not workout this way
> 
> Views ? 

The counter of views on your profile
