### ISSUE TITLE
[FEATURE] Help button to link to GitHub Discussions

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2281]
### Description

Add a help icon and link to GitHub Discussions

<img width="1467" alt="Screenshot 2022-11-26 at 12 09 16" src="https://user-images.githubusercontent.com/624760/204088162-c412ae49-3f09-43c8-b721-8f6d0c4a7b4b.png">

**Comment by joeshajan** [comment]
@eddiejaoude I would like to work on this. Can you assign this to me?

**Comment by joeshajan** [comment]
Do we need to fix the position of the button?

**Comment by joeshajan** [comment]
![image](https://user-images.githubusercontent.com/69904519/204100542-e8427a03-c84b-4806-9148-345a6537753e.png)

@eddiejaoude What do you think about this?
