### ISSUE TITLE
Profile heading characters should be limited

### ISSUE THREAD

**Issue by loftwah** [EddieHubCommunity/LinkFree#2286]
### Description

The amount of characters that can be used in a profile heading should be limited to what can be displayed in a card on the popular profiles pages. My profile is in the popular profiles page now and I noticed that I've used more characters than I probably should have. Instead of extending the cards I think it would be better to limit the amount of characters. I'll update mine and submit a PR so it doesn't look odd.

### Screenshots

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/19922556/204259490-8d76df76-432c-4a22-8fdb-37e4717e0a15.png">
![Uploading image.png…]()

### Additional information

You can see my headline is `Hi, I’m Dean Lofts and I am brilliantly lazy. I also go by 🎹 Loftwah The Beatsmiff, and you might remember me from such albums as Protektahz, Salty Waterz, Salty Waterz 2, Day of The Guiding Light, and Such Iz Life.` and the card cuts off at `Hi, I’m Dean Lofts and I am brilliantly lazy. I also go by 🎹 Loftwah The Beatsmiff, and you might remember me from such`.

**Comment by MirzaHasnat** [comment]
@eddiejaoude @loftwah  Hi ! Can I take this issue ?

**Comment by loftwah** [comment]
I'm good with that. Let me know if you need anything.

**Comment by eddiejaoude** [comment]
We now have markdown in the bio to help break it up. Is this issue still needed?

**Comment by loftwah** [comment]
I was the only person I know of causing issues here and I updated my profile so it would no longer be a problem.

**Comment by SaraJaoude** [comment]
Looks like no longer required, so closing this issue.
