### ISSUE TITLE
Standardize padding on main pages

### ISSUE THREAD

**Issue by Balastrong** [EddieHubCommunity/LinkFree#2288]
### Description

I noticed that `padding-top` and `padding-left` on the main pages (`/popular`, `/search` and `/events`) are not consistent, giving a weird effect when switching between them.

The popular page has the class `.p-5` on the first element, giving 1.25 rem on both top and left paddings.
Instead, search and events have on their first elements the class `.px-6` giving 1.5 rem on left and 0 on top.

I think they should be standardized (I would suggest to stick to `.p-5` on all three pages)

### Screenshots

![popular](https://user-images.githubusercontent.com/7253929/204372138-a43ef0d4-0918-4bbf-95cf-5f81d6c3e59a.png)

![search](https://user-images.githubusercontent.com/7253929/204372166-1eb8ab1b-62fc-4d21-a4d1-451ada281411.png)

![events](https://user-images.githubusercontent.com/7253929/204372189-bb21ff6a-0693-4c80-ab15-20958f16a377.png)

**Comment by Balastrong** [comment]
If you think it makes sense, I'll be happy to submit a PR for this :)

**Comment by AAYUSH-droid** [comment]
Would like to work on this issue. Can you assign me?

**Comment by schmelto** [comment]
@Balastrong  I assigned you
@AAYUSH-droid  maybe you can do a pair with @Balastrong

**Comment by Balastrong** [comment]
Fixed with #2336
