### ISSUE TITLE
Not all profiles have view counts.

### ISSUE THREAD

**Issue by LinuxGamer** [EddieHubCommunity/LinkFree#2294]
### Description

I was looking at the popular profile pages and saw mine there, I went to check the view count on the profile and it wasn't there, so I checked Eddie's and Pradumna's and they have it. There is other profiles on popular that don't have view counts.

### Screenshots

![4F8D9EB8-FBB2-443F-B1C0-6157F219CA58](https://user-images.githubusercontent.com/83363242/204654067-3c6bb3b7-d72a-4367-b550-f6cc3d467c0c.png)
![6F7E5461-A4B4-4C16-86C5-01BE15F7AA80](https://user-images.githubusercontent.com/83363242/204654077-e4238d4b-5a16-4ca0-9e0a-8893ee5d3318.png)
![E7F66F47-AC5C-4DC9-9BAB-8A9CD1EE095C](https://user-images.githubusercontent.com/83363242/204654080-f04ebcf2-ddea-4b96-b84e-50011a5d54af.png)
![F3BAFCF7-98C3-461C-896B-119E48636F2B](https://user-images.githubusercontent.com/83363242/204654083-60f54290-571d-4e88-9335-39135023c8c2.png)

**Comment by eddiejaoude** [comment]
It is off by default, you can enable it with `"displayStatsPublic": true,`, see the official example here in the docs...

https://github.com/EddieHubCommunity/LinkFree#-to-add-your-profile

**Comment by LinuxGamer** [comment]
Ok, I'll close this issue now :) XD

**Comment by eddiejaoude** [comment]
no worries, thank you for asking and closing 👍
