### ISSUE TITLE
[MOBILE] Github link doesn't open in new tab

### ISSUE THREAD

**Issue by LinuxGamer** [EddieHubCommunity/LinkFree#2295]
### Description

Same as #2159 but on mobile devices. 

### Additional information
Browser - Opera Touch
OS - iOS 15.7

**Comment by joeshajan** [comment]
Hey @LinuxGamer can I take this issue?

**Comment by LinuxGamer** [comment]
@joeshajan sure, a maintainer can assign you to the issue :)

**Comment by LinuxGamer** [comment]
Hey @joeshajan , are you still working on this issue?

**Comment by joeshajan** [comment]
No

**Comment by LinuxGamer** [comment]
Could I get assigned to this issue?

**Comment by eddiejaoude** [comment]
Sure, assigned @LinuxGamer
