### ISSUE TITLE
Social posts in profile should increment matching links counter

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2305]
### Description

When these social links are clicked, check for matching link in page and increment counter

<img width="1900" alt="Screenshot 2022-12-01 at 10 51 30" src="https://user-images.githubusercontent.com/624760/205034918-03dfc7bc-8b4c-46c9-893a-6e6b96bf1846.png">

**Comment by furkanmutlu** [comment]
Hi @eddiejaoude , can you assign this to me ?

**Comment by furkanmutlu** [comment]
Hi @eddiejaoude are you working on this ?

**Comment by eddiejaoude** [comment]
Hi @furkanmutlu yep I am 👍
