### ISSUE TITLE
[FEATURE] search by clicking on user's tags

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2323]
### Description

Currently we can add tags to our profiles, but it would be good to be able to search for these and also by clicking them it goes to the search page with it pre-filled

**Comment by joeshajan** [comment]
Hey, @eddiejaoude I would like to work on this. Before that, I just want to confirm what I understood.

So in the first case, if we search for any tags, It should display profiles with those tags, right?

![image](https://user-images.githubusercontent.com/69904519/205638375-a74147dc-0b90-40e2-ac59-22ab9c283199.png)

And in the second case, if we click on any tags from the profile, we should redirect the user to the search page and the selected tag will be typed in the text box right?

![image](https://user-images.githubusercontent.com/69904519/205638637-6a90613e-6e25-479a-8d67-a57012f4e6bb.png)

**after clicking**

![image](https://user-images.githubusercontent.com/69904519/205641875-3a3e8773-9a98-4d1f-af91-dabf3fc83a93.png)

If this is what we want can you assign this to me? Or can you please explain where I went wrong?

**Comment by eddiejaoude** [comment]
Wow this is explained super well 👍  yes that is correct @joeshajan 💯 

Would you like me to assign it to you?

**Comment by Smiley0412** [comment]
> Hey, @eddiejaoude I would like to work on this. Before that, I just want to confirm what I understood.
> 
> So in the first case, if we search for any tags, It should display profiles with those tags, right?
> 
> ![image](https://user-images.githubusercontent.com/69904519/205638375-a74147dc-0b90-40e2-ac59-22ab9c283199.png)
> 
> And in the second case, if we click on any tags from the profile, we should redirect the user to the search page and the selected tag will be typed in the text box right?
> 
> ![image](https://user-images.githubusercontent.com/69904519/205638637-6a90613e-6e25-479a-8d67-a57012f4e6bb.png)
> 
> **after clicking**
> 
> ![image](https://user-images.githubusercontent.com/69904519/205641875-3a3e8773-9a98-4d1f-af91-dabf3fc83a93.png)
> 
> If this is what we want can you assign this to me? Or can you please explain where I went wrong?

😎
