### ISSUE TITLE
[FEATURE] Markdown render to milestone and events

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2332]
### Description

We have markdown in the bio text, this functionality could be added to milestone and event description

Example for the bio https://github.com/EddieHubCommunity/LinkFree/blob/main/components/user/UserProfile.js#LL52

**Comment by KlausMikhaelson** [comment]
Hey @eddiejaoude would love to work on it, can you assign it to me ?

**Comment by ManishBisht777** [comment]
hi @KlausMikhaelson can we work on this together ?

**Comment by KlausMikhaelson** [comment]
Hey @ManishBisht777 will let you know if I need any help !

**Comment by KlausMikhaelson** [comment]
Hey @eddiejaoude , have created a pr i.e. https://github.com/EddieHubCommunity/LinkFree/pull/2343#issuecomment-1343490493 do let me know if there is any changes required !
Thank you !
