### ISSUE TITLE
[DOCS] Environment variable

### ISSUE THREAD

**Issue by KlausMikhaelson** [EddieHubCommunity/LinkFree#2342]
### Description

I think we should add more description for the .env file since as a new contributor people can get confused on filling out `NEXT_PUBLIC_GA_MEASUREMENT_ID` 

### Screenshots

<img width="587" alt="image" src="https://user-images.githubusercontent.com/100528412/206578037-9b5673fb-8717-44e1-9b55-303ff6e5535c.png">

**Comment by eddiejaoude** [comment]
We now have defaults that popular in the `.env` and better documentation. I don't think this causes any issues anymore so I will close for now. But please raise again if required
