### ISSUE TITLE
[FEATURE] Future milestones to have a dotted line

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2350]
### Description

We have milestones at the moment, but these are in the past, it would be great to have goals - these would need to be displayed slightly differently

Maybe a flag that is `goal: true`

Current data...

```json
"milestones": [
    {
      "title": "Started Freelancing",
      "date": "May 2010",
      "icon": "dollar",
      "color": "grey",
      "description": "Started freelancing again",
      "url": "https://www.eddiejaoude.io/"
    }
]
```

We could add a flag...
```json
"milestones": [
    {
      "isGoal": true,
      "title": "Started Freelancing",
      "date": "May 2010",
      "icon": "dollar",
      "color": "grey",
      "description": "Started freelancing again",
      "url": "https://www.eddiejaoude.io/"
    }
]
```

Currently milestones are displayed like this, but we could have a dotted line down to another group of cards and these could be slightly faded, to show they have not been achieved yet

<img width="1629" alt="Screenshot 2022-12-11 at 11 34 01" src="https://user-images.githubusercontent.com/624760/206901148-c7305c33-51c5-475c-9cc5-bc9777e83d45.png">

**Comment by ManishBisht777** [comment]
hi @eddiejaoude can you explain this a bit more

**Comment by eddiejaoude** [comment]
@ManishBisht777 I updated the issue description, I hope that helps

**Comment by ManishBisht777** [comment]
@eddiejaoude thanks for the detailed info

I would like to work on this feature
we can divide the task into parts:

    1) ui for the goals (faded cards)
    2) make it functional


I am starting with the UI

**Comment by eddiejaoude** [comment]
Both parts will need to come in the same PR though

**Comment by ManishBisht777** [comment]
sure

**Comment by SaraJaoude** [comment]
completed
