### ISSUE TITLE
[FEATURE] Milestones order change

### ISSUE THREAD

**Issue by ManishBisht777** [EddieHubCommunity/LinkFree#2366]
### Description

we can change the order of milestones from older first to newer first so that we don't have to scroll through the website to see recent milestones 

or we can add a button at the top to sort them in ascending or descending order

although i am not clear with the idea love to see other people take in this

### Screenshots

![Screenshot from 2022-12-10 19-59-08](https://user-images.githubusercontent.com/89926834/206860733-ab0dc9f6-8f34-4c44-9739-ddd7c00db3cc.png)

**Comment by eddiejaoude** [comment]
It would be good to give the user the ability to order the data in each tab 👍

**Comment by prajapati55** [comment]
Hey! I would like to add this feature.

**Comment by eddiejaoude** [comment]
Sure @prajapati55 👍

**Comment by adityassharma-ss** [comment]
Hey @eddiejaoude,  Solved this issue.

![Eddie Jaoude - Brave 12_30_2022 1_20_00 PM](https://user-images.githubusercontent.com/82082352/210047179-3bbe994b-98bb-4cc2-bc81-543d0fc7e7b2.png)

Do you want to add something else?

**Comment by adityassharma-ss** [comment]
Hey @eddiejaoude, Solved this issue

![Eddie Jaoude - Brave 12_30_2022 1_22_02 PM](https://user-images.githubusercontent.com/82082352/210047365-4d98521e-c6be-41e7-99fd-a06620ef7241.png)

Do you want to add something else to this?

**Comment by eddiejaoude** [comment]
Hi @adityassharma-ss , thank you, but this has already been solved in this PR https://github.com/EddieHubCommunity/LinkFree/pull/2474 but the issue was not closed yet - sorry for the confusion

**Comment by adityassharma-ss** [comment]
Oh! Sorry!

**Comment by eddiejaoude** [comment]
@adityassharma-ss don't be sorry, I feel bad you put in the work and it was already completed. Let me know if there is another issue you would like to do
