### ISSUE TITLE
New Testimonial

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/LinkFree#2368]
### Name

michaella23

### Title

An inspiration 

### Description

I had the pleasure of meeting Michaella in Scrimba’s Discord community. As a person who is fairly new to coding, her patience and enthusiasm when educating people about this skill is motivating to witness. Without her, I would have never learned about Open Source projects.

**Comment by eddiejaoude** [comment]
`michaella23` doesn't have a LinkFree profile, so adding a testimonial file I don't think makes sense

I think we have 2 options here:
1. ask `michaella23` if they would create a LinkFree profile
or
2. remove the file as it won't be used within the app

**Comment by CBID2** [comment]
Good point @eddiejaoude.
