### ISSUE TITLE
Paragraph under individual Profile is not centered and have no max-width

### ISSUE THREAD

**Issue by amittri1025** [EddieHubCommunity/LinkFree#238]
Make Paragraph under profile centered and set max-width to it .

![sample-image](https://user-images.githubusercontent.com/74503582/133905158-c38f2271-9331-460a-a590-f2d18de9f89a.png)

**Comment by rohan-kulkarni-25** [comment]
Please consider PR #209  while making changes

**Comment by eddiejaoude** [comment]
We could move the changes in #209 to a style and use it for the description too 👍

**Comment by nayabatir1** [comment]
Is this issue still open?

**Comment by amittri1025** [comment]
This issue is solved
