### ISSUE TITLE
Adding Contributing Guidelines

### ISSUE THREAD

**Issue by unnati914** [EddieHubCommunity/LinkFree#24]
We should add a CONTRIBUTING.md file to the root folder of the repository.

This file should include:
- Steps to set up a local instance of the project
- Instructions to add the JSON file
  - Include an example of formatting (emphasise `github.com/<username>.png` for avatars)
- Requirements for submitting a PR
  - Conventional commit messages

**Comment by aryasoni98** [comment]
I would like to work on it

**Comment by krishdevdb** [comment]
This issue shall be closed, already fixed in #32

**Comment by schmelto** [comment]
thx @krishdevdb
