### ISSUE TITLE
[FEATURE] Events tab improvements

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2414]
### Description

- [x] move events to sub folder `<username>/events/` https://github.com/EddieHubCommunity/LinkFree/pull/2540
- [ ] hide finished events (similar to `Community Events` page)
- [ ] ~~Better virtual icon~~
- [ ] filter based on key https://github.com/EddieHubCommunity/LinkFree/issues/2528
- [ ] show total in each key https://github.com/EddieHubCommunity/LinkFree/issues/2529
- [x] hide profile picture as not required on profile page (use flag to hide)
- [x] Key for icons (in person / virtual) https://github.com/EddieHubCommunity/LinkFree/pull/2527

**Comment by prajapati55** [comment]
hey Eddie! I would like to work on this feature

**Comment by eddiejaoude** [comment]
hey @prajapati55 thank you but I already assigned it to me the day before and started working on it. Please have a look at the issue list for unassigned items
