### ISSUE TITLE
[FEAT]: An Icon package

### ISSUE THREAD

**Issue by AbhijithGanesh** [EddieHubCommunity/LinkFree#242]
Can we use an icon package like react-icons to easily add our Icons to the website instead of mounting inside Class Names.

**Comment by eddiejaoude** [comment]
Can you give some examples and a link?

**Comment by schmelto** [comment]
#390

**Comment by Guneetsinghtuli** [comment]
@eddiejaoude I think we can use Font Awesome as it provides `icons` of almost every social media platform and many more we will be needing like FB, Insta, YouTube, Discord .
You can have a look at their website https://fontawesome.com/

**Comment by AbhijithGanesh** [comment]
Examples of an icon package:
- [React Icons](https://react-icons.github.io/react-icons/)
   - Easily addable as a package using npm and yarn
   - Very useful to integrate with React.
   - Diverse and supports various icons
- [Font-Awesome Icons](https://fontawesome.com/v5.15/how-to-use/on-the-web/using-with/react)
  - Diverse and supports various icons.



Can I work on adding a icon package if we need one?

**Comment by amittri1025** [comment]
Issue solved see #394

**Comment by AbhijithGanesh** [comment]
It isn't, we were discussing an addition and waiting for conseus

**Comment by Guneetsinghtuli** [comment]
> I think we're awaiting votes to decide on the best package instead of the patch and waiting for consensus. Please donot patch changes which are being discussed. Once the best icon package according to the comm is decided, we can move to patches.

I was also thinking that we were having a discussion over here and will have some kind of voting
But anyway @AbhijithGanesh I think Font Awesome will be more friendly as we will be just using a CDN and not the entire package, What do you think ?

**Comment by AbhijithGanesh** [comment]
> > I think we're awaiting votes to decide on the best package instead of the patch and waiting for consensus. Please donot patch changes which are being discussed. Once the best icon package according to the comm is decided, we can move to patches.
> 
> I was also thinking that we were having a discussion over here and will have some kind of voting
> But anyway @AbhijithGanesh I think Font Awesome will be more friendly as we will be just using a CDN and not the entire package, What do you think ?

I think using react icons will be more suitable for other applications at the same time it's more versatile and contains more icons w.r.t font awesome package. Font awesome lacks support for certain applications like hashnode, Dev, etc

**Comment by Guneetsinghtuli** [comment]
But don't you think Font awesome will be enough to provide all the icons we will be needing and it Seems like React icons also provide Font awesome icons in a form of a package. So now we have 2 options either to use Font awesome from the package or the CDN
![Screenshot 2021-10-02 at 12 11 52 AM](https://user-images.githubusercontent.com/48324492/135671763-0a3ba254-df9e-4b3b-a654-d9a4ca920216.png)

**Comment by muhon9** [comment]
Font awsome will be better

**Comment by krishguptadev** [comment]
tbh I think we should either use Devicons or SimpleIcons they have almost every icon a dev needs

**Comment by AbhijithGanesh** [comment]
We'll have a final poll today then?

**Comment by Guneetsinghtuli** [comment]
> tbh I think we should either use Devicons or SimpleIcons they have almost every icon a dev needs

I tried using both But Devicon they don't have icons for Instagram and discord but I like Simple icons.

**Comment by krishguptadev** [comment]
> > tbh I think we should either use Devicons or SimpleIcons they have almost every icon a dev needs
> 
> I tried using both But Devicon they don't have icons for Instagram and discord but I like Simple icons.

So then let's do simple icons

**Comment by krishguptadev** [comment]
> We'll have a final poll today then?

I'll create a poll here in a discussion...

**Comment by krishguptadev** [comment]
Check this: https://github.com/EddieHubCommunity/LinkFree/discussions/417

**Comment by krishguptadev** [comment]
Should we end the poll now?

**Comment by Guneetsinghtuli** [comment]
Yes I think we can end it

**Comment by krishguptadev** [comment]
I would love to work on this issue after the icon package is resolved
