### ISSUE TITLE
[FEATURE] Icons page

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2425]
### Description

Ability to search available icons that people can use in the project. This should only search 2 icons from ReactIcons `Fa` and `Md`.

The branch should be made from the new docs branch and the PR should be made to the same branch `cahllagerfeld/feature-documentation-2203`
https://github.com/EddieHubCommunity/LinkFree/blob/cahllagerfeld/feature-documentation-2203/components/Icon.js

The UI should be consistent with the user search, but display the icons available

**Comment by joeshajan** [comment]
Hey, @eddiejaoude I would like to add this feature. 

So what do you mean by available icons? The icons which we are currently using in the project or all the icons from react-icons.

**Comment by eddiejaoude** [comment]
Hey @joeshajan , great 👍 I have updated the description, any questions let me know

**Comment by joeshajan** [comment]
Thanks for updating it @eddiejaoude 
Can I start working on it? Can you assign this to me?

**Comment by joeshajan** [comment]
Hey @eddiejaoude where should users search for icons? In this current search page or should I create a new page for icons?

![image](https://user-images.githubusercontent.com/69904519/208714682-18d056ee-9938-4b6c-aea4-b2ceaf75b37d.png)

**Comment by eddiejaoude** [comment]
Please create a new page 👍 but you can use the current search page as an example.

We will link to the new icon search page from the documentation we are working on - please can you use the path `/icons`

**Comment by joeshajan** [comment]
Thanks, Eddie for clarifying the doubt.

**Comment by joeshajan** [comment]
Hey, @eddiejaoude this is what I did so far. Any suggestions to improve UI?

![image](https://user-images.githubusercontent.com/69904519/209362321-afcaecdb-5d4d-4809-bd07-c834e859b612.png)

This is what happens if the icon name is long.

![image](https://user-images.githubusercontent.com/69904519/209362596-96b963c3-0058-47c5-82f0-a2ca8396ca15.png)

On the react-icons official site, they are hiding the text.

![image](https://user-images.githubusercontent.com/69904519/209362736-4ee1fdb2-69e5-418f-b90a-dfc86a22d6b9.png)

If we hide the text we need to add the feature for copying the name on click.

What do you think?

**Comment by eddiejaoude** [comment]
It looks great 👍  The text can wrap for phase 1, we can get it merged as it will add value already 🎉 then in another PR later it can be improved!

Great work! Just to let you know we are now only using 2 icon sets, this is `fa` and `si` - can the search only search these 2 icon sets?

**Comment by joeshajan** [comment]
Yes, we can search only from `Fa` and `Md`.

`Si` is not included.

**Comment by eddiejaoude** [comment]
For the latest changes, we are using `Fa` and `Si` https://github.com/EddieHubCommunity/LinkFree/blob/main/components/Icon.js

**Comment by joeshajan** [comment]
> For the latest changes, we are using `Fa` and `Si` https://github.com/EddieHubCommunity/LinkFree/blob/main/components/Icon.js

Ok no problem will change it to `Si` then

**Comment by eddiejaoude** [comment]
Merged
