### ISSUE TITLE
[FEATURE] Improve Docker Compose file

### ISSUE THREAD

**Issue by Pradumnasaraf** [EddieHubCommunity/LinkFree#2432]
### Description

Make the **Docker Compose** more standard and complete according to the project by including the LinkFree image (service) building on the fly. Currently, we are only using the  Mongo image just to get for DB connection which is not good. Changes will connect the App and DB internally.

Also after this, a contributor doesn't need to step into the environment locally, everything will run inside containers. After this, the whole project setup will need just two-step

- Clone the repo
- Then `docker compose up`

**Comment by eddiejaoude** [comment]
Great idea 👍  we can include this in the new docs too

**Comment by dan-mba** [comment]
How would you do development with everything running in a container? Would you have to make changes then rebuild the container?

**Comment by Pradumnasaraf** [comment]
> How would you do development with everything running in a container? Would you have to make changes then rebuild the container?

Great question. We will use bind mounts (Volumes) so that we don't have to rebuild the images.

**Comment by dan-mba** [comment]
> Great question. We will use bind mounts (Volumes) so that we don't have to rebuild the images after every iteration.

So there is a link between the src files outside & inside the container.

How are you going to handle package.json & node_modules?
Would any install or update require a rebuild?

I am trying to think through my dev workflow to figure out where the points of maximum confusion or breakage would be.

**Comment by Pradumnasaraf** [comment]
Sorry missed the comment. 

Yes, we will do it that way. I think we don't need to worry about the `package.json & node_modules` Next handles it wonderfully, and if there is some issue we can improve over time with your and the community's contribution.

> Would any install or update require a rebuild?

I don't think so we run so that, if it's, we will add that in the docs to run `docker compose up --build`

**Comment by dan-mba** [comment]
> I think we don't need to worry about the `package.json & node_modules` 

So you will do an `npm ci` inside the container & it will have its own `node_modules` folder?
I was worried about OS specific dependencies if you are running Windows or MacOS outside with Linux inside the container.

**Comment by Pradumnasaraf** [comment]
> > I think we don't need to worry about the `package.json & node_modules`
> 
> So you will do an `npm ci` inside the container & it will have its own `node_modules` folder? I was worried about OS specific dependencies if you are running Windows or MacOS outside with Linux inside the container.

Yes, for now, I am less worried about that, because I have never faced any problem with a web application. Because we can improve with time. Thank you for all questions, helps to brainstorm

**Comment by eddiejaoude** [comment]
if I understand the concern correctly, I do not think it is an issue because where the dependencies are installed is where the app will run - yes people people try to do both, run the container and run it outside there will be an issue, but I think they need to select one of the options to run the project not both. Hope I understood correctly?

**Comment by dan-mba** [comment]
I just thought up another issue.

How do you run playwright tests with this compose file?

Playwright runs its own dev server, but is dependent on having mongo running.

**Comment by eddiejaoude** [comment]
oh that is a good question @dan-mba 👍 it is something we would need to look into, maybe running playwright on another port - yes please raise a new issue Dan, as this can be a further improvement

**Comment by Pradumnasaraf** [comment]
> if I understand the concern correctly, I do not think it is an issue because where the dependencies are installed is where the app will run - yes people people try to do both, run the container and run it outside there will be an issue, but I think they need to select one of the options to run the project not both. Hope I understood correctly?

Exactly. That's the whole point of Compose, we need not care about our local machine environment and OS-specific dependencies, everything is isolated within the container. 

Also, OS specific problem arises when using pre-build images (not building them on the fly)
