### ISSUE TITLE
[FEATURE] Group links together

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2437]
### Description

Sometimes we want to group links together.

Maybe all links can fall in `default` but then people could add other groups like `community` or `business` etc

I think this could be done with a group name property in the links section and if not set use `default`

```js
"links": [
   {
      ...
      "group": "business",
      ...
   }
]
```

**OR**

Have a field in the link object for the group, for example

```js
"links": [
   {
      "group": "Socials",
      ...
   }
]
```

Similar to @madzadev's profile on BioLink https://bio.link/madza

<img width="1262" alt="Screenshot 2023-01-22 at 17 26 33" src="https://user-images.githubusercontent.com/624760/213930489-4964aa38-516c-44b2-b8d3-6fc20a9e532a.png">

**Comment by mayo7e** [comment]
hi eddie, can this be assigned to me please..

**Comment by eddiejaoude** [comment]
Suer, assigned to you @mayo7e

**Comment by mayo7e** [comment]
@eddiejaoude thanks

**Comment by eddiejaoude** [comment]
@mayo7e I am going to unassigned this issue to give others the opportunity to work on this as there hasn't been any activity for over 4 weeks - you can find other issues when you are ready

**Comment by mayo7e** [comment]
ok thanks eddie
