### ISSUE TITLE
[FEATURE] New UI for landing page

### ISSUE THREAD

**Issue by ManishBisht777** [EddieHubCommunity/LinkFree#2441]
### Description

we can have a new UI for the landing page 

Although I never tried Figma before but want to learn that by building a real-world project.

**Comment by ManishBisht777** [comment]
sure @eddiejaoude we can proceed this way as well, let me know if you need some help on that.

**Comment by eddiejaoude** [comment]
Thank you @ManishBisht777 !!

If you want to get involved in some UI improvements, please can you check for responsiveness - I think we can make many improvements on this, and any improvements no matter how small would be appreciated

**Comment by ManishBisht777** [comment]
sure @eddiejaoude :)

**Comment by SaraJaoude** [comment]
This issue is not clear about the changes it is suggestion so I am going to close. Please raise a new issue with specific goals.
