### ISSUE TITLE
[FEATURE] Linked testimonial profiles

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#2444]
### Description

From the testimonials tab, clicking on the users avatar (or wherever makes sense) that provided the testimonial could lead to their GH profile.

Potential use case:
An employer lands on your linkfree, is reading testimonials
Wants to reach out to that person for a recommendation

Use case 2:
easy access to others connected to the main profile user for collaboration and/or connection

Future considerations:
Should non-GH users be able to submit testimonials in the future, what profile is linked?

**Comment by eddiejaoude** [comment]
sorry @Mohith234 someone has already opened a PR. Can you select another issue please
