### ISSUE TITLE
File adding

### ISSUE THREAD

**Issue by samsorrahman** [EddieHubCommunity/LinkFree#2453]
### Description

I have added files to link free project and the pull request has been merged so, what are the next steps to follow to get link free website.

**Comment by eddiejaoude** [comment]
The data file was in the wrong location that is why it wasn't being displayed in the app. I have fixed this now and in a few minutes your profile will appear https://github.com/EddieHubCommunity/LinkFree/blob/main/data/samsorrahman.json

Your profile will be here https://linkfree.eddiehub.io/samsorrahman

**Comment by samsorrahman** [comment]
Thank you so much, sir!
Highly Appreciated.
