### ISSUE TITLE
[FEATURE] Improvement - mobile testimonial UI

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#2454]
### Description

In mobile the testimonial text isn't making good use of the visual "real estate" right now creating longer testimonial cards than necessary. This issue is to modify the mobile UI to allow the text to float below the avatar and span the full width of the card.

### Screenshots

![mobile-testimonial-ui](https://user-images.githubusercontent.com/97615019/209005841-aba75378-a5b4-4b05-a299-1875ece0604b.PNG)

**Comment by Aadarsh805** [comment]
Can we change the layout to this on the mobile screen, if yes assign me I'd make the changes
![Group 1](https://user-images.githubusercontent.com/95094057/209065779-4ce3fa81-7da4-445e-9c9b-247bc886746e.png)

**Comment by eddiejaoude** [comment]
Thank you both 👍  

Looks good, assigned to you @Aadarsh805
