### ISSUE TITLE
[DOCS] Unclear contributing guide

### ISSUE THREAD

**Issue by Rishav-12** [EddieHubCommunity/LinkFree#2463]
### Description

This guide: https://github.com/EddieHubCommunity/LinkFree/blob/main/docs/contributing/contributing-your-profile.md to contribute user profiles is, in my opinion, not clear and intuitive enough for someone new to the Git/GitHub/PR workflow. I am aware there are resources where they can learn more, but if someone wants to add their profile and land on this file, they may be confused.

### Additional information

Examples of unclear instructions

- https://github.com/EddieHubCommunity/LinkFree/blob/e86f926ab704a1eae3677ab1ebdee0411bf8b8b2/docs/contributing/contributing-your-profile.md?plain=1#L3 Spelling error and not clear what to fork and how
- https://github.com/EddieHubCommunity/LinkFree/blob/e86f926ab704a1eae3677ab1ebdee0411bf8b8b2/docs/contributing/contributing-your-profile.md?plain=1#L18 This has changed now, we don't have a `public` folder anymore
- There are certain assumptions about what the new user is using, like they may not be using the SSH link to access GitHub and they may not be using VS Code https://github.com/EddieHubCommunity/LinkFree/blob/e86f926ab704a1eae3677ab1ebdee0411bf8b8b2/docs/contributing/contributing-your-profile.md?plain=1#L16
- In certain steps, there are instructions to click certain buttons which is not super clear. I think it would be better if screenshots are added.

**Comment by eddiejaoude** [comment]
Hi @Rishav-12 , sorry for the confusion. Thank you for the detailed reply about it. We just released a whole new docs section which will make it easier for people to use the project and contribute.

https://linkfree.eddiehub.io/docs

We still have more improvements to make, so any suggestions welcome.

As the file you mentioned has now be removed, I will close this issue, but please feel free to create another issue for any suggestions on the new documentation
