### ISSUE TITLE
Navbar Close on link click

### ISSUE THREAD

**Issue by ManishBisht777** [EddieHubCommunity/LinkFree#2464]
### Description

We can close the navbar ( mobile view ) When the routes are changed or A link is clicked

![image](https://user-images.githubusercontent.com/89926834/209341875-6939ff40-010c-4c62-86c8-daf9c9fe8200.png)

**Comment by ashuthe1** [comment]
Hi! , I want to work on it.
Please assign it to me.

**Comment by stephenokyere233** [comment]
@eddiejaoude could you please assign this to me, I would love to do this

**Comment by eddiejaoude** [comment]
Thanks @stephenokyere233 but I think there is a PR open already for it, I didn't have a chance to look at it yet though https://github.com/EddieHubCommunity/LinkFree/pull/2507

**Comment by stephenokyere233** [comment]
> Thanks @stephenokyere233 but I think there is a PR open already for it, I didn't have a chance to look at it yet though https://github.com/EddieHubCommunity/LinkFree/pull/2507

Okay then I'll take another issue

**Comment by eddiejaoude** [comment]
Thanks @stephenokyere233 - maybe you could also review the open PR and share your thoughts on it

**Comment by stephenokyere233** [comment]
> Thanks @stephenokyere233 - maybe you could also review the open PR and share your thoughts on it

I'll try that too
