### ISSUE TITLE
Spacing in profile submenu

### ISSUE THREAD

**Issue by ManishBisht777** [EddieHubCommunity/LinkFree#2466]
### Description

We can add a margin top and bottom of the submenu to prevent them from sticking to the QR code and the section below it

![image](https://user-images.githubusercontent.com/89926834/209343185-0ad4ddea-f05f-4a02-a239-2a6608eeb4c1.png)

**Comment by yrs147** [comment]
I would like to work on this issue @eddiejaoude, can you assign this to me?

**Comment by Aadarsh805** [comment]
it's already been fixed by #2468

**Comment by eddiejaoude** [comment]
Thanks @Aadarsh805 yes you are correct, it can be improved further - if someone would like to submit a new PR. I think your suggestion here is a good idea https://github.com/EddieHubCommunity/LinkFree/pull/2468#pullrequestreview-1229625656
