### ISSUE TITLE
Responsiveness - event page

### ISSUE THREAD

**Issue by ManishBisht777** [EddieHubCommunity/LinkFree#2467]
### Description

Currently, this looks a bit packed in the mobile view (320px)
We can add a bit more spacing and change the direction on flex to make it a bit spaced out
![image](https://user-images.githubusercontent.com/89926834/209343739-41c8070c-85fb-400f-84f9-e9dc21915fdb.png)

**Comment by KlausMikhaelson** [comment]
maybe if the profile is on top than the title and description is below it would look better, what do you think ?

**Comment by iamr-kumar** [comment]
I also think we can do away with some margin around the card and arrange the content inside a bit better.

**Comment by stephenokyere233** [comment]
@eddiejaoude I'd love to work on this on could you assign me please

**Comment by eddiejaoude** [comment]
Sure, assigned

I think the dates could be listed under each other and maybe the profile picture is hidden

**Comment by stephenokyere233** [comment]
@eddiejaoude Alright will do!

**Comment by stephenokyere233** [comment]
@eddiejaoude is it okay this way?

![Screenshot_20221227-142322_Chrome.jpg](https://user-images.githubusercontent.com/105071093/209680175-39f4e4f5-f316-4b8f-880e-1f9ab5618295.jpg)

**Comment by eddiejaoude** [comment]
Yes this looks like a great improvement 👍
