### ISSUE TITLE
Broken link to "contribution guidelines" in Readme file.

### ISSUE THREAD

**Issue by Nick-h4ck3r** [EddieHubCommunity/LinkFree#2477]
### Description

The current link is navigating to "https://github.com/EddieHubCommunity/LinkFree/blob/main/docs/contributing/CONTRIBUTING.md" which is showing a Page not found 404 page.

### Screenshots

![image](https://user-images.githubusercontent.com/70500923/209440837-eacca428-c3fd-4749-b401-f005d04928e1.png)

**Comment by eddiejaoude** [comment]
Broken link removed 👍 thank you
