### ISSUE TITLE
[DOCS] Markdown formatting issue in `README.md`

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/LinkFree#2482]
### Description

There's an issue that prevents proper Markdown formatting in the `README.md` file.

_Steps to contribute_

1. Fork the repository [**here**](https://github.com/EddieHubCommunity/LinkFree/).
2. Create a new branch in your fork named `fix_markdown`.
3. Open the `README.md` file.
4. In line 17, remove the space before the `**` at the end. This will fix the bold text being formatted wrongly. To do it easier, replace the current content with the following content:

```markdown
**Optional fields: `milestones`, `type(personal | community)`, `socials`, `testimonials` and `events`**\
```

5. Commit and push your changes.
6. Create a [**pull request**](https://github.com/EddieHubCommunity/LinkFree/compare).
7. You're done now! 🎉 You just have to wait until the maintainers review your PR.

If you need any help, let us know! 😃

### Additional information

This is a good first issue. Please leave it open to first-time contributors and beginners. 🙂

**Comment by Sriparno08** [comment]
Hey @Panquesito7, I would like to work on this issue!

**Comment by Sriparno08** [comment]
Hey @Panquesito7, there is no space before the `**` at the end:

```
**Optional fields: `milestones`, `type(personal | community)`, `socials`, `testimonials` and `events`**
```

**Comment by aravindraveendran7** [comment]
Hello Team, bit confused here with the line number mentioned in the description. Mentioned here as 17, however the same as in line number 65 in the readme.md. Could you please help me with this as am referring to the correct one.

**Comment by eddiejaoude** [comment]
I think this has already been fixed, that is why there no space anymore. I will close this, sorry for the confusion. 

Please have a look at our other open issues and any questions let us know https://github.com/EddieHubCommunity/LinkFree/issues

**Comment by Sriparno08** [comment]
No problem, Eddie!

**Comment by aravindraveendran7** [comment]
Thank you @eddiejaoude
