### ISSUE TITLE
[DOCS] "Next" command missing in the documentation 

### ISSUE THREAD

**Issue by yrs147** [EddieHubCommunity/LinkFree#2488]
### Description

I was working on an issue earlier. So when I try to run the project locally, it always shows the error "next not recognized as an internal and external command", then I need to enter the "npm install next" command to make it run locally. I faced this earlier as well when I was working on another device. I believe the documentation should be changed to fix this issue to make the process of setting up the project locally more convenient.

### Screenshots

![image](https://user-images.githubusercontent.com/98258627/209472573-c1caca84-32f8-4f6d-b14a-88617ec09003.png)

**Comment by yrs147** [comment]
I want to work on this issue @eddiejaoude

**Comment by adityassharma-ss** [comment]
Try updating the node packages on your local repository because I don't think that there is an issue with the LinkFree repo.
