### ISSUE TITLE
Explore React's accessibility docs to ensure aria tags, alt tags etc are correct.

### ISSUE THREAD

**Issue by stemount** [EddieHubCommunity/LinkFree#25]
React has really good accessibility support, and it would be good for someone to explore the React docs and ensure that this has all the aria labels, alt tag on the avatar of the persons name, all this good stuff.

**Comment by nhcarrigan** [comment]
An excellent tool to use for testing accessibility is https://wave.webaim.org/. Not sure if it tests for aria labels, but it is a great starting point.

**Comment by emmalearnscode** [comment]
I would like to work on this issue. Can someone please assign it to me?

**Comment by eddiejaoude** [comment]
Thank you @emmalearnscode for the PR, great work 💥
