### ISSUE TITLE
[DOCS] <Typo in the Quickstart Guide>

### ISSUE THREAD

**Issue by Sriparno08** [EddieHubCommunity/LinkFree#2501]
### Description

There is an issue in the Quickstart Guide. Follow these steps to spot the issue:

Step 1: Go to https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/docs/quickstart.mdx
Step 2: Scroll down to number 8 and find the table underneath the json structure
Step 3: Check the description of the field named "bio"

It says:

> Your description about yourself (you an use markdown here)

It needs to be changed to:

> Your description about yourself (you can use markdown here)

### Screenshots

![Untitled design](https://user-images.githubusercontent.com/89148144/209562042-5a22ebad-d3a9-4181-b311-5e1a7905ba82.png)

**Comment by Ertan222** [comment]
I am fix it right now.

**Comment by Ertan222** [comment]
#2502 going to fix this issue.

**Comment by Aadarsh805** [comment]
@Sriparno08 this can be closed now

**Comment by eddiejaoude** [comment]
Thank you all for collaborating and fixing. 

To avoid extra notifications please in your Pull Request write `closes #2501`, then when the PR is closed/merged, the issue will also be done automatically
