### ISSUE TITLE
[DOCS] Add a copy code button for all code blocks in Quickstart

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#2521]
### Description

To improve UX, add a copy code button/icon to the top right of each code block in the LInkfree quikstart

https://linkfree.eddiehub.io/docs/quickstart

**Comment by marksist300** [comment]
I'm happy to be assigned this issue to work on, if that's alright with everyone?

**Comment by ChinmayMhatre** [comment]
This seems like a great idea! I would like to work on this.

**Comment by eddiejaoude** [comment]
Sure I have assigned it to you @ChinmayMhatre

**Comment by ChinmayMhatre** [comment]
Hey @amandamartin-dev , Do you know where I could get started on this? is there a library ? If not do you know how I could go about this? 

I found this resource https://philstainer.io/blog/copy-code-button-markdown . but I am unable to implement it here

**Comment by eddiejaoude** [comment]
This blog looks useful https://blog.logrocket.com/implementing-copy-clipboard-react-clipboard-api/

**Comment by ChinmayMhatre** [comment]
Hey Eddie, I wasn't able to understand how to wrap the component around the mdx code block. Since we navigate to the mdx file using a link, I am confused how to pass the custom component to the mdx file. do I just import it?

**Comment by ChinmayMhatre** [comment]
Hey Eddie, I think I figured it out. Could you check if the PR is good?

**Comment by eddiejaoude** [comment]
yes I got the PR notifications and left some comments
