### ISSUE TITLE
[DOCS] Quickstart step 9 - link to icon search page

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#2522]
### Description

In Step 9 of the quickstart, it is mentioned that the user must grab icon definitions from react font awesome fa/si.  To improve UX, link to the icon search page on LinkFree.  Make sure to open in a new tab automatically so the user does not lose their place in the documentation

https://linkfree.eddiehub.io/icons

**Comment by Rounak-28** [comment]
link to the icon search page on LinkFree is already there:
![Screenshot from 2022-12-28 18-17-51](https://user-images.githubusercontent.com/95576871/209814817-ec0e4f39-1a9f-47aa-bd7c-6a17fb7d13cd.png)

But yeah it does not open a new tab to that page.

**Comment by amandamartin-dev** [comment]
@Rounak-28 so weird! It wasn't when I was reviewing, I must have missed the update but yes can it open in a new tab so the user cannot lose their place in the directions. Thank you

**Comment by Rounak-28** [comment]
I tried but `target="_blank"` is not working on the markdown file, is it not possible on markdown?

**Comment by amandamartin-dev** [comment]
I haven't worked on the docs page myself but some markdown allows for you to use regular HTML within it. If the docs are via GitHub markdown, you may have to look through their docs to see what is recommended in this case

I can take a look later after work if you are not able to find the answer. You can also try asking in contributor-support or help in discord as someone else may be more available to check

**Comment by Parsifal-M** [comment]
I believe adding something like `<a href="https://linkfree.eddiehub.io/icons" target="_blank"> Icons Here </a>` should work, I've not had time to set up my local dev environment but if someone wants to try the above I think it should work :smile:

**Comment by Rounak-28** [comment]
@Parsifal-M I tried the same but It's not working.

**Comment by Parsifal-M** [comment]
> @Parsifal-M I tried the same but It's not working.

Oh :disappointed:, maybe the alternative could be to use `[link](url){:target="_blank"}`? If that does not work we'll have to do a bit more R&D :smile:

**Comment by amandamartin-dev** [comment]
Great collaboration going on here! One thing to add don't forget about noreferrer for security when you do implement

**Comment by alokVerma749** [comment]
PR: #4250 solves this issue
