### ISSUE TITLE
[FEATURE] Algorithm to list popular profiles

### ISSUE THREAD

**Issue by roopeshsn** [EddieHubCommunity/LinkFree#2525]
### Description

How will it be if there is an algorithm to list the popular profiles by any parameters? To achieve this, we can get to know the popularity of a user by scraping into their social media profiles. Through this, we can assign a score to each user and according to this rating, we can render the popular profiles.

**Comment by legendarykamal** [comment]
@Panquesito7 @eddejayaklu any algorithms that guys have in mind for this ?

**Comment by Panquesito7** [comment]
Not 100% sure about that. We would need to calculate points and other stats (such as views or testimonials), and given that, we can show the most popular profiles on the most popular profiles page.
Let's wait and see what do the maintainers and the community think about this feature. 🙂

**Comment by eddiejaoude** [comment]
I think let's keep it simple for now, we have higher priority items that need doing first. I will close this for now not to cause any confusion or distraction.
