### ISSUE TITLE
[FEATURE] Filter events for virtual / in person

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2528]
### Description

After this PR is merged https://github.com/EddieHubCommunity/LinkFree/pull/2527

Click the key cards to filter events

<img width="1363" alt="Screenshot 2022-12-28 at 22 09 27" src="https://user-images.githubusercontent.com/624760/209880417-07dc5bda-a295-4ac1-8a49-c532c7e83fc6.png">

**Comment by adityassharma-ss** [comment]
Hey @eddiejaoude 
Can you assign this to me?

**Comment by abhijain2003** [comment]
hey eddie can I work on this, I really wanted to get started in open source

please help me

**Comment by eddiejaoude** [comment]
Sure 👍 , do you want me to assign it to you?

**Comment by abhijain2003** [comment]
yes eddie

**Comment by eddiejaoude** [comment]
Assigned to you 👍 

We have a new docs section in the app https://linkfree.eddiehub.io/docs (anything missing let us know)

Any questions you can ask in our EddieHub Discord

**Comment by abhijain2003** [comment]
thanks
