### ISSUE TITLE
[FEATURE] Display event totals in the relevant cards

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2529]
### Description

After this PR is merged https://github.com/EddieHubCommunity/LinkFree/pull/2527

Show totals for each in the relevant cards

<img width="1363" alt="Screenshot 2022-12-28 at 22 09 27" src="https://user-images.githubusercontent.com/624760/209880417-07dc5bda-a295-4ac1-8a49-c532c7e83fc6.png">

**Comment by ThorOnTheRocks** [comment]
@eddiejaoude Hi Eddie can I work on this one?

**Comment by eddiejaoude** [comment]
Sure @ThorOnTheRocks 👍

**Comment by ThorOnTheRocks** [comment]
Great! Thank u so much @eddiejaoude !
