### ISSUE TITLE
[DOCS] Quickstart improvement link to expanded profile setup

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#2535]
### Description

This quickstart covers how to setup the links portion of a new users LinkFree profile.  For someone who would like to continue and build out the other sections (events, milestones, testimonials, tags, etc) there is no reference to where to directly find that information.

Recommending 2 updates:
1. In the beginning paragraphs, explain what the quickstart will cover and link to where to find more info
2. Before step 10 where the user will commit, remind them that if they would prefer to add more categories first they can and link to those docs page for them to find more info

**Comment by Saha-7** [comment]
https://linkfree.eddiehub.io/docs/quickstart

**Comment by eddiejaoude** [comment]
Thanks Amanda 👍 I did a quick fix by adding `next steps` section to the end of the `QuickStart guide` to help

<img width="1433" alt="Screenshot 2023-01-07 at 10 12 43" src="https://user-images.githubusercontent.com/624760/211145225-ae88e9d7-2b95-4042-8e6c-0f892293bac4.png">

**Comment by amandamartin-dev** [comment]
Just saw this! That sounds good to me

**Comment by SaraJaoude** [comment]
> 1. In the beginning paragraphs, explain what the quickstart will cover and link to where to find more info

We now have this at the end in `Next Steps` 

> 2. Before step 10 where the user will commit, remind them that if they would prefer to add more categories first they can and link to those docs page for them to find more info

My concern is that adding a reminder at this stage may confuse some people, and it would be best to keep it as simple and straightforward so that people can add their profile. So I will close this for now and suggest we revisit in the future as we get feedback.
