### ISSUE TITLE
[DOCS] Quickstart image improvement

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#2536]
### Description

In the quickstart, any step with a corresponding image where the user is looking for a button or some other feature, the image should be updated with a visual aid to show where the button is

Example:
THese 2 items could be surrounded with a red square or other highlight to draw the eye to where they are in the screenshot
Step 3: If you wish to be kept up to date with the repo, hit that "Star" at the top right
Step 4: Click on Fork

**Comment by ChinmayMhatre** [comment]
I edited the two images. Could you take a look if this is good?
<img width="1676" alt="fork" src="https://user-images.githubusercontent.com/51131670/210128263-0716b260-5922-4db3-933d-f7e992b668a9.png">
<img width="1657" alt="star" src="https://user-images.githubusercontent.com/51131670/210128265-8a23977a-e80e-4037-b94b-253f5a23b8e7.png">

**Comment by amandamartin-dev** [comment]
@ChinmayMhatre Looks good! Do you think any other images in the quickstart could use editing or are the others clear enough in your opinion.  Perhaps the "create pull request" images? wdyt?

**Comment by ChinmayMhatre** [comment]
Hey @amandamartin-dev , I feel we could add this image at 6. click "Add file". What do you think?
![image](https://user-images.githubusercontent.com/51131670/210201815-9c56ca28-19e8-4ef9-9934-6014d5262624.png)

**Comment by amandamartin-dev** [comment]
@ChinmayMhatre I think that makes sense! Make sure to include what the final look is on your PR so the maintainers can see/approve/merge

**Comment by ChinmayMhatre** [comment]
@amandamartin-dev , Do the links to the image expire after the issue is closed? I was wondering if I should use the image url from this issue.

**Comment by eddiejaoude** [comment]
@ChinmayMhatre we use the image url from the issue, they do not expire - you can check this with other images in the docs

**Comment by ChinmayMhatre** [comment]
> @ChinmayMhatre we use the image url from the issue, they do not expire - you can check this with other images in the docs

Oh okay! I'll just add these then.
