### ISSUE TITLE
[DOCS] Quickstart Step 5 - link to turn off workflow docs

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#2537]
### Description

In step 5 after the user has forked the repo, they may want to turn off any workflows running.  Suggestion to link to the documentation for how to do this

https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow

**Comment by ChinmayMhatre** [comment]
Hey @amandamartin-dev , I could add the doc. Do you think a new step should be added or should this be in a note of sorts?

**Comment by ChinmayMhatre** [comment]
I'd like to take this issue.

**Comment by amandamartin-dev** [comment]
@ChinmayMhatre Hello! I'm so sorry I missed your first notification.  You are welcome to take this, but I am not able to assign you.  I think you can add as a step or notes, whatever you think will be best.  Thank you so much!

**Comment by ChinmayMhatre** [comment]
Hey @amandamartin-dev , eddie mentioned that the workflows are disabled by default in the forks. I also checked it in my fork. I guess we could skip this instruction.
![image](https://user-images.githubusercontent.com/51131670/211353210-f055c26f-c9c8-4858-b45f-739048255315.png)

**Comment by amandamartin-dev** [comment]
@ChinmayMhatre good catch! When I forked and made this ticket the workflows were running in my fork and I had to turn them off manually, they must have been turned off by default after that.

@eddiejaoude can you confirm that this issue is no longer needed? If not, we can close the ticket

**Comment by amandamartin-dev** [comment]
closing as no longer needed
