### ISSUE TITLE
[DOCS] Quckstart improvement - explain json structure

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#2538]
### Description

In step 8 where the first bit of JSON is presented, it is not explicitly stated that the next chunk of JSON should live inside the curly braces and not be copy/pasted below.

If a new user is not familiar with JSON they may not realize this and have confusing JSON errors when they try to merge at the end.

Recommend explaining briefly the json structure in step 8 or 9 to prevent this

**Comment by mohit1607** [comment]
I would like to change that text, assign me this task

**Comment by mohit1607** [comment]
By observing I came to conclusion that we can edit the bolck of code in 9th step to include the whole json structure with links array. Is it good ?

**Comment by amandamartin-dev** [comment]
hey @mohit1607 thanks for looking into this! I cannot assign you as I'm not a maintainer on this repo, but you are welcome to work on it as no one else is yet.  When you make the adjustment you are suggesting, can you put some screenshots of the new directions/code so that it can be reviewed for clarity with your PR?  It will be hard to know until anyone can see it, but it sounds good to try!

**Comment by mohit1607** [comment]
Ok @amandamartin-dev  thanks for reply I will try to do it.

**Comment by eddiejaoude** [comment]
Great collab everyone! I have assigned it to you @mohit1607

**Comment by mohit1607** [comment]
Thanks eddie I wil do it

**Comment by mohit1607** [comment]
![Screenshot (5732)](https://user-images.githubusercontent.com/57750800/210166528-100224ed-419b-40ea-afeb-0abff84b3644.png)
It should look like this.

**Comment by mohit1607** [comment]
Do I commit it ?

**Comment by eddiejaoude** [comment]
PR merged
