### ISSUE TITLE
[FEATURE] Popular profile page to show random users at the top

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2558]
### Description

Maybe select 2 random users to appear at the top of the popular profile page to help create awareness of profiles

**Comment by thevinitgupta** [comment]
How would the random users be selected?

**Comment by eddiejaoude** [comment]
What do you mean? It will be selected at random from the list of users in the database

**Comment by thevinitgupta** [comment]
I wanted to know if the selection will be completely random or any fixed algorithm to select.

**Comment by eddiejaoude** [comment]
Let's keep it simple and make it completely random

**Comment by ManishBisht777** [comment]
@eddiejaoude can we make a `button` to switch between `popular/featured profiles` and `random/new users `by default we can show new/random users
also by this so we `don't have to make a separate API call` for just 2-3 user :)

**Comment by eddiejaoude** [comment]
I think as we have small cards, having 2 sections on a single page would be better for now - the API calls are done on the server side I think

**Comment by eddiejaoude** [comment]
@ManishBisht777 there is still only 1 API call, as the end point is now `discover` not `popular`, so it will return all the required data 👍

**Comment by ManishBisht777** [comment]
> @ManishBisht777 there is still only 1 API call, as the end point is now `discover` not `popular`, so it will return all the required data +1

That's nice
