### ISSUE TITLE
[DOCS] Addition of a Click to Copy button to the docs bio page example code

### ISSUE THREAD

**Issue by Rishav-12** [EddieHubCommunity/LinkFree#2559]
### Description

The example code in the `bio` page (https://linkfree.eddiehub.io/docs/how-to-guides/bio) should have a Click to Copy button.

The `quickstart` page (https://linkfree.eddiehub.io/docs/quickstart) already has that component, can be used it as reference.

**Comment by VamshiReddy02** [comment]
Can I take up this issue?

**Comment by eddiejaoude** [comment]
Sure @VamshiReddy02 , assigned

**Comment by Anan7Codes** [comment]
Ah man, didn't notice it was assigned to somebody else :/
