### ISSUE TITLE
Add issue forms and pull request template

### ISSUE THREAD

**Issue by AbhijithGanesh** [EddieHubCommunity/LinkFree#256]
We need issue forms, bug forms and other templates to facilitate smoother workflow

**Comment by Zain-Muiz** [comment]
Can I work on this ? @AbhijithGanesh

**Comment by AbhijithGanesh** [comment]
Feel free to, I think this issue was created for the community members. Work on this and we'll review. 

Have a great day😄
@Panquesito7 and coding species, please note : I have asked Zain-Muiz to work on this.

**Comment by CodingSpecies** [comment]
This will help, as it will make it clearer in workflows, and how the maintainers, and others will understand each issue, as they are categorically listed, easier to navigate and sort. 
Thank you for working on this @Zain-Muiz
