### ISSUE TITLE
[DOCS] Addition of a Click to Copy button to the docs links page example code

### ISSUE THREAD

**Issue by Rishav-12** [EddieHubCommunity/LinkFree#2561]
### Description

The example code in the `links` page (https://linkfree.eddiehub.io/docs/how-to-guides/links) should have a Click to Copy button.

The `quickstart` page (https://linkfree.eddiehub.io/docs/quickstart) already has that component, can be used it as reference.

**Comment by harsitagarwalla187** [comment]
Hi. I am interested in contributing to this issue.
Could you guide me where i can this issue repository.

**Comment by eddiejaoude** [comment]
Hi @harsitagarwalla187 we have a few people already submitted PRs for this issue, please could you select another issue
