### ISSUE TITLE
backticks not getting rendered in Docs

### ISSUE THREAD

**Issue by Pradumnasaraf** [EddieHubCommunity/LinkFree#2562]
### Description

On the website, the backticks are not getting rendered. It's bolding just bolding up the text. 

**It should look something like** `sample-text` 

- Link to Docs folder - https://github.com/EddieHubCommunity/LinkFree/tree/main/pages/docs
- Link to the hosted site -  https://linkfree.eddiehub.io/docs

### Screenshots

<img width="1506" alt="Screenshot 2023-01-01 at 3 49 46 PM" src="https://user-images.githubusercontent.com/51878265/210168393-02abfcf2-8cea-4ce3-a23b-fa92a1e9d829.png">

Above Screenshot hosted link - https://linkfree.eddiehub.io/docs/contributing/hacktoberfest

**Comment by dan-mba** [comment]
I think this is related to the configuration of `remark-prism` which is done in [next.config.mjs](https://github.com/EddieHubCommunity/LinkFree/blob/main/next.config.mjs#L38-L44).

There is an option for it to handle [inline code](https://github.com/sergioramos/remark-prism#transforminlinecode), but it is off by default.

**Comment by AldrinSeanPereira** [comment]
I'd like to take up this bug. 

I referred to the links given by @dan-mba but I'm stuck at finding what needs to be fixed ... may need to spend more time (or not)

any advice would be appreciated :)

**Comment by dan-mba** [comment]
@AldrinSeanPereira the format of the plugins for `@next/mdx` isn't well documented, but it links to this [MDX documentation](https://mdxjs.com/docs/extending-mdx/#using-plugins).

I think `remarkPrism` needs to be changed to `[remarkPrism, {transformInlineCode: true}]`

**Comment by AldrinSeanPereira** [comment]
alright. thank you !!
