### ISSUE TITLE
The navbar doesn't close when the user navigates to another page

### ISSUE THREAD

**Issue by Olaleye-Blessing** [EddieHubCommunity/LinkFree#2569]
### Description

The navbar remains open when a user navigates to another page. 

### Screenshots

![58D47D84-AEF4-4F4E-A370-BF51D6998923](https://user-images.githubusercontent.com/70102539/210177476-ac0d52a9-3724-4b0f-b935-a646fa30578b.png)

**Comment by Olaleye-Blessing** [comment]
I'll like to work on it.

**Comment by eddiejaoude** [comment]
I think this issue is a duplicate of this one https://github.com/EddieHubCommunity/LinkFree/issues/2464

**Comment by Olaleye-Blessing** [comment]
Oh! True.
