### ISSUE TITLE
Storybook needs updating since the latest release of NextJS

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2570]
### Description

We have Storybook in the project but it was disabled as it had issues with the latest version of NextJS we were using.

But hopefully this can be resolved now and added back in

**Comment by adityassharma-ss** [comment]
I will be working on this, assign it to me. @eddiejaoude

**Comment by eddiejaoude** [comment]
Sure, assigned 👍

**Comment by adityassharma-ss** [comment]
Hey, @eddiejaoude Can you give more details regarding this issue? Do you want the stories tab to appear with other tabs like testimonials & events?

**Comment by eddiejaoude** [comment]
Storybook runs as a separate app, loading our components. We have some components already in Storybook, but it was removed from our application due to version conflicts when NextJS 13 came out.

This issue is about adding Storybook back as a dependency and being able to run the Storybook app to see and play with our React components

**Comment by ChinmayMhatre** [comment]
Hey @adityassharma-ss would you mind if I work on this? In case you haven't started already?

**Comment by adityassharma-ss** [comment]
@ChinmayMhatre Yes, man. I'm quite busy with my college & BSOC'23. That's why i'm not able to give time to linkfree.

**Comment by ChinmayMhatre** [comment]
> @ChinmayMhatre Yes, man. I'm quite busy with my college & BSOC'23. That's why i'm not able to give time to linkfree.

No worries! All the best for your exams!👍🏻

**Comment by ChinmayMhatre** [comment]
Hey @eddiejaoude , I was wondering if this issue needs to be closed? I think storybooks is already running in the project?🤔

**Comment by SaraJaoude** [comment]
@ChinmayMhatre yes you are correct 👍🏼 thank you
