### ISSUE TITLE
[FEATURE] Popular profiles to display profile view count

### ISSUE THREAD

**Issue by harsitagarwalla187** [EddieHubCommunity/LinkFree#2576]
### Description

Add a badge that displays number of  viewer has viewed the profile at the top right of the image of the User Card in the Popular Profiles page to display number .

### Screenshots

![Screenshot 2023-01-02 023412](https://user-images.githubusercontent.com/84774840/210184531-f57506f6-384d-45d0-812d-23b2a4c56273.png)
Similar to above profile in the below one.
![Screenshot 2023-01-02 023434](https://user-images.githubusercontent.com/84774840/210184538-b86ffa5b-8710-4cbe-b9d9-18254d3063d8.png)

**Comment by harsitagarwalla187** [comment]
Please assign this to me.

**Comment by eddiejaoude** [comment]
Sure, assigned
