### ISSUE TITLE
running sonarqube and jenkins for static code analysis

### ISSUE THREAD

**Issue by ShlokMohanty** [EddieHubCommunity/LinkFree#258]
in this we will be building the test reports and then passing some build commands after that we would be doing some static code analysis using the sonarQube .
below link is for hacking out the sonarQube website :
https://www.sonarqube.org/

**Comment by ShlokMohanty** [comment]
@eddiejaoude can we add some tag to this issue like build/code analysis?

**Comment by eddiejaoude** [comment]
Is there a GitHub Action for this available?

**Comment by ShlokMohanty** [comment]
@eddiejaoude not sure but will check it and if available then yes we can try to solve it .

**Comment by krishguptadev** [comment]
I think https://deepsource.io is a better options.. But only @eddiejaoude can do it
