### ISSUE TITLE
Popular profiles should not have profiles that do not display views

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2581]
### Description

If a profile has stats hidden, then we should not include their profile on the popular profile page

The API `api/users/popular` will need to only return profiles that have stats enabled for their profile

**Comment by KlausMikhaelson** [comment]
Hey @eddiejaoude can I work on this issue ?

**Comment by eddiejaoude** [comment]
Sure @KlausMikhaelson

**Comment by eddiejaoude** [comment]
@KlausMikhaelson the issue is still for you, @shyam0705 didn't notice it was assigned and kindly closed their pull request

**Comment by KlausMikhaelson** [comment]
thanks you @eddiejaoude will create the pr soon !

**Comment by KlausMikhaelson** [comment]
Hey @eddiejaoude have created the pr, do lmk if there is anything to change !
Thank you !

**Comment by KlausMikhaelson** [comment]
Hey @eddiejaoude was facing some issues with my forked repo so I reforked it and now instead of filtering the first 10 profiles it's checking the stats first and than out of those popular profiles who has there stats public it's gonna take the first 10.
took the reference from shaym so thank you !
