### ISSUE TITLE
Popular profiles should be selected on the last 28 days

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2582]
### Description

Currently they are selected on total views, but then it is difficult for other people to appear

We would need to store daily totals for each person, similar to the way we do it for the application totals https://github.com/EddieHubCommunity/LinkFree/blob/main/models/Stats.js

**Comment by imran1509** [comment]
Well we can have Sub-section or separate section of "Popular profiles of the month".
This way we can have both all time popular and monthly popular profile as well.

**Comment by shyam0705** [comment]
Can I work on this issue? in profile schema, we can add one more field stats that refer to StatsSchema.

**Comment by eddiejaoude** [comment]
PR merged, thanks 👍
