### ISSUE TITLE
[FEATURE] Daily stats for new users

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2587]
### Description

It would be great to keep stats per day for the app

https://github.com/EddieHubCommunity/LinkFree/blob/main/models/Stats.js

**Comment by joeshajan** [comment]
Hey @eddiejaoude does this mean we are only showing the count for one particular day instead of the total count from the beginning?

Or is it showing the counts per day separately?

**Comment by eddiejaoude** [comment]
We don't store the data yet, so in this issue...
- store the daily count
- display the daily count on the home page (next to the total)

**Comment by joeshajan** [comment]
Ok got it. I would like to do this. Can you assign this to me?

**Comment by eddiejaoude** [comment]
Sure, assigned 👍

**Comment by joeshajan** [comment]
Hey, @eddiejaoude is this feature #2118 already added?

So we already have this daily count here right? (marked in red)

So where should I display the daily count now?

I'm totally confused and need help.

![image](https://user-images.githubusercontent.com/69904519/211160470-764db987-7d8a-459e-b764-b53b9a2e0b4c.png)

**Comment by eddiejaoude** [comment]
The first box has total users only, this issue is to add a daily counter to the database for users in the system. So like the 2nd and 3rd box you circled, today's increase can be added to the first box in green with the up arrow

**Comment by joeshajan** [comment]
Thank you @eddiejaoude got it. Will do.
