### ISSUE TITLE
Removing the profile picture from the json

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2598]
### Description

We have each person's GitHub username, so we can get their profile picture

- remove the `avatar ` from every profile json file
- where the `avatar` was used before, replace with `https://github.com/${username}.png`

**Comment by dan-mba** [comment]
Is avatar optional in the current schema?
If so, I would suggest an optional  `noAvatar` boolean, to use a generic letter avatar instead of the GitHub avatar.

**Comment by eddiejaoude** [comment]
We don't say it is optional but it does default to the letter avatar

The reason I raised the issue, is I see people copying someone else's profile and forgetting to change the avatar image, so I thought this would be less work for them and less risk of a mistake if we always use the GitHub profile picture - but I appreciate it is less flexible

**Comment by riteshsonawane1372** [comment]
Okay will do it assign me

**Comment by eddiejaoude** [comment]
@riteshsonawane1372 thank you , but it is just an idea to discuss at the moment

**Comment by eddiejaoude** [comment]
I will close this issue also to avoid confusion

**Comment by riteshsonawane1372** [comment]
Okay.
