### ISSUE TITLE
[BUG] Profile view is showing NAN 

### ISSUE THREAD

**Issue by Pradumnasaraf** [EddieHubCommunity/LinkFree#2626]
### Description

The profile view is showing **-NAN** instead of hidden when the profile views are zero.

### Screenshots

<img width="1512" alt="Screenshot 2023-01-03 at 11 05 56 PM" src="https://user-images.githubusercontent.com/51878265/210413663-1f79c784-23b9-4902-8572-6d287f422682.png">

**Comment by dan-mba** [comment]
I think the easiest way to fix this would be adding the following code before [line 38](https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/api/users/index.js#L38) of `pages/api/users/index.js`

```javascript
    if (user.displayStatsPublic) {
      return {
        ...user,
        views: 0
      };
    }
```

This would eliminate the need for error handling on the front-end.

**Comment by eddiejaoude** [comment]
I think it is best to not return a `0` from the API because it is probably not correct, they do have views but they are hidden.

The frontend should probably check if `views` is set, if not set then don't display the badge. We use something like this in other places:

```js
{ views && ... }
```

**Comment by eddiejaoude** [comment]
Oh it has a check, but the wrong variable, probably because the api got updated not to pass back profiles that have their stats private

**Comment by eddiejaoude** [comment]
I fixed it, as I felt it was fairly high priority....

<img width="1392" alt="Screenshot 2023-01-03 at 19 50 24" src="https://user-images.githubusercontent.com/624760/210431625-fd7c7683-e011-446e-8550-e034ef1948a7.png">
