### ISSUE TITLE
[FEATURE] New badge that changes to views later

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#2630]
### Description

This is an idea to increase an inclusive feeling on the popular profiles page and also highlight new to linkfree folks.

When a new profile is created, where the profile views are will say "New" until the user has reached a certain amount of views (say 10 for example).  This way, new users are highlighted and no one would ever have a zero count to start

Potential issue for discussion:  A new tag may not make sense once a visitor clicks through the the profile, but only in the context of the search profiles, popular profiles pages.  Would need a decision on where this badge makes sense.  Could be back to the views count on click through if the context makes more sense that way.

Other issue for discussion - do folks without views shown get a new badge and if so, for how long

Example New:

![Eddie Linkfree profile with new in the views badge](https://user-images.githubusercontent.com/97615019/210453800-33f4228e-04aa-45af-b4c0-5987df7d32be.jpg)

**Comment by abhijain2003** [comment]
i think if we are storing view data in database, we can show number of view at absolute position on profile image, instead of new, 

for eg. 1.3k etc and even for new members we can write new over there

**Comment by sansarmaske** [comment]
I would like to work on this.

**Comment by amandamartin-dev** [comment]
@SaraJaoude and/or @eddiejaoude got a notification on this issue and see it's "read for dev", but it's from when we had views on the profiles which has now been hidden.  Should this issue be closed for now or are we bringing back views?

**Comment by eddiejaoude** [comment]
Oh yes, good point Amanda. We can now close this issue as it is not longer required 👍
