### ISSUE TITLE
LinkFree webpage screenshot issue Your Tags

### ISSUE THREAD

**Issue by loftwah** [EddieHubCommunity/LinkFree#2631]
### Description

The screenshot for Your Tags on the website contains artefacts from surrounding objects on the page.

Can we please crop this out so it looks cleaner?

- DL 🙇‍♂️

### Screenshots

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/19922556/210474265-5707949f-092e-4a84-8fb8-81fb3c33a16e.png">

**Comment by Shivam-AfA** [comment]
Hey! I would like to work on this issue.

**Comment by eddiejaoude** [comment]
Sure, assigned @Shivam-AfA

**Comment by ChinmayMhatre** [comment]
Hey @Shivam-AfA , do you need any help with the issue?

**Comment by eddiejaoude** [comment]
Thanks @ChinmayMhatre 👍 I notice this has now been fixed on the website already but the PR wasn't linked to the issue. I will close this as it is now done
