### ISSUE TITLE
Artifacts on the web page for LinkFree on the QR Codes screenshot

### ISSUE THREAD

**Issue by loftwah** [EddieHubCommunity/LinkFree#2632]
### Description

This is the same issue as I just raised with the other section.

The screenshot we have used contains little bits of text that can be cropped out.

- DL 🙇‍♂️

### Screenshots

<img width="1291" alt="image" src="https://user-images.githubusercontent.com/19922556/210474655-8cb751a6-f407-4269-b5a8-7c1703ba8404.png">

**Comment by KlausMikhaelson** [comment]
Hello @loftwah if it is approved than can I work on this issue ?

**Comment by loftwah** [comment]
All good with me, assuming it is approved and nobody else has it earmarked.

**Comment by KlausMikhaelson** [comment]
awesome ! have created a pr !
