### ISSUE TITLE
"Use of async/await and fs.promises to Improve efficiency of profile loading code"

### ISSUE THREAD

**Issue by yashdev9274** [EddieHubCommunity/LinkFree#2640]
### Description

Using the 'async' and 'await' keywords, as well as the 'fs.promises' API, can improve the efficiency of the code by allowing it to perform multiple operations concurrently, rather than waiting for each operation to finish before starting the next one. This can result in faster execution times and reduced server load.

Additionally, using pagination or filtering to limit the number of documents retrieved from the 'Profile' collection can also improve efficiency by reducing the amount of data that needs to be processed.

Finally, wrapping the 'JSON.parse' function in a try-catch block can help handle any errors that might occur during parsing, which can help improve the reliability and robustness of the code.

### Screenshots

![image](https://user-images.githubusercontent.com/72986960/210489014-61822e1d-23db-44b2-af82-21a18ea6e32f.png)

### Additional information

I hope this helps! Let me know if you have think there should be any changes required.

**Comment by eddiejaoude** [comment]
Challenge with doing them async, is that we can't append the username from the file name into the json
