### ISSUE TITLE
[FEATURE] Notification on community events

### ISSUE THREAD

**Issue by nanthakumaran-s** [EddieHubCommunity/LinkFree#2642]
### Description

A mailing list where users can get updates about community events posted on the LinkFree website.

**Comment by eddiejaoude** [comment]
Great idea 👍

**Comment by eddiejaoude** [comment]
@Susmita-Dey I think that is a great idea, we can pick some events from the list and add it to the EddieHub newsletter 👍  (@SaraJaoude this will be useful when you create the newsletter)

**Comment by SaraJaoude** [comment]
I will add Events to the EddieHub Newsletter, so I will close this issue for now and we can explore a mailing list in the future in a next major version.
