### ISSUE TITLE
[FEATURE] Profile playground and check page

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2645]
### Description

Playground page where people can add their profile json into a form and it shows them what it would look like

- validates json
- formats json
- shows main profile (bio, tags, social shortcuts)
- shows links
- shows milestones

**Comment by samyabrata-maji** [comment]
I think I can implement it. @eddiejaoude should I work on this?

**Comment by eddiejaoude** [comment]
@samyabrata-maji how is it going? If you are busy don't worry, we will unassigned it so others can work on it, let me know

**Comment by samyabrata-maji** [comment]
@eddiejaoude I tried solving it. Couldn't implement it. I think its better to assign it to someone else.

**Comment by yatharth1706** [comment]
Hy @eddiejaoude, I read the issue and I think I can implement this. Let me just confirm it once with you if I understood it correctly.

So basically we will have one more link in the navigation bar named as "Playground". When user will click on it, a form will appear where user can enter their profile json. Option to validate and format the json should be there in the page.

Option to preview how json will look in the website must also be there.

Correct eddie

**Comment by yatharth1706** [comment]
Have done some development. Attaching screenshots. Let me know if these looks fine. Also please suggest any ui improvements.

Features added:
- Playground page
- Preview page

## Playground page
![Playground1](https://user-images.githubusercontent.com/32243289/215320129-46f93686-8f8f-4de2-ae3b-350f536f25a4.png)

## Validations
![Validation1](https://user-images.githubusercontent.com/32243289/215320172-20c60bed-bde2-4e1d-ab8d-c3eb43cd4587.png)

![jsonValidate](https://user-images.githubusercontent.com/32243289/215320315-40e3eb3b-269b-4f13-a98e-653c1b8498af.png)

## Playground with all values filled
![Playground2](https://user-images.githubusercontent.com/32243289/215320156-c6a46306-6443-4621-ba2f-7c407c957aab.png)

## Preview page
![Preview page](https://user-images.githubusercontent.com/32243289/215320168-cffc07df-7508-4ab8-9a04-db55e8b6b3fa.png)

**Comment by eddiejaoude** [comment]
Love the json validator with line numbers 👍 

It would be good if the preview of the profile was on the same page?

Push the code to a draft pull request and we can take a look and give better suggestions

**Comment by yatharth1706** [comment]
For now preview page is in seperate page. 

We can do in same page. Either we can show in a modal in same page or below the form. Let me know what you think. Will make changes accordingly.

I have created a draft pull request. You can review the code and let me know if any mistakes are there.

**Comment by eddiejaoude** [comment]
A modal is a great idea if it is not too much work, otherwise show it below. Do what is the simplest first and we can improve more later. 

Note we are using tailwindcss, and I have also bought the components package, so if you need any prebuilt components let me know and I can share the code for it
https://tailwindui.com/components/application-ui/overlays/modals

**Comment by yatharth1706** [comment]
Yes sure, I will show the preview in modal then.

Please share the modal code. I will check it and make changes accordingly

**Comment by eddiejaoude** [comment]
This looks great @yatharth1706 👍 . I will have a proper look tomorrow. Thank you and sorry for my slow reply

**Comment by yatharth1706** [comment]
Yeah sure @eddiejaoude. No issues

**Comment by yatharth1706** [comment]
Hi @eddiejaoude, I think you can close this issue now. As my branch has been merged into master with your modifications. Let me know if anything is pending in this feature. Happy to help 😃

**Comment by SaraJaoude** [comment]
> Hi @eddiejaoude, I think you can close this issue now. As my branch has been merged into master with your modifications. Let me know if anything is pending in this feature. Happy to help 😃

Thank you for your contribution and for pointing out it has now been completed! I will close the Issue.
