### ISSUE TITLE
[DOCS] docs page reponsiveness issue

### ISSUE THREAD

**Issue by ChinmayMhatre** [EddieHubCommunity/LinkFree#2654]
### Description

https://linkfree.eddiehub.io/docs

Doesn't seem to be reponsive. Some element seems to be causing the page to expand.

### Screenshots

![image](https://user-images.githubusercontent.com/51131670/210533215-1f79debe-7203-4b5a-ae07-e0270a6f59c8.png)

**Comment by karanrao-github** [comment]
Hi @ChinmayMhatre , Can you please share steps to reproduce it.
I am unable to reproduce it.

**Comment by ChinmayMhatre** [comment]
> Hi @ChinmayMhatre , Can you please share steps to reproduce it. I am unable to reproduce it.

You can just navigate to the link given in the issue in a mobile device or use the browser tools.
https://linkfree.eddiehub.io/docs

**Comment by ManishBisht777** [comment]
This can be fixed by adding a class `break-words` to the `anchor` tag

![image](https://user-images.githubusercontent.com/89926834/210720052-4e28511c-df3e-4858-82bb-437517183a69.png)

Can i create a pull request for this

**Comment by ChinmayMhatre** [comment]
Hey @ManishBisht777 , a PR had been merged for this issue. I'll close this issue now.
