### ISSUE TITLE
[FEATURE] Add custom scrollbar

### ISSUE THREAD

**Issue by Susmita-Dey** [EddieHubCommunity/LinkFree#2656]
### Description

I want to add custom scrollbar to the LinkFree project and replace the existing normal one. 
I'll be editing the `global.css` page in this case.

### Screenshots

![image](https://user-images.githubusercontent.com/79099734/210533456-674bce8e-30cd-4320-901c-9ce5a664f624.png)

### Additional information

You can suggest me the color of the custom scrollbar.

**Comment by eddiejaoude** [comment]
Thanks for the idea Susmita, but I do not think we should customise the scroll bars, this is not good for accessibility - in my opinion we should use the theme of the users device and settings for this
