### ISSUE TITLE
Workflow errors

### ISSUE THREAD

**Issue by CodingSpecies** [EddieHubCommunity/LinkFree#266]
I am not sure if this is duplicate, but every time a place an issue message, commit, or review, it always gives workflow errors. thanks

![image](https://user-images.githubusercontent.com/70807500/134042297-e531223f-755d-43de-84cc-6fd74d61c891.png)

**Comment by rohan-kulkarni-25** [comment]
Duplicate #204  I think this will be solved after solving that

**Comment by CodingSpecies** [comment]
@rohan-kulkarni-25 should I close this?

**Comment by rohan-kulkarni-25** [comment]
> @rohan-kulkarni-25 should I close this?

Please Read the discussion on the issue if you thinks it is the same issue then feel free to close

**Comment by CodingSpecies** [comment]
I think I will close it, once that is sorted, I think this will be too
