### ISSUE TITLE
[FEATURE] <scroll back to top button>

### ISSUE THREAD

**Issue by lewisushindi** [EddieHubCommunity/LinkFree#2670]
### Description

introduction of a scroll back to top arrow at the bottom of the home and docs page could be helpful. saves users time compared to using their mouse's or keypads to manually scroll back at the top

### Screenshots

![Screenshot (86)](https://user-images.githubusercontent.com/104835999/210574383-911613c0-24f9-442d-8062-f62a709fede2.png)

**Comment by dhruvdabhi101** [comment]
I would like to work on this issue.

**Comment by dhruvdabhi101** [comment]
> @dhruvdabhi101 already working on it

okay. 👍

**Comment by eddiejaoude** [comment]
@lewisushindi I have assigned it to you, to avoid confusion

Btw which page are you adding it to? Because some pages have a button at the bottom right already

**Comment by SaraJaoude** [comment]
We have a lot of buttons at the moment so I think this would be an unnecessary distraction on the page - so I will close this issue.
