### ISSUE TITLE
Mobile UI/UX Improvement 

### ISSUE THREAD

**Issue by Anushka-codergirl** [EddieHubCommunity/LinkFree#2673]
### Description

The link is flowing out of main section.
This can be improved!

### Screenshots

![Screenshot_20230104_213646](https://user-images.githubusercontent.com/43162561/210609059-257635ea-2a59-4f14-a925-775e0fe50b68.jpg)

**Comment by dan-mba** [comment]
This is a browser difference problem.
It wraps the link fine in Firefox, but doesn't in Chrome.

The `break-words` tailwind class should fix the problem.

**Comment by LinuxGamer** [comment]
Is this being worked on?

**Comment by eddiejaoude** [comment]
Thanks @Anushka-codergirl for raising and @dan-mba for the suggested solution 👍 

@LinuxGamer assigned to you

**Comment by LinuxGamer** [comment]
So I've got the link to break at the end of the lie, respective of the size of the site, did you want it to ave a `-`? @eddiejaoude

**Comment by eddiejaoude** [comment]
Best to push what you have already with a screenshot to a PR, this will make it easier for us to understand and avoid any confusion

**Comment by ChinmayMhatre** [comment]
Hey, I guess there is a duplicate issue #2654

**Comment by LinuxGamer** [comment]
> Best to push what you have already with a screenshot to a PR, this will make it easier for us to understand and avoid any confusion

Ok, done :)
