### ISSUE TITLE
[FEATURE] Event CFP open icon and end date

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#2677]
### Description

Modify the events json to accept a line item for CFP end date with the following logic (open to discussion if we don't like the proposed logic or there is a better idea)

If CFP end date exists, populate CFP icon -- once the CFP date is passed this icon should automatically be removed
if CFP is left blank, do nothing (assumption being this is unknown or not an event that has a CFP)

Top legend should hold a new icon and explanation for CFP open such as:
Call for Papers Open
This event is accepting applications to speak.

Potential icons:
TbMicrophone2 
VscMegaphone

**Comment by eddiejaoude** [comment]
Love this idea 👍 Going to do it now 🎉

**Comment by Pradumnasaraf** [comment]
Love the idea.
