### ISSUE TITLE
New Testimonial for Eddie Jaoude

### ISSUE THREAD

**Issue by MadhuSaini22** [EddieHubCommunity/LinkFree#2696]
### Name

eddiejaoude

### Title

Most helping and mind blowing person I saw in my life!!

### Description

Eddie is super helpful to everyone, he had done a lot for the community, kindest and most amazing people I saw in my life! Because of Eddie, I stepped into Open Source, joined beautiful EddieHub Community

**Comment by schmelto** [comment]
@eddiejaoude https://github.com/EddieHubCommunity/LinkFree/actions/runs/3845930154/jobs/6550649453

**Comment by eddiejaoude** [comment]
Oh thanks @schmelto - we need to improve that 🤔  ideas welcome 😂

**Comment by eddiejaoude** [comment]
Thank you @MadhuSaini22 for the amazing testimonial ❤️
