### ISSUE TITLE
Load data/*.json file from domain name or from the URL

### ISSUE THREAD

**Issue by stemount** [EddieHubCommunity/LinkFree#27]
To support routes:

`thisproject.com/stemount` would load stemount.json

but if you use this project for your own domain, you could load in this order:

```
json/{{ url_slug }} (support being able to use something.com/url_slug)
json/{{ domain }} (if no URL slug, look at URL domain e.g. something.com.json)
json/me.json (a default in general)
```

**Comment by aaditya9899** [comment]
hey can i work on this?

**Comment by CodingSpecies** [comment]
Is anyone currently working on this issue? This is beause it has been open for a while now. If anyone needs help, feel free to ask!
Thank you.

**Comment by BoseSj** [comment]
> Is anyone currently working on this issue? This is beause it has been open for a while now. If anyone needs help, feel free to ask! Thank you.

Hi, I want to work on this issue. Please let me know, how to understand the problem and go through it.

**Comment by stemount** [comment]
Did LinkFree ever get this functionality?

**Comment by eddiejaoude** [comment]
I don't think so, if features are going to are added, probably best to add it to the `nextjs` branch though

**Comment by eddiejaoude** [comment]
I think this depends on the hosting platform? We are currently moving hosting solutions, so I will block it for now
