### ISSUE TITLE
Main branch is not protected because of the GH Action needs to write

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2756]
### Description

The default branch `main` should be protected but for the Actions that need to write to `main` this is a problem

What are the solutions?

**Comment by Panquesito7** [comment]
Looks like it's not 100% possible yet, I guess? https://github.com/orgs/community/discussions/25305

**Comment by ad3rinto** [comment]
Seems like an exception needs to be made in the branch protection rules.
https://github.blog/changelog/2021-11-19-allow-bypassing-required-pull-requests/

**Comment by Panquesito7** [comment]
> Seems like an exception needs to be made in the branch protection rules. https://github.blog/changelog/2021-11-19-allow-bypassing-required-pull-requests/

Yeah, but I'm not sure the `actions` user can be added. And if it can be added, it can be dangerous to use (see https://github.com/orgs/community/discussions/25305#discussioncomment-3247405).

**Comment by mocdaniel** [comment]
Yes, no exception should be made in order to allow the `actions` user to push to protected branches, because this allows for other loopholes to appear. The 'correct' way to solve this is probably by leveraging GitHub's API and providing the action with an accordingly privileged PAT - I'll draft a PR.

**Comment by eddiejaoude** [comment]
Thanks everyone for your help on this 💪 

I think the main rule should be `Require a pull request before merging` this stops anyone by mistake (especially me 😂 ) accidentally pushing to the `main` branch and breaking `production`
