### ISSUE TITLE
Some links in header is not working. Like search, popular

### ISSUE THREAD

**Issue by bharat5604** [EddieHubCommunity/LinkFree#2772]
### Description

header links for popular and search  is not redirecting on click

**Comment by rishabhverma54321** [comment]
@bharat5604  it's working 👌

**Comment by bharat5604** [comment]
yes it's working now on my machine too, i think this is bit slow when fast refresh whole pages reloads and takes time to re-render

**Comment by khalidx3** [comment]
everything is working fine just the search button is rendering a little slow but its definitely working
