### ISSUE TITLE
New Testimonial for Eddie Jaoude

### ISSUE THREAD

**Issue by KrishChopra22** [EddieHubCommunity/LinkFree#2781]
### Name

eddiejaoude

### Title

G.O.A.T of Open Source

### Description

The **Open Source Guru**, is none other than Eddie. He is GitHub Star of the Year ⭐ He is the founder of an amazing community, @EddieHubCommunity whose motive is Collaboration 1st, Code 2nd! If you are a beginner and stepping into Open Source, just join this community and you will never be missing out.

**Comment by eddiejaoude** [comment]
Thank you Krish 👍

**Comment by KrishChopra22** [comment]
> Thank you Krish 👍

My pleasure. Huge thanks to you for your incredible love towards Open Source 💖
