### ISSUE TITLE
New Testimonial for Nwoke Emmanuella

### ISSUE THREAD

**Issue by tobySolutions** [EddieHubCommunity/LinkFree#2829]
### Name

Ellah120

### Title

Testimonial For Ellah

### Description

She's a very hardworking and resilient developer with top-notch coding skills. Ellah has so much energy when it comes to delivering scalable and awesome Frontend applications built with the most stable and awesome libraries like Reactjs.

**Comment by eddiejaoude** [comment]
Awesome 🎉
