### ISSUE TITLE
Random LinkFree profiles returning undefined not found error

### ISSUE THREAD

**Issue by iamunnip** [EddieHubCommunity/LinkFree#2833]
### Description

From the discover page, we can see random LinkFree profiles but when we click any one of the profile it load with "undefined not found" error.

### Screenshots

![eddiehub](https://user-images.githubusercontent.com/22130675/211177970-b3bf0b2f-0721-48bf-92f4-b3e08cf75278.png)

### Additional information

Clicking any one of the popular LinkFree profiles it gives the exact profiles.

**Comment by dan-mba** [comment]
In the discover users api, the random users map [return](https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/api/users/discover.js#L55) for users with display stats turned off should be
```
return {
  …user,
  username: profile.username
}
```

The display stats path gets the username form `profile._doc`

**Comment by dan-mba** [comment]
The show user stats return path need to be changed as well, because aggregate doesn't return a mongoose document, per [the docs](https://mongoosejs.com/docs/api/aggregate.html#aggregate_Aggregate).

**Comment by rwiteshbera** [comment]
Hi, @dan-mba , could you please assign me this issue?

**Comment by eddiejaoude** [comment]
Thanks @dan-mba 👍 

@rwiteshbera I have assigned it to you - please note this is a critical bug (very high priority), if you do not have time to do it today, please let us know and you can do another issue that is less urgent. Thanks for understanding

**Comment by eddiejaoude** [comment]
Sorry @rwiteshbera I had to do a quick fix for this because of the amount of messages I was getting from it. Please have a look at the other open issues we have.
