### ISSUE TITLE
[FEATURE] Separate sections for projects

### ISSUE THREAD

**Issue by razaahmad333** [EddieHubCommunity/LinkFree#2835]
### A separate section to showcase the projects.
Currently, one can add links of their projects in `My Links` section through `links` field in their json data.

I think `My Links` is a more general space, one can figure out what to put there.

But having a `Projects` section can facilitate showcasing projects that one have worked on

### The data can look like
```json
 
    "projects": [
        {
            "title": "The name of the project",
            "techsUsed": [
                "ReactJS",
                "Typescript"
            ],
            "url": "url to the project if deployed",
            "githubRepo": " url to the repo if exists ",
            "contributors": []
        }
    ]

```

**Comment by eddiejaoude** [comment]
Great idea 👍 

I was thinking, people could add the owner/name of the repo and we can get all the latest information from GitHub, for example `EddieHubCommunity/LinkFree`

**Comment by razaahmad333** [comment]
yes,

**Comment by shyam0705** [comment]
Can I work on this issue?

**Comment by shyam0705** [comment]
@eddiejaoude  using GitHub API we can get the project description, URL, and tech stack which will be the same as the about section in the GitHub repository. so far I have modified API  to include a projects  array in the profile where each project will have `
        "title",
        "description",
        "githubrepo",
        "techUsed",
        "URL",
        "contributors"
`
fields.

**Comment by shyam0705** [comment]
I am thinking about UI like:-

<img width="927" alt="image" src="https://user-images.githubusercontent.com/72148710/212015145-0834366c-632d-4c4f-901d-e04bb20cd285.png">
We can stack avatars of the top 3 contributors.

Let me know if you have any suggestions and should I go ahead with this or not.

**Comment by eddiejaoude** [comment]
> so far I have modified API to include a projects array in the profile where each project will have "title", "description", "githubrepo", "techUsed", "URL", "contributors" fields.

What do you mean? What is in the user profile?

**Comment by schmelto** [comment]
I would separate this into several sub spaces. 

The structured as follows

- projects
  - open source projects (GitHub projects)
  - other projects (here a link or just a description will be needed) 

Json draft would look like this in my opinion:

Project
[
  GitHub/url (if this is present use the GitHub data for the fields which are not specified)
  Title
  Url
  Date
  ...

]

I think we can enhance this but I'm keen to hear your opinions on how to handle GitHub projects approach.

**Comment by shyam0705** [comment]
> > so far I have modified API to include a projects array in the profile where each project will have "title", "description", "githubrepo", "techUsed", "URL", "contributors" fields.
> 
> What do you mean? What is in the user profile json file?

In the JSON file, the user will only enter the owner and repo name. Using GitHub API, I am fetching the above details about the project

**Comment by eddiejaoude** [comment]
Thanks @schmelto , I think we only need this type of info in the user's json profile for now?

```js
   "projects": {
      "github": ["EddieHubCommunity/LinkFree"]
   }
```

@shyam0705 not sure what your structure is like, but this is what I recommend

**Comment by schmelto** [comment]
> Thanks @schmelto , I think we only need this type of info in the user's json profile for now?
> 
> ```js
>    "projects": {
> ```

What about non GitHub Projects?

My idea was that we can go with something like this:

```json
   "projects": {
      "github": ["EddieHubCommunity/LinkFree"]
      "name": "name"
      "url": "url"
     [...]
   }
```

where those fields are only obligatory. If the github link is present the fields like name are filled with the github ones but you can also add a project which is not from github by not maintianing the github link and only using the name url ...

```mermaid
graph TD
    B(Projects)
    B --> C{github link present}
    C -->|yes| D[Call github api and fill empty fields]
    C -->|no| E[Use only the fields in the profile json]
```

**Comment by eddiejaoude** [comment]
I think that will make it more complicated for people to create. My suggestion I think keeps it the simplest - we can focus on GitHub for now and later add more options

**Comment by razaahmad333** [comment]
> Great idea 👍
> 
> I was thinking, people could add the owner/name of the repo and we can get all the latest information from GitHub, for example `EddieHubCommunity/LinkFree`

what if the project do not have a github repo

**Comment by eddiejaoude** [comment]
This can be looked into further once forms have been completed as we don't want to add anymore data to the json files https://github.com/EddieHubCommunity/LinkFree/pull/6998

**Comment by eddiejaoude** [comment]
Work in progress...

- User can add/delete their GitHub repo in their profile
- Repo data is fetched from GitHub's API
- GitHub data is cached (similar to GitHub profile location data)
- Display new tab `Project` on profile
- Have overall app page for projects (similar to Events)
