### ISSUE TITLE
[DOCS] How can I add my skills

### ISSUE THREAD

**Issue by razaahmad333** [EddieHubCommunity/LinkFree#2836]
### Description

While reading docs, I was not able to figure out how to add my skills ( Assume I was dumb at that point).

### What should be done?
We can improve the docs by mentioning the keyword `skills` in the `Tags` section.
And also a link on the quickstart page which says "Add skills to your profile"

**Comment by eddiejaoude** [comment]
I think skills could be added to tags, as these are searchable as well https://linkfree.eddiehub.io/docs/how-to-guides/tags

**Comment by razaahmad333** [comment]
but it would be easier if docs is updated accordingly

**Comment by eddiejaoude** [comment]
yes we can improve the docs and include this information 👍

**Comment by SaraJaoude** [comment]
For the purpose of this project, as the word `tag` is synonymous with the word `skill` and users have been applying it in this way without any problems, I will close this issue.
