### ISSUE TITLE
[FEATURE] Copy name of icon from docs

### ISSUE THREAD

**Issue by razaahmad333** [EddieHubCommunity/LinkFree#2839]
### Copy names of icon
A feature to copy names of icons to add to the profile data.

### the icon page
https://linkfree.eddiehub.io/icons ,

**Comment by eddiejaoude** [comment]
Great idea 👍

**Comment by nanthakumaran-s** [comment]
Can we add something similar to this??

https://user-images.githubusercontent.com/59391441/211192945-89f93f59-bf48-435a-b9c2-a78007239639.mov

**Comment by eddiejaoude** [comment]
Yes just like that 👍

**Comment by KimberlyPangilinan** [comment]
I have the same idea. I had a hard time searching for the icon that i want or i dont have any idea what to search. Maybe it's a good idea that there are list of icons listed and when the user clicked the specific icon the code will be copypasted in the user's clipboard

We all know that users will just use things, only if it is accessible to them
 ![Screenshot_20230112_021810_com.android.chrome.jpg](https://user-images.githubusercontent.com/92774426/211886774-6ddbd56d-47a2-449c-903e-8940d4841e8d.jpg)
