### ISSUE TITLE
[DOCS] hashcode in color field of milestone data

### ISSUE THREAD

**Issue by razaahmad333** [EddieHubCommunity/LinkFree#2840]
### Description

Can I put hashcode in the color field of milestone data

What I want:

```json
{
    "title": "Started Freelancing",
    "date": "May 2010",
    "icon": "FaDollarSign",
    "color": "#007500",
    "description": "Started my own business",
    "url": "https://www.eddiejaoude.io/"
}
```

**Comment by eddiejaoude** [comment]
Yes you can add the colour to the milestone 👍 we should probably update the docs to say that hex colours are accepted https://linkfree.eddiehub.io/docs/how-to-guides/milestones

**Comment by nanthakumaran-s** [comment]
@eddiejaoude Can I add them to the docs? If no one is working on this.

**Comment by eddiejaoude** [comment]
Sure, I assigned it to you @nanthakumaran-s
