### ISSUE TITLE
[DOCS] Responsiveness breaks on Internal pages of doc page.

### ISSUE THREAD

**Issue by arpitghura** [EddieHubCommunity/LinkFree#2857]
### Description

The error is in the internal pages of the documentation. The Responsiveness on the pages breaks on smaller devices probably `below 768px`

The error can be caused by 
1. no wrapping of anchor text link
2. un-responsive images and code blocks used.

### Screenshots

Due to having un-responsive images and code blocks:
![image](https://user-images.githubusercontent.com/41796013/211191806-fc4f6dc2-f977-4155-928d-0999fe504ef2.png)

Due to not wrapped anchor tag URL:
![image](https://user-images.githubusercontent.com/41796013/211191889-459cd3c8-941e-4b60-ab5e-c618ffd2d852.png)

### Additional information

This issue is encountered on all pages by either of the two reasons mentioned.

**Comment by arpitghura** [comment]
I can work on this issue. I know how to resolve this issue created from either of the two ways mentioned. 

There are some classes that I need to add in anchor tags and in the images and code-blocks to resolve the issue.

**Comment by eddiejaoude** [comment]
Great! Sure I assigned it to you

**Comment by arpitghura** [comment]
I have seen some pages like (https://linkfree.eddiehub.io/docs/how-to-guides/editing) have responsive images but some pages like (https://linkfree.eddiehub.io/docs/quickstart). 
I want to know why this is happening, can you explain?
@eddiejaoude

**Comment by eddiejaoude** [comment]
Both work the same for me. What difference do you see?

**Comment by arpitghura** [comment]
Editing Guide Page:
![image](https://user-images.githubusercontent.com/41796013/211975326-5ede18d3-3bca-4509-8bb7-a13bc5bb78f4.png)

Quickstart Guide Page:
![image](https://user-images.githubusercontent.com/41796013/211975466-6636756d-43c0-4964-938f-2c958165563d.png)


See the difference between two images, in first the images are responsive but in second they are not. 

I am using the docs on 
- OS: Windows 10
- Browser: Microsoft Edge 

I have found the similar behavior on Google Chrome Browser as well.

> Both work the same for me. What difference do you see?
