### ISSUE TITLE
[FEATURE] Button to reload random profile list

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2864]
### Description

I love seeing the random profiles on the Discover page. I keep refreshing to discover more people. It would be great if there was a reload button to get another set of random profiles

**Comment by dhruvdabhi101** [comment]
I would like to work on this issue.

**Comment by ManishBisht777** [comment]
i want to work on this

**Comment by eddiejaoude** [comment]
Sure, assigned to you @ManishBisht777

**Comment by ManishBisht777** [comment]
closing this issue as completed

**Comment by SaraJaoude** [comment]
this has been completed
