### ISSUE TITLE
eddiejaoude profile shows fewer testimonials than those in the data

### ISSUE THREAD

**Issue by swiftugandan** [EddieHubCommunity/LinkFree#2880]
### Description

I was comparing the number of testimonials in the data for @eddiejaoude and realised there is a discrepancy between what the profile shows (5 testimonials) and what is contained in the data (7 testimonials). Please have a look.

**Comment by dan-mba** [comment]
This is working correctly.

In order for a testimonial to be displayed, the name of the file in the testimonial directory must also be in the profile testimonials field. Only 5 of the 7 files meet this requirement.

Eddie's profile has 2 names in the testimonials section that don't have a matching file in the testimonials directory.

**Comment by eddiejaoude** [comment]
Thank you both for collaborating 👍 

Yep I am have not reviewed the other testimonials yet, so I have not included them on my profile. Currently these are the ones included https://github.com/EddieHubCommunity/LinkFree/blob/main/data/eddiejaoude.json#L20

Here are the docs to the testimonials section if you would like to learn more (or let us know if something doesn't make sense or is missing)
