### ISSUE TITLE
[Terminal Error] Getting these errors for every profile that does not contain events

### ISSUE THREAD

**Issue by Aadarsh805** [EddieHubCommunity/LinkFree#2891]
### Description

 is this the usual behavior or in the new update (just pulled the new changes and noticed these)

### Screenshots

![Screenshot from 2023-01-09 00-22-35](https://user-images.githubusercontent.com/95094057/211213670-5f122ba2-322a-4d6c-b25c-adf3115b2d3e.png)

**Comment by eddiejaoude** [comment]
I think the log message is incorrect, but what happens is correct. 

I should probably say `Skipped loading events for profile ...`

**Comment by eddiejaoude** [comment]
Thanks @Aadarsh805 , these are correct 👍 I have tweaked the log messages a bit, they might need tweaking more - but nothing to be worried about. Thank you for raising
