### ISSUE TITLE
Found two user profiles whose GitHub profiles does not exist

### ISSUE THREAD

**Issue by Aadarsh805** [EddieHubCommunity/LinkFree#2893]
### Description

1) `Skyhero-admin.json`
2) `aaquibdev.json`

this error occurred due to this `upstream image response failed for https://github.com/Skyhero-admin.png 404`

### Screenshots

this caused the random user section to generate only 4 user profiles, the 5th threw error
![Screenshot from 2023-01-09 00-40-14](https://user-images.githubusercontent.com/95094057/211214416-29c8c1e6-db39-4acf-926d-584dc6fc148c.png)

### Additional information

There must be more accounts like this, it might be negligible for a large number of users (this happened on my local dev server, with smaller user list)

**Comment by eddiejaoude** [comment]
Thank you raising 👍

**Comment by MD-ARBAB-SAHID** [comment]
> ### Description
> 1. `Skyhero-admin.json`
> 2. `aaquibdev.json`
> 
> this error occurred due to this `upstream image response failed for https://github.com/Skyhero-admin.png 404`
> 
> ### Screenshots
> this caused the random user section to generate only 4 user profiles, the 5th threw error ![Screenshot from 2023-01-09 00-40-14](https://user-images.githubusercontent.com/95094057/211214416-29c8c1e6-db39-4acf-926d-584dc6fc148c.png)
> 
> ### Additional information
> There must be more accounts like this, it might be negligible for a large number of users (this happened on my local dev server, with smaller user list)

@Aadarsh805 I also tried with dummy database with some users having GitHub profile and some not, but in that case it was using the fallbackSvg avatar instead of breaking from that point like as you mentioned because of unavailability 4th user 5th one was not displayed, I dont know if I'am getting it right or not 😅.

**Comment by Aadarsh805** [comment]
> > ### Description
> > 
> > 1. `Skyhero-admin.json`
> > 2. `aaquibdev.json`
> > 
> > this error occurred due to this `upstream image response failed for https://github.com/Skyhero-admin.png 404`
> > ### Screenshots
> > this caused the random user section to generate only 4 user profiles, the 5th threw error ![Screenshot from 2023-01-09 00-40-14](https://user-images.githubusercontent.com/95094057/211214416-29c8c1e6-db39-4acf-926d-584dc6fc148c.png)
> > ### Additional information
> > There must be more accounts like this, it might be negligible for a large number of users (this happened on my local dev server, with smaller user list)
> 
> @Aadarsh805 I also tried with dummy database with some users having GitHub profile and some not, but in that case it was using the fallbackSvg avatar instead of breaking from that point like as you mentioned because of unavailability 4th user 5th one was not displayed, I dont know if I'am getting it right or not sweat_smile.

The one I'm talking about here don't have a GitHub account, not just the profile picture
If that's what you mean my having fallbackSvg in place of GitHub profile picture

**Comment by MD-ARBAB-SAHID** [comment]
@Aadarsh805  Even if the account is not there in github but if there is  a json file in data dir in that case fallbackSvg will be used. It only displays on the console unable to find .png 404 but it does not decrease the number of profiles. Tried with some dummy profiles without Github account.

**Comment by Aadarsh805** [comment]
> @Aadarsh805 Even if the account is not there in github but if there is a json file in data dir in that case fallbackSvg will be used. It only displays on the console unable to find .png 404 but it does not decrease the number of profiles. Tried with some dummy profiles without Github account.

Huh then that's weird, this is the error on my terminal
This one's causing that, not the 404 one
![image](https://user-images.githubusercontent.com/95094057/212158114-3d0ccd13-8768-4d5c-9ca5-c374c27b6e97.png)

**Comment by MD-ARBAB-SAHID** [comment]
> > @Aadarsh805 Even if the account is not there in github but if there is a json file in data dir in that case fallbackSvg will be used. It only displays on the console unable to find .png 404 but it does not decrease the number of profiles. Tried with some dummy profiles without Github account.
> 
> Huh then that's weird, this is the error on my terminal This one's causing that, not the 404 one ![image](https://user-images.githubusercontent.com/95094057/212158114-3d0ccd13-8768-4d5c-9ca5-c374c27b6e97.png)

Then ig this error mainly occurs if profile is stored in mongodb database and the corresponding profile.json is not present in data directory irrespective of whether GitHub account exist or not. I created dummy user1,user2,user3,user4 which don't have a GitHub account but their data is stored in mongodb database but corresponding json files are not present in data dir.
<img width="1034" alt="Screenshot 2023-01-15 at 12 01 14 AM" src="https://user-images.githubusercontent.com/63171580/212490592-7087646a-213d-4623-9541-c12268f1efb3.png"> 
For user with username "HAT52"  who has a Github account along with the "HAT52.json" stored in data dir. I deleted "HAT52.json" stored in data dir in that case it shows:
<img width="1041" alt="Screenshot 2023-01-15 at 12 08 33 AM" src="https://user-images.githubusercontent.com/63171580/212490738-04aae92f-93d1-4046-a522-ac42009a6740.png">

@eddiejaoude So ig error mainly occurs when data is present in the database and corresponding profile_data.json file is not present in data dir which leads to data inconsistency.

**Comment by eddiejaoude** [comment]
Great collaboration 👍 

Yes if the user file is deleted ,they remain in the database - this is something we need to fix 

I suggest if the file is not found, the user is removed from the database

**Comment by eddiejaoude** [comment]
These profiles do exist? 🤔 

- `Skyhero-admin.json` https://github.com/EddieHubCommunity/LinkFree/blob/main/data/Skyhero-admin.json
- `aaquibdev.json` https://github.com/EddieHubCommunity/LinkFree/blob/main/data/aaquibdev.json

**Comment by psavan1655** [comment]
We can use a cron for that. Delete users from DB whose json file is not available. I would like to work on this cron job issue.
If yes, let me know.  i can create a issue in relation to this issue.

**Comment by Tusharjagi** [comment]
we can do one more like if user file is deleted then changes the UI { this user is not available }

![Screenshot from 2023-03-04 12-50-56](https://user-images.githubusercontent.com/12596457/222882004-277ea88b-2944-4eff-aa40-1ba1dac37430.png)

something like that we can improve UI It's just an example

**Comment by SaraJaoude** [comment]
I will look into this.

**Comment by SaraJaoude** [comment]
@Skyhero-alt I believe that the account `Skyhero-admin` is your previous account.  Can you please comment on this Issue so that we can address it and close it? You can either edit your LinkFree profile or close this if you decide you no longer require it.

**Comment by SaraJaoude** [comment]
With `aaquibdev.json` the GitHub username does not exist and none of the links work

**Comment by eddiejaoude** [comment]
@Skyhero-alt yes please 👍

**Comment by kumarsonsoff3** [comment]
> With `aaquibdev.json` the GitHub username does not exist and none of the links work

From the commit history, I found that it's the previous account of @imaaquibali. 

@imaaquibali, Since you have created a new LinkFree profile on your [new username](https://github.com/EddieHubCommunity/LinkFree/blob/main/data/imaaquibali.json), could you please deleting your old json file: https://github.com/EddieHubCommunity/LinkFree/blob/main/data/aaquibdev.json or we should address it?

**Comment by SaraJaoude** [comment]
> Yes it is my old account
> I think i will update the link
> Should I make a Pull request for it ?

This has now been dealt with in: https://github.com/EddieHubCommunity/LinkFree/pull/6716

**Comment by SaraJaoude** [comment]
> > With `aaquibdev.json` the GitHub username does not exist and none of the links work
> 
> From the commit history, I found that it's the previous account of @imaaquibali.
> 
> @imaaquibali, Since you have created a new LinkFree profile on your [new username](https://github.com/EddieHubCommunity/LinkFree/blob/main/data/imaaquibali.json), could you please delete your old json file: https://github.com/EddieHubCommunity/LinkFree/blob/main/data/aaquibdev.json or we should address it?

I will delete the file `aaquibdev.json` as:

- it has been two weeks and there has been no response from @imaaquibali 
- the GitHub username does not exist
- the links mentioned in the file do not work

**Comment by aliaaquib** [comment]
@SaraJaoude Actualy I don't have access to my @imaaquibali account 😞. I lost my backup codes and forget to take backup of 2FA also. 

If you know any other options to access my account please let me know. 

I thought I already deleted my old profile btw thanks for deleting it 😊
