### ISSUE TITLE
New Testimonial for Marino Wijay

### ISSUE THREAD

**Issue by krupalitrivedi** [EddieHubCommunity/LinkFree#2894]
### Name

distributethe6ix

### Title

The DevRel we need

### Description

Marino has been super helpful to everyone on the tech twitter and opensource ecosystem. He has been extremely helpful to the tech community out there, giving honest advice, being there for people online and in present and just providing value everyway. The dedication to help and be there is amazing.

**Comment by eddiejaoude** [comment]
Love this 🎉
