### ISSUE TITLE
New Testimonial for Avie Fukai

### ISSUE THREAD

**Issue by Spiritdivine** [EddieHubCommunity/LinkFree#2897]
### Name

avie-dev

### Title

Motivator 

### Description

Avie has been of great motivation in the area of networking especially around the tech Twitter community. Her Twitter spaces provides a platform for people to speak regardless of what race one is.

**Comment by eddiejaoude** [comment]
Awesome 🎉

**Comment by avie-dev** [comment]
Thank you @Spiritdivine ❤️‍🔥
