### ISSUE TITLE
CSS issue with anchor tags in "Popular User Guides" section

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [EddieHubCommunity/LinkFree#2900]
### Description

**Below are some issues :-**
1. The anchor tags inside "Popular User Guides" section have `display: block`, due to which one can click even on blank space. In the below mentioned screenshot, the whole area inside red box is clickable.
<img width="401" alt="image" src="https://user-images.githubusercontent.com/54144759/211218566-92d42da9-185c-4c89-b910-cd01cc30653b.png">

2. The anchor tags are hard to recognise. Only by seeing the cursor change to `pointer` when I hover over the anchor tag, I was able to realise that it is clickable.

**Proposals :-**
1. Convert `display: block` to `display: inline` for `<h3>` tag or have `<a>` tag inside `<h3>` tag (prefer second).
2. Whenever hovered - either have an underline for **anchor tag** or change color. This is important to convey to users through UI that something is clickable here.
<img width="736" alt="image" src="https://user-images.githubusercontent.com/54144759/211218939-37b6f368-441d-441b-a855-59be2553435c.png">

**Comment by GaganpreetKaurKalsi** [comment]
I would like to work on this

**Comment by eddiejaoude** [comment]
Good spot @GaganpreetKaurKalsi 👍 Sure I have assigned it to you

**Comment by GaganpreetKaurKalsi** [comment]
Thanks @eddiejaoude 🚀

**Comment by ChinmayMhatre** [comment]
I think PR linked with the issue has be merged so the issue can be closed #2993

**Comment by eddiejaoude** [comment]
Thank you @ChinmayMhatre you are correct 👍
