### ISSUE TITLE
[FEATURE] Events page - add a cost identifier

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#2901]
### Description

This feature is to add a legend item for cost to events so that folks can easily identify free vs paid events.

To keep things simple proposing only
Free Event (possible icon tbd or simply put Free as text)
Paid Event (possible icon FaMoneyBill)

Consideration: If the event has a free and a paid portion, do we need a way to show that?

We could get more granular with this in the future if people find it more useful to know precise cost without clicking through to the event

**Comment by thebarshablog** [comment]
@amandamartin-dev so, is it an icon change you're recommending? 
Let's say, someone's going to an event which is free, from the linkfree list of icons, they can just incorporate the free one or paid one which writing down their events.

**Comment by amandamartin-dev** [comment]
Hey @thebarshablog I was thinking not a change but an addition.

In the legend at the top there would be another filter for cost/free and next to the actual event line would be an icon indicator as well. wdyt?  Perhaps there is another way to indicate this to folks
![events](https://user-images.githubusercontent.com/97615019/211314737-ace97180-1864-4454-964e-468d8558ba52.jpg)

**Comment by eddiejaoude** [comment]
Great idea 👍 

> Consideration: If the event has a free and a paid portion, do we need a way to show that?

yes this makes it a bit more complicated. Maybe could have `startingFrom` in the json and this case would be `0` for free events

**Comment by shyam0705** [comment]
I will like to work on this issue. Can you assign it to me?

**Comment by amandamartin-dev** [comment]
@shyam0705 sure, I can assign you.  Please see Eddies note to add to the json startingFrom and when 0 the event is free. If you have any other questions feel free to ask! Thanks for contributing
