### ISSUE TITLE
Input required and not supplied: firebase-key

### ISSUE THREAD

**Issue by harshraj8843** [EddieHubCommunity/LinkFree#291]
Have a look at this issue

![Screenshot from 2021-09-22 12-19-55](https://user-images.githubusercontent.com/54644599/134296138-237c694c-3a52-42a1-8938-95b873237499.png)

![Screenshot from 2021-09-22 12-22-09](https://user-images.githubusercontent.com/54644599/134296364-973e712c-1678-4590-a5c2-f6acdda234a8.png)

**Comment by schmelto** [comment]
This is a duplicate with #204
closing this one :) hope this is fine for you
