### ISSUE TITLE
[FEATURE] Adding dynamic underline effect in the navbar after clicking

### ISSUE THREAD

**Issue by Vishvsalvi** [EddieHubCommunity/LinkFree#2952]
### Description

This improve the user experience with navbar and its also a great animation. I can't make it because I have no clue how to pull it off in Tailwind CSS.  Watch the video I've put for the reference

### Screenshots

https://user-images.githubusercontent.com/82429084/211353753-5ca6510c-d1da-4085-b438-b678fbd6e4d7.mp4

**Comment by SaraJaoude** [comment]
Thank you for the suggestion.  As the navigation is already highlighted with a box when you are on that page, we feel that to underline it as well would be too much - so I will be closing this issue for now.
