### ISSUE TITLE
Glassmorphism design

### ISSUE THREAD

**Issue by veerbal1** [EddieHubCommunity/LinkFree#296]
Should we upgrade current design to Glassmorphism design, if will look beautiful...

**Comment by voidz7** [comment]
Those who are like me wondering what is Glassmorphism , it is a new trend in UX/UI scene which are just transparency (frosted-glass) or blur  , vivid or pastel colors, and a light border or round corners .

### for eg
![image](https://user-images.githubusercontent.com/62803658/134366337-94337acd-2f70-461c-b029-db701ae1f336.png)

For more examples [here](https://dribbble.com/tags/glassmorphism)

**Comment by voidz7** [comment]
> Should we upgrade current design to Glassmorphism design, if will look beautiful...

@veerbal1 From next time while making a issue about something try explaining it 👍🏼  btw great idea !

**Comment by veerbal1** [comment]
Thanks Bro

**Comment by amittri1025** [comment]
@veerbal1 Anyone working on this issue or should I start

**Comment by veerbal1** [comment]
@amittri1025 I am working on it.

**Comment by Panquesito7** [comment]
I think this is already being implemented in #313.
