### ISSUE TITLE
[DOCS] The point can be improved by adding other sentence, where users will not create pull request in their forked repo.

### ISSUE THREAD

**Issue by Sativarsainath-26** [EddieHubCommunity/LinkFree#2991]
### Description

- [When Following this docs](https://linkfree.eddiehub.io/docs/how-to-guides/editing)  13th point, It just says to create a Pull request but in that if the base branch is not set to `EddieHubCommunity/LinkFree `  then it will create a PR in your Forked branch.

### Screenshots

![doc-update](https://user-images.githubusercontent.com/85878757/211385620-bc9b9459-9003-4ff7-9030-94c82ccfe7cb.PNG)

**Comment by Sativarsainath-26** [comment]
I wanted to work on this doc update by adding a sentence that : 
Before raising a pull request, Please make sure that your base branch is set to `EddieHubCommunity/LinkFree `.  
If you any better sentence let me know :grinning:.

**Comment by shubhsharma19** [comment]
I already raised a PR about this so yeah once its merged it will be fixed.

**Comment by Sativarsainath-26** [comment]
@shubhsharma19 Could you please paste that pr link here?  It addressed this in order for maintainers to review it, provide feedback, and perhaps allow it to be integrated. Once it is merged this issue can be closed.

**Comment by shubhsharma19** [comment]
Sure! 

https://github.com/EddieHubCommunity/LinkFree/pull/2915

**Comment by eddiejaoude** [comment]
@shubhsharma19 please update your pull request description with `closes #2991` so GitHub can link the PR to the issue and also auto closes the issue when completed
