### ISSUE TITLE
[FEATURE] Tech Stack missing from README - request for inclusion

### ISSUE THREAD

**Issue by Saadat-B** [EddieHubCommunity/LinkFree#3000]
### Description

Adding the Tech Stack in the README can help other developers understand the technical requirements or dependencies of the project. If someone is interested in contributing to the project, they will know what tools or languages they need to be familiar with.

Sharing an example in the screenshots.

### Screenshots

![tech stack](https://user-images.githubusercontent.com/70024383/211473604-91b7ede9-b601-4382-9d1f-5f40c8dd3e37.png)

### Additional information

In the example given I was not able to verically align the text with the markdown badge otherwise it would have looked a bit clean.

**Comment by Saadat-B** [comment]
I am interested in taking on this issue, may I be assigned to it?

**Comment by eddiejaoude** [comment]
Great idea 👍 I have assigned it to you. I think add it above the `quickstart` section though

**Comment by Saadat-B** [comment]
Thank you for assigning it to me Eddie!
Sure will add it above the `quickstart`  section 👍
