### ISSUE TITLE
Facing Issue "DB" not connected

### ISSUE THREAD

**Issue by JunDevHarsh** [EddieHubCommunity/LinkFree#3001]
### What would you like to share?

I am facing this issue while installing all the reqiured dependencies. Steps I have followed to start the project locally:
1. `npm ci`
2. `npm run dev`

Does that mean I have to create mongodb cluster or something like that to connect with database because I have not connected with database.

### Additional information

Screenshots:

![Untitled](https://user-images.githubusercontent.com/94737463/211480107-2b1453f3-4c76-4dae-8e1b-8e3a38fde751.png)

**Comment by eddiejaoude** [comment]
Do you have mongo running? Have you looked at the docs about running the project locally https://linkfree.eddiehub.io/docs/environments/local-development

**Comment by eddiejaoude** [comment]
Discussion moved to Discord, so I will close this
