### ISSUE TITLE
[DOCS] fork image not visible in dark mode

### ISSUE THREAD

**Issue by shreyaansjain06** [EddieHubCommunity/LinkFree#302]
### Description

After the click on the in the  line 1 in screenshot it looks empty which is not looking good so we should make some changes to make it look clear

### Screenshots

<img width="1181" alt="Screenshot 2021-09-23 at 4 04 50 PM" src="https://user-images.githubusercontent.com/86606251/134492955-203fefcf-5c26-470e-9a49-389fc5cc8176.png">

**Comment by schmelto** [comment]
https://github.com/EddieHubCommunity/LinkFree/blob/main/Contributing.md

**Comment by ShlokMohanty** [comment]
@schmelto we mean to say that the fork repository symbol is not visible right ?
if I have understood the issue correctly?

**Comment by schmelto** [comment]
> @schmelto we mean to say that the fork repository symbol is not visible right ?
> if I have understood the issue correctly?

Yes

**Comment by ShlokMohanty** [comment]
@shreyaansjain06 is there any space between the sentence as per me as discussed in this thread with @schmelto  there is no such space but yes the symbol of the fork repository is not visible we have to make that visible so should we close this pr or changes have to be done?

**Comment by shreyaansjain06** [comment]
We should make changes

**Comment by ShlokMohanty** [comment]
like should we change the colour of the fork symbol maybe @shreyaansjain06 ?
