### ISSUE TITLE
[DOCS] Typo in docs under Bio

### ISSUE THREAD

**Issue by Rishav-12** [EddieHubCommunity/LinkFree#3042]
### Description

Under `Customising your profile` > `Bio` > "... It allow for the use..." > should be `allows`

### Screenshots

![typo in Bio section](https://user-images.githubusercontent.com/76068105/211503151-fe62d01c-3383-4d1c-ac2a-1a791210d3c7.png)

**Comment by devvsakib** [comment]
assign me, i want to take this

**Comment by krshkun** [comment]
Hey @Rishav-12, these should be two separate issues what do you think? I think we can take this issue for the typo in the bio thing, then you (if you want) can make a issue for the milestones one?

**Comment by Rishav-12** [comment]
Ya, it can be two issues. More green squares! 🟩

**Comment by HarshDeep61034** [comment]
can I get assigned to this one?
