### ISSUE TITLE
[DOCS] Typo in README.md

### ISSUE THREAD

**Issue by niteshseram** [EddieHubCommunity/LinkFree#306]
### Description

There is a typo in the README.md file.
`LinkFree` should be `Linktree` if I am not wrong.
As you can see in the below screenshot-

### Screenshots

![typo](https://user-images.githubusercontent.com/51370246/134624563-ff079133-e259-4864-bf4f-fff8990b528e.PNG)

**Comment by voidz7** [comment]
Fixed in #309 can be closed 👍🏼 .
