### ISSUE TITLE
[DOCS] Typo in docs under Milestones

### ISSUE THREAD

**Issue by Rishav-12** [EddieHubCommunity/LinkFree#3063]
### Description

Under `Customising your profile` > `Milestones` > "... This could when you got..." > should be "... This could `be` when you..."

### Screenshots

![typo in Milestones section](https://user-images.githubusercontent.com/76068105/211503339-d5d21093-fd9e-4721-bbc4-cf375b4738f0.png)

**Comment by gauravmnjwr** [comment]
Hey Rishav, I'd like to work on this issue.

**Comment by Rishav-12** [comment]
> Hey Rishav, I'd like to work on this issue.

Sure, but I think you should wait for the maintainers to assign you the issue first

**Comment by schmelto** [comment]
@gauravmnjwr I assigned you

**Comment by gauravmnjwr** [comment]
Thank you. I've created the pull request please check.
