### ISSUE TITLE
[BUG] When filtering events the profile picture is not correct

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/LinkFree#3069]
### Description

When filtering events the profile picture is not correct

### Screenshots

Without filtering (all events)
![image](https://user-images.githubusercontent.com/30869493/211524051-b5724c67-e144-478a-a845-69855dc0fe5a.png)
-> profile picture of eddie

when filtering for cfp open

![image](https://user-images.githubusercontent.com/30869493/211524110-b4d0b9cd-cb51-46ee-83dc-ca547607ccb9.png)
wrong user image
but it is linking to the right linkfree profile (eddies)

**Comment by eddiejaoude** [comment]
Good spot, thank you 👍
