### ISSUE TITLE
[FEATURE] If profile only has links then do not show dropdown or tab

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#3080]
### Description

Currently, a dropdown is rendered on mobile regardless of if it is needed or not.  This issue is to handle not rendering a dropdown for profiles that contain only links and only render a dropdown on 2 or more items.

### Screenshots

Current mobile view with links only, dropdown has been clicked in this image. Dropdown is not needed here
![Screenshot Amanda profile on android with dropdown clicked showing it has one item only](https://user-images.githubusercontent.com/97615019/211561244-bc7377d0-a4a4-4255-8b86-9db5bb5b8e93.png)

**Comment by Aadarsh805** [comment]
@amandamartin-dev how does this look? do you have any other suggestions on how it should be
![image](https://user-images.githubusercontent.com/95094057/211604030-1bc2e294-25a4-4f65-8019-36afa1df355a.png)

**Comment by amandamartin-dev** [comment]
Hey @Aadarsh805 Thank you for the screenshot I think that will work nicely.  For now, I know you have already taken on another issue that you are assigned to so I will leave this one open for someone else to try first.  If no one picks it up, feel free to ask once you have completed the other issue you are working.  Appreciate your contributions!

**Comment by Aadarsh805** [comment]
> Hey @Aadarsh805 Thank you for the screenshot I think that will work nicely. For now, I know you have already taken on another issue that you are assigned to so I will leave this one open for someone else to try first. If no one picks it up, feel free to ask once you have completed the other issue you are working. Appreciate your contributions!

I'm already done with that issue though, but yeah let's wait if someone else wanna grab this one, it's a good issue for beginners

**Comment by amirzgh** [comment]
i would like to work on this issue if its possible

**Comment by amandamartin-dev** [comment]
@Aadarsh805 thank you so much for sharing the good first issues and so sorry I didn't realize you were already dne with events. So fast!!

@amirzgh I will assign you now, thanks for contributing

**Comment by Aadarsh805** [comment]
@amirzgh feel free to ask for help if you get stuck somewhere 😇

**Comment by eddiejaoude** [comment]
I think removing the dropdown/tab is best for mobile if only links are used

**Comment by amandamartin-dev** [comment]
Yes, that makes sense esp since tabs are used elsewhere too

**Comment by ShuvamChatterjee28** [comment]
Hello @amirzgh, are you working on this? If you are not working on this, then I can work.

**Comment by arun-kushwaha04** [comment]
@SaraJaoude @amandamartin-dev i would like to work this issue, if its still open.

**Comment by SaraJaoude** [comment]
@arun-kushwaha04 I have assigned this to you

**Comment by lingaiahdanda** [comment]
@SaraJaoude  , I will work on this, if this issue is still open.

**Comment by arun-kushwaha04** [comment]
@SaraJaoude sorry for delayed response, got busy on some other task. I have created PR regarding this issue.

**Comment by KaveriRai** [comment]
Could I be assigned to this!

**Comment by SaraJaoude** [comment]
@KaveriRai I have assigned this to you

**Comment by KaveriRai** [comment]
> @KaveriRai I have assigned this to you

Thank you
