### ISSUE TITLE
[DOCS] Wrong links in the FAQ

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/LinkFree#3111]
### Description

There are various broken links on the FAQ page (such as the single-user mode or Hacktoberfest pages) which should be fixed immediately.

_Steps to contribute_

1. Fork the repository [here](https://github.com/EddieHubCommunity/LinkFree/fork).
2. Create a new branch named `fix_faq_links`.
3. Open the `faqs.mdx` file, which is located at `pages/docs/`.
4. In line 9, change the single-user mode link to `advanced/single-user-mode`. We do not want to include `docs` as otherwise, it would lead to `docs/docs/...` which is invalid.
5. In line 15, change the Hacktoberfest link to `contributing/hacktoberfest`.
6. The Discord invitation link seems to be broken as well. Change it to `http://discord.eddiehub.org` (located in line 21).
7. Commit and push your changes.
8. Create a [pull request](https://github.com/EddieHubCommunity/LinkFree/compare).
9. You're done now! 🎉 You just have to wait until the maintainers check your PR.

If you need any help, let us know about it and we'll gladly help you. 🙂

### Additional information

This is a good first issue. Please leave it open to first-time contributors and beginners.

**Comment by yashsharma8433** [comment]
i want to solve this issue.

**Comment by eddiejaoude** [comment]
Good spot @Panquesito7 👍

**Comment by yashsharma8433** [comment]
@eddiejaoude not yet closed but maybe he is not doing

**Comment by Uthycloud** [comment]
are they still working on this or i can go ahead to work on it?
