### ISSUE TITLE
Emoji for Contribution in README.md is not working

### ISSUE THREAD

**Issue by mohammadshaad** [EddieHubCommunity/LinkFree#3120]
### Description

The emoji of the Contribution in the README.md is not working while it works for other headlines.

### Screenshots

![image](https://user-images.githubusercontent.com/89409389/211609051-36897376-4c52-4b8d-93d6-2d25a7d07124.png)

**Comment by Panquesito7** [comment]
Strange. For me, it shows up well. Might be the emoji system based on the operating system and settings, I guess.

![image](https://user-images.githubusercontent.com/51391473/211610521-0de9dd5b-bf16-41b0-bc95-72390cc06297.png)

**Comment by ChinmayMhatre** [comment]
Works for me as well. Maybe should be checked on some more systems.

![image](https://user-images.githubusercontent.com/51131670/211613198-2c7a9a6e-6720-4871-a6e4-4b22c60bd42f.png)

**Comment by yashsharma8433** [comment]
can i do this, can u assign to me

**Comment by ChinmayMhatre** [comment]
> can i do this, can u assign to me

Is the emoji broken in your system?

**Comment by samyabrata-maji** [comment]
@yashsharma8433 Maybe its not downloaded in your system.

**Comment by Ertan222** [comment]
It's working for me as well. Do you still have problem ? @mohammadshaad

**Comment by samyabrata-maji** [comment]
@Ertan222 
@mohammadshaad 
Can you see this --> 🧰

**Comment by eddiejaoude** [comment]
Looks ok for me 👍 I will close as I think it works for most people. Please check your internet connection and network tab in your browser

<img width="908" alt="Screenshot 2023-01-11 at 19 03 44" src="https://user-images.githubusercontent.com/624760/211895261-3a7f5219-fa35-4e89-8c56-3d66e16f8865.png">

**Comment by Ertan222** [comment]
> @Ertan222 @mohammadshaad Can you see this --> toolbox

Yeah, I can see it.
