### ISSUE TITLE
[Make the icons clickable] 

### ISSUE THREAD

**Issue by HarshDeep61034** [EddieHubCommunity/LinkFree#3151]
### Description

while visiting the LinkFree website I immediately clicked on icons but found out the Icons are not clickable but the text below is,
so I request that we could make those icons clickable because it comes by Natural Human-instinct to click them.

### Screenshots

![Screenshot from 2023-01-11 16-33-04](https://user-images.githubusercontent.com/121210012/211793019-dc54d6c7-4785-4b79-a500-4b9d36bb88f8.png)

**Comment by Aadarsh805** [comment]
How about making the whole card clickable
We can also have a hover box shadow on the whole card

**Comment by HarshDeep61034** [comment]
that would be much better!

**Comment by eddiejaoude** [comment]
This [PR](https://github.com/EddieHubCommunity/LinkFree/pull/2993) just got merged for the headings of that section, but the icon would be good - not sure if the whole card would work, someone would have to try

**Comment by HarshDeep61034** [comment]
Alright Thanks @eddiejaoude

**Comment by HarshDeep61034** [comment]
can someone guide me on this issue? , I can't understand how to approach this one. @Aadarsh805  @ChinmayMhatre

**Comment by Aadarsh805** [comment]
> can someone guide me on this issue? , I can't understand how to approach this one. @Aadarsh805 @ChinmayMhatre

yes sure, you see here in the code
![image](https://user-images.githubusercontent.com/95094057/212538839-efc0a504-ab0b-4ca5-8fe3-3128e4e39f61.png)

the `h3`(the title of the cards: quickstart, links and all other) has a `Link` inside it, making it a link that will take us to a `href` defined
now we want the same thing for the icon above it, as we made `h3` a link right there, we can do the same for the icon above
this is in the path `pages/index.js` line around 410

I hope you got it, I you need further help, feel free to ask

**Comment by HarshDeep61034** [comment]
Thanks @Aadarsh805 😃

**Comment by EmmaDawsonDev** [comment]
> Keep it simple for now, let's keep moving forward often with little steps not slowly with big leaps - do the icon first and the card can come in another issue/pull request as it is probably more work

Sorry Eddie but I’m gonna veto this change to only do the icon first. It’s not good for accessibility to have two links side by side that go to the same place, it creates a lot of extra tab stops and noise.

**Comment by eddiejaoude** [comment]
Thanks Emma for the great feedback 👍 

Could you clarify, are you suggesting not to make any changes at all or only to do part of it?

**Comment by EmmaDawsonDev** [comment]
> Thanks Emma for the great feedback 👍
> 
> Could you clarify, are you suggesting not to make any changes at all or only to do part of it?

Either keep it as the heading of the card that is the only link, or just go ahead and make the entire card a link

**Comment by HarshDeep61034** [comment]
The entire card would be better what do you think @eddiejaoude @Aadarsh805

**Comment by HarshDeep61034** [comment]
Thanks for the Amazing feedback @EmmaDawsonDev

**Comment by Aadarsh805** [comment]
#### this is how it looks like when the whole card is the link

[screen-capture (12).webm](https://user-images.githubusercontent.com/95094057/212560989-3222c780-df80-492f-ad5c-b122e8bc5cb7.webm)

**Comment by HarshDeep61034** [comment]
This is more of a Subjective choice, Personally, I feel This one Looks better.

**Comment by eddiejaoude** [comment]
Can you share a screenshot please, `webp` does work on safari

**Comment by Aadarsh805** [comment]
> Can you share a screenshot please, `webp` does work on safari

Here's a gif of the same video

![screen-capture (12)](https://user-images.githubusercontent.com/95094057/212641567-df23ef16-d958-4373-8850-7e2852d59361.gif)
might look a little blurry, it's because of the conversion

**Comment by eddiejaoude** [comment]
Is it possible to make the whole card clickable? if having 2 is not a good idea

**Comment by Sriparno08** [comment]
Hey @eddiejaoude, I have found a way to make the whole card clickable, just like in the video/gif. So, can I work on this?

**Comment by Aadarsh805** [comment]
> Hey @eddiejaoude, I have found a way to make the whole card clickable, just like in the video/gif. So, can I work on this?

there is already a pr on this #3485

**Comment by Sriparno08** [comment]
Alright, @Aadarsh805 👍

**Comment by HarshDeep61034** [comment]
@Sriparno08 you can work buddy I'm really busy with my exams.

**Comment by Sriparno08** [comment]
Thanks bro 👍

Hey @Aadarsh805, can I go ahead and make a PR as @HarshDeep61034 is busy right now?

**Comment by Aadarsh805** [comment]
> Thanks bro +1
> 
> Hey @Aadarsh805, can I go ahead and make a PR as @HarshDeep61034 is busy right now?

sure

**Comment by alokVerma749** [comment]
we can create a card component that can accept Heading, Paragraph, and Link so that it  can be used anywhere we want
