### ISSUE TITLE
Navigation is very slow and doesn't work at times.

### ISSUE THREAD

**Issue by FrozenHearth** [EddieHubCommunity/LinkFree#3161]
### Description

When items in the navbar are clicked, sometimes, the navigation is very slow, and sometimes one has to click multiple times for the navigation to work.

### Screenshots

https://user-images.githubusercontent.com/27160715/211837965-2c261768-d849-4b70-98a7-83efda1f0318.mov

### Additional information

Chrome: Latest version
OS: Mac OS Monterey 12.5.1

**Comment by KimberlyPangilinan** [comment]
I also have the same experience both laptop and mobile device. Maybe we can fix that or add a loader animation specially when searching

**Comment by FrozenHearth** [comment]
Well, I feel naturally the route transitions should be seamless. A loader will be a nice temporary fix, but we need to find out why the route changes are taking time.

**Comment by eddiejaoude** [comment]
Thanks for raising the issue. Yes search page is the slowest because it loads all the profiles. I think this issue is a duplicate of https://github.com/EddieHubCommunity/LinkFree/issues/2815 ?

**Comment by FrozenHearth** [comment]
@eddiejaoude Thanks for replying! Along with the search, the other links also load sort of slow.

**Comment by eddiejaoude** [comment]
I have made improvements to the profile page also, I think there is a performance improvement by 50%

**Comment by FrozenHearth** [comment]
@eddiejaoude The profile page improvements PR is merged?

**Comment by eddiejaoude** [comment]
Yes 👍 https://github.com/EddieHubCommunity/LinkFree/pull/3477

**Comment by FrozenHearth** [comment]
Awesome! :)

**Comment by FrozenHearth** [comment]
@eddiejaoude I was thinking we could have a progress bar when switching routes. That would clearly indicate a loading state. Right now, we are having to click the chips multiple times for example, to navigate to a page. Clicking once also navigates, but it is slow, so naturally, I thought my click didn't go through, and clicked twice.

**Comment by eddiejaoude** [comment]
Can you profile the pages loading time with Chrome?

**Comment by FrozenHearth** [comment]
@eddiejaoude Could you please guide me as to how to do that?
I've tried Chrome's Performance Insights. Not sure if you're referring to the same?

**Comment by SaraJaoude** [comment]
Further performance improvements have been made since the above comments. 

Additionally, there is an open Pull Request for a progress loader - however this has been parked for the moment because of the new features introduced in the latest NextJS.

I will close this for now, but feel free to raise a new issue with specific criteria.
