### ISSUE TITLE
[BUG] User Milestones card alignment fix (good first issue)

### ISSUE THREAD

**Issue by Aadarsh805** [EddieHubCommunity/LinkFree#3180]
### Description

The icon and the milestone description aren't aligned and looks odd

### how it is
![Screenshot from 2023-01-11 23-03-49](https://user-images.githubusercontent.com/95094057/211877786-469efea4-dbef-457d-9ca4-aa1ce9245e18.png)

### It should be 
![image](https://user-images.githubusercontent.com/95094057/211877843-3eddd632-13cb-4a93-a9f6-ba46a7ab3caf.png)

**Comment by aditya-kapadia** [comment]
I can help work on this if nobody is working on it

**Comment by MahendraBishnoi29** [comment]
@Panquesito7 what do you think about this?

**Comment by Aadarsh805** [comment]
![Uploading image.png…]()
