### ISSUE TITLE
Typo in Docs

### ISSUE THREAD

**Issue by KimberlyPangilinan** [EddieHubCommunity/LinkFree#3183]
### Description

I found a typographical error in the docs. Buiding should be building

### Screenshots

![Screenshot_20230112_021258_com android chrome](https://user-images.githubusercontent.com/92774426/211885607-7c950022-c1fb-46aa-9493-ed6e850b5c54.jpg)

**Comment by Ertan222** [comment]
I can fix it

**Comment by HarshDeep61034** [comment]
@Aadarsh805 Hey can you guide me on this issue, how can I approach this one?

**Comment by Aadarsh805** [comment]
> @Aadarsh805 Hey can you guide me on this issue, how can I approach this one?

sure, it's this typo that is being referred in the issue
![Group 8](https://user-images.githubusercontent.com/95094057/211907332-154c69c2-b3e8-4b06-a2dd-6cee7226aba3.png)

you can edit this directly from GitHub, for this go to this directory `pages/docs/index.js`, there you'll find the typo in the description of the first object of the `sections` array, fix it and make a commit

**Comment by Aadarsh805** [comment]
@HarshDeep61034 make sure you wait for getting assigned as @Ertan222 asked for it first

**Comment by mpotane** [comment]
Nice find kabayan @KimberlyPangilinan ☕️

**Comment by KimberlyPangilinan** [comment]
> Nice find kabayan @KimberlyPangilinan ☕️

Haha thank you, kabayan

**Comment by HarshDeep61034** [comment]
sure @Aadarsh805 I was just wondering where could i find the docs.

**Comment by Aadarsh805** [comment]
> sure @Aadarsh805 I was just wondering where could i find the docs.

it's here `pages/docs/index.js` in this directory, or in this URL `https://linkfree.eddiehub.io/docs`

**Comment by HarshDeep61034** [comment]
@Ertan222 are you fixing this one if not can I get assigned?

**Comment by Ertan222** [comment]
I am actually waiting to assign but if it's your first time, take it :smile:

**Comment by HarshDeep61034** [comment]
Can I get Assigned ?

**Comment by KimberlyPangilinan** [comment]
> Can I get Assigned ?

may i ask? im still a beginner in open source. who's the one responsible in assigning tasks?

**Comment by eddiejaoude** [comment]
Hi everyone, sorry for the slow reply, we have many GitHub notifications to go through. There are many issues, please do not fight over a single issue, it causes more notifications and confusion.

> who's the one responsible in assigning tasks?

Maintainers can assign issues to people. But sometimes with small typo fixes, someone raises a pull request straight away.

- Thank you @KimberlyPangilinan for spotting the bug 👍 
- @Ertan222 thank you for sharing the `good first issue` with @HarshDeep61034 
- @Aadarsh805 thank you for giving such details instructions on how to fix

@KimberlyPangilinan would you like me to assign you another issue, if so please tag me on Discord with the link to the issue

**Comment by KimberlyPangilinan** [comment]
> Hi everyone, sorry for the slow reply, we have many GitHub notifications to go through. There are many issues, please do not fight over a single issue, it causes more notifications and confusion.
> 
> > who's the one responsible in assigning tasks?
> 
> Maintainers can assign issues to people. But sometimes with small typo fixes, someone raises a pull request straight away.
> 
>     * Thank you @KimberlyPangilinan for spotting the bug 👍
> 
>     * @Ertan222 thank you for sharing the `good first issue` with @HarshDeep61034
> 
>     * @Aadarsh805 thank you for giving such details instructions on how to fix
> 
> 
> @KimberlyPangilinan would you like me to assign you another issue, if so please tag me on Discord with the link to the issue

thank you for the information, @eddiejaoude . I am just curious, i thought i am missing something, but now I know. Thank you

**Comment by eddiejaoude** [comment]
No problem, it is always good to ask, I am sure the question and discussion helped other people also 👍
