### ISSUE TITLE
Color Themes

### ISSUE THREAD

**Issue by KimberlyPangilinan** [EddieHubCommunity/LinkFree#3185]
### Description

Users like to use things if they can do personalizations. It will help them to embrace the app better since it is based on their personal preference. Maybe we can add color themes, it can be a selection of different accent colors or an addition of dark theme

Thank you

**Comment by eddiejaoude** [comment]
Great idea 👍 

Is this issue similar to this one https://github.com/EddieHubCommunity/LinkFree/issues/2957

**Comment by ChinmayMhatre** [comment]
#2957 already has an ongoing discussion on themes. Maybe this can be discussed further there?

**Comment by KimberlyPangilinan** [comment]
> similar

Yes 

> Great idea 👍
> 
> Is this issue similar to this one #2957

Thank you. Almost and i found some replies there pertaining to this.

**Comment by KimberlyPangilinan** [comment]
> #2957 already has an ongoing discussion on themes. Maybe this can be discussed further there?

Yes, my bad

**Comment by ChinmayMhatre** [comment]
> > #2957 already has an ongoing discussion on themes. Maybe this can be discussed further there?
> 
> Yes, my bad

No worries, if you have any suggestions you can give them in that issue. You can close this one

**Comment by KimberlyPangilinan** [comment]
> > > #2957 already has an ongoing discussion on themes. Maybe this can be discussed further there?
> > 
> > Yes, my bad
> 
> No worries, if you have any suggestions you can give them in that issue. You can close this one

Still new here, thank you for reminding me
