### ISSUE TITLE
Views count on a user should be based on unique visitors 

### ISSUE THREAD

**Issue by damian-wevue** [EddieHubCommunity/LinkFree#3187]
### Description

I just tried checking for a user's profile and realized that the view count and kept counting on every refresh.

### Screenshots

![Screenshot_20230111-203513~2](https://user-images.githubusercontent.com/121625588/211901885-0017bfa7-f44d-4f2f-944b-489e49f5d89d.png)
![Screenshot_20230111-203507~2](https://user-images.githubusercontent.com/121625588/211901895-d879dec3-6595-4954-b267-3ee9ef8955dd.png)

### Additional information

I was wondering if a cookie or some identification can be used to prevent this or is this a feature

**Comment by eddiejaoude** [comment]
> should be based on unique visitors

I personally I prefer on total views. Unique could be added but it is very difficult to get accurate.

**Comment by Aadarsh805** [comment]
@damian-wevue I'd work if there were a login feature you know, then we could differentiate between the users by their profile id, but here we can't differentiate between the viewers as it's completely open to view

**Comment by eddiejaoude** [comment]
We have a login feature coming soon, but not everyone will always be logged in - so it helps but still is inaccurate to calculate unique

There are other options like sessions or cookies or ip, but again not accurate. I might close this for now as we have so many other things going on at the moment. We can revisit this in the future

Thank you for the idea @damian-wevue, please keep them coming 👍 

Thanks @Aadarsh805 for sharing your thoughts also 👍 

Great collaboration everyone 💪
