### ISSUE TITLE
[BUG] Wrong image tag index.js

### ISSUE THREAD

**Issue by Ertan222** [EddieHubCommunity/LinkFree#3190]
### Description

# Problem
There is an old `<img>` tag in index.js gives warning.

# Solution
We need to change to `next/image <Image>` element.

### Screenshots

Between line 369 - 373
![Screenshot from 2023-01-11 23-05-32](https://user-images.githubusercontent.com/62712555/211911265-e39673ac-c129-4608-a729-71a29e36e02b.png)

**Comment by Ertan222** [comment]
I can try to fix it.

**Comment by eddiejaoude** [comment]
Thank you 👍

**Comment by krshkun** [comment]
Hey, sorry for not noticing this issue and making a PR against it. @Ertan222 have you started working on this, if not there a few issues I know that you could get assigned to 🙂 Otherwise I'll remove my pr's fix

**Comment by Ertan222** [comment]
@krshkun No no, I haven't started to fix it and we can close this issues with your PR, don't worry :smile:

**Comment by stephenokyere233** [comment]
@eddiejaoude could I take this one?

**Comment by Ertan222** [comment]
> @eddiejaoude could I take this one?

#3288 is going to fix this issue, I think we should move to another one.

**Comment by stephenokyere233** [comment]
> @stephenokyere233 
> > @eddiejaoude could I take this one?
> 
> #3288 is going to fix this issue, I think we should move to another one.

Okayy man

**Comment by Ertan222** [comment]
@krshkun Hahaha, don't worry Krish. Every application going to have a issue. I can fix other things :)
