### ISSUE TITLE
Mobile (View) Navigation Menu changes required

### ISSUE THREAD

**Issue by swagataroy30** [EddieHubCommunity/LinkFree#3191]
### Description

- The hamburger menu should turn into a close icon when it is open(the SVG for the close icon is present in the code but is not implemented)
- When we click on the EddieHub Icon, it redirects us to the home page but doesn't close the mobile navigation menu.
- When we click outside the navigation menu, the mobile navigation menu should close.
- On clicking the hamburger menu it has a white outline around it, which doesn't look good.

### Issues

https://user-images.githubusercontent.com/116095538/211910355-5d1b408f-1857-4359-b6d3-fbc8c7282ff0.mp4

**Comment by Aadarsh805** [comment]
> 

It should also close when navigated to another route (add this too in the points), there's already an issue on this #2507

**Comment by swagataroy30** [comment]
Should I add this point? won't it duplicate the issue?

**Comment by Aadarsh805** [comment]
> Should I add this point? won't it duplicate the issue?

ig it will, well the points addressed in this will automatically fix the one at #2507 so ig no point addressing it again
Leave it as it is then

**Comment by ManishBisht777** [comment]
I think This can be worked upon after #2507 gets merged as it only solves `point no 3` and the one addressed by @Aadarsh805

**Comment by EmmaDawsonDev** [comment]
It should probably also open on top of the page instead of pushing the rest of the content down.

**Comment by SaraJaoude** [comment]
This has been completed here: https://github.com/EddieHubCommunity/LinkFree/pull/3202 so I am closing this issue.
