### ISSUE TITLE
[BUG] GitHub link in the mobile navbar opens in the same tab (good first issue)

### ISSUE THREAD

**Issue by Aadarsh805** [EddieHubCommunity/LinkFree#3219]
### Description

this linked icon:
![Screenshot from 2023-01-12 04-15-16](https://user-images.githubusercontent.com/95094057/211934763-0457492d-1982-4402-a3f8-ec63de3575d5.png)

### Missing `target="_blank"` on the anchor tab used in the mobile nav dropdown, line no. `165` at `components/Navbar.js`

![image](https://user-images.githubusercontent.com/95094057/211934746-4a545e98-83f1-4f6d-981d-bb164638ed78.png)

Works perfectly fine on desktop

**Comment by swagataroy30** [comment]
could it be that " target = '_blank' " was not specified for mobile view, intentionally?

**Comment by ChinmayMhatre** [comment]
I have the github mobile app. So the link redirects me to the app. I am not sure about the mobile website

**Comment by eddiejaoude** [comment]
Not sure I follow? The main navigation should always open in the same tab - I get that functionality on the desktop.

**Comment by Aadarsh805** [comment]
> Not sure I follow? The main navigation should always open in the same tab - I get that functionality on the desktop.

ohh is it, links open in the same tab in mobile view?

**Comment by eddiejaoude** [comment]
Oh for the GitHub link in the main nav, yes this should be a new tab 👍
