### ISSUE TITLE
Select navigation does not show current selected section

### ISSUE THREAD

**Issue by razaahmad333** [EddieHubCommunity/LinkFree#3234]
## How to reproduce this bug?
Open a Linkfree profile on web screen and select a different section other than `my links`
Then toggle to mobile screen,
you will notice that select will show `my links` but the list will be of other sections for example `milestones` and `events`

Here it is `milestones` section but select is showing `my links`

![image](https://user-images.githubusercontent.com/50910798/211967579-b534d828-df89-4ebc-97f9-9b75ec6bd362.png)

**Comment by razaahmad333** [comment]
can I submit a pr on this issue?

**Comment by eddiejaoude** [comment]
Good spot 👍 I have assigned it to you

**Comment by SaraJaoude** [comment]
A user will not go from desktop to mobile window size - they will either be viewing on a desktop, or on a mobile.  Therefore this is unnecessary code so I will be closing this issue.
