### ISSUE TITLE
UI Milestone card needs to be fixed

### ISSUE THREAD

**Issue by razaahmad333** [EddieHubCommunity/LinkFree#3236]
### Description

UI of milestone card does not looks good when the title is longer.

## Suggestions
We can make it look good by some replacement.
What about placing date in prefix of title

For example, 
##  ` logo Dec 2022 - Started writing blogs on web development `
then_the_description_can_come_here

### Screenshots

![image](https://user-images.githubusercontent.com/50910798/211967910-0350f55e-0def-4890-8df4-c17989a2bfac.png)

**Comment by razaahmad333** [comment]
should I work on this issue?

**Comment by ChinmayMhatre** [comment]
Maybe we could add a word limit after which "..." Would be appended to the title.

Eg : create something wi....

We could also add a tooltip to show the full title on hover

**Comment by eddiejaoude** [comment]
I think the date could come below the description

**Comment by stephenokyere233** [comment]
@eddiejaoude I'd love to take this one too

**Comment by eddiejaoude** [comment]
@razaahmad333 do you want to work on this issue or shall I assign it to @stephenokyere233 ?

**Comment by ManishBisht777** [comment]
I have this in my mind may be it can help

![image](https://user-images.githubusercontent.com/89926834/212536612-b419fc3a-3969-46e7-896c-0bb29eda6603.png)

**Comment by razaahmad333** [comment]
> I have this in my mind may be it can help
> 
> ![image](https://user-images.githubusercontent.com/89926834/212536612-b419fc3a-3969-46e7-896c-0bb29eda6603.pn

> @razaahmad333 do you want to work on this issue or shall I assign it to @stephenokyere233 ?

you can assign to him ✅

**Comment by razaahmad333** [comment]
> I have this in my mind may be it can help
> 
> ![image](https://user-images.githubusercontent.com/89926834/212536612-b419fc3a-3969-46e7-896c-0bb29eda6603.png)

then we need to show them in grid instead of one in a single row

**Comment by razaahmad333** [comment]
> Maybe we could add a word limit after which "..." Would be appended to the title.
> 
> Eg : create something wi....
> 
> We could also add a tooltip to show the full title on hover

but @ChinmayMhatre  we don't have any problem with big screens where we have cursors to hover, this UI problem comes when we toggle to small screens (mobile)

**Comment by ManishBisht777** [comment]
> > I have this in my mind may be it can help
> > ![image](https://user-images.githubusercontent.com/89926834/212536612-b419fc3a-3969-46e7-896c-0bb29eda6603.png)
> 
> then we need to show them in grid instead of one in a single row

We can only keep this to mobile screen

**Comment by razaahmad333** [comment]
@ManishBisht777 that seems fine

**Comment by ManishBisht777** [comment]
Want to work on this

**Comment by ManishBisht777** [comment]
Any Updates on this?

**Comment by MAYANKpandey14** [comment]
Heyy, is this assigned to someone ?

**Comment by amandamartin-dev** [comment]
hey all! Sorry for the delay, it looks like the first person requesting to be assigned was @stephenokyere233 .  Can you confirm if you would like to work on this? Otherwise I will ask the next requester in the comments

**Comment by SaraJaoude** [comment]
Looks like this has been improved with other changes:

<img width="568" alt="Screenshot 2023-02-04 at 18 30 30" src="https://user-images.githubusercontent.com/82668196/216764959-5ae0b1bb-d52e-40bb-af0f-3e0a2ba0d72d.png">

I will close this for now.
