### ISSUE TITLE
link is not working _discord_ _GitHub Organization_ 

### ISSUE THREAD

**Issue by Himanshuch8055** [EddieHubCommunity/LinkFree#3240]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="http://discord.eddiehub.org">Discord</a> chat and our <a href="http://github.eddiehub.org">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>

_Originally posted by @github-actions in https://github.com/EddieHubCommunity/LinkFree/pull/3238#pullrequestreview-1244913393_

**The link of `_discord_` and `_GitHub Organization_` did not open on Git Application.**

**Comment by schmelto** [comment]
@Himanshuch8055 can you elaborate your issue a little bit more.
For me links are working fine.

What system do you use what do you mean by git application?

**Comment by ChinmayMhatre** [comment]
> @Himanshuch8055 can you elaborate your issue a little bit more.
> For me links are working fine.
> 
> What system do you use what do you mean by git application?

Ohhh I think @Himanshuch8055  created this issue because they got a failed action while adding their profile. They haven't given the json file the correct name. Pradumna has mentioned this in the issue

**Comment by ChinmayMhatre** [comment]
> > @Himanshuch8055 can you elaborate your issue a little bit more.
> > For me links are working fine.
> > 
> > What system do you use what do you mean by git application?
> 
> Ohhh I think @Himanshuch8055  created this issue because they got a failed action while adding their profile. They haven't given the json file the correct name. Pradumna has mentioned this in the issue #3238

**Comment by Himanshuch8055** [comment]
@schmelto I mean GitHub App.

**Comment by schmelto** [comment]
> @schmelto I mean GitHub App.

I'm on the mobile app and it's working fine for me can you make a screen recording?

**Comment by Himanshuch8055** [comment]
@ChinmayMhatre Yes you are right. I'm failed when I add my profile.
What I do to fix this issue?

**Comment by schmelto** [comment]
> @ChinmayMhatre Yes you are right. I'm failed when I add my profile. What I do to fix that issue?

Pradumna left a message on how to fix the issue.

**Comment by ChinmayMhatre** [comment]
> @ChinmayMhatre Yes you are right. I'm failed when I add my profile.
> What I do to fix that issue?

Pradumna has suggested some changes in #3238 .  you can ask any questions you have over there. This issue can be closed.

**Comment by Himanshuch8055** [comment]
https://user-images.githubusercontent.com/94627200/212033382-9968ad96-6236-40c3-a3c9-82aa55660a8f.mp4


I'm taking about GitHub-actions (bot) massage.

**Comment by ChinmayMhatre** [comment]
> https://user-images.githubusercontent.com/94627200/212033382-9968ad96-6236-40c3-a3c9-82aa55660a8f.mp4
> 
> 
> I'm taking about GitHub-actions (bot) massage. @ChinmayMhatre 

Ohhh yeah! This doesn't work for me either. I am using the github app

**Comment by Himanshuch8055** [comment]
@ChinmayMhatre The URLs is wrong given by GitHub-actions (bot).

**Comment by schmelto** [comment]
Strange for me it's working just fine 🙈

**Comment by ChinmayMhatre** [comment]
@Aadarsh805 could you try this out?

**Comment by Aadarsh805** [comment]
> @Aadarsh805 could you try this out?

It's working perfectly fine for me

**Comment by ChinmayMhatre** [comment]
@Himanshuch8055 @Aadarsh805  what network providers are you using?

**Comment by Aadarsh805** [comment]
> @Himanshuch8055 @Aadarsh805 what network providers are you using?

Jio Fibre

**Comment by HarshDeep61034** [comment]
working fine for me too

**Comment by Himanshuch8055** [comment]
@schmelto @ChinmayMhatre @Aadarsh805 @HarshDeep61034 
Thank you for your feedback. I think problem is my side. So, I close this issue guys.
