### ISSUE TITLE
[OTHER] Tag/Skill Search Limit on things under 3 characters

### ISSUE THREAD

**Issue by Parsifal-M** [EddieHubCommunity/LinkFree#3259]
### What would you like to share?

Hey Team! :wave: 

First of all, a super cool project I like it a lot and have all my socials pointing to it :smile: 

Just wondering as this is not really a `bug` nor is it really a `feature request` I am just wondering if there is a specific reason behind having a minimum of `3` characters needed for searching? I only ask because I added `Go` as a skill (or `tag`) and it will not let me search on it, but of course `Golang` does.

Not a major issue, I've always just referred to it as `Go` and not `Golang`, but it made me wonder if there is a specific reason other than maybe performance we set a minimum limit to 3 characters. :smiley: 

**P.S** I could also see an issue here if, for example, you want to add `C#`

Thanks, Team!,

### Additional information

Happy to look into this if we think it's worth looking into.

Thanks!

**Comment by ManishBisht777** [comment]
Good point @Parsifal-M. maybe we can add a make call only when the user stopped typing

**Comment by eddiejaoude** [comment]
Good spot 👍  no reason, just a short term solution to improve performance. The use stops typing is probably a better way (but still with a minimum of 2 characters otherwise there are too many results)

**Comment by ManishBisht777** [comment]
> 
now the limit 2 doesn't show tags with `c` language

**Comment by Parsifal-M** [comment]
Not had much time to dive into the code for this, but based on a very quick check in the UI I can see that when you click on a tag it just performs a search on an entire profile for the `keyword` so I select `Rust` I could get the result of `Mr John Rust` who does not have `Rust` listed in their profile at all.

I wonder, and again I've not had much time to look into this :sob: would it not be better to implement that `tags` only search for other `tags`? so if I hit `Rust` or `Go` it would return profiles with `Rust` or `Go` in their tags?

Just an idea :smile: 

Let me know what you guys think!

**Comment by Aadarsh805** [comment]
Adding search by pressing Enter key might work if you wanna force a search

**Comment by eddiejaoude** [comment]
> I wonder, and again I've not had much time to look into this 😭 would it not be better to implement that tags only search for other tags? so if I hit Rust or Go it would return profiles with Rust or Go in their tags?

Yep currently it searches both, an optional radio buttons could be added like `all`, `tags`, `name`

> Adding the functionality to search by pressing Enter key might also work if you wanna force a search

Yep enter could trigger the search

**Comment by EmmaDawsonDev** [comment]
A debounce function might be more useful than the minimum 3 characters

**Comment by Parsifal-M** [comment]
Hey Team :wave: 

Some great ideas above, I have some time this weekend to try and play around with this, I need to set up my local dev environment first. I will report back to see if we can figure out a smart way to do this :smile: 

Thanks, team!

**Comment by ManishBisht777** [comment]
I want to work on this

**Comment by SaraJaoude** [comment]
@Parsifal-M did you manage to get your local environment working?  If so we can assign this to you (if not, @ManishBisht777 do you still want this?).

Probably best go with the debounce solution that Emma suggested.

**Comment by ManishBisht777** [comment]
> @Parsifal-M did you manage to get your local environment working? If so we can assign this to you (if not, @ManishBisht777 do you still want this?).
> 
> Probably best go with the debounce solution that Emma suggested.

i am up for it if no one is working on this :)

**Comment by Parsifal-M** [comment]
> @Parsifal-M did you manage to get your local environment working?  If so we can assign this to you (if not, @ManishBisht777 do you still want this?).
> 
> Probably best go with the debounce solution that Emma suggested. 

Hey! :wave:

I assumed @ManishBisht777 was working on this as he asked to, so I will help out if needed :smile:

**Comment by ManishBisht777** [comment]
> > @Parsifal-M did you manage to get your local environment working?  If so we can assign this to you (if not, @ManishBisht777 do you still want this?).
> > Probably best go with the debounce solution that Emma suggested.
> 
> Hey! wave
> 
> I assumed @ManishBisht777 was working on this as he asked to, so I will help out if needed smile

lol, I am waiting to get assigned. anyways love to work on this, @Parsifal-M will let you know if I need help :)
