### ISSUE TITLE
PlaceHolder text change

### ISSUE THREAD

**Issue by ManishBisht777** [EddieHubCommunity/LinkFree#3283]
### Description

On the search page, the placeholder says `search user` but we also search on the basis of `tag/languages` 
![image](https://user-images.githubusercontent.com/89926834/212050305-772cd1b5-9467-422e-a90d-bc3e3501d40c.png)

we can change it to `search by name or tags` or we can keep it short as `search here` and add an example below it stating `search for name or tags ie. Manish or javascript`  if we consider this 
https://github.com/EddieHubCommunity/LinkFree/issues/3259

**Comment by khalidx3** [comment]
Hey, I can fix it can anyone assign me this?

**Comment by eddiejaoude** [comment]
Good spot @ManishBisht777 👍 

@khalidx3 I will sign it to you
