### ISSUE TITLE
[FEATURE]  Background image/ Wallpaper with theme toggle

### ISSUE THREAD

**Issue by amelia2802** [EddieHubCommunity/LinkFree#3317]
### Description

It would be great experience for users if they can personalize their site. Maybe we can add an option for personalized background image/ wallpaper along with light to dark mode toggle button .

I am adding a demo of the feature here.
Thank you.

### Screenshots

![Demo of the feature](https://user-images.githubusercontent.com/49182604/212147504-d36b69ac-b1d4-480d-82fe-914e81337f6b.png)

**Comment by ChinmayMhatre** [comment]
Hey @amelia2802 great idea! A similar discussion is going on in #2957. Maybe this can be discussed further there?

**Comment by amelia2802** [comment]
> Hey @amelia2802 great idea! A similar discussion is going on in #2957. Maybe this can be discussed further there?

My bad. I haven't checked out the other issues. Thank you for letting me know. 😊

**Comment by eddiejaoude** [comment]
Great idea 👍 

I think the dark theme issue #2957 is a separate discussion, so good to keep this open.

**Comment by FrozenHearth** [comment]
I would suggest we use modern image formats like webp, etc if we're using background images, so that the image size is smaller.

A nice app made by a Google dev to convert your imgs to the modern formats: https://squoosh.app/

**Comment by SaraJaoude** [comment]
This is a really nice idea but there are challenges in accessibility and usability.  Let's do the themes first and revisit this in the future (so I shall close this for now).
