### ISSUE TITLE
[DOCS] Link to the docs

### ISSUE THREAD

**Issue by ThomasCode92** [EddieHubCommunity/LinkFree#3358]
### Description

In my opinion, It looks better to delete the full link in the anchor tag at the homepage of the documentation site.
Maybe it's better to make the word 'here' clickable.

### Screenshots

![docs](https://user-images.githubusercontent.com/108367944/212341474-86ee4d85-c450-4202-900b-5c4a0d3fe9e6.JPG)
![docs_modified](https://user-images.githubusercontent.com/108367944/212341481-b674f2be-9321-4f91-8dd7-7865559f0a45.JPG)

**Comment by Sriparno08** [comment]
Hey, I would like to work on this!

**Comment by HarshDeep61034** [comment]
sorry mate, i did'nt knew you were working on this, I already made a PR #3378

**Comment by MahendraBishnoi29** [comment]
> 



> sorry mate, i did'nt knew you were working on this, I already made a PR #3378

I've closed my PR👍🏻

**Comment by HarshDeep61034** [comment]
> > 
> 
> > sorry mate, i did'nt knew you were working on this, I already made a PR #3378
> 
> I've closed my PR👍🏻

Alright Cool : )

**Comment by Sriparno08** [comment]
Alright, @HarshDeep61034 👍

**Comment by ThomasCode92** [comment]
The first screenshot was of the real documentation site when I started this issue.
The second one was a quick fix with the browser dev tools, to clearify my point.

But this issue has been fixed, so I think I can close this issue..
