### ISSUE TITLE
[DOCS] Minor spelling typo

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/LinkFree#3366]
### Description

There's a minor spelling typo on the events page.

_Steps to contribute_

1. Fork the repository [here](https://github.com/EddieHubCommunity/LinkFree/fork).
2. Create a new branch named `fix_spelling`.
3. Open the [`docs/how-to-guides/events.mdx`](https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/docs/how-to-guides/events.mdx) file.
4. In line 18, change `javacsript` to `javascript`.
5. Commit and push your changes.
6. Create a [pull request](https://github.com/EddieHubCommunity/LinkFree/compare) to compare your changes.
7. You're done now! 🎉 You just have to wait until the maintainers review your PR.

If you need any help, let us know. 🙂on

### Additional information

This is a good first issue. Please leave it open to first-time contributors and beginners.

**Comment by HarshDeep61034** [comment]
can I get assigned? @Panquesito7

**Comment by HarshDeep61034** [comment]
#3374 submitted.

**Comment by lokeshvasnik** [comment]
Close the issue

**Comment by ChinmayMhatre** [comment]
> Close the issue

Hey @lokeshvasnik , I think this issue is still being worked on .

**Comment by HarshDeep61034** [comment]
@ChinmayMhatre  @lokeshvasnik  Yup not merged yet!
