### ISSUE TITLE
[DOCS] Add suggested tags

### ISSUE THREAD

**Issue by krshkun** [EddieHubCommunity/LinkFree#3376]
### Description

Suggested tags in linkfree profiles

### Additional information

We can have this docs

**Comment by ChinmayMhatre** [comment]
Could you elaborate on this. I didn't get it.

**Comment by krshkun** [comment]
We can programmatically calculate the popular tags and then show them to people

**Comment by HarshDeep61034** [comment]
@krshkun is that different from #3383 ?

**Comment by krshkun** [comment]
Oh yes.
