### ISSUE TITLE
[FEATURE] Make a landing page

### ISSUE THREAD

**Issue by qwel-exe** [EddieHubCommunity/LinkFree#339]
### Description

we can add a landing page telling about the linkfree etc 

### Additional information

could i take up this for hacktoberfest

**Comment by Cahllagerfeld** [comment]
Do you already have an idea or a mockup, how your landing page should look like? 😄

**Comment by qwe123coder** [comment]
> Do you already have an idea or a mockup, how your landing page should look like?

yess i do

**Comment by ZaidKhan2002** [comment]
> > Do you already have an idea or a mockup, how your landing page should look like?
> 
> yess i do

> Are you working on it or could you share the mockup you have

**Comment by qwe123coder** [comment]
hey could i work on this for hacktoberfest

**Comment by ZaidKhan2002** [comment]
Sure

**Comment by krishguptadev** [comment]
Are you still working? @qwe123coder

**Comment by qwe123coder** [comment]
> Are you still working on this issue or I could grab it? @qwe123coder

hey i am done but do you want to work on it ?

**Comment by qwe123coder** [comment]
> > Are you still working on this issue or I could grab it? @qwe123coder
> 
> hey i am done but do you want to work on it ?

there are still few things to do do you want to do ?

**Comment by krishguptadev** [comment]
Are the changes merged already?

**Comment by qwe123coder** [comment]
> Are the changes merged already?

nop i can put it in my folks and you can make a pr there

**Comment by krishguptadev** [comment]
wdym? folks? How does this word fit here?

**Comment by krishguptadev** [comment]
np if you are already working on it, continue.. I'll make fixes if I find any after your changes are merged

**Comment by Panquesito7** [comment]
> wdym? folks? How does this word fit here?

I think they meant to say "fork's".

**Comment by krishguptadev** [comment]
> > wdym? folks? How does this word fit here?
> 
> I think they meant to say "fork's".

np I'll wait for them to complete and merge the changes

**Comment by Vyvy-vi** [comment]
Hey there, just checking in.
Are you still working on this issue @qwe123coder?

**Comment by qwe123coder** [comment]
> Hey there, just checking in. Are you still working on this issue @qwe123coder?

hey i forgot about this i will make my pr soon

**Comment by sauradip007** [comment]
has this issue been addressed yet?

**Comment by krishguptadev** [comment]
> > Hey there, just checking in. Are you still working on this issue @qwe123coder?
> 
> hey i forgot about this i will make my pr soon

Just checking in once more, @qwe123coder still working? 🙂

**Comment by qwe123coder** [comment]
> > > Hey there, just checking in. Are you still working on this issue @qwe123coder?
> > 
> > 
> > hey i forgot about this i will make my pr soon
> 
> Just checking in once more, @qwe123coder still working? slightly_smiling_face

ya i diched it you can work on it if you want

**Comment by krishguptadev** [comment]
@sauradip007 feel free to work on this issue 😄

**Comment by Vyvy-vi** [comment]
I'm wondering, is a landing page needed?

(esp. considering the direction the project is taking with the user profiles grid on the main page)

**Comment by KendallDoesCoding** [comment]
Any update on this?

**Comment by frazie** [comment]
Is the landing page still needed for the project?
I'd be glad helping out if it hasn't been assigned yet? 😃

**Comment by emmalearnscode** [comment]
@frazie Yes, we are thinking of removing the chips entirely and replacing with a description of the project. You can see an updated issue here #1264 if you're interested. Task 1 has been completed but the second task which is slightly larger is still outstanding.

**Comment by emmalearnscode** [comment]
Eddie built the first iteration of the landing page on a live stream a couple of weeks ago so I'll close this issue now. Feel free to take a look at the current page and raise new issues if there are things you'd like to see added.
