### ISSUE TITLE
[FEATURE] Change text color of the profile views bubble to white

### ISSUE THREAD

**Issue by ChinmayMhatre** [EddieHubCommunity/LinkFree#3420]
### Description

I think the text color of the bubbles would be seen more clearly if it was white. I have attached a screenshot of both side by side for comparison

### Screenshots

![image](https://user-images.githubusercontent.com/51131670/212462809-96455c4e-8ded-4785-8093-fc63abd5c1d1.png)

**Comment by HarshDeep61034** [comment]
I would like to work on this one.

**Comment by HarshDeep61034** [comment]
@JunDevHarsh Great but you should've discussed it first before opening a PR.
no worries, just a suggestion from me.

**Comment by JunDevHarsh** [comment]
Hello @HarshDeep61034,

I noticed that you had requested to work on Issue #3423 and I apologize for not reaching out to you before creating the pull request. I had taken the initiative to work on the issue as I saw that it was unassigned and I wanted to help move the project forward.

However, I understand that this might have caused confusion and I apologize for any inconvenience caused. I would like to request you to review the pull request and let me know if there's anything that needs to be fixed or if you have any concerns.

**Comment by HarshDeep61034** [comment]
@JunDevHarsh  No problem 😊 👍 
I also make a lot of mistakes daily.

**Comment by EmmaDawsonDev** [comment]
Please check that the color contrast is more than 4.5:1 with white text on the orange background before making this change.

**Comment by JunDevHarsh** [comment]
@EmmaDawsonDev Please take a look at this. Is this what you were referring to? I agree with you that the white text does not contrast well enough with the orange background.

![1](https://user-images.githubusercontent.com/94737463/212611583-c4870917-4dff-4380-bf37-5d2b070dc558.png)

**Comment by EmmaDawsonDev** [comment]
> @EmmaDawsonDev Please take a look at this. Is this what you were referring to? I agree with you that the white text does not contrast well enough with the orange background.
> 
> ![1](https://user-images.githubusercontent.com/94737463/212611583-c4870917-4dff-4380-bf37-5d2b070dc558.png)

Yes, that’s what I was referring to.

**Comment by ChinmayMhatre** [comment]
> > @EmmaDawsonDev Please take a look at this. Is this what you were referring to? I agree with you that the white text does not contrast well enough with the orange background.
> > ![1](https://user-images.githubusercontent.com/94737463/212611583-c4870917-4dff-4380-bf37-5d2b070dc558.png)
> 
> Yes, that’s what I was referring to.

I think this issue can be closed since the black text has a good contract ratio

![image](https://user-images.githubusercontent.com/51131670/213198390-3945d29f-94dc-4c72-bc9b-03e3d38785a5.png)
