### ISSUE TITLE
[FEATURE] Improving UI for discover page

### ISSUE THREAD

**Issue by Aadarsh805** [EddieHubCommunity/LinkFree#3426]
### Description

The page doesn't have a visual hierarchy between the main heading and the subheadings, it'd be better to have the main heading different in terms of font size and placement

#### Suggesting something like this

this looks less cluttered
![image](https://user-images.githubusercontent.com/95094057/212467284-72fa4677-9a15-46e4-b779-6b49ea6a2a26.png)

**Comment by imtiazpy** [comment]
I believe it would greatly improve the overall design if the main heading was differentiated in terms of font size, etc. May I be assigned to this task so that I can work on this issue? Thank you.

**Comment by imtiazpy** [comment]
The task has been completed-
PR- https://github.com/EddieHubCommunity/LinkFree/pull/3479

**Comment by Aadarsh805** [comment]
#3403 Eddie said here that this change will disturb the consistency of layout over all pages
So it is not required rn

**Comment by imtiazpy** [comment]
How about making other pages look like this (The proposed layout) ? @Aadarsh805

**Comment by Aadarsh805** [comment]
> 

Well let's ask others by putting a new issue asking for this
would you like to create the issue? you can put the same screenshot there explaining how we could make the same changes for all other pages too

**Comment by imtiazpy** [comment]
Alright, I will create an issue regarding this UI change. @Aadarsh805

**Comment by Aadarsh805** [comment]
> Alright, I will create an issue regarding this UI change. @Aadarsh805

Let me know when you're done creating the issue, so I'll close this one as this will also be addressed in that
make sure to link this issue in there too

**Comment by imtiazpy** [comment]
Hi @Aadarsh805 
An issue has been created for the issue #3532 

You can close this issue
