### ISSUE TITLE
Views Order Not correct

### ISSUE THREAD

**Issue by ManishBisht777** [EddieHubCommunity/LinkFree#3434]
### Description

On toggling the sorting order of `Links` in profile page the views does not sort

### Default

![image](https://user-images.githubusercontent.com/89926834/212472894-5fc9cb4a-5261-45fa-8238-214e75a2957d.png)

### On sort the order changes but the view does show in the same

![image](https://user-images.githubusercontent.com/89926834/212472900-6ce332d7-8749-4a71-8792-8c6464c223df.png)

**Comment by Aadarsh805** [comment]
Can i get assigned on this
