### ISSUE TITLE
[DOCS] Update docker compsose commad in docs

### ISSUE THREAD

**Issue by Olohitai** [EddieHubCommunity/LinkFree#3437]
### Description

Update the docs with `docker compose up` instead of `docker-compsose up`

### Screenshots

Link to the Docs that need to be updated - https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/docs/environments/local-development-docker-compose.mdx

![Screenshot 2023-01-15 at 1 07 28 AM](https://user-images.githubusercontent.com/51878265/212493070-6f391333-9532-4fbc-857e-6996fc828421.png)

Ref - https://github.com/EddieHubCommunity/LinkFree/issues/3437#issuecomment-1382895896

**Comment by khalidx3** [comment]
I can fix it, can someone just assign it to me?

**Comment by shivam-sharma7** [comment]
Opened a PR

**Comment by Pradumnasaraf** [comment]
Hey, thanks for opening the issue. The command is the README is correct. I think in the docs it's outdated. You can check the screenshot below

- https://docs.docker.com/engine/reference/commandline/compose_up/

![Screenshot 2023-01-15 at 12 55 05 AM](https://user-images.githubusercontent.com/51878265/212492629-7c50af62-a49b-4a51-bf26-c821dc5aba2d.png)

**Comment by Pradumnasaraf** [comment]
Hey, @shivam-sharma7 you can raise PR for the updated instructions.

**Comment by Pradumnasaraf** [comment]
Yes, it's still open. But I will wait 1-2 more days for @shivam-sharma7 to reply. Otherwise you can work on it.

**Comment by HarshDeep61034** [comment]
Alright thanks. 👍

**Comment by shivam-sharma7** [comment]
> Alright thanks. 👍

you can work @HarshDeep61034

**Comment by HarshDeep61034** [comment]
@shivam-sharma7 ok Thanks!

**Comment by HarshDeep61034** [comment]
#3670
