### ISSUE TITLE
[FEATURE] Style: sort tailwindcss classes

### ISSUE THREAD

**Issue by JunDevHarsh** [EddieHubCommunity/LinkFree#3439]
### Description

It would be great to define tailwind CSS classes in a proper way rather than defining unsorted way. For e.g. 

`<li className="py-4 border-l-2 mb-4 pl-2 hover:border-l-4 pr-2 shadow-md">Some text</li>`

should be converted to

`<li className="mb-4 pl-2 pr-2 py-4 border-l-2 hover:border-l-4 shadow-md"><Some text</li>`

**Comment by JunDevHarsh** [comment]
@eddiejaoude Can I work on this issue?

**Comment by eddiejaoude** [comment]
Thank you for the suggestion, but from previous experience this is not sustainable and creates a lot make work for new contributors
