### ISSUE TITLE
New Testimonial for Krish Gupta 🥑

### ISSUE THREAD

**Issue by LinuxGamer** [EddieHubCommunity/LinkFree#3440]
### Name

krshkun

### Title

Wonderfully Helpful and Amazing

### Description

Krish is a very polite person who strives when helping others, and is generally a **wonderful and amazing** human being. :) A **huge** part of the EddieHub Community and the Open Source World.

**Comment by krshkun** [comment]
Thanks for the testimonial @LinuxGamer really appreciate it!
