### ISSUE TITLE
[FEATURE] Disassociate Discover by Tags from general Search

### ISSUE THREAD

**Issue by M1FXI** [EddieHubCommunity/LinkFree#3460]
### Description

Discover and Search are two features with distinctive purposes. Currently, clicking on a tag on Discover page will redirect the user to a Search for that tag. I believe the most natural approach would be to just display the assigned users on the spot, without redirecting to the search page. 

One example of Discover and Search having different concerns is #3380. Although randomizing results for tag discoverability is a good call, doing so in a search results page is not a great choice. The expected behavior of full text search is that most relevant results will be on top.

**Comment by SaraJaoude** [comment]
Thank you for raising.

1. Tags have been removed from the Discover page.
2. We will randomise for now and later we will add full text search. 

So I will close this.
