### ISSUE TITLE
Wrong twitter handel

### ISSUE THREAD

**Issue by himanshu1221** [EddieHubCommunity/LinkFree#3461]
### Description

My twitter handle is showing the wrong id can we please update it 

### Screenshots

![Screenshot_20230115_092735](https://user-images.githubusercontent.com/32031706/212522215-deaeb2d1-6ff4-4ca0-97a0-8eba25f0ebcd.jpg)

### Additional information

My main id is himanshuchhatw2

**Comment by khalidx3** [comment]
you may have provided wrong link

**Comment by himanshu1221** [comment]
Can u tell me whats the procedure to update it?

**Comment by khalidx3** [comment]
@Aadarsh805 could you help him out?

**Comment by vikaskumar2703** [comment]
@himanshu1221 You can create another pull request with more changes, here are the docs https://linkfree.eddiehub.io/docs/how-to-guides/editing

**Comment by himanshu1221** [comment]
Done

**Comment by Aadarsh805** [comment]
@himanshu1221 you should close this issue then

**Comment by himanshu1221** [comment]
> @himanshu1221 you should close this issue then

Sure
