### ISSUE TITLE
[FEATURE] Adding Search by Location capability

### ISSUE THREAD

**Issue by SandipPalit** [EddieHubCommunity/LinkFree#3467]
### Description

It would be great if we can search for users based on their location. It will help us in connecting with like-minded persons around us.

If we could add location information to our profile in [CITY], [STATE], [COUNTRY]. format, then it can be integrated with the search engine.

Examples:
- Kolkata, West Bengal, India.
- Mumbai, Maharashtra, India.
- Capital District, New York, United States.

### Screenshots

![image](https://user-images.githubusercontent.com/48781286/212527043-52032c1e-d36d-493e-ba42-a8506d95c34d.png)

**Comment by ManishBisht777** [comment]
great idea :+1:

**Comment by ManishBisht777** [comment]
An additional field `location :{
city:" ",
state:" ",
country:" "
}`

in `profile.json`

**Comment by SandipPalit** [comment]
Thanks, @ManishBisht777. 

Yes, we can store the data in `location :{ city:" ", state:" ", country:" " }` format, and we can display it as `city, state, country`.

**Comment by SaraJaoude** [comment]
Work has started on this in a draft PR by @amandamartin-dev https://github.com/EddieHubCommunity/LinkFree/pull/3169

This is something we will be able to do after that PR has been completed and merged.

**Comment by ThePiyushAggarwal** [comment]
Is this issue available to work on? As the PR by Amanda has been merged.

**Comment by SaraJaoude** [comment]
This issue remains blocked as it is also waiting for: https://github.com/EddieHubCommunity/LinkFree/pull/4438

**Comment by mishra-nikhil0110** [comment]
search is not working on my local....wtd

**Comment by akash19coder** [comment]
Could you please assign it to me I would like to implement it? I can see no one has been assigned and not a lot of work has been done so far

**Comment by SaraJaoude** [comment]
> Could you please assign it to me I would like to implement it? I can see no one has been assigned and not a lot of work has been done so far

@akash19coder I will assign this to you

**Comment by akash19coder** [comment]
I actually have semester exams going on right now I will work on it after June 23. So please do not unassign me if possible.

**Comment by SaraJaoude** [comment]
> I actually have semester exams going on right now I will work on it after June 23. So please do not unassign me if possible.

@akash19coder we cannot block the opportunity for someone else to work on this issue for this long so I have unassigned this from you.  If after June 23 no one has asked for this issue then please feel free to ask for this to be assigned to you again.  Good luck with your exams!

**Comment by shoebilyas123** [comment]
If no one is working on this, can I work on this issue?

**Comment by SaraJaoude** [comment]
> If no one is working on this, can I work on this issue?

@shoebilyas123 I will assign this to you

**Comment by shoebilyas123** [comment]
> > If no one is working on this, can I work on this issue?
> 
> @shoebilyas123 I will assign this to you

Thank you!
