### ISSUE TITLE
Mutliple tags with same name

### ISSUE THREAD

**Issue by ManishBisht777** [EddieHubCommunity/LinkFree#3469]
### Description

![image](https://user-images.githubusercontent.com/89926834/212530551-ece1367a-2e26-4ed9-9b9d-4d753869f650.png)

The data stored in the database for javascript, javaScript, JavaScript , JavascripT etc are different as it is considering them different 

we can convert them in lowercase or uppercase before adding them to the database 
and show it on the UI with a `text-transform: capitalize`

**Comment by nanthakumaran-s** [comment]
Another approach: Make reactjs react.js react js into one common identifier. Let me explain it

We will need 2 properties in the MongoDB collection. Those are
- Identifier
- Display Name

While inserting any skill, the display name will be the same as that entered by the user. but we are going to change the identifier. Here's how

let's take a skill React Js
- lowercase (react js)
- trim (reactjs)
- replace special characters with '' (reactjs)
- store

Let's see how it works on React.js,
- lowercase (react.js)
- trim (react.js)
- replace (reactjs)

So finally the identifier will be the same for React Js and React.js. We can use the identifier to calculate and display on discover.

> Note: This still doesn't work on skills like react and react.js. For those cases, we need to remove the js if present. It will solve the issue

**Cons**: 
- We need to create a dedicated collection in MongoDB however some logic with the existing code can avoid it

Hope this is helpful. If wish to add this I can also contribute to it.
