### ISSUE TITLE
[FEATURE] Application logging

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#3482]
### Description

We need to decide on how and where to log the application logs

Winston is a popular logging library https://www.npmjs.com/package/winston

NextJS recommend https://www.npmjs.com/package/pino

**Comment by krshkun** [comment]
Winston is cool, but have you had a look at consolajs? I built myself a logger some time ago to streamline the development of my apps, I previously used winston ([repo](/krshkun/alpaca-logger)) now I use consola because I find it much better ([repo](/krshoss/trevenant))

**Comment by eddiejaoude** [comment]
Thanks for the suggestion 👍 I will take a look.

We also need it to log to a service, so we can have the maintainers view the logs - I will need to do more research

**Comment by nanthakumaran-s** [comment]
According to the official docs by Next Js, we can use [Pino](https://www.npmjs.com/package/pino) as the logger for the application's server. This is the example repo - [next-pino-logflare-logging-example](https://github.com/Logflare/next-pino-logflare-logging-example)

<img width="770" alt="image" src="https://user-images.githubusercontent.com/59391441/212800170-5d607008-3598-430d-a042-23f0cc27f372.png">

Or we can have a discussion on the pros and cons of different logging plugins. Can I also work on this issue?
