### ISSUE TITLE
[FEATURE] Use Intl API instead of `js-abbreviation-number`

### ISSUE THREAD

**Issue by krshkun** [EddieHubCommunity/LinkFree#3483]
### Description

JavaScript has a Intl api (internationalization API) which does meet our use case requirements, no need for another dependency

**Comment by Rishabh-Singh-Codes** [comment]
I would like to work on this.

**Comment by krshkun** [comment]
Hey @Rishabh-Singh-Codes I have already made a PR for this and am working on it :) Thanks for showing interest though

**Comment by ChinmayMhatre** [comment]
Hey @krshkun , I think there was an issue while linked the PR. Since the PR is merged could you close the issue?

**Comment by krshkun** [comment]
Oh unsure why it didn't close
