### ISSUE TITLE
Spelling fix

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [EddieHubCommunity/LinkFree#3507]
### Description

Correct spellings
-  "Demonstrate" 
-  "message"

### Screenshots

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/212560622-43c9cbca-725d-404d-93cf-5785d8e788b1.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/212560888-2b4af47a-fcc4-4488-9979-228b7afd0d65.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/212561510-53c5f632-8b1c-420f-b42f-1b95e704e2c5.png">

**Comment by EmmaDawsonDev** [comment]
Well spotted!
