### ISSUE TITLE
[FEATURE] Fixing Navbar on Mobile to Stay in Place instead of Pushing Content Down [good first issue]

### ISSUE THREAD

**Issue by Aadarsh805** [EddieHubCommunity/LinkFree#3511]
### Description

Currently, whenever the navbar is opened on a mobile-sized screen, it pushes down the main page content down
It'd be better to have it fixed and open above the content mobile-sized

### Currently

![screen-capture (13)](https://user-images.githubusercontent.com/95094057/212566325-40218d4c-8159-436e-a844-49ba325eb2df.gif)

### After changes proposed

![screen-capture (1fsd0)](https://user-images.githubusercontent.com/95094057/212566252-ec6840ff-b208-47af-b67d-abba0c138a6b.gif)

### Additional information

If it's approved, it's a good first issue for beginners to work on

**Comment by imtiazpy** [comment]
Hi @Aadarsh805 I would like to work on this. 

Note: Do you want it to be transparent as well, so that the content underneath can be seen?

**Comment by Aadarsh805** [comment]
> Hi @Aadarsh805 I would like to work on this.
> 
> Note: Do you want it to be transparent as well, so that the content underneath can be seen?

Let a maintainer have a look at this, they'll assign you as well
I think making it transparent will disturb the color theme

**Comment by imtiazpy** [comment]
I understand your perspective, but recreating the design in the same way as before may result in the navigation bar covering up the content. This would make the content invisible again. @Aadarsh805

**Comment by ManishBisht777** [comment]
> Hi @Aadarsh805 I would like to work on this.
> 
> Note: Do you want it to be transparent as well, so that the content underneath can be seen?

I think if someone is opening the menu then their focus will be on the menu itself, making the navbar transparent will make the background text and the nav links text blend a bit causing it difficult to read for users as well.

**Comment by rohinish404** [comment]
How about making this action a bit more smooth by adding transition?

**Comment by Aadarsh805** [comment]
Yes make sure to add the transition whoever works on this

**Comment by Aadarsh805** [comment]
@Pradumnasaraf can you please review the issue and the suggestions which one to go for, also do assign imtiazpy if the issue is valid

**Comment by Aadarsh805** [comment]
> I understand your perspective, but recreating the design in the same way as before may result in the navigation bar covering up the content. This would make the content invisible again. @Aadarsh805

The content being visible is not the issue that's being addressed, it's the shifting in the layout that should not happen like that for no reason

**Comment by imtiazpy** [comment]
I got it @Aadarsh805 

Waiting for a maintainer to have a look into the issue and assign me.

**Comment by Pradumnasaraf** [comment]
> @Pradumnasaraf can you please review the issue and the suggestions which one to go for, also do assign imtiazpy if the issue is valid

Hey, I am not sure about this UI addition. Tagging @eddiejaoude

**Comment by k99sharma** [comment]
Hey, @Aadarsh805  I added the PR a while back to make the navbar functional. In my opinion, you should add a transition to it making it look smoother, but the content pushing makes the UI cooler. What do you think? @eddiejaoude

**Comment by eddiejaoude** [comment]
Great discussion everyone, lots of great ideas 👍 

I think we should do small steps so we can see and test the improvements. So I think the first and most simple step that adds value is making it transition first, then we can take it from there

**Comment by Aadarsh805** [comment]
@imtiazpy you can start with this, If you're free

**Comment by SaraJaoude** [comment]
This does not appear to be causing any challenges at the moment, so I will close this for now.
