### ISSUE TITLE
[BUG] Typo in the main docs page

### ISSUE THREAD

**Issue by Aadarsh805** [EddieHubCommunity/LinkFree#3512]
### Description

there is this typo in the `Available icons` section on the docs page

`profie` -> `profile`

![Group 11 (3)](https://user-images.githubusercontent.com/95094057/212567532-2897b44e-a6eb-4554-a91a-bc461d0d7f44.png)

### How to fix

this issue can be found in the `pages/docs/index.js` file

#### The typo is right here on the 67th line in `pages/docs/index.js` file
![image](https://user-images.githubusercontent.com/95094057/212567261-95d8848a-87be-4486-9003-6f6d48ecb636.png)

**Comment by dhruvdabhi101** [comment]
I would like to contribute.

**Comment by Sriparno08** [comment]
Hey @dhruvdabhi101, sorry for not noticing your contribution request! I have already raised a PR on this issue!

**Comment by Aadarsh805** [comment]
> Hey @dhruvdabhi101, sorry for not noticing your contribution request! I have already raised a PR on this issue!

Please get yourself assigned first on the issues so that it doesn't create such confusion and overlap in contributions.

**Comment by Sriparno08** [comment]
Alright, @Aadarsh805 👍
