### ISSUE TITLE
[BUG] Typo in the testimonials guide docs page

### ISSUE THREAD

**Issue by Aadarsh805** [EddieHubCommunity/LinkFree#3514]
### Description

there is this typo in the `Including a Testimonial on your Profile` section in the testimonials guide page

`If you receive a Testimonials` -> `If you receive a Testimonial`

![Group 11 (4)](https://user-images.githubusercontent.com/95094057/212568079-c10cac45-4fb1-47e7-83db-896a784f8bb8.png)

### How to fix

this issue can be found in the `pages/docs/how-to-guides/testimonials.mdx` file

##### The typo is right here on the 36th line in `pages/docs/how-to-guides/testimonials.mdx` file

![image](https://user-images.githubusercontent.com/95094057/212568303-7cf86a2f-33fc-4e1a-a41f-4db7be1fd252.png)

### Additional information

@eddiejaoude I also found some more typos in the testimonials written by users for your profile, which are being used as examples in the testimonials guide page, like this one: 

![image](https://user-images.githubusercontent.com/95094057/212568471-cec9c594-3afe-4007-9234-ed5cd18ae5ac.png)

which is also in your profile here
![Group 13](https://user-images.githubusercontent.com/95094057/212568580-4a31a205-a583-43bc-86da-a3ed07188520.png)

When users write testimonials for anyone we can't guarantee that there won't be typos in that right, so maybe not fix it there on your Linkfree profile, but can have it fixed in the docs
I don't think it would even matter because it's not a part of documentation and is just an example

**Comment by Aadarsh805** [comment]
@Pradumnasaraf this has been solved in #3510, but I still want Eddie's response on one other thing that I mentioned in the additional information
So should I close this or not

**Comment by Pradumnasaraf** [comment]
> @Pradumnasaraf this has been solved in #3510, but I still want Eddie's response on one other thing that I mentioned in the additional information So should I close this or not

You can let it remain open. You can close after Eddie's response.
Hey, @eddiejaoude can you look

**Comment by eddiejaoude** [comment]
Thanks for collaborating 👍 

Thanks for checking, but I think we should not update people's profiles or testimonial files even if there are typos, so we can close this issue now
