### ISSUE TITLE
[Feature/Fix ] :  Text color of LinkedIn link mixes with the bg-color, when hover

### ISSUE THREAD

**Issue by akash-kumar44** [EddieHubCommunity/LinkFree#352]
### Description

The background color of LinkedIn and Instagram links remains white when hovered over them.

### Screenshots

![Screenshot (94)](https://user-images.githubusercontent.com/86745118/135223331-0a892727-630b-4eeb-9db9-81296e4f0d50.png)
![Screenshot (95)](https://user-images.githubusercontent.com/86745118/135223354-642eb50b-5833-41f4-899d-b9cfdbf5f53f.png)

### Additional information

N/A

**Comment by Guneetsinghtuli** [comment]
I would like to work on this issue
