### ISSUE TITLE
ImageAlt can be relpaced with a Skeleton

### ISSUE THREAD

**Issue by Guneetsinghtuli** [EddieHubCommunity/LinkFree#353]
### Description

Image Alternative text shows up before the Avatar is rendered, The Alternate text can be replaced with the `Skeleton` of Prime react 
So the user is able to see a skeleton rather than that Alternate text and after the avatar is rendered the skeleton disappears for it.

### Screenshots

![Screenshot 2021-09-29 at 12 58 16 PM](https://user-images.githubusercontent.com/48324492/135223596-147affec-30c7-45cc-9671-76d94da70838.png)

### Additional information

I have tried solving this issue but facing a problem while solving it and will be needing some help with it

**Comment by AbhijithGanesh** [comment]
Skeleton as in the emoji or something else?

**Comment by Guneetsinghtuli** [comment]
By skeleton i mean 
![Screenshot 2021-09-29 at 2 33 06 PM](https://user-images.githubusercontent.com/48324492/135237971-f35348b1-4b63-4a53-9510-13993aa5960f.png)

**Comment by Cahllagerfeld** [comment]
I like this idea!

**Comment by AbhijithGanesh** [comment]
> By skeleton i mean 
> ![Screenshot 2021-09-29 at 2 33 06 PM](https://user-images.githubusercontent.com/48324492/135237971-f35348b1-4b63-4a53-9510-13993aa5960f.png)
> 
> 

Got it thanks, good idea

**Comment by Guneetsinghtuli** [comment]
@AbhijithGanesh Can you assign this to me

**Comment by AbhijithGanesh** [comment]
> @AbhijithGanesh Can you assign this to me 
> 

I actually don't have the access to assign people but I maybe able to help you out

**Comment by san-coding** [comment]
I think the alt text is more appropriate, because that is role `alt` attributes is supposed to play whenever picture is not rendered

**Comment by Cahllagerfeld** [comment]
I think when loading its fine to display a skeleton, the alt imo is when the image cant be loaded or displayed corretly

**Comment by san-coding** [comment]
Yeah you're right

**Comment by krishguptadev** [comment]
Skeleton is a better ui/ux option. Let's go with it!
