### ISSUE TITLE
[FEATURE] Improving UI for all the pages

### ISSUE THREAD

**Issue by imtiazpy** [EddieHubCommunity/LinkFree#3532]
### What would you like to share?

A concern was brought to our attention by @Aadarsh805 in issue #3426, stating that the [Discover](https://linkfree.eddiehub.io/discover) page lacks a clear visual hierarchy between the main heading and subheadings. 

In response, I submitted a pull request (PR) (#3479) to address this issue. However, it was later determined that this change would disrupt the overall consistency of the layout and was not implemented. - #3403 

As a result, it is suggested that the layout of other pages be reviewed and improved to clearly separate elements such as `titles`, `headings`, `subheadings`, and `content` for a more organized visual hierarchy.

Suggested change: ie: Discover page:
![LinkFree-Discover](https://user-images.githubusercontent.com/45868098/212616998-602359a8-b2e0-486b-b632-7a0af120ee7e.png)

**Comment by ManishBisht777** [comment]
Thinking something like this. Not sure if this is ok Because for this we have to do a lot of changes  
![image](https://user-images.githubusercontent.com/89926834/212973898-7fc3e898-68c8-4fd1-b657-141d237b2530.png)

**Comment by SaraJaoude** [comment]
It is unclear what problem this issue is trying to solve, so I shall close this now. Please raise a new issue with clearer and more specific information as to the benefits of the changes.
