### ISSUE TITLE
[OTHER] Suggestion - Add path aliases

### ISSUE THREAD

**Issue by FrozenHearth** [EddieHubCommunity/LinkFree#3564]
### What would you like to share?

Right now, we are having to manually specify the directory path in this way:

`import xyz from "../../../components/XYZComponent"
`

With aliasing using jsconfig.json file, we can clean up the import syntax, and do something like,

`import xyz from 'components/XYZComponent'
`

Next.js supports it out of the box: https://nextjs.org/docs/advanced-features/module-path-aliases

**Comment by FrozenHearth** [comment]
Anyone wants to take up this issue?
CC @ManishBisht777 @eddiejaoude

**Comment by FrozenHearth** [comment]
I can take this up.

**Comment by SaraJaoude** [comment]
Great idea @FrozenHearth - I will assign this to you.

**Comment by FrozenHearth** [comment]
Thanks @SaraJaoude !
Just a question; do you recommend I add the jsconfig/tsconfig file or additionally also make changes to all files to replace `../../components `with `@/components`

**Comment by eddiejaoude** [comment]
> Thanks @SaraJaoude !
> 
> Just a question; do you recommend I ONLY add the jsconfig file OR additionally also make changes to all files to replace `../../components` with `@/components`

I think it would be great to have it all moved over in this pull request

**Comment by eddiejaoude** [comment]
This has now been completed
