### ISSUE TITLE
[DOCS] Difficulty tags in Docs Page not Capitalised

### ISSUE THREAD

**Issue by AbdurrahmanSogbesan** [EddieHubCommunity/LinkFree#3586]
### Description

The tags that display the difficulty of actions that can be taken are not capitalised. 

### Screenshots

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/64173776/212916645-85fa709f-2cf5-48f5-a1fd-eaa4d2d83d64.png">

**Comment by HarshDeep61034** [comment]
I can fix that !
