### ISSUE TITLE
Add a back button on profile Page

### ISSUE THREAD

**Issue by Sejal-16** [EddieHubCommunity/LinkFree#359]
### Description

There should be a back button on individual profiles page so that it enhances user experience. Once you have done viewing about one user , then you can press the back button and go ahead view other users:)

### Screenshots

![image](https://user-images.githubusercontent.com/65293021/135459906-68070f65-2334-442a-9fea-99e18819a7ef.png)

**Comment by nivendha** [comment]
Hi i would like to work ion this issue
