### ISSUE TITLE
Heading not aligned properly on mobile on discover page.

### ISSUE THREAD

**Issue by rohinish404** [EddieHubCommunity/LinkFree#3596]
### Description

In mobile view, the second heading(random profiles) is centered and has small text while as the heading below it are normally aligned left with bigger font size like they were aligned on the desktop. I think this creates some  
 alignment issue as the whole page is not looking consistent.

https://user-images.githubusercontent.com/92542124/213004999-73a9a30d-422d-4ff2-af80-5b8e14936dae.mov

**Comment by rohinish404** [comment]
I'll be working on this and soon make a pr.

**Comment by ashuthe1** [comment]
hi! I want to work on this issue, as it seems to be inactive, could you assign this issue to me.

**Comment by jainamthakkar** [comment]
hey, i'm new to open source and i want contribute on this issue can you please this issue to me ?

**Comment by rohinish404** [comment]
Hello, so i'd already made a pr regarding this issue.
