### ISSUE TITLE
[Thread] Suggestions of names of the project

### ISSUE THREAD

**Issue by stemount** [EddieHubCommunity/LinkFree#36]
Suggestions coming in hot.................... 3 ................2.................1

**Comment by nhcarrigan** [comment]
`EddiePodLinkTreeHub: The only social link you'll ever need (Powered by Angular)`

**Comment by stemount** [comment]
LinkFREE

**Comment by stemount** [comment]
![image](https://user-images.githubusercontent.com/150512/132901772-4f14dc8e-05d9-4c99-9c38-bbdbe539b8a1.png)

**Comment by vijay-jaisankar** [comment]
Thanks @stemount 
Sorry, I didn't see the notification about the duplicated issue earlier.

**Comment by schmelto** [comment]
think this one can be closed now :) if not feel free to reopen
