### ISSUE TITLE
[FEATURE] tags in discovery duplicate due to case sensitivity

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/LinkFree#3604]
### Description

The tags section in the discovery tab has duplicate entries du to case sensitivity.
I think all tags should be not case sensitiv in my opinion.

### Screenshots

![image](https://user-images.githubusercontent.com/30869493/213142200-1a75e7eb-6ad2-4f4c-a5cf-fe7ffaafd8b1.png)

**Comment by ChinmayMhatre** [comment]
I agree, I think keeping all tags lowercase would be the best option here. Maybe we could add a line in the docs regarding this as well later on.

**Comment by rwiteshbera** [comment]
Yes, @ChinmayMhatre, it would be better if all tags are in lowercase. I want to work on this issue.

**Comment by ManishBisht777** [comment]
#3469 Addresses the same issue so closing that one

 @rwiteshbera maybe the discussion there can help you a bit with this

**Comment by eddiejaoude** [comment]
The tags effects a few places

- user's profile
- discover page
- search results

Something like this issue suggests improving search https://github.com/EddieHubCommunity/LinkFree/issues/900

**Comment by SaraJaoude** [comment]
Good spot. Tags have now been removed from the Discovery page so I will close this issue.
