### ISSUE TITLE
[FEATURE] Add ellipsis in cards

### ISSUE THREAD

**Issue by FrozenHearth** [EddieHubCommunity/LinkFree#3636]
### Description

Right now, when there's a long text, we are cutting off some of it, which is fine, but I feel it would look better if we do something like Google, which adds the three dots at the end of the text (aka ellipsis)

Screenshot 1: Linkfree
Screenshot 2: Google search results

### Screenshots

<img width="1783" alt="Screenshot 2023-01-19 at 12 25 24 AM" src="https://user-images.githubusercontent.com/27160715/213270108-7429e546-97cb-4ea7-a7d3-d1e13009baf3.png">

<img width="689" alt="Screenshot 2023-01-19 at 12 27 50 AM" src="https://user-images.githubusercontent.com/27160715/213270119-b08f2d37-94cc-4d17-b058-bd03282599db.png">

**Comment by ManishBisht777** [comment]
We can add a `--webkit-line-clamp` property to do with just Css
or we can we append `...` in the text before rendering it to ui

**Comment by FrozenHearth** [comment]
@ManishBisht777 I feel the CSS approach would be better. However, Tailwind has no in-built classname for line-clamp. It does have a plugin though. But, a plugin feels overkill. If we can achieve it through vanilla CSS, I guess it would work. Let me know your thoughts on this.

**Comment by ManishBisht777** [comment]
> @ManishBisht777 I feel the CSS approach would be better. However, Tailwind has no in-built classname for line-clamp. It does have a plugin though. But, a plugin feels overkill. If we can achieve it through vanilla CSS, I guess it would work. Let me know your thoughts on this.

CSS seems a better option for me as well. the plugin and  a change in `global.css` both seem good to me

**Comment by FrozenHearth** [comment]
Sounds good. Let me take a look at this, and see if I can add a PR for this.

**Comment by FrozenHearth** [comment]
PR is added - #3798

**Comment by Vishrut19** [comment]
Is this issue open ?

**Comment by Vishrut19** [comment]
I think there is a need of more tweaking with the cards that can be done like a more border-radius and plus a little bit of box-shadow wouldn't hurt but it will give more nicer affect and look. what say? @eddiejaoude @FrozenHearth
