### ISSUE TITLE
[FEATURE] Markdown support for testimonials

### ISSUE THREAD

**Issue by LinuxGamer** [EddieHubCommunity/LinkFree#3638]
### Description

Add markdown support to testimonials to allow people to put emphasis on certain parts, like in the bio of the profiles.

### Screenshots

![61F5E5C5-D526-4CD8-8B8D-3BB6632D1EC1](https://user-images.githubusercontent.com/83363242/213289904-5420fd69-8291-4f67-984d-35c57d6ffd64.jpeg)

**Comment by nanthakumaran-s** [comment]
It's great to have it... Can I work on this issue?

**Comment by loftwah** [comment]
I like this one. Markdown is always welcome to me and it is my favourite thing to use.

**Comment by SandipPalit** [comment]
Can we add Markdown support for Link titles also?

**Comment by anirudhp26** [comment]
Hey there, back after a long time!, can i work on this issue?
