### ISSUE TITLE
Replace Avatars with Chip

### ISSUE THREAD

**Issue by Guneetsinghtuli** [EddieHubCommunity/LinkFree#364]
### Description

As the number of people creating their profiles is increasing it is becoming a bit difficult to find our IDs. We can try to replace the Avatars `only image` with Chip `image with the name`

### Screenshots

![Screenshot 2021-10-01 at 1 52 56 AM](https://user-images.githubusercontent.com/48324492/135525214-a28e5e9d-3e8c-4e63-a2e0-b11e9d831410.png)

### Additional information

I would like to take up this issue and work on it.

**Comment by eddiejaoude** [comment]
Great idea 👍

**Comment by nasrob** [comment]
@eddiejaoude @Guneetsinghtuli can you assign me this issue?

**Comment by Guneetsinghtuli** [comment]
@nasrob I was just about to make a PR within an Hour

**Comment by aaditya9899** [comment]
Hey can i work on this if its still available?
