### ISSUE TITLE
New Testimonial for Aadarsh Thakur

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#3643]
### Name

Aadarsh805

### Title

Open Source

### Description

Great Open Source collaborator and helping get more people into Open Source! Thanks Aadarsh for the support in EddieHub and for reviewing so many LinkFree pull requests!

**Comment by Aadarsh805** [comment]
Thanks, Eddie for the Cool testimonial, I'll keep collaborating to this awesome community
