### ISSUE TITLE
Better padding to the "Add testimonial" Button

### ISSUE THREAD

**Issue by ChinmayMhatre** [EddieHubCommunity/LinkFree#3668]
### Description
When we navigate to any user's page we get the add testimonial button at the bottom left as seen in the screenshot below
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51131670/213468869-317b8bab-1c44-4e21-99b2-bdc944f81545.png">

link to the page https://linkfree.eddiehub.io/eddiejaoude

I feel the button could use a bit of padding to the side. 

### Screenshots

Before
![image](https://user-images.githubusercontent.com/51131670/213438559-546800e8-c7ad-4938-a318-25d0d5c655d7.png)

After adding horizontal padding
![image](https://user-images.githubusercontent.com/51131670/213438771-c87518f1-4d62-4a6d-a1a7-2e7ed9756e87.png)

**Comment by FrozenHearth** [comment]
Can we have a common padding set for all buttons, if possible? That will make things consistent.

**Comment by PerkinsDan** [comment]
Where is this button?

**Comment by Sriparno08** [comment]
Hey, I would like to work on this!

**Comment by ChinmayMhatre** [comment]
> Where is this button?

My bad, let me update the question with the details

**Comment by PerkinsDan** [comment]
There are only two buttons like this. Not worth making a class

**Comment by ChinmayMhatre** [comment]
Hey @PerkinsDan , thank you for your input. Before making a PR we generally discuss with the maintainers. Also I saw someone had already asked to be assigned to the issue. Please consider this before creating a PR next time, Thank you!
