### ISSUE TITLE
Add support for website link

### ISSUE THREAD

**Issue by harshmathurx** [EddieHubCommunity/LinkFree#368]
### Description

Can we add support for website links and discord links like this?

![image](https://user-images.githubusercontent.com/58532371/135568081-6d9a0913-d346-4bd7-a4a5-aeb5190a236e.png)

**Comment by harshmathurx** [comment]
I would also like to work on this

**Comment by eddiejaoude** [comment]
Great idea, website link is important 👍

**Comment by eddiejaoude** [comment]
Assigned to you

**Comment by harshmathurx** [comment]
hey @eddiejaoude I made a PR #369

**Comment by krishguptadev** [comment]
I think this issue is fixed. Can this be closed?

**Comment by harshmathurx** [comment]
> I think this issue is fixed. Can this be closed?

yes, I'll close it
