### ISSUE TITLE
[DOCS] documentation

### ISSUE THREAD

**Issue by sudhanshu042004** [EddieHubCommunity/LinkFree#3688]
### Description

**Getting started is small** as compare to **Popular user Guides**

### Screenshots

![getting started](https://user-images.githubusercontent.com/122972603/213531101-c7818095-1900-421b-8a15-21f25a5aa508.png)

**Comment by khalidx3** [comment]
Hey is anyone working on it? Can it be assigned to me?

**Comment by HarshDeep61034** [comment]
@khalidx3 No one is assigned you can make a direct PR.

**Comment by khalidx3** [comment]
Alright Thankyou

**Comment by Ertan222** [comment]
> @khalidx3 No one is assigned you can make a direct PR.

Actually, ı think we should wait before open a PR when a issue don't have a assigned person. I think a maintainer going to be assing to khalid.

**Comment by DhirajGilda** [comment]
is this issue still open i would like to contribute on it

**Comment by khalidx3** [comment]
Yeah its open you can work on it

**Comment by Ertan222** [comment]
In EddieHub, we are trying to assign a issue to every person. Usually waiting for assignment is important @khalidx3 and @DhirajGilda. I know you are wants to contribute and do something good but we should wait for a repository maintainer. If no one sees for a long time, maybe mention is good solution for it but opening a PR without assignment break the purpose of that community.

**Comment by HarshDeep61034** [comment]
@Ertan222 I understand and respect your opinion but Eddie himself said that small changes like this can be done by direct PR theres no need even to open an issue for small changes like this.

**Comment by Vaibhavsah1122003** [comment]
Pls comment if any changes needed
