### ISSUE TITLE
[FEATURE] GitHub Action to check profile filename matches the GitHub username

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#3692]
### Description

We have a label `LGTM` added when the author of the profile creates/edits their profile and the file name is the exact match

But this can get missed, so it would be great to have a GitHub Action that fails if these checks are not matched...

- is the author of the PR the owner of the file, for example for my GitHub user `eddiejaoude`, my file would have to match exactly to `data/eddiejaoude.json` (case sensitive)

**Comment by dan-mba** [comment]
I will take a look at this.

**Comment by eddiejaoude** [comment]
Awesome, thanks Dan! 🔥
