### ISSUE TITLE
Sort is not working with the view count

### ISSUE THREAD

**Issue by SandipPalit** [EddieHubCommunity/LinkFree#3702]
### Description

When I am sorting my Links section, it is sorting the links in Alphabetical order, but the view counts are not getting sorted along with the title. Please check the screenshots for more details

### Screenshots

![image](https://user-images.githubusercontent.com/48781286/213667923-7992cd3c-0f6c-4c81-9ac7-760724e675e7.png)
![image](https://user-images.githubusercontent.com/48781286/213668056-d6ad6a09-09f7-444a-aa99-925c8dff6383.png)

**Comment by ManishBisht777** [comment]
@SandipPalit  Thanks for contributing but this issue is already been made ( #3434 ) and a pr #3496 fixes that.

you can add a review to the proposed solution #3496 though and close this issue, thanks :)

**Comment by amandamartin-dev** [comment]
Hello all! Closing this issue as per the comment by @ManishBisht777 as a duplicate issue.  thank you both for contributing!
