### ISSUE TITLE
[FEATURE] Add instagram hover link

### ISSUE THREAD

**Issue by RoshanMhatre** [EddieHubCommunity/LinkFree#372]
### Description

Hey Eddie, I want to add the Instagram hover link.
Please assign the Hacktoberfest label to it and assign this issue to me.

**Comment by RoshanMhatre** [comment]
Please accept my PR #373 so that I can make another one for this issue.

**Comment by Vyvy-vi** [comment]
Hey @RoshanMhatre 
We appreciate the enthusiasm, _however_ it would be appreciated if this issue had more detail.
