### ISSUE TITLE
JSON syntax checker insufficient error log 

### ISSUE THREAD

**Issue by ChinmayMhatre** [EddieHubCommunity/LinkFree#3736]
### Description

This is an extension to the dicussion on the #contributor-support on the discord server.

whenever an actions fails on linkfree for example a json error. this is the error log. This doesn't seem to be very clear about the line error.
![image](https://user-images.githubusercontent.com/51131670/213848642-cc8325b7-4f50-45c4-8d3d-b02405ed5ab9.png)

A discussion was happening on creating a custom action for the json validation.

I looked into this and had these observations.

1. Whenever a JSON file is required in javascript. `JSON.parse()` is executed. If the file has a syntax error an exception is thrown. 
![image](https://user-images.githubusercontent.com/51131670/213848829-aaa7f94b-9603-4098-872a-1df544c7163e.png)
However position 318 isn't very clear as to what the error is. The exception is part of the `SyntaxError` object. 

However `SyntaxError.lineNumber` doesn't work on all browser. It didn't work on my browser.
![image](https://user-images.githubusercontent.com/51131670/213848889-1f7b39c8-3045-4ca1-b0be-55e31d867b65.png)

I cannot really find a work around to this. 

2. I found a library [jsonlint](https://www.npmjs.com/package/jsonlint) 
Error thrown by this library gives out the line number but it requires a json string. Since the `SyntaxError` is thrown while requiring the code doesn't reach here.
![image](https://user-images.githubusercontent.com/51131670/213848975-d2f74d0a-f1a8-4044-84de-7bbf55afee3f.png)

Maybe I am overlooking something? Would like any feedback.

My suggestions if this doesn't work would be to add a link to https://jsonlint.com/  in the docs it is a website for checking json syntax errors.

**Comment by ChinmayMhatre** [comment]
Hey @eddiejaoude could you take a look at this. We had a discussion about this on discord about the error log of the json-checker not being clear. I looked into it a bit.

**Comment by eddiejaoude** [comment]
Sorry @ChinmayMhatre I missed this. Maybe adding a link to that website is a good first step in the docs and/or if that Action fails we can get the Action to add a comment with a link to that website

**Comment by ChinmayMhatre** [comment]
> Sorry @ChinmayMhatre I missed this. Maybe adding a link to that website is a good first step in the docs and/or if that Action fails we can get the Action to add a comment with a link to that website

Both seem like a good idea. I'll open a new issue for add the link to the doc. Also maybe i could rename this issue for the action that comments the link and that could continue here?

**Comment by MAYANKpandey14** [comment]
Hey, is someone working on this currently?

**Comment by SaraJaoude** [comment]
Thanks for raising. 

This Pull Request https://github.com/EddieHubCommunity/LinkFree/pull/4211 will solve the need for this Issue so I will close.
