### ISSUE TITLE
New Testimonial for Manish Tyagi 

### ISSUE THREAD

**Issue by the-amazing-atharva** [EddieHubCommunity/LinkFree#3753]
### Name

money8203

### Title

A Dedicated Open Source Advocate and Valuable  Member of Tech Twitter 

### Description

I've had the pleasure of following Manish on Twitter for some time now and I cannot express enough how much his tweets, threads and open source advocacy have helped me in my own journey as a learner. His valuable information and insights have not only helped me in my work, but also inspired me to contribute more to the open source community. He is truly a role model for the tech community and I always look forward to reading his posts.

**Comment by money8203** [comment]
Thank you so much Atharva, means a lot to me. 🙏🏻

**Comment by the-amazing-atharva** [comment]
Your Welcome

Keep sharing your info everywhere
