### ISSUE TITLE
New Testimonial for Pradumna Saraf

### ISSUE THREAD

**Issue by tobySolutions** [EddieHubCommunity/LinkFree#3760]
### Name

Pradumnasaraf

### Title

A mentor to GenZ Techies

### Description

Pradumna has always been an inspiration to GenZ techies like me that had never found open source interesting. I went from being a nobody in the open-source community to a maintainer of 2 very big open-source projects in the 4c community!

Pradumna is such an inspiration to me when it comes to open source and he's one of the people I credit for everything I have achieved in Open source today

**Comment by Pradumnasaraf** [comment]
Thank you so much for the kind words and a wonderful testimonial

**Comment by tobySolutions** [comment]
Pleasure is all mine Pradumna!! Everything I stated in the testimonial is facts. You know that.
