### ISSUE TITLE
[BUG] LinkedIn not matched

### ISSUE THREAD

**Issue by AbhijithGanesh** [EddieHubCommunity/LinkFree#377]
### Description

Linkedin logo is not matched to the tab. 

I shall patch it soon so please assign me to this!

**Comment by eddiejaoude** [comment]
Assigned

**Comment by AbhijithGanesh** [comment]
Thank you eddie

**Comment by eddiejaoude** [comment]
Sorry @AbhijithGanesh I forgot this was assigned to you 🤦‍♂️

**Comment by AbhijithGanesh** [comment]
It's okay, it's chill. It was Patched to make the comm better. It's okay
