### ISSUE TITLE
 duplicate json file

### ISSUE THREAD

**Issue by qwe123coder** [EddieHubCommunity/LinkFree#378]
### Description

there are 2 profiles for the same person 
with the same links

### Screenshots

![image](https://user-images.githubusercontent.com/72848513/135580368-e73a44a1-5bbe-4e6c-bb2a-a5fa75c0e7b0.png)

### Additional information

to fix this bug we have to remove the  andres-bermeo.json file

**Comment by ItsMeIshan** [comment]
hey, @qwe123coder  there are two files in of the name which one do we have to remove?
here's the ss.
![Screenshot 2021-10-01 at 12 52 56 PM](https://user-images.githubusercontent.com/65131563/135581537-41614a0d-ba19-475a-bded-72344e671941.png)
