### ISSUE TITLE
Update all logging to use new logging method

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#3792]
### Description

We have `console.log` or `console.error` in many places, but now we have a logging function, we should use that and replace every `console.*`

The function can be found in this file `config/logger.js` , and an example of it's usage can be found in `https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/api/users/%5Busername%5D/index.js#L25`

**Comment by nanthakumaran-s** [comment]
Can you please explain a bit? I also like to contribute to this issue...

**Comment by SaraJaoude** [comment]
The description has been updated, please recheck.

**Comment by Vishrut19** [comment]
Hey! Can I work on this issue ?

**Comment by SaraJaoude** [comment]
> Hey! Can I work on this issue ?

@Vishrut19 we are only assigning one issue per person at the moment.  I can see that you have been assigned and are still working on: https://github.com/EddieHubCommunity/LinkFree/issues/3232

**Comment by sansarmaske** [comment]
I would like to work on this.

**Comment by sansarmaske** [comment]
Thank you. I will get started on this!
