### ISSUE TITLE
[FEATURE] Profile last updated

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#3803]
### Description

- last updated (excluding increments)

**Comment by Ertan222** [comment]
Last updated is good for knowing this user still using/updating this profile but why we need update counter?

**Comment by Ananya2001-an** [comment]
@eddiejaoude @Ertan222 Yeah I too feel showing information for last update is more than enough because adding an update counter as well will just increase redundancy.

**Comment by Ananya2001-an** [comment]
@eddiejaoude I think we have to write a GitHub Action for this which will keep track of merge commits involving change to the json files. When the PR is merged it will then add the date-time information to the respective profile's document in the database. Not sure if this is the right way to do it. What do you think?

**Comment by ChayanSD** [comment]
Give me some information or documentation . I want to learn for contribute to this project.

**Comment by Avi-88** [comment]
Hi @eddiejaoude , @Ananya2001-an  , I'm not sure if this is correct but will it work if we read the last modified date of the file from its metadata ? We can get the file name from the url params , do let me know your thoughts on this, thanks

**Comment by ChinmayMhatre** [comment]
> Give me some information or documentation . I want to learn for contribute to this project.

Hey @ChayanSD , here is the link to the documentation for the project https://linkfree.eddiehub.io/docs, you can also look at open issues or create new issue if you find any feature missing or come across a bug. Thank you!

**Comment by amandamartin-dev** [comment]
Can I offer a suggestion that showing last updated could be optional?  For example, if I am using linkfree primarily as an aggregate for my socials, I may rarely (if ever) update my profile and then having the date could imply it is stale even though I am not updating because I do not need to.

**Comment by Ananya2001-an** [comment]
> Can I offer a suggestion that showing last updated could be optional?  For example, if I am using linkfree primarily as an aggregate for my socials, I may rarely (if ever) update my profile and then having the date could imply it is stale even though I am not updating because I do not need to. 

I too feel the same.

**Comment by Avi-88** [comment]
> Can I offer a suggestion that showing last updated could be optional? For example, if I am using linkfree primarily as an aggregate for my socials, I may rarely (if ever) update my profile and then having the date could imply it is stale even though I am not updating because I do not need to.

Yeah I agree

**Comment by wadeedmadni** [comment]
> Can I offer a suggestion that showing last updated could be optional? For example, if I am using linkfree primarily as an aggregate for my socials, I may rarely (if ever) update my profile and then having the date could imply it is stale even though I am not updating because I do not need to.

Exactly

**Comment by eddiejaoude** [comment]
I think I will close this for now, we have the field being saved now
