### ISSUE TITLE
New Testimonial for Eddie Jaoude

### ISSUE THREAD

**Issue by Ertan222** [EddieHubCommunity/LinkFree#3807]
### Name

eddiejaoude

### Title

You want to learn Open Source and Github? Eddie is answer!

### Description

Eddie is important for my developer career. Helped me about my open source passion and finally ı become a open source developer. Still learning from him about Gtihub, Git and so many things. Thanks Eddie for everything :star2:

**Comment by eddiejaoude** [comment]
Thank you @Ertan222 🎉

**Comment by Ertan222** [comment]
**Thank you** Eddie for everything ^^ @eddiejaoude
