### ISSUE TITLE
I opened a Pull request Please check it.

### ISSUE THREAD

**Issue by priyankarpal** [EddieHubCommunity/LinkFree#3847]
### What would you like to share?

Hi, Developers I opened a Pull request for my linkfree profile, please check it. **(priyankarpal-patch-1)**
![Screenshot from 2023-01-23 20-55-38](https://user-images.githubusercontent.com/88102392/214078635-238233cd-6278-4b63-828f-5eef2125f978.png)

**Comment by ChinmayMhatre** [comment]
Hey @priyankarpal , I think you accidentally created a PR to your fork's main branch. When creating a PR what you need. to do is. create a PR between the branch in which you made the changes `priyankarpal-patch-1` in this case and the eddiehub community's linkfree's main branch.

**Comment by ChinmayMhatre** [comment]
In case you have any difficult feel free to ping me here.

**Comment by priyankarpal** [comment]
hi, @ChinmayMhatre thanks for finding my error. I resolve it. I created a new branch & created a Pull request. I hope now it's ok. 

![Screenshot from 2023-01-23 23-39-35](https://user-images.githubusercontent.com/88102392/214116782-f4b5b1c5-7b3e-4fcb-bece-2dadbd22bad3.png)
![Screenshot from 2023-01-23 23-35-01](https://user-images.githubusercontent.com/88102392/214116790-940da890-e3a7-44dc-b4cd-cc79c98d9007.png)

**Comment by priyankarpal** [comment]
# is there any problem? 

![Screenshot from 2023-01-23 23-42-10](https://user-images.githubusercontent.com/88102392/214117287-7c4d0571-186c-45f4-889d-c8fa3c761fa8.png)

**Comment by ChinmayMhatre** [comment]
@priyankarpal Any problems can be discussed in the PR itself. I'll review it there. You can close this issue . by clicking the close issue button below the textfield
