### ISSUE TITLE
[FEATURE] Add filter tags on Search page as well

### ISSUE THREAD

**Issue by Ananya2001-an** [EddieHubCommunity/LinkFree#3849]
### Description

Right now we are allowing users to click on tags in the discover page and then it redirects them to the search page with the found results but this introduces a bit of time lag which is kind of annoying. Why not add these tags on the search page as well so that it's convenient for users to search profiles with the help of it rather than just making them type it out in the search bar?

### Screenshots

![image](https://user-images.githubusercontent.com/55504616/214089758-73e1a127-0346-4b09-84cc-02e3a54cb252.png)

### Additional information

I would like to get assigned for this issue.

**Comment by ManishBisht777** [comment]
On the search page you can directly search javascript or any other other language you want to search it will show results for that.
Adding `tags` ln the search page like discover would distrub the layout on the search page in my opinion as we don't have a proper ui for that.
So may be we can first improve the ui on the discover page then implement the same on
the search page.

@eddiejaoude any suggestions?

**Comment by Ananya2001-an** [comment]
@ManishBisht777 yeah I guess we should do that.

**Comment by Ananya2001-an** [comment]
Yeah I agree on this. I thought the same.

**Comment by ManishBisht777** [comment]
Maybe instead of tag list we can add a filter option And move tags in that
@Ananya2001-an @abelparayil

**Comment by Ananya2001-an** [comment]
@ManishBisht777 yeah that sounds good

**Comment by Ananya2001-an** [comment]
@ManishBisht777 can I work on this ?

**Comment by Ananya2001-an** [comment]
Moreover I have noticed that in the search bar we can only search 1 tag but we should allow users to be able to search profiles with combination of tags like maybe javascript  + react ....

**Comment by ManishBisht777** [comment]
> Moreover I have noticed that in the search bar we can only search 1 tag but we should allow users to be able to search profiles with combination of tags like maybe javascript + react ....

sounds good.  you can work on that

**Comment by ManishBisht777** [comment]
@eddiejaoude you can assign this to @Ananya2001-an 

@Ananya2001-an let me know if you need any help implementing the same

**Comment by Ananya2001-an** [comment]
@ManishBisht777 Okay. I have already started working on this.

**Comment by Ananya2001-an** [comment]
> @eddiejaoude you can assign this to @Ananya2001-an 
> 
> @Ananya2001-an let me know if you need any help implementing the same

Yeah sure I will.

**Comment by eddiejaoude** [comment]
Great discussion and collaboration everyone 👍 

I have assigned it to @Ananya2001-an 

I think we can add the tags at the top similar to the way it is on the discover page, then as suggested people can click on the directly

**Comment by Ananya2001-an** [comment]
@eddiejaoude @ManishBisht777 created PR for this issue. Kindly review.
