### ISSUE TITLE
[FEATURE] Consider removing the bubble

### ISSUE THREAD

**Issue by adityaraute** [EddieHubCommunity/LinkFree#387]
### Description

The bubble, as can be seen in the screenshot, displays the number of links on the page. However, I wonder if it is of any use to the user. 
I will suggest to consider getting rid of this bubble altogether.

### Screenshots

![image](https://user-images.githubusercontent.com/43912470/135600713-d12cf24a-04ee-42df-b2d2-ef2095470a9f.png)

**Comment by sudhay23** [comment]
@adityaraute Can I work on this?

**Comment by adityaraute** [comment]
I am not the moderator so can't assign you

**Comment by schmelto** [comment]
> @adityaraute Can I work on this?

done

**Comment by amittri1025** [comment]
These bubbles would be useful if it could be seen on homepage by doing hover on profiles so that one can know how many profiles these guy have , without clicking on individual profile

**Comment by amittri1025** [comment]
hello @schmelto , this project is not participating in Hacktoberfest , what to do now ?

**Comment by iatharva** [comment]
Well, you can still contribute, cause it's about collaboration.

**Comment by krishguptadev** [comment]
Yeah thanks... This is really needed!

**Comment by krishguptadev** [comment]
> hello @schmelto , this project is not participating in Hacktoberfest , what to do now ?

Only issues labelled "Hacktoberfest" are counted but yet it's about collaboration things like Hacktoberfest are only small festivals of opensource not the reason for opensource.

**Comment by Vyvy-vi** [comment]
the suggestion made by @amittri1025 is similar to what's proposed in #191

**Comment by code3z** [comment]
@Vyvy-vi Can I try this? I'll make a Figma design first.

**Comment by code3z** [comment]
Should the profile card display the profile icons (github, twitter, personal site)? What about the username?

**Comment by adityaraute** [comment]
This issue is only for removing the bubble

**Comment by nathgoutam93** [comment]
Hey there, looks like this issue is no longer exist . So we should close this issue . right?

**Comment by adityaraute** [comment]
Those bubbles are visible after hovering. Wouldn't say doesn't exist.

**Comment by nathgoutam93** [comment]
> Those bubbles are visible after hovering. Wouldn't say doesn't exist.

This bubble issue was about the bubble in the user profile not the user chips in home page . 

This issue was fixed in a PR I made and some of us decided to add the bubble in the chips instead .

**Comment by adityaraute** [comment]
alrighty then
