### ISSUE TITLE
Add common things to the .gitignore (IDEs)

### ISSUE THREAD

**Issue by stemount** [EddieHubCommunity/LinkFree#39]
Use a tool like toptal https://www.toptal.com/developers/gitignore?templates=visualstudiocode,phpstorm+all

**Comment by StarTrooper08** [comment]
Hey ,can I take this issue?

**Comment by rohan-kulkarni-25** [comment]
Yeah That is good idea !! I think for Now 
- Visual Studio Code 
- Visual Studio 
- Sublime 

These will be enough we can update later if any

**Comment by voidz7** [comment]
> Yeah That is good idea !! I think for Now
> 
>     * Visual Studio Code
> 
>     * Visual Studio
> 
>     * Sublime
> 
> 
> These will be enough we can update later if any

Vim 📳

**Comment by StarTrooper08** [comment]
Alright
