### ISSUE TITLE
[FEATURE] Add Loader

### ISSUE THREAD

**Issue by rahulpandey70** [EddieHubCommunity/LinkFree#3900]
### Description

We can add loader, When users navigate to different routes. So application look more user friendly. When i click on different routes i feel like nothing is happing.

**Comment by ManishBisht777** [comment]
Good idea @rahulpandey70

**Comment by prajapati55** [comment]
Hey, I want to try this.

**Comment by rahulpandey70** [comment]
> Hey, I want to try this.

Okay, try it

**Comment by consolexyz** [comment]
ohh i wanted to try this

**Comment by SaraJaoude** [comment]
Blocking this Issue as waiting for the full upgrade to NextJS 13.

**Comment by MadhuSaini22** [comment]
@eddiejaoude is this issue is blocked? I would be happy to work on this :)

**Comment by SaraJaoude** [comment]
> @eddiejaoude is this issue is blocked? I would be happy to work on this :)

@MadhuSaini22 please avoid tagging a specific maintainer - all maintainers receive project notifications. 

This feature could be done now, but the Issue will remain blocked until we catch up with open pull requests and these changes will cause major conflicts. 

I would suggest checking the Contributing Guidelines and familiarising yourself with the Labels we use on this project.  An Issue will be ready to be worked on when it has the label `status: ready for dev`.

**Comment by dheerajmw** [comment]
I want to work on this project, its an easy fix.

**Comment by eddiejaoude** [comment]
@dheerajmw please read the previous message to yours

**Comment by jtejederabit** [comment]
I will also add to not limit the loader only on navigation and extend the feature when fetching data. For example in Search page while writing in the input text or selecting tags it also take few seconds to display the results.

**Comment by eddiejaoude** [comment]
I think we can close this now as our pages are much faster
