### ISSUE TITLE
[FEATURE] Embed quickstart YouTube video into quickstart guide

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#3905]
### Description

At the top of the quickstart docs it would be good to embed the YouTube video for it https://linkfree.eddiehub.io/docs/quickstart

YouTube video https://www.youtube.com/watch?v=05HEeCQSKRE

**Comment by Ertan222** [comment]
I want try it Eddie, can you assign me?

**Comment by eddiejaoude** [comment]
Sure @Ertan222

**Comment by sidharthviz** [comment]
Hey  @eddiejaoude  Can i embed the video in the documentation file as i was doing so but apparently it's already assign to someone.  Please allow me if i can make changes.

**Comment by sidharthviz** [comment]
> Sure @Ertan222

Can i work on this ? @eddiejaoude

**Comment by eddiejaoude** [comment]
@sidharthviz please see the comments and timeline above, it was already requested recently and assigned

**Comment by sidharthviz** [comment]
> @sidharthviz please see the comments and timeline above, it was already requested recently and assigned

Okay..got it.

**Comment by Ertan222** [comment]
@eddiejaoude I am having a problem with tests. Don't know what is the reason and while having a problem in my local repo, maybe ı shouldn't open a PR for production. Also, this problem going to block my feature tests. Maybe you should assign to another person. Sorry for that, after ı fix the problem, going to contribute again :)

**Comment by sidharthviz** [comment]
can i work on it ? @schmelto

**Comment by sidharthviz** [comment]
> @eddiejaoude I am having a problem with tests. Don't know what is the reason and while having a problem in my local repo, maybe ı shouldn't open a PR for production. Also, this problem going to block my feature tests. Maybe you should assign to another person. Sorry for that, after ı fix the problem, going to contribute again :)

Hey @Ertan222 meanwhile you can try with Gitpod setup that might work maybe for you.

**Comment by Ertan222** [comment]
> > @eddiejaoude I am having a problem with tests. Don't know what is the reason and while having a problem in my local repo, maybe ı shouldn't open a PR for production. Also, this problem going to block my feature tests. Maybe you should assign to another person. Sorry for that, after ı fix the problem, going to contribute again :)
> 
> Hey @Ertan222 you can try with Gitpod setup that might work maybe for you.

I forget the gitpod, you are right. Thanks, trying right now :)

**Comment by Ertan222** [comment]
There was a problem with test and Dan fixed it. I am going work on it again.

**Comment by sidharthviz** [comment]
> > > @eddiejaoude I am having a problem with tests. Don't know what is the reason and while having a problem in my local repo, maybe ı shouldn't open a PR for production. Also, this problem going to block my feature tests. Maybe you should assign to another person. Sorry for that, after ı fix the problem, going to contribute again :)
> > 
> > 
> > Hey @Ertan222 you can try with Gitpod setup that might work maybe for you.
> 
> I forget the gitpod, you are right. Thanks, trying right now :)

Great..👍🏼

**Comment by SaraJaoude** [comment]
Closing as Pull Request has been merged.
