### ISSUE TITLE
thebarshablog profile can't be found in the data directory

### ISSUE THREAD

**Issue by thebarshablog** [EddieHubCommunity/LinkFree#3907]
![Screenshot (824)](https://user-images.githubusercontent.com/103309340/214352322-033c5bd6-9438-43ed-9ca5-a7043d5450e5.png)

Kindly share the reason behind truncating 1000 files and where do I recover my file from?

**Comment by ManishBisht777** [comment]
@thebarshablog There is a limit to files that GitHub can show on the UI

Your profile is still present in the database you can check all the files by cloning the fork into your local environment

![image](https://user-images.githubusercontent.com/89926834/214358419-95acf9dd-e8ca-429e-b5a1-f21bc3b0000d.png)

**Comment by ManishBisht777** [comment]
@thebarshablog as your file name is your username you can find
it by appending your GitHub profile Name to the `https://github.com/EddieHubCommunity/LinkFree/tree/main/data/`

Here's the Link 
https://github.com/EddieHubCommunity/LinkFree/tree/main/data/thebarshablog

**Comment by ManishBisht777** [comment]
let me know if that helps :)

**Comment by thebarshablog** [comment]
@ManishBisht777 Thanks for pointing out. However, the above ones contain my events and testimonials. Where do I find my original file apart from events and testimonials?

**Comment by ManishBisht777** [comment]
@thebarshablog  you can append .json afterward to access your JSON file as well
https://github.com/EddieHubCommunity/LinkFree/blob/main/data/thebarshablog.json

**Comment by thebarshablog** [comment]
> @thebarshablog you can append .json afterward to access your JSON file as well https://github.com/EddieHubCommunity/LinkFree/blob/main/data/thebarshablog.json

I sincerely appreciate your help.
