### ISSUE TITLE
[DOCS] Updating Profile Instructions

### ISSUE THREAD

**Issue by ManishBisht777** [EddieHubCommunity/LinkFree#3909]
### Description

As some people only use GitHub UI for creating and updating profiles and the UI can only show only first 1000 files so profiles that are at the end of the alphabetic order do not appear in that list if someone wanted to update it

#3907

**Comment by Ertan222** [comment]
We need to add an guide to find their directories and json files in documentation right? is it your propose?

**Comment by ChinmayMhatre** [comment]
The file can always be searched with the `go to file` button.
![image](https://user-images.githubusercontent.com/51131670/214366950-533f20ce-5690-494c-b421-f7e57d327243.png)

**Comment by ManishBisht777** [comment]
> The file can always be searched with the `go to file` button. ![image](https://user-images.githubusercontent.com/51131670/214366950-533f20ce-5690-494c-b421-f7e57d327243.png)

it didn't know that :cry:  But yes mentioning it int he docs as well will be good
