### ISSUE TITLE
[DOCS] Add a link to jsonlint in the quickstart guide

### ISSUE THREAD

**Issue by ChinmayMhatre** [EddieHubCommunity/LinkFree#3914]
### Description

Add link to https://jsonlint.com/ in the quickstart guide before point 10 and explain.
This is a website for the contributors to check the json file for any linting error before committing.
Feel free to add the content according to your best knowledge.

Link to the quickstart page : https://linkfree.eddiehub.io/docs/quickstart

### Screenshots

My suggestion would be adding this before point 10.
![image](https://user-images.githubusercontent.com/51131670/214369182-b2780aa5-b219-4419-b318-2a4637e5e76c.png)

**Comment by ChinmayMhatre** [comment]
Hey @Sriparno08 , I won't be able to assign it to you, but you are welcome to take this. Thank you!

**Comment by Sriparno08** [comment]
Alright 👍

**Comment by MAYANKpandey14** [comment]
Hey @Sriparno08 are you working on this ?

**Comment by Sriparno08** [comment]
> Hey @Sriparno08 are you working on this ?

I was about to start, but if you want, you can go ahead!

**Comment by ChinmayMhatre** [comment]
Hey @MAYANKpandey14 , are you working on this? Do you need any help?

**Comment by MAYANKpandey14** [comment]
> > Hey @Sriparno08 are you working on this ?
> 
> I was about to start, but if you want, you can go ahead!

Yes , I want to work on this ?

**Comment by MAYANKpandey14** [comment]
> Hey @MAYANKpandey14 , are you working on this? Do you need any help?

I will start today and if I'll need any help I will ask thank you .

**Comment by MAYANKpandey14** [comment]
Hey, @ChinmayMhatre  is this OK .

![Screenshot 2023-01-27 at 2 44 13 PM](https://user-images.githubusercontent.com/94740455/215050473-cf874ff5-56dd-4e79-8486-dee34f291022.png)

**Comment by MAYANKpandey14** [comment]
I have a question also @ChinmayMhatre.
I am using Gitpod because of my old Mac , is it ok or  I'll  have to switch to  local environment.

**Comment by ChinmayMhatre** [comment]
Hey @MAYANKpandey14 , I think we could highlight the sentence using. 

**NOTE**

add the sentence here

---


What do you think?

**Comment by ChinmayMhatre** [comment]
> I have a question also @ChinmayMhatre.
> I am using Gitpod because of my old Mac , is it ok or I'll have to switch to local environment.

If you don't want to do the local environment setup , since this is a small change you could do it on GitHub itself. If you want help with this please feel free to ping me here.

**Comment by ChinmayMhatre** [comment]
> Hey, @ChinmayMhatre is this OK .
> 
> ![Screenshot 2023-01-27 at 2 44 13 PM](https://user-images.githubusercontent.com/94740455/215050473-cf874ff5-56dd-4e79-8486-dee34f291022.png)

I think we could simplify the sentence like . Please use the JSON Lint (add the link into the word) to check if your Json file is valid before creating the PR.

**Comment by MAYANKpandey14** [comment]
Yeah sure , we can reframe it as `Please use JSON Lint (Link into this word) to check if your JSON file is Error free before committing your pull request.`

> > Hey, @ChinmayMhatre is this OK .
> > ![Screenshot 2023-01-27 at 2 44 13 PM](https://user-images.githubusercontent.com/94740455/215050473-cf874ff5-56dd-4e79-8486-dee34f291022.png)
> 

> I think we could simplify the sentence like . Please use the JSON Lint (add the link into the word) to check if your Json file is valid before creating the PR.

**Comment by MAYANKpandey14** [comment]
I have reframed the sentence as suggested by @ChinmayMhatre .
Here is before and after to get a better understanding of the changes we have done .

**BEFORE** 

![Screenshot 2023-01-27 at 11 33 05 PM](https://user-images.githubusercontent.com/94740455/215161447-bddbc9d3-393d-4353-9b85-7cf649f58c61.png)

**AFTER**

![Screenshot 2023-01-27 at 11 32 25 PM](https://user-images.githubusercontent.com/94740455/215161720-13e1a4db-beaf-4a0a-a394-765dbc358c17.png)

**Comment by ChinmayMhatre** [comment]
> Hey @MAYANKpandey14 , I think we could highlight the sentence using.
> 
> **NOTE**
> 
> add the sentence here
> 
> What do you think?

Please use a style like this to highlight the sentence. After doing please create the PR. Rest changes can be done there. Thanks!

**Comment by MAYANKpandey14** [comment]
![Screenshot 2023-01-27 at 11 49 31 PM](https://user-images.githubusercontent.com/94740455/215164110-18a06bc5-fa99-45ca-b687-057f96e24176.png)

Instead using two lines , i think this is enough to get reader's attention.

**Comment by ChinmayMhatre** [comment]
> ![Screenshot 2023-01-27 at 11 49 31 PM](https://user-images.githubusercontent.com/94740455/215164110-18a06bc5-fa99-45ca-b687-057f96e24176.png)
> 
> @ChinmayMhatre Instead using two lines , i think this is enough to get reader's attention.

Feel free to add it according to your best knowledge 👍🏻

**Comment by MAYANKpandey14** [comment]
@ChinmayMhatre I am using Gitpod , how do I create a pull request .

**Comment by MAYANKpandey14** [comment]
![Screenshot 2023-01-28 at 12 04 14 AM](https://user-images.githubusercontent.com/94740455/215167134-fe2fa2a6-8bc7-4628-b427-c16edb0ad2c9.png)


Should I go forward with the commit button.

**Comment by MAYANKpandey14** [comment]
Thank you @ChinmayMhatre for the helping me in my first contribution, hoping to contribute more .

**Comment by ChinmayMhatre** [comment]
@MAYANKpandey14 Could you close this issue as the PR has been merged.

A tip for next time. When creating a PR you can say "Closes #[Issue number]" This will close the Issue when the PR is merged Automatically.

**Comment by MAYANKpandey14** [comment]
> @MAYANKpandey14 A tip for next time. When creating a PR you can say "Closes #[Issue number]" This will close the Issue when the PR is merged Automatically.

Yeah sure , I'll make sure to close the issue next time thanks for the tip.
