### ISSUE TITLE
[DOCS] Readme can be improved

### ISSUE THREAD

**Issue by Aliencoder-75** [EddieHubCommunity/LinkFree#393]
### Description

Readme is not properly organized which makes it hard to understand, and it feels a bit cluttered.

### Screenshots

![image](https://user-images.githubusercontent.com/87473057/135634945-cfc9e859-3ea0-4604-a07b-80d42419b515.png)

**Comment by Dhananjaymahajan2001** [comment]
hwllo i would like to work on this issue so could you assign it to me

**Comment by Dhananjaymahajan2001** [comment]
#397 
made some improvements
- YouTube link simplified
- note for participants in a separate section
