### ISSUE TITLE
New Testimonial for Madhu Saini

### ISSUE THREAD

**Issue by loftwah** [EddieHubCommunity/LinkFree#3934]
### Name

MadhuSaini22

### Title

Highly Promising Full-Stack MERN Developer

### Description

Madhu Saini is an up-and-coming full-stack developer focusing on the MERN stack. Though I have yet to have the opportunity to work with her directly, I have heard great things about her skills and dedication to her craft. Madhu firmly understands the latest technologies and can deliver high-quality code. I look forward to the opportunity to work with Madhu in the future, and I'm confident that her skills and passion for development will make her an asset to any team.

**Comment by gurjeetsinghvirdee** [comment]
I think the testimonial workflow not working or the rate limit was exceeded @loftwah

**Comment by loftwah** [comment]
Is there anything wrong with the `json`?

**Comment by dan-mba** [comment]
The error message is
```
Invalid string: control characters from U+0000 through U+001F must be escaped
```

I think the newline is causing a problem

**Comment by loftwah** [comment]
Cool I'll fix it soon

**Comment by eddiejaoude** [comment]
I removed the line break and the GitHub Action has re-run

**Comment by loftwah** [comment]
Thanks Eddie I'm not sure how I managed to do that.

**Comment by MadhuSaini22** [comment]
OMG, you made my day @loftwah ❤❤
Thank you so much for your kind words, It's my first testimonial and it's boom💥 I appreciate your words :)

**Comment by MadhuSaini22** [comment]
Oops testimonial is by @eddiejaoude 😲😭
This is unbelievable for me❤❤❤❤
I haven't even thought of that Open Source God can add a testimonial for me!!
Tons of Thanks to you Eddie :)
Lots of love and respect for you!!

**Comment by eddiejaoude** [comment]
@MadhuSaini22 sorry it was from Dean, the GitHub took my username because I edited the issue
