### ISSUE TITLE
Fix social media preview of LinkFree profile

### ISSUE THREAD

**Issue by aqib-m31** [EddieHubCommunity/LinkFree#3950]
### Description

I shared my linkfree profile URL with a friend and I spotted - in profile preview the bio tag appears as markdown.
It would be good if it appears as simple text without the markdown symbols.

### Screenshots

![WhatsApp Image 2023-01-25 at 13 40 53](https://user-images.githubusercontent.com/63852213/214514226-32bf33c9-4791-47ae-ad0f-2a978a051e1b.jpg)
Have a look below my name - asterisk symbols also appear.

### Additional information

I don't know is it a bug or whatever! I thought it could be improved - so I learned how to refer an issue in an open source project!

**Comment by gurjeetsinghvirdee** [comment]
It's not a bug, you have to edit your data @aqib-m31 

<img width="371" alt="Screenshot 2023-01-25 142126" src="https://user-images.githubusercontent.com/73753957/214519755-43a21bb1-e9ed-4a60-8214-541c790be76f.png">

**Comment by gurjeetsinghvirdee** [comment]
It's a JSON file you can't write markdown inside it, make a new PR by removing those  **Asterisk**

**Comment by aqib-m31** [comment]
If I want some text to appear in bold or italic - how will I do that?

**Comment by aqib-m31** [comment]
> It's a JSON file you can't write markdown inside it, make a new PR by removing those **Asterisk**

I followed the QuickStart Documentation it shows you can use markdown in bio!

![Screenshot 2023-01-25 142846](https://user-images.githubusercontent.com/63852213/214520907-972707c4-23e5-4608-94a0-43d85b594e17.png)

**Comment by gurjeetsinghvirdee** [comment]
ok ok I got it, you didn't add space before **"**

**Comment by aqib-m31** [comment]
It won't work.
I tried to share @eddiejaoude profile on whatsapp - the asterisks appear on Eddie's profile also. @gurjeetsinghvirdee

**Comment by aqib-m31** [comment]
![WhatsApp Image 2023-01-25 at 14 51 11](https://user-images.githubusercontent.com/63852213/214525499-6d594049-e2a4-4d08-803d-351102e3238b.jpg)

**Comment by gurjeetsinghvirdee** [comment]
then better to remove this **Asterisk**

**Comment by ChinmayMhatre** [comment]
Hey @aqib-m31 , I tried it out myself and it does seem to be as you say. Maybe others contributors can take a look and see if they see any solution. Thank you for raising this issue!
![image](https://user-images.githubusercontent.com/51131670/214540717-bedba317-bd98-425b-813d-76aeff436bb1.png)

**Comment by eddiejaoude** [comment]
Thank you for raising the issue 👍 

The markdown is currently only rendered when displaying on the LinkFree project, we can control how the previews are done with `og:` tags - we have a few of these but need to add more for the bio and render the markdown

**Comment by eddiejaoude** [comment]
Looking into this I am not sure the OG tags will allow rendered markdown, so we might have to strip them 🤔

**Comment by aqib-m31** [comment]
From the json files?

**Comment by SaraJaoude** [comment]
We should keep the markdown in the json file as this is the source, but we can manipulate how it is used.

- Currently the markdown is rendered on the website for our profiles correctly
- For the preview when sharing on other platforms, we have 2 options, we can remove the markdown when used in the `title` or `OG` tags or we can try to render the markdown in the `title` and `OG` tags and see if that works

**Comment by Abhinav-6** [comment]
There is String.replaceAll() method available in JavaScript. Using this method we can replace all "*" with empty string "".

**Comment by ChinmayMhatre** [comment]
I would like to give this a go.

**Comment by Abhinav-6** [comment]
You don't get what I was saying. In Pagehead components they are passing data.bio as description. Instead of data.bio if pass `data.bio.replaceAll("*","")`, this will remove all the * from description.![Screenshot_2023-02-13-17-45-17-12_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/89967724/218455427-39451f96-b926-40c2-879c-ac3c6954cc4d.jpg)
