### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by priyankarpal** [EddieHubCommunity/LinkFree#3954]
### Description

I'm getting errors when I'm clicking on the Milestones tab. Visit my profile and see this problem. https://linkfree.eddiehub.io/priyankarpal

### Screenshots

![Screenshot from 2023-01-25 14-02-06](https://user-images.githubusercontent.com/88102392/214516459-17b23074-4101-43e7-9ecf-459c99031380.png)

**Comment by eddiejaoude** [comment]
Thank you for raising 👍 

`url` has become a requirement, I will try to do a global fix now

**Comment by eddiejaoude** [comment]
Fix being deployed now 🎉

**Comment by priyankarpal** [comment]
@eddiejaoude Now it's working. 👍🏻 🥳
