### ISSUE TITLE
Add new features

### ISSUE THREAD

**Issue by priyankarpal** [EddieHubCommunity/LinkFree#3985]
### Description

**Hi, @eddiejaoude I think the previous milestones cards UI was far better than the present card UI.**

### Screenshots

<img width="2353" alt="Untitled" src="https://user-images.githubusercontent.com/88102392/214683375-81ba927a-c3d4-4b06-b93f-58425a71d80a.png">

**Comment by eddiejaoude** [comment]
Thank you for the feedback. The whole card was clickable before, now it is a specific icon. We can keep improving the design as we go along

I will close this issue and feel free to raise specific improvements.

**Note: please don't write it is like you are shouting**
