### ISSUE TITLE
[FEATURE]UI Improvement-Home Page

### ISSUE THREAD

**Issue by manavmodi22** [EddieHubCommunity/LinkFree#399]
### Description

On the main page of LinkFree, it just shows the avatars of people part of the platform. Instead of _just_ the avatars, if there is provision of providing more information, that would make the platform much better. 
Suggestions:

- [ ] 1. Cards interface having the avatar, name and description.
- [ ] 2. Carousels widget
- [ ] 3. List view 
- [ ] 4. Hover and show

Maybe add a toggle view option for user preference between the present view/ and the others suggested.
### Screenshots
![image](https://user-images.githubusercontent.com/55242552/135654877-51f2b4f8-b162-4e8a-90b2-a18f9f831ab5.png)

### Additional information
None.

**Comment by AbhijithGanesh** [comment]
Can you please add a description for this issue?

**Comment by krishguptadev** [comment]
By cards do you mean? Something like what github has: 
![image](https://user-images.githubusercontent.com/91655303/135758389-4c9a2e94-ea53-4702-80fe-d7509a745fff.png)

If yes.. I guess we should keep it open to contributors for hacktoberfest. What do you think maintainers?

**Comment by manavmodi22** [comment]
Yes, I guess this is a good start.

**Comment by AbhijithGanesh** [comment]
I don't think I have access

**Comment by Vyvy-vi** [comment]
related to #144 #191 #122

**Comment by emmalearnscode** [comment]
As the profiles are now shown as chips with avatar and name and a hover effect is applied to show how many links they have in their profile, I’ll close this issue for now. Feel free to open new issues if you have ideas for how the ui could be improved further, preferably with a mock-up so it’s easy to visualise the changes.
