### ISSUE TITLE
[FEATURE] Addition of purge-css

### ISSUE THREAD

**Issue by AbhijithGanesh** [EddieHubCommunity/LinkFree#400]
### Description

We can add a purge css to remove unused css in this project, it will be useful as it'll benefit the developers.

### Additional information

[Docs](https://purgecss.com/)
I would like to know if this is possible and if it is I would like to be assigned to it.

**Comment by krishguptadev** [comment]
My Question is that does purgecss work with PrimeReact? Else it seems a bit non-useful to me

**Comment by AbhijithGanesh** [comment]
Can the maintainers assign me this issue ? I would like to prepare a patch @krishdevdb

**Comment by krishguptadev** [comment]
Nope, I don't. I didn't even add my profile to Linkfree 😆 

![image](https://user-images.githubusercontent.com/91655303/136663470-65345525-a8b7-4007-a664-201b1ddc8963.png)

**Comment by krishguptadev** [comment]
Hey there @AbhijithGanesh, do you need any help?

**Comment by nathgoutam93** [comment]
Hey there @Vyvy-vi looks like current assignee is no longer working on it and he's not active . Can I work on this issue. I already made an PR but @emmalearnscode suggested to ask before taking over.

**Comment by Vyvy-vi** [comment]
It would have been great if this message was sent before a PR, though I think there's no harm in working on 3 month stale issues

**Comment by nathgoutam93** [comment]
oh, yeah I should have 😅

**Comment by krshdev** [comment]
Not yet stale...
