### ISSUE TITLE
[FEATURE] Add Icon for Website links

### ISSUE THREAD

**Issue by orama254** [EddieHubCommunity/LinkFree#401]
### Description

Add an extra icon for website links

#### Actual Result
![Actual result](https://user-images.githubusercontent.com/50571688/135658259-30256669-4b4b-46b1-bebf-657fa8986394.jpg)

#### Expected Result
![globe icon eddiehub](https://user-images.githubusercontent.com/50571688/135658052-4fcbabe6-f15b-41d7-9ad2-21abeb719f13.jpg)

**Comment by sanjana-98** [comment]
Hi @orama254 can I take this up?

**Comment by orama254** [comment]
Hi @sanjana-98 I'm already working on it right now.

**Comment by Omkar845** [comment]
can i contribute to this

**Comment by orama254** [comment]
This was resolved in a conversation at #403
