### ISSUE TITLE
Issue about Profile view

### ISSUE THREAD

**Issue by HarshPanchal26** [EddieHubCommunity/LinkFree#4013]
### Description

    Every time I refreshing my profile page , the total view count is increasing , I just take my profile view count to 50 by refreshing page . Is this possible to resolve it without implementing system which is base on Sign in / Sign up.

I don't think personally it can be called as an issue but , here it is.

### Screenshots

Before Refreshing the page

 

![Screenshot (177)](https://user-images.githubusercontent.com/95937722/214811914-1f44f0b9-7522-4761-9e64-68b68d99bc86.png)

After Refreshing the page .

![Screenshot (178)](https://user-images.githubusercontent.com/95937722/214812209-bf9c3f03-07f7-46ac-949f-99dbff822821.png)

### Additional information

Can it be possible to resolve this by use of cookies/session thus we are now working on a system which is not login base ?

It'll be great if I'll be assign for this issue.

**Comment by sidharthviz** [comment]
> ### Description
> ```
> Every time I refreshing my profile page , the total view count is increasing , I just take my profile view count to 50 by refreshing page . Is this possible to resolve it without implementing system which is base on Sign in / Sign up.

> Can it be possible to resolve this by use of cookies/session thus we are now working on a system which is not login base ?
> 
> It'll be great if I'll be assign for this issue.

 Hi @HarshPanchal26  i think it can work by creating two tables for profile_view & pages..
 so when a user goes to a profile it will insert a new record into profile_vies with the user_id and increase the counter. Also it will insert a record in it..still Not sure about it. we can work on it.

**Comment by HarshPanchal26** [comment]
Hey 

> > ### Description
> > ```
> > Every time I refreshing my profile page , the total view count is increasing , I just take my profile view count to 50 by refreshing page . Is this possible to resolve it without implementing system which is base on Sign in / Sign up.
> > ```
> 
> > Can it be possible to resolve this by use of cookies/session thus we are now working on a system which is not login base ?
> > It'll be great if I'll be assign for this issue.
> 
> Hi @HarshPanchal26 i think it can work by creating two tables for profile_view & pages.. so when a user goes to a profile it will insert a new record into profile_vies with the user_id and increase the counter. Also it will insert a record in it..still Not sure about it. we can work on it.

> Hi @sidharthviz  Cab you plz explain bit more about your thought , I would like to work with you.

**Comment by tobySolutions** [comment]
Hey @sidharthviz! I noticed the issue as well. I was about to raise it just now, but, found out that @HarshPanchal26 has raised it here already.


Before:
![Screenshot from 2023-01-26 16-36-39](https://user-images.githubusercontent.com/96334363/214883446-3b9258e1-9819-44fd-9526-51d29521a27b.png)

After:
![Screenshot from 2023-01-26 16-54-04](https://user-images.githubusercontent.com/96334363/214883505-ecdd8a24-a75e-43c1-bc68-d16e230b4524.png)

**Comment by HarshPanchal26** [comment]
hey @eddiejaoude Can it be possible to make this change and if it is can you plz assign it to me ?

**Comment by HarshPanchal26** [comment]
> Hey @sidharthviz! I noticed the issue as well. I was about to raise it just now, but, found out that @HarshPanchal26 has raised it here already.
> 
> Before: ![Screenshot from 2023-01-26 16-36-19](https://user-images.githubusercontent.com/96334363/214883880-525024af-8898-4eed-8238-1138e64b5aa8.png)
> 
> After: ![Screenshot from 2023-01-26 16-54-04](https://user-images.githubusercontent.com/96334363/214883505-ecdd8a24-a75e-43c1-bc68-d16e230b4524.png)

hey @tobySolutions We can make it together .

**Comment by Aadarsh805** [comment]
This has been discussed previously here #3187

**Comment by amandamartin-dev** [comment]
Thank you for noticing that @Aadarsh805 .  I will close this issue for now as per #3187 it was decided not to move forward with the fix at this time.  Appreciate the contribution and idea.  For more details on why, please see the discussion in the referenced issue.
