### ISSUE TITLE
A video for Step 13

### ISSUE THREAD

**Issue by muhammadanas0716** [EddieHubCommunity/LinkFree#4043]
### Description

Make a video for step 13 so the lives of people can be made easier.

### Additional information

Reminder

CC: @eddiejaoude @FrancescoXX

**Comment by Avi-88** [comment]
Hi @muhammadanas0716 , there are currently 2 PR's #3825 and #4177 which are trying to improve the same. One is for replacing the image with a gif and other replaces it with a different image with edits specifying the same please leave your thoughts on these which will help in getting them merged faster,thanks.

**Comment by muhammadanas0716** [comment]
Oh cool.

I was in a live stream with Eddie, so he told me to make the PR as a reminder.

CC: @eddiejaoude

**Comment by shubhsharma19** [comment]
I think the one from @Avi-88 is a good option :D

**Comment by muhammadanas0716** [comment]
Up to you honestly. I don't mind!

**Comment by Avi-88** [comment]
cool , I think you can close this issue so it avoids confusion  as it is  already being  handled, thanks

**Comment by SaraJaoude** [comment]
I will close this as this has now been done: https://linkfree.eddiehub.io/docs/quickstart

**Comment by muhammadanas0716** [comment]
Thank you, Sara!
