### ISSUE TITLE
New Testimonial for Francesco Ciulla

### ISSUE THREAD

**Issue by priyankarpal** [EddieHubCommunity/LinkFree#4062]
### Name

FrancescoXX

### Title

Francesco Ciulla: The Dev Advocate &  Open Source Enthusiasts

### Description

Francesco Ciulla is an amazing dev advocate and open-source enthusiast. His sarcasm and wit add a unique touch to his presentations, making them not only informative but also entertaining. I have learned so much about dev advocacy from watching his videos and highly recommend them to anyone interested in the topic.
![Screenshot from 2023-01-26 22-46-45](https://user-images.githubusercontent.com/88102392/214904103-257354ce-3343-4601-a140-c3e43524297f.png)

**Comment by dan-mba** [comment]
This testimonial won't work with the current action.
There is an issue open to fix that.
Please try again and avoid newlines, links, or quotation marks.
Other markdown formatting should be fine.

**Comment by scorcism** [comment]
Hello there, I'm new to this can you help me to make my first pull request.
Hope to get a positive response.

**Comment by priyankarpal** [comment]
@scorcism Follow this official doc if you want to contribute LinkFree https://linkfree.eddiehub.io/docs/quickstart

**Comment by scorcism** [comment]
@priyankarpal sure, thank you
