### ISSUE TITLE
[FEATURE] sum of interactions

### ISSUE THREAD

**Issue by FrancescoXX** [EddieHubCommunity/LinkFree#4078]
### Description

ON the right of each row, there are the total interactions.

It would be great to have the total of the interaction at the top or bottom of the page, even semi-transparent and gray

### Screenshots

![image](https://user-images.githubusercontent.com/18360871/214941792-8288379a-5b10-4f41-961d-e0ed8f18155f.png)

**Comment by kunaaal13** [comment]
i'd like to work on this, please assign this to me

**Comment by FrozenHearth** [comment]
A circular indicator on the top right of each card would work well, I think.

**Comment by SaraJaoude** [comment]
I will close this issue as now this is available in your private stats page, after you log in (this was released today).

<img width="1355" alt="Screenshot 2023-02-05 at 11 33 34" src="https://user-images.githubusercontent.com/82668196/216801767-a39c4b3b-2e46-4db8-b337-f42b53c494ea.png">
