### ISSUE TITLE
New Testimonial for Pradumna Saraf

### ISSUE THREAD

**Issue by FrancescoXX** [EddieHubCommunity/LinkFree#4098]
### Name

Pradumnasaraf

### Title

The Open Source and DevOps guy

### Description

Pradumna is an absolute gem for the Developer Community. His passion and approach to people will bring him far. Not following him literally everywhere is a great mistake if you want to know more about Open Source, DevOps, and other things related to tech. Also very friendly and always keen to help.

I hope to meet him in person as soon as possible, then we can make an updated version of the testimonial!

**Comment by Pradumnasaraf** [comment]
Thank you so much for your kind words and support, Francesco.
