### ISSUE TITLE
Navbar width gets reduced when viewing docs in smaller screen

### ISSUE THREAD

**Issue by swagataroy30** [EddieHubCommunity/LinkFree#4120]
### Description

When viewing docs, the navbar width decreases as the screen size gets smaller, It should take up the full width of the screen.

### Screenshots

![linkfree_docs_nav_issue](https://user-images.githubusercontent.com/116095538/215113634-bbbcc732-2b6c-4149-bb86-a33bb41ba655.jpeg)

**Comment by swagataroy30** [comment]
can i work on this?

**Comment by Avi-88** [comment]
Hi @swagataroy30, sorry but I tried recreating  this bug but I wasn't able to. So I'm guessing it was just a fluke but it would help if you could specify how you came across it like the your browser, the screen size, etc. thanks

**Comment by swagataroy30** [comment]
I just checked it again the issue is occurring in mobile view 

https://user-images.githubusercontent.com/116095538/215487147-5201170b-b19b-4672-b101-7ff5c51f09df.mp4

In Firefox : 

![WhatsApp Image 2023-01-30 at 6 47 55 PM](https://user-images.githubusercontent.com/116095538/215488532-fcfe3a82-8b4c-404e-8f39-f2b12b7731c5.jpeg)

**Comment by FrozenHearth** [comment]
It's not just the navbar. Seems the entire page is not taking the full width. Checked it on devtools.

**Comment by swagataroy30** [comment]
Ya did check that too ... but didn't find a better way to write the title :sweat_smile:   but I did mention navbar here just for the visual changes to point out the issue

**Comment by Avi-88** [comment]
I'm not sure what is causing this but I tried again on mobile using chrome and on desktop using firefox but couldn't replicate it, have a look 

# On mobile (chrome)
![breaknav](https://user-images.githubusercontent.com/79744258/215514715-d80e3e62-041e-45f8-bd5e-9e6afc0d52aa.jpeg)

# On desktop (firefox)
![navbreak](https://user-images.githubusercontent.com/79744258/215514829-0f701d72-91b8-4e0c-9fde-226323c5ef53.png)

**Comment by swagataroy30** [comment]
@Avi-88 could you check by selecting a smaller device on Firefox like iphone 12/13 or 11. @FrozenHearth could also reproduce this issue.

**Comment by Avi-88** [comment]
I just tried with all three of these , still didn't break.
![linkfreeiphone](https://user-images.githubusercontent.com/79744258/215547586-3898b8c0-4c24-4096-a3c5-eaf0dac8a499.png)

**Comment by FrozenHearth** [comment]
Tried on my iPhone 11 on Chrome & Firefox, and it's not breaking.

**Comment by Aadarsh805** [comment]
This is happening because there is no width defined in the layout, so the children are taking as much width as they require
This will be easily fixed by adding `widht: 100%` on the parent container

**Comment by Aadarsh805** [comment]
> Tried on my iPhone 11 on Chrome & Firefox, and it's not breaking.

how about this route https://linkfree.eddiehub.io/docs/quickstart ?

**Comment by FrozenHearth** [comment]
> > Tried on my iPhone 11 on Chrome & Firefox, and it's not breaking.
> 
> how about this route https://linkfree.eddiehub.io/docs/quickstart ?

This is the only route that is breaking on mobile.

**Comment by Aadarsh805** [comment]
> > > Tried on my iPhone 11 on Chrome & Firefox, and it's not breaking.
> > 
> > 
> > how about this route https://linkfree.eddiehub.io/docs/quickstart ?
> 
> This is the only route that is breaking on mobile.



> > > Tried on my iPhone 11 on Chrome & Firefox, and it's not breaking.
> > 
> > 
> > how about this route https://linkfree.eddiehub.io/docs/quickstart ?
> 
> This is the only route that is breaking on mobile.

Nah, try this as well https://linkfree.eddiehub.io/docs/how-to-guides/testimonials, any route inside docs with images will have this problem, because `width` is not defined to the parent

**Comment by Aadarsh805** [comment]
> > > > Tried on my iPhone 11 on Chrome & Firefox, and it's not breaking.
> > > 
> > > 
> > > how about this route https://linkfree.eddiehub.io/docs/quickstart ?
> > 
> > 
> > This is the only route that is breaking on mobile.
> 
> Yeah it is strange though because it works responsively if you resize the window but as soon as you try the preset mobile screen sizes it breaks.

#### That happens because of the viewport meta tag

The viewport meta tag with "width=device-width, initial-scale=1.0" sets the viewport's width equal to the width of the device screen and sets the initial zoom level to 1.0. This means the layout will be optimized for the device screen size when the page is first loaded.
However, if the screen size changes after the page have loaded ( if we resize the browser window), the layout will not adjust itself

**Comment by PerkinsDan** [comment]
@FrozenHearth Also broken on 

https://linkfree.eddiehub.io/docs/how-to-guides/editing
https://linkfree.eddiehub.io/docs/how-to-guides/bio
https://linkfree.eddiehub.io/docs/how-to-guides/links
https://linkfree.eddiehub.io/docs/how-to-guides/statistics
https://linkfree.eddiehub.io/docs/how-to-guides/tags
https://linkfree.eddiehub.io/docs/how-to-guides/socials-shortcuts
https://linkfree.eddiehub.io/docs/how-to-guides/milestones
https://linkfree.eddiehub.io/docs/how-to-guides/events
https://linkfree.eddiehub.io/docs/how-to-guides/testimonials
https://linkfree.eddiehub.io/docs/contributing/storybook
https://linkfree.eddiehub.io/docs/full-profile-example

The rest are fine for me. Seems to be image is not resizing causing the issure

**Comment by Aadarsh805** [comment]
> @FrozenHearth Also broken on
> 
> https://linkfree.eddiehub.io/docs/how-to-guides/editing https://linkfree.eddiehub.io/docs/how-to-guides/bio https://linkfree.eddiehub.io/docs/how-to-guides/links https://linkfree.eddiehub.io/docs/how-to-guides/statistics https://linkfree.eddiehub.io/docs/how-to-guides/tags https://linkfree.eddiehub.io/docs/how-to-guides/socials-shortcuts https://linkfree.eddiehub.io/docs/how-to-guides/milestones https://linkfree.eddiehub.io/docs/how-to-guides/events https://linkfree.eddiehub.io/docs/how-to-guides/testimonials https://linkfree.eddiehub.io/docs/contributing/storybook https://linkfree.eddiehub.io/docs/full-profile-example
> 
> The rest are fine for me. Seems to be image is not resizing causing the issure

Yes because the docs-layout parent container does not have width defined, so these routes which have images inside them will have this issue
This can be very easily fixed by just adding `w-full` to the parent container in the docs layout

**Comment by Avi-88** [comment]
> This is happening because there is no width defined in the layout, so the children are taking as much width as they require This will be easily fixed by adding `width: 100%` on the parent container

Oh yes, I see it now, I guess @swagataroy30  can make a PR for this as he mentioned he wanted to work on this, feel free to loop us in if you need any help, thanks

**Comment by swagataroy30** [comment]
Thanks @Avi-88, and @Aadarsh805 w-full on the parent doesn't work here we need to add min-w-fit to the parent container. Let me add a snap after i make the changes

![linkfree_docs_fix_snap](https://user-images.githubusercontent.com/116095538/215720169-4f53d76f-6d82-4ff5-9f16-ef7e6dfd1efb.jpeg)

Should i make a PR?

**Comment by Aadarsh805** [comment]
> Thanks @Avi-88, and @Aadarsh805 w-full on the parent doesn't work here we need to add min-w-fit to the parent container. Let me add a snap after i make the changes
> 
> ![linkfree_docs_fix_snap](https://user-images.githubusercontent.com/116095538/215720169-4f53d76f-6d82-4ff5-9f16-ef7e6dfd1efb.jpeg)
> 
> Should i make a PR?

Yeah go ahead

**Comment by eddiejaoude** [comment]
It seems there are multiple discussions and PRs going on for this issue - this creates more work for everyone. The maintainers will try to figure this out, for the future it is better to collaborate on the PR together not compete.

**Comment by swagataroy30** [comment]
Hey @eddiejaoude I did make the pull request first as the discussion of the issue goes, I asked @Aadarsh805 and others if i can make a PR,  i meant no compete 😅. And the other PR looks good - should I close mine?

**Comment by eddiejaoude** [comment]
Thank you, but let me go through and review/test both PRs and see what we can use.

> I did make the pull request first

This is not a reason for a pull request to be accepted

**Comment by SyedImam1998** [comment]
Hey, @eddiejaoude  Thanks for the feedback I really appreciate that. Sorry for the multiple Pr. I guess some of us have started working on this at the same time and each of us has our own perspective regarding this issue so we put it out so none of them can be missed out. 
Cheers,

**Comment by eddiejaoude** [comment]
Thanks @SyedImam1998 for the energy in getting started 👍 but we will try to find a way where people can collaborate more and combine ideas to produce a better solution 

We are going to start using labels on issues more and can assign an issue to multiple people

**Comment by swagataroy30** [comment]
> Thank you, but let me go through and review/test both PRs and see what we can use.
> 
> > I did make the pull request first
> 
> This is not a reason for a pull request to be accepted

My bad :sweat_smile: . I will keep that in mind ! :+1:

**Comment by eddiejaoude** [comment]
Fixed by #4448
