### ISSUE TITLE
optimize search to find by github username as well

### ISSUE THREAD

**Issue by KlausMikhaelson** [EddieHubCommunity/LinkFree#4124]
### Description

we can optimize the search feature so that people can even search user by their github username as well

**Comment by Vishrut19** [comment]
Can I try to work on this issue ?

**Comment by SaraJaoude** [comment]
> Can I try to work on this issue ?

I have recently assigned you an issue and we only assign one issue at a time.

**Comment by nanthakumaran-s** [comment]
Can I work on this issue?

**Comment by SaraJaoude** [comment]
Sure @nanthakumaran-s I have assigned this to you

**Comment by nanthakumaran-s** [comment]
Thanks @SaraJaoude ... will give a PR soon.

**Comment by eddiejaoude** [comment]
@nanthakumaran-s I will unassign this issue, as it is blocking other people from doing it. We can assign you another issue when you have more time.

**Comment by Vishrut19** [comment]
Can I try to work on this issue ??

**Comment by KlausMikhaelson** [comment]
hey @eddiejaoude would like to work on it incase it's open to work on rn

**Comment by eddiejaoude** [comment]
@Vishrut19 you comment first, so I will assign it to you (sorry @KlausMikhaelson)

**Comment by KlausMikhaelson** [comment]
sure sure nw, @Vishrut19 do lmk if you need any help !

**Comment by eddiejaoude** [comment]
> lmk if you need any help !

love that, working together is 🔥

**Comment by Vishrut19** [comment]
Hey @KlausMikhaelson are you on Discord ? It would be great if you can connect with me over there and we can discuss about stuff. My Discord Id - Vishrut || Web Developer#0359. Please ping me over there

**Comment by Vishrut19** [comment]
Hey! I am working on this issue but I am not able to find the search component file or basically a file that uses some API to search users by their username.
<img width="1284" alt="Screenshot 2023-03-18 at 11 15 46 AM" src="https://user-images.githubusercontent.com/53470896/226087682-4244d922-4f14-4779-b456-80939a0ba5c8.png">
And also how to resolve this error 👇
<img width="1284" alt="Screenshot 2023-03-18 at 11 11 13 AM" src="https://user-images.githubusercontent.com/53470896/226087528-52dedf2e-cf9e-4d62-930b-5c25a0691343.png">
