### ISSUE TITLE
[FEATURE] Creating a Navigation Bar for the Home Page

### ISSUE THREAD

**Issue by Soham041201** [EddieHubCommunity/LinkFree#414]
### Description

Adding a basic nav-bar using prime react. A skeleton navigation bar, which can be updated and improved later

### Screenshots

A skeleton template of the navigation bar which can be updated later

![image](https://user-images.githubusercontent.com/79072777/135704595-ed8dc0ee-d08a-40bb-900e-637b9359e933.png)

**Comment by prsmahajan** [comment]
Can I work on this issue?

**Comment by Soham041201** [comment]
Actually I am working on this :)

**Comment by Vyvy-vi** [comment]
closed by 9029abe
