### ISSUE TITLE
[BUG] Wrong Image Element

### ISSUE THREAD

**Issue by Ertan222** [EddieHubCommunity/LinkFree#4149]
## Problem
Another wrong element for image usage in userMilestones . We should change this one to NextJs's Image component. 

### Github UI

[Here](https://github.com/EddieHubCommunity/LinkFree/blob/main/components/user/UserMilestone.js)

### File Path

```

LinkFree/components/user/UserMilestone.js

```

### Screenshots

![Screenshot from 2023-01-28 04-35-58](https://user-images.githubusercontent.com/62712555/215235089-b2560139-8dac-490a-916c-7964a32663e3.png)

### Additional information

Same problem with this issue #3190

**Comment by Sriparno08** [comment]
Hey, I can work on this!

**Comment by hasnainmakada-99** [comment]
Hey @Ertan222 can I be assigned to this issue ?

**Comment by eddiejaoude** [comment]
Actually image is not supported and has been removed from the docs. Please remove the code referring to the `image`, only `icon` is support at the moment

**Comment by eddiejaoude** [comment]
@Sriparno08 you asked first, so I have assigned it to you

Thanks @Ertan222 for raising 👍

**Comment by Sriparno08** [comment]
Thanks, Eddie!

**Comment by Sriparno08** [comment]
Hey Eddie, should I delete this whole section?

![Screenshot 2023-01-29 231927](https://user-images.githubusercontent.com/89148144/215345627-181c3596-ecc0-4265-9c31-b87ec0ea7142.png)

**Comment by eddiejaoude** [comment]
@alokVerma749 please check issues are not already assigned to someone else before making changes

**Comment by eddiejaoude** [comment]
I did a quick fix as this issue was cuisine confusion as people were not reading the conversation.

So I will close this issue as it is fixed here https://github.com/EddieHubCommunity/LinkFree/pull/4312
