### ISSUE TITLE
[FEATURE] Adding an Animated gif in the quickstart guide. 

### ISSUE THREAD

**Issue by shubhsharma19** [EddieHubCommunity/LinkFree#4175]
### Description

I want to add an Animated gif in Quickstart.mdx in LinkFree to ensure that new people do not end up merging their PR into their own "forked repo".

### Screenshots

![base repo](https://user-images.githubusercontent.com/69891912/215273700-501b8d44-251c-4a19-a927-fc2b37049bad.gif)

### Additional information

This will ensure noone merges their PR into their own forked repo.

**Comment by Vishrut19** [comment]
Can you explain more about it? So that I can work on it @shubhsharma19

**Comment by SaraJaoude** [comment]
Thank you for your suggestion.  I don't think this required any longer as additional screenshots as well as a video have now been added to the Docs.

**Comment by shubhsharma19** [comment]
Thankyou @SaraJaoude
