### ISSUE TITLE
New Testimonial for Mohd Imran

### ISSUE THREAD

**Issue by aasthashahcodes** [EddieHubCommunity/LinkFree#4206]
### Name

imran1509

### Title

Kind & Amazing.

### Description

I've interacted with Imran a few times now, and everytime got to learn something new from them. They have such positive response to every question I've & tries to explain everything with patience. Not to mention, they have been excellent at their work & inspire people too. If you wanna talk with them, connect on socials or even a calendly meet for mentorship.

**Comment by imran1509** [comment]
Thankyou so much Aastha !!!!
