### ISSUE TITLE
Image alt text doesn't match image content

### ISSUE THREAD

**Issue by EmmaDawsonDev** [EddieHubCommunity/LinkFree#4223]
### Description

Many images on the landing page have the alt text: White canvas laptop sleeve with gray felt interior, silver zipper, and tan leather zipper pull.

The alt text needs to be changed to match what is actually shown in the images.

### Screenshots

<img width="280" alt="Screenshot_20230129_163537" src="https://user-images.githubusercontent.com/57045550/215337658-457c148a-2d53-494a-a6e9-e0e70b7d5a25.png">

**Comment by ShuvamChatterjee28** [comment]
Hello @EmmaDawsonDev can you please assign me this issue?

**Comment by EmmaDawsonDev** [comment]
Sure, go ahead :)
