### ISSUE TITLE
Update image for tags on Features section of home page

### ISSUE THREAD

**Issue by PerkinsDan** [EddieHubCommunity/LinkFree#4252]
### Description

The image is low quality and also out of date compared to what it currently looks like.

To fix: update image to newer higher resolution image. Possibly make it interactive so that hover styles apply like it does on discover page.

I would like to be assigned to this

### Screenshots

<img width="1276" alt="Screenshot 2023-01-30 at 11 06 24" src="https://user-images.githubusercontent.com/84538727/215461529-ebec250c-7723-41bd-a7cd-37d410192b59.png">

**Comment by Avi-88** [comment]
Hi @PerkinsDan , I was thinking that just updating the image will suffice . The styling it has currently seems good to me as the features section just needs to display the available features and doesn't need to be interactive. Do share your thoughts if you had something else in  mind, thanks
