### ISSUE TITLE
More than One JavaScript and ReactJS Tags on header

### ISSUE THREAD

**Issue by Vishrut19** [EddieHubCommunity/LinkFree#4253]
### Description

I can see that there is more than one JavaScript and ReactJS category on the header that divides the folks into different groups according to their skillset mentioned on their LinkFree profile page.

I have also attached a Screenshot of it for your reference. 

### Screenshots

<img width="1279" alt="Screenshot 2023-01-30 at 10 44 44 AM" src="https://user-images.githubusercontent.com/53470896/215463792-77047b4f-06ce-4ae5-95d8-299f30b1afd5.png">

**Comment by PerkinsDan** [comment]
This issue already looks at duplicate tags #3604

**Comment by GauravBurande** [comment]
It's due to the different spellings. 

We should have capitalized, lowercased or uppercased the text before adding it to the database.

**Comment by GauravBurande** [comment]
And even if we do that to new user's data, I think we'd need to change the tags of every existing user.
I may be wrong.

**Comment by Aadarsh805** [comment]
@Vishrut19 this issue already exists, you should close this

**Comment by ChinmayMhatre** [comment]
Hey @Vishrut19 , Thank you for creating this PR. There is an open PR working on this and will be fixed soon. Thanks !
