### ISSUE TITLE
The Release Label or Tag in Readme Redirects a to a page and opens up an image . It should be giving the release details

### ISSUE THREAD

**Issue by bonysureliya** [EddieHubCommunity/LinkFree#4276]
### Description

The Release Label or Tag in Readme Redirects a to a page and opens up an image .
 It should be giving the release details .

**Comment by Sheikh-JamirAlam** [comment]
@bonysureliya The release details you mentioned are these right?
https://github.com/EddieHubCommunity/LinkFree/releases

**Comment by bonysureliya** [comment]
Yes
