### ISSUE TITLE
[DOCS] In Linkfree QuickStart docs, when creating new file inside data folder click on the data folder and then create a new file

### ISSUE THREAD

**Issue by GauravBurande** [EddieHubCommunity/LinkFree#4281]
### Description

In Linkfree QuickStart docs, instead of creating a file data/<username>.json, the user should first open the data folder and then create a new file and name the file <username>.json instead of data/<username>.json, it'll be easy to understand.

### Screenshots

![create a new file](https://user-images.githubusercontent.com/100035026/215670919-2e4eb580-52d0-4094-94c6-0873c300ad1d.png)

**Comment by GauravBurande** [comment]
Please assign this issue to me.

**Comment by GauravBurande** [comment]
Can we use scribehow extension to generate steps to create a user account on linkfree.
It looks so good.
here's a demo of how to use scribehow:

https://scribehow.com/shared/How_to_use_Scribe__csOSUfOlQJGuzFx2HN92wQ

**Comment by SaraJaoude** [comment]
Thank you for your suggestion.  This is another way to add your file, but as with many things on GitHub, there are multiple ways to achieve the same thing. 

There is already a video embedded in the QuickStart guide: https://linkfree.eddiehub.io/docs/quickstart and more videos will be coming to other sections of the Docs.
