### ISSUE TITLE
[DOCS] the linkfree docs page states there are three ways to add user's profile, but only one way is defined

### ISSUE THREAD

**Issue by GauravBurande** [EddieHubCommunity/LinkFree#4286]
### Description

the linkfree docs page states there are three ways to user's profile, but someone new can only add their profile using the GitHub UI.

Either state the other 2 ways or remove the text from the docs page. It may be confusing for someone new.

### Screenshots

![docs](https://user-images.githubusercontent.com/100035026/215682414-87e070ea-1251-4548-8e9a-65a14a07fe7f.png)

**Comment by Vishrut19** [comment]
Can I try to work on this issue ?

**Comment by mohit-marathe** [comment]
Hello @GauravBurande , can I work on this issue?

**Comment by GauravBurande** [comment]
> Hello @GauravBurande , can I work on this issue?

You can, but I'm not the one assigning issues here.
I think the maintainers of this project are too busy somewhere else.

**Comment by SaraJaoude** [comment]
The Docs do not say that someone new can **only** add their profile using the GitHub UI.  The Docs state that for the **purpose** of the Quickstart guide, we will be showing how to add a profile using the GitHub UI. 

The next tabs along in the Docs, **Gitpod**, **Local Development** and **Docker Compose**  explain the other ways in which the profile can be added.  This is also referenced in the Readme: https://github.com/EddieHubCommunity/LinkFree

We will be updating that there are now **4** ways as Docker Compose has recently been introduced. 

I cannot see how this issue improves the project, so I will be closing it. 

> You can, but I'm not the one assigning issues here. I think the maintainers of this project are too busy somewhere else.

This is not a particularly helpful comment to the project ☝🏼 

Kindly remember maintainers are working across several timezones to deal with many notifications on this project. They are doing this role voluntarily whilst juggling family, work and other life commitments.
