### ISSUE TITLE
Issue: Stats text overflow on mobile to desktop transition

### ISSUE THREAD

**Issue by JunDevHarsh** [EddieHubCommunity/LinkFree#4301]
### Description

The text overflowed while doing a transition from mobile to desktop.

### Screenshots

![Untitled](https://user-images.githubusercontent.com/94737463/215751579-b55c8528-d634-4ff7-902d-7d0637c0283f.png)

### Additional information

https://user-images.githubusercontent.com/94737463/215748395-242b4b34-f829-4a9f-b288-472797a8fe0c.mp4

**Comment by ashuthe1** [comment]
Hi! I want to work on this issue , but I am new to open source. could you please guide me

**Comment by Aadarsh805** [comment]
> Hi! I want to work on this issue , but I am new to open source. could you please guide me

Hey @ashuthe1, this issue already has a pr, you can look onto other issues, and feel free to ask for help there as well

**Comment by GauravBurande** [comment]
No one has been assigned for this issue and there's a pr already for this issue, is this 
allowed?

**Comment by Aadarsh805** [comment]
> No one has been assigned for this issue and there's a pr already for this issue, is this allowed?

They themself created the issue so ig that works
But they must wait for the issue to be declared valid first

**Comment by eddiejaoude** [comment]
> But they must wait for the issue to be declared valid first

Thanks @Aadarsh805 we are going to start adding labels very soon to help clarify this as issues must be vetted first to avoid people wasting their time 👍
