### ISSUE TITLE
[FEATURE]  Add animation 

### ISSUE THREAD

**Issue by rahulpandey70** [EddieHubCommunity/LinkFree#4320]
### Description

It could be a good addition, if we add animation when clicking on hamburger menu (Dropdown menu).

**Comment by Aadarsh805** [comment]
> 

What kind of animations are you suggesting Rahul, can you please elaborate

**Comment by rahulpandey70** [comment]
> > 
> 
> What kind of animations are you suggesting Rahul, can you please elaborate attach some examples or screenshots maybe

Sure, on small devices when we click on hamburger menu the Dropdown come out in one go, what i wanted is it come out little bit slowly.

**Comment by ManishBisht777** [comment]
@Aadarsh805 @rahulpandey70 we can implement some framer motion animations

**Comment by Aadarsh805** [comment]
> @Aadarsh805 @rahulpandey70 we can implement some framer motion animations

Maintainers will have to approve using external library

**Comment by Aadarsh805** [comment]
> > > 
> > 
> > 
> > What kind of animations are you suggesting Rahul, can you please elaborate attach some examples or screenshots maybe
> 
> Sure, on small devices when we click on hamburger menu the Dropdown come out in one go, what i wanted is it come out little bit slowly.

yeah Eddie has asked to add a transition to the same, I don't remember what happened to that pr

**Comment by Vishrut19** [comment]
Is this issue still Open ?

**Comment by hirentimbadiya** [comment]
hey can you assign me this issue i can work on this , thanks!!

**Comment by rahulpandey70** [comment]
> hey can you assign me this issue i can work on this , thanks!!

Hey, You can see there is already one PR is created. Wait for the maintainers feedback
