### ISSUE TITLE
Wrong size for navigation bar

### ISSUE THREAD

**Issue by ThomasCode92** [EddieHubCommunity/LinkFree#4325]
### Description

When you view the QuickStart guide on mobile, the navigation bar doesn't go to the end of the screen.
I think the images are to wide.

### Screenshots

![navigation](https://user-images.githubusercontent.com/108367944/215873813-10efe07b-dcf7-4f7a-9169-3f29ab629e9b.PNG)

**Comment by Aadarsh805** [comment]
This issue already exists right here #4120
you can close this one

**Comment by GauravBurande** [comment]
it's due to the width of the images.

**Comment by ThomasCode92** [comment]
Ok, than I must have overlooked it when I searched the issues for it.
