### ISSUE TITLE
[FEATURE] People to only trend once per month

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#4335]
### Description

To give more people discoverability on LinkFree, it would be good to log which day people have trended on so that we can exclude them from other days that month

**Comment by Pradumnasaraf** [comment]
It would a great addition to LinkFree

**Comment by Ananya2001-an** [comment]
Sounds good

**Comment by adityaraute** [comment]
One thing to look for here is whether we are considering 30 days or calendar months. If we go with the latter, someone trending on 31 Jan can still be trending on 1 Feb. I'd suggest the former approach.

**Comment by abhijain2003** [comment]
I think we do not need to do manually, we can use javascript data method to check which data user is trending and we can store that date somewhere

**Comment by eddiejaoude** [comment]
Discover page has been removed
