### ISSUE TITLE
[FEATURE] Filter to show past events

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#4358]
### Description

Currently past events are hidden, it would be good to be able to show these

**Comment by abhijain2003** [comment]
i think inside Community Event, we can add another tab of past events, but from where we will get list of past events?

**Comment by swagataroy30** [comment]
Can I work on this?

**Comment by swagataroy30** [comment]
Can we do something like this?
![linkfree_past_events](https://user-images.githubusercontent.com/116095538/216245941-17924e57-13d8-44c1-994a-f9fe3e9ef0cc.png)

**Comment by lmac-1** [comment]
I was just coming here to report an issue and spotted this one. If a user has past events, it shows in the preview but then when you click there's nothing to see: 

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/64803272/216350028-65f32473-5ecd-4cdf-b6a2-a59f43fb9860.png">

You can take a look [here](https://linkfree.eddiehub.io/Panquesito7) for an example

Should I raise this as a separate issue or will it be fixed by this issue?

**Comment by abhijain2003** [comment]
ya that might be an issue, i think Event(1) here 1 is not targeting to wrong point or different one which is not relating to data being fetched in event page, can I work on this, but i need to more help from you guys

**Comment by swagataroy30** [comment]
> I was just coming here to report an issue and spotted this one. If a user has past events, it shows the total number of events the tab but then when you click there's nothing to see.
> 
> For example, here it says **Events (1)** on the tab but when you click on it, there are no events: <img alt="image" width="1261" src="https://user-images.githubusercontent.com/64803272/216350028-65f32473-5ecd-4cdf-b6a2-a59f43fb9860.png">
> 
> You can take a look [here](https://linkfree.eddiehub.io/Panquesito7) for an example
> 
> Should I raise this as a separate issue or will it be fixed by this issue?

I guess this can be can be included under this issue coz Events(1) would make sense when we add the past events.

**Comment by abhijain2003** [comment]
did you find solution to this

**Comment by swagataroy30** [comment]
Ya i actually implemented this :sweat_smile: but can't proceed further without any maintainer assigning the task or further discussion to this issue. We have to wait for that !

**Comment by SaraJaoude** [comment]
> Can we do something like this?
> ![linkfree_past_events2](https://user-images.githubusercontent.com/116095538/216438809-7d117ba9-6544-40b4-8f73-4200893df434.png)

This is a step in the right direction, let's go for it - I will assign it to you.  

I still think further work needs to be done for a better UX, but this can come separately in another issue and pull request.

**Comment by swagataroy30** [comment]
Thanks @SaraJaoude and i had a query under the Show all tab do we also need to include the past events or the Show all tab just includes the current events ?

**Comment by SaraJaoude** [comment]
Currently I think the `Show All` only shows future events, let's rename this one to be `Show All Future Events` and move this to the 2nd position across. 

So what about two new tabs, one with `Show Past Events` that this issue was originally created for but also another tab (at the top left in position 1) called `Show All Events` (which will include all types of events)

**Comment by swagataroy30** [comment]
> Currently I think the `Show All` only shows future events, let's rename this one to be `Show All Future Events` and move this to the 2nd position across.
> 
> So what about two new tabs, one with `Show Past Events` that this issue was originally created for but also another tab (at the top left in position 1) called `Show All Events` (which will include all types of events)

Ok so we have to rename that tab to `Show All Future Events `and add two new tabs `Show Past Events` and `Show All Events`, Ya that would be great but i was thinking if `Show all` includes only the future events then can just change the description of it to `List all future events with no filters` then it will be distinguishable. just want your views on it ? :sweat_smile:

**Comment by eddiejaoude** [comment]
Great collaboration 👍 We can tweak the titles at the PR stage, as it is better when we can see it.

**Comment by swagataroy30** [comment]
![linkfree_events_feature](https://user-images.githubusercontent.com/116095538/216817381-71a6f66b-ac66-4a08-a2cc-f3cab1a0ccde.png)

@SaraJaoude is it what you were suggesting? would really like your views on it @eddiejaoude

**Comment by swagataroy30** [comment]
![Screenshot from 2023-02-05 20-17-06](https://user-images.githubusercontent.com/116095538/216827347-edda96ff-f3b8-4ab6-b805-fa60a05e5890.png)

And what about the community events. Any suggestions? It's a snap after I added the past events !

**Comment by ManishBisht777** [comment]
> > Currently I think the `Show All` only shows future events, let's rename this one to be `Show All Future Events` and move this to the 2nd position across.
> > So what about two new tabs, one with `Show Past Events` that this issue was originally created for but also another tab (at the top left in position 1) called `Show All Events` (which will include all types of events)
> 
> Ok so we have to rename that tab to `Show All Future Events `and add two new tabs `Show Past Events` and `Show All Events`, Ya that would be great but i was thinking if `Show all` includes only the future events then can just change the description of it to `List all future events with no filters` then it will be distinguishable. just want your views on it ? sweat_smile

ig we can do keep it as `show all` and fade the past events just like we did in the `future milestones` 
![image](https://user-images.githubusercontent.com/89926834/216832456-a1f40290-9a41-4ba0-8767-28864dec25f9.png)

**Comment by SaraJaoude** [comment]
> @SaraJaoude is it what you were suggesting? would really like your views on it @eddiejaoude ... and just to add my views - not all events excluding the past events are `future events` - there are also some `ongoing events` that's happening, so can we do something like this ? - i'll add some snaps below  ![Screenshot from 2023-02-05 22-06-38](https://user-images.githubusercontent.com/116095538/216832124-b81a915d-a173-447a-a19f-36ea7ba6112b.png)


Like the idea - let's go for it

**Comment by SaraJaoude** [comment]
> ![Screenshot from 2023-02-05 20-17-06](https://user-images.githubusercontent.com/116095538/216827347-edda96ff-f3b8-4ab6-b805-fa60a05e5890.png)
> 
> And what about the community events. Any suggestions? It's a snap after I added the past events !

Let's leave this for now as I don't think past community events are so important

**Comment by SaraJaoude** [comment]
> ig we can do keep it as `show all` and fade the past events just like we did in the `future milestones` ![image](https://user-images.githubusercontent.com/89926834/216832456-a1f40290-9a41-4ba0-8767-28864dec25f9.png)

Thank you for the suggestion. Let's keep as separate sections for now.

**Comment by swagataroy30** [comment]
> > @SaraJaoude is it what you were suggesting? would really like your views on it @eddiejaoude ... and just to add my views - not all events excluding the past events are `future events` - there are also some `ongoing events` that's happening, so can we do something like this ? - i'll add some snaps below  ![Screenshot from 2023-02-05 22-06-38](https://user-images.githubusercontent.com/116095538/216832124-b81a915d-a173-447a-a19f-36ea7ba6112b.png)
> 
> Like the idea - let's go for it

Ok thanks!

**Comment by swagataroy30** [comment]
> > ![Screenshot from 2023-02-05 20-17-06](https://user-images.githubusercontent.com/116095538/216827347-edda96ff-f3b8-4ab6-b805-fa60a05e5890.png)
> > And what about the community events. Any suggestions? It's a snap after I added the past events !
> 
> Let's leave this for now as I don't think past community events are so important

Ok then I will be dropping the past events from `Community Events` !

**Comment by Aadarsh805** [comment]
closing this issue #4552
