### ISSUE TITLE
[FEATURE] button should open discussion page on next tab

### ISSUE THREAD

**Issue by alokVerma749** [EddieHubCommunity/LinkFree#4360]
### Description

can we do this, or it is fine as it is?

### Screenshots

![image](https://user-images.githubusercontent.com/87599400/216142445-17a867c5-7569-42f2-a9d6-785f5911b96f.png)

**Comment by hirentimbadiya** [comment]
is this issue still open ? if it is i can work on this. can you assign me?

**Comment by alokVerma749** [comment]
actually PR: #4361 already been made on this issue
