### ISSUE TITLE
[FEATURE] Add Email to Social Media list

### ISSUE THREAD

**Issue by merouanezouaid** [EddieHubCommunity/LinkFree#437]
### Description

LinkFree will mostly be used for professional contact so I think that adding Emails (Gmail, Outlook, etc...) is required.

### Screenshots

![image_2021-10-03_112951](https://user-images.githubusercontent.com/74367730/135749748-180b65af-2ef9-4971-ba72-fba5c90471f7.png)

### Additional information

Please assign me to it  I'm already working on it .. Thank you!

**Comment by krishdevdb** [comment]
Can I get this issue?

**Comment by krishguptadev** [comment]
Can I work upon this issue?

**Comment by merouanezouaid** [comment]
> Can I work upon this issue?

I've already worked on it

**Comment by krishguptadev** [comment]
Oh cool 🚀

**Comment by Omkar845** [comment]
can i work on this issues plz

**Comment by krishguptadev** [comment]
A pr has been already made, but you can look up to other issues :-)

**Comment by eddiejaoude** [comment]
PR merged, there are other socials that can be added 👍

**Comment by Omkar845** [comment]
> PR merged, there are other socials that can be added 👍

Can you assign me to add other social
