### ISSUE TITLE
[enhancement]Adding Skeleton while profile is loading

### ISSUE THREAD

**Issue by suhail34** [EddieHubCommunity/LinkFree#443]
### Description

I think instead of ProgressBar there should be Skeleton when loading the profile
For reference : https://primefaces.org/primereact/showcase/#/skeleton

### Additional information

Changes to be made in 
1. https://github.com/EddieHubCommunity/LinkFree/blob/main/src/Components/Socials.js
2. https://github.com/EddieHubCommunity/LinkFree/blob/main/src/Components/Home.js

If the feature looks good i would like to make a pr

**Comment by krishguptadev** [comment]
How does that affect the project? I think progressbars are better in terms of ux

**Comment by suhail34** [comment]
Acually the progressBar was looking large so i tried using progressSpinner and it was looking good so i raised this issue

**Comment by krishguptadev** [comment]
You can instead make the progress bar smaller 🙂

**Comment by Bhavyawahie** [comment]
Loading spinner certainly looks better as far as UI is concered

**Comment by krishguptadev** [comment]
I mentioned ux not ui 🙂 But if we wanna consider both of them, let's use skeletons for the complete project

**Comment by suhail34** [comment]
So should i close this issue

**Comment by krishguptadev** [comment]
If you want you can make a pr for skeletons 🙂

**Comment by Panquesito7** [comment]
> Should i make a pr or wait?

Feel free to make a PR. 🙂

**Comment by Vyvy-vi** [comment]
this issue has been resolved by fbac8f7
