### ISSUE TITLE
[FEATURE] Remove unused js

### ISSUE THREAD

**Issue by ManishBisht777** [EddieHubCommunity/LinkFree#4434]
### Description

There is a lot of unused javascript which is being loaded in `icon.js`
Here we are importing all the icons from `react-icons/fa` and `react-icons/si` but we only need a handful of them 

So I think instead of importing all we can import individual icons here and then export them

### Screenshots

![image](https://user-images.githubusercontent.com/89926834/216592478-c1d3efd5-8178-4323-b01b-f738b2ab7b21.png)

**Comment by Vishrut19** [comment]
Hey @ManishBisht777 and @Pradumnasaraf! Can I try to work on this issue?

**Comment by moaoa** [comment]
please what is the tool you used to produce this result @ManishBisht777  ?

**Comment by ManishBisht777** [comment]
> please what is the tool you used to produce this result @ManishBisht777 ?

I used lighthouse for this

**Comment by priyankarpal** [comment]
Check I found another one.
![Screenshot from 2023-02-03 22-24-22](https://user-images.githubusercontent.com/88102392/216661306-01bb0356-e1c5-4551-8715-f43647ef3e97.png)

**Comment by moaoa** [comment]
if we are using Webpack we can use the WebpackExports feature to make the tree shake the dynamic imports in the icon.js file 
I would love to help with this issue if I can

**Comment by SaraJaoude** [comment]
Thank you for the suggestion.  Performance improvements to the icons have just been merged in this Pull Request: https://github.com/EddieHubCommunity/LinkFree/pull/4435

So I shall be closing this issue.
