### ISSUE TITLE
[FEATURE] change styling in components/Link.js 🐧

### ISSUE THREAD

**Issue by mpotane** [EddieHubCommunity/LinkFree#4444]
## Here's an idea

- Change dotted to no-underline
- Add offset for underline equal to 4
- Clean tailwind classes

### Screenshots

Sample

> https://www.w3schools.com/css/tryit.asp?filename=trycss_link_decoration

**Comment by Sreekar-Tammana** [comment]
Hello there, I would like to work on this issue. Can you please assign me to this?

**Comment by SaraJaoude** [comment]
Thank you for your suggestion but we will be keeping the link styles we have at the moment, so I will close this issue.
