### ISSUE TITLE
[FEATURE] Change the events filter cards to dropdown

### ISSUE THREAD

**Issue by MitAbhay** [EddieHubCommunity/LinkFree#4445]
### Description

We can change our filter cards of the events to the dropdown, it will be more attractive.

### Screenshots

Before
![image](https://user-images.githubusercontent.com/76659113/216591053-83709f12-b242-41c0-8590-9ed8ca95bc3a.png)

After
![image](https://user-images.githubusercontent.com/76659113/216664362-8d46482d-72c6-452c-b3c3-08f90353db93.png)

**Comment by Ananya2001-an** [comment]
@MitAbhay Though the drop-down is much cleaner still the cards make the UI look much better I guess.

**Comment by abhijain2003** [comment]
can I work on this?

please

**Comment by MitAbhay** [comment]
> @MitAbhay Though the drop-down is much cleaner still the cards make the UI look much better I guess.

But these cards are consuming too much space and looking not that good, what else we can do according to you?

**Comment by Ananya2001-an** [comment]
Since this requires UI update we need to ask the mainteners of the project about it before proceeding any further. @eddiejaoude your suggestions?

**Comment by abhijain2003** [comment]
that's true

**Comment by SaraJaoude** [comment]
Thank you for your suggestion.  We are looking into ways to have this filter be reusable on the Profile Events section and the Community Events page.  I will close this and we will raise further issues when we have a solution.
