### ISSUE TITLE
[FEATURE] Provide Placeholder for Profile page during loading

### ISSUE THREAD

**Issue by nivendha** [EddieHubCommunity/LinkFree#445]
### Description

It would be better to have a placeholder for the images and text button , rather than a progress bar for loading the profile page content

**Comment by nivendha** [comment]
I like to work on this

**Comment by krishguptadev** [comment]
imho Skeletons would be better...

**Comment by Vyvy-vi** [comment]
this issue has been resolved by fbac8f7
