### ISSUE TITLE
Navbar items shrinks to centre after login feature

### ISSUE THREAD

**Issue by alokVerma749** [EddieHubCommunity/LinkFree#4496]
### Description

After addition of the login button, all navbar items shrink to the center, leaving blank spaces at both ends 

## Before fix
![image](https://user-images.githubusercontent.com/87599400/216805271-47293852-4e6d-4ee1-b33b-567d76b4ad2b.png)

![image](https://user-images.githubusercontent.com/87599400/216805223-710e5f96-fcdc-45fd-80f7-ad835dd545b0.png)
## After fix(change proposed)
![image](https://user-images.githubusercontent.com/87599400/216805286-9d191da1-c00b-49e3-a0e8-2a95d180ca7e.png)

![image](https://user-images.githubusercontent.com/87599400/216805254-af6707af-eac1-4495-be9c-9ddfd71b5e6f.png)

### Additional information

I made some changes regarding this issue, let me know  you thought on this issue

**Comment by eddiejaoude** [comment]
Thank you for the suggestion. I don't think we need this change now. 

The Navbar buttons are always the same width of the contents of the page - I think it is best to keep it the same for now, so I will close this issue
