### ISSUE TITLE
[BUG] - Navbar items not "center" transition from mobile to desktop screen

### ISSUE THREAD

**Issue by JunDevHarsh** [EddieHubCommunity/LinkFree#4499]
### Description

After signing in successfully using the GitHub account, when the user tries to transition from mobile to desktop screen then the navbar menu items are not properly centered.

### Screenshots

![issue](https://user-images.githubusercontent.com/94737463/216806576-2d613583-e066-4100-8969-ee2a233c1dc2.png)

### Additional information

Here is the screenshot attached to get the result that is expected.

![solve](https://user-images.githubusercontent.com/94737463/216806629-327e9ef5-48e0-4013-882d-dc0cfa87ef77.png)

**Comment by JunDevHarsh** [comment]
Can I work on this issue?

**Comment by SaraJaoude** [comment]
@JunDevHarsh I have assigned this to you. Please rename `Community Events` to `Events` and this will resolve the problem.

**Comment by JunDevHarsh** [comment]
@SaraJaoude Thank you for assigning this bug to me. I will work on resolving it as soon as possible. Additionally, I have noted the change that you mentioned and will keep that in mind as I work on the bug. I appreciate the opportunity to contribute to this project and look forward to updating you on my progress.

**Comment by kumarsonsoff3** [comment]
closing being completed by #4548
