### ISSUE TITLE
[BUG] Storybook Navbar Component: TypeError: Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by Saadat-B** [EddieHubCommunity/LinkFree#4500]
## Description

I'm getting this error - Cannot read properties of undefined (reading 'data')

The error is being thrown at the following link: https://eddiehubcommunity.github.io/LinkFree/?path=/story/components-navbar-navbar--basic

The error occurs in the Storybook Navbar component and is related to reading the property 'data'

![Screenshot from 2023-02-05 11-14-18](https://user-images.githubusercontent.com/70024383/216806126-a13ddb0c-ef9a-4ee6-a7b7-bc4adfe84db0.png)

## Steps to Reproduce - 

Access the page at https://eddiehubcommunity.github.io/LinkFree/?path=/story/components-navbar-navbar--basic

Go to components/navbar/Navbar/Basic

Observe the error being thrown in the Navbar component

## Expected Behavior -

The 'data' property should be successfully read without errors and it should display the navbar component

![Screenshot from 2023-02-05 12-44-02](https://user-images.githubusercontent.com/70024383/216806721-af55688e-ab7f-41a8-a37a-06a5217cc3d1.png)

### Additional information

A full stack trace of the error is provided below:

```console
TypeError: Cannot read properties of undefined (reading 'data')
    at Navbar (https://eddiehubcommunity.github.io/LinkFree/pages-username-stories.317d149d.iframe.bundle.js:1:10794)
    at Xh (https://eddiehubcommunity.github.io/LinkFree/475.0ea6cbd8.iframe.bundle.js:517:694469)
    at Wk (https://eddiehubcommunity.github.io/LinkFree/475.0ea6cbd8.iframe.bundle.js:517:750962)
    at Vk (https://eddiehubcommunity.github.io/LinkFree/475.0ea6cbd8.iframe.bundle.js:517:740158)
    at Uk (https://eddiehubcommunity.github.io/LinkFree/475.0ea6cbd8.iframe.bundle.js:517:740089)
    at Jk (https://eddiehubcommunity.github.io/LinkFree/475.0ea6cbd8.iframe.bundle.js:517:739958)
    at Ok (https://eddiehubcommunity.github.io/LinkFree/475.0ea6cbd8.iframe.bundle.js:517:736814)
    at Hk (https://eddiehubcommunity.github.io/LinkFree/475.0ea6cbd8.iframe.bundle.js:517:735369)
    at J (https://eddiehubcommunity.github.io/LinkFree/475.0ea6cbd8.iframe.bundle.js:517:789168)
    at MessagePort.R (https://eddiehubcommunity.github.io/LinkFree/475.0ea6cbd8.iframe.bundle.js:517:789718)
```

**Comment by eddiejaoude** [comment]
I get a different error. Please check you have the latest changes from `main` and you also have done `npm ci`.

The error I get is because the component needs to be wrapped in `SessionProvider` for Storybook

<img width="1679" alt="Screenshot 2023-02-05 at 14 52 25" src="https://user-images.githubusercontent.com/624760/216807860-dedd62b3-cfd2-40e7-93b2-3070a1b6d6a6.png">

**Comment by Saadat-B** [comment]
> I get a different error. Please check you have the latest changes from main and you also have done npm ci.

> The error I get is because the component needs to be wrapped in SessionProvider for Storybook

> We might need to use a plugin for Storybook to help mock a logged in user https://storybook.js.org/addons/@tomfreudenberg/next-auth-mock


I followed the above steps and got the same error as you.

So I installed the plugin: next-auth-mock and followed the instructions in the link provided by you

I updated `.storybook/main.js` and appended the list of addons with `@tomfreudenberg/next-auth-mock/storybook` - 

```javascript
addons: [
    "@storybook/addon-essentials",
    "@storybook/addon-a11y",
    "@tomfreudenberg/next-auth-mock/storybook",
  ]
```


After doing the above the error dissappeared without even wrapping the Navbar component in storybook with `SessionProvider`


So is this okay or should I still wrap the component?

![storybook-navbar-login](https://user-images.githubusercontent.com/70024383/216817923-a7803000-b06e-45e9-81ef-90546a78721f.png)

![storybook-navbar-logout](https://user-images.githubusercontent.com/70024383/216817945-8889f0e6-9731-4e70-9dbc-b85631fb4c72.png)





Also the plugin has provided 6 default set of auth states: `session unknown`, `session loading`, `admin not authenticated`, `admin authenticated`, `user not authenticated`, `user authenticated`.

<img width="191" alt="auth-state" src="https://user-images.githubusercontent.com/70024383/216818267-96e62b6b-7adf-4ce8-8bf1-2556b1afa116.png">

If I select any one of these two states - `session unknown`  `session loading`. I will see the Navbar component with the Login button.

![login-btn](https://user-images.githubusercontent.com/70024383/216818476-cf5bd38b-326a-4025-89e5-5014cf3d67ab.png)

If I select any one of these four states - `admin not authenticated` `admin authenticated` `user not authenticated` `user authenticated` I will see the Navbar component with the Logout button.

![logout-btn](https://user-images.githubusercontent.com/70024383/216818604-712b434b-0798-42ed-9df8-2c46704f1676.png)


I tried to customize these auth states but got a webpack error and couldn't debug it so I think we should create a separate issue and PR for customizing these states. What do you think?

**Comment by SaraJaoude** [comment]
@Saadat-B as you raised this Issue and come up with a solution, I have assigned this to you.

**Comment by Saadat-B** [comment]
> Oh great, that sounds good if you don't need to wrap it after using the plugin 👍

Nice then I'll create the PR soon 👍
