### ISSUE TITLE
[DOCS] Extra text

### ISSUE THREAD

**Issue by rohinish404** [EddieHubCommunity/LinkFree#4506]
### Description

There's a extra "and the" in the documentation layout which should be removed as there are no links after that.

### Screenshots

<img width="1434" alt="Screenshot 2023-02-05 at 4 31 18 PM" src="https://user-images.githubusercontent.com/92542124/216815158-6db56573-4674-4a13-b385-7f6bc186d0f8.png">

**Comment by rohinish404** [comment]
Will make a pr regarding this :)

**Comment by rohinish404** [comment]
Im trying to make a pr but when i compare the changes it's showing me changes in 4 files(changelog.md,package-lock.json,package.json and the layout one which im actually trying to make a change) the other three are getting changed automatically. What should i do?

**Comment by swagataroy30** [comment]
> Im trying to make a pr but when i compare the changes it's showing me changes in 4 files(changelog.md,package-lock.json,package.json and the layout one which im actually trying to make a change) the other three are getting changed automatically. What should i do?

did you use `npm install` to install the dependencies? try using `npm ci` .

**Comment by rohinish404** [comment]
Yeah i first used npm install but after watching the video i tried npm ci..still same

**Comment by swagataroy30** [comment]
> Yeah i first used npm install but after watching the video i tried npm ci..still same

https://www.youtube.com/watch?v=jHkIXYVpMTo&t=270s check this part of the video it shows the solution to it

**Comment by Deva-1903** [comment]
I've fixed and opened a PR for this.🙂

**Comment by rohinish404** [comment]
Oh that's great!!
U faced the issue of files getting changed automatically?

**Comment by Deva-1903** [comment]
No, everything worked fine. Where do you face the issues of files changing automatically?

**Comment by Deva-1903** [comment]
@rohinish404 This is just a doc change right so I didn't do the npm install.

**Comment by rohinish404** [comment]
Oh yeah..that makes sense. Awesome!!🙂👍
