### ISSUE TITLE
Latest features and upcoming features

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/LinkFree#4510]
### Description

Hi there! I saw someone suggest this feature in the comment section of one of Eddie’s LinkedIn post and thought it’d be worth adding here:
“It would be great to have a section on the Docs for the new features coming up so that the users can keep themselves updated”. What do you think @eddiejaoude?

**Comment by saaagarsingh** [comment]
Hey @SaraJaoude I would love to work on this but there are some doubts that I just want to clear? 
1. Do i need to add a new section into the doc with heading new features?
2. Or I have to add a subsection into some other section?
3. Are there any new features that would appear in this??

**Comment by SaraJaoude** [comment]
> Hey @SaraJaoude I would love to work on this but there are some doubts that I just want to clear?
> 
@saaagarsingh I would recommend that you check the labels of the Issue before starting any work.  This Issue shows the label `status: awaiting triage`. Please wait until the maintainers review the Issue and update the label to `status: ready for dev` and then please ask to be assigned the Issue.

**Comment by SaraJaoude** [comment]
Great idea @CBID2.  This needs some thought and planning, but something to consider for the near future.

**Comment by eddiejaoude** [comment]
This has now been implemented https://linkfree.eddiehub.io/changelog
