### ISSUE TITLE
Border of Login Button touches GitHub Icon 

### ISSUE THREAD

**Issue by anikdhabal** [EddieHubCommunity/LinkFree#4514]
### Description

When the screen size is small, border of login button touches GitHub Icon.  So, when I hover over the login button it occurs.

### Screenshots

<img width="390" alt="Screenshot 2023-02-05 202709" src="https://user-images.githubusercontent.com/81948346/216827301-ebe0e2d7-3b84-4068-bcb3-2cee28d0a832.png">

**Comment by anikdhabal** [comment]
Can I work on this issue?

**Comment by prakhartiwari0** [comment]
The same is happening on the Desktop.

![image](https://user-images.githubusercontent.com/65062036/216829111-8074f55e-b5c2-46bf-995b-11a1cc38f831.png)

**Comment by prakhartiwari0** [comment]
I can solve this issue, you may assign me or the person commented above

**Comment by alokVerma749** [comment]
@prakhartiwari0 I think this layout is provided by next-auth package itself. Can we change it?

**Comment by Vishrut19** [comment]
Hey @Pradumnasaraf! Can I take up this issue?

**Comment by SaraJaoude** [comment]
> ### Description
> When the screen size is small, border of login button touches GitHub Icon. So, when I hover over the login button it occurs.
> 
> ### Screenshots
> <img alt="Screenshot 2023-02-05 202709" width="390" src="https://user-images.githubusercontent.com/81948346/216827301-ebe0e2d7-3b84-4068-bcb3-2cee28d0a832.png">

Good spot! I will assign this to you @anikdhabal

**Comment by SaraJaoude** [comment]
> @prakhartiwari0 I think this layout is provided by next-auth package itself. Can we change it?

Yes this is correct. We can override the page but this is not something we want to do at this time.

**Comment by SaraJaoude** [comment]
> Hey @Pradumnasaraf! Can I take up this issue?

Tagging individual maintainers creates more notifications for them.  All maintainers are notified of project activity. Please avoid tagging people unless it is absolutely necessary.

**Comment by Vishrut19** [comment]
Sure Sara and sorry for it! It won't happen again.
