### ISSUE TITLE
Navigation to another page is taking time and not showing loading state

### ISSUE THREAD

**Issue by bharat5604** [EddieHubCommunity/LinkFree#4532]
### Description

when navigating to another page. redirection is taking time and not showing loading

**Comment by Vishrut19** [comment]
what type of loading state do you think it should have? @bharat5604

**Comment by SaraJaoude** [comment]
There is an issue already open for this: https://github.com/EddieHubCommunity/LinkFree/issues/3900

I will be closing as this is a duplicate.
