### ISSUE TITLE
[BUG] Old event count still showing on profile

### ISSUE THREAD

**Issue by Aadarsh805** [EddieHubCommunity/LinkFree#4552]
### Description

After the events are over, they get deleted from the profile but the count doesn't go down

### Screenshots

As you can see here, Now that HackThisFall is over, that I was attending
it's been deleted from my events but the count is still 1

![Screenshot from 2023-02-06 23-26-02](https://user-images.githubusercontent.com/95094057/217049563-e491fa68-ae23-428a-9af9-7bab2584a3a5.png)

### Additional information

Not sure if that's intentional, maybe to showcase that users have attended or gonna be in these many events
if that's the case, it's not being correctly representing that, It's representing that you'll find that number of events when clicked on events tab

**Comment by swagataroy30** [comment]
This issue can come under #4358. When we add the past events - Events(1) will make sense .

**Comment by Aadarsh805** [comment]
> This issue can come under #4358. When we add the past events - Events(1) will make sense .
