### ISSUE TITLE
Rename the files from .js to .jsx

### ISSUE THREAD

**Issue by ChinmayMhatre** [EddieHubCommunity/LinkFree#4581]
### Description

Renaming the .js file to .jsx can help vscode recognise the files and the developer can user the snippets similar to html.
This can be done with a .js file as well by changing the language mode to `javascript react` But I feel changing the file name would be a better thing to do.

### Screenshots

Here is a demo with `.js` as file extension

https://user-images.githubusercontent.com/51131670/217241776-198241cd-abb4-4274-aece-ccd2abae086e.mov

Here is a demo with `.jsx` as the file extension

https://user-images.githubusercontent.com/51131670/217241866-f5253fc4-11f5-404c-8523-8b7e887bb4a9.mov

**Comment by ankitjangidx** [comment]
hello @ChinmayMhatre, can u assign it to me ? i will do it.

**Comment by ChinmayMhatre** [comment]
> hello @ChinmayMhatre, can u assign it to me ? i will do it.

Hey @ankitjangidx , let one of the maintainers confirm the status and then they can assign you. Thank you!

**Comment by eddiejaoude** [comment]
Thanks @ChinmayMhatre for the suggestion and great demo videos 👍 

I don't think this change is required, it also can cause confusion for people learning javascript. From what I understand the React community are preferring the `.js` extension more and more.
