### ISSUE TITLE
[BUG] Community events heading not alligned to the hinticon

### ISSUE THREAD

**Issue by Aadarsh805** [EddieHubCommunity/LinkFree#4627]
### Description

The `h1` on the heading of the events page is not aligned with the `HintIcon`

### Screenshots

![Group 49 (3)](https://user-images.githubusercontent.com/95094057/217733325-f95fa4cf-3cbf-4065-be68-4e58aa5a469b.png)

### Additional information

this is because there is a margin-bottom is on `h1` instead of the parent div containing both `h1` and `HintIcon`

**Comment by eddiejaoude** [comment]
Thank you, I am fixing this as part of my refactor badges PR https://github.com/EddieHubCommunity/LinkFree/pull/4479

**Comment by ChinmayMhatre** [comment]
I believe this got fixed in the PR Eddie mentioned. So the issue can be closed.

**Comment by Aadarsh805** [comment]
> I believe this got fixed in the PR Eddie mentioned. So the issue can be closed.

Oh that pr got merged, cool closing this then
