### ISSUE TITLE
New Testimonial for Francesco Ciulla

### ISSUE THREAD

**Issue by oyenolaphilipinc** [EddieHubCommunity/LinkFree#4635]
### Name

FrancescoXX

### Title

Amazing Leader and mentor

### Description

Francesco is a great mentor, leader and role model in the tech space. His unbeatable contributions in open source makes him an outstanding person and also a great leader in the open source and tech space.

**Comment by FrancescoXX** [comment]
thanks @oyenolaphilipinc
