### ISSUE TITLE
[BUG] Mobile responsiveness issue: Navbar not covering full screen width

### ISSUE THREAD

**Issue by Saadat-B** [EddieHubCommunity/LinkFree#4657]
### Description

The Navbar in the statistics page does not seem to cover the full width of the screen on mobile in the deployed version of LinkFree, however the navbar seems to cover the full width of the screen on mobile when I tried to recreate it locally.
 
Screenshot of the page on the `Deployed version`

![navbar-bug-deployed](https://user-images.githubusercontent.com/70024383/218010966-7bbcf896-bdf4-4b3c-9492-9fed7752a1ac.png)

Screenshot of the page on the `Local Build`

![navbar-bug-local](https://user-images.githubusercontent.com/70024383/218011061-a4369b02-dd16-4b7b-855b-ec4c6966c975.png)

**Comment by Saadat-B** [comment]
I found the bug it is in the table which is displaying the clicks and links. If the url name is too long like in this case this link `https://www.linkedin.com/in/saadat-badgujar-ba85b5211/` then the table expands and overflows and causes this issue.
I think I can solve this issue by using text-overflow: ellipsis; which will append `...` at the end of a long link and shorten it's length.
May I be assigned to this Issue?

**Comment by dan-mba** [comment]
I think the problem is caused by the `whitespace-nowrap` class [here](https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/account/statistics.js#L149)

Changing the class to `md:whitespace-nowrap` will set the nowrap to only happen on larger screens.

Have you tried clicking on the links on your profile locally to generate the table?
This will be difficult to test without a way to reproduce

**Comment by Saadat-B** [comment]
> I think the problem is caused by the whitespace-nowrap class [here](https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/account/statistics.js#L149)
Changing the class to md:whitespace-nowrap will set the nowrap to only happen on larger screens.

Okay thanks will test this out and will let you know.

>Have you tried clicking on the links on your profile locally to generate the table?

Yes I did click on the links and generated the table locally. Before clicking on the links everything was fine.

> This will be difficult to test without a way to reproduce

Right, I'm working on the steps to reproduce the bug right now, will give an update soon.

**Comment by Saadat-B** [comment]
> I think the problem is caused by the whitespace-nowrap class [here](https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/account/statistics.js#L149)
Changing the class to md:whitespace-nowrap will set the nowrap to only happen on larger screens.

> Okay thanks will test this out and will let you know.

Changing the class to `md:whitespace-nowrap` has fixed the bug, thanks Dan 👍

I tested all three links to see which one causes the bug and it was the longest link which was causing it and after adding the class as you suggested it wrapped the link and the bug was fixed. 

## Here are the steps to reproduce the bug:

1. Click a link on your profile
2. Go to the statistics page under the bar chart to see the generated table with the link
3. Go to mongodb > linkfree > links
4. Edit the URL of the link
5. Increase the length of the URL by adding characters
6. Observe that the table overflows and causes the bug to occur


Let me know if this is okay then I'll proceed with the pull request

**Comment by dan-mba** [comment]
Great work, let me know if you need any help with the PR.

**Comment by Saadat-B** [comment]
Thank you Dan! 👍🏻
Will reach out to you if I need any help 😄

**Comment by eddiejaoude** [comment]
I can't reproduce this issue? Here is the result on the smallest screen option...

<img width="715" alt="Screenshot 2023-02-12 at 07 40 38" src="https://user-images.githubusercontent.com/624760/218287112-9c6e848c-2e2f-4858-aef9-4454a6ce4ea0.png">

**Comment by dan-mba** [comment]
@eddiejaoude The overflow is caused by the table below the bar chart.

**Comment by Saadat-B** [comment]
> I can't reproduce this issue? Here is the result on the smallest screen option...

@eddiejaoude I think I missed to include one step in the steps to reproduce. After step 5 which is adding characters to the URL you need to do `npm run dev` to see the changes occur. 

I was able to reproduce the issue just now here's the screenshot of the same, can you please try again and also share the length of the URL if possible?

![Screenshot from 2023-02-12 08-43-33](https://user-images.githubusercontent.com/70024383/218291139-23d8a806-a4f1-427f-8f89-3bf36f8592e8.png)

**Comment by krshkun** [comment]
@eddiejaoude the issue is caused by long links, I think we just have to add the class `max-w-prose` and that should solve the problem

**Comment by zaidahmad25** [comment]
What is the status of this issue?

**Comment by Saadat-B** [comment]
Waiting for Eddie's response

**Comment by SyedImam1998** [comment]
Hey @Saadat-B  I solved this issue regarding the nav-bar for the Documentation page earlier.
Please look my PR I guess it would help you.

[Old PR](https://github.com/EddieHubCommunity/LinkFree/pull/4448)
