### ISSUE TITLE
[FEATURE] Search Page - also search for username

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/LinkFree#4660]
### Description

In the search page searching also for the github username should be possible

**Comment by joeshajan** [comment]
Can you assign this to me @eddiejaoude? I would like to work on this.

**Comment by swagataroy30** [comment]
Hey this seems to be a duplicate issue for #4124

**Comment by eddiejaoude** [comment]
Good spot 👍 I will close this duplicate

**Comment by eddiejaoude** [comment]
> Can you assign this to me @eddiejaoude? I would like to work on this.

Please only request 1 issue at a time

**Comment by schmelto** [comment]
> Hey this seems to be a duplicate issue for #4124

Thanks for spotting this I guess I missed that there is already an issue open for this topic.
