### ISSUE TITLE
[BUG] Typo in the alert message in statistics.js

### ISSUE THREAD

**Issue by Saadat-B** [EddieHubCommunity/LinkFree#4708]
### Description

There is a typo on line 101 in the Alert message of the [pages/account/statistics.js](https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/account/statistics.js#L101) file. The word `proile` should be `profile`

![Screenshot from 2023-02-11 21-47-21](https://user-images.githubusercontent.com/70024383/218268951-9c14d6d3-8b2c-484b-9ef3-b9a6db49901d.png)

**Comment by Saadat-B** [comment]
I have the PR ready to go. May I be assigned to this issue 🙂

**Comment by eddiejaoude** [comment]
Sure, assigned to you
