### ISSUE TITLE
"Copied icon to Clipboard" dialog box gets partially hidden under the navbar

### ISSUE THREAD

**Issue by swagataroy30** [EddieHubCommunity/LinkFree#4729]
### Reproduce The Error

- Go to - https://linkfree.eddiehub.io/icons
- Search for an icon and then click on the IconCard
- The "Copied `icon` to Clipboard" dialog box gets hidden under the navbar.

### Issue

https://user-images.githubusercontent.com/116095538/218293677-478ab8f8-a9b5-450f-95e3-036fb74f046d.mp4

**Comment by GauravBurande** [comment]
Can I work on this issue?

**Comment by GauravBurande** [comment]
z-index 30 of the navbar is causing this issue, should I set the z-index of IconCard to 40?

**Comment by GauravBurande** [comment]
I've already made the changes, let me know if I should proceed with a pull request after getting assigned.

**Comment by krshkun** [comment]
Go ahead @GauravBurande ✅ Don't need assignment, also- I don't think we should just change the z-index, maybe fix the overflow problem?

**Comment by GauravBurande** [comment]
> Go ahead @GauravBurande ✅ Don't need assignment, also- I don't think we should just change the z-index, maybe fix the overflow problem?

I checked the code, I think it's not overflow problem,

**Comment by eddiejaoude** [comment]
> I've already made the changes, let me know if I should proceed with a pull request after getting assigned.

thank you, I have now assigned it to you 👍 this avoids multiple people working on the same issue

**Comment by GauravBurande** [comment]
> > I've already made the changes, let me know if I should proceed with a pull request after getting assigned.
> 
> thank you, I have now assigned it to you 👍 this avoids multiple people working on the same issue

I just need your opinion on this. 

Should I set the Alert's zindex to 40 which displays it over Navbar, covers version and login only for 1.5sec and keep it at its old position or as @swagataroy30 suggested to move the Alert's position to bottom center, which is same position as in mobile view.

**Comment by GauravBurande** [comment]
I'd keep it in its old place, instead of placing it at the bottom center.

**Comment by GauravBurande** [comment]
I closed the recent pr and created changes in the new pr to avoid the whole confusion.

**Comment by eddiejaoude** [comment]
I think over the navbar is fine and the default position 👍

**Comment by GauravBurande** [comment]
formatting changes are made in pr #4771 and this issue is solved in pr #4777
