### ISSUE TITLE
Merge the following PR

### ISSUE THREAD

**Issue by RockingSNP** [EddieHubCommunity/LinkFree#4732]
Please merge this now

_Originally posted by @RockingSNP in https://github.com/EddieHubCommunity/LinkFree/issues/4700#issuecomment-1426952233_

**Comment by ChinmayMhatre** [comment]
Hey @RockingSNP , once the maintainers go through the PR it will get merged. Since it is a PR adding/updating your profile you do not need to create an issue. Thank you!

**Comment by RockingSNP** [comment]
Yeah I will keep that in my mind

**Comment by krshkun** [comment]
I would not suggest creating such issues, these just add to the notifications and make the process of merging your PR slower
