### ISSUE TITLE
Profile Views statistics not showing properly

### ISSUE THREAD

**Issue by SandipPalit** [EddieHubCommunity/LinkFree#4768]
### Description

As per the screenshot attached below, my profile views is "**415 from 416**". That means It decreased by 1. But on the right side it is showing as ''increased by **1**".

I believe it should be shown as "**416 from 415**".

### Screenshots

![image](https://user-images.githubusercontent.com/48781286/218364347-6925db61-fa1d-482c-8384-2de1f470d2b7.png)

**Comment by Aadarsh805** [comment]
it's actually correct, it says You have 415 Profile views in the last 30 days with a total of 416.
The 1 represents the increase in views from the previous period: `416 - 415`

**Comment by Aadarsh805** [comment]
I believe it can be represented with more clarification

**Comment by SandipPalit** [comment]
ohh okay.. Thanks for your clarification @Aadarsh805
