### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Guneetsinghtuli** [EddieHubCommunity/LinkFree#477]
### Description

The dimensions that are mentioned in the manifest.json for the icons don't seem to be the same as the actual size for both the `logo192.png` and `logo512.png`.

### Screenshots

![Screenshot 2021-10-08 at 8 25 58 PM](https://user-images.githubusercontent.com/48324492/136579374-988287b7-e5e1-4424-aea8-ab2ffaec89cd.png)

### Additional information

It's a beginner-friendly issue to solve and if you are having experience in this project kindly leave it for other newcomers. If anyone is not able to solve it feel free to ask me on the discord server or tag me here, I will help you out.

**Comment by kkhitesh** [comment]
@krishguptadev leave it for beginners 😆

**Comment by RagibAjmal** [comment]
I would like to work this issue @Guneetsinghtuli

**Comment by RagibAjmal** [comment]
sure @krishguptadev
