### ISSUE TITLE
[FEATURE] Accessibility: make QR-code bouncing effect opt-in

### ISSUE THREAD

**Issue by SavvasStephanides** [EddieHubCommunity/LinkFree#4792]
### Description

Currently the QR-code image for each profile has a bouncing effect which can be distracting for users that need reduced motion. An option is to have the bouncing effect turn off when the user has chosen to have their "reduced motion" setting turned on.

### Screenshots

Current implemention with QR code bouncing effect:

https://user-images.githubusercontent.com/478770/218465218-d2a85dab-9a71-4365-914e-2c9774f9c79f.mov

Possible implemention with "reduced motion" on:

https://user-images.githubusercontent.com/478770/218465423-ad796d26-571d-4b2f-9aad-afe06f9781b2.mov

### Additional information

This can be implemented with the `motion-safe` variants in Tailwind.

**Comment by SavvasStephanides** [comment]
This is something I can pick up and implement if you decide to assign me this issue.

**Comment by Vishrut19** [comment]
I may also help you @SavvasStephanides  with this or maybe try it !

**Comment by SavvasStephanides** [comment]
Thank you @Vishrut19. This seems like a fairly small change that I've already tested locally. If you get assigned to this issue, I'll be more than happy to help 👊

**Comment by SaraJaoude** [comment]
Thank you for your suggestion.  I don't think this needs to be configurable as it will add more complexity to the project and not a lot of value.  As we have had some feedback that this effect can be distracting, let's remove it for everyone.

@SavvasStephanides as you suggested this, I will assign it to you.

**Comment by SavvasStephanides** [comment]
Thank you @SaraJaoude!
