### ISSUE TITLE
Account button doesn't do anything

### ISSUE THREAD

**Issue by Ananya2001-an** [EddieHubCommunity/LinkFree#4800]
### Description

After logging into LinkFree, there are 2 buttons at the top among which the Account button is not doing anything. Maybe it should show some information about the current user who is logged in rather than a button.  

### Screenshots

https://www.awesomescreenshot.com/video/14774892?key=3b8272099061db1358167aefa3b2c8b4

**Comment by swagataroy30** [comment]
The account button actually shows the account statistics. Let's say you navigate away from `Account` to `Docs` or `Map` and then if you click on `Account` it will show your account statistics.

**Comment by Ananya2001-an** [comment]
Ok got it. I didn't check it properly. I will close this issue now.
