### ISSUE TITLE
[FEATURE] Add a debounce in search to improve speed

### ISSUE THREAD

**Issue by SageKyle** [EddieHubCommunity/LinkFree#4806]
### Description

The search feature lags a lot and I believe it would be better to add a debounce function which will trigger the querying after a certain delay time.

**Comment by ChinmayMhatre** [comment]
This seems like a good idea. I'd like to implement this after this issue is accepted by the maintainers.

**Comment by ChinmayMhatre** [comment]
I just looked the the code in `search.js` a debounce is already implemented there I believe.
<img width="369" alt="image" src="https://user-images.githubusercontent.com/51131670/218663652-faf394d2-51e5-4c59-bc97-c0fb6841094f.png">

**Comment by ManishBisht777** [comment]
debounce function is implemented but a search with just only 1 or 2 characters is a bit laggy this is something that is done backend part

**Comment by SageKyle** [comment]
> debounce function is implemented but a search with just only 1 or 2 characters is a bit laggy this is something that is done backend part

I think you can implement this by checking the length of `inputValue` (if it's equal to 3) before calling `filtetData(arg)`, just as it's done in the component for searching icons

**Comment by eddiejaoude** [comment]
It was originally minimum 3 characters without debounce. But then languages like `go` or `c` are less than 3 characters so the minimum was removed and debounce replaced it.

Thank you for the suggestion, I will close this as we have a couple of open issues already about this
- each on enter https://github.com/EddieHubCommunity/LinkFree/issues/2815
- use search library https://github.com/EddieHubCommunity/LinkFree/issues/900

**Comment by eddiejaoude** [comment]
It was originally minimum 3 characters without debounce. But then languages like `go` or `c` are less than 3 characters so the minimum was removed and debounce replaced it.

Thank you for the suggestion, I will close this as we have a couple of open issues already about this
- each on enter https://github.com/EddieHubCommunity/LinkFree/issues/2815
- use search library https://github.com/EddieHubCommunity/LinkFree/issues/900
