### ISSUE TITLE
Overflown alt text

### ISSUE THREAD

**Issue by manavmodi22** [EddieHubCommunity/LinkFree#481]
### Description

The alt text displayed while on the user profile page is quite abnormal.

### Screenshots

<img width="1373" alt="Screenshot 2021-10-08 at 22 39 59" src="https://user-images.githubusercontent.com/55242552/136596653-a7ed1619-c4cf-49e6-bf4f-1724597ac6ed.png">

### Additional information

N/A

**Comment by GaryNLOL** [comment]
I would like to work on this.

**Comment by GaryNLOL** [comment]
Is something like this okay?
![image](https://user-images.githubusercontent.com/46727048/136609117-74a06758-73a5-4831-9cf0-ff11f670a84f.png)

I only added this style rule in `Profile.css`.
```css
.p-avatar > img{
  font-size: 0.5em;
}
```

Let me know if I should create a PR.
