### ISSUE TITLE
Events tab being shown even if not added

### ISSUE THREAD

**Issue by Ananya2001-an** [EddieHubCommunity/LinkFree#4815]
### Description

I came across this profile on LinkFree and noticed that it was showing events tab even if there is no event added by them. In the JSON file of this user there is no events key as well. [Parsifal-M](https://github.com/EddieHubCommunity/LinkFree/blob/1f1356c4cd8ae8d74bc7f11ee10ea9eaaad6af3b/data/Parsifal-M.json)

### Screenshots

![image](https://user-images.githubusercontent.com/55504616/218664091-3dd343f7-db4a-4f4e-bc8c-c3eb19374dbb.png)

**Comment by SaraJaoude** [comment]
This happens when the person does have an event but it is now in the past (already taken place).  There is a Pull Request open to be able to display historic events: https://github.com/EddieHubCommunity/LinkFree/pull/4574 so I will close this Issue.
