### ISSUE TITLE
Add markdown rendering on map - user bio

### ISSUE THREAD

**Issue by Pradumnasaraf** [EddieHubCommunity/LinkFree#4817]
### Description

Currently, the users having markdown syntax elements  in their profile bio in not getting rendered.

### Screenshots

<img width="639" alt="Screenshot 2023-02-14 at 1 18 35 PM" src="https://user-images.githubusercontent.com/51878265/218673247-d8e221e9-36fb-400f-b38e-84bf4b24ac19.png">

**Comment by SaraJaoude** [comment]
Thanks for raising. 

Note to contributor:

- We have a markdown component that can be used.

**Comment by Pradumnasaraf** [comment]
Unlocking the issue and ready for assignment.

**Comment by Girishbari** [comment]
I would like to work on this @Pradumnasaraf

**Comment by Jayakrishna2b** [comment]
is it fixed

**Comment by Pradumnasaraf** [comment]
> I would like to work on this @Pradumnasaraf

yes go ahead

**Comment by Pradumnasaraf** [comment]
> Hi @Pradumnasaraf, first of all, thanks for assigning this work to me, I was searching for any slack or communication channel of this repo but was unable to find them, can you please ping it in the comment so that I can join and ask my doubts

Hey, 
We have discord. You can join here 
http://discord.eddiehub.org/

**Comment by SaraJaoude** [comment]
> @Pradumnasaraf is this still open?

@Aathirajan as you can see from the top of this page this issue has already been assigned to someone else and they have a Pull Request open.  In future:

1. Please check the conversation and and assignee section
2. Please do not tag a specific maintainer to be assigned an issue.  All maintainers are notified of activity in the project and are able to assign.

**Comment by Aathirajan** [comment]
Yeah! got it thank you for taking time to guide me.
