### ISSUE TITLE
[FEATURE] Enabling Insights for the User Profile Page

### ISSUE THREAD

**Issue by manavmodi22** [EddieHubCommunity/LinkFree#482]
### Description

Normal linktree provides the user an option to view insights like click counters, page visits, and the source, etc. 
I am creating this issue and keeping the suggestions wide open on how the Analytics/User Insights can be enabled for the project. The goal is to ideate, cause making it the same as Linktree might not be possible but it is important that in some way the users on the project get these insights.

**Comment by Zishan-7** [comment]
@manavmodi22 That would be a great addition, but don't you think for that we will firstly have to make an login page for the users?
After logging in they can check insights for their account only.

**Comment by krishguptadev** [comment]
Also, where are you gonna store the stats? Also are we sure to store the stats? 🤔

**Comment by Zishan-7** [comment]
We'll have to make a database for storing data and backend APIs or we can use firebase as it's much more convenient.

**Comment by krishguptadev** [comment]
> We'll have to make a database for storing data and backend APIs or we can use firebase as it's much more convenient.

Humm, I don't think this will be a good idea to add insights.

**Comment by Zishan-7** [comment]
I think it will be a good addition because it will make LinkFree much more like link tree.

**Comment by krishguptadev** [comment]
> I think it will be a good addition because it will make LinkFree much more like link tree.

Then maybe let's wait for the coming API... it would introduce a features that may help 😄

**Comment by code3z** [comment]
Should the analytics be public or private?

**Comment by eddiejaoude** [comment]
I like this idea, we will need people to authenticate to see their stats (private), and we will need to move it to a database

**Comment by Zishan-7** [comment]
@eddiejaoude Yes, we will have to make a fresh new backend 
I would suggest we can use ExpressJs for that and MongoDB for the database

**Comment by eddiejaoude** [comment]
This has now been completed and deployed, thank you all for the suggestion 👍
