### ISSUE TITLE
On the events page the question mark beside heading is opening docs

### ISSUE THREAD

**Issue by rohinish404** [EddieHubCommunity/LinkFree#4832]
### Description

The question mark besides the heading Community Events is opening a documentation page. Are they linked by mistake or is this intentional. If by mistake then what should that icon link to?
Below are the screenshots-
<img width="1434" alt="Screenshot 2023-02-15 at 12 54 22 PM" src="https://user-images.githubusercontent.com/92542124/218960716-7128b6b4-fcfa-49de-9810-7249dd690448.png">
And on clicking, the below page is getting opened.
<img width="1434" alt="Screenshot 2023-02-15 at 12 54 27 PM" src="https://user-images.githubusercontent.com/92542124/218960829-043febce-a7ae-4bfa-aa13-be65a919c6a2.png">

### Screenshots

https://user-images.githubusercontent.com/92542124/218960917-be5ebaeb-29e7-4d9f-974b-664fd6469d78.mov

**Comment by SaraJaoude** [comment]
This feature was requested by the community so they can understand how to get their events on this page. I will be closing this issue as is intentional.

**Comment by rohinish404** [comment]
Okay..sure!
