### ISSUE TITLE
[FEATURE] Add user avatar as a dropdown menu in the navbar

### ISSUE THREAD

**Issue by ChinmayMhatre** [EddieHubCommunity/LinkFree#4839]
### Description

I suggest putting the `account` and `logout` button within a avatar icon like so
<img width="865" alt="image" src="https://user-images.githubusercontent.com/51131670/219025499-d4c6a04c-69f8-4d09-acec-d99772ae37ca.png">

We can use the tailwind elements for reference.
https://tailwind-elements.com/docs/standard/navigation/navbar/

**Comment by ankitk26** [comment]
Please let me work on this issue once it gets verified.

**Comment by ManishBisht777** [comment]
Great idea

**Comment by eddiejaoude** [comment]
Thank you for the suggestion, we will need this in the near future as we add more links to the logged in user, but currently this is not needed. So I will mark as blocked

**Comment by SaraJaoude** [comment]
I am closing this as it is a duplicate of: https://github.com/EddieHubCommunity/LinkFree/issues/4995
