### ISSUE TITLE
[Link Addition] Telegram link in LinkFree

### ISSUE THREAD

**Issue by atharvashirdhankar** [EddieHubCommunity/LinkFree#484]
### Description

Telegram link can be added into LinkFree.

(I have made changes for the same locally on my forked repository.)

**Comment by krishguptadev** [comment]
I like your idea. Would you like to open a pr for the same?

**Comment by krishguptadev** [comment]
> Yes

So Go on!

**Comment by StarTrooper08** [comment]
PR for this issue #493
