### ISSUE TITLE
In larger screen when we hover on eventCard it scales out of bound

### ISSUE THREAD

**Issue by Sudhanva-Nadiger** [EddieHubCommunity/LinkFree#4840]
### Description

When we hover on event card it scales and goes out of the screen.

### Screenshots

![image](https://user-images.githubusercontent.com/93595710/219025571-eaff51ef-fcaf-4ca4-98ce-68be4e6fb14f.png)

**Comment by FrozenHearth** [comment]
Can you please provide the screen size on which it is happening?

**Comment by GauravBurande** [comment]
Can I work on this issue?

**Comment by Sudhanva-Nadiger** [comment]
14inch screen

**Comment by FrozenHearth** [comment]
> 14inch screen

Dimensions, please. Width x Height.

**Comment by Sudhanva-Nadiger** [comment]
Width: 14.11 in. (358.5 mm) ; Depth: 9.27 in. (235.56 mm)

**Comment by FrozenHearth** [comment]
> Width: 14.11 in. (358.5 mm) ; Depth: 9.27 in. (235.56 mm)

How much is that in pixels?

**Comment by eddiejaoude** [comment]
I think the animation could be reduced to prevent this

**Comment by GauravBurande** [comment]
Can I work on this issue?

**Comment by GauravBurande** [comment]
> I think the animation could be reduced to prevent this

Already on min scale-105

**Comment by GauravBurande** [comment]
> > I think the animation could be reduced to prevent this
> 
> It's already on min, hover:scale-105

Maybe reduce the width?

**Comment by GauravBurande** [comment]
I've made some changes to the hover effects, which solve this problem, it looks like the cursor is pressing on it.
[screen-capture.webm](https://user-images.githubusercontent.com/100035026/220453793-aaf8dae2-38de-4b58-b2c7-54f1b6a56000.webm)

**Comment by Abhijit20112003** [comment]
please close the issue it's already solved
