### ISSUE TITLE
[OTHER] Add Prettier config to the project root

### ISSUE THREAD

**Issue by ThePiyushAggarwal** [EddieHubCommunity/LinkFree#4847]
### What would you like to share?

While contributing, my personal prettier configuration are taking over and are making unnecessary changes.

The blue lines are all prettier changes.

![image](https://user-images.githubusercontent.com/27003616/219101946-b64dfcbc-01d5-4162-a59b-80a90a24c4f3.png)

A `.prettierrc` at the root of the project works fine even if it contains an empty JSON object.

![image](https://user-images.githubusercontent.com/27003616/219102461-6a952c94-75f6-4768-b1b4-83f4d356337a.png)

**Comment by PratikDey** [comment]
Hi, I would like to contribute to this issue

**Comment by FrozenHearth** [comment]
We already have eslint setup for this project, with the defaults. I think a .prettierrc or .eslintrc would be helpful.

**Comment by sansarmaske** [comment]
> Hi, I would like to contribute to this issue

Wait for `status: ready for dev`

**Comment by eddiejaoude** [comment]
thank you @ThePiyushAggarwal for the great idea and the detailed issue 💯 

@PratikDey I have assigned it to you
