### ISSUE TITLE
There are same filter type in search page

### ISSUE THREAD

**Issue by devvsakib** [EddieHubCommunity/LinkFree#4852]
### Description

Double javascript type in the search page
![image](https://user-images.githubusercontent.com/88339569/219127946-64e1eb8e-49b2-4660-8cc3-2e2e19e8be0a.png)

**Comment by FrozenHearth** [comment]
Duplicate of #4676

**Comment by Aadarsh805** [comment]
you can close this one @devvsakib, it exists already
