### ISSUE TITLE
[FEATURE] Tweaks for chip component on homepage.

### ISSUE THREAD

**Issue by sh-himanshu** [EddieHubCommunity/LinkFree#487]
### Description

- Currently, the chip has uneven padding because of the circular profile picture.
- Hover state is barely noticeable because everything is closely arranged.

### Screenshots

Before           |  After
:-------------------------:|:-------------------------:
![Screenshot 2021-10-09 130129](https://user-images.githubusercontent.com/88159798/136649012-0129acde-a758-4c02-ac4d-e4b3878da3a4.png) | ![Screenshot 2021-10-09 130223](https://user-images.githubusercontent.com/88159798/136649014-49c19f9d-16af-4760-8aef-d05c04b34af4.png)

### Additional information

If these changes are approved I would like to PR for the same.

**Comment by krishguptadev** [comment]
> > Can this be done, without any custom styles and just PrimeReact?
> 
> Custom styles already exist in the repo I just tweaked it.

Cool, please open a PR so that we can check it out
