### ISSUE TITLE
[DOCS] Typo in "Local development with Docker Compose" doc

### ISSUE THREAD

**Issue by zaidahmad25** [EddieHubCommunity/LinkFree#4881]
### Description

In the fourth point, there should be an "are" in the sentence to make it gramatically right.

### Screenshots

![image](https://user-images.githubusercontent.com/39582467/219414845-2079253c-173e-47ee-8db2-3e55e38163a4.png)

**Comment by Jayakrishna2b** [comment]
i don't think so nothing wrong in that sentence

**Comment by zaidahmad25** [comment]
"If you making" is incorrect. It should be- "If you are making"

**Comment by HarshDeep61034** [comment]
@zaidahmad25 are you working on this ?

**Comment by zaidahmad25** [comment]
No

**Comment by HarshDeep61034** [comment]
@kumarsonsoff3 plz work after getting Assigned to the issue next time !
Anyways thanks for the contribution 😄

**Comment by kumarsonsoff3** [comment]
Hey @HarshDeep61034, You might get it wrong. Being a maintainer, I'm aware of this. 😄

Here, @GauravBurande has already created a PR for this issue. I just linked this issue with that PR to avoid multiple PRs for the same issue. And Gaurav, I recommend you to always get assigned first before working on an issue.

**Comment by GauravBurande** [comment]
Sure, I'll keep that in mind.

**Comment by HarshDeep61034** [comment]
> Hey @HarshDeep61034, You might get it wrong. Being a maintainer, I'm aware of this. 😄
> 
> Here, @GauravBurande has already created a PR for this issue. I just linked this issue with that PR to avoid multiple PRs for the same issue. And Gaurav, I recommend you to always get assigned first before working on an issue. 

Ohh my bad 😅 
But i don't think so he was assigned either.
No problem it was just a typo 👍

**Comment by zaidahmad25** [comment]
Yeah, I didn't work on this since I wasn't assigned 😅
