### ISSUE TITLE
Profile Picture fails to load occasionally.

### ISSUE THREAD

**Issue by sh-himanshu** [EddieHubCommunity/LinkFree#491]
### Description

- This issue only happens rarely but I did face it 3 times till now. Mostly happens when page is reloaded several times.
- PrimeReact Avatar component provides an `onImageError` prop which can be utilized to reload the image or display a default avatar image.

### Screenshots

![image](https://user-images.githubusercontent.com/88159798/136683585-e66c9f2b-cac1-4776-925f-1ec52c1e5e9a.png)

**Comment by krishguptadev** [comment]
Duplicate of https://github.com/EddieHubCommunity/LinkFree/issues/480. I request the maintainers to thus close this 🙂

**Comment by sh-himanshu** [comment]
> Duplicate of #480. I request the maintainers to thus close this 🙂

My Bad
