### ISSUE TITLE
[FEATURE] Scroll back to top button at footer

### ISSUE THREAD

**Issue by sudhanshutech** [EddieHubCommunity/LinkFree#4920]
### Description

When a website has a lot of content and the user has to scroll down a long way to get to the bottom, a scroll back to the top button can be helpful as it saves the user time and effort. Rather than having to manually scroll all the way back up to the top of the page, the user can simply click the button and be taken there instantly.

**Comment by FrozenHearth** [comment]
https://github.com/EddieHubCommunity/LinkFree/issues/2670#issuecomment-1415992389

**Comment by sudhanshutech** [comment]
> [#2670 (comment)](https://github.com/EddieHubCommunity/LinkFree/issues/2670#issuecomment-1415992389)
But I guess right now there are not so many buttons at bottom of the site, only a help button is there so it might not create any problem rather this feature will help users to navigate easily.

**Comment by yashpandey002** [comment]
Can anyone confirm if this feature is needed or not?

If needed, I will love to help

**Comment by sudhanshutech** [comment]
> Can anyone confirm if this feature is needed or not?
> 
> If needed, I will love to help

Yes I would also like to solve the issue

**Comment by ChinmayMhatre** [comment]
The discussion over the feature have been done before. And it has be decided to not implement this. This issue can be closed

**Comment by sudhanshutech** [comment]
ok then we can close this issue

**Comment by yashpandey002** [comment]
OK then, thanks @ChinmayMhatre

**Comment by eddiejaoude** [comment]
Thank you for the idea, this was discussed only 2 weeks ago that it is not needed
