### ISSUE TITLE
[DOCS] Special entities ( <, > ) are rendered incorrectly

### ISSUE THREAD

**Issue by kumarsonsoff3** [EddieHubCommunity/LinkFree#4930]
### Description

In the testimonials guide, some of the special entities like (`<`, `>`) are not being rendered correctly. It's showing the syntax instead of the exact symbols. 

### Screenshots

It should be something like this `data/<username>/testimonials/<your-username>.json`

![image](https://user-images.githubusercontent.com/88786642/219849574-4d5ff949-d444-4e6a-8ec4-5ad392430721.png)

**Comment by rghdrizzle** [comment]
I would like fix this

**Comment by Imshk** [comment]
I want to fix this problem, please assign it to me .

**Comment by kumarsonsoff3** [comment]
@rghdrizzle asked first, so I'm assigning this to them. 

@Imshk you can check out other issues you can work on (labeled as `ready for dev`) or check back later. 
Thanks for asking though. :)

**Comment by rghdrizzle** [comment]
@kumarsonsoff3 can you tell me the location of the folder where this issue exists  ?

**Comment by kumarsonsoff3** [comment]
The path where the source code for the page exists is `pages/docs/how-to-guides/testimonials.mdx`
