### ISSUE TITLE
[OTHER]

### ISSUE THREAD

**Issue by merwinmathew33** [EddieHubCommunity/LinkFree#4942]
### What would you like to share?

I cannot see my profile in the map. I am from kerala, India.

**Comment by amandamartin-dev** [comment]
Hello! No need to open an issue for this, but to answer for you as the likely reason why:

The LinkFree map uses the Nominatum API to find the Lat/Long value of the location.  In your case, Nominatum does not recognize this location so it is not returning a value.

You can see this here: https://nominatim.openstreetmap.org/ui/search.html?q=Thrissur%2C+Aripalam+P.O

Nominatum does, however, return a location for your place without the "P.O".  I am not sure if that is still accurate, but you can change if you like

See here: https://nominatim.openstreetmap.org/ui/search.html?q=Thrissur%2C+Aripalam

If you do choose to change your location, please wait up to 7 days for the data to repopulate in the database.  To manage the amount of calls to the GitHub API we only refresh the databse once per week.

If you change the location to something the API understands and after a week, you still do not see anything on the map - please ask in Discord and we can see if an issue should be opened. 

Feel free to tag me if anything is unclear in Discord.  I will close this issue for now.
