### ISSUE TITLE
[FEATURE] Card and hover effect on docs page

### ISSUE THREAD

**Issue by sudhanshutech** [EddieHubCommunity/LinkFree#4944]
### Description

We could create card elements or some background effects for different docs elements because now the user is not sure that the element is clickable or not
![image](https://user-images.githubusercontent.com/90546692/219881521-69325581-c5cf-467d-8090-50fbe5cabfd6.png)
 Later we could apply a hover effect for those cards then it gonna look more attractive as UI.

### Screenshots

![image](https://user-images.githubusercontent.com/90546692/219881601-a9ada839-f67d-438e-97f5-27f33accadbf.png)
Similarly in these

**Comment by khalid827** [comment]
I want to work on it can you assign it to me?

**Comment by eddiejaoude** [comment]
Maybe a simple border might be effective

**Comment by eddiejaoude** [comment]
@khalid827 I have assigned it to you

**Comment by khalid827** [comment]
> @khalid827 I have assigned it to you

Thank U.

**Comment by Mahmoudgalalz** [comment]
Is anyone working on it ?, it could be finished just an hour, if no one is doing it can I take it and send the pr

**Comment by akashIsCoding** [comment]
Hi @Mahmoudgalalz I would like to work on this right now, if you don't mind.

**Comment by psavan1655** [comment]
If anyone is working on this issue. A simple suggestion.
Please add a box shadow on hover `className="shadow hover:shadow-lg"`. Would look much better. 

What do you think @eddiejaoude ?

**Comment by akashIsCoding** [comment]
hey @psavan1655 I raised a PR - this is the implementation I did:
`className="border-2 hover:border-orange-600 transition-all duration-250 ease-linear rounded px-6 py-2 mb-4"`

PR - #5125

**Comment by Mahmoudgalalz** [comment]
> Hi @Mahmoudgalalz I would like to work on this right now, if you don't mind.

sorry for being late, the time difference uk, I see you made a pr

**Comment by eddiejaoude** [comment]
@akashIsCoding please do not create a PR without the issue be assigned to you, as this creates more work for everyone and confusion. 

As you will see from the timeline @Mahmoudgalalz requested to be assigned the issue before you, but this time **only** as you have created a PR I will assign it to you @akashIsCoding 

@Mahmoudgalalz we can find you more issues, or we can create some new ones also, what type would you like to work on?

**Comment by akashIsCoding** [comment]
@eddiejaoude sorry, I'm new to contributing to open source, its in fact my first PR. Will keep this in mind. Thank you

**Comment by Mahmoudgalalz** [comment]
> @akashIsCoding please do not create a PR without the issue be assigned to you, as this creates more work for everyone and confusion. 
> 
> As you will see from the timeline @Mahmoudgalalz requested to be assigned the issue before you, but this time **only** as you have created a PR I will assign it to you @akashIsCoding 
> 
> @Mahmoudgalalz we can find you more issues, or we can create some new ones also, what type would you like to work on?

Really, I can work on many different aspects like front, back end 

So no worries, I will look for the ready for devs 
Tag

I'm not a beginner to OSS

**Comment by aksharma27** [comment]
@eddiejaoude  If the deadline for this issue is over, please assign this to me.

**Comment by eddiejaoude** [comment]
I think there is a pull request open for this already

**Comment by eddiejaoude** [comment]
Pull request merged https://github.com/EddieHubCommunity/LinkFree/pull/5125
