### ISSUE TITLE
[FEATURE] Ability to filter map by tag

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#4957]
### Description

Add tag filter to map page to increase consistency across the UI and provide users a way to interact with the data displayed there in a meaningful way.

**Comment by amandamartin-dev** [comment]
I have assigned myself, but will wait until after triage to begin work in case there is something else in the pipeline that would block or otherwise de-prioritize this effort.  Lmk!

**Comment by eddiejaoude** [comment]
Great idea Amanda, go for it 👍

**Comment by amandamartin-dev** [comment]
update on this for visibility - in progress, tags are added and search is toggling map view.

Need to tweak the search function as the results aren't always as expected.  Will get back to this in the next few days. 

lil video below...it's a fun filter!


https://user-images.githubusercontent.com/97615019/220772364-4074324c-232c-44a2-aa04-e1bf1482b2dd.mov

**Comment by eddiejaoude** [comment]
Looks great 👍  

I wonder if the whole search to reduce users and keeping the tag clicked can be reused from the search page by abstracting it out?

**Comment by amandamartin-dev** [comment]
I did take code I needed from the search, removing anything that requires the input (for now). I'm afk but I'll open a draft pr tomorrow so you can see how it looks so far. Open to ideas always ☺️
