### ISSUE TITLE
[FEATURE] Homepage feature to have section on map

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#4962]
### Description

On the homepage we list the feature of LinkFree, but we need to add the map page

- [ ] title
- [ ] description
- [ ] screenshot

**Comment by devXprite** [comment]
Hii @eddiejaoude I want to work on this issue

**Comment by adiitiii** [comment]
hey @eddiejaoude, can you please elaborate on what we exactly need to do for this issue, I will love to help!

**Comment by Aadarsh805** [comment]
Is this how you want it to be @eddiejaoude 

![Group 101](https://user-images.githubusercontent.com/95094057/220066759-6a4d110b-b3cd-42a9-aee2-06689058a814.png)

**Comment by Aadarsh805** [comment]
> assigned

I made this on Figma, I have not started to code or anything 
so I think we should let @devXprite work on this, as they asked first

**Comment by Aadarsh805** [comment]
@devXprite if you still want to work on it you can, use the image I provided above as a reference, and also make sure to keep note of the changes Eddie asked for above

**Comment by eddiejaoude** [comment]
> I made this on Figma, I have not started to code or anything

oh love this @Aadarsh805 👍

**Comment by devXprite** [comment]
> @devXprite if you still want to work on it you can, use the image I provided above as a reference, and also make sure to keep note of the changes Eddie asked for above

Thanks @Aadarsh805

**Comment by eddiejaoude** [comment]
Great collaboration everyone !!
