### ISSUE TITLE
[DOCS] Update screenshots on /docs/quickstart 

### ISSUE THREAD

**Issue by sansarmaske** [EddieHubCommunity/LinkFree#4999]
### Description

We need to update the screenshots on https://linkfree.eddiehub.io/docs/quickstart as new people are being confused.
It currently has `avatar` and `displayStatsPublic` which are no longer required.

### Screenshots

![issue-ss-1](https://user-images.githubusercontent.com/18899162/220371058-4e09425d-bc0c-4435-a24d-beca29a8fcc0.jpg)
![issue-ss-2](https://user-images.githubusercontent.com/18899162/220371068-4f66c625-ffe1-4126-92be-e00cadfd274d.jpg)

**Comment by Ankur1493** [comment]
can I work on this @sansarmaske

**Comment by sansarmaske** [comment]
> can I work on this @sansarmaske

Don't work on it yet. Let this be approved by maintainers first.

**Comment by Swpn0neel** [comment]
I can work on that!!

**Comment by SaraJaoude** [comment]
The video cannot easily be updated. The code blocks (which are meant for users to copy) have already been updated. 

The screenshots only should be updated - I will update the issue description to reflect this.

**Comment by MAYANKpandey14** [comment]
Hey @SaraJaoude , I have worked on Quick-start guide before ( Adding JSON lint)
Can you please assign this to me ?

**Comment by SaraJaoude** [comment]
> Hey @SaraJaoude , I have worked on Quick-start guide before ( Adding JSON lint)
> Can you please assign this to me ?

@MAYANKpandey14 I will assign this to you.  In future please avoid tagging a specific maintainer - all maintainers receive notifications on the project and can assign.

**Comment by MAYANKpandey14** [comment]
> > Hey @SaraJaoude , I have worked on Quick-start guide before ( Adding JSON lint)
> > Can you please assign this to me ?
> 
> @MAYANKpandey14 I will assign this to you. In future please avoid tagging a specific maintainer - all maintainers receive notifications on the project and can assign.

Sure!. I didn't know about it.
I'll make sure of it for future.

**Comment by MAYANKpandey14** [comment]
Due to some issue i had to close this pr 
I am creating another one .
