### ISSUE TITLE
[FEATURE] Adding Logo to the HomePage

### ISSUE THREAD

**Issue by RiddhiDamani** [EddieHubCommunity/LinkFree#501]
### Description

How about adding a logo to the home page? I believe no portal is complete without having a logo of its own. I would like to present a logo to LinkFree and add it to the project repo. 

### Screenshots

<img width="1435" alt="pic" src="https://user-images.githubusercontent.com/19336011/136882056-1379255f-4966-4e73-8bea-52ed71bfb5ef.png">

### Additional information

Do let me know if you like this logo design or if you want me to customize it as per your design criteria. I will be more than happy to accommodate it and contribute to this repository.  Also, please let me know if I should create a PR for this. Thanks!

**Comment by krishguptadev** [comment]
> Hey @krishdevdb have already created the design at my end and added the code in my cloned repo. I am wondering if someone here would assign this task to me or should I go ahead and create a pull request without assignment?

Ohk! So you can make a PR instead :)

**Comment by RiddhiDamani** [comment]
Does this qualify to be part of #Hacktoberfest2021? Thanks again!

**Comment by RiddhiDamani** [comment]
Sure, I just came to know about it. No worries. The best logo design should be up on the portal. :) Thanks for letting me know @schmelto @krishguptadev

**Comment by Vyvy-vi** [comment]
I would like to affirm - Adding Logos after designing them _adds value_, and thus _can_ count for hacktoberfest, though I think hacktoberfest has ended today

**Comment by eddiejaoude** [comment]
Thanks all for the collaboration, sorry we didn't look at the logo options yet. We will do it this week 👍

**Comment by CodingSpecies** [comment]
@eddiejaoude if you were to check the logo, here is a list of them all in the discussion : https://github.com/EddieHubCommunity/LinkFree/discussions/206#discussioncomment-1465924
there are also more being produced in other chat threads too.

**Comment by krshdev** [comment]
Not stale yet (comment to remove stale)

**Comment by CodingSpecies** [comment]
Please can this issue be reopened? 
thank you.

**Comment by Vedant-Manjrekar** [comment]
What happened about this issue, currently there is no logo on the website. If provided with Logo I can add it to the website.

Assuming [Link Free](http://linkfree.eddiehub.io/) is the website as there is one more website named "Link Free" although [Link Free](http://linkfree.eddiehub.io/) is mentioned in the README.

**Comment by CodingSpecies** [comment]
@Vedant-Manjrekar we are in the process of choosing a logo #206 , though it is not active at the moment.

**Comment by Vedant-Manjrekar** [comment]
Can you assign me this issue, once you all choose the logo?

**Comment by CodingSpecies** [comment]
@Vedant-Manjrekar I am not a maintainer and @RiddhiDamani might still wish to work on it.
Thank you.

**Comment by Vedant-Manjrekar** [comment]
FIne @CodingSpecies , @RiddhiDamani if you need any help feel free to ask.

**Comment by eddiejaoude** [comment]
Lots of great collaboration everyone, thank you 👍 I think for now maybe we can use one of the EddieHub Mascots

We have some great new features with the new version that got released today
