### ISSUE TITLE
Login button and Milestones tab not working

### ISSUE THREAD

**Issue by dev-rakeshshaw** [EddieHubCommunity/LinkFree#5013]
### Description

The milestone tab of any user`s profile is not working.
Also, the Login button is also not working.

### Screenshots

#Milestone tab
![image](https://user-images.githubusercontent.com/88075256/220639712-4e274021-fbb0-4794-acd4-75235659294f.png)

#Login Button
![image](https://user-images.githubusercontent.com/88075256/220639400-2e115bbe-8829-49b2-8ccb-1f04ef49665b.png)

### Additional information

Please resolve this issue.

**Comment by ChinmayMhatre** [comment]
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/51131670/220711399-5c66a78f-a32b-4a3f-a969-27e31afe4c56.png">
The milestone tab is working for me

**Comment by ChinmayMhatre** [comment]
Is this a local server?

**Comment by dev-rakeshshaw** [comment]
> Is this a local server?
> 

Ya now it's working for me also. 
Don't know what happened back then.
