### ISSUE TITLE
[FEATURE] Include app testimonial in README

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#5019]
### Description

We have app testimonials on the homepage, but we should include them on the README as well.

I think these could be done in a table format

PR to add them to the homepage https://github.com/EddieHubCommunity/LinkFree/pull/5015

**Comment by abdulsamad** [comment]
Could you please assign this to me?

**Comment by Imshk** [comment]
I would like to do it , Please assign this issue to me .

**Comment by eddiejaoude** [comment]
Sure @Imshk , I will assign it to you

**Comment by eddiejaoude** [comment]
Hi @Imshk it looks like a PR has already been created even though it was not assigned to them. I have asked them not to do this in the future as it causes confusion for everyone.

Sorry I will unassigned it from you as they have done the work already 

https://github.com/EddieHubCommunity/LinkFree/pull/5036

**Comment by eddiejaoude** [comment]
@SohamRoy-01 created a PR already. @SohamRoy-01 I can't assign the issue to you for some reason, maybe if you comment here

**Comment by SohamRoy-01** [comment]
Sorry for my behalf @eddiejaoude I shouldn't have started before it  is assign to me ,Please assign me ...

**Comment by eddiejaoude** [comment]
Thank you for understanding 👍  it is now assigned to you

**Comment by Imshk** [comment]
It's okay @eddiejaoude , I will search for another contribution .
