### ISSUE TITLE
profile views stats

### ISSUE THREAD

**Issue by IPratikMali** [EddieHubCommunity/LinkFree#5023]
### Description

The stats/graphs of profile views are not displaying properly when hovering over them.

### Screenshots

https://user-images.githubusercontent.com/100037271/220819264-f0f96649-fdbc-430d-b066-ad6efdaf0a90.mp4

**Comment by abdulsamad** [comment]
Done 🎉

**Comment by eddiejaoude** [comment]
Thank you @abdulsamad
