### ISSUE TITLE
Events tab showing after all events have passed

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#5053]
### Description

In personal profiles, if the user previously had an event that has now ended and no future events are planned.  The events tab is still showing

see my profile for an example: https://linkfree.eddiehub.io/amandamartin-dev

![events](https://user-images.githubusercontent.com/97615019/221283535-a3c9ffc0-edc0-48b4-9841-c083e0d97ea0.jpg)

**Comment by eddiejaoude** [comment]
There is a Pull Request that I think will fix this https://github.com/EddieHubCommunity/LinkFree/pull/4574

**Comment by SaraJaoude** [comment]
> There is a Pull Request that I think will fix this #4574

This Pull Request has now been merged so I will close this Issue.
