### ISSUE TITLE
[DOCS] Change Screenshot on README.md

### ISSUE THREAD

**Issue by NS007-dev** [EddieHubCommunity/LinkFree#506]
### Description

On the readme there is @eddiejaoude screenshot of his profile in LinkFree. But, I think it needs updating as he has added milestones.

## Before:
![image](https://user-images.githubusercontent.com/70807500/137013357-1d339247-0634-4b62-aed3-99efe9e8783d.png)

## After:
![image](https://user-images.githubusercontent.com/70807500/137013476-fa550985-57d2-4bdb-8684-168180dc6700.png)

### Additional information

I can change the image to make it smaller.
If you agree with this, please can you assign this to me?
Thank you.

**Comment by krishguptadev** [comment]
Can I work on this?
