### ISSUE TITLE
Remove unnecessary scrolling

### ISSUE THREAD

**Issue by abhijain2003** [EddieHubCommunity/LinkFree#5064]
### Description

if there is no requirement then we should remove unnecessary scrolling in website

### Screenshots

https://user-images.githubusercontent.com/91718608/221353199-48cb80e8-af1e-42dd-af4c-cf2a2f074119.mp4

### Additional information

the video is just for my profile, but i think in each page, if not needed then remove scrolling

**Comment by abhijain2003** [comment]
if maintainers are ready then I would like to work on this

**Comment by SaraJaoude** [comment]
> if maintainers are ready then I would like to work on this

@abhijain2003 I have assigned this to you

**Comment by abhijain2003** [comment]
sure sarajaoudo

**Comment by abhijain2003** [comment]
sorry I am failed to raise pr as finding difficulty in setting mongodb for this repo locally

**Comment by MAYANKpandey14** [comment]
> sorry I am failed to raise pr as finding difficulty in setting mongodb for this repo locally

Hey @abhijain2003 you can try using Gitpod, it is very good alternative for situations like you are facing.

**Comment by abhijain2003** [comment]
do you have any documentation for this attached to the repo?

**Comment by ChinmayMhatre** [comment]
> sorry I am failed to raise pr as finding difficulty in setting mongodb for this repo locally

Could you elaborate on the problem you are facing?

**Comment by SaraJaoude** [comment]
Unable to replicate so I will be closing this Issue for now.
