### ISSUE TITLE
[DOCS]Embed YouTube video 

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#5066]
### Description

This video needs to be at the top of the editing profile docs

- video https://www.youtube.com/watch?v=eze7Y4Rxwtc
- page https://linkfree.eddiehub.io/docs/how-to-guides/editing

Similar to https://linkfree.eddiehub.io/docs/quickstart

**Comment by JunDevHarsh** [comment]
Can I work on this?

**Comment by eddiejaoude** [comment]
Sure, assigned to you @JunDevHarsh

**Comment by JunDevHarsh** [comment]
@eddiejaoude, here is the screenshot of the following changes I have made. Just want to ask whether should I change the title before the video i.e. `QuickStart`?

![Screenshot 2023-02-24 172714](https://user-images.githubusercontent.com/94737463/221367525-c59b0e53-0510-4564-a146-c8b299e68a44.png)

**Comment by eddiejaoude** [comment]
I would keep the same title on the page, and add the video below it
