### ISSUE TITLE
[FEATURE] add LinkFree H1 to Homepage

### ISSUE THREAD

**Issue by CodingSpecies** [EddieHubCommunity/LinkFree#507]
### Description

I am not sure if this is already an issue, but On linkfree, we just have a page of profiles, and a search bar, but not a heading or anything explaining this is LinkFree. 
Maybe just above the search bar, we could have a H1 saying LinkFree.
Thank you.

**Comment by krishguptadev** [comment]
I've design a better page for LinkFree in LHD Learn: 

![LinkFree](https://user-images.githubusercontent.com/91655303/137056693-c29b22c0-dd67-4d61-a23d-bbadc946cbd7.png)

Design file is available at Figma. Also, I can design the other pages as well :) What do you think @eddiejaoude? I really wanna make my first contribution to LinkFree :) Lemme know what you think!

**Comment by schmelto** [comment]
#501

**Comment by schmelto** [comment]
> I mean, that if you like the design, I would make the other pages and then we could implement the design to current functionality

tose other issues are for the issue  @CodingSpecies specified in this issue :)

**Comment by eddiejaoude** [comment]
Sorry for my slow reply.

I think the cards would take up more space, which would display less people on the page.

I guess there could be 2 display types
- condensed (what we have now)
- large (the card example you are showing)

This could be changed with a switch https://www.primefaces.org/primereact/showcase/#/inputswitch

**Comment by krishguptadev** [comment]
I can design both condensed and comfortable! We can have a switch like you said...

**Comment by Vyvy-vi** [comment]
Imo, the condensed version could just be the current version... It looks alright, and idk if more work is needed there.

There is a small issue with using a switch though - Many people would like a dark mode switch. Imho, 2 switches would be quiet confusing.

**Comment by krishguptadev** [comment]
Can someone fix this?

**Comment by eddiejaoude** [comment]
Sure I can reopen

**Comment by emmalearnscode** [comment]
This has now been added with the homepage redesign Eddie did a couple of weeks ago.
