### ISSUE TITLE
[FIX] - Add padding to code block

### ISSUE THREAD

**Issue by JunDevHarsh** [EddieHubCommunity/LinkFree#5094]
### Description

The current code block makes it difficult to read and understand the text written in it. By adding some padding to the escaping backtick code block, users can easily read and understand. If the code blocks become unreadable due to padding, it can negatively impact the user experience.

### Screenshots

The current behavior:

![Screenshot 2023-02-26 121438](https://user-images.githubusercontent.com/94737463/221396355-cc422773-0e84-41df-9bb0-6829aecf81ed.png)

![Screenshot 2023-02-26 121438](https://user-images.githubusercontent.com/94737463/221396448-5706e441-67f7-4fa8-98c6-bbd8ffc3cbc3.png)

The expected behavior:

![Screenshot 2023-02-26 121438](https://user-images.githubusercontent.com/94737463/221396393-5815c4e1-9034-4202-b9ae-ea01f840db4e.png)

![Screenshot 2023-02-26 121842](https://user-images.githubusercontent.com/94737463/221396478-3120dadc-214a-40f5-bfad-8daa1e152499.png)

**Comment by JunDevHarsh** [comment]
Can I work on this issue?

**Comment by eddiejaoude** [comment]
Sure, I have assigned it to you. 

Please try to avoid any global styles
