### ISSUE TITLE
Inconsistency in search tag selection

### ISSUE THREAD

**Issue by niteshseram** [EddieHubCommunity/LinkFree#5096]
### Description

The search badge tag selection is not case-sensitive. When I click on one tag, it results in selecting other tags with the same words in non-case-sensitive manners but only one tag appears.

### Screenshot
Current Behavior:
If I click on `Javascript` tag, it is selecting the `JavaScript` tag as well. But the search input is showing only `Javascipt` tag and searching is completely case insensitive.

![image](https://user-images.githubusercontent.com/51370246/221398950-160cbb76-65cf-4ce1-a59e-0d53bc2c1a28.png)

Expected Behavior:
I feel like when I select the `Javascript` tag, it should only select the `Javascript` tag although the search is case insensitive.
Or, we could convert all the tags to a common case and remove all the duplicate tags from the original tags data;

Would love to know if someone has some other thoughts here.

I would love to work on fixing this.

**Comment by Deva-1903** [comment]
@niteshseram **.toLowerCase() .split(",")** these methods were done to the input, so it can not recognize the difference between JavaScript and Javascript both becomes "**javascript**" and I think this would be the best way to keep, changing it to be case sensitive would not be a good idea.

**Comment by amandamartin-dev** [comment]
Hello! An issue for this has already been created #4676
