### ISSUE TITLE
GitHub action for linting the data/*.json files

### ISSUE THREAD

**Issue by stemount** [EddieHubCommunity/LinkFree#51]
We need to catch in the pull request GitHub action that the file doesn't have a trailing comma, or the JSON file is malformed.

This would stop the necessity for someone to reply to a pull request, it would prevent a merge!

**Comment by Recognizeyourself** [comment]
Can't understand what it is. Can you brief me a little more? (P.s: i am new to GitHub)

**Comment by nhcarrigan** [comment]
This could be achieved using `ESLint` and adding an action to run `npm run lint`, as a potential example approach.

**Comment by RagibAjmal** [comment]
@stemount  @nhcarrigan
I was thinking of working on this issue but then I got to know that there is an action to run npm run lint in build.yaml and also  Linkfree already has ESlint
If there is   anything more to work on for this issue i would like to contribute

**Comment by stemount** [comment]
@Vyvy-vi @RagibAjmal @nhcarrigan good stuff, lint is good
