### ISSUE TITLE
Takes some times to open search page 

### ISSUE THREAD

**Issue by priyankarpal** [EddieHubCommunity/LinkFree#5145]
### Description

I noticed that on the LinkFree website when I click any nav link it takes some time to open that page. 

I added a Screen recording you can see.

### Screenshots

https://user-images.githubusercontent.com/88102392/221829931-c057c1d6-b0f1-4a1b-8df3-daf0398bcc5c.mp4

**Comment by eddiejaoude** [comment]
Thank you for raising. This is a duplicate of https://github.com/EddieHubCommunity/LinkFree/issues/2815

We currently load all profiles, as the list grows it will get slower - we should move the search functionality to the backend
