### ISSUE TITLE
[DOCS] Setting up .env 

### ISSUE THREAD

**Issue by yoyoekta** [EddieHubCommunity/LinkFree#5147]
### Description

As already given, a new file will be created .env and  required details are to be updated to set up the project.  Further details, like what the terms actually mean and the documentation link on how to update the fields can be added.

### Additional information

I would like to update the docs for the same. Kindly assign this issue to me.

**Comment by eddiejaoude** [comment]
Thank you for raising 👍 

To all project setup docs I added a link to the environment variable docs...

<img width="1663" alt="Screenshot 2023-03-01 at 10 45 25" src="https://user-images.githubusercontent.com/624760/222039906-3fe2ae92-e2d9-4d09-8b69-5d97821734d8.png">
