### ISSUE TITLE
[BUG] - NavLink active state not persist

### ISSUE THREAD

**Issue by JunDevHarsh** [EddieHubCommunity/LinkFree#5190]
### Description

 When we go from the `/docs` page to the `/docs/quickstart` page, the navigation link for the current page does not have an active state. The active state is only visible when we are on the `/docs` page. This behavior is confusing and can be improved.
 
 Here is the video of the current behavior:
 
 
https://user-images.githubusercontent.com/94737463/222326097-eea2b3f2-5576-4ef2-ab89-acf8e8e5d091.mp4

---

Here is the video of the expected behavior:

- For desktop screen:

https://user-images.githubusercontent.com/94737463/222326307-e8cb0aa5-4d42-46e1-819d-147a73c53bc4.mp4

- For mobile screen:

https://user-images.githubusercontent.com/94737463/222326364-0464f1d6-8550-450c-98a8-9551eddfe317.mp4

**Comment by JunDevHarsh** [comment]
Can I work on this issue?

**Comment by eddiejaoude** [comment]
Good spot 👍 

Sure I will assign it to you
