### ISSUE TITLE
[BUG] irrelivant link

### ISSUE THREAD

**Issue by himanshu1221** [EddieHubCommunity/LinkFree#5202]
### Description

an unknown link under the statistics page

that `https://twitter.com/himanshu1221`

### Screenshots

![Screenshot from 2023-03-02 16-36-04](https://user-images.githubusercontent.com/32031706/222411582-e96751ec-22f9-4aa9-8924-f478b5c68059.png)

**Comment by Aadarsh805** [comment]
that is very weird, I couldn't find that link anywhere in the files

**Comment by ChinmayMhatre** [comment]
The old links aren't removed from the backend I guess. I updated my profile to have a hashnode link and remove the dev.to link 
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/51131670/222946594-33dbb605-c5b5-4a89-819a-24cc0a16b4f8.png">

While the dev.to link may not get more clicks, it still shows the previous ones. 
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/51131670/222946621-8669c280-7f09-4968-8ec9-54782c82da7e.png">

I feel keeping the old ones seems okay as we could track the links previously clicked. What do ya'll think?

**Comment by abhijain2003** [comment]
it means there is a problem in function implementation which handles link deletion

**Comment by kumarsonsoff3** [comment]
Yeah, this shows the total stats (views, links, link clicks) of your profile. So it may include the past link clicks which are no longer available on your profile. 

And I think it's okay, since it's showing the history of your profile from the day it was created it should include these all. 

--
If there were a filter, for the past week, month, etc then it should filter the removed links out, as the days pass. ⏳

**Comment by eddiejaoude** [comment]
Great discussion! Yes historic links are displayed 👍 

What about...?
- links not currently in the profile are faded slightly or shown in a separate list underneath the main list of link stats
- when we add filters like: last 30 days, older links will not be displayed

**Comment by ChinmayMhatre** [comment]
> Great discussion! Yes historic links are displayed 👍
> 
> What about...?
> 
> * links not currently in the profile are faded slightly or shown in a separate list underneath the main list of link stats
> * when we add filters like: last 30 days, older links will not be displayed

a separate list seems like a good idea

**Comment by khanahmar** [comment]
is this issue open yet

**Comment by eddiejaoude** [comment]
> is this issue open yet

@khanahmar please read the contributing guide to understand the labels rather than ask this on multiple issues https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by AJcodes42** [comment]
I tried looking into it. But was not able to find any mechanism to identify the links that have been deleted to show in separate list. If someone can guide on how we can identify the deleted link I would like to take this up. Applying filter for last 30days seems like a straight forward solution.

**Comment by ChinmayMhatre** [comment]
> I tried looking into it. But was not able to find any mechanism to identify the links that have been deleted to show in separate list. If someone can guide on how we can identify the deleted link I would like to take this up. Applying filter for last 30days seems like a straight forward solution.


I have not gone tested this but I have gone through the code and noticed this:


If we check the `data` object that is passed and used in `statistics.js`. it comes from this api call

## statistics.js

<img width="716" alt="image" src="https://user-images.githubusercontent.com/51131670/231757274-a95307c1-6511-49db-bee5-cfaa7f6f78ff.png">

 Note: This contains all previous links


If we navigate to the `[username].js` where only current links are displayed there is also a `data` object but it comes from `getUserApi` call. 

##  [username].js

<img width="685" alt="image" src="https://user-images.githubusercontent.com/51131670/231758212-c6b74cab-6e5f-46f8-8e58-b82a6de68cab.png">

<img width="685" alt="image" src="https://user-images.githubusercontent.com/51131670/231758272-dd397427-e11f-4bf9-aad6-a985d087473f.png">

Note : This contains current links.

---

To conclude, `profile`  object from the `getUserApi` call exists in `statistics.js` as well. you can use `data.links` for all links and `profile.links` for current links and compare. (Please verify this I am not sure).

**Comment by AJcodes42** [comment]
Thanks @ChinmayMhatre. I missed the `getUserApi` call in `statistics.js`. Could you please assign the issue to me and also let me know how the deleted links should get disabled.

**Comment by eddiejaoude** [comment]
Great collab 👍 

Yes let's not remove them, let's fade them so people can still see historic links for now

I will assign the issue
