### ISSUE TITLE
[OTHER] Addtion of Rocket.chat icon in icons.json

### ISSUE THREAD

**Issue by imf-ali** [EddieHubCommunity/LinkFree#5247]
### What would you like to share?

Description

I want to show case my Rocket.chat contribution milestone. For I this I need approval for introducing FaRocketchat icon in icon.json

Here is the icon preview
![image](https://user-images.githubusercontent.com/42451210/222910121-f70d189c-1444-4706-ad31-58724aab9d2d.png)

**Comment by amandamartin-dev** [comment]
This icon is already available to use as shown here when searching avalable icons.  https://linkfree.eddiehub.io/icons

![rocketchat](https://user-images.githubusercontent.com/97615019/222919042-96b53a32-93dd-45cc-9bfb-2e9316a24224.jpg)

**Comment by imf-ali** [comment]
Oh yes, I saw the website as well. It's showing up. This issue can be closed. 
Thanks @amandamartin-dev.
