### ISSUE TITLE
Buttons used as links need role="link" to signify to screen readers that they are linking to another page

### ISSUE THREAD

**Issue by EmmaDawsonDev** [EddieHubCommunity/LinkFree#526]
### Description

The buttons on the milestone cards in milestones.js redirect to another site and therefore need role="link" added. Also because the url opens in a new window for extra safety it should also have an attribute rel="noopener noreferrer"

https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noreferrer

https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noopener

### Screenshots

<img width="250" alt="Screenshot 2021-10-17 201831" src="https://user-images.githubusercontent.com/57045550/137640000-7a485f12-865a-41cd-94ac-5a4d3151e987.png">
<img width="473" alt="Screenshot 2021-10-17 201913" src="https://user-images.githubusercontent.com/57045550/137640001-8c6b30fe-4efa-4109-9aa2-d3da7a9bacae.png">

**Comment by krishguptadev** [comment]
> Is this issue still not resolved? I would like to work on this.

Looks like someone has already started to work on it :) Please have a look to our other issues
