### ISSUE TITLE
[DOCS] <link not working properly>

### ISSUE THREAD

**Issue by Akash3121** [EddieHubCommunity/LinkFree#5286]
### Description

https://linkfree.eddiehub.io/docs/how-to-guides/editing point 17.

The link showing is this: https://linkfree.eddiehub.io/SaraJaoude

but when we **click** on it, it's taking to this: https://linkfree.eddiehub.io/docs/how-to-guides/linkfree.eddiehub.io/SaraJaoude
this will give a 404 - page not found as it is not the correct one.

### Screenshots

<img width="952" alt="image" src="https://user-images.githubusercontent.com/87650180/223321586-f0bbf446-fddf-4f96-b2ce-e4203039013b.png">

**Comment by harshit-002** [comment]
hey @Akash3121, I would like to work on it, can you assign this to me?

**Comment by Akash3121** [comment]
I have not seen this your PR coming buddy!
