### ISSUE TITLE
please send me invitation to join organization

### ISSUE THREAD

**Issue by sumitshinde-84** [EddieHubCommunity/LinkFree#5301]
### What would you like to share?

please send me invitation to join organization

**Comment by kumarsonsoff3** [comment]
This is probably not the right place for this issue. To join the org, you need to create an [**issue here**](https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) in the support repo. You'll then receive an invitation.

**Comment by sumitshinde-84** [comment]
thank you @kumarsonsoff3
