### ISSUE TITLE
[BUG] Account Statistics - own visits added after every refresh 

### ISSUE THREAD

**Issue by Hoargarth** [EddieHubCommunity/LinkFree#5311]
### Description

Currently my own visits to my own profile and as well the /account/statistics page adding towards to view count in statistics.

This happens when
- going to the profile/statistics via any link
- on refresh

I can do it multiple times and always the view count gets up.

In my opinion at least my own views shouldn't ve counted. Especially if I'm visiting the sratistics page.

**Comment by Akhilbisht798** [comment]
Yes, this is confirmed. On refresh or on loading profile view count increase.
I don't known if this is meant to be this way or not. 
If it is than totally fine

**Comment by Akhilbisht798** [comment]
Can I work on this issue?

**Comment by Akhilbisht798** [comment]
Hey, I am trying to solve this and as @eddiejaoude said this happen when API end-point is requested. I am not quite sure the endpoint responsible for this but i think it is  `pages/api/users/[username]/index.js`. I have a solution for this.

To check if user is authenticated in `pages/api/users/[username]/index.js`. If user is authenticated than we do not run the code for the increment of view count.. In this we have to update `getUserApi` function to have a extra parameter `isAuthenticated` and provide its value from `handler` where it is called from.

Should i continue on this solution or  is there some better way we can do this?

**Comment by Akhilbisht798** [comment]
I am trying to fix this. @eddiejaoude Should we check this on `pages/api/users/[username]/index.js` as i think that is API that is incrementing the user. 
From that we can check if authenticated user and profile are same and if they are same don't increment. We have update some function for that.
Also `const session = await unstable_getServerSession(req, res, authOptions)` is this okay to get information about user who is authenticated.

**Comment by eddiejaoude** [comment]
Thank you for the question 👍 

Yes use the session information in the API, and like you mentioned if the authenticated user is the profile owner then don't increment the profile view counter
