### ISSUE TITLE
[FEATURE] Clear filters for map

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#5312]
### Description

Create a clear filters tag/button for the map page to be able to reset the data. Currently the only path to do this is refreshing the browser.

### Screenshots

![clearmap](https://user-images.githubusercontent.com/97615019/224116448-e8266de3-eab1-42ed-a143-ef09e2d65863.jpg)

**Comment by weilincheng** [comment]
Hello, I was wondering if I could be assigned to work on this issue. I am very interested in contributing and would love the opportunity to do so. Thank you!

**Comment by amandamartin-dev** [comment]
> Hello, I was wondering if I could be assigned to work on this issue. I am very interested in contributing and would love the opportunity to do so. Thank you!

Assigned! Thank you for contributing
