### ISSUE TITLE
[FEATURE] Tag filter highlight on map page

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#5313]
### Description

The tag based filtering on the map page should stay highlighted on filter selection.  It should mimic the functionality on the search page.

**Comment by harshit-002** [comment]
I am unable to see the **tags** in **/map** my gitpod devlopment environment, can someone help me please?
<img width="955" alt="image" src="https://user-images.githubusercontent.com/95224348/224310908-17293387-b802-4a01-8f67-8eecae1a88a0.png">

**Comment by gquaresma-godaddy** [comment]
I can work on that!

**Comment by joaoGabriel55** [comment]
I can work on that!

**Comment by amandamartin-dev** [comment]
> I can work on that!

I see you already opened a PR.  In the future for the linkfree repo, please wait to be assigned so we don't end up with multiple folks creating pr's for the same issue.  I will assign to you now.  Thanks for contributing!
