### ISSUE TITLE
[Toast] a prime react component for showing alert

### ISSUE THREAD

**Issue by Yax-coder** [EddieHubCommunity/LinkFree#532]
### Description

a prime react component for showing alert notifications based on action, i.e error, success, info and etc.

**Comment by Yax-coder** [comment]
![screenshot-localhost_3001-2021 10 18-14_13_18](https://user-images.githubusercontent.com/48949826/137750909-6fa63df7-ec70-497b-9439-68379195e571.png)

**Comment by krishguptadev** [comment]
Looks good but can you share some use cases? Like what errors could even occur in this project?

**Comment by Yax-coder** [comment]
@krishguptadev  take a look at this pull request https://github.com/EddieHubCommunity/LinkFree/pull/533 and see the changes, and as for "what error could even occur", you should know there is no perfect code. and what i did on the pull request was to leverage the prime-react toast component rather than continue using the native js alert. we account for errors to make sure that when they occur we handle them better, not because we think they can't occur.
