### ISSUE TITLE
[OTHER] Incorrect Map

### ISSUE THREAD

**Issue by Rahulbaran** [EddieHubCommunity/LinkFree#5346]
### What would you like to share?

Good morning, I was going through **Map** tab and noticed an incorrect map of my country **Bharat(India)**
I request you to use a correct map.

**Comment by eddiejaoude** [comment]
Please can you share more information about what is incorrect and what it should be? Please use screenshots for both

**Comment by Rahulbaran** [comment]
This is the incorrect map
![incorrect](https://user-images.githubusercontent.com/65500579/224478736-f4f8352a-737c-480f-be2a-6d2de4ff49e8.png)


Here is the correct one
![bharat](https://user-images.githubusercontent.com/65500579/224478697-b306f3bd-9d26-48de-9b48-e6f121471e08.jpg)

**Comment by eddiejaoude** [comment]
We do not make the map, it is provided to us by the tool we use `leaflet`. You will need to submit it to that project for any changes
