### ISSUE TITLE
[FEATURE] A loader or some sort of indication that the user is actually navigating to other page

### ISSUE THREAD

**Issue by probablyArth** [EddieHubCommunity/LinkFree#5366]
### Description

Loading pages takes quite a while sometimes, and when switching between the pages there's no way of knowing that you are actually switching, when I first saw it I thought that the website is broken or something but then it changed.

**Comment by eddiejaoude** [comment]
This is a duplicate of https://github.com/EddieHubCommunity/LinkFree/issues/3900, so I will close this issue
