### ISSUE TITLE
[DOCS] Need more examples to explain agile points

### ISSUE THREAD

**Issue by adityaraute** [EddieHubCommunity/LinkFree#5375]
### Description

Introduce more examples for Agile points table.

Currently there are no examples for 8 and 13 points, whereas only 1 point has two examples.

Also, those examples for point 3 and 5 are not really examples but an explanation of the kind of issues that are assigned those points. For e.g. Point 5 example can be replaced with something like "Adding a ChatGPT-based bot for interaction" (bad example ik but I hope it drives the point home).

### Screenshots

![image](https://user-images.githubusercontent.com/43912470/224539536-149f312d-8de7-4c0c-ad53-f6c61cae3fe5.png)

### Additional information

Might wanna consider getting rid of point levels for which we cannot have any valid examples

**Comment by amandamartin-dev** [comment]
i think the difficulty with defining concretely what each point level in fibonacci based agile will amount to is that it will be different for every dev based on their level of expertise with what they are attempting to do.  I like that the examples are a bit more general, but I could see how it would be confusing if you have never worked with this methodology before. 

Perhaps a link to a quick video or definition of how to think about fibonacci would help in addition to a few different types of examples?

**Comment by adityaraute** [comment]
>  it will be different for every dev based on their level of expertise

I didn't realize this when I read the docs.

Whether we choose to go specific or general, important point is that we must have adequate examples.

**Comment by amandamartin-dev** [comment]
> I didn't realize this when I read the docs.

Yes, I only knew about it because this was the way I had to assign points to my own work on my last dev team.  It took awhile to get the hang of it for me.

Makes sense that a definition of how fibonacci works in dev estimation and a variety of examples would be useful

**Comment by eddiejaoude** [comment]
More examples will be good 👍
