### ISSUE TITLE
[FEATURE] Map display total results

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#5405]
### Description

Display the total amount of users on the map with/without filters, for example 

- if there were 100 people and with no filters, it would show `100/100`
- with a filter that only showed 60 people, it could display `60/100`

https://linkfree.eddiehub.io/map

**Comment by lmac-1** [comment]
Hello! Could I be assigned this one? I'd love to work on it 🤩

**Comment by lmac-1** [comment]
I've been taking a look at this. A few questions:
1. I haven't touched anything to do with the map but every time I make a change locally on the map page, I am getting the following error `Error: Map container is already initialized.`. Seems like a dev only issue but was wondering if you already knew about it. The error goes away if I refresh the page, but it's just a bit annoying when developing.
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/64803272/225462419-766e5e7b-0899-41ae-b2a5-6c35017c5e23.png">


2. I had a go at using the component you suggested but I can't find a good place for the component with the current design. I was thinking to create something like this, but I think that I'd need to fix an extra bug as part of this PR:

![image](https://user-images.githubusercontent.com/64803272/225468786-931dffd0-6fa2-41ab-856a-a539428d25df.png)
![image](https://user-images.githubusercontent.com/64803272/225468823-59343dd4-da33-443f-bcdf-0df4999e8bc8.png)


At the moment, when you deselect a tag, it has no effect on the map. You have to click the **Clear/Reset Filters** button in order for the map to update. With the above design, I think it would be a bit confusing so I'm suggesting that I should fix this bug as part of this PR. This would mean that when you deselect the tag, it would update the users on the map straight away. We would still have a **Clear Filters** button on the right hand side in case the user selects all the tags and wants to remove them easily. 

What do you think?

**Comment by eddiejaoude** [comment]
Thanks Lucy for the detailed reply 👍 

1. I think this is due to the SSR, maybe @amandamartin-dev knows more?
2. Maybe for now we can keep it simpler and use the `Badge` component on the `clear filters` button? https://github.com/EddieHubCommunity/LinkFree/blob/main/components/Badge.js
3. Do not worry about the de-toggle (un-toggle?) bug it is being worked on here https://github.com/EddieHubCommunity/LinkFree/issues/5420

**Comment by amandamartin-dev** [comment]
@eddiejaoude and @lmac-1  Hey! Thanks for the tag - yup, this will happen only during dev because of the way the updates push the code while you work.  You can just refresh and it will be fine. 

One thing to note with the tags is that those counts are inaccurate.  I noted this in the PR when I created v1 of the tags but when you pull the data from the tags API it already comes with counts that are based on all of LF profiles whereas the map data will only pull folks with a location.

I was not sure how to remedy this at that time without an adjustment to the underlying API or some other method.

**Comment by lmac-1** [comment]
Thanks @amandamartin-dev - just wanted to check it wasn't a new error. 

Good point about tag counts! But we aren't actually using them to calculate the total number of selected users on this page. We are calculating everything from `users` which is returned from `getServerSideProps`. This is returning the users that have a location set: 

```
data.users = data.users.filter(
    (user) =>
      user.location &&
      user.location.provided &&
      user.location.provided !== "unknown" &&
      user.location.name !== "unknown" &&
      user.location.provided.toLowerCase() !== "remote"
  );
```

**Comment by lmac-1** [comment]
And thanks @eddiejaoude! I am taking a look at the `Badge` component and will report back.

**Comment by amandamartin-dev** [comment]
> Thanks @amandamartin-dev - just wanted to check it wasn't a new error.
> 
> Good point about tag counts! But we aren't actually using them to calculate the total number of selected users on this page. We are calculating everything from `users` which is returned from `getServerSideProps`. This is returning the users that have a location set:
> 
> ```
> data.users = data.users.filter(
>     (user) =>
>       user.location &&
>       user.location.provided &&
>       user.location.provided !== "unknown" &&
>       user.location.name !== "unknown" &&
>       user.location.provided.toLowerCase() !== "remote"
>   );
> ```

True! But perhaps after this issue we should create one to handle the tag counts since with the map user count now visible it might become confusing that the tag counts don't add up to the map count?  Not critical at all and can definitely be handled separately

**Comment by eddiejaoude** [comment]
> I was not sure how to remedy this at that time without an adjustment to the underlying API or some other method.

> But perhaps after this issue we should create one to handle the tag counts since with the map user count now visible it might become confusing that the tag counts don't add up to the map count? Not critical at all and can definitely be handled separately

yep we can have a separate issue to fix this, I have an idea on how this could be solved - but I don't think it is a blocker for this issue

**Comment by lmac-1** [comment]
Yeah I hadn't paid attention so much to this because I didn't have all of the users in my local db. I was just assuming it would total up correctly when all the users were there, but looking into the code a bit more, it looks like it won't.

Definitely interested in the best practice to solve this problem, so will be keeping an eye out on the other issue 😁. Is it #5281?

**Comment by amandamartin-dev** [comment]
>  Is it #5281?

Oh! I just looked at that issue, I'm not sure if it's the same or not, but basically the tag counts would need to not be tied to total profiles for the map to be accurate.  So unclear whether it could be solved in the scope of that issue or would still be handled separately.  Good catch!

**Comment by lmac-1** [comment]
Yeah I am wondering if we need a separate issue for the tag issue on the maps page but perhaps there's another one lurking around that I missed!

**Comment by amandamartin-dev** [comment]
I think you are good creating it, I know I forgot to make one for it after I noticed and am not seeing one specific to the map either

**Comment by eddiejaoude** [comment]
> Definitely interested in the best practice to solve this problem, so will be keeping an eye out on the other issue 😁. Is it https://github.com/EddieHubCommunity/LinkFree/issues/5281?

This one is different. Feel free to raise an issue if you like for the new issue

**Comment by lmac-1** [comment]
PR and issue raised 🎉 thanks everyone!

**Comment by eddiejaoude** [comment]
Great collab 🚀
