### ISSUE TITLE
[DOCS] QuickStart documentation should clarify that avatar property is no longer needed

### ISSUE THREAD

**Issue by sebashmh** [EddieHubCommunity/LinkFree#5419]
### Description

The [QuickStart documentation ](https://linkfree.eddiehub.io/docs/quickstart) does a great job explaining how to get started with LinkFree. However, in the video, there are a couple of mentions that are not actually used or accepted in the .json file.

The QuickStart documentation should be updated clarifying that the `avatar` property is no longer needed or no longer accepted in the .json file.

### Screenshots

<img width="1176" alt="Screenshot 2023-03-13 at 15 28 14" src="https://user-images.githubusercontent.com/26228479/224811980-59c2fa2e-5ae8-4cc4-9523-e609aa7a697c.png">

### Additional information

Even though the example code in the QuickStart guide does not include the `avatar` property, it would be better to add a clarification that this property is no longer used. This will ensure that users who watch the video have a clear understanding of the changes.

**Comment by eddiejaoude** [comment]
Thank you for raising 👍

**Comment by sebashmh** [comment]
No problem! I could fix it too, I would love to contribute to the community.
