### ISSUE TITLE
Map toggle off tag does not work

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#5420]
### Description

After filtering by a tag, visually it toggles off, but functionality it does not seem to work

1. First coming to the page with no filters...

<img width="1672" alt="Screenshot 2023-03-14 at 08 29 13" src="https://user-images.githubusercontent.com/624760/224854530-9ed84c72-1608-4d37-9957-c9ff14180992.png">

2. Then after applying a tag filter...

<img width="1665" alt="Screenshot 2023-03-14 at 08 29 21" src="https://user-images.githubusercontent.com/624760/224854563-0f678412-5d1b-49b2-89a5-ce4f2d3401e6.png">

3. After removing the tag filter it should return to the first screenshot...

<img width="1674" alt="Screenshot 2023-03-14 at 08 29 30" src="https://user-images.githubusercontent.com/624760/224854619-fe2ddb9e-9714-48db-a33f-f53d6661ef05.png">

**Comment by weilincheng** [comment]
Hello Eddie,

Could you please assign me to work on this issue? I believe I have a good understanding of the map page already.

Thank you!

**Comment by eddiejaoude** [comment]
Great! Yes, I have assigned it to you @weilincheng 👍
