### ISSUE TITLE
Map clear filter button looks out of place

### ISSUE THREAD

**Issue by ChinmayMhatre** [EddieHubCommunity/LinkFree#5432]
### Description

<img width="1388" alt="image" src="https://user-images.githubusercontent.com/51131670/224912500-e0c29aff-c3ce-4c51-9060-135bf7eaf555.png">

the filter and the description have different alignment

**Comment by probablyArth** [comment]
I'd like to get assigned

**Comment by AKHIL-GIREESH** [comment]
Hi, I'd love to work on this issue! Could you assign it to me?

**Comment by sanskar1306** [comment]
I wish to work on this issue.

**Comment by MAYANKpandey14** [comment]
Hey @ChinmayMhatre i think this looks fine considering the alignment being similar.

![Screenshot 2023-03-18 at 2 00 40 PM](https://user-images.githubusercontent.com/94740455/226094711-851ea37b-d49c-4799-8bb4-def4ca25ae7f.png)

**Comment by ChinmayMhatre** [comment]
> I'd like to get assigned

 I am not a maintainer so I can't assign you but you can get go ahead with this. Thank you!

**Comment by MAYANKpandey14** [comment]
> Hey @ChinmayMhatre i think this looks fine.
> 
> ![Screenshot 2023-03-18 at 2 00 40 PM](https://user-images.githubusercontent.com/94740455/226094711-851ea37b-d49c-4799-8bb4-def4ca25ae7f.png)

OK waiting for eddie to also see this and give feedback .

**Comment by MadhuSaini22** [comment]
Would be happy to work on this UI fix :)

**Comment by amandamartin-dev** [comment]
> I'd like to get assigned

Hello! Sorry for the delay. Please let me know if you are still interested in this issue, if not I will check the next folks who commented.  Assigning for now, awaiting confirmation.

**Comment by probablyArth** [comment]
I'm On it 👍

**Comment by probablyArth** [comment]
> > I'd like to get assigned
> 
> Hello! Sorry for the delay. Please let me know if you are still interested in this issue, if not I will check the next folks who commented. Assigning for now, awaiting confirmation.

I'm on it 👍

**Comment by SaraJaoude** [comment]
I am closing this Issue for now as there seems to be no clear solution and we may be looking to redesign in the future.
