### ISSUE TITLE
map , and search taking long time to open ,sometimes double click

### ISSUE THREAD

**Issue by AniketShuklaG** [EddieHubCommunity/LinkFree#5453]
### Description

 **map , and search taking long time to open ,sometimes double click**
[https://linkfree.eddiehub.io/](url)

### Screenshots

![image](https://user-images.githubusercontent.com/127586592/225212316-607de432-c094-4271-905b-8651d5987c10.png)

### Additional information

can someone please check that  _,**this could be frustrating to others**_

**Comment by eddiejaoude** [comment]
These pages are loading all the users before displaying, we have an issues already open this https://github.com/EddieHubCommunity/LinkFree/issues/2815

**Comment by AniketShuklaG** [comment]
thanks , I didn't knew about that .
