### ISSUE TITLE
Add Ability to Download QR Code of Profile Link for Social Media Sharing

### ISSUE THREAD

**Issue by iAnonymous3000** [EddieHubCommunity/LinkFree#5454]
### Description

Linkfree allows users to create a profile with their links and share it with others. However, it would be useful if users could also download a QR code of their profile link that they could share on social media platforms. This feature would enable users to promote their links and profile more effectively, making it easier for others to access them.

Adding the ability to download a QR code of a Linkfree profile link would offer several advantages to users:
- Users would be able to share their links on social media platforms easily
- It would enable them to promote their Linkfree profile offline, for example, on business cards and flyers.
- Providing a QR code for their profile link would make it more convenient for others to access their links without needing to type the URL manually.

**Comment by eddiejaoude** [comment]
Great idea 👍

**Comment by ujjawal-4664** [comment]
[
![image](https://user-images.githubusercontent.com/105547714/225375263-ed83abea-79cb-4a76-bb1c-225274ba3a5b.png)
](url)

**Comment by MAYANKpandey14** [comment]
### We can add a QR download button which downloads the user's QR in png form just below where QR shows up after clicking on the profile.

It will look like this :
![Screenshot 2023-03-15 at 11 58 39 PM](https://user-images.githubusercontent.com/94740455/225407709-6d678ccc-e557-4508-8c84-6bbda5a57ba2.png)

Rest we just need to add a simple JS function to start downloading the created png of QR code once the button is clicked.
I am interested to contribute to code first time . Can you assign me ?

**Comment by nishant-siddh** [comment]
assign me

**Comment by nishant-siddh** [comment]
That seems great, please assign me to it.

**Comment by nishant-siddh** [comment]
That seems good, please assign me to it.

**Comment by eddiejaoude** [comment]
Thank you @MAYANKpandey14 for the example 👍 I will assign it to you

@nishant-siddh it was already requested

**Comment by SyedImam1998** [comment]
Hey,👋 @eddiejaoude I have designed for both the Desktop and Mobile version.
may be this design could look nice.



### Desktop Version:

https://user-images.githubusercontent.com/52135949/225517432-d48bfe7a-db27-49bc-8f2a-d48ec63c0965.mp4

### Mobile Version


https://user-images.githubusercontent.com/52135949/225517509-8c1f26fc-d024-4b53-b146-6d1d2c2e9b5f.mp4

**Comment by MAYANKpandey14** [comment]
> Hey,👋 @eddiejaoude I have designed for both the Desktop and Mobile version. Please play the video. Maybe this design could look nice.
> 
> #### Note: These are just Figma Designs not yet implemented. I am happy to update them as per requirements.
> ### Desktop Version:
> ### Mobile Version

Great work @SyedImam1998 really like your design but I think for a task as simple as to download a QR we should not add this much code to the repo ,a simple button will do the same . I think we should prioritize functionality.
What do you think @eddiejaoude ? Correct me if you think I am wrong.

**Comment by MAYANKpandey14** [comment]
### Desktop Version:
![Screenshot 2023-03-16 at 10 13 34 PM](https://user-images.githubusercontent.com/94740455/225691952-ef5b51c6-a2f7-407b-97de-7c9d7f7d2123.png)

### Mobile Version:

![Screenshot 2023-03-16 at 10 14 06 PM](https://user-images.githubusercontent.com/94740455/225691979-1755ccf6-19c0-455b-9b37-87acf5b4ef02.png)

### Quick Question ?
Should the button only appear when the smaller orange coloured QR badge is clicked or button should appear always for users to directly download the QR code and not use it from the site itself.

**Comment by eddiejaoude** [comment]
@SyedImam1998 really nice designs, I think it is best if these come in another pull request, here we can work on the functionality more (also I think the desktop and mobile should be the same design)

@MAYANKpandey14 yes please keep it simple for now, I think the download QR should only show when the QR is showing otherwise it will take up too much vertical space (note we have a component for `Button` you can reuse)

**Comment by SyedImam1998** [comment]
> I am happy to update them as per requirements.

Thanks for the feedback @eddiejaoude.

**Comment by SyedImam1998** [comment]
> @SyedImam1998 really nice designs, I think it is best if these come in another pull request, here we can work on the functionality more (also I think the desktop and mobile should be the same design)
> 
> @MAYANKpandey14 yes please keep it simple for now, I think the download QR should only show when the QR is showing otherwise it will take up too much vertical space (note we have a component for `Button` you can reuse)

Thanks for the feedback @eddiejaoude.

**Comment by MAYANKpandey14** [comment]
> @SyedImam1998 really nice designs, I think it is best if these come in another pull request, here we can work on the functionality more (also I think the desktop and mobile should be the same design)
> 
> @MAYANKpandey14 yes please keep it simple for now, I think the download QR should only show when the QR is showing otherwise it will take up too much vertical space (note we have a component for `Button` you can reuse)

Got it @eddiejaoude. Thank you for the feedback 👍

**Comment by MAYANKpandey14** [comment]
### Final Look , completely responsive and download button displayed only on-click as suggested.
Sorry for the quality of the video, old laptop. 
Video's aim is to give a good understanding of the outcome.



https://user-images.githubusercontent.com/94740455/225841110-226a6515-e88e-4b27-9549-a6f705ce10b4.mp4

**Comment by MAYANKpandey14** [comment]
If this is ok @eddiejaoude , I will move forward to making the pull request .
