### ISSUE TITLE
Profile image different 

### ISSUE THREAD

**Issue by saifrahmn** [EddieHubCommunity/LinkFree#5455]
### Description

My profile image was the image that you see on my github profile but now that I checked after few months, I see a random guys image on my profile.

### Screenshots

![image](https://user-images.githubusercontent.com/64410006/225238227-447ef439-b548-48ac-a1ea-a0bad8f95027.png)

**Comment by khushalarora** [comment]
I found the cause of this Bug, please assign me this issue.
I would be really happy to help.

**Comment by eddiejaoude** [comment]
@saifrahmn your profile doesn't match your GitHub username, that is why

**Comment by eddiejaoude** [comment]
This is not a bug, please raise a pull request renaming your file to your GitHub username not someone else's

**Comment by eddiejaoude** [comment]
yes but they also need to update where they use the link, as the link uses the GitHub username
