### ISSUE TITLE
[FEATURE] Add events validation in playground

### ISSUE THREAD

**Issue by MahirMahdi** [EddieHubCommunity/LinkFree#5457]
### Description

Add another option in the playground for events just like profile:

   - validates json
   - formats json
   - shows event card

**Comment by vibronst** [comment]
We would like to be assigned this task!

**Comment by amandamartin-dev** [comment]
> We would like to be assigned this task!

All yours!

**Comment by KaveriRai** [comment]
hello. could i please be assigned this issue

**Comment by eddiejaoude** [comment]
@vibronst and @KaveriRai great to see you are working together on this issue, I have assigned it to you both

**Comment by eddiejaoude** [comment]
I am going to close this issue, as the pull request has been closed and in the near future forms will be available
