### ISSUE TITLE
[DOCS] Need more information on why user markers not appearing on map in local development mode

### ISSUE THREAD

**Issue by weilincheng** [EddieHubCommunity/LinkFree#5473]
### Description

In the current implementation, a user's location information in MongoDB is only updated when they visit their specific profile page. This leads to the map page not displaying any user markers during local development since no user has their location information yet in the database. To display user markers on the map page, developers need to visit multiple user profiles to populate the database with location information.

It would be helpful to update the map page documentation to reflect this behavior and provide clear instructions on how to populate the database with location information.

### Screenshots

In the local development environment, the map snapshot will not display any user markers if no profiles have been visited. Therefore, it is necessary to visit at least one user profile to populate the map with user markers.

Initially, no user markers
![image](https://user-images.githubusercontent.com/7236196/225502855-3a2425dc-31b5-4753-96d6-d1ed71890961.png)

After visiting some profiles:
![image](https://user-images.githubusercontent.com/7236196/225504499-785aa266-076c-457b-9988-42584e9af1be.png)

**Comment by naomi-lgbt** [comment]
Seems like it might be a good idea to have a `seed` script that can be run locally to fill the database with some location data?

**Comment by weilincheng** [comment]
> Seems like it might be a good idea to have a `seed` script that can be run locally to fill the database with some location data?

Great idea! However, we should also consider that running a seed script locally could potentially hit the rate limit for location data. Eddie brought up a good point, so we might need to think of an alternative solution to avoid this issue. In the meantime, we can document the current behavior and brainstorm potential solutions to this problem. Thank you for bringing this up!

**Comment by weilincheng** [comment]
Could I be assigned to this issue, please? I would really appreciate it. Thank you!

**Comment by naomi-lgbt** [comment]
How would we hit a rate limit? Generally a database seed includes all of the data needed for testing locally - that is, we'd hard-code location data into the mock database records, rather than calling any APIs.

**Comment by weilincheng** [comment]
> How would we hit a rate limit? Generally a database seed includes all of the data needed for testing locally - that is, we'd hard-code location data into the mock database records, rather than calling any APIs.

Thank you for the clarification, Naomi. I initially assumed the script would need to call APIs to obtain location data. However, since it does not involve any API calls, we won't encounter any rate limits.
Perhaps we could utilize a library such as [Faker](https://fakerjs.dev/) to generate hard-coded location data, and then use the seed script to insert it into our local MongoDB instance?

**Comment by naomi-lgbt** [comment]
That could certainly be an option, yes!
