### ISSUE TITLE
[FEATURE] Proposing Designs for downloading QR image

### ISSUE THREAD

**Issue by SyedImam1998** [EddieHubCommunity/LinkFree#5494]
### Description

Hey, @eddiejaoude I have some designs that can help download QR codes without taking much space on the screen.
I am happy to update them according to the requirements.

#### Desktop Design:

https://user-images.githubusercontent.com/52135949/225814990-f23c9bbe-945c-4166-ab32-32ec11bb6a53.mp4

#### Mobile Design:

https://user-images.githubusercontent.com/52135949/225815023-ab03a5d1-5aaf-4da7-b885-7c359272ce36.mp4

**Comment by SyedImam1998** [comment]
Hey @iAnonymous3000 Something like this Right?

#### Sample Image:
![image](https://user-images.githubusercontent.com/52135949/225967566-03e07aad-7abd-48a9-843b-c3340fde163a.png)

**Comment by eddiejaoude** [comment]
How does a hover work on a mobile? It should probable be on click of the QR code the button appears?

**Comment by SyedImam1998** [comment]
Yes @eddiejaoude on mobile we should click on qr code to get the option to download.
As you know hover mode in mobile screens activates when you tap.

Do you want me to think 🤔 something else for mobile???

**Comment by eddiejaoude** [comment]
it will be mostly used on mobile, and I think it would be best to keep it simple and clear

What about having the download button just the QR code for all devices and we can make further improvements later

**Comment by SyedImam1998** [comment]
If that is the case we can close this feature issue because this feature has already been implemented on Issue: #5539 

**Note:** Just my POV
Normally Users tap on QR Code when they see it. So hovering on the large screens works fine and on mobile when they tap works I guess this is what I feel. Let me know if i am wrong🤗

I am okay with anything that makes users feel great.🤩🤩

**Comment by eddiejaoude** [comment]
From my experience people will not know to tap the QR code on mobile to get the extra option - let us close this for now and see how the feature does, then we can revisit this in the future

Thank you for the great creative designs 👍
