### ISSUE TITLE
[FEATURE] Profile progress complete

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#5496]
### Description

Display how much of their profile is complete

- links
- social shortcuts
- events
- testimonials
etc

**Comment by ChinmayMhatre** [comment]
I think this is a great idea. It encourages the user to creating a better fuller profile. I do think we shouldn't add the events as a part of the profile completion percentage, it could be under a section like "How you can improve your profile further" after the user has added all the basic ones.

Would love to work on this if we decide to go ahead.

**Comment by eddiejaoude** [comment]
> I think this is a great idea. It encourages the user to creating a better fuller profile. I do think we shouldn't add the events as a part of the profile completion percentage, it could be under a section like "How you can improve your profile further" after the user has added all the basic ones.

Great question, something we can continue to discuss and improve

> Would love to work on this if we decide to go ahead.

sure, I will assign it to you

**Comment by ChinmayMhatre** [comment]
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/51131670/227181545-cb7ad29d-3551-4fb7-8014-42daee7b7897.png">

I have gotten the feature this far. I wanted feed back on the hint :
1. We could add screenshot on how the section looks like (for example socials in the ss)
2. We could have a code block with the json to add that section
3. Just have a description on why the user should add it

Which would make the most sense?
