### ISSUE TITLE
Clear/Reset Filters button on the map page should be disabled by default

### ISSUE THREAD

**Issue by FrozenHearth** [EddieHubCommunity/LinkFree#5500]
### Description

Right now, Clear/Reset filters is enabled by default, and clicking on it doesn't do anything. When I click on a tag, and then click on this button, it works fine.
I think disabling it by default would be a better UX. Else, the user is confused when nothing happens when the button is clicked without any tags being selected.

### Screenshots

<img width="1439" alt="Screenshot 2023-03-17 at 6 26 34 PM" src="https://user-images.githubusercontent.com/27160715/225911136-0a7ccc4b-668b-463b-8a10-b71f72b9f4f5.png">

**Comment by eddiejaoude** [comment]
Yes good suggestion 👍

**Comment by Vedant-Manjrekar** [comment]
I would like to work on this issue, please assign it to me.

**Comment by MAYANKpandey14** [comment]
> 

Yes, it should be displayed only when you select a tag for the map. 
Thank you for the Contribution to the community @FrozenHearth 
Keep up the good work 💯

**Comment by FrozenHearth** [comment]
Thanks! @eddiejaoude @MAYANKpandey14 
@Vedant-Manjrekar One of the maintainers will assign you the issue soon.
