### ISSUE TITLE
[FEATURE] Mark PR as blocked if issue does not have label `status: ready for dev`

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#5511]
### Description

Continue building on this feature https://github.com/EddieHubCommunity/LinkFree/issues/5371

**Comment by Ananya2001-an** [comment]
Hey @eddiejaoude I am not sure if you are aware of it or not but you can use reviewpad's playground to test its working instead of creating new PRs again and again.

**Comment by eddiejaoude** [comment]
Oh thank you 👍

Btw I had to comment it out because I couldn't get the linked issue to work

**Comment by Ananya2001-an** [comment]
That's weird. It was working when I used it.  You can also see that in my PR #5394 there was a linked issue so it didn't add the blocked label.

**Comment by eddiejaoude** [comment]
> can you tell me why you commented out the previous solution

can you please give some context?

> what do mean by "Mark PR as blocked"

add the label `status: blocked` (I will need to double check the label name but I think that I sit)

**Comment by amitabh-sahu** [comment]
> can you please give some context

I was talking about Ananya2001-an reviewpad's solution which you commented out in reviewpad.yml as you mention in earlier comments so I keep that in mind while working on this

**Comment by lokesh3097** [comment]
Yeah @eddiejaoude I have raised a new [issue](https://github.com/reviewpad/reviewpad/issues/828) on reviewpad requesting for a feature. I'm hoping that someone responds. (I actually thought of considering me taking up the same issue but I have absolutely no clue about Go and reviewpad's other tech stack)

**Comment by SaraJaoude** [comment]
This is being done manually for the moment, so I will close this Issue to clear up the issues backlog.
