### ISSUE TITLE
[FEATURE] Redesign search bar and filter for improved usability

### ISSUE THREAD

**Issue by SyedImam1998** [EddieHubCommunity/LinkFree#5516]
### Description

Hey Team 👋,

#### Description:

I would like to propose a new design for the search bar and filters, which I believe would improve the overall user experience. As a user, I have noticed that the current UI is a little bit difficult to understand and as the tech stack grows it won't be able to show all the tech filters on the screen and alignment of the numbers on top of the tech name needs a little bit of enhancement which displays a clear message to the user.

I believe that this design would provide a more intuitive and efficient user experience, and I would be happy to discuss it further with you.

**Note: These are just figma designs please feel free to bring out your thoughts.**

#### Current Design:

![image](https://user-images.githubusercontent.com/52135949/226079873-6ab9b994-eaeb-4326-9394-c1c01c51f311.png)

#### Proposed Design:
![filter-2](https://user-images.githubusercontent.com/52135949/226080055-8a5f6943-83f3-472e-977f-234afd37d078.png)

**Comment by MAYANKpandey14** [comment]
Hey @SyedImam1998 the search bar you designed looks really good.
Can you try some variation for the tags, I think  making them less curved will do great. 
What do you think ?
Overall, great work and contribution to the community 💯

**Comment by SyedImam1998** [comment]
> Hey @SyedImam1998 the search bar you designed looks really good. Can you try some variation for the tags, I think making them less curved will do great. What do you think ? Overall, great work and contribution to the community 💯

Thanks for the feedback @MAYANKpandey14, 🤗
Sure I will take your input and let you know how things look.

**Comment by SyedImam1998** [comment]
Hey @MAYANKpandey14 

I have reduced the border-radius: 4px;

#### Design:

![filter-2-1](https://user-images.githubusercontent.com/52135949/226095068-8622f952-40c7-4030-b579-9624610a655a.png)

**Comment by psavan1655** [comment]
Also add the same border-radius to search bar as well. As all UI components should look same. It would feel good.

**Comment by sanskar1306** [comment]
I would like to work. Assign this to me.

**Comment by SyedImam1998** [comment]
> Also add the same border-radius to search bar as well. As all UI components should look same. It would feel good.

Hey, @psavan1655 Here is the updated search bar UI..

#### Design:
![filter-21](https://user-images.githubusercontent.com/52135949/226188821-af142b62-e07c-4870-a9dc-a77db30004b7.png)

**Comment by Vicolas11** [comment]
Assign it to me, please

**Comment by eddiejaoude** [comment]
Great collaboration everyone!

Things to keep in mind...
- We need to keep everything consistent on the site
- orange/white background/text fails accessibility - this is how we used to have it but changed it to be more accessible

**Comment by eddiejaoude** [comment]
This issue does not have the label `status: ready for dev` please do not ask for it to be assigned, it just creates more notifications for the maintainers

**Comment by SyedImam1998** [comment]
> Great collaboration everyone!
> 
> Things to keep in mind...
> 
> * We need to keep everything consistent on the site
> * orange/white background/text fails accessibility - this is how we used to have it but changed it to be more accessible

Hey, @eddiejaoude Thanks for the feedback i will try to change the colors. As the logo bunny(rabbit) color is orange so i went with that color. I apologize.  If you have any color combinations in mind, please help us here. But before that what do you feel about the numbers inside the box with text? 

[opensource (308)] design ?
