### ISSUE TITLE
[add icon] a linkedin icon can be added

### ISSUE THREAD

**Issue by abrahamalen** [EddieHubCommunity/LinkFree#554]
### Description

Instead of an arrow on **Follow me on Linkedin** adding an icon there will be better and aesthetically cool.

### Screenshots

![image](https://user-images.githubusercontent.com/53680255/138492053-3dee03ec-d934-4ddf-93bf-419cfb65cbfc.png)

### Additional information

for designers a Behance or dribble option adding will be good

**Comment by Panquesito7** [comment]
Closing as the LinkedIn icon is already there. 🙂
