### ISSUE TITLE
[FEATURE] Integrating mongodb atlas

### ISSUE THREAD

**Issue by abhijain2003** [EddieHubCommunity/LinkFree#5551]
### Description

currently the project is using Mongodb, but only installed version not mongodb web version which is mongodb atlas.

it would be better if we also integrate it. so people who are less experienced in mongodb might not find difficulty in making their first contribution.

as mongodb atlas is way easier to setup as compared to mongodb compass.

**Comment by eddiejaoude** [comment]
The project uses a mongo connection string, this can be used for local or remote mongo. Are you suggesting having docs for Atlas? Could you explain a bit more?

**Comment by abhijain2003** [comment]
the project use this url

mongodb://localhost:27017/linkfree

which only works if mongodb installed in same machine

while in order to connect mongodb atlas web which doesn't require you to install mongodb in machine needs a connection string to connect

would be better if we also provide functionality to this also

**Comment by eddiejaoude** [comment]
I think this is not an issue, I will close for now.
