### ISSUE TITLE
Suggestion for making website more user-friendly for non-techies.

### ISSUE THREAD

**Issue by immortalAbdul01** [EddieHubCommunity/LinkFree#5583]
### Description

I would like to suggest that we should make the website more user-friendly for non-techies who may also want to combine their links in one link. To achieve this, we should consider adding a Google sign-in option and allow users to add links and profiles from the UI itself.

This will make the website more accessible to a wider audience and help users who may not have technical knowledge to easily use the platform.

**Comment by eddiejaoude** [comment]
Thank you for the suggestion, but I will close because...

- We do already have GitHub sign in, we could extend this in the future
- There is already an existing issue for people to be able to manage their profile from the UI https://github.com/EddieHubCommunity/LinkFree/issues/5575
