### ISSUE TITLE
[DOCS] Add a link to the environment variable page in the local development section

### ISSUE THREAD

**Issue by ChinmayMhatre** [EddieHubCommunity/LinkFree#5613]
### Description

I think we should add a link since anyone who wants to setup in the local system would have to add the environment variables.

If the contributor tries to login in the local env and it doesn't work, It would be confusing since the setup steps don't mention the env variables.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51131670/227104390-1f750b2d-2862-4704-9875-3a4cd07d244d.png">

Link to the page : https://linkfree.eddiehub.io/docs/environments/local-development

**Comment by SohamRoy-01** [comment]
@ChinmayMhatre Yeah but on the third point on clicking into variables it redirect to a environmental variable where all the explanation is there

**Comment by ChinmayMhatre** [comment]
> @ChinmayMhatre Yeah but on the third point on clicking into variables it redirect to a environmental variable where all the explanation is there
> 

You are correct, I missed that. Weird🤔. Will close this issue since link is already present.
