### ISSUE TITLE
[FEATURE] limit zoom on map

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#5635]
### Description

When zooming out on the map view there is no limitation which creates an unpleasant visual that does not provide anything to the UX.  Recommending to limit the zoom out functionality to be inline with the map bounds. See the attached video to illustrate the behavior.

### Screenshots

https://user-images.githubusercontent.com/97615019/227570973-43a9897d-12d8-4323-b3ea-636c6cbc46f7.mov

**Comment by amandamartin-dev** [comment]
> can you assign me this issue?

Hello. This issue is awaiting triage, in the future please wait to ask to be assigned to an issue until after it has the status "ready for dev"

More details are available to help guide contributions in [the contribution guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md)

**Comment by eddiejaoude** [comment]
Thank you Amanda 👍 

@anikdhabal I have triaged the issue and assigned it to you
