### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by Bharadwajshivam28** [EddieHubCommunity/LinkFree#5639]
### Description

In the navigation bar, the logo of EddieHub doesn't respond. When one goes there it comes like a click but when we click it doesn't take anywhere if it is a logo then we can remove the sign when we go there.

When the cursor changes, it looks like there is some link where we click, we will be redirected but nothing happens.

If there is no link on the icon then we can remove the changing of cursor it looks like we have to click and redirect to another page and if there is any page linked to the icon then please drop it I will add so one when clicking and then go to that page.

### Screenshots

![Screenshot from 2023-03-24 23-10-41](https://user-images.githubusercontent.com/108119109/227601263-6c1dd8e1-f64a-4a1e-9f0c-b6c91e169af5.png)

**Comment by eddiejaoude** [comment]
Currently the logo goes to the homepage, if there is a bug please share more information about what page you were on when trying to click the logo (I suggest not cropping the screenshot so much so we can get context)

<img width="1669" alt="Screenshot 2023-03-25 at 07 39 56" src="https://user-images.githubusercontent.com/624760/227668532-fdc0a7a0-9149-4aa9-aefa-1eaa76e0c952.png">
