### ISSUE TITLE
Extra white space

### ISSUE THREAD

**Issue by Bharadwajshivam28** [EddieHubCommunity/LinkFree#5640]
### Description

There are extra spaces between some sections. It looks ugly when there is more space so we can remove those extra spaces. 

### Screenshots

![Screenshot from 2023-03-24 23-11-03](https://user-images.githubusercontent.com/108119109/227602015-4a3c1979-ceeb-4be3-80c5-362b0a381705.png)
![Screenshot from 2023-03-24 23-11-13](https://user-images.githubusercontent.com/108119109/227602024-92aefd96-061b-4790-916f-80f08fdf0210.png)

**Comment by eddiejaoude** [comment]
Thank you for the suggestion 👍 - I have updated the labels

> There are extra spaces between some sections. It looks ugly when there is more space so we can remove those extra spaces

Note: please make a bit of extra effort with your text, saying the current design is `ugly` you are insulting someone's hard work, it does not make your idea any better by making someone else feel bad.

**Comment by yoyoekta** [comment]
I have made some changes and I believe they align with the requirements of this issue. I have attached the image to this comment and would appreciate it if you could review it and provide feedback on whether or not it's a good fit. Please let me know if any revisions are needed or if you have any questions or concerns about the changes I have made. Thank you for your time and support in reviewing my changes.

![image](https://user-images.githubusercontent.com/92643605/227698798-4923072c-318a-487e-86e7-4f14e15b8ddf.png)

**Comment by eddiejaoude** [comment]
@yoyoekta would you like me to assign you the issue, you can then push your changes to a Pull Request (or draft if you prefer) it is easier to review and discuss

**Comment by Bharadwajshivam28** [comment]
> Thank you for the suggestion 👍 - I have updated the labels
> 
> > There are extra spaces between some sections. It looks ugly when there is more space so we can remove those extra spaces
> 
> Note: please make a bit of extra effort with your text, saying the current design is `ugly` you are insulting someone's hard work, it does not make your idea any better by making someone else feel bad.

Oh sorry should I make the changes and create the pr

**Comment by yoyoekta** [comment]
> @yoyoekta would you like me to assign you the issue, you can then push your changes to a Pull Request (or draft if you prefer) it is easier to review and discuss

Sure! Thank you!

**Comment by eddiejaoude** [comment]
> > Thank you for the suggestion 👍 - I have updated the labels
> > > There are extra spaces between some sections. It looks ugly when there is more space so we can remove those extra spaces
> > 
> > 
> > Note: please make a bit of extra effort with your text, saying the current design is `ugly` you are insulting someone's hard work, it does not make your idea any better by making someone else feel bad.
> 
> Oh sorry should I make the changes and create the pr

@Bharadwajshivam28 no, because it is now assigned to someone else, in the future please request if you wish to do the issue
