### ISSUE TITLE
Bio - Profile card in search page

### ISSUE THREAD

**Issue by KimberlyPangilinan** [EddieHubCommunity/LinkFree#5647]
### Description

When searching for a profile in the app, the profile card that appears in the search results typically includes a brief bio about the user. However, if the bio is lengthy or contains a large number of characters, it may create a spacing issue within the profile card just like mine. And I tried adding characters and I can see that exceeding chaarcters will be hidden. 

I think we can text truncate it  "..." for better user exp. Thank you

### Screenshots

![image](https://user-images.githubusercontent.com/92774426/227695911-51c4b16f-8002-44e0-9d89-fe569537780a.png)
![image](https://user-images.githubusercontent.com/92774426/227696066-b9d5bf21-1000-47af-b444-ce6815962e61.png)

**Comment by nishant-siddh** [comment]
Hey can u assign me to it

**Comment by Reedham20** [comment]
Hey @KimberlyPangilinan, should I work on this?

**Comment by Landouda** [comment]
hey, I would be glad to work on this @KimberlyPangilinan. Thanks.

**Comment by Srinja333** [comment]
Can I work on this?

**Comment by getlost01** [comment]
hey  @KimberlyPangilinan , I saw this thing is already implemented here in the profile card.

# Screenshot of profile card
<img width="233" src="https://user-images.githubusercontent.com/79409258/227758581-b9d2bb71-304b-4eb2-9ce7-d974a26b48b9.png">
# For the larger bio section
<img width="338" src="https://user-images.githubusercontent.com/79409258/227758598-8b8bfdca-823b-476b-8a07-24d457792843.png">

**Comment by 01vishu** [comment]
Hey, i think i can help out with this can you assign this issue to me?

**Comment by sanskar1306** [comment]
I can fix this. Assign this to me.

**Comment by FrozenHearth** [comment]
Hi @KimberlyPangilinan  I have already implemented this for the profile cards in search page. Refer https://github.com/EddieHubCommunity/LinkFree/pull/3798

Using tailwind's line clamp plugin.

**Comment by eddiejaoude** [comment]
Great collaboration everyone 👍 looks like it has been implemented, but if there are further improvements please raise a new issue
