### ISSUE TITLE
[FEATURE] Imports to have an index file

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#5654]
### Description

We now have aliases for imports, for example...

```js
import ModelA from "@models/..."
import ModelB from "@models/..."
import ModelC from "@models/..."
```

but we need to have a line for each imported model file.

It would be cleaner to have an `index.js` file in each alias import folder, so we can do...

```js
import { ModelA, ModelB, ModelC } from "@models/..."
```

**Comment by Bharadwajshivam28** [comment]
@eddiejaoude Sir can i work on this issue?

**Comment by eddiejaoude** [comment]
Sure, I have assigned it to you

**Comment by Bharadwajshivam28** [comment]
> Sure, I have assigned it to you

Thanks sir

**Comment by Bharadwajshivam28** [comment]
> Sure, I have assigned it to you

If you can then please elaborate this issue sir

**Comment by Akhilbisht798** [comment]
I think we need to add a `index.js` file in the model directory from where we can get all the models from just using that index.js file and not using import statement for all the models.
I don't known completely i am making assumption here but importing all models to the index.js file and than exporting them all can do the job.
Again i am not sure about it so i have check first.

**Comment by Akhilbisht798** [comment]
Hey are we looking for something like this?
`import {Profile, ProfileStats, Link, LinkStats} from "@models/index";`

**Comment by eddiejaoude** [comment]
Sure @Bharadwajshivam28, I will update the issue description (please note it is better to ask these questions before asking to have the issue assigned to you)

@Akhilbisht798 you are correct, thank you 💯

**Comment by MahendraBishnoi29** [comment]
@Bharadwajshivam28 if you find this difficult then I would love to work on this please let me know :)

**Comment by Bharadwajshivam28** [comment]
> Sure @Bharadwajshivam28, I will update the issue description (please note it is better to ask these questions before asking to have the issue assigned to you)
> 
> @Akhilbisht798 you are correct, thank you 💯 

Okay sir thanks 👍

**Comment by Bharadwajshivam28** [comment]
> Sure @Bharadwajshivam28, I will update the issue description (please note it is better to ask these questions before asking to have the issue assigned to you)
> 
> @Akhilbisht798 you are correct, thank you 💯 

I will work on this now sir please thanks for suggesting

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 if you find this difficult then I would love to work on this please let me know :)
Let me give it. A try 🙂

**Comment by khanahmar** [comment]
is this issue open yet

**Comment by MahendraBishnoi29** [comment]
> > @Bharadwajshivam28 if you find this difficult then I would love to work on this please let me know :)
> > Let me give it. A try 🙂

any update @Bharadwajshivam28

**Comment by eddiejaoude** [comment]
> is this issue open yet

@khanahmar yes this issue is open and ready for dev as you can see by the labels, but it is already assigned

> any update @Bharadwajshivam28

@MahendraBishnoi29 please be patient is has only been a few days, people have work/school etc

After 2 weeks if there is no progress we can look to re-assign the issue

**Comment by MahendraBishnoi29** [comment]
> 

alright 👍🏻

**Comment by SaraJaoude** [comment]
Due to lack of activity I will be unassigning this Issue.

**Comment by Shaikh-Danish** [comment]
I would like to work on this issue, please assign the issue to me @SaraJaoude

**Comment by akash19coder** [comment]
@eddiejaoude Is it the case that we need to create a new file called `index.js` in the `models` folder where we import all the schemas and export them at the same time?
![Screenshot (4)](https://user-images.githubusercontent.com/72060440/231872435-3050401a-493c-453d-a9bb-772fa5dfb931.png)

**Comment by SaraJaoude** [comment]
> I would like to work on this issue, please assign the issue to me @SaraJaoude

I will assign it to you

**Comment by shobhitexe** [comment]
Hey is this issue still open if yes then plz assign it to me i'd love to work on this Thanks

**Comment by SaraJaoude** [comment]
PR merged.
