### ISSUE TITLE
Inconsistency between filteredUsers and sum of count shown on selected tags

### ISSUE THREAD

**Issue by jenishVadodaria** [EddieHubCommunity/LinkFree#5710]
### Description

When selecting a tag for search bar, the filteredUsers does not match the total count shown on the tags.

### Screenshots

![Screenshot (143)](https://user-images.githubusercontent.com/62771159/228649642-77116174-d051-4ca1-a387-5e447e05ef10.png)

**Comment by Deva-1903** [comment]
Can I work on this issue?

**Comment by jenishVadodaria** [comment]
@eddiejaoude, can you review the issue? I think we need to refactor the filterData function.

**Comment by amandamartin-dev** [comment]
Potentially related issue #5470

**Comment by eddiejaoude** [comment]
Good spot Amanda 👍 

Thank you for raising @jenishVadodaria but it is a duplicate of #5470 so I will close
