### ISSUE TITLE
[FEATURE] User changelog entry for Profile progress

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#5716]
### Description

Now we have a profile progress, we should let the users now about it in the user changelog page
https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/changelog.js

<img width="1668" alt="Screenshot 2023-03-30 at 13 04 04" src="https://user-images.githubusercontent.com/624760/228757608-faa6edd4-d73a-4beb-956b-158ceef58938.png">

**Comment by ApurvaBasule** [comment]
@eddiejaoude can i take this issue?
