### ISSUE TITLE
Algin footer elements in the same row

### ISSUE THREAD

**Issue by Deva-1903** [EddieHubCommunity/LinkFree#5735]
### Description

If we could align the elements in the footer namely **powered by eddiehub** and **help**. If we could place them on a single row it will look nice and clean. 

### Screenshots

![Screenshot (295)](https://user-images.githubusercontent.com/97371915/229024187-19401594-8fdc-40b9-a825-ae990fd69b15.png)

**Comment by Deva-1903** [comment]
If maintainers find this as a potential issue, I could work on this.

**Comment by eddiejaoude** [comment]
Thank you @Deva-1903 for the suggestion. However I do not think this is possible because the `help` item is static and the `powered by EddieHub` moves as the page scrolls - so I will close for now but please correct me if I am wrong
