### ISSUE TITLE
Changed line sequence of type, sizes in  manifest.json for consistency.

### ISSUE THREAD

**Issue by its-kunal** [EddieHubCommunity/LinkFree#5751]
### What would you like to share?

![image](https://user-images.githubusercontent.com/92196937/229136914-85ff877c-72d4-4670-bc9b-da896a74dbab.png)
Before and after.

**Comment by tarunclub** [comment]
Hey, I can help you out with this issue can you assign this to me?

**Comment by eddiejaoude** [comment]
Please do not work on issues or request to be assigned issues that do not have the label `status: ready for dev` 

You can read more about the best practices in our contributing guide, any questions you can ask in EddieHub Discord https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md
