### ISSUE TITLE
[FEATURE] Add test for map page to populate location information on local environment

### ISSUE THREAD

**Issue by weilincheng** [EddieHubCommunity/LinkFree#5767]
### Description

In the current implementation, user location information in MongoDB is only updated when a user visits their profile page. As a result, when running the project in local development mode, no user has location data in the database, preventing user markers from appearing on the map page. Currently, developers must manually visit multiple user profiles to populate the database with location information.

To improve the development experience, we have discussed this situation in issue #5473, which will add an explanation to the [Map Information Doc](https://linkfree.io/docs/map). @naomi-lgbt suggested adding a seed script that can populate the database with mock user location data. Running this script locally would make it easier to test the map functionality without having to visit multiple user profiles.

I suggest adding the seed script to the `services/profiles` directory and naming it `seedLocationData.js`. This script could generate random location data for a specified number of users and insert it into the database. We can then add the usage instructions to the [Map Information Doc](https://linkfree.io/docs/map).

I believe that this feature would be beneficial for both experienced and beginner developers, and I look forward to your feedback.

**Comment by joeshajan** [comment]
Yes, @weilincheng I agree with you. I face this same issue all the time. This feature will help developers a lot.

**Comment by eddiejaoude** [comment]
I don't think a seed script is needed. Another solution which is also good practice is if they run the automated tests, some profiles will be visited and this will also populate the database with a location

**Comment by weilincheng** [comment]
> I don't think a seed script is needed. Another solution which is also good practice is if they run the automated tests, some profiles will be visited and this will also populate the database with a location

Hi Eddie, thank you for your comment. That's a great point about using the automated tests to populate the database with location data. I’ll give it a try and see how it works.

**Comment by eddiejaoude** [comment]
Great, thanks 👍

**Comment by eddiejaoude** [comment]
I have assigned this to you @weilincheng as we have been discussing it in the docs PR about write a test file to visit some profile pages https://github.com/EddieHubCommunity/LinkFree/pull/5766

Let me know if that is ok, or if you prefer me to unassigned it

**Comment by weilincheng** [comment]
> I have assigned this to you @weilincheng as we have been discussing it in the docs PR about write a test file to visit some profile pages #5766
> 
> Let me know if that is ok, or if you prefer me to unassigned it

Thank you for assigning this issue to me, Eddie. I appreciate it. As we have been discussing this issue in #5766, I will work on it and keep you updated. Thank you again for your support.

**Comment by naomi-lgbt** [comment]
> Another solution which is also good practice is if they run the automated tests, some profiles will be visited and this will also populate the database with a location

This suggests that our tests aren't encapsulated. A test suite, IMHO, should not leave a database polluted.

**Comment by weilincheng** [comment]
> > Another solution which is also good practice is if they run the automated tests, some profiles will be visited and this will also populate the database with a location
> 
> This suggests that our tests aren't encapsulated. A test suite, IMHO, should not leave a database polluted.

Hi Naomi. I agree with your concern about test encapsulation and the importance of not leaving the database polluted. Maybe we can address it by using a separate database for testing to prevent any potential pollution of the production database. Let me know if you have any suggestions or best practices you'd like to share, and we can discuss them further to improve our test suite. 😃

**Comment by eddiejaoude** [comment]
No one has access to the production database (even me), so there is a low risk of it affecting production.

I think as the direction of this issue has changed, can the title be updated @weilincheng ? thanks

**Comment by weilincheng** [comment]
> I think as the direction of this issue has changed, can the title be updated @weilincheng ? thanks

Thank you for pointing that out. I've updated the issue title accordingly. Please let me know if there are any further improvements or suggestions.
