### ISSUE TITLE
[DOCS] Statistics screenshot added to features on homepage

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#5771]
### Description

![Screenshot 2023-04-01 at 21 39 53](https://user-images.githubusercontent.com/624760/229295853-ddafba87-7feb-4562-9867-4346871dd25a.png)

**Comment by Blaize15** [comment]
It's good to Showcase `Account Statistics` feature on the `Homepage` . Should we put in last? If not then what sequence number from top?

**Comment by eddiejaoude** [comment]
I think it should go after the links

**Comment by Blaize15** [comment]
Alright, Eddie! I'm on my way 🚀

**Comment by eddiejaoude** [comment]
ok, let me assign the issue to you @Blaize15 to avoid any confusion
