### ISSUE TITLE
[OTHER] Playwright automated tests for authenticated pages

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#5788]
### What would you like to share?

Playwright has an example of authenticated tests, to be able to test pages that require authentication

- [ ] Logged in, can reach Account page and check title
- [ ] Not logged in, trying to navigate to Account page, but redirected

Here are the Playwright docs https://playwright.dev/docs/auth but we don't want to use a real username and password, we want to mock those out, this blog might help https://dev.to/kuroski/writing-integration-tests-for-nextjs-next-auth-prisma-using-playwright-and-msw-388m

### Additional information

Plan B: We could during testing switch to credential login and create a fake user in the DB

**Comment by Vishrut19** [comment]
Hey! No issue is assigned to me right now. So, can I try to work on this issue? If that's okay

**Comment by eddiejaoude** [comment]
Sure, thanks Vishrut 👍

**Comment by amandamartin-dev** [comment]
@eddiejaoude asking a potentially silly question here. Why not use a GitHub login stored in dot env so as to not expose the credentials versus standing up a separate server to try to intercept calls for the one test like in the blog example? Is this less secure or is there another reason I'm missing?

**Comment by eddiejaoude** [comment]
> @eddiejaoude asking a potentially silly question here. Why not use a GitHub login stored in dot env so as to not expose the credentials versus standing up a separate server to try to intercept calls for the one test like in the blog example? Is this less secure or is there another reason I'm missing?

There are no silly questions Amanda. If we need to use anything private like a "real" login (which I hope we don't need to) then yep we should store it in the `.env` file. TBH I didn't go through the blog, just had a very quick glance, so I am open to suggestions. 

I am happy to bounce ideas on a call if easier, as I know this is a challenging ticket, just let me know in Discord.
