### ISSUE TITLE
Add a visual effect on hover

### ISSUE THREAD

**Issue by Palakkgoyal** [EddieHubCommunity/LinkFree#5812]
### Description

On the events page, there are certain events mentioned. But the whole event box is not clickable and only the title of the box is such as `API Days Patna` in the screenshot. So, can we add a simple underline below the title. So, it will enhance the UX.
![Screenshot (481)](https://user-images.githubusercontent.com/116902573/229454158-175b1bd9-5db7-456f-a875-f325707c7e65.png)

**Comment by dheerajmw** [comment]
I am writing to express my interest in contributing to your project on [LinkFree]. After reviewing the project requirements and objectives, I believe that I can add value to your team and help drive the project to success.

I have experience working with relevant technology or tools], and I am excited to apply my skills to this project. Additionally, I am highly motivated to collaborate with your team and contribute to the open-source community.

**Comment by RutamBhagat** [comment]
@Palakkgoyal can i work on this issue it will be an easy fix

**Comment by Palakkgoyal** [comment]
Hey @RutamBhagat and @dheerajmw, I am also a learner like you and I have just created this issue. Cause I felt it is missing. But it need to get the request from the maintainers of this project that whether anyone can work on this or not. I created this issue because I was not able to find issue that is free(I mean on which I can work and no other person is working). Like this you can also go to LinkFree and see if you think if there is any change required. If there, then create a new issue and work on that. This thing seems pretty easy to me then to search for an issue that is available. 
What do you think?

**Comment by eddiejaoude** [comment]
We have a component for links that would help with this 👍

**Comment by Vishrut19** [comment]
Hey! I can work on this issue. Can you please assign me?

**Comment by eddiejaoude** [comment]
@Vishrut19 other people have requested the issue before you, also you have requested on another issue, please do not request more than 1 issue at a time as it creates more work/confusion for the maintainers

**Comment by eddiejaoude** [comment]
@RutamBhagat I have assigned this issue to you

**Comment by RutamBhagat** [comment]
@eddiejaoude just needed to confirm one thing. The underline should only appear on mouse hover right?
![Screenshot from 2023-04-04 16-44-06](https://user-images.githubusercontent.com/72187009/229775180-09d0b1f0-188c-42b9-af42-36fc8523143a.png)
Like this?
And shouldn't be static like this
![Screenshot from 2023-04-04 16-34-59](https://user-images.githubusercontent.com/72187009/229775348-c5e779fc-da4e-4b22-a19b-a91ca7d612bf.png)

**Comment by eddiejaoude** [comment]
yes on mouse hover, the `Link` component should do this already for you

**Comment by RutamBhagat** [comment]
@eddiejaoude #5836 fixes this issue, please review and merge the pull request

**Comment by eddiejaoude** [comment]
Closing in favour of another solution https://github.com/EddieHubCommunity/LinkFree/issues/5870
