### ISSUE TITLE
Ui fixex in Community Events oae

### ISSUE THREAD

**Issue by hussnainjav3d** [EddieHubCommunity/LinkFree#5817]
### Description

As u see in this SS text color for badge should be white and also border radius for top should b handle as it looks weird 
should i work in this task ??

### Screenshots

![image](https://user-images.githubusercontent.com/55350630/229490428-bfb9b30a-4067-4e39-bfd6-06b4bd04c668.png)

**Comment by eddiejaoude** [comment]
Please can you explain what you mean, I do not understand the changes you are suggesting

**Comment by eddiejaoude** [comment]
Not clear on the suggested changes
