### ISSUE TITLE
[OTHER] Digital Ocean Database backup

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#5819]
### What would you like to share?

Is there some docs on how to do this for Digital Ocean hosted database?

**Comment by dan-mba** [comment]
[MongoDB Backup & Restore](https://www.digitalocean.com/community/tutorials/how-to-back-up-restore-and-migrate-a-mongodb-database-on-ubuntu-20-04)
[mongodump](https://www.mongodb.com/docs/database-tools/mongodump/)

**Comment by eddiejaoude** [comment]
Thank you 👍

**Comment by MAYANKpandey14** [comment]
Hey, according to my understanding is this issue raised to backup the database to Digital Ocean.
Correct me, If I am wrong.

**Comment by eddiejaoude** [comment]
@MAYANKpandey14 we need to backup the managed MongoDB, this might be an option we can select on DigitalOcean and/or we can do it manually - this is currently to discuss options and ideas (I am keen to keep things simple)

**Comment by MAYANKpandey14** [comment]
Ok got it

**Comment by amandamartin-dev** [comment]
closing as no longer needed
