### ISSUE TITLE
[FIRST CONTRIBUTOR] Sign in with Github Button UI idea

### ISSUE THREAD

**Issue by Eclipse175** [EddieHubCommunity/LinkFree#5849]
### Description

Personally I think it looks a little off, the colors look nice but the border-radius can be made a little better and the button itself can be centered as well (which currently its not) and some simple hover animation would also look good, i can try work on this issue as well.

### Screenshots

![image](https://user-images.githubusercontent.com/94952857/229952015-8a820da6-5b2f-48b3-a2ce-5c79791ca52d.png)

**Comment by Vishrut19** [comment]
I think the button's shadow didn't work out pretty well! So I guess changing the button's shadow or switching to light colors for button shadow would help.

**Comment by Eclipse175** [comment]
hmmm, for a darker theme like that, you think it'd make sense to add a white shadow?

**Comment by Tommymarvel** [comment]
> hmmm, for a darker theme like that, you think it'd make sense to add a white shadow?

Obviously not, i think the size of the shadow is too big

**Comment by Eclipse175** [comment]
thats a shadow you mean? it looks like a background in itself

**Comment by eddiejaoude** [comment]
Thank you for raising, this is a duplicate (although it was raised first, but the other issue has more discussion and examples), so I will close this https://github.com/EddieHubCommunity/LinkFree/issues/5856
