### ISSUE TITLE
[FEATURE] Improve login page design

### ISSUE THREAD

**Issue by NiazMorshed2007** [EddieHubCommunity/LinkFree#5856]
### Description

Current login page design is not so descriptive, it's just a button there. Maybe add some texts and a logo to present it better. I've created a demo design in my local system. If it passes let me know, I would like to work on this 🙂

Screenshots below 👇

### Current version: 
![image](https://user-images.githubusercontent.com/77217706/230000085-d2906a29-421d-485c-86c8-dc31e1a28995.png)

### Proposed version:
![image](https://user-images.githubusercontent.com/77217706/230000213-2236a4c2-39b3-4a3c-a89d-33c1e7ec0e96.png)

**Comment by bharathkalyans** [comment]
The proposed version looks good compared to the normal page.

**Comment by harshitXdesign** [comment]
1. Incorporated the logo onto the sign-up page for improved brand recognition and trust-building.
2. Added a clear copy to inform users about the service's value proposition: "Hassle-free connectivity with a single link."
3. Included a subheading that makes the sign-up process more actionable and prompts users to take action: "Join now."
4. Redesigned the button to be more visually prominent and communicate its primary CTA status to users.
5. Overall, the updates were made with the user experience in mind, improving the page's usability and overall effectiveness.

![Join now](https://user-images.githubusercontent.com/130032317/230287156-7bb30091-1725-4195-9242-fd2ca85f70f8.png)

**Comment by NiazMorshed2007** [comment]
> 1. Incorporated the logo onto the sign-up page for improved brand recognition and trust-building.
> 2. Added a clear copy to inform users about the service's value proposition: "Hassle-free connectivity with a single link."
> 3. Included a subheading that makes the sign-up process more actionable and prompts users to take action: "Join now."
> 4. Redesigned the button to be more visually prominent and communicate its primary CTA status to users.
> 5. Overall, the updates were made with the user experience in mind, improving the page's usability and overall effectiveness.
>    @rakesh-gupta29 will be able to integrate into development.
>    ![Join now](https://user-images.githubusercontent.com/130032317/230287156-7bb30091-1725-4195-9242-fd2ca85f70f8.png)

Design looks great!

**Comment by Eclipse175** [comment]
LOOK AWESOME!

**Comment by eddiejaoude** [comment]
Great collaboration and designs everyone! I think here are the docs to customising the default `next-auth` login page https://next-auth.js.org/configuration/pages#oauth-sign-in

> LOOK AWESOME! can i work on this with somebody if the project is in react?

@Eclipse175 thank you for your enthusiasm however it is better to research the project first and make your own decisions fro that

**Comment by sansarmaske** [comment]
I would like to work on this.

**Comment by ajaxbo360** [comment]
Hi, i would like to work on this

**Comment by eddiejaoude** [comment]
@NiazMorshed2007 as you created the issue and requested it first, let me know if you would like this issue or if I should assign it to someone else

Please note my previous comment about Tailwind prebuilt components

**Comment by Eclipse175** [comment]
@NiazMorshed2007 hey bro can i have your discord? i just want to talk about it if you'd like

**Comment by eddiejaoude** [comment]
> @NiazMorshed2007 hey bro can i have your discord? i just want to talk about it if you'd like

@Eclipse175 best to discuss in public in the EddieHub Discord - so others can learn and join in

**Comment by NiazMorshed2007** [comment]
@Eclipse175 yep,, let's hangout on EddieHub discord
