### ISSUE TITLE
[DOCS] userStatus/speakingTopic missing from events guide

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#5858]
### Description

There are a few optional fields missing from the events docs here https://linkfree.eddiehub.io/docs/how-to-guides/events

"userStatus": "speaking",
"speakingTopic": "Open Source",

This issue is to add these items to the example as optional parameters with an explanation of what data should be stored there.
![events with missing fields](https://user-images.githubusercontent.com/97615019/230087179-00b845ec-8745-4f95-9b78-9236f1b289c8.jpg)

**Comment by parth-ranalkar** [comment]
Hey I would like to contribute to this issue. @amandamartin-dev

**Comment by amandamartin-dev** [comment]
> Hey I would like to contribute to this issue. @amandamartin-dev

This issue is "awaiting triage" please do not ask to be assigned unless you see the status "ready for dev". We appreciate your interest and enthusiasm, but please follow the guide to. help keep confusion down and decrease the work for maintainers.

See the contributing guide for more information: https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by Darshanjaji** [comment]
Assign to me, If no one working on this project

**Comment by eddiejaoude** [comment]
Oh good spot Amanda on the missing docs 👍

**Comment by wrmacdonald** [comment]
I'd love to be assigned this!

**Comment by eddiejaoude** [comment]
Sure @wrmacdonald I have assigned it to you
