### ISSUE TITLE
[BUG] Duplication in map popup

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#5867]
### Description

There is a duplicate span in the map component which is displaying user.bio twice.  This should be removed
![popup-duplication](https://user-images.githubusercontent.com/97615019/230246088-a856ae8c-f295-4e1a-ae50-75bc93ac24b5.PNG)

**Comment by ashutosh887** [comment]
Please assign me this issue @amandamartin-dev @eddiejaoude

**Comment by eddiejaoude** [comment]
@ashutosh887 thank you for being keen to contribute to the project, but please do not spam and request multiple issues at once to be assigned to you, this creates more noise, notifications and confusion within the community. If you are unsure please read our contributing guidelines here https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

I have assigned this issue to you, but I will not be assigning the other issues you requested, as we only assign 1 open issue at a time to each person

**Comment by ashutosh887** [comment]
Sure I'll keep this in mind @eddiejaoude Sir
Thanks for considering

**Comment by rajaditya06** [comment]
hai @ashutosh887  are u working on it ?

**Comment by ashutosh887** [comment]
Yes @rajaditya06  Thanks

**Comment by Ashish-1016** [comment]
@eddiejaoude Can I get assigned to resolve this issue?. Like its my first time contributing so can I gain some open-source contribution by resolving my first issue.

**Comment by amandamartin-dev** [comment]
> @amandamartin-dev Its my first time contributing, if I am wrong please give me some positive feedback.

Hello! You are correct about what is causing the issue, but it is currently assigned to someone else who has confirmed recently they are working on it.  We are happy for your enthusiasm, but please make sure to check and see if an issue is assigned before asking to work on it.

**Comment by nithin999989** [comment]
please assign this to me i will surely correct this

**Comment by SaraJaoude** [comment]
> please assign this to me i will surely correct this

@nithin999989 please refer to the conversation above - this issue has already been assigned.

**Comment by ChinmayMhatre** [comment]
@ashutosh887 do you need any help with this issue? Don't wanna rush you incase you are busy just wanted to ping you incase you want help with this issue.

**Comment by amandamartin-dev** [comment]
> Yes @rajaditya06 Thanks

Hello! It has been 3 weeks, please let up know if you are working on this and need more time otherwise I would like to open this up to others

**Comment by ashutosh887** [comment]
Yes @amandamartin-dev 
Wrapping this up soon!

**Comment by amandamartin-dev** [comment]
> Yes @amandamartin-dev Wrapping this up soon!

Awesome! Thank you for the update

**Comment by ashutosh887** [comment]
Thanks @eddiejaoude
