### ISSUE TITLE
[BUG] Speaker details on mobile without avatar

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#5869]
### Description

The user avatar does not display on the event, but the speaker details do.  If the avatar cannot fit on mobile, the speaker details should be hidden on mobile.

![mobile-event-speaker-details](https://user-images.githubusercontent.com/97615019/230247680-56ad3b6a-bee8-4e95-997a-a26dd2c89595.PNG)

**Comment by ashutosh887** [comment]
I would like to work on this @amandamartin-dev @eddiejaoude

**Comment by eddiejaoude** [comment]
This issue cannot be assigned to you @ashutosh887 as it has not been triaged and is not ready for dev. As per our contributing [guidelines](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) you can only be assigned 1 open issue at a time that has the label `status: ready for dev` and I have just assigned another issue to you.

**Comment by ashutosh887** [comment]
Thanks a lot @eddiejaoude Sir
I'll start working on that issue

**Comment by Shaikh-Danish** [comment]
Hey, @amandamartin-dev I would like to work on this issue.

**Comment by Shaikh-Danish** [comment]
Hi, @amandamartin-dev I would like to work on this issue when the status changes.

**Comment by eddiejaoude** [comment]
@Shaikh-Danish I have assigned the issue to you now it has been triaged (but in future please do not ask to be assigned **before** it has the label `status: ready for dev` as it creates more notifications and confusion), if you are unsure lease ready out contenting guidelines https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by Shaikh-Danish** [comment]
Thanks, I'll work on this.

**Comment by Djaberkaci** [comment]
Hi there,
I would like to contribute to this issue.
