### ISSUE TITLE
[FEATURE] Home Page Improvement

### ISSUE THREAD

**Issue by vedprakashnautiyal** [EddieHubCommunity/LinkFree#5881]
### Description

I think it would be better to introduce a slider for the feature section in the home page, rather than a long page like structure......

### Screenshots

<img width="1680" alt="Screenshot 2023-04-06 at 6 47 47 PM" src="https://user-images.githubusercontent.com/71223796/230390177-2c99e733-b44a-4929-a6ac-84a22fc5f2fd.png">
 

I am talking about the above section of the page........

What do you think...??!!

**Comment by eddiejaoude** [comment]
Thank you for the suggestion. But personally I don't like sliders because it is difficult to get a glance as to what is going on. 

Also all images would need to be the exact same size which is not the case for our images here

**Comment by vedprakashnautiyal** [comment]
Fair enough....Thank you for your time.....
