### ISSUE TITLE
DarkMode Issue on preview of JSON on playground

### ISSUE THREAD

**Issue by Chandraprakash-Darji** [EddieHubCommunity/LinkFree#5911]
### Description

When we visit the playground page <https://linkfree.eddiehub.io/playground> and add the json if we try to preview it the text is not readable in dark mode. 

Modal is not following the dark mode styles.

> I would love to contribute to it, Anyone please assign me

### Screenshots

![Screenshot 2023-04-08 at 11 16 35 AM](https://user-images.githubusercontent.com/93640141/230705641-cd8300a7-3a2f-492d-b6d0-c78b2546fe57.png)

**Comment by eddiejaoude** [comment]
I have assigned it to you @Chandraprakash-Darji - please check the component as I thought it was using the same component as the actual page

**Comment by Chandraprakash-Darji** [comment]
I am not it, Thanks @eddiejaoude

**Comment by anupamthe99** [comment]
Hey, is this issue still open, and has anyone been working on it? I am happy to help with this issue.

**Comment by Chandraprakash-Darji** [comment]
I am working on it

**Comment by Chandraprakash-Darji** [comment]
I am working on it, creating PR in 2 hour

**Comment by Chandraprakash-Darji** [comment]
@anupamthe99 you can work on it, I got busy with something

**Comment by anupamthe99** [comment]
sure , i will be happy to work on it @Chandraprakash-Darji

**Comment by SaraJaoude** [comment]
> @anupamthe99 you can work on it, I got busy with something

@Chandraprakash-Darji if you can no longer work on an Issue please ask to be unassigned first rather than allocating this to someone else.

**Comment by SaraJaoude** [comment]
> sure , i will be happy to work on it @Chandraprakash-Darji

@anupamthe99 I will unassign this from @Chandraprakash-Darji and assign this to you
