### ISSUE TITLE
[DOCS] link color is camouflage with background in docs

### ISSUE THREAD

**Issue by Chandraprakash-Darji** [EddieHubCommunity/LinkFree#5922]
### Description

Link color is camouflage with background 

Visit: https://linkfree.io/docs/environments/environment-variables and scroll down to bottom

I am able to see because is selected.
![Screenshot 2023-04-08 at 2 34 11 PM](https://user-images.githubusercontent.com/93640141/230713307-9e2ca513-4440-4c74-83fd-1f09bfa17509.png)

If not selected: 
![Screenshot 2023-04-08 at 2 36 36 PM](https://user-images.githubusercontent.com/93640141/230713363-34b6e610-b3cf-401f-8cef-1c5b019901a1.png)

![Screenshot 2023-04-08 at 2 37 08 PM](https://user-images.githubusercontent.com/93640141/230713391-c49a9480-a00b-411d-82c2-a1f585dff876.png)

**Comment by Soyeb01** [comment]
Same issue here .
Visit: https://linkfree.io/docs/community-resources

![image](https://user-images.githubusercontent.com/98175646/230717167-da6d6c00-d4d0-4316-b7f0-033e2eeccf50.png)

**Comment by eddiejaoude** [comment]
Oh great spot 👍 thank you both

**Comment by eddiejaoude** [comment]
I think we need to create custom components for the mdx markdown->html to allow for dark mode, here are the official docs to do it https://nextjs.org/docs/advanced-features/using-mdx#custom-elements

**Comment by ajaxbo360** [comment]
Hi @Chandraprakash-Darji, I'd like to take on this if it's possible. Thank you.

**Comment by ChinmayMhatre** [comment]
block quotes bugs #5926

**Comment by karthiknadar1204** [comment]
If this issue is still open,please assign it to me

**Comment by ChinmayMhatre** [comment]
Hey @ajaxbo360 , @karthiknadar1204 apologies for not responding earlier, these bugs are from the PR I merged last week. I think it would be best if I close them in this considering the priority. Please feel free to take other new issues. Thank you for understanding!

**Comment by eddiejaoude** [comment]
Thank everyone for collaborating! I have assigned to @ChinmayMhatre as they have done all the work on this already before

**Comment by eddiejaoude** [comment]
Fixed https://github.com/EddieHubCommunity/LinkFree/pull/6000
