### ISSUE TITLE
[FEATURE] order milestones descending

### ISSUE THREAD

**Issue by Sammeeey** [EddieHubCommunity/LinkFree#5945]
Please only make changes after PR https://github.com/EddieHubCommunity/LinkFree/pull/5765 has been merged (or branch from this PR to make the changes)

### Description

I'd order the milestones in descending order (as suggested in Twitter DM chat with @eddiejaoude on April 8, 2023.

note: Sort by date desc

### Screenshots

![milestones_linkfree](https://user-images.githubusercontent.com/49591562/230766662-d86aa631-7520-461b-af84-54699e7b9589.jpg)

**Comment by Marco1314** [comment]
Hi Sammeeey,

You want the milestones sorted by date I assume?
Best regards
Marco

**Comment by pratham-yuxo** [comment]
@Sammeeey can you assign me this issue?

**Comment by Macky151203** [comment]
HI, can i work on this issue, I think i can fix this

**Comment by eddiejaoude** [comment]
Thank you @Sammeeey 👍 

@pratham-yuxo @Macky151203 please do not request to be assigned issues that have not been triaged yet and have the label `status: ready for dev`, please read the contributing guidelines to avoid any confusion https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by YOKESHCR** [comment]
Hey hi @eddiejaoude Is this issue open to work and resolve now?

**Comment by Vedant-Manjrekar** [comment]
> https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

Please don't tag maintainers, while asking to work on the issue. Kindly refer https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md for more info on the do's and don'ts to contribute to this project.

**Comment by SaraJaoude** [comment]
> > Hey hi @eddiejaoude Is this issue open to work and resolve now?
> 
> Please don't tag maintainers, while asking to work on the issue. Kindly refer https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md for more info regarding the do's and don'ts to contribute to this project.

Thank you for linking the Contributing Guide - this is something @Vedant-Manjrekar that you also need to be aware of yourself, as the Issue has not been assigned to you but you have created a Pull Request.  This causes confusion for other contributors and difficulty for the maintainers to manage the project (as well as potential for the time and work that you have done not to be used).

**Comment by SaraJaoude** [comment]
> I would like to be assigned this issue.

@sanskar1306 do you still want this issue? If not I will assign this to @Vedant-Manjrekar

**Comment by Vedant-Manjrekar** [comment]
> > > Hey hi @eddiejaoude Is this issue open to work and resolve now?
> > 
> > 
> > Please don't tag maintainers, while asking to work on the issue. Kindly refer https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md for more info regarding the do's and don'ts to contribute to this project.
> 
> Thank you for linking the Contributing Guide - this is something @Vedant-Manjrekar that you also need to be aware of yourself, as the Issue has not been assigned to you but you have created a Pull Request. This causes confusion for other contributors and difficulty for the maintainers to manage the project (as well as potential for the time and work that you have done not to be used).

Sorry my bad, will be more careful next time onwards.

**Comment by pratham-yuxo** [comment]
Currently this issue is assigned to no one. So, can I work on this issue?

**Comment by sanskar1306** [comment]
> > I would like to be assigned this issue.
> 
> @sanskar1306 do you still want this issue? If not I will assign this to @Vedant-Manjrekar

Yes I wish to work on it.

**Comment by SaraJaoude** [comment]
> > @sanskar1306 do you still want this issue? If not I will assign this to @Vedant-Manjrekar
> 
> Yes I wish to work on it.

I will assign it to you

**Comment by sanskar1306** [comment]
Thanks i m working on it.

**Comment by sanskar1306** [comment]
Hey i am unable to login, I am using gitpod and it shows unable to connect to localhost. I need to preview the changes I have done.

**Comment by eddiejaoude** [comment]
> Hey i am unable to login, I am using gitpod and it shows unable to connect to localhost. I need to preview the changes I have done.

this is a public page, you don't need to setup OAuth to view this page

**Comment by AJcodes42** [comment]
I would like to take this up if it is still open.

**Comment by eddiejaoude** [comment]
Sure @AJcodes42 I can assign it to you. But please be aware that today/tomorrow we will be merging the PR https://github.com/EddieHubCommunity/LinkFree/pull/5765 that changes the app to load the data from the database, so this might change the way the implementation is done

**Comment by AJcodes42** [comment]
Sure will work on this once https://github.com/EddieHubCommunity/LinkFree/pull/5765 is merged.

**Comment by AJcodes42** [comment]
Raised PR for this https://github.com/EddieHubCommunity/LinkFree/pull/7076
