### ISSUE TITLE
[FEATURE] Made Tags unclickable and add Button

### ISSUE THREAD

**Issue by Ahtaxam** [EddieHubCommunity/LinkFree#5959]
### Description

The tags of users specify it's skills. we should made them not clickable and only viewable. we can add back button or link to go back search page.

What you think Team ?

### Screenshots

![Screenshot from 2023-04-10 10-26-03](https://user-images.githubusercontent.com/64573767/230832343-3830016a-f31d-4fb6-8b4f-392cfb9f0fab.png)

**Comment by karthiknadar1204** [comment]
If this issue is still open,please assign it to me,i would like to work on it

**Comment by pratham-yuxo** [comment]
@Ahtaxam If it is open, then please assign it to me.

**Comment by eddiejaoude** [comment]
Thank you for the idea. But I think for the moment, the feature should stay at it is
