### ISSUE TITLE
QR code is not getting scanned in dark mode.

### ISSUE THREAD

**Issue by pratham-yuxo** [EddieHubCommunity/LinkFree#5969]
### Description

When I'm scanning the QR code in dark mode, it is not getting scanned properly. Because apparently QR code needs a white background.

Dark Mode
![Screenshot (278)](https://user-images.githubusercontent.com/111678040/230909547-27f51008-3b41-46e8-9d8a-9855a144cc72.png)

Light Mode
![Screenshot (279)](https://user-images.githubusercontent.com/111678040/230909564-4e9da94e-3276-4eba-9ebb-b445810b8938.png)

What are your thoughts on this??

**Comment by pratham-yuxo** [comment]
I have a solution for this. Look at this screenshot.

By adding a border will solve this problem.
![Screenshot (280)](https://user-images.githubusercontent.com/111678040/230910064-0c6c2cc3-2747-4d46-a851-3e4c7ecbb967.png)

If you have any other suggestions, then you can tell me. Or should I create a PR for this?

**Comment by Devesh35** [comment]
Can you assign this to me?

Fix to be done: Make sure the QR code has a contrasting background (white) without changing the position or alignment of the QR.

**Comment by eddiejaoude** [comment]
> I have a solution for this. Look at this screenshot.
> 
> By adding a border will solve this problem. ![Screenshot (280)](https://user-images.githubusercontent.com/111678040/230910064-0c6c2cc3-2747-4d46-a851-3e4c7ecbb967.png)
> 
> If you have any other suggestions, then you can tell me. Or should I create a PR for this?

Thank you @pratham-yuxo for raising the bug and coming up with a solution. I have updated the labels with `ready for dev` and I have assigned it to you.

@Devesh35 the author of the issue already requested to work on it, please have a look at other open issues that are `ready for dev` and not assigned

**Comment by pratham-yuxo** [comment]
@eddiejaoude Thank you for assigning this to me, I will solve this issue as soon as possible.
