### ISSUE TITLE
Hover action in the icons and logo of NavBar

### ISSUE THREAD

**Issue by YOKESHCR** [EddieHubCommunity/LinkFree#5972]
### Description

The color of the Github icon and the the dark mode toggle icon is white when compared to the other links. And there is also no action performed while hovering over the icon buttons apart from the mouse pointer functionality. This looks quite odd. And the same applies also to the logo at the extreme left of the Nav Bar

### Screenshots

![image](https://user-images.githubusercontent.com/27686539/230942415-23095703-7c00-4660-9f49-4189145c7d88.png)

**Comment by anupamthe99** [comment]
Hi everyone, I just submitted a pull request (#5972) to address this issue. I have made some changes to the code to fix the problem, and I believe they should resolve the issue. Please take a look at the pull request and let me know if you have any feedback or suggestions. Thanks!

**Comment by eddiejaoude** [comment]
@YOKESHCR thank you or raising the issue 👍 

> Hi everyone, I just submitted a pull request (#5972) to address this issue. I have made some changes to the code to fix the problem, and I believe they should resolve the issue. Please take a look at the pull request and let me know if you have any feedback or suggestions. Thanks!

@anupamthe99 thank you for your contribution, but please read our contributing guide next time, as this will avoid confusion and extra work for the project and community https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by anupamthe99** [comment]
Hi @eddiejaoude,

Thanks for your kind suggestion. I appreciate your help and will make sure to read the contributing guide before contributing to the project again.

Best regards,
Anupam
