### ISSUE TITLE
Inherit the EddieHubCommunity template!

### ISSUE THREAD

**Issue by stemount** [EddieHubCommunity/LinkFree#6]
We skipped using the EddieHubCommunity template! PR is open but not sure if you can add a template retrospectively to a repo!

**Comment by krishdevdb** [comment]
Is this fixed yet or I can work on this?

**Comment by RoshanMhatre** [comment]
I believe it's fixed now

**Comment by nhcarrigan** [comment]
Yep I think this is good to go.
