### ISSUE TITLE
[DOCS] Typo in the maintainers page

### ISSUE THREAD

**Issue by ChinmayMhatre** [EddieHubCommunity/LinkFree#6001]
### Description

spelling error in the second to last line at : https://linkfree.io/docs/contributing/maintainers

(modification, to the)

### Screenshots

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/51131670/231264769-a7af4c3b-2a93-45a4-adac-21ae00df758e.png">

**Comment by eddiejaoude** [comment]
Good spot 👍

**Comment by pratham-yuxo** [comment]
If no one is working on this issue, can I work on it?

**Comment by anupamthe99** [comment]
Yes @eddiejaoude  , i would like to work on this issue

**Comment by eddiejaoude** [comment]
@anupamthe99 I have assigned this issue to you

@pratham-yuxo and @AJcodes42 please have a look at other issues
