### ISSUE TITLE
Extra backtick in docs

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#6008]
### Description

Remove extra closing backtick for inline code

<img width="534" alt="Screenshot 2023-04-12 at 09 51 35" src="https://user-images.githubusercontent.com/624760/231335936-3310b65c-9f82-46db-b4ab-7bbf9d521eaf.png">

**Comment by eddiejaoude** [comment]
@iamvbenz49 would you like me to assign you this issue?

**Comment by eddiejaoude** [comment]
> Can you assign me this issue ?

hi @anupamthe99 , I promised this issue to someone else, but there is as similar issue if you would like? I am about to put the label `status: ready for dev` on it, leave a comment in this issue #6001 if you would like me to assign it to you https://github.com/EddieHubCommunity/LinkFree/issues/6001

**Comment by iamvbenz49** [comment]
Yes, you can assign this issue to me

**Comment by iamvbenz49** [comment]
Can I know where are the docs

**Comment by eddiejaoude** [comment]
ok assigned 👍 

Try searching the codebase for the text you see in the screenshot

**Comment by gantanikhilraj** [comment]
@eddiejaoude I have removed the extra backtick, please check the PR #6017

**Comment by eddiejaoude** [comment]
> @eddiejaoude I have removed the extra backtick, please check the PR #6017

Thank you @gantanikhilraj for the contribution but the issue is not assigned to you. Please read our contributing guidelines so you don't cause confusion and also create extra work for you plus us https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by iamvbenz49** [comment]
I removed the extra backtick @eddiejaoude , here's the link to PR #6026
