### ISSUE TITLE
Move table component to a separate file 

### ISSUE THREAD

**Issue by ChinmayMhatre** [EddieHubCommunity/LinkFree#6012]
### What would you like to share?

We can see an inline `table` component on line 6 of the component `components/mdx/ComponentStyles.js`

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/51131670/231348307-847d796b-f1f2-4458-a68d-24b95eee8952.png">

## Changes Requested

Please move this inline Component to a separate file `components/mdx/Table.js` and import it in the `ComponentStyles.js` component.

**Comment by anupamthe99** [comment]
Hey anyone working on this issue , I would be happy to work on it .

**Comment by ChinmayMhatre** [comment]
> Hey anyone working on this issue , I would be happy to work on it .

Hey @anupamthe99, please refrain from spamming on issues that don't have the "ready for dev" tag.

**Comment by eddiejaoude** [comment]
> Hey anyone working on this issue , I would be happy to work on it .

@anupamthe99 you have already been explained the contributing guidelines on multiple issues in the last few days with a link to the contributing guidelines, which you have acknowledged, plus you already have an issue assigned to you    
- https://github.com/EddieHubCommunity/LinkFree/issues/5972#issuecomment-1502577877
- https://github.com/EddieHubCommunity/LinkFree/issues/5926#issuecomment-1504409947

**Comment by ajaxbo360** [comment]
Hi , @ChinmayMhatre , i would like to take on this issue if it’s not yet taken.Thanks.

**Comment by eddiejaoude** [comment]
@ajaxbo360 I have assigned the issue to you
