### ISSUE TITLE
Move the li component to a separate file

### ISSUE THREAD

**Issue by ChinmayMhatre** [EddieHubCommunity/LinkFree#6013]
### What would you like to share?

We can see an inline `li` component on line 11 of the component `components/mdx/ComponentStyles.js`

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/51131670/231348307-847d796b-f1f2-4458-a68d-24b95eee8952.png">

## Changes Requested

Please move this inline Component to a separate file `components/mdx/Li.js` and import it in the `ComponentStyles.js` component.

**Comment by eddiejaoude** [comment]
> Can anyone assigned me this issue ?

@anupamthe99 you already have an open issue assigned to you, if you are unsure please read the contributing guidelines https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by pratham-yuxo** [comment]
Can I work on this issue?

**Comment by eddiejaoude** [comment]
Sure @pratham-yuxo , I have assigned it to you
