### ISSUE TITLE
[FEATURE] Adding a scroll Button

### ISSUE THREAD

**Issue by pratham-yuxo** [EddieHubCommunity/LinkFree#6014]
### Description

If I search for something and there are too many results, and I find myself at the bottom of the search page and want to go back to the top, I have to use the mouse or side scroller.

**Solution**
I think we can make it much easier by adding a button which will scroll to the top automatically.

This button can be added at the bottom right position and will be visible only when user has scrolled.
![Screenshot (282)](https://user-images.githubusercontent.com/111678040/231376914-00291bd8-c74e-4684-a7c4-7e356f3a4c56.png)

UI of the button
![Screenshot (283)](https://user-images.githubusercontent.com/111678040/231376930-190e23b7-ef2e-4820-b3d0-b986d554db4b.png)

If you have any other suggestions regarding this then you can tell me. For now I'm thinking of adding this to the search tab, but if you want I can make a general function and can use that in other tabs too.

### Additional information

@eddiejaoude If you think that this feature will help then can you please assign this issue to me?

**Comment by eddiejaoude** [comment]
Thank you for the suggestion. But later we plan to have pagination feature, so I think this won't be needed
