### ISSUE TITLE
[FEATURE] Ability to add a recurring event

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#6020]
### Description

This is an idea to adjust the events json to allow for recurring events.  This idea came to me due to certain types of events that happen on a regular basis (ex. monthly meetup, weekly livestream)

Potential strategy:

isRepeating (or isRecurring) - optional field- yes/no

if yes we would need the cadence: ex. "weekly on Thursdays at 9am" 

One idea:
if recurrung is YES, then these 3 fields are required
**cadence**: weekly,monthly,bi-weekly, etc
**dayOfWeek:** M,Tu,Wed,Th,Fr,Sa,Su
**time**: time with timezone here

**This change will require UI changes that can be addressed in a separate issue if we move forward

**Comment by eddiejaoude** [comment]
Thanks Amanda! My concern with this feature, is that people might "fake" the reoccurrence daily just to always appear at the top - we saw a lot of these "gaming" the system style tactics on the Discover page (which I really miss)

So I like the idea but I think it is too easily gamble, so I might close for now
