### ISSUE TITLE
[OTHER] Have consistent border radius for both inputs on playground page

### ISSUE THREAD

**Issue by FrozenHearth** [EddieHubCommunity/LinkFree#6025]
### What would you like to share?

There's a difference in border radius in the first and second input boxes in playground page

<img width="1439" alt="Screenshot 2023-04-12 at 8 09 51 PM" src="https://user-images.githubusercontent.com/27160715/231493146-f9025d27-5be5-4760-8733-50d3d3890b79.png">

Having a consistent border-radius would make it look clean.

**Comment by eddiejaoude** [comment]
Good spot 👍

**Comment by FrozenHearth** [comment]
Thank you @eddiejaoude 
Please assign it to me.

**Comment by ajaxbo360** [comment]
Hi, i would like to take on this issue. Thanks.

**Comment by eddiejaoude** [comment]
> Hi, i would like to take on this issue. Thanks.

@ajaxbo360 I know you are energetic but it has already been requested only a few minutes before you, it is best to check the issue history first, plus you already have an open issue assigned to you, please read our contributing guidelines https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

@FrozenHearth I have assigned it to you

**Comment by FrozenHearth** [comment]
Thanks @eddiejaoude 
Will add a PR soon.
