### ISSUE TITLE
[Refactoring] Refactor the Components , Utils ,Constant and pages.

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [EddieHubCommunity/LinkFree#605]
### What would you like to share?

Currently, We are just following a random folder structure but we should change it.

We should refactor our application like this.

Page
 - it only contains the API calls and components to render 
 - no business logic

components
 - It will receive the props from the parent component and render the UI
 - it will include the business logic 
 
Utils
  - it will include the utility file for our application

Constant
 - it will include the constant that we are using in our application.

**Comment by eddiejaoude** [comment]
Referencing the jsx discussion https://github.com/EddieHubCommunity/LinkFree/issues/612

**Comment by Sfitzg** [comment]
👍🏻 For this Idea 
I tried to work on an issue and I also got super confused as to the file structure wasn't sure what was a view or a component took me quite a while to understand what was what.

I'd like to propose that while doing the refactor you also use the folder method for components.
for example -

- Components (Folder)
     - ComponentName (Folder)
         - ComponentName.js (File)
         - ComponentName.css (File)
         - ComponentName.module.css (File)
         - index.js  (File - this file exports the ComponentName.js so when importing the component you can just hit the folder instead of needing to hit the folder and the file )

This is just my input use it don't use it.

**Comment by Sachin-chaurasiya** [comment]
> 👍🏻 For this Idea I tried to work on an issue and I also got super confused as to the file structure wasn't sure what was a view or a component took me quite a while to understand what was what.
> 
> I'd like to propose that while doing the refactor you also use the folder method for components. for example -
> 
> * Components (Folder)
>   
>   * ComponentName (Folder)
>     
>     * ComponentName.js (File)
>     * ComponentName.css (File)
>     * ComponentName.module.css (File)
>     * index.js  (File - this file exports the ComponentName.js so when importing the component you can just hit the folder instead of needing to hit the folder and the file )
> 
> This is just my input use it don't use it.

@Sfitzg thank you.

**Comment by Sfitzg** [comment]
@Sachin-chaurasiya is this still being worked on ?

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya is this still being worked on ?

@Sfitzg As changes are being made continuously so it will take more time to complete this.

**Comment by krishguptadev** [comment]
You can mark the PR if any draft for now then 🙂
