### ISSUE TITLE
[DOCS] clarify whether location is required or optional on events guide

### ISSUE THREAD

**Issue by wrmacdonald** [EddieHubCommunity/LinkFree#6059]
### Description

There seems to be conflicting information on the event docs page (https://linkfree.eddiehub.io/docs/how-to-guides/events), whether the location is required. On Add Event > 3. it says **location** is required, however, in the table view below, the Required column is marked as **false**.

### Screenshots

<img width="1280" alt="Screen Shot 2023-04-13 at 3 09 03 PM" src="https://user-images.githubusercontent.com/64927843/231894839-dd57a547-99e4-4182-a1b8-d7c1d29ab745.png">
<img width="1279" alt="Screen Shot 2023-04-13 at 3 09 14 PM" src="https://user-images.githubusercontent.com/64927843/231894860-bdeb7e1c-ed60-46c8-8402-5b84599868d3.png">

**Comment by eddiejaoude** [comment]
Good spot 👍 I think it should be required if `isInPerson` is `true`

**Comment by pratham-yuxo** [comment]
Can I work on this issue?

**Comment by lokesh3097** [comment]
Can you assign this to me?

**Comment by eddiejaoude** [comment]
> So, In the 3rd point of add event, we have to make a change like this "If `isInPerson` is true then location is required otherwise not". or we can write like this-> This json file will contain one object for the event and must have six fields, `isVirtual` and/or `isInPerson`, `color`, `name`, `description`, `date`, `url`, and `location`(required only when `isInPerson` is true), which will look like this:
> 
> Can I work on this issue?

Yes we need to update the docs in 2 places, point 3 in the first screenshot and also the table can show `true/false` and in the description have a brief explanation
