### ISSUE TITLE
New Feature - Fixed Position Nav Bar

### ISSUE THREAD

**Issue by YOKESHCR** [EddieHubCommunity/LinkFree#6062]
### Description

Hi @eddiejaoude,

I might recommend to go with a fixed Nav bar so that on scrolling long pages it might be easier to navigate to other pages.

### Additional information

If this issue is approved can you please assign this to me?

**Comment by eddiejaoude** [comment]
Thank you for the idea and suggestion. But I don't think this is needed for now
