### ISSUE TITLE
[OTHER] Create a Basic Test for Map Page

### ISSUE THREAD

**Issue by Vishrut19** [EddieHubCommunity/LinkFree#6064]
### What would you like to share?

The goal of this issue is to have a test file and test to navigate to the Map page, and that checks the page loads correctly with the heading with no error.

Edit: belongs to this epic https://github.com/EddieHubCommunity/LinkFree/issues/5787

**Comment by Vishrut19** [comment]
let's go!!! 🚀

**Comment by eddiejaoude** [comment]
@Vishrut19 it looks like this ended up as a duplicate as part of populating the database with map information via the tests https://github.com/EddieHubCommunity/LinkFree/pull/6084

So I will close this issue, please selected another page to add the basics tests to
