### ISSUE TITLE
Biography information repeated twice on user marker in map view

### ISSUE THREAD

**Issue by weilincheng** [EddieHubCommunity/LinkFree#6080]
### Description

The user's biography information on the map marker is duplicated and displayed twice. This can be easily observed in the attached screenshot.

Steps to Reproduce:
- Navigate to the map page.
- Observe any one of the user markers.
- Notice that the biography information is repeated twice on the marker.

### Screenshots

![image](https://user-images.githubusercontent.com/7236196/232172849-41f9655d-8234-4b97-8b31-d96e2a73769d.png)

**Comment by eddiejaoude** [comment]
Thanks for raising 👍 how this has been raised already, I will close as it is a duplicate issue https://github.com/EddieHubCommunity/LinkFree/issues/5867

**Comment by weilincheng** [comment]
> Thanks for raising 👍 how this has been raised already, I will close as it is a duplicate issue #5867

Thanks for the heads up! I didn't realize this issue had already been raised. I'll be more careful next time and make sure to check for duplicates before submitting anything.

**Comment by eddiejaoude** [comment]
No problem, it happens sometimes
