### ISSUE TITLE
UX improvement on docs page

### ISSUE THREAD

**Issue by Chandraprakash-Darji** [EddieHubCommunity/LinkFree#6096]
### Description

When we vist the docs page: https://linkfree.io/docs

- There are cards on the page to navigate between docs:
![Screenshot 2023-04-15 at 2 59 33 PM](https://user-images.githubusercontent.com/93640141/232205574-98569c78-3c35-4ef2-a494-c5bbc2bd5b72.png)

- When we hover the card it show the border:
![Screenshot 2023-04-15 at 3 00 20 PM](https://user-images.githubusercontent.com/93640141/232205602-04d635f6-e6a2-41e8-98a7-2b4f08fac760.png)

But is clickable only on in the red border: (I have added the border to explain)
![Screenshot 2023-04-15 at 3 00 55 PM](https://user-images.githubusercontent.com/93640141/232205630-dd8b31bb-b2f2-46f5-8346-182998e8d567.png)
It would be good that when we click in the green border also. 

It show border all over that it should be clikable

**Comment by Lalman888** [comment]
I want to contribute . I can do above task

**Comment by iamvbenz49** [comment]
@eddiejaoude your thoughts on this issue?

**Comment by eddiejaoude** [comment]
@Lalman888 please do not tag maintainers, we all get the notifications, plus please do not ask for issues that are still awaiting triage, we have contributing guide with more information https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

@iamvbenz49 yes we can make this clearer by having the whole hover area clickable or removing the hover effect and having only the title clickable

**Comment by thehashmap** [comment]
I would like to work on this task, can you please assign it to me?

**Comment by iamvbenz49** [comment]
I would love to work on it

**Comment by SaraJaoude** [comment]
> I would like to work on this task, can you please assign it to me?

@thehashmap as you were the first to request this once the label changed to `status: ready for dev` I will assign this to you
