### ISSUE TITLE
[DOCS] Quick copy all required env vars

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#6114]
### Description

The variables documentation has a nice table of all the variables and what they mean, but you must copy/paste individually into your project.  The idea for this issue would be to create a button on that page to copy the required variable to be able to quickly post them to your local .env file.

docs page: https://linkfree.io/docs/environments/environment-variables

**Comment by iamvbenz49** [comment]
I can work on this issue

**Comment by eddiejaoude** [comment]
> ### Description
> The variables documentation has a nice table of all the variables and what they mean, but you must copy/paste individually into your project. The idea for this issue would be to create a button on that page to copy the required variable to be able to quickly post them to your local .env file.
> 
> docs page: https://linkfree.io/docs/environments/environment-variables
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

Ah yes a code block would work well, because we have a copy button at the top right (although it seems to be hidden with recent theme changes, but that can be fixed in another issue)

**Comment by eddiejaoude** [comment]
> ### Description
> The variables documentation has a nice table of all the variables and what they mean, but you must copy/paste individually into your project. The idea for this issue would be to create a button on that page to copy the required variable to be able to quickly post them to your local .env file.
> 
> docs page: https://linkfree.io/docs/environments/environment-variables

Ah yes a code block would work well, because we have a copy button at the top right (although it seems to be hidden with recent theme changes, but that can be fixed in another issue)

**Comment by eddiejaoude** [comment]
> I can work on this issue

@iamvbenz49 as discussed multiple times please do not request an issue if it has not be triaged, it creates more noise and will not be assigned, you can learn more on our contributing guide https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by PratikDey** [comment]
Hi, if it's not a problem with @iamvbenz49 , can I take up this issue?

**Comment by SaraJaoude** [comment]
@PratikDey as you request this issue be assigned to you once the correct label was added, this is not a problem.  I will assign this to you now.

**Comment by iamvbenz49** [comment]
I'm sorry @eddiejaoude

**Comment by amandamartin-dev** [comment]
Hello @PratikDey it has been 2 weeks so would like to check in that you are in progress on this issue, if not we will open it to be assigned.  Let us know if you need more time!

**Comment by amandamartin-dev** [comment]
> Hi @amandamartin-dev , sorry I couldn't update. Actually I have done the changes but I am not able to test as because I am getting an error while running locally.

If you want, you can try in gitpod or open a draft PR so others can see any potentially help problem solved the errors with you

**Comment by PratikDey** [comment]
Hi there, I have added a draft pull request. Let me know if any changes are required.

**Comment by amandamartin-dev** [comment]
> Hi there, I have added a draft pull request. Let me know if any changes are required.

Apologies for the delayed response, I was traveling.  I see that the draft PR is now closed.  Are you still working on this?

**Comment by PratikDey** [comment]
> > Hi there, I have added a draft pull request. Let me know if any changes are required.
> 
> Apologies for the delayed response, I was traveling. I see that the draft PR is now closed. Are you still working on this?

Yes Amanda, I made some mistakes in the previous PR, that's why it got closed. 
You can expect a PR(with correct code) by this week
