### ISSUE TITLE
[DOCS] Put all local dev env instructions in one place

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#6115]
### Description

Request/Discussion - 

When setting up my local environment I first clicked on the local development quickstart and downloaded db/began to go through the process.  I only realized after I had started that the docker local dev docs were in another location and recommended. 

Proposing to combine the two local documentation cards into one that has 2 sections:
Card title ideas: Local Development || Setting up your development environment || Local development Options
with 2 sections:
Docker compose (recommended)
Local development (advanced)

![local-dev](https://user-images.githubusercontent.com/97615019/232252073-04ab1e5a-4ceb-4f6b-8e87-c22cd42b3185.jpg)

**Comment by CBID2** [comment]
I'll try this! :)

**Comment by SaraJaoude** [comment]
> I'll try this! :)

@CBID2 thank you for your enthusiasm.  Please keep a look out for when this Issue has the label `status: ready for dev` and ask for it to be assigned to you then.

**Comment by CBID2** [comment]
Ok thanks @SaraJaoude! :)

**Comment by geeky-sambhav** [comment]
I would like to contribute on this issue

**Comment by SaraJaoude** [comment]
> I would like to contribute on this issue

@geeky-sambhav please wait until the label changes to `status: ready for dev` before asking to be assigned an issue

**Comment by CBID2** [comment]
> I would like to contribute on this issue

Hey @geeky-sambhav! 😊 We can work on it together if you want?

**Comment by geeky-sambhav** [comment]
@CBID2 yea cool

**Comment by Nanak360** [comment]
I see this issue has not been assigned to anyone yet.
I can take it up in that case.

**Comment by SaraJaoude** [comment]
> I see this issue has not been assigned to anyone yet.
> I can take it up in that case.

@Nanak360 as you are the first person to comment now that the label has changed, I will assign this Issue to you

**Comment by geeky-sambhav** [comment]
@Nanak360 can we work on this issue together?

**Comment by Nanak360** [comment]
> @Nanak360 can we work on this issue together?

Sure
@SaraJaoude what do you say about it?

**Comment by CBID2** [comment]
> I have made some changes
> 
> Here is a screenshot of the `docs/environments/local-development` page: ![LinkFree-Local-Development-Documentation](https://user-images.githubusercontent.com/36790357/233126435-7242b5db-799b-4320-9527-a76dcf7e2fe5.png)
> 
> and here is a screenshot of `docs` page: ![LinkFree-Documentation](https://user-images.githubusercontent.com/36790357/233126587-84c13d44-8806-40ff-8c3c-2a7dbb7c2e89.png)
> 
> let me know if some additional changes are required or if any change in text is needed.

Can you post a link to your PR @Nanak360? I'll provide my feedback there.
