### ISSUE TITLE
Links are rendering empty in playground when links array contains objects with empty key-val pair

### ISSUE THREAD

**Issue by NiazMorshed2007** [EddieHubCommunity/LinkFree#6117]
### Which page is affected?
The `playground` page is affected

### What is the problem?
While putting JSON for previewing in playground, if I put `links` array with empty `objects` it renders links with empty name and url in the preview.

`#### Here is code that produced the issue:`
```json
{
    "name": "Niaz Morshed",
    "type": "personal",
    "bio": "Dev",
    "links": [
        {},
        {},
        {}
    ]
}
```

`#### Here is result/bug due for the code`:

![image](https://user-images.githubusercontent.com/77217706/232260971-710f8d58-eae7-49a6-9488-4ce836baa874.png)

### Possible fix?
Links shouldn't be rendered until the object holds key value pairs. Possibly, currently it's only checking if the length of the links array is larger than 0.

Would love to work on this 🙂

**Comment by Nanak360** [comment]
I can take this up

**Comment by SaraJaoude** [comment]
> I can take this up

@Nanak360 please see my comment to you on https://github.com/EddieHubCommunity/LinkFree/issues/6120 which applies here, as to familiarising yourself with the Contribution guidelines. 

Also to note:

1. We only assign one Issue per person
2. This Issue is not ready to be assigned - it still has the label `status: awaiting triage`.  It will be ready to be assigned when the label changes to `status: ready for dev`

**Comment by luckyklyist** [comment]
can i work on this issue after it is being status: ready for dev ?

**Comment by SaraJaoude** [comment]
> can i work on this issue after it is being status: ready for dev ?

@luckyklyist in order for maintainers to manage the project more efficiently, we will not be looking at requests or considering requests for assigning an issue until the label has changed.

**Comment by Nanak360** [comment]
> > I can take this up
> 
> @Nanak360 please see my comment to you on https://github.com/EddieHubCommunity/LinkFree/issues/6120 which applies here, as to familiarising yourself with the Contribution guidelines. 
> 
> Also to note:
> 
> 1. We only assign one Issue per person
> 2. This Issue is not ready to be assigned - it still has the label `status: awaiting triage`.  It will be ready to be assigned when the label changes to `status: ready for dev`

Yes absolutely
Will keep it in mind

**Comment by eddiejaoude** [comment]
Thank you @NiazMorshed2007 for raising the issue. But I don't see this as an issue that is occurring with the users.
