### ISSUE TITLE
BUG: copy code block theme colours make it hidden

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#6120]
### Description

- update light theme button colour for `copy`, I think `text-primary-low` will help, but will need a hover state
- update dark theme button colour for `copy`

maybe this can use preset theme colours

<img width="1662" alt="Screenshot 2023-04-16 at 11 05 09" src="https://user-images.githubusercontent.com/624760/232265968-b5c0379b-9265-47c9-9afc-ee91c6e30d34.png">

**Comment by Nanak360** [comment]
I can take it up

**Comment by pratham-yuxo** [comment]
can I work on this issue?

**Comment by luckyklyist** [comment]
can I work on this issue if anyone is not working on it ?

**Comment by Nanak360** [comment]
I have started working on it

**Comment by SaraJaoude** [comment]
> I have started working on it

@Nanak360 this is not how we deal with contributions on this project and I suggest you familiarise yourself with our Contributing Guide: https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

Please do not start to work on an Issue if this has not be assigned to you - this causes confusion to other contributors, extra work for maintainers and it is no guarantee to you that the time spent and the work you do will be accepted. 

In this case, as you were the first person to comment I will assign it to you.

**Comment by Nanak360** [comment]
> > I have started working on it
> 
> @Nanak360 this is not how we deal with contributions on this project and I suggest you familiarise yourself with our Contributing Guide: https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md
> 
> Please do not start to work on an Issue if this has not be assigned to you - this causes confusion to other contributors, extra work for maintainers and it is no guarantee to you that the time spent and the work you do will be accepted.
> 
> In this case, as you were the first person to comment I will assign it to you.

Oh yes, really sorry about this. My bad.
I have gone through the Contributing guide and will keep it in mind from the next time.
