### ISSUE TITLE
[DOCS] Update Gitpod Docs

### ISSUE THREAD

**Issue by ThomasCode92** [EddieHubCommunity/LinkFree#6132]
### Description

I had some trouble connecting my copy of this repository and Gitpod. After some online research, I managed to get it to work.
The docs on LinkFree weren't that clear, I suppose to update them with a step-for-step example.

### Screenshots

![image](https://user-images.githubusercontent.com/108367944/232479169-e3f9baf3-f5f9-4650-b0c5-eaf6c437755f.png)

### Additional information

The docs are very unclear (at least to me). For example

- it doesn't say which repo you must or can open with gitpod
- It doesn't say how you can open a repo
- there is no step-for-step guide (with instruction how you can make a change/ contribution
- the Gitpod link is broken, it leads to an _'Couldn't parse context error'_

![image](https://user-images.githubusercontent.com/108367944/232481523-98ad2af4-be87-4f97-9911-606e4200e4f0.png)

**Comment by luckyklyist** [comment]
It would have been more clear if you have added some screen shots regarding the issues in docs .

**Comment by eddiejaoude** [comment]
@ThomasCode92 thank you for raising the issue, but it is unclear what was missing? Please include more information

**Comment by nithin999989** [comment]
@ThomasCode92 can u please elobrate please

**Comment by ThomasCode92** [comment]
Hi, @luckyklyist, @eddiejaoude and @nithin999989 
I updated my first post to clarify a couple of things, I hope this helps

**Comment by eddiejaoude** [comment]
Thank you for updating @ThomasCode92 👍  Would you like this issue assigned to you as you are familiar with it?

**Comment by ThomasCode92** [comment]
@eddiejaoude, you can assign this issue to me!

**Comment by CBID2** [comment]
> @eddiejaoude, you can assign this issue to me!

I'd like to help with this issue to if you don't mind @ThomasCode92! 😄

**Comment by CBID2** [comment]
> > > @eddiejaoude, you can assign this issue to me!
> 
> > 
> 
> > I'd like to help with this issue to if you don't mind @ThomasCode92! 😄
> 
> 
> 
> Hi @CBID2, sorry for the late response (very busy with work, wedding plans & renovations)
> 
> But great idea! Let's work on this together.
> 
> I have already made an branch for it, you can check it out on [my repo](https://github.com/ThomasCode92/LinkFree/tree/update-gitpod-docs). 
> 
> 
> 
> Do I need to give you access to this branch? (I never worked together with someone on a PR)
> 
> Maybe we can co-author some commits?
I can just add some suggestions to your lines of code and you can commit them

**Comment by ThomasCode92** [comment]
@CBID2, can't see your answer?

**Comment by CBID2** [comment]
> @CBID2, can't see your answer? 

Hey @ThomasCode92! I was asking if you can link your PR here.

**Comment by ThomasCode92** [comment]
I haven't made an PR yet, will do it as soon as possible and let you now!

**Comment by ThomasCode92** [comment]
@CBID2, I created a PR

**Comment by CBID2** [comment]
> @CBID2, I created a PR

Ok share the link here
