### ISSUE TITLE
Allow Users to Add Custom Icons to Links

### ISSUE THREAD

**Issue by iAnonymous3000** [EddieHubCommunity/LinkFree#6135]
### Description

Currently, Linkfree only allows users to choose from a set of predefined icons when adding links to their profile. This feature request proposes enabling users to add custom icons to their links.

Linkfree would become more visually appealing and engaging by allowing users to add custom icons. Users could select icons that better represent the content of their links and match their personal branding.

This feature would allow users to:

- Add more personality and customization to their Linkfree profile
- More accurately represent the content of their links
- Customize the appearance of their Linkfree profile to match their branding and style

By enabling users to add custom icons to their links, Linkfree would become a more versatile and user-friendly platform. It would allow users to express themselves and their work better, resulting in a more engaging and visually appealing experience.

**Comment by Lalman888** [comment]
To add custom icons we can add a upload button to upload icon

**Comment by eddiejaoude** [comment]
Thank you for the suggestion, for the moment I think we have enough icons available with 2 large icon sets already included, these can be searched here https://linkfree.io/icons
