### ISSUE TITLE
Side margins are not consistent.

### ISSUE THREAD

**Issue by Pradumnasaraf** [EddieHubCommunity/LinkFree#620]
### Description

**Side margins on the landing page are not consistent, even though the page is at 100%.**

The problem arises in :

* PC
* Mobile
* Mobile with Desktop site enabled.

### PC

![Screenshot 2021-10-29 181305](https://user-images.githubusercontent.com/51878265/139445824-4d8323b4-4c4f-4153-bd91-e80cbe18c261.png)

### Mobile

<p align="center"><img src="https://user-images.githubusercontent.com/51878265/139446282-1fe3c764-ff34-4231-b408-a4e69b4d8a8f.png" height =700></p>

### Mobile with Desktop site enabled

<p align="center"><img src="https://user-images.githubusercontent.com/51878265/139446519-a42ed78a-d01d-4060-ad7e-3a387ffbf96c.png" height =700></p>

### Additional information

It may vary from one screen size to another

**Comment by FidalMathew** [comment]
@Pradumnasaraf  I would like to work on this issue. I hope no one is working on it.

**Comment by Pradumnasaraf** [comment]
Yes, go-ahead,
+ soon any maintainer will assign this to you.

**Comment by mohan-murali** [comment]
@FidalMathew Oh you are working on this? I actually fixed this one.

**Comment by FidalMathew** [comment]
Sorry, @mohan-murali I didn't check out this message. Thank you for giving me the opportunity to contribute.

**Comment by Pradumnasaraf** [comment]
> @FidalMathew Oh you are working on this? I actually fixed this one.

So you didn't open the PR after fixing @mohan-murali ?

**Comment by mohan-murali** [comment]
> > @FidalMathew Oh you are working on this? I actually fixed this one.
> 
> So you didn't open the PR after fixing @mohan-murali ?

No I was going to, but it was taken. And I checked that @FidalMathew  had already raised PR. Its fine. As long as it fixes the issue. :)

**Comment by Pradumnasaraf** [comment]
Oh I see, still thanks for the effort

Just advice - if you find some Open issues, and you feel like you gonna work on it before start working on that, drop a message below the issue like `I'm working on this`/get assigned

**Comment by Pradumnasaraf** [comment]
Sorry, I closed it by mistake,
