### ISSUE TITLE
[OTHER]

### ISSUE THREAD

**Issue by moonLight-7k** [EddieHubCommunity/LinkFree#6218]
### What would you like to share?

I think the UI need some fix here

![Screenshot (28)](https://user-images.githubusercontent.com/90507998/233063674-86e6bb95-4207-49d8-8c0b-8a70fc16fa3f.png)

### Additional information

the buttons are not of same  size and its seems like they are jumping.

**Comment by SaraJaoude** [comment]
There is no title. It is also unclear as to what improvement is being suggested. I will be closing this issue. 

Please feel free to raise an issue with more actionable details.
