### ISSUE TITLE
Place "Contribute on Github" at the navbar(Grey empty area)

### ISSUE THREAD

**Issue by FidalMathew** [EddieHubCommunity/LinkFree#623]
### Description

Instead of Footer being in place after the end of the content. The issue will be focusing on placing "Contribute on Github" at the navbar(Grey empty area).

### Screenshots

![image](https://user-images.githubusercontent.com/84982038/139571878-3cfbb857-9e7a-460a-870c-1753e76d70a6.png)

**Comment by mohan-murali** [comment]
I can work on this.

**Comment by FidalMathew** [comment]
@mohan-murali I am not a maintainer, it's just an issue I found so I thought of mentioning it :)

**Comment by krishguptadev** [comment]
This seems weird to me, footers are supposed to be at the bottom, not sticky like navbars 🤔

**Comment by nhcarrigan** [comment]
I go back and forth with this in my own design.

It really depends on the rest of the layout.

**Comment by FidalMathew** [comment]
@krishguptadev @nhcarrigan I would like to try to fix this issue. Shall I continue?

**Comment by Vyvy-vi** [comment]
Personally I think it's fine this way...
Esp. since whenever anyone screenshots their links, it most probably would include this little "Contribute on <i:github> vX.X.X" line, so others viewing the screenshots might be more prone to look into making additions.

Moreover, while footers are neat, on larger screens they really disconnect with the content, unless we structure the layout in a way there is no _gap_.

**Comment by FidalMathew** [comment]
In the Eddiehub discord channel, Eddie told that it would be nice if we could put the "contribute on Github" in the grey area.
I would like to work on this issue.

**Comment by Vyvy-vi** [comment]
Oh, in the menu bar?
Sure, go on ahead. 
I think that makes a lot of sense :)
Maybe you can merge this message with the github icon on there.

I would recommend that you _update_ the issue's title and description to reflect what changes you might be making.

**Comment by FidalMathew** [comment]
Guys, I am facing some troubles, the menubar is a UI component that has parameters - start, model, end.
The start and end are defined as of now and the model has to be assigned.
The model takes items, which need to be an array. Any Idea on how to add the content there?
One link I referred to is [LINK](https://bit.dev/primefaces/primereact/menubar?__cf_chl_jschl_tk__=pmd_3LfRNhJdUKaL1mj0hxCnTJ1ZcTajmHunyJgF4X.rTI0-1635911829-0-gqNtZGzNAmWjcnBszQtR).



![image](https://user-images.githubusercontent.com/84982038/140009049-a5556dc1-7ae0-4169-b95a-72649cbedae0.png)
![image](https://user-images.githubusercontent.com/84982038/140009114-747c047b-2e24-4ada-ae29-e61e927498f7.png)

**Comment by mohan-murali** [comment]
Any idea where in the grey area you want this message?
If you want it to be at the end you can do something like 
```jsx
 end = (
      <div className="p-d-flex p-jc-center p-align-center">
        contribute on Github
        <a
          className="p-ml-3"
          href="https://github.com/EddieHubCommunity/LinkFree"
        >
          <i className="pi pi-github" style={{ fontSize: '2em' }}></i>
        </a>
      </div>
    )
```

**Comment by mohan-murali** [comment]
> Guys, I am facing some troubles, the menubar is a UI component that has parameters - start, model, end. The start and end are defined as of now and the model has to be assigned. The model takes items, which need to be an array. Any Idea on how to add the content there? One link I referred to is [LINK](https://bit.dev/primefaces/primereact/menubar?__cf_chl_jschl_tk__=pmd_3LfRNhJdUKaL1mj0hxCnTJ1ZcTajmHunyJgF4X.rTI0-1635911829-0-gqNtZGzNAmWjcnBszQtR).
> 
> ![image](https://user-images.githubusercontent.com/84982038/140009049-a5556dc1-7ae0-4169-b95a-72649cbedae0.png) ![image](https://user-images.githubusercontent.com/84982038/140009114-747c047b-2e24-4ada-ae29-e61e927498f7.png)

Otherwise you can add the contribute to the github in the items array like this 
```jsx
 if (!items) {
    items = [
      {
        label: 'Contribute on Github',
        icon: 'pi pi-fw pi-github',
      },
    ]
  }

```

**Comment by FidalMathew** [comment]
> > Guys, I am facing some troubles, the menubar is a UI component that has parameters - start, model, end. The start and end are defined as of now and the model has to be assigned. The model takes items, which need to be an array. Any Idea on how to add the content there? One link I referred to is [LINK](https://bit.dev/primefaces/primereact/menubar?__cf_chl_jschl_tk__=pmd_3LfRNhJdUKaL1mj0hxCnTJ1ZcTajmHunyJgF4X.rTI0-1635911829-0-gqNtZGzNAmWjcnBszQtR).
> > ![image](https://user-images.githubusercontent.com/84982038/140009049-a5556dc1-7ae0-4169-b95a-72649cbedae0.png) ![image](https://user-images.githubusercontent.com/84982038/140009114-747c047b-2e24-4ada-ae29-e61e927498f7.png)
> 
> Otherwise you can add the contribute to the github in the items array like this
> 
> ```js
>  if (!items) {
>     items = [
>       {
>         label: 'Contribute on Github',
>         icon: 'pi pi-fw pi-github',
>       },
>     ]
>   }
> ```
> 
> Checkout Prime React docs for more info https://www.primefaces.org/primereact/showcase/#/menubar

Thanks a ton @mohan-murali ! I will check it out
