### ISSUE TITLE
node version mismatch between nvmrc and engines

### ISSUE THREAD

**Issue by kirandash** [EddieHubCommunity/LinkFree#6233]
### Description

node version required in package.json is "node": "18.x" but nvmrc has "v16.17.0". That's why `npm i` throws a warning.

Please update node version in .nvmrc file to LTS: v18.16.0

**Comment by eddiejaoude** [comment]
Great spot @kirandash 👍 thank you for creating the issue!

**Comment by kirandash** [comment]
@eddiejaoude you are welcome! can you please assign this issue to me. I can create a PR for the fix.

**Comment by eddiejaoude** [comment]
Sure, I have assigned it to you @kirandash  👍
