### ISSUE TITLE
[OTHER] Playground Page - Have profile json's placeholder text as default input value for better UX

### ISSUE THREAD

**Issue by FrozenHearth** [EddieHubCommunity/LinkFree#6249]
### What would you like to share?

The placeholder text in profile json disappears as soon as user starts typing. The user has to clear the input text to see the placeholder text again.

I think if we have the default input value as the placeholder text, that would be very simple for the user. The user doesn't have to clear the input text repeatedly to see the format of the profile json.

We can go with that, or either have the profile json sample below the input value so that the user can always refer to it.

https://user-images.githubusercontent.com/27160715/233563200-1f4f514a-b54b-460f-ad10-d43e9eff5e54.mov

**Comment by eddiejaoude** [comment]
Good idea 👍 we didn't do this originally because we didn't want people to forget to update some fields, but having a default json would be helpful for people to get started 💯

**Comment by Zhreyu** [comment]
Hey! can I tackle this issue?

**Comment by Zhreyu** [comment]
I believe #6294 fixes this issue

**Comment by SaraJaoude** [comment]
> Hey! can I tackle this issue?

> I believe #6294 fixes this issue

@Zhreyu in future please read the Contributing Guide: https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

Please wait for an issue to be assigned to you before you create a Pull Request.  If you do not then you run the risk of the Pull Request being closed and the time and work you spent on this being lost.

On this occasion as no one else has asked for this issue, I will assign this to you.

**Comment by Zhreyu** [comment]
I'm sorry, I will be more careful from now on, thanks for assigning me the issue

**Comment by FrozenHearth** [comment]
> Good idea 👍 we didn't do this originally because we didn't want people to forget to update some fields, but having a default json would be helpful for people to get started 💯

I see. Yes, default json would be fantastic. :)

**Comment by yosr-fourati** [comment]
Can you assign this to me ?
@eddiejaoude

**Comment by eddiejaoude** [comment]
This issue has already been completed, sorry for the confusion https://github.com/EddieHubCommunity/LinkFree/pull/6294
