### ISSUE TITLE
Client side error upon blank JSON input in playground JSON textarea

### ISSUE THREAD

**Issue by omlondhe** [EddieHubCommunity/LinkFree#6287]
## Bug creation:
1. Go to the link: [LinkFree Playground](https://linkfree.io/playground).
2. Add your username.
3. Add a blank JSON like this `{}`.
4. Click on the format JSON button.
5. Click on validate JSON button.
6. Click on the preview JSON button.

### Screenshots

https://user-images.githubusercontent.com/61611599/233778728-531d4448-c13e-48a2-8151-57bf33136a85.mov

**Comment by eddiejaoude** [comment]
Good spot! 👍 

I think here we can do some simple checks for the required fields

**Comment by omlondhe** [comment]
Hey @eddiejaoude , I have solved the bug! May I send you a PR for this one?
Assign me this issue please!

**Comment by eddiejaoude** [comment]
@omlondhe sure, I will assign it to you, but please also have a read of our contributing guide https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by omlondhe** [comment]
Yeah, sure @eddiejaoude !
