### ISSUE TITLE
[FEATURE] Add a link to your profile in the account tab

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/LinkFree#6306]
### Description

When I'm checking my statistics, I sometimes would like there's a link to go to your profile,
rather than having to go to your profile link manually. This would make it better to see your account as well, IMO.

Edit: add link to top of dashboard page to go to the user's profile page

**Comment by eddiejaoude** [comment]
Great idea, this is coming as part of the new nav changes when we have forms, but for now we could add a link at the top of the dashboard page to make it easier for people

**Comment by wrmacdonald** [comment]
I'd love to try taking this on!

**Comment by AJcodes42** [comment]
I would like to take this up.

**Comment by SaraJaoude** [comment]
> I'd love to try taking this on!

@wrmacdonald as you requested first after the label changed to `status: ready for dev` I will assign this to you
