### ISSUE TITLE
[FEATURE] adding transitions to buttons

### ISSUE THREAD

**Issue by HarshDeep61034** [EddieHubCommunity/LinkFree#6331]
### Description

I'm thinking if we could add transitions to the buttons it would look smother instead of instantly changing color
I added the recording of before & after below.

### Screenshots

Before: 
![2023-04-24 18-42-37](https://user-images.githubusercontent.com/121210012/234010412-fd05406b-2c65-4c73-93d1-e958d672f8b4.gif)

After: 
![2023-04-24 18-42-52](https://user-images.githubusercontent.com/121210012/234010478-b2aafbbf-7b94-49ad-b94b-b721fd82b458.gif)

**Comment by eddiejaoude** [comment]
Looks good @HarshDeep61034  👍 As it seems you have made the demo already I have assigned it to you
