### ISSUE TITLE
Screenshots on landing page need to be cropped

### ISSUE THREAD

**Issue by loftwah** [EddieHubCommunity/LinkFree#6333]
### Description

These two screenshots from the LinkFree landing page have some extra pixels on the right of the image that don't appear like they're meant to be there.

### Screenshots

![image](https://user-images.githubusercontent.com/19922556/234020820-3714a79c-4edf-4ed6-b39d-9355f738cc09.png)

![image](https://user-images.githubusercontent.com/19922556/234020952-d79a9cfa-28c6-4648-a842-f590b577660a.png)

### Additional information

These should be able to just be cropped and then used again.

**Comment by eddiejaoude** [comment]
Great idea 👍 we could probably also crop the navbar also, to reduce the vertical height

**Comment by beyonxd** [comment]
I've done this work already in my own projects, can you assign it to me ?

**Comment by beyonxd** [comment]
I'm really sorry for this PR mess, I will correct myself on this !

I think I've addressed the issue, you can checkout!
