### ISSUE TITLE
[DOCS]  add new linkfree domain link 

### ISSUE THREAD

**Issue by priyankarpal** [EddieHubCommunity/LinkFree#6341]
### Description

We need to add a new domain link in the https://linkfree.io/docs/environments/environment-variables

### Screenshots

![Screenshot from 2023-04-24 22-45-23](https://user-images.githubusercontent.com/88102392/234069383-ff452154-2f04-4160-9900-dd06e2c6541d.png)

**Comment by eddiejaoude** [comment]
Good spot, yes we need to update everything to the new dedicated url 👍
