### ISSUE TITLE
Change website meta description

### ISSUE THREAD

**Issue by Muhammed-Rahif** [EddieHubCommunity/LinkFree#635]
### Our website meta description is generated by create-react-app, it is still not changed :-
https://github.com/EddieHubCommunity/LinkFree/blob/d92c50dbe216a2e7aed0b73292088b65c79ffa66/public/index.html#L8-L11

### Screenshots

![Screenshot from 2021-11-02 18-23-07](https://user-images.githubusercontent.com/73386156/139855912-41456559-447d-4f00-945f-0480be697f77.png)

### Additional information

**_If you provide me a description, I can make a PR using that description to solve this issue now..._**

**Comment by Muhammed-Rahif** [comment]
> hey wave @Muhammed-Rahif are you working on this ?, if not then may i work on it ? slightly_smiling_face

I can work on this, but didn't started yet. I am waiting for response from maintainers...

**Comment by krishguptadev** [comment]
> > hey wave @Muhammed-Rahif are you working on this ?, if not then may i work on it ? slightly_smiling_face
> 
> I can work on this, but didn't started yet. I am waiting for response from maintainers...

You can start working :D Maintainers would see it soon!

**Comment by Muhammed-Rahif** [comment]
Then can you please suggest a description ?! or use the the github repo description (Open source alternative to LinkTree) ?

**Comment by Muhammed-Rahif** [comment]
@krishguptadev @TakshakRamteke take a look at #636
