### ISSUE TITLE
Stop postinstall script from overwriting .env

### ISSUE THREAD

**Issue by dan-mba** [EddieHubCommunity/LinkFree#6350]
### Description

The current postinstall script copies `.env.example` to `.env` on every npm install.

This causes problems for people who have setup the GitHub OAuth settings.

The posinstall script should not overwrite an existing `.env` file

**Comment by eddiejaoude** [comment]
I agree, this is a bit of a pain, I keep a backup of it - what are the options to solve this?

- check if the file exists then ignore?
- remove automation and developer has to do it manually when setting up the project?
- something else?

**Comment by dan-mba** [comment]
I think we can switch to using the [shx](https://github.com/shelljs/shx) package.

The command `shx cp -n ./.env.example ./.env` will copy only if the file doesn't exist.
But I would like to see it tested on Windows before saying that it will work there.

**Comment by yosr-fourati** [comment]
Can you assign this to me ?
@eddiejaoude
