### ISSUE TITLE
[DOCS] <Adding a new docs page specific for using Atlas>

### ISSUE THREAD

**Issue by Vee339** [EddieHubCommunity/LinkFree#6354]
### Description

Hello,

I was in the process of setting up LinkFree on my local system to make some changes to the CSS. However, I encountered an issue when I realized that MongoDB is required to run the project locally, whereas I am more familiar with MySQL. I believe there may be others who are also unfamiliar with MongoDB but are interested in contributing to LinkFree.

To make it easier for potential contributors, I suggest adding a step-by-step guide in the project documentation that provides instructions for installing MongoDB locally with Atlas, as it offers a free tier. This would be helpful in getting new contributors up and running quickly and enabling them to contribute to the project with ease.

Thank you for considering my suggestion.

Best,
Veerpal

**Comment by eddiejaoude** [comment]
Thank you for the suggestion, I think this would be a great addition to the docs 👍

**Comment by weilincheng** [comment]
Hello, I would like to contribute to this issue. My understanding is that MongoDB Atlas is a cloud-hosted MongoDB service. I'm wondering if this issue is looking to add a tutorial on how to set up Atlas specifically, or if the goal is to focus on installing the MongoDB community version locally. Could you provide some clarification on the desired outcome for this issue? Thank you.

**Comment by eddiejaoude** [comment]
Yes Atlas is free for the smallest option (I think M0). This documentation would be a new page in the LinkFree app docs written with mdx to help people get started with creating an account to getting their cloud mongo connection to ave the app running locally but the mongo db in the Atlas cloud

**Comment by eddiejaoude** [comment]
@weilincheng would you still like me to assign it to you?

**Comment by weilincheng** [comment]
Hi, Eddie. Thank you for the clarification. I appreciate it. I would be happy to work on this issue.

**Comment by eddiejaoude** [comment]
Great, I have assigned it to you 👍  any questions let us know

I think a new file (page) in here would make sense https://github.com/EddieHubCommunity/LinkFree/tree/main/pages/docs/environments maybe with the name `local-with-atlas.mdx`

**Comment by weilincheng** [comment]
Quick update: The new document is almost ready! I just need to make a few final adjustments. I'll submit a pull request in the next couple of days. Stay tuned! 😄

**Comment by eddiejaoude** [comment]
Great 👍  

Remember you can create a `draft` pull request sooner also

**Comment by weilincheng** [comment]
> Great 👍
> 
> Remember you can create a `draft` pull request sooner also

Thanks, Eddie. I just created a draft pull request for this issue. #6690 
Please let me know if you have any suggestions. 😃
