### ISSUE TITLE
[FEATURE] Limit pulse animation duration for Alert components

### ISSUE THREAD

**Issue by Ben-Ga** [EddieHubCommunity/LinkFree#6358]
### Description of feature
The alerts that pulse indefinetly can be negative to the user experience, especially when using dark mode or when using at night and the alert is flashing red for an extended period of time.

### Suggested approach
Extend the tailwind config to add a pulse of a limited duration (2-3 seconds?) for the Alert components used across the application.

A SO post that achieves a similar "finite" animation effect:

https://stackoverflow.com/questions/70552422/how-to-stop-tailwindcss-animation-after-a-set-time

### Screenshots

![image](https://user-images.githubusercontent.com/46089745/234397522-b7f23130-944a-4783-94e5-833627866f7d.png)

**Comment by eddiejaoude** [comment]
Thank you for the suggestion. It might be simpler to remove the animation. We might have a rebrand/redesign of the app, so for now I will close this.
