### ISSUE TITLE
Center Sign in with GitHub button alignment

### ISSUE THREAD

**Issue by Pradumnasaraf** [EddieHubCommunity/LinkFree#6397]
### Description

This is **Sign in with GitHub** window which pops after clicking the login button. The button is aligned in the center, there is extra padding on the bottom

### Screenshots

<img width="966" alt="Screenshot 2023-04-27 at 1 47 05 PM" src="https://user-images.githubusercontent.com/51878265/234802688-369e220b-f977-419f-b5c0-de450195a570.png">

<img width="1512" alt="Screenshot 2023-04-27 at 1 34 51 PM" src="https://user-images.githubusercontent.com/51878265/234801619-335e344d-4e23-47a4-aa39-1fcad383fb93.png">

**Comment by eddiejaoude** [comment]
Thanks Pradumna! There is a PR to have a custom login page https://github.com/EddieHubCommunity/LinkFree/pull/6016

**Comment by Pradumnasaraf** [comment]
> Thanks Pradumna! There is a PR to have a custom login page #6016

Wow. LinkFree is moving fast it's hard to track, haha.

**Comment by eddiejaoude** [comment]
lol yes! If this is the same, do you want to close as a duplicate or is it different?

**Comment by Pradumnasaraf** [comment]
I think we should keep it open until the issue you mentioned gets solved. This way, if someone else encounters the same problem, they can read our conversation. What do you think?

**Comment by eddiejaoude** [comment]
I think this might cause confusion, with 2 separate issues on the same PR. Maybe we should close this issue but reference it in the other issue, so we can continue the conversation in one place?

**Comment by Pradumnasaraf** [comment]
That sounds great, Eddie.

Closing this issue as it's a duplicate of #6016
