### ISSUE TITLE
buttons nested inside of links

### ISSUE THREAD

**Issue by emmalearnscode** [EddieHubCommunity/LinkFree#649]
### Description

The links to different social profiles are buttons wrapped inside of links which is not good semantically. Ideally they are just links and then they get styled according to the design. Alternatively they are buttons but given an aria role of link so that they are still accessible for screen readers.

### Screenshots

<img width="686" alt="Screenshot 2021-11-09 143146" src="https://user-images.githubusercontent.com/57045550/140934620-ef490efb-2188-4dad-bc75-6e2c0d108595.png">

**Comment by emmalearnscode** [comment]
No, the buttons don't appear to have an onclick handler currently

**Comment by krishguptadev** [comment]
> I can look into this, if no one else is.

For sure!
