### ISSUE TITLE
[IMPROVEMENTS] Implementing useRef hook in userDetails QR

### ISSUE THREAD

**Issue by shobhitexe** [EddieHubCommunity/LinkFree#6495]
### What would you like to share?

![image](https://user-images.githubusercontent.com/29349136/235291692-e5d03396-78bb-44c4-9088-9064769286d6.png)

I noticed that the userDetails.js component was using "document.querySelector" to target elements, which I believe is not the most convenient approach. Instead, I suggest using the "useRef" hook for this purpose. I have already made the necessary changes to the code. Please assign me ill be very happy to make a PR ....Thanks 

### Additional information

No

**Comment by eddiejaoude** [comment]
I don't think they are the same so I will close, but I will unlock for discussion

> useRef is a React Hook that lets you reference a value that’s not needed for rendering.

https://react.dev/reference/react/useRef

> The [Document](https://developer.mozilla.org/en-US/docs/Web/API/Document) method querySelector() returns the first [Element](https://developer.mozilla.org/en-US/docs/Web/API/Element) within the document that matches the specified selector, or group of selectors

https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector

**Comment by shobhitexe** [comment]
I believe that both "document.getElementById" and "useRef" serve the same purpose, but when working with React or Next, I would prefer to use the useRef() hook.

 **This hook is specifically designed to create a reference to a DOM node or store a mutable value that remains persistent through re-renders in React.**
 
 useRef got many advantages like:

Performance: useRef() is more performant than document.getElementById(). When you use document.getElementById(), the browser has to search the entire document to find the element, whereas useRef() only needs to be called once and creates a reference to the element.

Better integration with React: useRef() is specifically designed for use with React, whereas document.getElementById() is a standard JavaScript function that is not optimized for use with React. By using useRef(), you can take advantage of the React lifecycle methods and avoid potential issues with updating the DOM manually.

More flexible: useRef() can be used to store a mutable value that persists across re-renders. This can be useful in situations where you need to maintain state within a component but don't want to trigger a re-render every time the state changes.

Easier to read and write: useRef() is a React hook, so it follows the same syntax as other hooks in React. This makes it easier to read and write code, especially if you are already familiar with React.

**Comment by shobhitexe** [comment]
![image](https://user-images.githubusercontent.com/29349136/235302898-557881a1-c68e-45c5-9025-e70a76c1d376.png)
![image](https://user-images.githubusercontent.com/29349136/235302911-9f69f22f-f5fb-446b-9c3e-80055fda1daf.png)

**Comment by eddiejaoude** [comment]
> I have already made the necessary changes to the code

Hmm interesting, thank you for elaborating. Could you share your code example please?

**Comment by shobhitexe** [comment]
Yes Sure!
Here's code snippets with comments

![image](https://user-images.githubusercontent.com/29349136/235306580-5d62a2ff-d67f-4491-b0bd-71a2d91e6bf6.png)
![image](https://user-images.githubusercontent.com/29349136/235306590-1c32dba5-c837-41aa-b130-7a2eba8f44d7.png)
![image](https://user-images.githubusercontent.com/29349136/235306597-7e1fc200-0cb0-4569-b439-29e0b3c23cc9.png)

A short recorded video

https://user-images.githubusercontent.com/29349136/235306711-ba3e652c-263d-4eaf-a820-77a05d232dd1.mp4

**Comment by shobhitexe** [comment]
Hello!


> Yes Sure! Here's code snippets with comments
> 
> ![image](https://user-images.githubusercontent.com/29349136/235306580-5d62a2ff-d67f-4491-b0bd-71a2d91e6bf6.png) ![image](https://user-images.githubusercontent.com/29349136/235306590-1c32dba5-c837-41aa-b130-7a2eba8f44d7.png) ![image](https://user-images.githubusercontent.com/29349136/235306597-7e1fc200-0cb0-4569-b439-29e0b3c23cc9.png)
> 
> A short recorded video
> 
>  2023-04-29.19-27-58.mp4

Hello!

**Comment by shobhitexe** [comment]
> Yes Sure! Here's code snippets with comments
> 
> ![image](https://user-images.githubusercontent.com/29349136/235306580-5d62a2ff-d67f-4491-b0bd-71a2d91e6bf6.png) ![image](https://user-images.githubusercontent.com/29349136/235306590-1c32dba5-c837-41aa-b130-7a2eba8f44d7.png) ![image](https://user-images.githubusercontent.com/29349136/235306597-7e1fc200-0cb0-4569-b439-29e0b3c23cc9.png)
> 
> A short recorded video
> 
>  2023-04-29.19-27-58.mp4

Hello is anyone here!!

**Comment by eddiejaoude** [comment]
> Hello is anyone here!!

Thank you for the explanation 👍 . Yes we are here, but please be patient we get many notifications.

I will assign this issue to you @shobhitexe

**Comment by shobhitexe** [comment]
Thanks for your reply you are too humble ❤️

**Comment by shobhitexe** [comment]
> > Hello is anyone here!!
> 
> Thank you for the explanation 👍 . Yes we are here, but please be patient we get many notifications.
> 
> I will assign this issue to you @shobhitexe

Thanks for your reply you are too humble ❤️
