### ISSUE TITLE
[UI/UX] Fix the user guide cards

### ISSUE THREAD

**Issue by thehashmap** [EddieHubCommunity/LinkFree#6505]
### Description

There seems to be an issue with the Link tag assignment in the Getting Started section on the homepage. Currently, the Link tag is only active in a specific region of the cards, as highlighted in the screenshot below, which appears unusual to me.

### Screenshots

![user-guide](https://user-images.githubusercontent.com/76116523/235307325-027413fb-5608-4c1b-b4fc-e7f8df242c29.png)

https://user-images.githubusercontent.com/76116523/235307347-f4ed3350-c728-4196-82a8-a1de2e572897.mp4

### Additional information

I suggest one of the below ways:

![image](https://user-images.githubusercontent.com/76116523/235307577-0083521f-7af7-45a1-b909-6c9151fd6807.png)
 OR
![image](https://user-images.githubusercontent.com/76116523/235307523-7df11059-dd75-47ce-87af-6703170a08a8.png)

What do you think?

**Comment by SaraJaoude** [comment]
@thehashmap thank you for the suggestion but as we are in the process of redesigning the website this will be addressed at that stage, so I will close this PR for now.
