### ISSUE TITLE
[bug]: Date not visible when hovering on stats graph in dark mode

### ISSUE THREAD

**Issue by NiazMorshed2007** [EddieHubCommunity/LinkFree#6532]
### Description

Steps to reproduce:

1. Go to `https://linkfree.io/account/statistics`
2. Scroll down to profile views section
3. Make sure you're on dark mode
4. Hover over on a day, you'll see something like this 👇
![image](https://user-images.githubusercontent.com/77217706/235392571-a47daed8-e0c6-4eec-a463-f9510854b642.png)

### Screenshots

But on light it works fine. Screenshot:
![image](https://user-images.githubusercontent.com/77217706/235392617-a9ec2934-94df-4d4d-98f0-77bbc59f7449.png)

### Additional information

Let me know about this issue. I'll make quick pr for this

**Comment by eddiejaoude** [comment]
Great spot!! I have assigned it to you, thank you 👍
