### ISSUE TITLE
[FEATURE] add progress bar on top

### ISSUE THREAD

**Issue by badrivlog** [EddieHubCommunity/LinkFree#6545]
### Description

I have a suggestion,

When navigating to a different route in our LinkFree web application, there is currently no visual indication that the page is loading. This can be confusing for users who may think that the application is not working or responding. To improve the user experience, i would like to add a progress bar at the top of the page that shows the loading progress when navigating to a different route.

The progress bar should appear at the top of the page as soon as the user clicks on a link or button that navigates to a different route. It should remain visible until the new page is fully loaded. The progress bar should provide visual feedback to the user on the loading progress, such as a percentage or a loading animation. I will be happy to work on this feature, what you think about my idea.

### Screenshots

https://user-images.githubusercontent.com/73095526/235506626-6cd83814-8318-4b02-afc4-560f24ae967d.mp4

**Comment by eddiejaoude** [comment]
Thank you for the suggestion 👍 

A few issues have been raised on this topic already and here are our thoughts..

- As we move to using the database, the app should improve performance https://github.com/EddieHubCommunity/LinkFree/issues/6244
- Also when we upgrade to the latest version of NextJS we get features like this more easily (need to merge open PRs)

We will revisit this after the above 2 steps are complete.
