### ISSUE TITLE
[IMPROVEMENTS] remove unnecessary useState 

### ISSUE THREAD

**Issue by badrivlog** [EddieHubCommunity/LinkFree#6559]
### Description

we can see `events` components on line 87 of the component use `tabs` state variable to contains `filters` data, but never call `setTabs` state update function.

**In general,**  if we are using state to manage some aspect of our component's behavior, we should use the setter function returned by useState to update the state value as needed. If we find that we don't need to update the state value, we may want to consider whether we really need state at all, or if we can use a different mechanism to manage the behavior of our component.

**Path**
`pages/events.js`
**Github UI** [here](https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/events.js)
![Screenshot (10)](https://user-images.githubusercontent.com/73095526/235589841-86ad9744-8b01-4071-96e7-857ae1c37ed3.png)

 

### Proposed Changes

instead of state variable we should use normal variable to contains that `filters` data

**Comment by eddiejaoude** [comment]
Good spot 👍 yes we could probably use a standard variable for it

**Comment by omlondhe** [comment]
Can you assign me this issue, please?

**Comment by badrivlog** [comment]
I will be happy to work on this issue

**Comment by Amitpawar88** [comment]
I would like to work on this issue. Can I be assigned to it?

**Comment by geeky-sambhav** [comment]
I would like to work on this issue

**Comment by SaraJaoude** [comment]
> Can you assign me this issue, please?

@omlondhe as you were the first to request this Issue when the labels changed to `status: ready for dev` I will assign this to you
