### ISSUE TITLE
JavaScript tag is shown 2 times in Search page

### ISSUE THREAD

**Issue by Vee339** [EddieHubCommunity/LinkFree#6568]
### Description

On the search page, the tag for JavaScript is shown twice. Even when the user selects both tags, "JavaScript" is written two times in the search bar.

### Screenshots

![linkfree-tags](https://user-images.githubusercontent.com/81091817/235717329-18a6f71c-9e01-41c1-9806-e0af1cf1a335.png)

**Comment by omlondhe** [comment]
Can you assign me this issue, please?

**Comment by eddiejaoude** [comment]
There is an old issue, I will close this as it is a duplicate of https://github.com/EddieHubCommunity/LinkFree/issues/4676
