### ISSUE TITLE
[other] Improve color contrast for text in dark mode

### ISSUE THREAD

**Issue by Saurabh-Singh02** [EddieHubCommunity/LinkFree#6572]
### What would you like to share?

![Screenshot (469)](https://user-images.githubusercontent.com/122091208/235752831-0f9711d1-38ee-4484-ab61-622426684d0b.png)

![Screenshot (462)](https://user-images.githubusercontent.com/122091208/235742486-78416fd5-07c7-4579-b442-01f76fd3ad09.png)

![Screenshot (463)](https://user-images.githubusercontent.com/122091208/235742491-c4613d71-a19e-4dfd-bc44-91732439c1e6.png)

I found an accessibility while using dark mode of linkfree.io/docs.
As the color contrast ratio of foreground color[ rgb(121, 129, 140)]=(hex value= #79818c) to background color(#111827) is found 4.5:1 that do not meet criteria as required.
According to WCAG AAA, the color contrast ratio is equal to or more than 7:1.
I putted some screenshots  of the website and contrast ratio of that color.
My suggestion is to change rgb(121, 129, 140) to #BDC0C7 color.
This color gives color contrast ratio = 9.73:1. And it is acceptable according to WCAG AAA.
 
![Screenshot (467)](https://user-images.githubusercontent.com/122091208/235747378-7e29739e-906d-4e62-821a-c587aa263356.png)

![Screenshot (468)](https://user-images.githubusercontent.com/122091208/235747383-24b4cd9e-938c-48a1-9dd7-392258654119.png)

I want to work on this issue please assign it to me.

Thank you.

**Comment by amandamartin-dev** [comment]
Hello! Thank you for bringing this up.  This issue is throughout the site in dark mode and not only on the docs page, so ideally there will be a solution that will adjust that contrast ratio throughout.

**Comment by ChinmayMhatre** [comment]
> The colours for Light Mode and Dark Mode are globally managed in the `tailwind.config.js` - hopefully it can be tweaked from here

That's right those colour are part of the `primary` variable can be tweaked according to the accessibility requirements

**Comment by dan-mba** [comment]
According to @EmmaDawsonDev WCAG AAA is for Government sites and those requiring maximum accessibility by legal statute only. Most businesses & personal sites need only meet the AA standard.

Trying to meet AAA will mean redoing the colors for most of the site in both light & dark mode.
We currently test for AA color contrast.
Current testing level
["wcag2a", "wcag2aa", "wcag21a", "wcag21aa"]
Proposed testing level
['wcag2a', 'wcag2aa', 'wcag2aaa', 'wcag21a', 'wcag21aa', 'wcag21aaa']

Migrating to AAA will require significant effort & a possible complete color scheme redesign.

**Comment by amandamartin-dev** [comment]
That's a really good point @dan-mba . I wasn't aware which level we were shooting for. It looks like this issue isn't needed.

**Comment by eddiejaoude** [comment]
Thanks everyone for the great collaboration 👍 as mentioned above this issue is no longer needed, so I will close.
