### ISSUE TITLE
[BUG] Two React buttons in search: clicking one doesn't select both

### ISSUE THREAD

**Issue by geeky-sambhav** [EddieHubCommunity/LinkFree#6573]
### Description

When using the search feature, there are two React buttons present. However, when clicking on one of the buttons, it does not automatically select both buttons as expected unlike the javascript button

### **Expected behavior:**
Both React buttons should be selected when either one is clicked.

![image](https://user-images.githubusercontent.com/83087385/235762675-7934fd30-38f1-41a3-8a0d-bc0c5cf1eb55.png)

### **Actual Behaviour**
Only the clicked button is selected, while the other remains unselected.

![image](https://user-images.githubusercontent.com/83087385/235762846-b35a98c1-aa7f-43e5-a4d5-cb53390232ec.png)

**Comment by eddiejaoude** [comment]
There is an existing issue, I will close this as it is a duplicate of https://github.com/EddieHubCommunity/LinkFree/issues/4676
