### ISSUE TITLE
Userlink Github icon not visible correctly when dark mode is on

### ISSUE THREAD

**Issue by badrivlog** [EddieHubCommunity/LinkFree#6579]
### Description

when dark mode is on userlink Github icon not visible correctly. I am curious if this an intentional design choice or if it a bug. If it is a bug, i want to work on this, please assign me on this issue

### Screenshots

![Screenshot (12)_LI](https://user-images.githubusercontent.com/73095526/235844285-d3d86b31-fbff-4552-8e99-5f64756cb28e.jpg)

**Comment by eddiejaoude** [comment]
Good spot, we could change it to white as GitHub has a white logo as part of their assets, so it is allowed usage https://github.com/logos 

I think we have a config file for icon colours for the links, we might need to improve this config to cover dark mode?

**Comment by omlondhe** [comment]
Can you assign me this issue, I have an idea to fix this one with some basic UI changes.

**Comment by eddiejaoude** [comment]
> Can you assign me this issue, I have an idea to fix this one with some basic UI changes.

@omlondhe thank you for your enthusiasm, but please read the [contributing guidelines](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) as already mentioned to you [here](https://github.com/EddieHubCommunity/LinkFree/issues/6287#issuecomment-1518654043) 2 weeks ago to avoid extra work and confusion for everyone!  (note: you already have 1 open issue assigned to you, and this issue is not `ready for dev`)

**Comment by omlondhe** [comment]
> > Can you assign me this issue, I have an idea to fix this one with some basic UI changes.
> 
> @omlondhe thank you for your enthusiasm, but please read the [contributing guidelines](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) as already mentioned to you [here](https://github.com/EddieHubCommunity/LinkFree/issues/6287#issuecomment-1518654043) 2 weeks ago to avoid extra work and confusion for everyone! (note: you already have 1 open issue assigned to you, and this issue is not `ready for dev`)

Got it! Thank you for your response!

**Comment by yoyoekta** [comment]
> I think we have a config file for icon colors for the links, we might need to improve this config to cover dark mode?

Yes, we just need to remove custom color of the icon. Default icon is working fine on both light and dark theme.

**Comment by yoyoekta** [comment]
> I think we have a config file for icon colors for the links, we might need to improve this config to cover dark mode?

Yes, we just need to remove custom color of the icon. Default icon is working fine on both light and dark theme.

**Comment by Snach13** [comment]
> Good spot, we could change it to white as GitHub has a white logo as part of their assets, so it is allowed usage https://github.com/logos
> 
> I think we have a config file for icon colours for the links, we might need to improve this config to cover dark mode?

@eddiejaoude I was thinking the same just turn that logo into white let me work on this issue

**Comment by eddiejaoude** [comment]
Oh that sounds like a great solution @yoyoekta nice and simple, I like it 👍 

@yoyoekta as you came up with the solution would you like me to assign it to you?

@Snach13 it wasn't `ready for dev` when you made your comment, please familiarise yourself with our [contributing guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) to reduce noise and confusion

**Comment by yoyoekta** [comment]
> @yoyoekta as you came up with the solution would you like me to assign it to you?
Sure! Thanks.

**Comment by geeky-sambhav** [comment]
I would like to contribute

**Comment by badrivlog** [comment]
> Oh that sounds like a great solution @yoyoekta nice and simple, I like it 👍 
> 
> @yoyoekta as you came up with the solution would you like me to assign it to you?
> 
> @Snach13 it wasn't `ready for dev` when you made your comment, please familiarise yourself with our [contributing guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) to reduce noise and confusion

Hey@eddiejaoude , According to Github logo and Usage guidelines, using black and white github logo can be a good option if we need a simplified version of the logo. Would love to fix this issue.

**Comment by badrivlog** [comment]
Hey@eddiejaoude according to Github logo and Usage guidelines, using black and white github logo can be a good option if we need a simplified version of the logo. Would love to fix this issue.

**Comment by eddiejaoude** [comment]
@yoyoekta I have assigned it to you

@geeky-sambhav please read the messages above yours

@badrivlog sorry you did request to work on it in the issue description, I will assign another issue to you - let me know
