### ISSUE TITLE
[FEATURE] Add hover effect to search button

### ISSUE THREAD

**Issue by tanishagupta1** [EddieHubCommunity/LinkFree#658]
### Description

Currently, the cursor when hovered at the search button shows default arrow-pointer, we can change that to hand-pointer and  add color highlighting to the button.

**Comment by Palaksharma23** [comment]
@tanishagupta1 are you working on this issue ? 
Can I take up this issue , I would love to work on it.

**Comment by tanishagupta1** [comment]
> @tanishagupta1 are you working on this issue ? Can I take up this issue , I would love to work on it.

Hey I am working on this issue

**Comment by emmalearnscode** [comment]
Cursor is accessible as it is. Closing this issue.
