### ISSUE TITLE
[FEATURE] update releases to work with protected branches

### ISSUE THREAD

**Issue by Sfitzg** [EddieHubCommunity/LinkFree#659]
### Description

Hello @eddiejaoude 

The current workflow for releases doesn't work with protected branches that require pull requests or branches that require status checks to pass before merging because the standard  `GITHUB_TOKEN` does not give admin access which is required to push to protected branches.

I have a workflow that will allow pushing to protected branches, it requires a Personal Access Token with admin rights to be set as a github secret to be able to achieve this. 
the workflow also checks if the `INCLUDE ADMINS` setting is set before doing the push and will temporarily disable `INCLUDE ADMINS` make the git push and then re enable `INCLUDE ADMINS`  if it was previously set.

I have setup the workflow in such a way that if the personal access token is not supplied in the github secrets it will revert to just using the previous workflow using the `GITHUB_TOKEN` therefore this workflow should work as before if the branch is not protected and admin token not supplied.

I would like to update the `releases.yml` to use this workflow!!

**Comment by stemount** [comment]
@Sfitzg I'm fascinated about what made you raise this issue, what does this stop you doing?

Some related info:
https://github.community/t/best-practices-for-protected-branches/10204

If it is to release, then you can override these in your `repository settings > environments` and provide the needed environment variables.

![smscreenshot 2021-11-16 at 01 47 04@2x](https://user-images.githubusercontent.com/150512/141880917-fde868b7-1af2-48f3-96d2-37e386123577.png)

**Comment by Sfitzg** [comment]
The only real difference is that the workflow disables the includes admins checkbox and then re-enables it after the commit is pushed as I had a really hard time dealing with this and I figured that people could benefit from the updated workflow.

but I'm going to close this issue as you are correct this is not needed in this repo.

**Comment by stemount** [comment]
@Sfitzg thanks for the explanation, I get it, I think this only applies when you actually do need to force push branches or straight to the main repository.

GItHub doesn't *really* support this but certainly can have environment-based (testing, prod, et al) secrets that Jinja (?) uses with `{{ secrets.blah }}`
