### ISSUE TITLE
[OTHER] Changelog page to have basic tests

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#6600]
### What would you like to share?

It would be good to have a basic **test** for the Changelog page, similar to the event page test `tests/events.spec.js`, that checks the page loads without any errors

### Additional information

```js
// @ts-check
import { test, expect } from "@playwright/test";
const AxeBuilder = require("@axe-core/playwright").default;

test("Click on events profile in navbar navigates to events page", async ({
  page,
}) => {
  await page.goto("/");
  await page.getByRole("link", { name: 'Events', exact: true }).click();
  await expect(page).toHaveURL("/events");
});

test.fixme("Events listed", async ({ page }) => {
  await page.goto("/events");
  await expect(page.locator("li")).toBeGreaterThan(1);
});

test.describe("accessibility tests (light)", () => {
  test.use({ colorScheme: 'light' });

  test("should pass axe wcag accessibility tests", async ({ page }) => {
    await page.goto("/events");
    const accessibilityScanResults = await new AxeBuilder({ page })
      .withTags(["wcag2a", "wcag2aa", "wcag21a", "wcag21aa"])
      .analyze();
    expect(accessibilityScanResults.violations).toEqual([]);
  });
});

test.describe("accessibility tests (dark)", () => {
  test.use({ colorScheme: 'dark' });
  
  test("should pass axe wcag accessibility tests (dark)", async ({ page }) => {
    await page.goto("/events");
    const accessibilityScanResults = await new AxeBuilder({ page })
      .withTags(["wcag2a", "wcag2aa", "wcag21a", "wcag21aa"])
      .analyze();
    expect(accessibilityScanResults.violations).toEqual([]);
  });
});
```

**Comment by sansarmaske** [comment]
Hey Eddie, I would love to work on this if someone else is not assigned yet.

**Comment by eddiejaoude** [comment]
Sure @sansarmaske I have assigned it to you

**Comment by SaraJaoude** [comment]
> Sure @sansarmaske I have assigned it to you

I cannot see that there has been any activity on this and since it has been two weeks I will unassign.

**Comment by sansarmaske** [comment]
Hi Sara, I am really sorry for not being able to work on this in past couple of weeks as I had to travel to attend urgent business but I am just back home today morning.

**Comment by Vishrut19** [comment]
Hey! Since this issue is unassigned and also previously I have worked on writing tests. So, I am pretty confident to work on this issue.

**Comment by SaraJaoude** [comment]
> Hi Sara, I am really sorry for being unable to work on this in the past couple of weeks as I had to travel to attend to urgent business. I am just back home today morning. Shall I work on the PR for this now?

@sansarmaske we understand that our contributors have other commitments and in future please feel free to let us know if you will not have availability to work on an assigned issue for an extended period of time - as this will allow maintainers to better manage the project. As it has been some time we will give someone else in the community a chance to contribute.

**Comment by SaraJaoude** [comment]
> Hey! Since this issue is unassigned and also previously I have worked on writing tests. So, I am pretty confident to work on this issue.

@Vishrut19 I have assigned this to you.

**Comment by sansarmaske** [comment]
> > Hi Sara, I am really sorry for being unable to work on this in the past couple of weeks as I had to travel to attend to urgent business. I am just back home today morning. Shall I work on the PR for this now?
> 
> 
> 
> @sansarmaske we understand that our contributors have other commitments and in future please feel free to let us know if you will not have availability to work on an assigned issue for an extended period of time - as this will allow maintainers to better manage the project. As it has been some time we will give someone else in the community a chance to contribute.

Sure, I will keep that in mind. 🙂

**Comment by SaraJaoude** [comment]
@Vishrut19 how are you getting on with raising a PR for this Issue?

**Comment by Vishrut19** [comment]
I am working on it. Please give me a day or two I will raise a PR. I was busy with some other work @SaraJaoude

**Comment by Vishrut19** [comment]
PR raised
