### ISSUE TITLE
[BUG] setState() is not get correct value

### ISSUE THREAD

**Issue by badrivlog** [EddieHubCommunity/LinkFree#6609]
**update: code is no longer required and can be removed**

### Description

I found an issue in [components/user/UserLink.js](https://github.com/EddieHubCommunity/LinkFree/blob/main/components/user/UserLink.js) line number 29. Here we update state based on previous state, but current implementation of `setState()` is not correct. 
**Because**,
Whenever we update state and that depend on the previous state, for example, as we do it here [components/user/UserLink.js](https://github.com/EddieHubCommunity/LinkFree/blob/main/components/user/UserLink.js) line number 29. We should not do it like this but we should use an alternative form of this state updating function.

![Screenshot (14)](https://user-images.githubusercontent.com/73095526/236171606-1f7d8466-a4a6-4ad3-9b09-3d833ccff265.png)

### Why we shouldn't do it like this?
In many cases it will work fine, but according to React docs, React schedules state updates, it doesn't perform them instantly. And therefore, theoretically, if we schedule a lot of state updates at a same time, we could be depending on outdated or incorrect state snapshot if we use this approach.

### Additional information

Would love fix this if this a valid issue.
Thanks

**Comment by eddiejaoude** [comment]
Good spot, but I think that code is no longer required, as the clicks are not longer displayed on the profile page and if I remember correctly this was added just to reduce the extra call to the API to get the latest click statistics for that link.

So basically this code can now be removed.

**Comment by badrivlog** [comment]
hey @eddiejaoude, here it might not concern

> Good spot, but I think that code is no longer required, as the clicks are not longer displayed on the profile page and if I remember correctly this was added just to reduce the extra call to the API to get the latest click statistics for that link.
> 
> So basically this code can now be removed.
> 
> I have assigned it to you @badrivlog

thank you for giving me a chance to contribute
