### ISSUE TITLE
[FEATURE] Homepage alert/notice to make users aware of important information

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#6622]
### Description

- We have an existing alert component, could this be used `components/Alert.js`
- Load app notifications from `config/app.json` (multiple, so loop over them)
- Display on the homepage only

**json example**
```js
{
   // ...
   "alerts": [
      {
         "type": "warning",
         "message": "... ..."
      }
   ]
}
```

**Comment by NiazMorshed2007** [comment]
I can give it a shot...

**Comment by Soyeb01** [comment]
Can you please assign me this issue .

**Comment by omlondhe** [comment]
May I go ahead with this issue?

**Comment by vaibhav-xt** [comment]
I am happy to work on this issue. please assign it to me.

**Comment by SaraJaoude** [comment]
> I can give it a shot...

@NiazMorshed2007 I have assigned this to you as you were the first to request here in this Issue.
