### ISSUE TITLE
[FEATURE] UserTabs component can utilize full width

### ISSUE THREAD

**Issue by Nanak360** [EddieHubCommunity/LinkFree#6628]
## Description
The usertab component utilizes only 1/4th of the section's width. This results in the tabs always staying at the left.
In cases when we have two or three tabs, making them take the full width might look better.

This is how the tabs look right now
<img width="1266" alt="Screenshot 2023-05-04 at 10 14 38 PM" src="https://user-images.githubusercontent.com/36790357/236525561-c262f139-ffa0-4381-a932-0388ec80af9b.png">

### one tab
this does not look that good
<img width="1266" alt="Screenshot 2023-05-05 at 11 15 16 PM" src="https://user-images.githubusercontent.com/36790357/236531608-665f2ce4-e674-4486-812e-27b7efc5f6c3.png">

### two tabs
<img width="1266" alt="Screenshot 2023-05-04 at 10 15 30 PM" src="https://user-images.githubusercontent.com/36790357/236525510-3d76c8f5-5b74-487e-94f3-d4b9645992e7.png">

### three tabs
<img width="1266" alt="Screenshot 2023-05-05 at 11 13 50 PM" src="https://user-images.githubusercontent.com/36790357/236531399-4a077fdd-eb75-4795-a6d1-ec5b303beebe.png">

**Comment by ChinmayMhatre** [comment]
@eddiejaoude views on this?

**Comment by eddiejaoude** [comment]
Thank you Nanak for the suggestion and Chinmay for the reminder 👍  I am not a designer, but the original design is from the paid Tailwind components - personally I prefer the original design as it doesn't change and has more consistency

Also we are planning on have a new redesign in a few months, so I might close this for now, sorry Nanak
