### ISSUE TITLE
Less margin/padding on mobile screens to maximize screen area

### ISSUE THREAD

**Issue by emmalearnscode** [EddieHubCommunity/LinkFree#664]
### Description

There is a lot of padding round the links and cards on user profile page on mobile. This should be reduced to make better use of the space and means less text will be cutoff from the links

### Screenshots

<img width="161" alt="Screenshot 2021-11-14 114724" src="https://user-images.githubusercontent.com/57045550/141677920-68988af9-18e3-4a01-94df-319f09a20418.png">
<img width="161" alt="Screenshot 2021-11-14 114741" src="https://user-images.githubusercontent.com/57045550/141677921-0dc76391-d050-4642-8032-5ae838b7d4af.png">

**Comment by AbhinavMV** [comment]
Can i work on this?
