### ISSUE TITLE
[IMPROVEMENT] Update all Node.js versions

### ISSUE THREAD

**Issue by sarthakroy2002** [EddieHubCommunity/LinkFree#6649]
### What would you like to share?

Node.js 16 (LTS) will go End-of-Life in September 2023. So its better to update it to the latest Node version, 20. Also, Node.js 20 will enter long-term support (LTS) in October 2023.

**Comment by eddiejaoude** [comment]
Areas that need updating?

- Gitpod
- Docker
- NVM
...?

**Comment by sarthakroy2002** [comment]
So i will check all dependencies and update all at once. Assign it to me

**Comment by eddiejaoude** [comment]
Yes but the issue needs to list the changes first before it can be marked as ready for dev and assigned

**Comment by munnokd** [comment]
Hey @SaraJaoude can you assign this issue to me?

**Comment by eddiejaoude** [comment]
@munnokd I have assigned it to you - btw you don't need to tag maintainers, we all get the notification and can assign issues 🤓

**Comment by SaraJaoude** [comment]
@munnokd how are you getting on?

**Comment by munnokd** [comment]
I will finish this issue in the next 2 or 3 days.

**Comment by munnokd** [comment]
Hey, I have one doubt, that is I need to change all dependencies to update to the latest versions present in the package.json? Please help me on this issue.

**Comment by eddiejaoude** [comment]
> Hey, I have one doubt, that is I need to change all dependencies to update to the latest versions present in the package.json? Please help me on this issue.

What help do you need?

**Comment by munnokd** [comment]
Thank you for your response, Now I understand what I need to do in this issue 😊.

**Comment by SaraJaoude** [comment]
@munnokd when do you expect to raise a PR for this Issue?  Please do let us know if you need any help wit this.  We are conscious that this was assigned to you two weeks ago and if no progress is made we will need to assign it.  It is perfectly fine if you do not have the time to work on this now, but we cannot block other contributors from the chance of working on this.

**Comment by munnokd** [comment]
Sorry @SaraJaoude for delay, Because I am busy in my some exam related works in college so unable to complete this issue so you can assign this issue to other person.

**Comment by Hs809** [comment]
@SaraJaoude While reviewing the package.json file for Link Free, I noticed that the project is currently utilizing Node 18.
Can you tell me if there are any other places to look out? If not then we can close this ticket

**Comment by eddiejaoude** [comment]
> @SaraJaoude While reviewing the package.json file for Link Free, I noticed that the project is currently utilizing Node 18.
> Can you tell me if there are any other places to look out? If not then we can close this ticket

Thank you for checking, yes we will need to update other places also, for example
- docker(s) + docker compose
- gitpod
and maybe somewhere else?

**Comment by Hs809** [comment]
I checked the Docker file and .gitpod.Dockerfile they both have node 18.  I didn't find any place where we use node 16. 
If there is any place can you specify it?

**Comment by eddiejaoude** [comment]
I did a search and noticed...

- In the documentation it refers to `16`
   - `README.md`
   - `pages/docs/environments/local-development.mdx`

**Comment by Hs809** [comment]
Yeah. Found it. I thought we only need to update the node package not in the documentation. Sorry for that. 
can you assign this ticket to me?

**Comment by eddiejaoude** [comment]
Sure, assigned to you @Hs809

**Comment by Hs809** [comment]
@eddiejaoude should I add version 18.16.1 to the files?

**Comment by Hs809** [comment]
Created the PR for this issue https://github.com/EddieHubCommunity/LinkFree/pull/7749. If I need to change the Node version to 19 or 20 please let me know. 

Thank you all for helping me out

**Comment by eddiejaoude** [comment]
Thank you, I see the PR, I will update your PR description to include the issue number to link it to this issue
