### ISSUE TITLE
Card text needs consistent alignment on mobile

### ISSUE THREAD

**Issue by emmalearnscode** [EddieHubCommunity/LinkFree#665]
### Description

On desktop the cards on the user profile page alternate between left and right aligned. On mobile all the cards are center aligned but their text is still left/right aligned which looks inconsistent. They should all have the same text alignment on mobile.

### Screenshots

<img width="287" alt="Screenshot 2021-11-14 114849" src="https://user-images.githubusercontent.com/57045550/141677984-232c2b9f-7a4d-41f2-982f-2230f401c667.png">

**Comment by AbhinavMV** [comment]
Can i work on this issue?

**Comment by mohan-murali** [comment]
> Can i work on this issue?

Go ahead.
