### ISSUE TITLE
[OTHER] Can use default values for props instead of if statement

### ISSUE THREAD

**Issue by badrivlog** [EddieHubCommunity/LinkFree#6657]
### What would you like to share?

It would be great to use default values for props instead of if statement in [components/PageHead.js](https://github.com/EddieHubCommunity/LinkFree/blob/main/components/PageHead.js) 

By using default values for props, we can write cleaner, more concise code that is easier to maintain and understand.

### Additional information

Would love to work on this.

Thanks

**Comment by eddiejaoude** [comment]
Good idea @badrivlog , I have assigned it to you 👍
