### ISSUE TITLE
Add Default Profile Image

### ISSUE THREAD

**Issue by AbhinavMV** [EddieHubCommunity/LinkFree#667]
### Description

If an image is not visible we can show a default image with Initial character from name (eg: Like it is shown on gmail)

### Screenshots

![image](https://user-images.githubusercontent.com/35369843/141697187-bfc15093-1a8c-4b0e-90c1-babe59bf32f9.png)
![image](https://user-images.githubusercontent.com/35369843/141697241-a6bef51c-f150-458b-af3b-7915ddaaac79.png)

**Comment by PritamReddy101** [comment]
I would love to give this a try! Can i work on this issue?

**Comment by emmalearnscode** [comment]
Since the avatar is right next to the name I don’t think that initials are necessary. A default profile icon should suffice for all missing profile images.

**Comment by harshrai654** [comment]
> I would love to give this a try! Can i work on this issue?

Are you working on this issue?

**Comment by PritamReddy101** [comment]
No I'm not, Sorry. Could you please assign this issue to someone else.

**Comment by emmalearnscode** [comment]
Thanks for letting us know @PritamReddy101 . Do you want it assigned to you @harshrai654  ?

**Comment by harshrai654** [comment]
> Thanks for letting us know @PritamReddy101 . Do you want it assigned to you @harshrai654  ?

Yeah sure.

**Comment by harshrai654** [comment]
@emmalearnscode can you review the changes.
