### ISSUE TITLE
[DOCS] LinkFree profile tips

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#6684]
### Description

It would be great to have a docs page with some tips for people's profiles

For example:
- Links to be grouped
   - YouTube link to have the subscribe flag, so when they visit the YouTube channel it asks them if they want to subscribe
   - Twitter has a similar feature as suggested by @loftwah https://twitter.com/intent/follow?screen_name=loftwah
- Achieved milestones and add future milestones for accountability
- Events
- Testimonials
   - ask on socials for people to give you a testimonial on LinkFree

This docs page can start small and be iterated on.

**Comment by geeky-sambhav** [comment]
I would like to contribute on this issue

**Comment by SaraJaoude** [comment]
> I would like to contribute on this issue

@geeky-sambhav I will assign this to you

**Comment by loftwah** [comment]
GitHub Achievements can be added to your profile in this same style.

https://github.com/loftwah?tab=achievements is the page for all of your achievements, or you can have one that goes to a specific achievement. https://github.com/loftwah?tab=achievements&achievement=pair-extraordinaire

This could be visible automatically for anyone using LinkFree who has a GitHub account too.

**Comment by eddiejaoude** [comment]
> GitHub Achievements can be added to your profile in this same style.
> 
> https://github.com/loftwah?tab=achievements is the page for all of your achievements, or you can have one that goes to a specific achievement. https://github.com/loftwah?tab=achievements&achievement=pair-extraordinaire
> 
> This could be visible automatically for anyone using LinkFree who has a GitHub account too.

thanks Dean! I like this idea but I think adding these automatically to LinkFree profile (if available from GitHub's api) should be a separate issue

**Comment by geeky-sambhav** [comment]
Sorry I could u pls unassign me as I am very busy nowadays due to the demise of my grandmother.Moreover my exams are starting from next week.I am really very sorry.

**Comment by eddiejaoude** [comment]
> Sorry I could u pls unassign me as I am very busy nowadays due to the demise of my grandmother.Moreover my exams are starting from next week.I am really very sorry.

Sure we can unassign it, I hope everything goes ok @geeky-sambhav (btw you are able to unassign yourself from issues)

**Comment by CBID2** [comment]
I can work on this issue @eddiejaoude

**Comment by SaraJaoude** [comment]
> I can work on this issue @eddiejaoude

@CBID2 I will assign this to you.  In future, please take into consideration the `Working on an Issue (get it assigned to you` [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md#working-on-an-issue-get-it-assigned-to-you) and not tag maintainers when asking for an Issue to be assigned.

**Comment by CBID2** [comment]
> > I can work on this issue @eddiejaoude
> 
> 
> 
> @CBID2 I will assign this to you.  In future, please take into consideration the `Working on an Issue (get it assigned to you` [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md#working-on-an-issue-get-it-assigned-to-you) and not tag specific maintainers when asking for an Issue to be assigned - as any maintainer can assign an Issue.  The helps us reduce notifications and also with the flow of the project.
> 
> 

Noted
