### ISSUE TITLE
[FEATURE] Adding stories for all the components

### ISSUE THREAD

**Issue by Nanak360** [EddieHubCommunity/LinkFree#6691]
## Adding stories for all the components

Currently, the following components have stories:
- Footer
- Navbar
- Components related to the users page

However, there are several components that do not have stories yet. I believe that having stories for all components will greatly enhance the developer experience.

Having stories for each component would help with testing and debugging, as developers could quickly see how the component is supposed to behave in various scenarios. It would also make it easier for new developers to get up to speed with the project.

**Comment by eddiejaoude** [comment]
Yes we need to improve the test coverage and storybook coverage.

But I think it is better to make an issue per story, so we can merge them often. We have 1 issue here but no one has completed it yet https://github.com/EddieHubCommunity/LinkFree/issues/1989

So I will close this issue, please create a new issue for the Story you wish to complete and we can assign it to you
