### ISSUE TITLE
[BUG] useEffect has missing dependency

### ISSUE THREAD

**Issue by badrivlog** [EddieHubCommunity/LinkFree#6693]
### Description

found an issue in [pages/search.js](https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/search.js) line number `120`  useEffect has missing dependency `filterData`.

According to [React Docs](https://react.dev/learn/lifecycle-of-reactive-effects#all-variables-declared-in-the-component-body-are-reactive), props, state and others values declared inside the component are reactive because they're calculated during rendering and participate in the React data flow. If useEffect uses any reactive values then that values must be included in the dependency array.

![Screenshot (17)](https://user-images.githubusercontent.com/73095526/236885677-d3f6c29a-c864-4b54-802f-df44feb2f799.png)
[pages/search.js](https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/search.js) in useEffect  body line number `116` we call `filterData` function but never include `filterData` as dependency, this seems to be not correct.

### Additional information

Would love to fix this issue.

Thanks

**Comment by eddiejaoude** [comment]
Thank you for raising 👍  I have assigned it to you
