### ISSUE TITLE
[DOCS] Word Wrapping Incorrect in List Items

### ISSUE THREAD

**Issue by naomi-lgbt** [EddieHubCommunity/LinkFree#6709]
### Description

In the LinkFree documentation, the stylesheet appears to be configured to break words in list items - this results in text that is harder to read and understand. 

### Screenshots

<img width="891" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/63889819/c3712c05-1bee-49f6-9f89-84f149609788">

<img width="116" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/63889819/fe5508e5-0983-4695-a714-c645b3f38b2b">

**Comment by thehashmap** [comment]
I would like to work on this issue

**Comment by iamvbenz49** [comment]
we can use keep-all change this right??

**Comment by zaidahmad25** [comment]
Is this issue resolved?

**Comment by eddiejaoude** [comment]
yes this has been merged now
