### ISSUE TITLE
Add testimonial button overlays the social media icons on profile page

### ISSUE THREAD

**Issue by thehashmap** [EddieHubCommunity/LinkFree#6710]
**Edit: Changes to make...we use the notifications from Tailwind on the icons page, we should move that to a reusable component https://linkfree.io/icons**

### Description

On scrolling to the end of the profile page of any use, the Add Testimonial button overlays the social media icons. 

I suggest one of the following:
- Move the button to center
- Change the size of button to only display the icon and expand on hover

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/76116523/5d5d8173-7c57-4eb0-98bd-6ddb12cbb419)

**Comment by amandamartin-dev** [comment]
This bug is dependent on screen size and as it is a floating CTA, there may not be a perfect solution that will work on all resolutions if it remains floating.  For example, on my screen this does not happen.
![add testimonial screenshot](https://github.com/EddieHubCommunity/LinkFree/assets/97615019/0f1b53d8-6719-414d-985a-2001a9b4800b)

Moving the button to center would be awkward while scrolling, but the expandable CTA on hover is an idea that may work (be sure to consider mobile experience)

wdyt @eddiejaoude ?

**Comment by eddiejaoude** [comment]
Great points Amanda 👍 

Maybe it should be moved away from a floating button, possible to a `+` button next to `testimonials` tab? (but if they don't have any testimonials on their profile yet, then it won't appear 🤔 )

<img width="1667" alt="Screenshot 2023-05-10 at 03 01 36" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/f8829313-50e4-4f8f-a306-69742267154d">

**Comment by amandamartin-dev** [comment]
> Great points Amanda 👍
> 
> Maybe it should be moved away from a floating button, possible to a `+` button next to `testimonials` tab? (but if they don't have any testimonials on their profile yet, then it won't appear 🤔 )
> 

That is one solution, but considering we reuse that CTA throughout the app should all be fixed or just this one?

**Comment by eddiejaoude** [comment]
Another great point, yes we do use it on the homepage as well (I don't think anywhere else?), but I think the homepage `help` is easier to fix/move

**Comment by amandamartin-dev** [comment]
> Another great point, yes we do use it on the homepage as well (I don't think anywhere else?), but I think the homepage `help` is easier to fix/move

Oh right, I was thinking help was on every page for some reason. And yes, the help is also much smaller and potentially not necessary to adjust

**Comment by eddiejaoude** [comment]
Or the `help` can be added to the main navbar so it is on every page (but something else might need to move to give more space) - so I think the `help` is less of a challenge, but the `add testimonial` is more challenging, some ideas...

Move the `add testimonials` floating button to...
1. on the testimonial tab (but not always displayed)
2. top left of the profile picture (similar to the QR code)
3. top right of the profile page (under the navbar)
4. ...something else?

**Comment by eddiejaoude** [comment]
Another idea is to use the toast style component from Tailwind components therefore the user can dismiss it...

<img width="1402" alt="Screenshot 2023-05-10 at 12 08 02" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/f5ab15c4-436b-4477-a9bc-99cec5e0a834">

https://tailwindui.com/components/marketing/elements/banners#component-c5bc8a46a1093693fd286f0b74c631f4

**Comment by eddiejaoude** [comment]
There are notifications also as part of Tailwind components too https://tailwindui.com/components/application-ui/overlays/notifications

**Comment by eddiejaoude** [comment]
We use the notifications from Tailwind on the icons page, we should move that to a reusable component https://linkfree.io/icons

**Comment by ChinmayMhatre** [comment]
If we want to go with the + button route we could add a button says "Add a testimonial for {user name}" above the actual testimonials.
<img width="1314" alt="Screenshot 2023-05-11 at 12 42 12 AM" src="https://github.com/EddieHubCommunity/LinkFree/assets/51131670/e27b7427-8c2d-4590-8e4f-3bba4d464605">

**Comment by eddiejaoude** [comment]
But if no one has a testimonials yet on their profile, then that tab doesn't appear yet

**Comment by ChinmayMhatre** [comment]
> But if no one has a testimonials yet on their profile, then that tab doesn't appear yet

Umm... Just a thought, could we keep the tab even if there were no testimonials? Could look consistent. We could add a message encouraging to add a testimonial for the person?

**Comment by thehashmap** [comment]
I agree with @ChinmayMhatre. This could provide a more consistent user experience.

**Comment by eddiejaoude** [comment]
We had this displayed before but most people wanted it hidden until they used that feature to keep their profile minimalistic - which I think looks better

**Comment by Pradumnasaraf** [comment]
Here are the points we discussed in Discord.


Proposed solution by @Pradumnasaraf 

> _How about we chnage it to hover and expand or some other solution? Or we can move socials to a different position. By hover and expand, I mean something like this._
<img height= 250 src="https://github.com/EddieHubCommunity/LinkFree/assets/51878265/2e861525-8949-4d98-a60b-745df1ac8390">

Proposed solution by @dan-mba 

> _While technically possible, this will require a good bit of custom CSS. You can add the Aria tags to make it work with accessibility, but is it worth it? A simpler solution would be to add extra padding to the bottom of the footer so nothing gets blocked._

**Comment by eddiejaoude** [comment]
Thanks everyone, great collab! I have updated the issue description, I think we should do for the simplest solution for now, which will also help other notifications in the app - which is reusing the icon page's notification

**Comment by zaidahmad25** [comment]
Can I work on this issue?

**Comment by eddiejaoude** [comment]
We are now looking at getting the whole app redesigned, so I will close this for now
