### ISSUE TITLE
Images Clashes

### ISSUE THREAD

**Issue by kumarankit999** [EddieHubCommunity/LinkFree#6720]
### Description

On the Home-page, We can see in the below picture that Github Accelerator picture and github logo has been clashed, we can give some spaces between these two pictures to remove this clashes.

![image](https://github.com/EddieHubCommunity/LinkFree/assets/111564362/e0e87342-1fff-4e15-9c1f-da5beec88b7d)

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/111564362/0d0cc084-39e4-4f01-8be4-8a540b6653ba)

**Comment by eddiejaoude** [comment]
Thank you for the suggestion, but that is the design from Tailwind, to have an overlap style, so I will close this issue
