### ISSUE TITLE
[FEATURE] Custom error page 404

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#6721]
### Description

We currently have the default NextJS 404 error page, we should customise this 

https://nextjs.org/docs/pages/building-your-application/routing/custom-error

<img width="1659" alt="Screenshot 2023-05-10 at 13 44 25" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/c1961d76-4d96-4a9f-8454-a6c1faaec5dc">

Tailwind has a custom error page we can use https://tailwindui.com/components/marketing/feedback/404-pages

**Comment by Segacnd** [comment]
I am happy to work on this issue.

**Comment by SaraJaoude** [comment]
> I am happy to work on this feature.

@Segacnd I will assign this to you
