### ISSUE TITLE
fix: Icons Alignment

### ISSUE THREAD

**Issue by RayyanRNKJ** [EddieHubCommunity/LinkFree#674]
### Description

The icons are not properly *vertically aligned* with the text in the button,
One of the most important UI Principles is **Alignment**, So without that Principle it seems, it is lacking something.

### Screenshots

![Group 14](https://user-images.githubusercontent.com/64679235/141960117-38b52bf8-a464-4695-85b1-227d40435207.png)

**Comment by emmalearnscode** [comment]
Which browser is this happening in?

**Comment by krishguptadev** [comment]
> Which browser is this happening in?

I think this is in all the browsers 🤔

**Comment by emmalearnscode** [comment]
> > Which browser is this happening in?
> 
> I think this is in all the browsers 🤔

I ask because I'm not seeing it on my browser.

**Comment by krishguptadev** [comment]
The icon is not centred like the text. There is no inconsistency between the icons (they all are at the bottom). I think the vertical alignment of the icons comparing with the text is inconsistent

**Comment by RayyanRNKJ** [comment]
> Which browser is this happening in?

The Mozilla Web Developer Edition Browser.

**Comment by RayyanRNKJ** [comment]
> The icon is not centred like the text. There is no inconsistency between the icons (they all are at the bottom). I think the vertical alignment of the icons comparing with the text is inconsistent

Exactly.

**Comment by emmalearnscode** [comment]
I’m not seeing this issue in either chrome or safari. I can check others later.

**Comment by RayyanRNKJ** [comment]
> I’m not seeing this issue in either chrome or safari. I can check others later.

Nowadays Cross-browser compatibility is an essential part.

**Comment by emmalearnscode** [comment]
Of course, just trying to narrow down the problem first

**Comment by mohan-murali** [comment]
I have checked in chrome, brave, firefox and edge. Doesn't seem to occur in any of these.

**Comment by RayyanRNKJ** [comment]
> I have checked in chrome, brave, firefox and edge. Doesn't seem to occur in any of these.

Oh, but still for me its vertical alignment is not equal.

**Comment by RayyanRNKJ** [comment]
> I have checked in chrome, brave, firefox and edge. Doesn't seem to occur in any of these.

> Of course, just trying to narrow down the problem first

While I am hovering on it, the vertical alignment is really visible for me.
![Screenshot from 2021-11-17 10-40-45](https://user-images.githubusercontent.com/64679235/142139089-471fed51-6f5f-4393-b944-4e80891f6c54.png)

**Comment by mohan-murali** [comment]
Firefox : -
![image](https://user-images.githubusercontent.com/26025710/142140593-aaba8bb1-2c3f-4291-a548-23b6a280ded0.png)

Chrome: -
![image](https://user-images.githubusercontent.com/26025710/142140659-715d51b3-684c-429e-b4cc-54e26cd5af74.png)

Brave:-
![image](https://user-images.githubusercontent.com/26025710/142140721-e6061580-4473-4290-9569-3f094b1f14d3.png)

edge:-
![image](https://user-images.githubusercontent.com/26025710/142140843-b3668324-b365-4b60-bf2b-8d4bcb98fe7b.png)

**Comment by RayyanRNKJ** [comment]
> Firefox : - ![image](https://user-images.githubusercontent.com/26025710/142140593-aaba8bb1-2c3f-4291-a548-23b6a280ded0.png)
> 
> Chrome: - ![image](https://user-images.githubusercontent.com/26025710/142140659-715d51b3-684c-429e-b4cc-54e26cd5af74.png)
> 
> Brave:- ![image](https://user-images.githubusercontent.com/26025710/142140721-e6061580-4473-4290-9569-3f094b1f14d3.png)
> 
> edge:- ![image](https://user-images.githubusercontent.com/26025710/142140843-b3668324-b365-4b60-bf2b-8d4bcb98fe7b.png)

Oh, I don't why the vertical alignment is not proper for me.
Maybe It depends on the OS I am using or the Browser I am using otherwise my screen height.

**Comment by mohan-murali** [comment]
> > Firefox : - ![image](https://user-images.githubusercontent.com/26025710/142140593-aaba8bb1-2c3f-4291-a548-23b6a280ded0.png)
> > Chrome: - ![image](https://user-images.githubusercontent.com/26025710/142140659-715d51b3-684c-429e-b4cc-54e26cd5af74.png)
> > Brave:- ![image](https://user-images.githubusercontent.com/26025710/142140721-e6061580-4473-4290-9569-3f094b1f14d3.png)
> > edge:- ![image](https://user-images.githubusercontent.com/26025710/142140843-b3668324-b365-4b60-bf2b-8d4bcb98fe7b.png)
> 
> Oh, I don't why the vertical alignment is not proper for me. Maybe It depends on the OS I am using or the Browser I am using otherwise my screen height.

Might be. what browser and OS you are using?

**Comment by RayyanRNKJ** [comment]
> > > Firefox : - ![image](https://user-images.githubusercontent.com/26025710/142140593-aaba8bb1-2c3f-4291-a548-23b6a280ded0.png)
> > > Chrome: - ![image](https://user-images.githubusercontent.com/26025710/142140659-715d51b3-684c-429e-b4cc-54e26cd5af74.png)
> > > Brave:- ![image](https://user-images.githubusercontent.com/26025710/142140721-e6061580-4473-4290-9569-3f094b1f14d3.png)
> > > edge:- ![image](https://user-images.githubusercontent.com/26025710/142140843-b3668324-b365-4b60-bf2b-8d4bcb98fe7b.png)
> > 
> > 
> > Oh, I don't why the vertical alignment is not proper for me. Maybe It depends on the OS I am using or the Browser I am using otherwise my screen height.
> 
> Might be. what browser and OS you are using?

OS: Ubuntu 20.04
Browser: Mozilla Firefox Developer Edition

**Comment by emmalearnscode** [comment]
If this is only happening on Mozilla Dev browser I don't think we should focus on it for now. The dev browser probably has some beta or experimental features which is affecting it which doesn't exist in any other browser and may not end up in production on the normal mozilla browser either.

**Comment by krishguptadev** [comment]
Can this issue be closed for the same?

**Comment by RayyanRNKJ** [comment]
> If this is only happening on Mozilla Dev browser I don't think we should focus on it for now. The dev browser probably has some beta or experimental features which is affecting it which doesn't exist in any other browser and may not end up in production on the normal mozilla browser either.

Totally Agree with that 💯
