### ISSUE TITLE
Roadmap formatting

### ISSUE THREAD

**Issue by loftwah** [EddieHubCommunity/LinkFree#6748]
### Description

The right border of the first card is missing, and the left border of the final card is missing on my mobile device. Eddie knows what I'm describing. I can add a screenshot if needed. It is on the new Roadmap page.

**Comment by ChinmayMhatre** [comment]
Can be fixed by changing `border-r-0` to `lg:border-r-0` and `border-l-0` to `lg:border-l-0` at lines `95` `96` in the `roadmap.js` page.

**Comment by ChinmayMhatre** [comment]
I'll add the screenshots from our discussion in discord !
![image](https://github.com/EddieHubCommunity/LinkFree/assets/51131670/307c2dd9-5258-45a8-8f35-547b20a0aca0)
![image](https://github.com/EddieHubCommunity/LinkFree/assets/51131670/671f03eb-ac27-44e5-a5c1-5c81582020fb)

**Comment by eddiejaoude** [comment]
@ChinmayMhatre looks like you came up with the solution already, feel free to assign it to yourself if you want to do it

**Comment by ChinmayMhatre** [comment]
> @ChinmayMhatre looks like you came up with the solution already, feel free to assign it to yourself if you want to do it

Hey Eddie I think this can be a good opportunity for someone to get a green square. 

I can take this up in case no one responds

**Comment by eddiejaoude** [comment]
Sounds great 👍

**Comment by Lalman888** [comment]
Can I do this issue ?

**Comment by GunjanKMishra** [comment]
Hi Eddie!!
Can I please do this issue? I'm new at coding and open-source too😅!!

**Comment by GunjanKMishra** [comment]
sounds great!! 
thanks Eddie!!

**Comment by Lalman888** [comment]
done
