### ISSUE TITLE
[FEATURE] Toggle header/footer on/off for your profile

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#6757]
### Description

Some profiles might want to hide the main navbar and also the footer

Note changes
- toggle component
- passing data to the layout
- model for 2 new parameters
- stats page with toggles

**Comment by Agastya18** [comment]
@eddiejaoude  can i work on it

**Comment by eddiejaoude** [comment]
> @eddiejaoude can i work on it

thank you @Agastya18 but this issue is already assigned and has a pull request waiting for review already

Please have a look at issues that are not assigned yet and ready for dev, you can learn more in our contributing guide, any questions you can ask us in the EddieHub Discord https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by eddiejaoude** [comment]
Done as part of this PR https://github.com/EddieHubCommunity/LinkFree/pull/8647
