### ISSUE TITLE
GitHub links - Redirect to a new tab

### ISSUE THREAD

**Issue by YOKESHCR** [EddieHubCommunity/LinkFree#6763]
### Description

The Github links which are present in the footer when clicked can be made to be opened in a new tab , instead of redirecting. The only Giithub link which opens in a new tab are the one which is present in the nav-bar icon and the user's Github profile.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/27686539/c72304a2-e0b2-4dd3-8355-dd7e135bc651)

**Comment by eddiejaoude** [comment]
Thanks for raising, yes external links should open in a new tab 👍

**Comment by HassanTanveer** [comment]
Hey, can you assign this issue to me?

**Comment by eddiejaoude** [comment]
Sure, assigned @HassanTanveer - please note my comment above, it should only open in new tab for external links

**Comment by HassanTanveer** [comment]
Thanks, I understand

**Comment by kaafivikrant** [comment]
Hey, @eddiejaoude  you assign this issue to me?

I have tested the code with the changes.

**Comment by eddiejaoude** [comment]
> Hey, @eddiejaoude you assign this issue to me?
> 
> I have tested the code with the changes.

@kaafivikrant the issue is already assigned, please read the replies just above yours

**Comment by kaafivikrant** [comment]
Sure
