### ISSUE TITLE
[OTHER] GitHub bot should unlock conversation once '🏁 status: ready for dev' label is added

### ISSUE THREAD

**Issue by HassanTanveer** [EddieHubCommunity/LinkFree#6770]
### What would you like to share?

Currently, conversations in issues is locked while it is labelled `🚦 status: awaiting triage` and a maintainer needs to unlock it manually after label is changed to `🏁 status: ready for dev`. The conversation in #6658 is still locked even though it's labelled `🏁 status: ready for dev`.

<img width="997" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/57575219/86d98987-0a2b-4bec-8fb8-df1366193928">

**Comment by eddiejaoude** [comment]
Thank you for raising, yes as this is a new process sometimes we forget to unlock after changing the label to `ready for dev` - if this can be automated then it would be better 👍

**Comment by eddiejaoude** [comment]
It might be possible to use the same Action we are using to lock the issue https://github.com/dessant/repo-lockdown, but if not there is another Action that is more generic that might work https://github.com/marketplace/actions/oction-unlock-issue

*note: please use inclusive language in our GitHub Org, similar to how we do in the EddieHub Discord, not everyone is a `guy`*

**Comment by MAYANKpandey14** [comment]
> It might be possible to use the same Action we are using to lock the issue https://github.com/dessant/repo-lockdown, but if not there is another Action that is more generic that might work https://github.com/marketplace/actions/oction-unlock-issue
> 
> _note: please use inclusive language in our GitHub Org, similar to how we do in the EddieHub Discord, not everyone is a `guy`_

I'll make sure of it for next time. Thanks

**Comment by eddiejaoude** [comment]
Thank you @MAYANKpandey14 👍

**Comment by iamvbenz49** [comment]
can i know where can i find the files related to this issue?

**Comment by weilincheng** [comment]
I'm sorry for the unexpected message. While testing GitHub Action on my forked repository, I accidentally referenced to this issue. 
If no one is working on it right now, I would like to help.

**Comment by eddiejaoude** [comment]
Sure @weilincheng it is not assigned, I will assign it to you

**Comment by SaraJaoude** [comment]
There does not seem to have been any activity in the last two weeks so I have unassigned this issue.

**Comment by nitheesh-daram** [comment]
Hey, I would like to take this up!

**Comment by SaraJaoude** [comment]
> Hey, I would like to take this up!

@nitheesh-daram I have assigned this to you

**Comment by eddiejaoude** [comment]
Merged 🎉
