### ISSUE TITLE
fix: event card problem

### ISSUE THREAD

**Issue by priyankarpal** [EddieHubCommunity/LinkFree#6776]
### Description

In the event card, we need to add spacing & padding to fix the card issue. 

## What to add?
- we need to add `space-y-3` and `pl-3` to fix left side icons 
- To fix the text spacing we need to add `space-y-2` 
- also, to fix the avatars issue we need to add `pr-2`

### Before 

![image](https://github.com/EddieHubCommunity/LinkFree/assets/88102392/aa46c310-d10b-4349-bd17-975ccfa13b20)

### After

![image](https://github.com/EddieHubCommunity/LinkFree/assets/88102392/4b91dc31-1805-46c6-b8c9-262e3de25e74)

### Additional information

I want to work on this issue

**Comment by amandamartin-dev** [comment]
Hey @priyankarpal can you provide a little more information about how to recreate this?  I just completed a quick test of responsive behaviors and didn't see this overlap.

https://github.com/EddieHubCommunity/LinkFree/assets/97615019/fb1ef5ce-dd61-4d66-8236-43fb2fcc3f63

**Comment by eddiejaoude** [comment]
I didn't test it but if needed, I think the items are using flex, so a `gap` would work better that various padding

**Comment by priyankarpal** [comment]
> Hey @priyankarpal can you provide a little more information about how to recreate this? I just completed a quick test of responsive behaviors and didn't see this overlap.
> 
>  responsive.test.mov


https://github.com/EddieHubCommunity/LinkFree/assets/88102392/52fa55d8-33de-4abc-bce5-7dbf9da788e5

**Comment by eddiejaoude** [comment]
I couldn't replicate this either, what browser and OS are you using?

**Comment by priyankarpal** [comment]
> I couldn't replicate this either, what browser and OS are you using?

also, the same issue in google chrome 

https://github.com/EddieHubCommunity/LinkFree/assets/88102392/ba925277-00c1-4025-9c49-a29fd4b1792d

**Comment by KhuloodHassan** [comment]
Hey! I tested this in Chrome, Brave and Edge and have the same issue. Screenshots attached for you!
![BRAVE](https://github.com/EddieHubCommunity/LinkFree/assets/51343773/f18534d9-5abb-4729-b0f6-ec2907af7c00)
![CHROME](https://github.com/EddieHubCommunity/LinkFree/assets/51343773/fd8e1521-2f9c-4f13-92d4-3391dd79c337)
![EDGE](https://github.com/EddieHubCommunity/LinkFree/assets/51343773/b3adce45-93bc-47b0-b916-d34cd43fa23d)

**Comment by ChinmayMhatre** [comment]
> Hey @priyankarpal can you provide a little more information about how to recreate this? I just completed a quick test of responsive behaviors and didn't see this overlap.
> 
>  responsive.test.mov

I tried testing on safari and brave in macos, works fine on mine as well. maybe an issue on windows

**Comment by priyankarpal** [comment]
> > Hey @priyankarpal can you provide a little more information about how to recreate this? I just completed a quick test of responsive behaviors and didn't see this overlap.
> > responsive.test.mov
> 
> I tried testing on safari and brave in macos, works fine on mine as well. maybe an issue on windows

I'm using Linux

**Comment by amandamartin-dev** [comment]
> I'm using Linux

So, can we confirm this only happens on machines running Linux?  Do you happen to have access to a non-Linux machine to see if you can confirm that on your end?

**Comment by priyankarpal** [comment]
> > I'm using Linux
> 
> So, can we confirm this only happens on machines running Linux? Do you happen to have access to a non-Linux machine to see if you can confirm that on your end?

you can check @KhuloodHassan comment

**Comment by amandamartin-dev** [comment]
> > > I'm using Linux
> > 
> > 
> > So, can we confirm this only happens on machines running Linux? Do you happen to have access to a non-Linux machine to see if you can confirm that on your end?
> 
> you can check @KhuloodHassan comment

Their comment does not name OS. My test on Mac and chrome did not recreate this and so far it looks like only Linux but need to confirm with someone with access to both

**Comment by ujjwalkirti** [comment]
I am attaching screenshots, where I tried to replicate this on my windows PC.
**OS**: Windows 10
**Screen Resoution**:  1920 * 1080
**Browser**: Brave
![Screenshot (20)](https://github.com/EddieHubCommunity/LinkFree/assets/64329707/e5c4e08e-df68-4435-96a0-05d643b690fe)
![Screenshot (21)](https://github.com/EddieHubCommunity/LinkFree/assets/64329707/819ff067-1cc5-4c3d-9891-da2eed407132)
![Screenshot (22)](https://github.com/EddieHubCommunity/LinkFree/assets/64329707/8d647233-0ee0-419f-9c92-2216c94af61c)

***Note***: This screenshot is of local setup for development purposes.

**Comment by priyankarpal** [comment]
@amandamartin-dev you can check if there is the same problem with windows.

**Comment by amandamartin-dev** [comment]
> @amandamartin-dev you can check if there is the same problem with windows.

I am not seeing this problem at all on my windows or mac. I do not have access to a linux machine to compare there as well which is why I asked for you to confirm if possible.  But, it sounds like this problem is limited to users on Linux unless any new information comes to light.

**Comment by shoebilyas123** [comment]
Hey @amandamartin-dev, I tested on both windows and linux. The error persists.

**Comment by amandamartin-dev** [comment]
> Hey @amandamartin-dev, I tested on both windows and linux. This UI bug persists.

Hello, as I reported previously, I am unable to recreate this on Windows or Mac (I don't have Linux).  I will leave the decision to @eddiejaoude whether or not to move forward with this as it appears to only happen for a small subset of folks under very specific conditions so I am not sure how to best proceed here. Thank you for testing!

**Comment by KhuloodHassan** [comment]
> > > > I'm using Linux
> > > 
> > > 
> > > So, can we confirm this only happens on machines running Linux? Do you happen to have access to a non-Linux machine to see if you can confirm that on your end?
> > 
> > 
> > you can check @KhuloodHassan comment
> 
> Their comment does not name OS. My test on Mac and chrome did not recreate this and so far it looks like only Linux but need to confirm with someone with access to both

I'm on Windows 10!

**Comment by eddiejaoude** [comment]
Thank you everyone for your amazing collaboration - we are currently planning to have the whole app redesigned, so I will close this issue for now. 

Thanks again everyone 💪
