### ISSUE TITLE
[FEATURE] use docker mutlti-stage builds 🐋

### ISSUE THREAD

**Issue by samyabrata-maji** [EddieHubCommunity/LinkFree#6819]
### Description

We can use [docker multi-stage builds](https://docs.docker.com/build/building/multi-stage/) to make the code more readable.

**Comment by Pradumnasaraf** [comment]
Thank you for bringing up the multi-stage build feature in Dockerfiles. 

I agree that it is an ideal solution for production environments. However, for our specific use case, where we primarily use build images for local development, the impact may be minimal. Therefore, I am not particularly keen on adding them at this time. However, we do have plans to deploy on Kubernetes in the future, and at that point, we can optimize the use of multi-stage builds.

**Comment by Pradumnasaraf** [comment]
Thank you for bringing up the multi-stage build feature in Dockerfiles. 

I agree that it is an ideal solution for production environments. However, for our specific use case, where we primarily use build images for local development, the impact may be minimal. Therefore, we are not particularly keen on adding them at this time. However, we do have plans to deploy on Kubernetes in the future, and at that point, we can optimize the use of multi-stage builds.
