### ISSUE TITLE
[FEATURE] Search page to display 5 random profiles

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#6824]
### Description

I think by default the search page should show 5 random profiles when there is no search performed

Tasks
- do not load all profiles on page load (think will make the page load faster)
- on page load select 5 random profiles 
- when searching perform search on the server side

**Comment by shoebilyas123** [comment]
Would like to work on this issue.

**Comment by SaraJaoude** [comment]
> Would like to work on this issue.

@shoebilyas123 I will assign this to you

**Comment by shoebilyas123** [comment]
Hey @eddiejaoude. I closed the previous pr and gave a new one with only the changes made to display random user profiles. Was having some issues while working on that pr.

**Comment by eddiejaoude** [comment]
thank you @shoebilyas123  👍
