### ISSUE TITLE
[OTHER] Fix mongo db initial connection config

### ISSUE THREAD

**Issue by mnvsk97** [EddieHubCommunity/LinkFree#6855]
### What would you like to share?

Currently, to establish a connection with the mongoDB instance, we use the `connectMongo` function in the `config/mongo.js` file. A new connection is not established when there is an existing connection. Please refer to the attached screenshot:
<img width="737" alt="Screenshot 2023-05-13 at 11 28 14 PM" src="https://github.com/EddieHubCommunity/LinkFree/assets/28086178/ff0767d8-89f8-4a2d-a611-9caa3a9a6c60">

`hasConnection` variable is assigned in line 24 and reassigned in line 28. 

Proposal:

1. replace `hasConnection` with `connection` variable which stores the result of `await mongoose.connect(....` which returns an object with the current connection's information.
2. Remove the return and re assignment of `hasConnection` since we don't use the connection information anywhere.
3. Improvement: extract `LINKFREE_MONGO_CONNECTION_STRING` variable using `const { } = params.env` and re use it wherever needed. This way, we don't have to use `process.env.....` everywhere.
4. Remove the usage of `process.env.CA_CERT` as it is not being used anymore.
5. Fix `import logger from "../config/logger";` to `import logger from "./logger";` since the `logger.js` file exists in the same directory.

**Comment by eddiejaoude** [comment]
Thanks for the suggestions, I think you have a few different issues in 1, we could split them up.

- `mongo.js`, not sure I follow all your suggestions, but also the `cert` can be removed, it is no longer required
- the validator of the environment variables sounds interesting, could you create a separate issue for this with a link to an example (or their official docs) - edit your issue description and remove this suggestion from this issue

**Comment by mnvsk97** [comment]
> Thanks for the suggestions, I think you have a few different issues in 1, we could split them up.
> 
> * `mongo.js`, not sure I follow all your suggestions, sounds interesting though (btw the `cert` can be removed, it is no longer required)
> * the validator of the environment variables sounds interesting, could you create a separate issue for this with a link to an example (or their official docs) - edit your issue description and remove this suggestion from this issue

Hey 👋 
1. I've edited the issue as per your suggestions.
2. Here is the [issue](https://github.com/EddieHubCommunity/LinkFree/issues/6871) for the validator.

LMK how this looks. Thanks 🙏

**Comment by eddiejaoude** [comment]
I think it sounds good 👍

**Comment by Chalithya** [comment]
Hey Eddie, I would love to work on this if someone else is not assigned yet.

**Comment by SaraJaoude** [comment]
> Hey Eddie, I would love to work on this if someone else is not assigned yet.

@Chalithya I have assigned this to you.

**Comment by Chalithya** [comment]
I did some changes to the code including the changes in the requirements and created a PR 🚀
