### ISSUE TITLE
[FEATURE] "View All" option on Icons page

### ISSUE THREAD

**Issue by thehashmap** [EddieHubCommunity/LinkFree#6869]
### Description

Currently, we need to search the icons by name. But there might be some less popular icons that the user wants to use but does not know the search term to look for it.
So an option to view all the available icons at once would come in handy.

**Comment by eddiejaoude** [comment]
Thank you for the suggestion but I think this will make the page very slow as there will be so many, we use `react-icons` with multiple icon sets.
