### ISSUE TITLE
[FEATURE] Validate environment variables on start up

### ISSUE THREAD

**Issue by mnvsk97** [EddieHubCommunity/LinkFree#6871]
### Description

Add a schema validator like zod for all the `required` env variables and run it at the start of the app to raise an error if any of them are not present/invalid. This way, any manual checks can be avoided. Some of the examples of manual validations are: 

<img width="931" alt="Screenshot 2023-05-14 at 1 52 52 PM" src="https://github.com/EddieHubCommunity/LinkFree/assets/28086178/25edc1fb-3d8b-4b29-b917-97d2a8505e87">

An example of how a basic validation can be added can be found [here](https://zod.dev/?id=basic-usage)

**Comment by eddiejaoude** [comment]
This looks really interesting 👍 

Especially as it could be used for the json profiles on...
- playground page
- GitHub Action for profile changes

**Comment by mnvsk97** [comment]
Please assign this to me. Also, can you please elaborate on the json profiles validations? If you create a separate ticket, please let me know and I can have a look.

**Comment by eddiejaoude** [comment]
I have assigned it to you @mnvsk97 

sure I created a separate ticket 👍 https://github.com/EddieHubCommunity/LinkFree/issues/6874

**Comment by SaraJaoude** [comment]
I have unassigned due to lack of activity.

**Comment by mnvsk97** [comment]
Hi @SaraJaoude 
Thanks for unassigning. I won't be able to work on this for some time due to other engagements. Please assign it to someone who is looking for an issue. Thanks 🙏

**Comment by plbstl** [comment]
I'd love to work on this. I have some ideas already

**Comment by SaraJaoude** [comment]
> I'd love to work on this. I have some ideas already

@plbstl please wait to be assigned an Issue before working on it so that you do not run the risk of your PR being closed. This requirement is set out in the [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) which I would suggest you familiarise yourself with.

On this occasion as this Issue was already marked as `status: ready for dev` I will assign this to you.

**Comment by eddiejaoude** [comment]
As there is overlap with the other Zod issue, I am reassign this issue to @catalinpit to avoid conflicts and I am assigning @plbstl another issue they created a PR for

**Comment by catalinpit** [comment]
> As there is overlap with the other Zod issue, I am reassign this issue to @catalinpit to avoid conflicts and I am assigning @plbstl another issue they created a PR for

Thank you!

**Comment by plbstl** [comment]
> @plbstl please wait to be assigned an Issue before working on it so that you do not run the risk of your PR being closed. This requirement is set out in the [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) which I would suggest you familiarise yourself with.

Duly noted. I have done that now. Thank you
