### ISSUE TITLE
[OTHER] Improve user search experience 

### ISSUE THREAD

**Issue by shoebilyas123** [EddieHubCommunity/LinkFree#6872]
### What would you like to share?

These are the issues relating the user search experience on the search page that need to improved/fixed:
- Search keywords including a name along with a tag separated by a comma ("OpenSource,Eddie Jaoude") results in not found error.
- If there is an extra comma or an extra space, it should be ignored otherwise it has a bad user search experience.

**Comment by eddiejaoude** [comment]
Thank you for raising, I will block this until we migrate to using the DB, because Mongo has search capabilities which will make this easier

**Comment by itsdevdeepak** [comment]
Hi! I would like to work on this. Please assign me this issue.

**Comment by SaraJaoude** [comment]
> Hi! I would like to work on this. Please assign me this issue.

@itsdevdeepak I have assigned this to you
