### ISSUE TITLE
[IMPROVEMENT] Fix slow page load on maps page. 

### ISSUE THREAD

**Issue by shoebilyas123** [EddieHubCommunity/LinkFree#6873]
### What would you like to share?

On the maps page, we need to load all the users and we do it on getServerSideProps. The result is extremely slow page load. This is a challenging issue that we need to resolve.

**Comment by eddiejaoude** [comment]
We have to load all the users to display them on the map. Could we load them in batches (paginated)? For example load 100 at a time with a progress bar

**Comment by shoebilyas123** [comment]
But it should be automatic right? The api should be called repeatedly and the new users added and displayed accordingly. This is a method I found on stackoverflow that we can use with your approach. Thankfully the react-leaflet works flawlessly with dynamic state updates. 
https://stackoverflow.com/questions/42835692/react-leaflet-add-markers-dynamically

**Comment by amandamartin-dev** [comment]
> 

Is the query slow or the map rendering the data slow?  Meaning, do we know if this is a data problem or a leaflet problem?

**Comment by eddiejaoude** [comment]
I think it is slow (similar to the search page) because loading the large dataset takes time

**Comment by amandamartin-dev** [comment]
> I think it is slow (similar to the search page) because loading the large dataset takes time

I guess what I'm thinking about is the fact that this isn't a lot of points for leaflet and by using marker cluster, we are further decreasing the load on the map as the points aren't all rendering on page load. So, I'm not completely convinced pagination is indicated and also unsure what that will do to the map rendering since it's client side. Untested though, I don't currently have another path to offer just thinking so still work a try if it's not too heavy a lift

**Comment by shoebilyas123** [comment]
> > I think it is slow (similar to the search page) because loading the large dataset takes time
> 
> I guess what I'm thinking about is the fact that this isn't a lot of points for leaflet and by using marker cluster, we are further decreasing the load on the map as the points aren't all rendering on page load. So, I'm not completely convinced pagination is indicated and also unsure what that will do to the map rendering since it's client side. Untested though, I don't currently have another path to offer just thinking so still work a try if it's not too heavy a lift

I looked into this on stackoverflow and found that client side state updates work flawlessly on markers. However, I am not sure how performant it is on multiple consecutive state updates but we should definitely try it out.

**Comment by amandamartin-dev** [comment]
> I looked into this on stackoverflow and found that client side state updates work flawlessly on markers. However, I am not sure how performant it is on multiple consecutive state updates but we should definitely try it out.

Oh amazing! Thank you for checking into this

**Comment by dan-mba** [comment]
I put some code together in the [static-map branch](https://github.com/EddieHubCommunity/LinkFree/tree/static-map) that should fix this.

I am waiting on #6049 to be merged before creating a PR for more pages using Incremental Static Regeneration.

**Comment by eddiejaoude** [comment]
> I am waiting on #6049 to be merged before creating a PR for more pages using Incremental Static Regeneration.

OMG sorry Dan, I completely forgot, I will do this first thing tomorrow morning
