### ISSUE TITLE
[FEATURE] Json profile validation

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#6874]
### Description

Another issue is going to use [Zod](https://zod.dev/?id=basic-usage) to validate the required environment variables https://github.com/EddieHubCommunity/LinkFree/issues/6871

I wonder if this could be used to validate the json profiles in `data/`? For example https://github.com/EddieHubCommunity/LinkFree/blob/main/data/eddiejaoude.json

The areas in the application that could benefit from the schema validation are: (these could be each in their own issue)
- Playground https://linkfree.io/playground
- GitHub Action checks the json is valid, but checking the schema would be even better
- Loading in the json to the DB in `pages/api/system/reload.js` log out any that fail validation

**Comment by mnvsk97** [comment]
@eddiejaoude Are you suggesting something like validation the presence of
1. mandatory fields
2. validate schema and the structure of objects
3. url validation

**Comment by eddiejaoude** [comment]
Yes 👍  and...

- dates
and possibly other item types in the json

**Comment by shoebilyas123** [comment]
I checked through the documentation and I think this is a great idea! It will also prevent non-admins to add tags like "EddieHub Maintainer" or "EddieHub Ambassador" apart from validating the json.

**Comment by catalinpit** [comment]
Hey, can I pick this, please?

**Comment by Vishrut19** [comment]
Hey @SaraJaoude! It has been 2 weeks and there is no update on this issue. So can I take it up and work on it?

**Comment by catalinpit** [comment]
Hello, I'm still working on this one. I was diving deeper into Zod, hence why I didn't push any changes yet.

**Comment by SaraJaoude** [comment]
> Hey @SaraJaoude! It has been 2 weeks and there is no update on this issue. So can I take it up and work on it?

@Vishrut19 may I ask again that you do not tag specific maintainers - this is referred to in our [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) which has been sent to you on more than one occasion. If there is something about the Contributing Guide which is unclear then please raise this in Discord so that we can look to make improvements.

As this is a more complex issue that requires multiple changes, we would prefer to assign it to a contributor who is more familiar with our codebase, especially given the previous discussions with you. We encourage you to look at some other issues that are open for contribution - `unassigned` issues labelled with `points 1 to 3`.

**Comment by Vishrut19** [comment]
> > Hey @SaraJaoude! It has been 2 weeks and there is no update on this issue. So can I take it up and work on it?
> 
> @Vishrut19 may I ask again that you do not tag specific maintainers - this is referred to in our [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) which has been sent to you on more than one occasion. If there is something about the Contributing Guide which is unclear then please raise this in Discord so that we can look to make improvements.
> 
> As this is a more complex issue that requires multiple changes, we would prefer to assign it to a contributor who is more familiar with our codebase, especially given the previous discussions with you. We encourage you to look at some other issues that are open for contribution - `unassigned` issues labelled with `points 1 to 3`.

okay thanks for updating

**Comment by eddiejaoude** [comment]
Merged https://github.com/EddieHubCommunity/LinkFree/pull/8357
