### ISSUE TITLE
Deploy project

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#69]
**Update: ingress config is not loading, there is no service running, could this be the issue?**

Deployed to Kubernetes 

<img width="1672" alt="Screenshot 2021-09-11 at 08 49 10" src="https://user-images.githubusercontent.com/624760/132940840-1566a280-bb73-4ef8-93cf-a157c6ab457a.png">

### DNS looks ok

works: api.eddiehub.org

```
dig api.eddiehub.org

; <<>> DiG 9.10.6 <<>> api.eddiehub.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24845
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;api.eddiehub.org.		IN	A

;; ANSWER SECTION:
api.eddiehub.org.	2563	IN	A	67.207.70.148

;; Query time: 67 msec
;; SERVER: 10.0.1.1#53(10.0.1.1)
;; WHEN: Sat Sep 11 08:52:35 BST 2021
;; MSG SIZE  rcvd: 50
```

fails: linkfree.eddiehub.org

```
dig linkfree.eddiehub.org

; <<>> DiG 9.10.6 <<>> linkfree.eddiehub.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8309
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;linkfree.eddiehub.org.		IN	A

;; ANSWER SECTION:
linkfree.eddiehub.org.	472	IN	A	67.207.70.148

;; Query time: 61 msec
;; SERVER: 10.0.1.1#53(10.0.1.1)
;; WHEN: Sat Sep 11 08:52:46 BST 2021
;; MSG SIZE  rcvd: 55
```

## Kubernetes config

API (works) https://github.com/EddieHubCommunity/api/tree/main/kubernetes
LinkFree (fails) https://github.com/EddieHubCommunity/LinkFree/tree/main/kubernetes

**Comment by FayasNoushad** [comment]
Temporarily Deployed for you :- https://eddie-hub-community-link-free.vercel.app/

**Comment by FayasNoushad** [comment]
Eddiejaoude :- https://eddie-hub-community-link-free.vercel.app/Eddiejaoude
FayasNoushad :- https://eddie-hub-community-link-free.vercel.app/FayasNoushad

**Comment by eddiejaoude** [comment]
Thank you 🤓

**Comment by FayasNoushad** [comment]
> Thank you

You can user vercel or netlify ( free servers ) and no more problems for deploying.

**Comment by eddiejaoude** [comment]
Fixed, we are now deploying to our Kubernetes cluster 🎉
