### ISSUE TITLE
[FEATURE] Implement Prettier GitHub Action

### ISSUE THREAD

**Issue by krishguptadev** [EddieHubCommunity/LinkFree#690]
### Description

Implement a GitHub Action to format files automatically

### Additional information

The conversation started at #689, I would love to work on this.

**Comment by emmalearnscode** [comment]
I wonder if a pre-commit hook would be more useful so that code gets formatted locally before every commit.

**Comment by krishguptadev** [comment]
> I wonder if a pre-commit hook would be more useful so that code gets formatted locally before every commit.

Not everyone uses `git` cli and especially keeps husky installed.

**Comment by emmalearnscode** [comment]
I don't think git cli is necessary for using pre-commit hooks. I quite often use the inbuilt git in vs-code and the pre-commit formatting hooks work just fine there in the projects that use them. I guess you mean that not everyone does npm install if they are adding a json file? But is there not some inbuilt format on save instructions in the prettier config that can solve this?

**Comment by krishguptadev** [comment]
> I don't think git cli is necessary for using pre-commit hooks. I quite often use the inbuilt git in vs-code and the pre-commit formatting hooks work just fine there in the projects that use them. I guess you mean that not everyone does npm install if they are adding a json file? But is there not some inbuilt format on save instructions in the prettier config that can solve this?

As per what I know, people tend to use the github UI **directly** to add their profile 🙂

**Comment by Vyvy-vi** [comment]
That's true though pre-commit hooks are kinda neat.
However, I personally think it's better to have pre-push hooks instead, since that way people don't have to wait for the CI process to run on every commit

**Comment by krishguptadev** [comment]
Can I work on this? (On a discord call it was decided github actions)

**Comment by Vyvy-vi** [comment]
Go on! I think it would be great if the action only runs on the `pull_request` event when PR is `opened`, `reopened` or `edited` and makes a commit only if the files don't pass prettier.
