### ISSUE TITLE
[OTHER] GitPod checking links results in error

### ISSUE THREAD

**Issue by GrahamTheDevRel** [EddieHubCommunity/LinkFree#6912]
### What would you like to share?

I was trying to check my PR worked in GitPod. 

While my profile did load, all of the links were throwing errors as they were trying to connect to [http://localhost:3000/api/users/grahamthedevrel/links/](http://localhost:3000/api/users/grahamthedevrel/links/) 

So I could not check that I had done everything correctly there.

**Comment by dan-mba** [comment]
I believe this issue is not fixable due to the hackery GitPod performs to handle localhost port mapping. I was able to get the links to the correct server, but GitPod prevented the links from hitting the API route, instead sending them to the 404 page.

**Comment by eddiejaoude** [comment]
Thanks for raising the issue Graham 👍  and thanks Dan for testing and feedback 💪 

We should probably add this message to the docs so people are aware.

**Comment by amandamartin-dev** [comment]
+1 to what Dan mentioned, you will see this when working on a few types of issues via Gitpod (such as authenticated pages).  I do not know that there is a solution but perhaps @Cahllagerfeld would be able to confirm

**Comment by Cahllagerfeld** [comment]
If I'm not mistaken you can use the local companion they provide [[1](https://www.gitpod.io/docs/references/ides-and-editors/local-companion)] or open the workspace in your local vscode. Then there should be a portforwarding to your actual local host

**Comment by MAYANKpandey14** [comment]
Thanks Dan @dan-mba for mentioning this 
I faced this issue while contributing today only.
I agree with @Cahllagerfeld , we can connect our local Vscode but we need to update our docs to provide information to new or beginner contributor as they use Gitpod for contributing and they won't be able to see and debug their changes.
In fact, I used Gitpod for my own first contribution as a beginner.

**Comment by eddiejaoude** [comment]
> I changed the NEXT_PUBLIC_BASE_URL to the http://linkfree.io URL and then clicking on "View Profile" worked fine.

This does not fix the issue, because the link will redirect to production instead of the local dev environment. This link should be updated to the temporary Gitpod environment I think - but I am not sure if there are further challenges

@bikrantjajware please note we use inclusive language in EddieHub,`guys` is not inclusive, try `folks` or `friends` 😉

**Comment by bikrantjajware** [comment]
Yup, it does work with the temporary gitpod url as well.
<img width="1022" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/34072248/7429a326-8f55-4d4f-9b7f-db2082b94046">

Thanks @eddiejaoude , i'll keep that in mind  😊

**Comment by bikrantjajware** [comment]
right, i guess we need to update docs. If it's ok i would like to contribute to update docs

**Comment by eddiejaoude** [comment]
Sure @bikrantjajware I have assigned it to you

**Comment by bikrantjajware** [comment]
Thank you for assigning @eddiejaoude,
Here are my proposed changes:
<img width="972" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/34072248/cfa92366-6835-45f7-a8d9-e065d92b1b2e">

Also adding a note for when gitpod URL updates
<img width="962" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/34072248/0b38da36-9a85-4281-88f9-c61dc53c30fa">

Please suggest.

**Comment by eddiejaoude** [comment]
Looks good 👍
