### ISSUE TITLE
Missing Icon

### ISSUE THREAD

**Issue by qwe123coder** [EddieHubCommunity/LinkFree#693]
### Description

there used to be an arrow icon here 
![image](https://user-images.githubusercontent.com/72848513/142967335-b69a8399-bf2a-42a0-8454-9b7d43ad80e0.png)

but I think it's not there because the icon is too light 
because I can see a <i> tag for it 

![image](https://user-images.githubusercontent.com/72848513/142967687-47c6cfff-bb90-4f58-8462-4b99c30211b8.png)

we can fix it by change the color of the icon or change the icon itself 

### Screenshots

![image](https://user-images.githubusercontent.com/72848513/142967033-b465591b-57ed-4619-a5bc-ac06cee26cf7.png)

a icon is needed there

**Comment by krishguptadev** [comment]
If a color is defined, there is gonna be no icon. Maybe should remove the colors not in use.

**Comment by Panquesito7** [comment]
> If a color is defined, there is gonna be no icon. Maybe should remove the colors not in use.

Looks like we need to use `link` instead 😅 @qwe123coder and I are working on this.

**Comment by krishguptadev** [comment]
> > If a color is defined, there is gonna be no icon. Maybe should remove the colors not in use.
> 
> Looks like we need to use `link` instead 😅 @qwe123coder and I are working on this.

Hmm 🤔 So we need to change all the unsupported socials to `link`?
