### ISSUE TITLE
Light/Dark theme switch doesn’t always hide NavBar

### ISSUE THREAD

**Issue by n1ceFella** [EddieHubCommunity/LinkFree#6940]
### Description

Light/Dark theme switch suppose to hide NavBar when clicked. Clicking theme switch button doesn't always hide menu which:

- not provided by logic 
- creates bad UX design (user may want to continue exploring si)

### Screenshots

https://github.com/EddieHubCommunity/LinkFree/assets/50242030/ca35a36d-9365-4fcd-b42b-68a5af8a74b0

https://github.com/EddieHubCommunity/LinkFree/assets/50242030/af47a040-e62e-4e91-b10b-e9a50cfdddef

**Comment by eddiejaoude** [comment]
I could not replicate this issue, could you share more about your OS and browser?

**Comment by n1ceFella** [comment]
> I could not replicate this issue, could you share more about your OS and browser?
This bug occures in Safari Browser in iOS

**Comment by eddiejaoude** [comment]
> This bug occures in Safari Browser in iOS

Interesting, that is what I am using. Let's see if someone else can replicate it

**Comment by kumarsonsoff3** [comment]
I tried it on Android Chrome & devTools too, but failed to replicate it.

It might be an issue caused due to slow internet or some cached data in your browser!

**Comment by n1ceFella** [comment]
> I tried to replicate this issue on android Chrome, but failed to so. Is this thing issue happened fairly often to you or just a one time thing?

I happenes every 2-3 clicks. I'll try to test it on other devices.

**Comment by shoebilyas123** [comment]
> > I tried to replicate this issue on android Chrome, but failed to so. Is this thing issue happened fairly often to you or just a one time thing?
> 
> I happenes every 2-3 clicks. I'll try to test it on other devices.
I tried to replicate this on chrome and brave but it works fine. Even after 2-3 clicks. Might be a Safari issue.

**Comment by ChinmayMhatre** [comment]
Works fine on android/brave. Issue occurs in safari dev tools. maybe an ios issue
