### ISSUE TITLE
[OTHER] Performance improvements to the UserPage component

### ISSUE THREAD

**Issue by badrivlog** [EddieHubCommunity/LinkFree#6951]
### What would you like to share?

I think we can make a slight performance improvement here [components/user/UserPage.js](https://github.com/EddieHubCommunity/LinkFree/blob/main/components/user/UserPage.js)

![Screenshot (17)](https://github.com/EddieHubCommunity/LinkFree/assets/73095526/bb4436ea-b119-4cb9-b226-45b39f02a739)

The current code snippet utilizes multiple `find` calls to check for specific tab names and access their `current` property. However, this approach can result in potential performance issues. 
To fix this we need to refactor the existing code to incorporate optional chaining (`?.`) in order to enhance its robustness and readability.

### Additional information

Would love to fix this.

Thanks.

**Comment by eddiejaoude** [comment]
It will be interesting to see if that works the same, thank you for the suggestion 👍 I have assigned it to you

**Comment by badrivlog** [comment]
> It will be interesting to see if that works the same, thank you for the suggestion 👍 I have assigned it to you

Yes, it will work same 💯
Thank you!
