### ISSUE TITLE
[DOCS] Alert Boxes

### ISSUE THREAD

**Issue by naomi-lgbt** [EddieHubCommunity/LinkFree#6957]
### Description

We should find a plugin (or build one) that allows us to display alert boxes in the documentation - specifically for calling out important information that is commonly missed.

### Screenshots

Here's what an alert box looks like in Becca's documentation:

![image](https://github.com/EddieHubCommunity/LinkFree/assets/63889819/707b8823-baf1-4391-9755-082a1c01f920)

### Additional information

This doesn't stand out enough and is often missed by contributors:

![image](https://github.com/EddieHubCommunity/LinkFree/assets/63889819/04dc3291-9677-4ebf-a7d6-29fa8b950c25)

**Comment by eddiejaoude** [comment]
We have the Alert component `components/Alert.js` that could be used within the does

**Comment by NiazMorshed2007** [comment]
I can give this a shot. 

However when I was working on showing alert on homepage, I noticed the alerts are fading in and out, maybe using tailwind pulse class, should that style will also be applied here on docs?

**Comment by eddiejaoude** [comment]
Sure, I have signed it to you @NiazMorshed2007 

Yes I think keep it consistent for now 👍

**Comment by NiazMorshed2007** [comment]
Before I submit a pr for this, I'd like to know about which type to use in `Alert` component.
Here are the different views for different types👇
What do you think what to use?
| type | preview |
|--------|--------|
| error | ![image](https://github.com/EddieHubCommunity/LinkFree/assets/77217706/2bee957a-31ea-4e1d-86fc-a234d320d42c)|
| warning | ![image](https://github.com/EddieHubCommunity/LinkFree/assets/77217706/a504bbf4-68dc-43a1-a55c-4b899d324112)|  
| info | ![image](https://github.com/EddieHubCommunity/LinkFree/assets/77217706/6a532280-38df-4381-929c-68f8006b3001)|

**Comment by johntymuriithi** [comment]
I can give it a try

**Comment by SaraJaoude** [comment]
> I can give it a try

@johntymuriithi this Issue has already been assigned to someone else

**Comment by eddiejaoude** [comment]
Looks great @NiazMorshed2007 👍  raise the issue and we can continue the discussion there

**Comment by NiazMorshed2007** [comment]
@eddiejaoude All good! Opening pr

**Comment by SaraJaoude** [comment]
Closing as the Pull Request has been merged.
