### ISSUE TITLE
Add GitHub Organisation profiles suggestion.

### ISSUE THREAD

**Issue by CodingSpecies** [EddieHubCommunity/LinkFree#696]
### Description

I just thought as an idea if it was possible for us to submit profiles of our organisations in LinkFree.
- Maybe, in the bio / description we can explain how to join the org/ what the org is about.
- However, this can not be any organisation, but only the ones you actual are the founder of.
- There could be a seperate page to view different organisations, or in the same page, but highlighted differently so it differs from user profiles.
Thank you.

I am not sure if this can be implemented, but I just thought as an idea.

**Comment by krishguptadev** [comment]
I like the idea, but don't support them to be displayed in a highlighted way.

**Comment by CodingSpecies** [comment]
I was thinking as the user profiles are rounded, maybe the organisation profiles should have some different styling to perhaps look different to the user profiles. This is so you can see which ones are clearly organisations and what are not. @krishguptadev

**Comment by krishguptadev** [comment]
> I was thinking as the user profiles are styled maybe the organisation profiles should have some different styling to perhaps look different to the user profiles. This is so you can see which ones are clearly organisations and what are not. @krishguptadev

But I don't think we need this. Organisation Profiles should be like normal profiles.

**Comment by CodingSpecies** [comment]
Yes @krishguptadev i don’t think it is necessary now. Thank you

**Comment by krishguptadev** [comment]
Can the issue be closed for the same?

**Comment by CodingSpecies** [comment]
I don’t know because I don’t have the answer if we  are able to add the organisations. Once I have the answer, then this can be closed @krishguptadev

**Comment by krishguptadev** [comment]
> I don’t know because I don’t have the answer if we are able to add the organisations. Once I have the answer, then this can be closed @krishguptadev

I just added a org, to clear the doubt 😄 #703

**Comment by CodingSpecies** [comment]
So now at LinkFree we can add our own organisation profiles, shouldn't this be made clear on the CONTRIBUTING.md or README.md?

**Comment by CodingSpecies** [comment]
As I said in #704 
To make only organisations come up in the search, maybe at the end of each profile name, the emoji 📛, which is the badge could be put. `EG: Eddie Hub 📛`.
When you put 📛 in the search all the organisations will come up, as they all have the same badge emoji in their name.

**Comment by krishguptadev** [comment]
> As I said in #704 To make only organisations come up in the search, maybe at the end of each profile name, the emoji 📛, which is the badge could be put. `EG: Eddie Hub 📛`. When you put 📛 in the search all the organisations will come up, as they all have the same badge emoji in their name.

I think it is gonna be more of a badge rather than a emoji at the end of the name

**Comment by Vyvy-vi** [comment]
Imo, I think there needs to be some form of distinction _atleast_ in the JSON schema for the org profile.
Maybe we can add some text about this being an org, in the profile(if we want).

From a maintenance point of view, it would be easier to out-right see it as an org., so that anyone can edit it's data..
(Also, in future we might want to make these open-accessed, instead of being linked through the discord)

**Comment by eddiejaoude** [comment]
I think if we have an *optional* `type` field in the json for `community` | `personal`

There could be multiple PRs
1. updating `community` profiles with the `type: community`
2. [optional] updating the `personal` to `type: community`
3. on homepage display the type in each chip
4. on the profile page display type at the top
5. filter search by type using dropdown

**Comment by qwe123coder** [comment]
> I think if we have an _optional_ `type` field in the json for `community` | `personal`
> 
> There could be multiple PRs
> 
> 1. updating `community` profiles with the `type: community`
> 2. [optional] updating the `personal` to `type: community`
> 3. on homepage display the type in each chip
> 4. on the profile page display type at the top
> 5. filter search by type using dropdown

we could also add like a badge telling its a org

**Comment by emmalearnscode** [comment]
Since the original issue has been done, can we take Eddie's suggestions and turn each into it's own issue so that they're easier to keep track of?

**Comment by CodingSpecies** [comment]
That would be helpful. Do you want me to create separate issues and then close this one @emmalearnscode

**Comment by emmalearnscode** [comment]
@CodingSpecies if you’ve got time then that would be great, otherwise I can do it tomorrow 😊
