### ISSUE TITLE
[DOCS] Alignment of href tags

### ISSUE THREAD

**Issue by iamvbenz49** [EddieHubCommunity/LinkFree#6967]
### Description

the href tags are not aligned properly to the bullet points

![WhatsApp Image 2023-05-18 at 19 10 56](https://github.com/EddieHubCommunity/LinkFree/assets/93785572/b2ec4d5a-e834-412b-9396-5d960eea3908)

### Additional information

it will look better if it is aligned properly to the bullet point and would look nice if we add more example linkfree profiles

**Comment by iamvbenz49** [comment]
I am using kali linux and mozilla firefox

**Comment by ChinmayMhatre** [comment]
@MitAbhay could you tell us your os and browser as you faced the same issue?

@iamvbenz49  Please inspect the bulletpoint and see why the element is breaking

**Comment by MitAbhay** [comment]
@ChinmayMhatre I have faced this issue in Ubuntu and Firefox.

**Comment by ghughes13** [comment]
I'll take this

**Comment by SaraJaoude** [comment]
> I'll take this

@ghughes13 the label on this Issue has not yet changed to `status: ready for dev` and in any event you may wish to check this project's [Contributing Guide ](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md)as to our guidelines on assignment before working on an Issue and raising a PR.

**Comment by ghughes13** [comment]
Ahh sorry. Let me know when it's ready and I'll be happy to knock it out!

It's due to the way Firefox handles <p> tags inside <a> tags.

FireFox Version 113 - Windows 11
![Firefox - Broken](https://github.com/EddieHubCommunity/LinkFree/assets/18102814/67c7ac0a-9126-4bd8-9bd1-1997da535ad4)

**Comment by eddiejaoude** [comment]
> Ahh sorry. Let me know when it's ready and I'll be happy to knock it out!
> 
> It's due to the way Firefox handles <p> tags inside <a> tags.
> 
> FireFox Version 113 - Windows 11 ![Firefox - Broken](https://user-images.githubusercontent.com/18102814/242609332-67c7ac0a-9126-4bd8-9bd1-1997da535ad4.png)

Good spot! What do you think the solution is, as this is generated from MDX?

```mdx
- <Link href="https://github.com/EddieHubCommunity/LinkFree/blob/main/data/eddiejaoude.json">
    Eddie Jaoude
  </Link>
- <Link href="https://github.com/EddieHubCommunity/LinkFree/blob/main/data/amandamartin-dev.json">
    Amanda Martin
  </Link>
- <Link href="https://github.com/EddieHubCommunity/LinkFree/blob/main/data/Pradumnasaraf.json">
    Pradumna Saraf
  </Link>
```

**Comment by SaraJaoude** [comment]
@ghughes13 I have changed the labels and assigned this to you

**Comment by Dev-Arhaan** [comment]
Is this opened to be assigned?
I'd like to work on it.

**Comment by ChinmayMhatre** [comment]
> Is this opened to be assigned?
> I'd like to work on it.

As you can see in the conversation the issue have been assigned. you can see the name of the assignee on the top left.
You can take a look at other open issue which aren't assigned.

You can read the contribution guidelines here incase any doubts  https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md
