### ISSUE TITLE
LinkFree Statistics total views possible problem

### ISSUE THREAD

**Issue by loftwah** [EddieHubCommunity/LinkFree#6984]
### Description

I noticed the total views for my account needed to make more sense. Shouldn't the total number be higher than the from number? Is the calculation correct? I could be reading it wrong.

Total views
16K
from 19K
Increased by2.4K

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/19922556/fd553af0-d2d0-41a9-959b-5b18ce6c3c86)

**Comment by eddiejaoude** [comment]
I actually changed this in the new version as part of the forms to remove confusion, what do you think...

<img width="1667" alt="Screenshot 2023-05-20 at 09 56 10" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/e47990ee-d5bc-45db-a70e-9f6e16df5ecc">

**Comment by amandamartin-dev** [comment]
> I actually changed this in the new version as part of the forms to remove confusion, what do you think...

I think this is more clear! Looks good. Should we close this? I see it's not live yet, but if it's in a branch already no need for this issue

**Comment by loftwah** [comment]
Sounds like it is resolved to me.

**Comment by SaraJaoude** [comment]
This is being done as part of #5575 so I will close
