### ISSUE TITLE
Names are misplaced in example profiles

### ISSUE THREAD

**Issue by MitAbhay** [EddieHubCommunity/LinkFree#6999]
### Description

As we can see, the names mentioned in the example profile are misplaced from their place. CSS needs to be correct.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/76659113/90e79e05-52d3-471e-a1ca-9a061500c397)

**Comment by amandamartin-dev** [comment]
Hello! Closing this as a duplicate of #6967 

Please check out the conversation there if you wish to see the status
