### ISSUE TITLE
We should probably update the readme list of available icons

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/LinkFree#701]
We should probably update the readme list of available icons

_Originally posted by @emmalearnscode in https://github.com/EddieHubCommunity/LinkFree/pull/699#issuecomment-978301579_

**Comment by krishguptadev** [comment]
Can I know that what icon are to be added?

**Comment by emmalearnscode** [comment]
Yes, this issue came directly from a comment in another thread so it is a bit vague. Portfolios are now using globe icon instead of link icon so globe needs adding to the readme section about available  icons

**Comment by krishguptadev** [comment]
Globe icon has been fixed, #702

**Comment by schmelto** [comment]
Closed in #702
