### ISSUE TITLE
LinkFree TotalLinkClick get increase on own's click

### ISSUE THREAD

**Issue by Akhilbisht798** [EddieHubCommunity/LinkFree#7011]
### Description

The Total Link Click in Profile get increase on one's own click.

If it is supposed  to be that way then i get.

### Screenshots

![Screenshot from 2023-05-19 21-37-20](https://github.com/EddieHubCommunity/LinkFree/assets/92508481/b11f3653-9917-4fac-8aee-ff1690d6a536)

**Comment by eddiejaoude** [comment]
> The Total Link Click in Profile get increase on one's own click.

Please can you explain a bit more, what steps you took?

**Comment by Akhilbisht798** [comment]
Total link click will increase even when you have clicked any one of your social link.
Is that suppose to be the way it is or should we change it.
I suppose our own click count will be low so is it worth changing it.

**Comment by eddiejaoude** [comment]
Yes it will be low, but we can do a check to see if they are the owner or not, similar to how it was done on profile views (but only works if they are logged in)

**Comment by Akhilbisht798** [comment]
Assign me i can do this.

**Comment by SaraJaoude** [comment]
> Assign me i can do this.

@Akhilbisht798 I will assign this to you
