### ISSUE TITLE
[FEATURE] admin page to manage profiles

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#7022]
### Description

Page started with `/admin/statistics` (and protected by environment variable), this issue should create `admin/users`

TODO
- [ ] admin API profiles
- [ ] admin page list profiles
   - [ ] include `source` field
   - [ ] default list last 10 recently updated profiles
- [x] access to this page is restricted by an environment variable `ADMIN_USERS` list of usernames (separated by commas) in the `.env`
- [x] show basic stats (totals)
- ~~delete button to delete all user's data in DB (must type in their username to confirm)~~ Separate Issue/PR

We can use the Tailwind component https://tailwindui.com/components/application-ui/lists/stacked-lists#component-13acf9810a8e9f90cc6a67a4b6d8b8f7

```js
import { ChevronRightIcon } from '@heroicons/react/20/solid'

const people = [
  {
    name: 'Leslie Alexander',
    email: 'leslie.alexander@example.com',
    role: 'Co-Founder / CEO',
    imageUrl:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    href: '#',
    lastSeen: '3h ago',
    lastSeenDateTime: '2023-01-23T13:23Z',
  },
  {
    name: 'Michael Foster',
    email: 'michael.foster@example.com',
    role: 'Co-Founder / CTO',
    imageUrl:
      'https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    href: '#',
    lastSeen: '3h ago',
    lastSeenDateTime: '2023-01-23T13:23Z',
  },
  {
    name: 'Dries Vincent',
    email: 'dries.vincent@example.com',
    role: 'Business Relations',
    imageUrl:
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    href: '#',
    lastSeen: null,
  },
  {
    name: 'Lindsay Walton',
    email: 'lindsay.walton@example.com',
    role: 'Front-end Developer',
    imageUrl:
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    href: '#',
    lastSeen: '3h ago',
    lastSeenDateTime: '2023-01-23T13:23Z',
  },
  {
    name: 'Courtney Henry',
    email: 'courtney.henry@example.com',
    role: 'Designer',
    imageUrl:
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    href: '#',
    lastSeen: '3h ago',
    lastSeenDateTime: '2023-01-23T13:23Z',
  },
  {
    name: 'Tom Cook',
    email: 'tom.cook@example.com',
    role: 'Director of Product',
    imageUrl:
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    href: '#',
    lastSeen: null,
  },
]

export default function Example() {
  return (
    <ul role="list" className="divide-y divide-gray-100">
      {people.map((person) => (
        <li key={person.email} className="relative flex justify-between gap-x-6 py-5">
          <div className="flex gap-x-4">
            <img className="h-12 w-12 flex-none rounded-full bg-gray-50" src={person.imageUrl} alt="" />
            <div className="min-w-0 flex-auto">
              <p className="text-sm font-semibold leading-6 text-gray-900">
                <a href={person.href}>
                  <span className="absolute inset-x-0 -top-px bottom-0" />
                  {person.name}
                </a>
              </p>
              <p className="mt-1 flex text-xs leading-5 text-gray-500">
                <a href={`mailto:${person.email}`} className="relative truncate hover:underline">
                  {person.email}
                </a>
              </p>
            </div>
          </div>
          <div className="flex items-center gap-x-4">
            <div className="hidden sm:flex sm:flex-col sm:items-end">
              <p className="text-sm leading-6 text-gray-900">{person.role}</p>
              {person.lastSeen ? (
                <p className="mt-1 text-xs leading-5 text-gray-500">
                  Last seen <time dateTime={person.lastSeenDateTime}>{person.lastSeen}</time>
                </p>
              ) : (
                <div className="mt-1 flex items-center gap-x-1.5">
                  <div className="flex-none rounded-full bg-emerald-500/20 p-1">
                    <div className="h-1.5 w-1.5 rounded-full bg-emerald-500" />
                  </div>
                  <p className="text-xs leading-5 text-gray-500">Online</p>
                </div>
              )}
            </div>
            <ChevronRightIcon className="h-5 w-5 flex-none text-gray-400" aria-hidden="true" />
          </div>
        </li>
      ))}
    </ul>
  )
}
```

**Comment by Vishrut19** [comment]
I can work on it

**Comment by Vishrut19** [comment]
Hey! Can I get some more context on this issue?

**Comment by eddiejaoude** [comment]
I have updated the issue description

**Comment by Vishrut19** [comment]
So, I need to create a new file in the `pages` folder called `admin` right and then add the above code and above-mentioned functionalities. Right?

**Comment by eddiejaoude** [comment]
> So, I need to create a new file in the `pages` folder called `admin` right and then add the above code and above-mentioned functionalities. Right?

Yes that is correct 👍  I suggest `pages/admin/users.js`

**Comment by Vishrut19** [comment]
Hoping asking a lot of questions won't bother ?

**Comment by Vishrut19** [comment]
> > So, I need to create a new file in the `pages` folder called `admin` right and then add the above code and above-mentioned functionalities. Right?
> 
> 
> 
> Yes that is correct 👍  I suggest `pages/admin/users.js`

Also, can you please help me with the endpoint for fetching user data and list of users ?

**Comment by eddiejaoude** [comment]
> Hoping asking a lot of questions won't bother ?

no, specific questions are good, but please try to keep extra notifications down otherwise it spams the maintainers and community

> Also, can you please help me with the endpoint for fetching user data and list of users ?

You will need to create a new end point, similar path to the new page `pages/api/admin/users.js`

**Comment by Vishrut19** [comment]
> > Hoping asking a lot of questions won't bother ?
> 
> no, specific questions are good, but please try to keep extra notifications down otherwise it spams the maintainers and community
> 
> > Also, can you please help me with the endpoint for fetching user data and list of users ?
> 
> You will need to create a new end point, similar path to the new page `pages/api/admin/users.js`

Hey Eddie! Can you please help me how to build this endpoint? And also how to test it?

**Comment by amandamartin-dev** [comment]
@eddiejaoude Sorry for the delay, here are my notes from the stream...

light mode, dark mode
accessibility review for the OOTB tailwind component
search and filter to display profiles
what happens on profile click (expand detail, new page, out to public profile, something else)
dev env for folks to work on issues related to this page even if they don't have admin access?
testing rules, pr merge rules for production (since real profiles can be deleted, in some cases only an admin will be able to approve?)
security on the API, any CRUD actions, and on the page itself
Deleting vs. Deactivating accounts
compliance - how/where to manage any requests for data modification, deletions. Are we being compliant with all regulations
I have a note about refactoring the Icons page (not related to admin, just an aside)
another note about creating a helper for date/time displays versus writing these each time on the page
a note about moving any place we build image urls to the API's (check maps, not sure where else)
make sure all admin page user intents are understood first before building out features
