### ISSUE TITLE
We need a h1 on homepage

### ISSUE THREAD

**Issue by gptkrsh** [EddieHubCommunity/LinkFree#7032]
### Description

Because there is no h1 on homepage, which disrupts the heading hierachies

### Additional information

Check for other pages <3

(By @GrahamTheDevRel from the livestream)

**Comment by anikdhabal** [comment]
I would like to work in this issue?

**Comment by SaraJaoude** [comment]
> I would like to work in this issue?

@anikdhabal I will assign this to you
