### ISSUE TITLE
[BUG] GitHub Accelerator program should not be a heading

### ISSUE THREAD

**Issue by gptkrsh** [EddieHubCommunity/LinkFree#7033]
### Description

It should be a increased size using css but not an heading by markup

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/91655303/a3eb6359-a45f-4ba7-9100-88291985e558)

### Additional information

By @GrahamTheDevRel in the livestream

**Comment by Gauravrandheer** [comment]
I can do this. Please assign to me

**Comment by SaraJaoude** [comment]
> I can do this. Please assign to me

@Gauravrandheer I will assign this to you
