### ISSUE TITLE
[BUG] Github navbar logo needs more padding and less margin. (Especially when tabbing)

### ISSUE THREAD

**Issue by sabrinalzbh** [EddieHubCommunity/LinkFree#7034]
### What would you like to share?

This issue is raised for the improvement of accessibility.

**Comment by anikdhabal** [comment]
can you assign me to this issue?

**Comment by AliMora83** [comment]
I also just forked it 🤣
I'll look for another **'beginner issue'** 👍🏼

**Comment by SaraJaoude** [comment]
> can you assign me to this issue?

@anikdhabal I have already assigned an issue to you: https://github.com/EddieHubCommunity/LinkFree/issues/7032

We appreciate your enthusiasm but in future please do not ask for multiple issues to be assigned to you.  We only assign one issue per person.  If you request various issues then this creates added noise, confusion and notifications as well as extra work for the maintainers.

**Comment by SaraJaoude** [comment]
> I also just forked it 🤣
> I'll look for another **'beginner issue'** 👍🏼

@AliMora83 I will assign this to you but please familiarise yourself with this project's Contributing Guide: https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md 

namely: 
1. Request to be assigned an issue
2. Once it is assigned to you then create a Pull Request to make the changes

**Comment by AliMora83** [comment]
Noted and thank you @SaraJaoude 🙏🏼🥳

**Comment by ayushlohmod** [comment]
Does this Issue is fixed? if not i really like to work on this

**Comment by AliMora83** [comment]
Yes, it was. 🥳


Before:
<img width="273" alt="Screenshot 2023-05-23 at 09 44 13" src="https://github.com/EddieHubCommunity/LinkFree/assets/56822813/fd2f9026-9d5e-4a70-83cf-d4cdf760b2b9">

After:
<img width="268" alt="Screenshot 2023-05-23 at 10 11 22" src="https://github.com/EddieHubCommunity/LinkFree/assets/56822813/296a38c5-0d47-4a70-9ef9-85ab2aff0a2c">

**Comment by SaraJaoude** [comment]
As the PR relating to this Issue has been merged, I will now close this.

**Comment by AliMora83** [comment]
Thank you @SaraJaoude 🥳
