### ISSUE TITLE
Locally you won't know that you have to reload DB to have search/other features work

### ISSUE THREAD

**Issue by gptkrsh** [EddieHubCommunity/LinkFree#7035]
### Description

Create a banner for this, using the env variables `VERCEL` and `VERCEL_ENV`

### Additional information

/cc @eddiejaoude (you told me to create this issue as a reminder to you)

**Comment by eddiejaoude** [comment]
Krish I thought you forgot to raise the issue, so I created one also, so I will close as duplicate  https://github.com/EddieHubCommunity/LinkFree/issues/7020
