### ISSUE TITLE
[BUG] The tags on the search page should be buttons 

### ISSUE THREAD

**Issue by sabrinalzbh** [EddieHubCommunity/LinkFree#7037]
### What would you like to share?

This issue is raised for improving accessibility.

**Comment by kishoreravi24** [comment]
I can give it a try

**Comment by SaraJaoude** [comment]
> I like to give a try on this bug work

@kishoreravi24 I will assign this to you

**Comment by SaraJaoude** [comment]
I will close as the PR for this Issue has been merged
