### ISSUE TITLE
[FEATURE] Change tag text color on select

### ISSUE THREAD

**Issue by shoebilyas123** [EddieHubCommunity/LinkFree#7040]
### Description

Tags text colour when selected on search page should change to black color instead of white to improve readibility.
![Screenshot from 2023-05-20 20-06-47](https://github.com/EddieHubCommunity/LinkFree/assets/73349037/5a5fe181-8286-4924-9640-3a37f188a80b)

**Comment by JayK1524** [comment]
Hello, I'm interested in working on this. Please assign me this issue.

**Comment by Rahullokare** [comment]
Hey folks, I'm excited to contribute to my first open-source project, and I believe I've found the perfect task, to begin with.
Would it be possible to assign me this one? Thank you.

**Comment by Ayushchaudhary-Github** [comment]
is this issue open?

**Comment by SaraJaoude** [comment]
> Hello, I'm interested in working on this. Please assign me this issue.

@JayK1524 as you have been the first to request after the labels have changed I will assign this to you
