### ISSUE TITLE
[BUG] Profile page links on hover are not accessible 

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/LinkFree#7042]
### Description

Current focus indicate for links is changing the border, but it would be good to change the background.

UPDATE...

On hover (especially in dark mode) only the border of the link changes colour, the background should change also to show it is being hovered

- the background colour change on hover will be needed for light and dark mode
- we have prebuilt classes you can use from `tailwind.config.js`

Any questions let us know

<img width="1668" alt="Screenshot 2023-05-26 at 20 15 36" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/140aa428-6d76-4d1f-a0b4-ca73614a1b7f">

**Comment by Annie154** [comment]
Hello maintainers, i would love to work on this issue.

**Comment by JayK1524** [comment]
Hello, I'm interested in working on this. Please assign me this issue.

**Comment by SaraJaoude** [comment]
> Hello maintainers, i would love to work on this issue.

@Annie154 as you were the first to request this after the label changed I will assign this to you

**Comment by SaraJaoude** [comment]
> Hello, I'm interested in working on this. Please assign me this issue.

@JayK1524 please see my comment on: https://github.com/EddieHubCommunity/LinkFree/issues/7041

**Comment by Kevin-Usadadiya** [comment]
I would like to work on this issue please, I know Web dev a better, I can help to resolve this

**Comment by SaraJaoude** [comment]
> I would like to work on this issue please, I know Web dev a better, I can help to resolve this

@Kevin-Usadadiya in future please check the historic comments - this issue has already been assigned to someone else. Also please do not request multiple issues to be assigned to you in the hope that one will be assigned (we only assign one issue per person at a time) as this creates extra work for maintainers.  You may wish to have a look at our [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) to familiarise yourself with how this project is run.

**Comment by Kevin-Usadadiya** [comment]
oh sorry, I didn't know that

**Comment by Annie154** [comment]
Could you please provide me screenshot. This is my first issue

**Comment by SaraJaoude** [comment]
> Could you please provide me screenshot. This is my first issue

@Annie154 the Description has been updated to have more information and also a screenshot. Thank you for asking this question as it was unclear - we want to make sure that our first time contributors get the support they need. 

We are glad that you have decided to contribute, but in future it would be best to make sure that you ask any questions about the issue and understand what steps need to be taken to resolve it before you ask for the issue to be assigned to you.

Any more questions, let us know!

**Comment by ChinmayMhatre** [comment]
@Annie154 How are you coming along with this issue? let us know if you need any more help regarding this.

**Comment by Ankur1493** [comment]
This issue is open from 3 weeks if no one is working can I pick it up?

**Comment by eddiejaoude** [comment]
@Ankur1493 thank you for your enthusiasm but you just requested another [issue](https://github.com/EddieHubCommunity/LinkFree/issues/7492) to be assigned to you, which I have. Please only request 1 issue at a time to avoid blocking other contributors - I suggest familiarising yourself with our contributing guide to avoid creating extra notifications and work for the maintainers https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by yashug** [comment]
@SaraJaoude @eddiejaoude  I noticed that this issue has been open for the past three weeks. If no one is currently working on it, would it be possible for me to pick it up?

I'm willing to contribute my skills and efforts to help resolve this issue.

**Comment by SaraJaoude** [comment]
> SaraJaoude eddiejaoude I noticed that this issue has been open for the past three weeks. If no one is currently working on it, would it be possible for me to pick it up?
> 
> I'm willing to contribute my skills and efforts to help resolve this issue.

@yashug I have assigned this to you.  In future please avoid tagging specific maintainers as all maintainers can assign issues.

**Comment by yashug** [comment]
ok thanks
