### ISSUE TITLE
[BUG] Testimonial page add testimonial needs hover

### ISSUE THREAD

**Issue by zaidahmad25** [EddieHubCommunity/LinkFree#7043]
## Problem Statement

Add a focus indicator on hover to the `Add testimonial` button for better accessibility.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/39582467/7f48d705-c7ab-42df-b199-62e7e69a8227)

**Comment by marteenaf** [comment]
Hi! I'm new and this would be my first contribution, I would like to be assigned to this issue please! :)

**Comment by pathull** [comment]
Hello! Can you please advise on how to route to this page locally? I created mock data in both users and profiles schemas in MongoDB with matching ids but I am getting user not found even though the tags appear above search and "Active Users
1 from 2K" appears on home page. Basically just trying to get to the endpoint to see this button while adding the requested focus on hover for accessibility.

**Comment by SaraJaoude** [comment]
> Hi! I'm new and this would be my first contribution, I would like to be assigned to this issue please! :)

@marteenaf as you were the first to request assignment when labels changed, I will assign this to you.

**Comment by marteenaf** [comment]
> > Hi! I'm new and this would be my first contribution, I would like to be assigned to this issue please! :)
> 
> @marteenaf as you were the first to request assignment when labels changed, I will assign this to you.

Thanks @SaraJaoude !

**Comment by eddiejaoude** [comment]
> Hello! Can you please advise on how to route to this page locally? I created mock data in both users and profiles schemas in MongoDB with matching ids but I am getting user not found even though the tags appear above search and "Active Users
> 1 from 2K" appears on home page. Basically just trying to get to the endpoint to see this button while adding the requested focus on hover for accessibility.

@pathull sorry I just saw your comment. You need to visit the url `/api/system/reload?secret=development` to load the json files into the db - sorry for the confusion, this was a recent change. Any questions, come and ask in the EddieHub Discord, you will get a faster response
