### ISSUE TITLE
[BUG] Testimonial page text need more color contrast.

### ISSUE THREAD

**Issue by sabrinalzbh** [EddieHubCommunity/LinkFree#7048]
### What would you like to share?

Edits for improved accessibility. 

<img width="1374" alt="Screenshot 2023-05-26 at 09 34 55" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/5ea92960-9d01-416b-bb16-bbed19fedc03">

**Comment by JayK1524** [comment]
Hello, I'm interested in working on this. Please assign me this issue.

**Comment by SaraJaoude** [comment]
> Hello, I'm interested in working on this. Please assign me this issue.

@JayK1524 Please see my comments on several other issues today which explain why we cannot assign this issue to you at this time

**Comment by johntymuriithi** [comment]
Can I work on this one

**Comment by SaraJaoude** [comment]
> Can I work on this one

@johntymuriithi I have assigned this to you

**Comment by SaraJaoude** [comment]
> Hi, I'd like this one be assigned to me. I'm new and this would be my first contribution.

@rustybatmobile I have just assigned another issue to you.  As per our [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) we only assign one issue per person. 

We appreciate your enthusiasm but in future please do not ask to be assigned to various issues in the expectation that one of these will be assigned to you.  I am sure you will appreciate this creates extra work for maintainers as well as notifications and noise.

**Comment by ChinmayMhatre** [comment]
@sabrinalzbh could you specify what changes are you suggesting.

**Comment by luckyklyist** [comment]
is this issue has been assigned ? I am happy to work on it  if it is still open  .

**Comment by SaraJaoude** [comment]
> is this issue has been assigned ? I am happy to work on it if it is still open .

@luckyklyist yes it has.  In future can I please ask that you look at the top right of the page under the `Assignees` section - this will answer your question and reduce unnecessary notifications for maintainers.

**Comment by amandamartin-dev** [comment]
We recently closed a similar issue as "wont do" re: color contrast as we are meeting the AA standard across the site. I'm not sure which text this is specifically referring to and if it means dark and/or light mode, but just wanted to make sure this isn't related to the same closed issue. Take a look #6572

**Comment by eddiejaoude** [comment]
Thanks Amanda, great point 👍 

This was raised as part of the live stream with Graham but you are correct, the colours are the same as #6572 so the same rule will apply.

Plus there is a new redesign coming soon.

Thanks @sabrinalzbh for raising though. 

Sorry @johntymuriithi I will close this issue, please have a look at other open issues

**Comment by sabrinalzbh** [comment]
> Thanks Amanda, great point 👍 
> 
> 
> 
> This was raised as part of the live stream with Graham but you are correct, the colours are the same as #6572 so the same rule will apply.
> 
> 
> 
> Plus there is a new redesign coming soon.
> 
> 
> 
> Thanks @sabrinalzbh for raising though. 
> 
> 
> 
> Sorry @johntymuriithi I will close this issue, please have a look at other open issues

No probable at all @eddiejaoude! And thank you @amandamartin-dev for catching that!
