### ISSUE TITLE
[BUG]: Playground page submit buttons should not be replaced

### ISSUE THREAD

**Issue by shoebilyas123** [EddieHubCommunity/LinkFree#7053]
### Description

Playground page submit buttons are being replaced but should not be and should have the text updated

**Comment by AJcodes42** [comment]
Hi, Would like to know more about this issue as was not able to understand from the description.
In playground page I can see the below given error on click of preview. Is that the issue?
<img width="995" alt="Screenshot 2023-05-21 at 6 52 15 PM" src="https://github.com/EddieHubCommunity/LinkFree/assets/29297057/dbdf128b-d537-47f5-b1be-407be18453da">

**Comment by bharathkalyans** [comment]
* @shoebilyas123   Please attach snapshots, so that it becomes easier to understand the issue and make other developer's lives easier 😀

**Comment by amitabh-sahu** [comment]
Hi, I'm want to work on this. Please assign me this issue.

**Comment by SaraJaoude** [comment]
> Hi, I'm want to work on this. Please assign me this issue.

@amitabh-sahu I will assign this to you.
