### ISSUE TITLE
[BUG] Rename "users" API to "profiles"

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#7072]
### Description

We use the model `profile` but the api path is `users`, this should be renamed to `profiles`

**Comment by daxitpatel** [comment]
Hey folks,

This issue would be perfect for me who is making the first ever open source contribution, has some BE knowledge, but no experience with Next.js.

Would it be possible to assign me this one? Thank you.

**Comment by eddiejaoude** [comment]
Sure @daxitpatel I have assigned it to you

**Comment by AliMora83** [comment]
All the best, @daxitpatel 🥳

**Comment by SaraJaoude** [comment]
@daxitpatel how are you getting on with raising a PR for this Issue?

**Comment by daxitpatel** [comment]
Hey @SaraJaoude . Hope you are doing well.

Actually, I was away the last week. So, could not look much into this. Set up the project and GitHub OAuth2 flow in my local machine 🎉. PR should be available tomorrow.

Thank you,
