### ISSUE TITLE
social icons repeatation

### ISSUE THREAD

**Issue by priyazsh** [EddieHubCommunity/LinkFree#7100]
### Description

In my Linkfree [profile](https://linkfree.io/oyepriyansh), there is a repetition of social icons that I added only once, as you can see in the screenshot provided below and in the [JSON file](https://github.com/EddieHubCommunity/LinkFree/blob/main/data/oyepriyansh.json).

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/83062406/8039a128-d495-49f3-be65-cc0d3bdac4fb)

**Comment by eddiejaoude** [comment]
Sorry for the inconvenience, this usually happens with boundary conditions, I will look into it now - thank you for raising the issue
