### ISSUE TITLE
Hot reloading does not work when project is set using docker compose up.

### ISSUE THREAD

**Issue by Harrish-Selvarajah** [EddieHubCommunity/LinkFree#7102]
### Description

When a developer sets up the project using docker. The project does not support hot reloading hence the dev has to stop the container and run it again every time a change is made.

I was able to identify a fix for this:

![image](https://github.com/EddieHubCommunity/LinkFree/assets/42291934/18d8f19e-1764-4300-aa1c-503104628db6)

![image](https://github.com/EddieHubCommunity/LinkFree/assets/42291934/22f8c505-4f87-4f2f-b626-b8156db3d19d)

If this issue persists for other devs too, I can take this up and push a fix :)

**Comment by SaraJaoude** [comment]
@Harrish-Selvarajah thank you for raising and figuring the fix - I have assigned this to you.

**Comment by ChinmayMhatre** [comment]
@Harrish-Selvarajah How are you coming along with the issue? could you give an update and do let us know if you need any help

**Comment by Harrish-Selvarajah** [comment]
Hi @ChinmayMhatre , been a bit busy with work for the past week. Will try to push a PR today 👍
