### ISSUE TITLE
[DOCS] <Guide on discussing the impact of contributions to Open Source Projects>

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/LinkFree#7120]
### Description

 In the open source community, I haven't seen discussions on how contributors can mention their open source experience in their resume or during a job interview. I think EddieHub members(and open source contributors in general) would benefit greatly from a guide that provides tips on this. What do you think?

**Comment by SaraJaoude** [comment]
@CBID2 this is a good discussion point generally but it does not specifically relate to how LinkFree can progress, so this Repo would not be the appropriate place for this. I will therefore be closing this issue. 

I would suggest a more appropriate place will be the Support Repo in the EddieHub Org. However before you raise an Issue there, this idea needs some more thought.  The title refers to a `Guide on discussing` which implies a guide on how to discuss something, yet the description refers more to a guide on how to add open source contributions to your resume. In my view the latter may more what you are trying to achieve?  Please can you raise a Discussion [here](https://github.com/orgs/EddieHubCommunity/discussions/new/choose) - perhaps you could also include the tips you have thought of?
