### ISSUE TITLE
[fix] Possible plagarism

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/LinkFree#7122]
### What would you like to share?

I found [this](https://github.com/MichaelBarney/LinkFree) when I typed GitHub into the search engine. Have you seen this before @eddiejaoude?

**Comment by SaraJaoude** [comment]
@CBID2 thank you for bringing this to our attention.  Unfortunately this is not the first time this has happened, there are other instances where LinkFree has been copied - however in this case in fact it seems the Repo was created before ours back in 2019. This is of course permitted in open source but, I appreciate seeing vastly similar projects can be quite frustrating when all the community is working so hard contributing to make LinkFree unique. 

It seems also this project has not had any contributions, but in any event I don't think there is anything we could really do about.
