### ISSUE TITLE
[DOCS] Better formatting of text in the Events documentation.

### ISSUE THREAD

**Issue by MAYANKpandey14** [EddieHubCommunity/LinkFree#7139]
### Description

Information in the Events documentation page is not formatted properly which may cause difficulty for the user to understand.
This small fix will bring more clarity in documentation.

### Screenshots

For Example can be written in the second line for better visibility 
![Screenshot 2023-05-23 174216](https://github.com/EddieHubCommunity/LinkFree/assets/94740455/8899f02b-8464-4ea0-8ae4-2a02d3d0e125)

Extra line spacing and a ";" can be seen
![Screenshot 2023-05-23 174225](https://github.com/EddieHubCommunity/LinkFree/assets/94740455/bdb30652-2964-47c3-872c-d78b60a50d42)

**Comment by SaraJaoude** [comment]
Removing the blank line and `;` would be a good improvement.

**Comment by tusharkumar19701** [comment]
I am new to open source and I would like to contribute. Please assign me.

**Comment by MAYANKpandey14** [comment]
> Removing the blank line and `;` would be a good improvement.
> 
> @MAYANKpandey14 do you want this assigned to you

Thank you, However I think this can become someone's first pull request.

**Comment by SaraJaoude** [comment]
> I am new to open source and I would like to contribute. Please assign me.

@tusharkumar19701 I will assign this to you

**Comment by tusharkumar19701** [comment]
@SaraJaoude Thanks for assigning me this issue.

**Comment by tusharkumar19701** [comment]
what to do after cloning it in my terminal......unable to open the file

**Comment by tusharkumar19701** [comment]
sorry I just don't know how to do it....I am unassigning myself

**Comment by AliMora83** [comment]
> sorry I just don't know how to do it....I am unassigning myself

I'll assist you, @tusharkumar19701 🥳

**Comment by AliMora83** [comment]
> > what to do after cloning it in my terminal......unable to open the file
> 
> It will be saved as a Folder with the Name LinkFree . Open it and go to pages/docs/how-to-guides/events.mdx LinkFree -> pages -> docs -> how-to-guides -> events.mdx This events.mdx file is what you have to edit to debug the issue .
> 
> Ask freely @tusharkumar19701 if you get stuck in future . No need to get demotivated and quit, it is a part of the process, there is always something you are absolute beginner in.

So True 🥳

**Comment by jaskarandji** [comment]
Hi, I ✋ would like to work on that issue, if that would be ok please assign me the issue. I can do that changes.

**Comment by SaraJaoude** [comment]
> sorry I just don't know how to do it....I am unassigning myself

@tusharkumar19701 We appreciate that if you do not feel ready to work on an issue that you mention this - we want our contributors to feel comfortable.  Don't forget that when you are ready to contribute again you can check out the list of unassigned 'good first issues' which I have added [here](https://github.com/EddieHubCommunity/LinkFree/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee).

 Also, as others have said here please do reach out and ask questions in the EddieHub Discord! Whilst maintainers prefer that conversation regarding an issue is done publicly on the issue's comments so they can help, Discord is a great way to bounce ideas and get the community's feedback.

**Comment by SaraJaoude** [comment]
> Hi, I ✋ would like to work on that issue, if that would be ok please assign me the issue. I can do that changes.

@jaskarandji I have assigned this to you.

**Comment by tusharkumar19701** [comment]
Thanks all of you for showing your support. I would definitely try to contact community members if I have any issues. I was just frustrated at that moment. After spending hours I was clueless, so that's why I unassigned myself. Next time I won't be quitting, I will definitely try to ask my doubts and clear them. Sorry for causing disturbance.

**Comment by jaskarandji** [comment]
I have set the formatting of text and I want to ask that I created a separate branch for edit to debug the issue. My branch is now ready to go. Should I merge it with the main branch or should I do this 👇 ?
![Debuging](https://github.com/EddieHubCommunity/LinkFree/assets/89390268/cb3f324a-92c7-443d-982d-9606d4304e86)
![Set it](https://github.com/EddieHubCommunity/LinkFree/assets/89390268/ed487036-71f2-49ff-8b1d-19d06aeafeb4)

**Comment by SaraJaoude** [comment]
@jaskarandji please do as you mention in the screenshot (create Pull Request from your fork repo's branch `Text-Format` to the EddieHub LinkFree `main` branch).

This will then appear on our list of Pull Requests and will be reviewed by a maintainer in due course.

**Comment by eddiejaoude** [comment]
merged
