### ISSUE TITLE
[OTHER] Improved management of ISR revalidation intervals using a configuration file

### ISSUE THREAD

**Issue by badrivlog** [EddieHubCommunity/LinkFree#7142]
### What would you like to share?

Currently, Linkfree uses Incremental Static Regeneration (ISR) for some pages,
managing the `revalidate` values for different pages becomes crucial for customization and maintainability. I propose implementing a configuration file specifically for managing ISR revalidation intervals to enhance code organisation and provide more flexibility.

**Benefits**

- Centralized configuration: A dedicated configuration file consolidates all `revalidate` values in one place, providing a clear overview of regeneration intervals for different pages.
- Easy customization: The configuration file allows for simple adjustments of the regeneration intervals without modifying the code directly, offering flexibility as requirements evolve.
- Separation of concerns: Separating `revalidate` values from page-specific logic ensures a clear distinction between regeneration configuration and data fetching/rendering, improving code modularity.
- Scalability and maintainability: As the application expands with additional pages, a configuration file simplifies updates and modifications, contributing to code maintainability.
- Dynamic values: The configuration file approach supports dynamic `revalidate` values, enabling fetching from external sources, using environment variables, or calculating intervals based on conditions.
- Collaboration and team workflows: With a configuration file, developers can easily collaborate and make changes to regeneration intervals, ensuring consistency across the project.

**Changes proposed**

- Create a configuration file (e.g., `isr.js`) to store `revalidate` values for different pages.
- Import the configuration file into the `getStaticProps` function for each page and utilize the appropriate `revalidate` value from the configuration object.
- Update the configuration file as needed to reflect the desired `revalidate` intervals for each page.

This enhancement will improve the management of ISR revalidation intervals, leading to a more organized codebase, easier customization, and streamlined collaboration among team members.

### Additional information

Happy to work on this 👍

Thanks

**Comment by SaraJaoude** [comment]
@badrivlog I have updated the labels so this shows `status: ready for dev` and I have assigned this to you

**Comment by eddiejaoude** [comment]
Thanks for the suggestion 👍 We could probably using the existing app config file `config/app.json` and add a new object to it with...

```js
{
   // ...
   isr: {
      
   }
}
```
