### ISSUE TITLE
Layout needs a html header

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#7148]
### Description

In the navbar component change the parent `div` to `header`

**Comment by sabrinalzbh** [comment]
I'd like to work on this.🤓

**Comment by SaraJaoude** [comment]
> I'd like to work on this.🤓

@sabrinalzbh I have assigned this to you

**Comment by sabrinalzbh** [comment]
> > I'd like to work on this.🤓
> 
> 
> 
> @sabrinalzbh I have assigned this to you

Thank you, Sara!
