### ISSUE TITLE
[FEATURE] Create A "Label" within Github for "Design" Feats & Updates

### ISSUE THREAD

**Issue by sabrinalzbh** [EddieHubCommunity/LinkFree#7151]
### Description

I had an idea to create a new label to add design ideas to the project as it is not a popular topic in Github. 

Hopefully, designers can contribute more to enhancing the UX/UI aspect of the site.

**Comment by eddiejaoude** [comment]
Thank you for raising Sabrina! I was just going to create the label but noticed we have `interface`, which is very similar.

Sorry for the confusion but I will come this issue.

<img width="246" alt="Screenshot 2023-05-24 at 11 24 32" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/6c4c5c23-2799-4acc-8c8f-d189fa88e740">

**Comment by sabrinalzbh** [comment]
> Thank you for raising Sabrina! I was just going to create the label but noticed we have `interface`, which is very similar.
> 
> 
> 
> Sorry for the confusion but I will come this issue.
> 
> 
> 
> <img width="246" alt="Screenshot 2023-05-24 at 11 24 32" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/6c4c5c23-2799-4acc-8c8f-d189fa88e740">
> 
> 

Ahhhh, I missed that! All good. Thank you, Eddie!
