### ISSUE TITLE
[BUG] links in bio with markdown do not have any visual identification

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#7152]
### Description

Links in the bio with markdown work but they don't have our app's link styles on it

> I believe in order to make this work, the `<a>` tag will need to be overridden in [react-markdown](https://github.com/remarkjs/react-markdown#appendix-b-components)

Suggested by Dan https://github.com/EddieHubCommunity/LinkFree/issues/7152#issuecomment-1560944413

**Comment by MAYANKpandey14** [comment]
Can you provide some screenshots Eddie

**Comment by MAYANKpandey14** [comment]
#7139 #7043 these issues conversations are locked . Kindly look into this.

**Comment by harshpatel-r** [comment]
Hey folks,

I'm new to open source contributions, but I understand backend development well. Although my main expertise is in backend, I also have enough knowledge of front-end development to solve this problem. I see this as a valuable opportunity  to contribute as a front-end developer. 

Could you please assign this issue to me? Thanks!

**Comment by dan-mba** [comment]
I believe in order to make this work, the `<a>` tag will need to be overridden in [react-markdown](https://github.com/remarkjs/react-markdown#appendix-b-components)

**Comment by MAYANKpandey14** [comment]
> > #7139 #7043 these issues conversations are locked . Kindly look into this.
> 
> I have unlocked these issues

Thank you Buddy @ChinmayMhatre

**Comment by badrivlog** [comment]
> > > #7139 #7043 these issues conversations are locked . Kindly look into this.
> > 
> > I have unlocked these issues
> 
> @ChinmayMhatre thank you! I forgot to unlock when I changed the labels.

@SaraJaoude  kindly unlock #7142 this issue also

**Comment by KushagraVarshney05** [comment]
@SaraJaoude @eddiejaoude I am new to opensource and would like to contribute. Can you assign this issue to me and provide some more details of this issue?

**Comment by SaraJaoude** [comment]
> Hey folks,
> 
> I'm new to open source contributions, but I understand backend development well. Although my main expertise is in backend, I also have enough knowledge of front-end development to solve this problem. I see this as a valuable opportunity to contribute as a front-end developer.
> 
> Could you please assign this issue to me? Thanks!

@harshpatel-r as you were the first to request this I have assigned it to you

**Comment by eddiejaoude** [comment]
> I believe in order to make this work, the `<a>` tag will need to be overridden in [react-markdown](https://github.com/remarkjs/react-markdown#appendix-b-components)

thanks @dan-mba I will add it to the issue description

**Comment by harshpatel-r** [comment]
![bio-link-style-fix](https://github.com/EddieHubCommunity/LinkFree/assets/113815273/1904f508-c80d-4394-ab17-0d031136e223)

Hi @eddiejaoude  @SaraJaoude ,
I hope you're doing well. I've been working on the issue where the links in the bio with markdown work but they don't have our app's link styles on it.

I have made progress in resolving this issue, but I'm uncertain about the specific color to use for the links. To ensure consistency with our app's design, could you kindly provide me with the preferred color code to apply to the links style?

Thank you very much for your assistance. I appreciate your help!

**Comment by eddiejaoude** [comment]
> I have made progress in resolving this issue, but I'm uncertain about the specific color to use for the links. To ensure consistency with our app's design, could you kindly provide me with the preferred color code to apply to the links style?

Great work @harshpatel-r !! Please can you use the `Link` component, then this will ensure consistency on the styles in the app now and in the future when we update the style https://github.com/EddieHubCommunity/LinkFree/blob/main/components/Link.js
