### ISSUE TITLE
[FEATURE] Profile page add confetti and cake icon on user's birthday

### ISSUE THREAD

**Issue by zaidahmad25** [EddieHubCommunity/LinkFree#7162]
### Description

> I believe this feature would add a personal touch to LinkFree. 

### Suggestion
1. Add a birthday icon right next to the name 🎂
1. Add confetti when page loads on birthdate 🎉

### Screenshots

![Screenshot 2023-05-25 015435](https://github.com/EddieHubCommunity/LinkFree/assets/39582467/0289e481-4e07-402d-9944-a0ffc218d22f)

### Additional information

Please take care of the contrast ratio for the icon.

**Comment by SaraJaoude** [comment]
Thank you for the suggestion.  However as this is personal information which at this time we do not wish to store, I will close this Issue.
