### ISSUE TITLE
Searching by tags doesn't return a result unless search text is matching whole tag word

### ISSUE THREAD

**Issue by nicwithdev** [EddieHubCommunity/LinkFree#7218]
### Description

When searching for users via tags, the search text needs to be fully matching the potential tag before it will recognize it. I'm not sure if this is a bug or expected behaviour but I think it would make a great feature if it's expected. In the screenshots attached, I have tried searching for python and golang but only get results on full match. 

### Screenshots

![linkfree-search](https://github.com/EddieHubCommunity/LinkFree/assets/24362560/c3841563-677a-49b8-8815-25eb054cf373)
![linkfree-search2](https://github.com/EddieHubCommunity/LinkFree/assets/24362560/be577b6b-3d61-4db7-af59-8fecfa64a994)
![linkfree-search3](https://github.com/EddieHubCommunity/LinkFree/assets/24362560/f3779cf1-995a-4cb8-8b73-80097430fcf9)

**Comment by eddiejaoude** [comment]
Good spot and thank you for raising this is a bug 👍

**Comment by gamecube7561** [comment]
Hello, new to open source. May I have this assigned to me. Thanks!

**Comment by SaraJaoude** [comment]
> Hello, new to open source. May I have this assigned to me. Thanks!

@gamecube7561 this does not have the `good first issue` label - are you comfortable taking on this task?  If so I will assign this to you.  If not I would suggest you have a look at the list on unassigned good first issues, which I am linking [here](https://github.com/EddieHubCommunity/LinkFree/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee+label%3A%22good+first+issue%22).

**Comment by gamecube7561** [comment]
@SaraJaoude
Yes I am comfortable with the task.

**Comment by SaraJaoude** [comment]
> @SaraJaoude
> Yes I am comfortable with the task.

@gamecube7561 I will assign this to you

**Comment by ChinmayMhatre** [comment]
@gamecube7561 how are you coming along with the issue? do you require any assistance?

**Comment by eddiejaoude** [comment]
I just noticed this is no longer a bug, and got fix as part of another refactor
