### ISSUE TITLE
[FEATURE] Add Fade Animation to Links in 'Popular User Guides' Section

### ISSUE THREAD

**Issue by qwertyroop** [EddieHubCommunity/LinkFree#7231]
### Description

I would like to take on this issue and work on adding the fade animation to the links in the "popular user guides" section. I believe that this animation will greatly enhance the user experience and make the website more visually appealing.

I plan to implement the fade animation using CSS transitions and apply it to the links in the designated section. I will ensure that the animation is smooth and matches the desired behavior described in the issue.

Once the animation is implemented, I will create a pull request for review and include any necessary documentation or instructions for further maintenance.

I look forward to working on this issue and making the necessary improvements

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/45703076/4e22800b-8055-4f41-b2f6-2c9d7fec0454)

**Comment by SaraJaoude** [comment]
@qwertyroop thank you for your suggestion for enhancing the website, but we are in the process of redesigning this so there is no point making additional changes at this stage and I will close this Issue for now.
