### ISSUE TITLE
Open gitpod in a new tab

### ISSUE THREAD

**Issue by ChinmayMhatre** [EddieHubCommunity/LinkFree#7242]
### What would you like to share?

Could we make the gitpod button open the app in a new tab?

**Comment by dan-mba** [comment]
I don't believe this is possible.
GitHub removes certain attributes from anchor tags when it renders and `target` is one of them.
See this [StackOverflow post](https://stackoverflow.com/a/42156438)

**Comment by ChinmayMhatre** [comment]
> I don't believe this is possible.
> GitHub removes certain attributes from anchor tags when it renders and `target` is one of them.
> See this [StackOverflow post](https://stackoverflow.com/a/42156438)

👍🏻 Will close this issue.
