### ISSUE TITLE
[Bug] Youtube iframe in docs have less height

### ISSUE THREAD

**Issue by nitheesh-daram** [EddieHubCommunity/LinkFree#7273]
### Description

Embeded youtube video in docs now has less height,causing the video to shrink

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/54185106/2b280fe4-5c08-4dff-855f-f2b7b119a5e2)

**Comment by plbstl** [comment]
Okay. Thank you

**Comment by eddiejaoude** [comment]
thank you, assigned
