### ISSUE TITLE
App stats should read from DB not the json files

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#7284]
### Description

In the API file `pages/api/statistics/totals.js` it still counts the json files but as these are loaded into the DB, we should be using the DB not the files

**Comment by akash19coder** [comment]
Could you please assign the issue to me?

**Comment by eddiejaoude** [comment]
Sure, assigned 👍 (btw you don't need to tag me, other maintainers can assign also)
