### ISSUE TITLE
[DOCS] Add YouTube video to contributing file

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#7289]
### Description

Add this video with thumbnail to the top o the contributing guide https://youtu.be/dfeSpGd8leU

**Comment by luckyklyist** [comment]
I will like to work on this issue .

**Comment by SaraJaoude** [comment]
> I will like to work on this issue .

@luckyklyist I have assigned this to you.

**Comment by luckyklyist** [comment]
can you tell me the exact link of the page (contributing page )?

**Comment by eddiejaoude** [comment]
It is the same contributing md file in every repo, it is in the root of the project `CONTRIBUTING.md`, here is the url https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by kulkarniyash7** [comment]
someone is working; or should I just start working on it ?

**Comment by kulkarniyash7** [comment]
Please review my pr #7396

**Comment by eddiejaoude** [comment]
@kulkarniyash7 this issue is already assigned with an open pull request (please read the issue timeline above for more information)

**Comment by kulkarniyash7** [comment]
Sure, sorry about that!
