### ISSUE TITLE
Font size is too small for Feature section description on MainPage (Desktop)

### ISSUE THREAD

**Issue by Rohanfulzele** [EddieHubCommunity/LinkFree#7297]
### Description

Font size is too small for the Feature Section (Heading/Description) on Main page.
We can increase it a little more to make it look good.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/34005260/0f330161-e96d-4c1e-ab03-ec672d7b58bd)

### Additional information

Please make sure the Mobile view in not impacted, handle it too.

**Comment by ChinmayMhatre** [comment]
@KushagraVarshney05  assigning it to you

**Comment by FrozenHearth** [comment]
Also, please check the colors and contrast, for accessibility.

**Comment by ChinmayMhatre** [comment]
> Also, please check the colors and contrast, for accessibility.

In case you have any improvement suggestions feel free to create a separate issue regarding this. 

We try to keep the issues small and focused.
