### ISSUE TITLE
Cant run on my local machine. Help needed !!

### ISSUE THREAD

**Issue by Recognizeyourself** [EddieHubCommunity/LinkFree#73]
![image](https://user-images.githubusercontent.com/35026190/132955815-3049d1d9-f157-404d-8eda-b15705a8b78e.png)

Help needed !!

**Comment by eddiejaoude** [comment]
hi @Recognizeyourself , did you run `npm install`?

If you can share the steps you have taken, we can help you better

**Comment by Recognizeyourself** [comment]
I just tried doing `npn install` and it worked. Thankyou Again.
