### ISSUE TITLE
[BUG] Cannot de-select skill in search when coming from Profile

### ISSUE THREAD

**Issue by ribhav-pahuja** [EddieHubCommunity/LinkFree#7340]
### Description

Clicking on a particular skill from a profile takes us to the search menu with that skill selected. That skill can not be unselected unless manually removed from the search bar.

Steps to reproduce: 

1. Go to the profile - https://linkfree.io/eddiejaoude
2. Select Javascript.
3. We are taken to the search menu with Javascript pre-selected.
4. When trying to un-select Javascript, it does not happen and one more tag of `javascript` appears.

### Screenshots

Steps to reproduce:
1.
<img width="1327" alt="Screenshot 2023-06-03 at 2 06 10 AM" src="https://github.com/EddieHubCommunity/LinkFree/assets/28953852/0ee97289-a735-4dc2-be2a-b1eb4c97c955">

2. 
<img width="1413" alt="Screenshot 2023-06-03 at 2 06 29 AM" src="https://github.com/EddieHubCommunity/LinkFree/assets/28953852/029dd34a-831e-42d5-8aa4-b1459d94f74f">

3. 
<img width="1438" alt="Screenshot 2023-06-03 at 2 06 42 AM" src="https://github.com/EddieHubCommunity/LinkFree/assets/28953852/62e08295-d9d2-427d-a05f-840e8da1df6c">

### Additional information

I would like to work on this issue.

**Comment by ribhav-pahuja** [comment]
I would like to work on this issue. Please assign it to me. Thanks in advance!

**Comment by SaraJaoude** [comment]
> I would like to work on this issue. Please assign it to me. Thanks in advance!

@ribhav-pahuja I have assigned this to you

**Comment by ribhav-pahuja** [comment]
@eddiejaoude, gotcha. Will keep this in mind.
Also, thanks for merging the PR.
