### ISSUE TITLE
[OTHER] Remove single use mode

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#7343]
### What would you like to share?

This feature is not used and we are keen for people to connect on the hosted platform

REMOVE
- layout
- config
- docs
anything else?

**Comment by raviraj-github** [comment]
Assign this to me. I will happy to clean up the code. 

I am very new to this project it will help me to understand the project more.

**Comment by eddiejaoude** [comment]
Sure, I have assigned it to you @raviraj-github 👍

**Comment by Pierstoval** [comment]
Well, I just saw this in the last release, and was using the single-user mode, sorry for not reacting earlier. Was merged quite fast 😭

**Comment by eddiejaoude** [comment]
Oh no, I didn't realise anyone was using this. Why don't you use the platform version, you get all the latest features?

**Comment by eddiejaoude** [comment]
We do have stats if that is what you are looking for? But let us know what else is missing and we can try to add those features in

<img width="1680" alt="Screenshot 2023-06-07 at 19 25 27" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/1a50f630-ee19-4412-a652-ffbe8201b3f7">
