### ISSUE TITLE
[BUG] Dark mode issue in email form on premium website

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/LinkFree#7346]
### Description

Email form does not support dark mode

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/30869493/fd010f03-89de-4520-a644-cd2f1066910e)

**Comment by eddiejaoude** [comment]
I will try to remove the background in the Kartra form builder but I don't think it looks good

<img width="1076" alt="Screenshot 2023-06-03 at 14 52 35" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/eee45e04-7a4b-492d-809c-4e39cdb6b349">

**Comment by eddiejaoude** [comment]
Thanks for raising Tom! The best I could do it make it 50% transparent, so it doesn't show in light mode, but in dark mode the text is still readable

<img width="1205" alt="Screenshot 2023-06-03 at 14 53 08" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/98eb5562-4d2d-465a-9ff2-cdf0825478fc">
