### ISSUE TITLE
[FEATURE] OnScroll Zoom in/out on Map

### ISSUE THREAD

**Issue by Rohanfulzele** [EddieHubCommunity/LinkFree#7358]
### Description

Add OnScroll Zoom In/Out event on the Map just like Google Maps does it.

- OnScroll Wheel Forward : Map zoom IN
- OnScroll Wheel Backward : Map zoom OUT

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/34005260/b0d60e86-69bb-4694-957e-ac314a9da2cb)

### Additional information

This will be good with respect to User Experience.

**Comment by eddiejaoude** [comment]
@amandamartin-dev what are your thoughts on this?

**Comment by amandamartin-dev** [comment]
> @amandamartin-dev what are your thoughts on this?

I think this is fine, truly I don't remember disabling this ability but I just checked the code and it's set to false.

You will just want to change this to true in the map component and then test to make sure it still adheres to the map bounds which it should

``` scrollWheelZoom={false}```

**Comment by amandamartin-dev** [comment]
@Rohanfulzele I am going to change to ready for dev, do you want to be assigned this issue?
