### ISSUE TITLE
Badge count div overlapping with Clear/Reset filter button [Mobile]

### ISSUE THREAD

**Issue by Rohanfulzele** [EddieHubCommunity/LinkFree#7359]
### Description

[For Mobile Devices ONLY]
Badge count div overlapping with Clear/Reset filter button.
Some padding is needed in between the Button and Badge count divs.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/34005260/12381550-02d6-4199-8efe-2e1a9c81f7e0)

**Comment by SaraJaoude** [comment]
@Rohanfulzele thank you for the suggestion, however as we are going to be redesigning the website this will be resolved then so I am going to close this Issue.
