### ISSUE TITLE
improve the colors and contrast for accessibility

### ISSUE THREAD

**Issue by KushagraVarshney05** [EddieHubCommunity/LinkFree#7368]
### What would you like to share?

change color contrast in feature description area.

![Screenshot 2023-06-04 102207](https://github.com/EddieHubCommunity/LinkFree/assets/112865931/5dcf6305-26b0-460e-8419-b7696935685c)

**Comment by SaraJaoude** [comment]
I am closing this Issue as we are looking at a full redesign of the website and this will be covered then.

However in future when creating issues of this nature it would be good if you could include the following information in the description:

- what accessibility standard are you suggesting we move from and to 
- including current colour contrast ratio and proposed colour contrast ratio
