### ISSUE TITLE
[OTHER]  font size is much smaller as compared to other components

### ISSUE THREAD

**Issue by KushagraVarshney05** [EddieHubCommunity/LinkFree#7373]
### What would you like to share?

description of feature section's font is much smaller as compared to other fonts.
![Screenshot 2023-06-04 142034](https://github.com/EddieHubCommunity/LinkFree/assets/112865931/60b6d6ea-dbea-4ec2-8516-9b6a41e40add)

### Additional information

Its my fault.. previously I was assigned to increase the font size but neglected this section.

I will like to contribute to this.

**Comment by SaraJaoude** [comment]
We need to ensure consistency so the updated font size should be the same as this:

<img width="1515" alt="Screenshot 2023-06-05 at 09 51 12" src="https://github.com/EddieHubCommunity/LinkFree/assets/82668196/91306991-60cc-4ca2-9b01-f49382bf66e4">

**Comment by KushagraVarshney05** [comment]
I would like to contribute to it

**Comment by Vishrut19** [comment]
I would like to work on it

**Comment by pritamrajput** [comment]
If this issue is not assigned to anyone. I would like to work on it.

**Comment by SaraJaoude** [comment]
> I would like to contribute to it
@KushagraVarshney05 I will assign this to you

**Comment by SaraJaoude** [comment]
> I would like to work on it

@Vishrut19 as I have mentioned to you before, please do not spam multiple unassigned issues asking them to be assigned to you. If you wish to work on an issue then please wait to find out if this has been assigned to you or not before requesting another. As you have already been made aware this cause confusion for maintainers and community members, as well as extra notifications.

**Comment by KushagraVarshney05** [comment]
> We need to ensure consistency so the updated font size should be the same as this:
> 
> <img alt="Screenshot 2023-06-05 at 09 51 12" width="1515" src="https://user-images.githubusercontent.com/82668196/243240545-91306991-60cc-4ca2-9b01-f49382bf66e4.png">

should i have to update font size same as in this picture @SaraJaoude

**Comment by SaraJaoude** [comment]
@KushagraVarshney05 please update the font size of the description of Feature to the same font size as the description of Popular User Guides.
