### ISSUE TITLE
[Home Page] add a Home Page contaning info and docs about LinkFree to the website

### ISSUE THREAD

**Issue by kr-anurag** [EddieHubCommunity/LinkFree#738]
### Description

Hey there!
This issue is about adding a Home Page to LinkFree, like rather than directly showing all the Contributors, it should first show a Home Page, including docs, and some MetaData, now GitHub works too! But it would be great if it's added to the WebSite itself

I'm adding this issue to collect feedback!

**Comment by krishguptadev** [comment]
Duplicate of https://github.com/EddieHubCommunity/LinkFree/issues/339

**Comment by kr-anurag** [comment]
> Duplicate of #339

oof, apparently i should see pre-existing issues and PRs before making new ones 🤦

**Comment by krishguptadev** [comment]
No worries, but can you close this one though?

**Comment by kr-anurag** [comment]
ah yep, sure!
