### ISSUE TITLE
[FEATURE] Add "system" setting in Dark Mode

### ISSUE THREAD

**Issue by FrozenHearth** [EddieHubCommunity/LinkFree#7383]
### Description

We have dark mode and light mode toggle now. 
It would be great if we could allow the user to select their system default as the third option.
So the three options would be:

- Light
- Dark
- System

System would imply that light or dark mode get auto-selected if the user's system has the same config.

Something like what Vercel team has implemented on the Next.js official docs:

### Screenshots

![dark_mode](https://github.com/EddieHubCommunity/LinkFree/assets/27160715/6af5203c-e564-45f4-b359-7d7d2779280e)

**Comment by SaraJaoude** [comment]
Thank you for the great suggestion.  This seems like a lot of work when people can just select what theme they prefer, plus many people prefer different themes to the System theme. Additionally I don't think there is a Tailwind toggle for three options. I will be closing this Issue.
