### ISSUE TITLE
[OTHER] Fix package.json description.

### ISSUE THREAD

**Issue by MahirMahdi** [EddieHubCommunity/LinkFree#7389]
### What would you like to share?

It should be "~~Linkfree~~ LinkFree connects". 
![Screenshot 2023-06-05 103205](https://github.com/EddieHubCommunity/LinkFree/assets/66949598/def2f3ef-92d9-44fc-96f7-c6a0a2c175bc)

**Comment by SaraJaoude** [comment]
Good spot @MahirMahdi  - also please note LinkFree has a capital `F`

**Comment by pratham-yuxo** [comment]
so, we just have to replace "connect" with "connects". 
You can assign this to me.

**Comment by MahirMahdi** [comment]
> Good spot @MahirMahdi - also please note LinkFree has a capital `F` - I have updated the description.

Thanks Sara. Right back at you. 😃

**Comment by shubham2o** [comment]
@SaraJaoude Can you assign this issue to me as I am new to open source?

**Comment by ChinmayMhatre** [comment]
@pratham-yuxo  assigning you the issue.

**Comment by pratham-yuxo** [comment]
Thanks, I'll make a pr soon.
