### ISSUE TITLE
[FEATURE] Redesigning the UserCard

### ISSUE THREAD

**Issue by AliReza1083** [EddieHubCommunity/LinkFree#7405]
### Description

Hi,
I hope you are doing well.

I came across and saw that User Cards seem to be a simple design, I thought it would be great to design a new User Card.
That's why I have designed one and I want to show them to you, if you liked it, then I can work on this and implement the new card.

I am waiting for your Replies :)

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/99729607/85e412c8-99e1-4896-a2f5-294ad9ecd51f)

**Comment by SaraJaoude** [comment]
Looks good and we appreciate you taking the time to do this, but as we are in the process of redesigning the website and all of this will change I am closing this issue.
