### ISSUE TITLE
YouTube logo present in the footer was not correct

### ISSUE THREAD

**Issue by shaikahmadnawaz** [EddieHubCommunity/LinkFree#7422]
### Description

The YouTube present in the footer was not full 👇

![Screenshot 2023-06-06 212759](https://github.com/EddieHubCommunity/LinkFree/assets/96189881/1db42f60-f17d-460b-b5dd-8ab4426213f3)

 I think the original icon will looks like below 👇

![Screenshot 2023-06-06 213240](https://github.com/EddieHubCommunity/LinkFree/assets/96189881/56dad61a-2af0-40ed-9439-4d69dd7ca060)

Reference: https://react-icons.github.io/react-icons/search?q=youtube

Can I work on this issue?

**Comment by dan-mba** [comment]
> The logo is correct here, this is due to the logo being pushed/hidden which is likely due to some global styling update. @eddiejaoude may know specifically what caused this, I have been away for a couple weeks

The error is actually due to a cut & past error I made on a PR to minimize bundle size.

I extracted icons here: https://github.com/EddieHubCommunity/LinkFree/tree/main/components/icons
But I missed differences in the viewbox sizes.
The one for the YouTube icon should be viewBox="0 0 576 512"
The one for the LinkedIn icon should be viewBox="0 0 448 512"

**Comment by KushagraVarshney05** [comment]
can i contribute to this.

**Comment by saudch007** [comment]
Please assign me a issue? Thanks.

**Comment by shaikahmadnawaz** [comment]
Thank you for assigning, I already made PR #7434 check it out ✨

**Comment by ChinmayMhatre** [comment]
> Thank you for assigning, I already made PR #7434 check it out ✨

Please check my comment on the PR regarding the guidelines and Please refrain from tagging the maintainers unless the issue have been inactive for a week.

**Comment by shaikahmadnawaz** [comment]
> > Thank you for assigning, I already made PR #7434 check it out ✨
> 
> Please check my comment on the PR regarding the guidelines and Please refrain from tagging the maintainers unless the issue have been inactive for a week.

Okay removed tags 👍
