### ISSUE TITLE
[OTHER] LinkFree Logging Improvements

### ISSUE THREAD

**Issue by raviraj-github** [EddieHubCommunity/LinkFree#7437]
### What would you like to share?

During my analysis of the LinkFree issue https://github.com/EddieHubCommunity/LinkFree/issues/7065, I have observed that our current approach to debug logging is not implemented properly. In most cases, console logging has been used, which I believe is not ideal.

To address this issue, I suggest the following solutions in a polite manner:

1. Update the logger to provide more comprehensive log-level support. It appears that the logger we are currently using already supports this functionality.

2. Make debug logging configurable, with the default setting being disabled in the Production environment. This will help prevent unnecessary log output in production and ensure a cleaner log file.

3. Instead of relying solely on console logging, consider utilizing a file appender for logging purposes. This will make log analysis easier and could also be valuable for future analytics purposes.

4. Create a documentation page specifically dedicated to proper logging practices and make it mandatory for contributors to read before making any contributions. It is important to enforce adherence to these logging standards while addressing open issues.

Based on my knowledge and analysis, it seems that **PinoLogger(_the one we are using_)** supports all the mentioned requirements. However, if it does not meet our needs, we can explore other open-source libraries available in the marketplace.

**Comment by raviraj-github** [comment]
I am satisfied with using Pino(_it claims that it is **5 times** faster than other loggers_) to address these issues, and I believe it already covers all of them. I would prefer not to make any changes in this regard.

However, for the purpose of analysis, if someone wishes to explore alternative loggers, the following options can be considered:

- **Winston**
- **Pino**
- **Bunyan**
- **Loglevel**
- **Npmlog**

**Comment by akash19coder** [comment]
@eddiejaoude Could you please recommend me files or locations that I might wanna check.

**Comment by akash19coder** [comment]
I have updated the Logger..js file
### Logger.js
```
import { serverEnv } from "@config/schemas/serverSchema";
import * as PinoLogger from "pino";
import { join } from "path";

const logsPath = join(__dirname, "..", "logs", "app.log"); 

const config = {
  transport: {
    target: "pino-pretty",
    options: {
      colorize: true,
    },
  },
  level: serverEnv.NODE_ENV === "development" ? "debug" : "info", 
  enabled: serverEnv.NODE_ENV !== "production", 
  timestamp: true,
  redact: ['req.headers.authorization'],
  pinoFileOptions: {
    appendFile: logsPath,
    prettyPrint: true,
    timestamp: true,
    create:true,
  },
  streams: [
    { stream: process.stdout }, 
    { stream: PinoLogger.destination(logsPath), level: "debug", enabled: serverEnv.NODE_ENV !== "production" }, 
  ],
};

let logger;

logger = PinoLogger(config);

export default logger;

```

**Comment by raviraj-github** [comment]
The current setup appears acceptable. However, I suggest transitioning to the Winston Library since Pino lacks support for a File Appender. This means that the logging will continuously append to the "app.log" file, whereas we require a solution that can split the file after reaching a certain memory limit and begin writing to a new file.

Additionally, it is essential to generate a log file in the production environment. However, the log level should be set to "info" by default, while still allowing the flexibility to change it to "debug" if necessary.

Let us know, if you want us to assign this issue to you. 

Thanks for your support!

**Comment by akash19coder** [comment]
@raviraj-github  Sure I can work on it. Please assign it to me

**Comment by SaraJaoude** [comment]
@akash19coder I have assigned this to you

**Comment by raviraj-github** [comment]
@akash19coder :  I was trying to test your logger code but it doesn't seem to be working for me. It is throwing an exception for the log file. Have a look at the screenshot.

![image](https://github.com/EddieHubCommunity/LinkFree/assets/11041028/9c9cafe4-d13c-429a-97ac-643a49e2335d)
