### ISSUE TITLE
[BUG] Improve the accessibility of Profile Tags

### ISSUE THREAD

**Issue by itsdevdeepak** [EddieHubCommunity/LinkFree#7463]
### What would you like to share?

What would you like to share?
Currently, there is a problem with tab navigation when interacting with tags on the page. When using the Tab key to navigate through the page elements, I noticed that each tag consists of two tabbable elements.

one is by `a` tag
![image](https://github.com/EddieHubCommunity/LinkFree/assets/105926677/a85bbd72-8db2-4f4a-ac41-7de5580ab15b)
and other one by `button`
![image](https://github.com/EddieHubCommunity/LinkFree/assets/105926677/3a1ef46f-61ab-4616-98b5-ff63f925394b)

### Additional information

i would like to work on this this issue.

**Comment by eddiejaoude** [comment]
Good spot 👍 I have assign the bug to you
