### ISSUE TITLE
[OTHER] Improve the accessibility of floating buttons

### ISSUE THREAD

**Issue by itsdevdeepak** [EddieHubCommunity/LinkFree#7464]
### What would you like to share?

There is no visual indication of the of selecting floating buttons when navigating through Tab key.
This is because `a` Tag is Tabbable Element and its child element has `"position: fixed"` assigned to it.

Update these buttons to resolve the issue: 
- Help Button on the Home Page
- Add Testimonial Button on Profile Page

![image](https://github.com/EddieHubCommunity/LinkFree/assets/105926677/c648cc9a-365f-4002-bdd5-d9cde7c4a9ca)

Moving "position: fixed" to its parent element `a` tag should fixed this problem.

#### Additional information
*No response*

**Comment by eddiejaoude** [comment]
Thank you for raising 👍

**Comment by itsdevdeepak** [comment]
its also same problem on home page for help button

**Comment by eddiejaoude** [comment]
good spot 👍

**Comment by anirudhp26** [comment]
@eddiejaoude hey Eddie, I am facing a issue regarding asking for assignments of issues, it showing "Limited to collaborators and won't allow me to comment anything !  , how can I be a collaborator at LinkFree?

**Comment by GaganpreetKaurKalsi** [comment]
I would like to work on this issue.

**Comment by eddiejaoude** [comment]
Sure, I have assigned it to you @GaganpreetKaurKalsi
