### ISSUE TITLE
Color error for preview in playground

### ISSUE THREAD

**Issue by shobhitexe** [EddieHubCommunity/LinkFree#7467]
### Description

The preview in playground section shows only light color regardless of theme we have selected 

As we can see on attached video below in light theme its fine but when we switch to dark mode the color scheme of preview still remains same which hides imp info like bio 

https://github.com/EddieHubCommunity/LinkFree/assets/29349136/8e58f8f1-3f3a-45c9-927c-c5c472f800b4

**Comment by amandamartin-dev** [comment]
Thanks @shobhitexe, i was able to recreate this and will open the issue. Do you want to be assigned?

**Comment by shobhitexe** [comment]
> Thanks @shobhitexe, i was able to recreate this and will open the issue. Do you want to be assigned?

Yes plz assign this to me i would love to create a PR on it

**Comment by anirudhp26** [comment]
@eddiejaoude yes sirr, i was talking about this issue, it was locked for me sometime ago

**Comment by eddiejaoude** [comment]
@anirudhp26  yes maintainers sometimes forget to unlock the issue when it is `ready for dev` (hopefully this will be automated soon). If this happens as I mentioned when replying to your comment in the other issue, please ask in Discord with an issue link for the maintainers to unlock, do not comment on other issues as this is creating more notifications for people that are unrelated.
