### ISSUE TITLE
Fix needed for the rate limit issue in the GitHub API endpoint 'users/{userName}' within the 'getLocationByUsername.js' file

### ISSUE THREAD

**Issue by raviraj-github** [EddieHubCommunity/LinkFree#7492]
### Description

During my code analysis, I discovered that we are utilizing the GitHub API "**_https://api.github.com/users/{userName}_**" and employing the Octokit utility provided by GitHub for making the API calls.

However, I noticed that we are not supplying an authentication token when creating the Octokit object. This is crucial because the API has a rate limiter implemented, which restricts the number of user reads to 60 per hour. Given our requirements, this limit is insufficient.

Here is a screenshot of the relevant code for reference from "getLocationByUsername.js".

![image](https://github.com/EddieHubCommunity/LinkFree/assets/11041028/ad12be34-5817-485d-935a-97efe4566bd5)

See the error while loading the test data. 

![image](https://github.com/EddieHubCommunity/LinkFree/assets/11041028/dea4201a-97ff-4092-860b-da3cdeb20a22)

**Proposed Solution:**
-------------------------------------------------------------------------------------------------------------
According to the GitHub rate limiter guidelines, if we include an authentication token when making requests to this API, we will be allowed to make up to 5000 requests per hour. This limit appears to be acceptable for the current situation. However, as the number of users grows, we may need to reconsider this aspect in the future. 

To address this issue, let's fix it by adding an authentication token as shown below:

![image](https://github.com/EddieHubCommunity/LinkFree/assets/11041028/da49e396-3cdc-4e22-88da-31fb2420e90f)

Have a look into detailed documentation for rate limit from GitHub https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limiting

### Additional information

Please consult the following document, [Authentication Doc](https://github.com/octokit/auth-app.js/#createappauthoptions-or-new-octokit-auth-), for detailed instructions on the necessary steps to implement token authentication. This guide outlines the specific procedures required to obtain and utilize the token for reading purposes.

Screenshot for generating the token-

![image](https://github.com/EddieHubCommunity/LinkFree/assets/11041028/3feda41a-51e4-42ff-9492-a28d35faa7b9)

More reference:  Follow this youtube video for step by step process. 

[How to use GitHub REST API](https://www.youtube.com/watch?v=OvfLavRD1Os)

Happy Coding!

**Comment by eddiejaoude** [comment]
Good spot Ravi 👍 

Someone can add this to the environment variables `GITHUB_API_TOKEN` 💯

**Comment by Ankur1493** [comment]
can I work on this?

**Comment by eddiejaoude** [comment]
Sure @Ankur1493 , assigned to you

**Comment by raviraj-github** [comment]
Thank you for submitting your pull request. I have included a review comment that requires your attention. Additionally, for this particular change, please update the [documentation](https://linkfree.io/docs/environments/environment-variables) to reflect the modifications. It may also be necessary to provide instructions on generating tokens, if applicable.

Furthermore, please provide details on how you verified this change. In my case, I identified this issue by utilizing additional logs during the test data reload process. I recommend adding extra logs while reloading the test data, specifically within the `/api/system/reload?secret=development` endpoint. You can refer to the `reload.js` file for the location API call implementation.
