### ISSUE TITLE
[BUG] Issue with the changelog and trigger in release action.

### ISSUE THREAD

**Issue by Pradumnasaraf** [EddieHubCommunity/LinkFree#7496]
## Bug No.1 (SOLVED)
The old changelog is not maintained when a new changelog is created.

<img width="1498" alt="Screenshot 2023-06-10 at 3 39 14 PM" src="https://github.com/EddieHubCommunity/LinkFree/assets/51878265/d9a02a49-af61-4a5a-88fb-cbe6c905fd39">

## Bug No.2
It's incrementing the app version number with every PR and not following SemVer. This applies even to commits with `docs:` and `chore:` prefixes. However, it does not apply to commits with `data:` since we have ignored them.

<img width="1089" alt="Screenshot 2023-06-10 at 3 45 39 PM" src="https://github.com/EddieHubCommunity/LinkFree/assets/51878265/4117573c-8e8a-428f-a7e7-fac91a9c2da6">

**Comment by dan-mba** [comment]
For issue 1, the conventional changelog action provides the following option:
release-count: Number of releases to preserve in changelog. Default 5, use 0 to regenerate all.

**Comment by nitheesh-daram** [comment]
Hey team, if no one is working on this, I would like to take this up!

Thanks

**Comment by eddiejaoude** [comment]
Thanks @dan-mba 👍 

Sure @nitheesh-daram assigned to you

**Comment by nitheesh-daram** [comment]
Hey Team,

it looks like both bugs got resolved due to recent changes by Dan and pradumnasaraf; now I can see the latest five versions are persistent in CHANGELOG.md and versioning is following SemiVer.

I think we can close this issue, let me know if I'm wrong

**Comment by Pradumnasaraf** [comment]
Hey, Nitheesh.

The changelog part is fixed in one of the recent PR by Dan. But I think the SemVer issue is still there.

**Comment by nitheesh-daram** [comment]
Thanks for the clarification Pradumnasaraf 

I've little knowledge about SemiVer.So what changes you suggest for SemiVer to work !

Thanks

**Comment by Pradumnasaraf** [comment]
Apologies I missed the comment. We discuss this in EddieHub Discord. One potential cause can be the overriding issue put by Dan. Here is what Dan quoted.

>`skip-on-empty`: Boolean to specify if you want to skip empty release (no-changelog generated). This case occurred when you push `chore` commit with `angular` for example. Default `'true'`. We override this to `false`

Hey, @dan-mba, would you like to add something else?

**Comment by eddiejaoude** [comment]
> set skip-on-empty to true. This will require the use of chore & docs in commit messages to only be for things that don't require a deployment. (README, non-deployment actions, dockerfiles).

I think option `1` is a good option, the deploy vercel action will need to deploy for `docs` path

**Comment by SaraJaoude** [comment]
@nitheesh-daram how are you getting on?
