### ISSUE TITLE
Duplicate events

### ISSUE THREAD

**Issue by ChinmayMhatre** [EddieHubCommunity/LinkFree#7497]
### Description

![image](https://github.com/EddieHubCommunity/LinkFree/assets/51131670/79329f57-3c2b-4c09-a48d-b9a98da99987)

![image](https://github.com/EddieHubCommunity/LinkFree/assets/51131670/5de13bcc-9ee2-4a92-b693-dc03e7cbdf06)

**Comment by eddiejaoude** [comment]
Thanks for noticing 👍 

For some reason, 1 profile was duplicated (yep only 1), I have disabled the duplicate profile and I will try to investigate why it happened
