### ISSUE TITLE
[FEATURE] All db models to have created/updated dates

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#7499]
### Description

It would be useful to see when documents are created and updated, we can do this with mongoose

https://mongoosejs.com/docs/timestamps.html

**Comment by anirudhp26** [comment]
@eddiejaoude I would like to contribute to this issue.

**Comment by The-Saras** [comment]
I would like to contribute. pls assign me this issue.

**Comment by eddiejaoude** [comment]
@anirudhp26 sure, I have assigned it to you

@The-Saras this issue was requested a few minutes before you, please read the timeline and familiarise yourself with the contributing guidelines to reduce the noise, notification and confusion with the community  https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by eddiejaoude** [comment]
Merged
