### ISSUE TITLE
Search support

### ISSUE THREAD

**Issue by FayasNoushad** [EddieHubCommunity/LinkFree#75]
Please add search support for members.

**Comment by amittri1025** [comment]
I want to work on this issue

**Comment by FayasNoushad** [comment]
> I want to work on this issue

Feel free and add a pull request

**Comment by Shivansh-yadav13** [comment]
@FayasNoushad Can I make a PR for this?

**Comment by krishguptadev** [comment]
@Shivansh-yadav13 Sorry but this issue in already been assigned to @amittri1025, You can work on this only if they aren't 🙂

**Comment by FayasNoushad** [comment]
> > @Shivansh-yadav13 Sorry but this issue in already been assigned to @amittri1025, You can work on this only if they aren't slightly_smiling_face
> 
> @amittri1025 are you working on this issue? slightly_smiling_face

Yeah, You can.
