### ISSUE TITLE
[BUG] Issue with profile page url on statistics page

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [EddieHubCommunity/LinkFree#7507]
### Description

When on statistics page, clicking on username(in blue) sometimes takes me to `localhost:3000/username`. This behaviour is observed when going to some other page and then coming back to Account page.

**Steps to reproduce bug :-**
- Go to **Account** page
- Hard reload tab (Cmd + Shift + R)
- Hover over your username(in blue). It will point to `https://linkfree.io/<username>`. In my case `https://linkfree.io/GaganpreetKaurKalsi`
- Click on some other tab (Go to **Events** page)
- Now go back to **Account** page
- Hover over your username in blue. It will point you to `http://localhost:3000/<username>`. In my case `http://localhost:3000/GaganpreetKaurKalsi`

### Screenshots

Look at the bottom left section of the image. You will find the url the username is pointing to.

<img width="1440" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/54144759/ee5c6f0a-92f1-4573-839b-a6d2f85a9a6d">

<br><br>

Same issue is coming up on playground page as well (see bottom left corner)

<img width="1440" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/54144759/21ba54de-9075-4c05-933a-169144a0105c">

**Comment by eddiejaoude** [comment]
Oh good spot, very strange bug, thanks for raising

**Comment by NiazMorshed2007** [comment]
Strange.....
I'd love to work on this bug

**Comment by eddiejaoude** [comment]
Sure, assigned to you @NiazMorshed2007

**Comment by NiazMorshed2007** [comment]
Looking into it

**Comment by Sidhartha-Saxena** [comment]
Hey @NiazMorshed2007 are you still working on this issue

**Comment by GaganpreetKaurKalsi** [comment]
If we console the `clientEnv.NEXT_PUBLIC_BASE_URL` in `statistics.js` file, it is always `https://localhost:3000`, the fallback given in `clientSchema.js`. Also there is an error in the console saying the client and server url doesn't match. See below screenshot

<img width="1440" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/54144759/3f2afbca-4bc1-4897-8f57-8245ddd7a2b5">

<br><br>
 
We are unable to receive the correct url on the stats page.

**Comment by GaganpreetKaurKalsi** [comment]
While looking at other pages, same issue is coming up in playground as well. The url is a localhost (see below image, bottom left corner)


<img width="1440" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/54144759/21ba54de-9075-4c05-933a-169144a0105c">

<br><br>

**(Updated issue description)**

**Comment by GaganpreetKaurKalsi** [comment]
Hey @NiazMorshed2007, 

try seeing how `clientEnv.NEXT_PUBLIC_BASE_URL` is being consumed in other files.
Compare `statistics.js` with `[username].js`. 

This should help you figure out the problem.

**Comment by eddiejaoude** [comment]
Great collaboration 💪 ❤️

**Comment by GaganpreetKaurKalsi** [comment]
Hey @NiazMorshed2007, let me know if you are still facing any issues.

**Comment by NiazMorshed2007** [comment]
@GaganpreetKaurKalsi could you please take this issue?
I'm suddenly going through some busyness,, @eddiejaoude can you assign them?

Sorry, for the the confusion it may caused.

**Comment by SaraJaoude** [comment]
> @GaganpreetKaurKalsi could you please take this issue? I'm suddenly going through some busyness,, @eddiejaoude can you assign them?
> 
> Sorry, for the the confusion it may caused.

@NiazMorshed2007 I have unassigned this from you.  In future please avoid tagging a specific maintainer as all maintainers receive these notifications and can assign. 

@GaganpreetKaurKalsi please let me know if you would like this assigned to you.

**Comment by GaganpreetKaurKalsi** [comment]
> > @GaganpreetKaurKalsi could you please take this issue? I'm suddenly going through some busyness,, @eddiejaoude can you assign them?
> > Sorry, for the the confusion it may caused.
> 
> @NiazMorshed2007 I have unassigned this from you. In future please avoid tagging a specific maintainer as all maintainers receive these notifications and can assign.
> 
> @GaganpreetKaurKalsi please let me know if you would like this assigned to you.

Sure @SaraJaoude, will raise a PR by EOD.

**Comment by SaraJaoude** [comment]
@GaganpreetKaurKalsi I have assigned this to you
