### ISSUE TITLE
[DOCS] update QuickStart screenshot and add alert box

### ISSUE THREAD

**Issue by SaraJaoude** [EddieHubCommunity/LinkFree#7516]
### Description

adding a new screenshot to the QuickStart guide to reflect we no longer need: `type`

given the video has not been updated, also adding an alert box to emphasise we do not need:

- avatar
- type
- personal

### Screenshots

<img width="1360" alt="Screenshot 2023-06-11 at 09 25 39" src="https://github.com/EddieHubCommunity/LinkFree/assets/82668196/6f5727c7-b7a1-414b-8ec0-372e8fc287e8">

**Comment by eddiejaoude** [comment]
Merged
