### ISSUE TITLE
[OTHER] Review the position and style of the Add Testimonial Bubble/Floating button

### ISSUE THREAD

**Issue by katzjeff** [EddieHubCommunity/LinkFree#7530]
### What would you like to share?

Hi team,
Am not so sure if this should fall here or under the General feature request, given the limited options of selecting for an update to a feature, but anyway...

**This is just a request to review the positioning or rather the design of the "Add testimonial for..." bubble /floating button at the bottom of the Home page. The current position tends to hide the social media icons, both when in mobile and full screen views. 

Suggestion would be to have just a testimonial icon that's in-line with the other social media icons, thus improving on user experience.

See images below**

Full Screen View:
![fullPageView](https://github.com/EddieHubCommunity/LinkFree/assets/31887646/af17e916-733c-4c1a-9458-f8cc052def57)

### Additional information

Mobile View
![mobileView](https://github.com/EddieHubCommunity/LinkFree/assets/31887646/1239b985-0e9d-47f6-a708-36de00421813)

**Comment by eddiejaoude** [comment]
Thank you for raising the issue 👍  we are going to go for a redesign soon, so this will be fixed as part of that, so I will close this issue for now

**Comment by katzjeff** [comment]
> Thank you for raising the issue 👍 we are going to go for a redesign soon, so this will be fixed as part of that, so I will close this issue for now

This is well noted . Cheers
