### ISSUE TITLE
[OTHER] Add a sponsor button in the repository

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/LinkFree#755]
### What would you like to share?

I think we should add a sponsor button on this repository as well. CC: @eddiejaoude.

**Comment by krishguptadev** [comment]
It is already there, https://github.com/EddieHubCommunity/LinkFree/blob/main/.github/FUNDING.yml, @eddiejaoude maybe just needs to turn it on in the settings?

**Comment by eddiejaoude** [comment]
Oh yes, I needed to turn it on 🤦‍♂️ thank you all 🔥
