### ISSUE TITLE
[FEATURE] Add Icon for University or School to use in Milestone Section

### ISSUE THREAD

**Issue by theriyazo** [EddieHubCommunity/LinkFree#757]
### Description

When adding graduation details in the milestones section of the profile, there is no school or university icon.

An Icon such as YouTube, Github in Milestone list if made available, those who want to add their graduation can make use of it.

- [ ] Added Icon for Uni/School

**Comment by CodingSpecies** [comment]
Maybe as a graduation, @theriyazo ,
something like a graduation hat like this:
<img src="https://cdn-icons-png.flaticon.com/512/0/422.png" height=100 />

or a school/education something like this:
<img src="https://icon-library.com/images/book-icon-transparent/book-icon-transparent-25.jpg" height=100 />

**Comment by CodingSpecies** [comment]
Maybe as a graduation, @theriyazo ,
something like a graduation hat like this:
<img src="https://cdn-icons-png.flaticon.com/512/0/422.png" height=100 />

or a school/education something like this:
<img src="https://icon-library.com/images/book-icon-transparent/book-icon-transparent-25.jpg" height=100 />

**Comment by vinzvinci** [comment]
> 

I like the first one :D

**Comment by krishguptadev** [comment]
+1, for vinz suggestion

**Comment by theriyazo** [comment]
I too like the hat one.
Great choice @vinzvinci and @krishguptadev

**Comment by RagibAjmal** [comment]
@theriyazo I would like to work on this

**Comment by Vyvy-vi** [comment]
@RagibAjmal Feel free to open a PR!

**Comment by theriyazo** [comment]
> @theriyazo @Vyvy-vi I created a svg with the hat you chose and I used it as icon using the below code I am not sure if it is the correct way to do it as I am just learning , If I am wrong please help me with the right way ![Screenshot 2021-12-09 at 8 29 21 PM](https://user-images.githubusercontent.com/73844685/145420261-3cf29b34-4ada-4e6f-ad04-357245ec6463.png)
> 
> And here is the output of the below code . I added icon in @theriyazo file for testing ![Screenshot 2021-12-09 at 8 30 48 PM](https://user-images.githubusercontent.com/73844685/145420498-0f6c62e4-f86f-4156-8c2c-01e046cc0593.png)

This needs to be a little small and have padding.

**Comment by RagibAjmal** [comment]
![Screenshot 2021-12-11 at 3 54 15 PM](https://user-images.githubusercontent.com/73844685/145673179-31e68025-1a65-426d-a832-ce69bd193d8f.png)
Is this fine

**Comment by theriyazo** [comment]
Yes, @RagibAjmal that's great work!

**Comment by CodingSpecies** [comment]
> ![Screenshot 2021-12-11 at 3 54 15 PM](https://user-images.githubusercontent.com/73844685/145673179-31e68025-1a65-426d-a832-ce69bd193d8f.png)
> Is this fine

Yes it seems good and padded also thank you for changing the sizing @RagibAjmal

**Comment by RagibAjmal** [comment]
Thanks for you feedback @theriyazo @CodingSpecies  Can I make a PR then?

**Comment by Vyvy-vi** [comment]
sure, go ahead!

**Comment by RagibAjmal** [comment]
I have made  a PR, but its failing in build and test . I tried googling but couldn't resolve it , Does anyone know how to solve it

**Comment by emmalearnscode** [comment]
Added in PR #823
