### ISSUE TITLE
[FEATURE] Display random profile on homepage

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#7575]
### Description

1. api to get random profiles (list of users from environment variable)
2. display randomly selected profile from list on the homepage

note: use code from here to created UI https://github.com/EddieHubCommunity/LinkFree/pull/6998/files#diff-bd5cb53f7f62529ac08cd24699132a88e8567b73d93b5289764cfa29442b5720R139-R197
<img width="1326" alt="Screenshot 2023-06-14 at 14 32 54" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/4c251a94-30e0-4094-b71b-29b02489a656">

**Comment by Vishrut19** [comment]
Can I work on this?

**Comment by samthatcode** [comment]
> Can I work on this?

Can i also work on this as well? is that possible? I'm aware it has been assigned to someone already. I also need clarity please as this is my very first. thanks

**Comment by Vishrut19** [comment]
I am fine collaborating with someone else.

**Comment by webstar0103** [comment]
Can I work now?

**Comment by SaraJaoude** [comment]
> Can I work now?

@webstar0103 your message is not clear.  Are you asking this to be assigned to you? This has already been assigned - please read the history and familiarise yourself with the [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) so that you are aware of project's requirements.

**Comment by SaraJaoude** [comment]
> > Can I work on this?
> 
> Can i also work on this as well? is that possible? I'm aware it has been assigned to someone already. I also need clarity please as this is my very first. thanks

@samthatcode I have assigned this to you and suggest you discuss this with @Vishrut19

**Comment by samthatcode** [comment]
> I am fine collaborating with someone else.

Hello Dev @Vishrut19 , I also got assigned to feature that was assigned to you and the message said to discuss with you how to go about it. What do you propose and how do you think we should start with the collaboration?. This is my first time and i welcome suggestions and what to do. I have seen your Github profile as well and i think you're more experienced than i am. Looking forward to working with you on this one. I have Installed necessary dependencies and got everything working on ly local machine, Ran the server with mongoDB and it was a success and the database was populated. Kindly get back to me so we can get started. Need more clarification on the description above and this issue that was mentioned by [SaraJaoude](https://github.com/SaraJaoude)
[FEATURE] Add user profile in the Navbar #4995. thanks

**Comment by eddiejaoude** [comment]
> Need more clarification on the description above and this issue that was mentioned by [SaraJaoude](https://github.com/SaraJaoude)
[FEATURE] Add user profile in the Navbar https://github.com/EddieHubCommunity/LinkFree/issues/4995

Please ignore issue #4995 this has been done and is in a PR. Just focus on this issue

**Comment by samthatcode** [comment]
> > Need more clarification on the description above and this issue that was mentioned by [SaraJaoude](https://github.com/SaraJaoude)
> [FEATURE] Add user profile in the Navbar https://github.com/EddieHubCommunity/LinkFree/issues/4995
> 
> Please ignore issue #4995 this has been done and is in a PR. Just focus on this issue 

Okay thanks

**Comment by webstar0103** [comment]
Hello there,
I can't install node_modules.

***@***.***: Permission denied (publickey).
fatal: Could not read from remote repository.
this is error message.
Can you help me?

**Comment by samthatcode** [comment]
I have implemented the [FEATURE] Display random profile on homepage
#7575 in my local machine by { 1. api to get random profiles (list of users from environment variable), 
   2. display randomly selected profile from list on the homepage }
 and its working by displaying a random profile in the homepage just after the LinkFree 100% OpenSource paragraph but haven't pushed yet.  I'm having a question which is the screenshot provided above for clarification and also to ask if the profile should display subsequent profile at random say every 5 seconds just to be dynamic(just my opinion). thanks and will expect feedback

**Comment by eddiejaoude** [comment]
@samthatcode I commented on the PR

@Vishrut19 are you collaborating on this PR?

**Comment by SaraJaoude** [comment]
@Vishrut19 I have unassigned this from you for the following reasons: https://github.com/EddieHubCommunity/LinkFree/issues/7637 In the future if you do not want to collaborate then please unassign yourself. 

@samthatcode please do reach out if you need any help with this, particularly as we understand that when you asked to work on this you were under the impression you would be doing so with another community member.

**Comment by SaraJaoude** [comment]
Closing as PR has been merged.
