### ISSUE TITLE
[OTHER] <Placement of Community Resources>

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/LinkFree#7581]
### What would you like to share?

Highlighting Non-coding contributions discussion
I recently read [this article](https://github.com/readme/featured/open-source-non-code-contributions). I think there’s more that can be done to show new members that Linkfree accepts non-coding contributions. Like a disclaimer or pin examples of merged non-code prs. By the way, it’s June 14th not July 14th(referring to the Office Hours title).

> We do have non code contributions docs page, it would be good to add more information to this page https://linkfree.io/docs/community-resources

**Comment by eddiejaoude** [comment]
I will copy the context from the GitHub Discussion, and update the issue to give context

**Comment by SaraJaoude** [comment]
How to best highlight these contributions will be discussed with the design team when we redesign the website in the future so I will close this issue for now
