### ISSUE TITLE
the github logo not looking good in the responsive part

### ISSUE THREAD

**Issue by devagya-rattan** [EddieHubCommunity/LinkFree#7590]
### Description

github logo below the testimonial section is misplaced

### Screenshots

![Screenshot (37)](https://github.com/EddieHubCommunity/LinkFree/assets/112056749/a7435ce3-8e73-48d3-89fa-894bd11ca5df)

**Comment by eddiejaoude** [comment]
Thank you for raising the issue. That is the Tailwind component design. Not sure what alternative solution is being suggested, so I will close this issue
