### ISSUE TITLE
New Testimonial for Pradumna Saraf

### ISSUE THREAD

**Issue by Anushka-codergirl** [EddieHubCommunity/LinkFree#7592]
### Name

Pradumnasaraf

### Title

The Open-source guy

### Description

Pradumna is a highly skilled developer, an active open-source contributor, and a great communicator. He puts forth a lot of effort and constantly encourages others in the community. He shares insightful information, which is fantastic!

**Comment by Pradumnasaraf** [comment]
Hey, 

Thank you so much, Anushka for your kind word 🙏.

Also, when we are meeting next?
