### ISSUE TITLE
[BUG] Profile link does not preview correctly on share

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#7604]
### Description

The `ogImage` and the `cleanBio` are incorrect

```diff
- ogImage={data.avatar}
+ ogImage={`https://github.com/${data.username}.png`}
```

<img width="361" alt="Screenshot 2023-06-15 at 22 14 03" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/3e717ef5-fed5-41ba-b476-9de435dba278">

**Comment by sandramsc** [comment]
Can I have this assigned to me?
