### ISSUE TITLE
[UI] Content Overflow in user profile card

### ISSUE THREAD

**Issue by Deveesh-Shetty** [EddieHubCommunity/LinkFree#7605]
### Description

The description text is overflowing below the card in the search bar profile suggestions

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/89470104/f6dbf04e-6dfc-4c10-9ccf-4487fb613d91)

### Additional information

The potential solution can be either limiting the number of characters in the description or making the card responsive to the text

**Comment by eddiejaoude** [comment]
Thank you for raising, I can't replicate, so I will close

<img width="1668" alt="Screenshot 2023-06-16 at 09 40 16" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/fd267200-a386-41c5-98ae-248431867fed">
