### ISSUE TITLE
[FEATURE] Remove animation from notes

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#7623]
### Description

On this page there is a notification that flashes infinitely, this issue is to remove that animation.

Page: https://linkfree.io/docs/environments/local-development

Related CSS:
```
.animate-pulse {
    -webkit-animation: pulse 2s cubic-bezier(.4,0,.6,1) infinite;
    animation: pulse 2s cubic-bezier(.4,0,.6,1) infinite;
}
```

**Comment by shashwatshiv** [comment]
hello, i  would like to work on this issue.

**Comment by shashwatshiv** [comment]
i understood the problem and have identified the html class causing it,  thus I will remove it.

**Comment by Shiv-2712** [comment]
I want to work on this issue

**Comment by amandamartin-dev** [comment]
> hello, i would like to work on this issue.

Thank you, I have assigned you to this issue.

**Comment by eddiejaoude** [comment]
I think the `components/Alert.js` has the class `animate-pulse` which can be removed and should solve this issue

**Comment by shashwatshiv** [comment]
yes. working on it. Thank you.
