### ISSUE TITLE
Border Color is not visible

### ISSUE THREAD

**Issue by anikdhabal** [EddieHubCommunity/LinkFree#7642]
### Description

Border Color is not visible for the first event in event list.

### Screenshots

![Screenshot 2023-06-17 115456](https://github.com/EddieHubCommunity/LinkFree/assets/81948346/42c7cb3f-a5ef-446b-8033-0d65d973a3ed)
![Screenshot 2023-06-17 115440](https://github.com/EddieHubCommunity/LinkFree/assets/81948346/7e46c525-7b85-47ab-ba44-39fe87fc0d52)

**Comment by anikdhabal** [comment]
Can you assign me to this issue?

**Comment by web-dev-kushal** [comment]
Hey i would like to work on this issue

**Comment by rahulkhattri0** [comment]
I think I can handle that.

**Comment by harshit-senpai** [comment]
hey i looked into the problem at `https://linkfree.io/events` and will love to work on it as a guy who works with tailwind css

**Comment by yassineatik** [comment]
Hi there , 
I would love to contribute in this project , and fix this error

**Comment by SaraJaoude** [comment]
> Can you assign me to this issue?

@anikdhabal I have assigned this to you as you were the first to request. In future if you would like to work on an issue that you have created, feel free to mention this in the `Additional Information` of the issue template.

**Comment by anikdhabal** [comment]
> > Can you assign me to this issue?
> 
> @anikdhabal I have assigned this to you as you were the first to request. In future if you would like to work on an issue that you have created, feel free to mention this in the `Additional Information` of the issue template.

okk

**Comment by anikdhabal** [comment]
> > Can you assign me to this issue?
> 
> @anikdhabal I have assigned this to you as you were the first to request. In future if you would like to work on an issue that you have created, feel free to mention this in the `Additional Information` of the issue template.

okk

**Comment by vishalsingh2972** [comment]
@anikdhabal are you still working on this ? otherwise I would like to give this a try @SaraJaoude !

**Comment by anikdhabal** [comment]
> @anikdhabal are you still working on this ? otherwise I would like to give this a try @SaraJaoude !

yes I am working on this.

**Comment by SaraJaoude** [comment]
> anikdhabal are you still working on this ? otherwise I would like to give this a try @SaraJaoude !

@vishalsingh2972 please avoid putting pressure on assignees especially when they have been assigned the issue less than two weeks ago.In future also please avoid tagging a specific maintainer for generic questions as this adds noise and extra notifications - all maintainers receive the project's notifications and can deal with these. I would suggesting looking at our [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md).

**Comment by dan-mba** [comment]
Closing issue as it is superseded by #7840
