### ISSUE TITLE
[BUG] GitHub Accelerator logo is out of screen

### ISSUE THREAD

**Issue by anikdhabal** [EddieHubCommunity/LinkFree#7643]
### Description

GitHub Accelerator logo is out of the page in small screen.

### Screenshots

![Screenshot 2023-06-17 120100](https://github.com/EddieHubCommunity/LinkFree/assets/81948346/4d415b76-6007-4a5a-8610-00b98155a8ab)

**Comment by SaraJaoude** [comment]
Thank you for your suggestion, but this appears to be a duplicate of: https://github.com/EddieHubCommunity/LinkFree/issues/6658 so I will close this Issue for now.
