### ISSUE TITLE
Consistency Issue: `getUsers` should be renamed to `getProfiles`

### ISSUE THREAD

**Issue by krishstwt** [EddieHubCommunity/LinkFree#7648]
### Description

Under `​pages/api/profiles/index.js`:

https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/api/profiles/index.js#L16

This function should be renamed to `getProfiles` for consistency.

### Screenshots

https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/api/profiles/index.js#L16

### Additional information

Caught live: https://www.youtube.com/watch?v=lBqZj7hJHJ4

**Comment by eddiejaoude** [comment]
Thanks for raising 👍 

Changes required...
- line 12 and 16 in `pages/api/profiles/index.js`
- line 11 and 26 `pages/map.js`
- line 13 and 23 `pages/search.js`

**Comment by SaraJaoude** [comment]
I have blocked this issue until the current open related PRs have been merged

**Comment by Harshalshirote2002** [comment]
Could you please assign this issue to me?

**Comment by SaraJaoude** [comment]
> Could you please assign this issue to me?

@Harshalshirote2002 I have assigned this to you
