### ISSUE TITLE
Add date formatting functionality 

### ISSUE THREAD

**Issue by EmmaDawsonDev** [EddieHubCommunity/LinkFree#7650]
### Description

To avoid repetition, either add a date formatting helper function or add a date library such as date fns.

**Comment by eddiejaoude** [comment]
Thanks Emma 👍

**Comment by Vishrut19** [comment]
I can work on it

**Comment by SaraJaoude** [comment]
> I can work on it

@Vishrut19 I have assigned this to you

**Comment by SaraJaoude** [comment]
> > I can work on it
> 
> @ Vishrut19 I have assigned this to you

@Vishrut19 how are you getting on?

**Comment by Vishrut19** [comment]
I am working on it. Just give me some time as I was not well. I will work and raise a PR in 2-3 days. Hope that's okay.

**Comment by Vishrut19** [comment]
Hey ! I am trying to work on it but stuck with this issue. Someone please help
![image](https://github.com/EddieHubCommunity/LinkFree/assets/53470896/56e0037c-a90a-4a97-82fd-5ba4f3d47dde)

**Comment by eddiejaoude** [comment]
@Vishrut19 please keep the issue discussion **focused** on the issue otherwise it creates noise for everyone. Environment setup questions are best discussed in EddieHub Discord

**Comment by Vishrut19** [comment]
> @Vishrut19 please keep the issue discussion **focused** on the issue otherwise it creates noise for everyone. Environment setup questions are best discussed in EddieHub Discord

I have asked about it on Discord as well but got no response on it.

**Comment by Vishrut19** [comment]
Someone Please review my [PR](https://github.com/EddieHubCommunity/LinkFree/pull/7978)
