### ISSUE TITLE
[DOCS] Update Linkfree Profile Creation tutorial 

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/LinkFree#7652]
### Description

Once #5575 is addressed, I’d like to update the tutorial on how to create a Linkfree profile. This is important so that users can create their profiles effectively.

**Comment by SaraJaoude** [comment]
Thanks @CBID2 but we want to ensure PR https://github.com/EddieHubCommunity/LinkFree/pull/6998 follows best practices, so the documentation for Issue https://github.com/EddieHubCommunity/LinkFree/issues/5575 will be included within said PR.  I will therefore close this Issue.
