### ISSUE TITLE
[FEATURE] Optimization for images

### ISSUE THREAD

**Issue by krshkun** [EddieHubCommunity/LinkFree#766]
### Description

We could download and store the images in `public/` prebuild and then fetch from there instead, this will allow us control to optimize and compress images :D

### Screenshots

![Uploading image.png…]()

**Comment by MadhaviMandalia** [comment]
Hello @krishguptadev ,

Can you explain a bit more about it?

**Comment by eddiejaoude** [comment]
Now with the new version using NextJS, we have image optimisation - I will close this and if required a new one can be opened
