### ISSUE TITLE
[FEATURE] top Nav bar to remain "fixed" upon scrolling

### ISSUE THREAD

**Issue by preston176** [EddieHubCommunity/LinkFree#7674]
### Description

the user experience can be enhanced by making the top navigation bar remain fixed at the top of the page while scrolling. This improvement will provide better navigation accessibility and convenience for users, ensuring that the navigation menu is always accessible regardless of the page position.

By implementing this feature, users will have a consistent and persistent navigation experience, allowing them to easily access different sections of the website without the need to scroll back to the top of the page.

### Screenshots

![pic1](https://github.com/EddieHubCommunity/LinkFree/assets/49411983/ffe87ff4-4b76-4c40-b094-66a703ad761d)

**Comment by SaraJaoude** [comment]
Thank you for your suggestion.  However as we will be going through a website shortly there is no point making these changes presently, so I will close this Issue.
