### ISSUE TITLE
[FEATURE]: Filter by name Feature

### ISSUE THREAD

**Issue by Petsamuel** [EddieHubCommunity/LinkFree#7676]
### Description

Add a filter by name feature to add/improve pagination functionality. Users will be able to search and retrieve specific information based on their name/username not just their tags, enhancing data navigation and organization.

This feature will provide a more streamlined user experience and efficient handling of large datasets.

**Comment by SaraJaoude** [comment]
Thank you for the suggestion.  However the ability to search by name and username is already present, I will be closing this issue.
