### ISSUE TITLE
Help icon is overlapping github and youtube icon in tablet view which makes both the icon non-clickable

### ISSUE THREAD

**Issue by KushagraVarshney05** [EddieHubCommunity/LinkFree#7678]
### Description

Help button is overlapping github and youtube icon in tablet view which makes both the icon non-clickable

### Screenshots

![Screenshot 2023-06-19 032529](https://github.com/EddieHubCommunity/LinkFree/assets/112865931/fa9447e6-af47-4891-bfbc-dd53f239859a)

### Additional information

i wnat to contribute to this

**Comment by SaraJaoude** [comment]
This has been raised several times before however no one has proposed a solution. 

As you have raised this Issue and mentioned you would like to work on it, how do you propose this is resolved?

**Comment by dan-mba** [comment]
A potential fix is adding the class `pb-8` to the footer element.

**Comment by jasalltime** [comment]
@dan-mba actually ```class="pb-8"``` is present there instead we can do `class="pb-20"` .  Here's how it looks:-

https://github.com/EddieHubCommunity/LinkFree/assets/88364383/97d38fbf-6ece-4f21-bb33-2c3b52f94837

This is from Chrome but I also checked on Brave and Edge. Also, this problem exists in medium/large/very large font sizes in browsers in pc also.
@SaraJaoude please give feedback and please assign me if possible.

**Comment by SaraJaoude** [comment]
@dan-mba and @jasalltime thank you both for your comments and support

@KushagraVarshney05 as you request first I will assign this to you

**Comment by satyam4484** [comment]
can i work on this issue or it's has been assigned

**Comment by SaraJaoude** [comment]
> can i work on this issue or it's has been assigned

@satyam4484 in future please have a look at the `Assignees` box at the top of the page - this shows whether an issue has been assigned or not. This will answer your question immediately and help reduce notifications for people on the project.

**Comment by satyam4484** [comment]
sure, mam i am new to it so don't know about how all this things works.

**Comment by KushagraVarshney05** [comment]
thanks for the suggestion @jasalltime as of now it is a woking after giving padding in the footer.
