### ISSUE TITLE
[DOCS] <Clarity needed in Links Grouping>

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/LinkFree#7682]
## Problem
I noticed that the Links Grouping Guide only has a screenshot. While helpful, users might be wondering how to actually do it.

## Proposed Solution

Add brief directions with a code snippet from a current user’s profile as an example.

### Screenshots

![Proof of problem](https://github.com/EddieHubCommunity/LinkFree/assets/105683440/62fb001a-3424-466a-8131-50ea8fb132b7)

### Additional information

I’m open to collaborate with anyone on this issue.

**Comment by SaraJaoude** [comment]
Thanks @CBID2 this is such a small change -  1 point - I do not think this requires a collaboration. Shall I assign it to you?

**Comment by SaraJaoude** [comment]
> > Thanks @CBID2 this is such a small change -  1 point - I do not think this requires a collaboration. Shall I assign it to you?
> 
> Yes @SaraJaoude

Done!
