### ISSUE TITLE
[FEATURE] Add pagination to the search page 

### ISSUE THREAD

**Issue by detronetdip** [EddieHubCommunity/LinkFree#7703]
### Description

Currently, the search page in this project lacks a pagination system, which makes it difficult for users to navigate through search results efficiently. To improve user experience and enhance usability, we should consider implementing a pagination feature.

**Proposed Solution:**

1. Introduce a pagination component that allows users to navigate through search results pages.
2. Display a limited number of results per page, with options to navigate to previous or next pages.

**Benefits:**

1. Enhanced user experience by simplifying navigation through search results.
2. Improved performance by loading only the necessary data per page.
3. Better usability, especially for users with large search result sets.

**Comment by detronetdip** [comment]
@eddiejaoude please review it and I would love to know your thoughts on this. Also If my proposal resonates to you I would love to work on this feature

**Comment by badrivlog** [comment]
Hey @detronetdip i think the issue you suggested this already has opened #7599 and I've been working on this

**Comment by detronetdip** [comment]
@badrivlog  I am extremely sorry. 


Closing
