### ISSUE TITLE
[Docs] Clarity needed in Links and Editing Guidelines 

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/LinkFree#7722]
## Problem 
In rereading the code snippets in the Links and Editing guidelines, they both say to format the profile section like in the following ways:

- Example in [Links](https://linkfree.io/docs/how-to-guides/links)

```
 "links": [
    {
      "name": "Follow me on Twitter",
      "url": "https://twitter.com/SaraJaoude",
      "icon": "FaTwitter"
    },
    {
      "name": "Follow me on Instagram",
      "url": "https://twitter.com/EddieAndSaraExplore",
      "icon": "FaInstagram"
    }
  ]
```
- Example in Editing 
Refer to the screenshot section 

But I was told here that [the comma needs to be present](https://github.com/EddieHubCommunity/LinkFree/pull/7701/files#r1235937160).

## Possible Solution 
Update the code snippets to fit [this advice](https://github.com/EddieHubCommunity/LinkFree/pull/7701/files#r1235937160)

## Benefits 
The change would help reviewers give contributors consistent advice on how to improve or create the Links section of their Linkfree profile.

### Screenshots

<img width="1664" alt="0F74C275-71FE-4851-B5DB-0E86F4BC3DF0" src="https://github.com/EddieHubCommunity/LinkFree/assets/105683440/dc4c72be-cd38-4fb6-a8b1-695fc32c5cdf">

### Additional information

I’m open to collaboration requests and suggestions.

**Comment by eddiejaoude** [comment]
Thanks for raising the issue @CBID2 👍 

In the example you shared above from the documentation, the json is correct, the `icon` property shouldn't have a trailing comma. 

However, in the link you shared to the PR comment, the `icon` property should have a trailing comma.

The comma is not determined by the name of the property but by the structure of the object. You may find this guide "JSON for beginners" by FreeCodeCamp helpful https://www.freecodecamp.org/news/what-is-json-a-json-file-example/

So I will close this issue
