### ISSUE TITLE
[DOCS] Updating LinkFree Preview (README)

### ISSUE THREAD

**Issue by Pradumnasaraf** [EddieHubCommunity/LinkFree#773]
### Description

Updating the LiknFree preview picture in README.

## Current:
![old](https://user-images.githubusercontent.com/51878265/145021923-1a58f8de-4662-4350-b3be-9e03650dd1b0.png)

## Updated one:

![Screenshot from 2021-12-07 17-04-14](https://user-images.githubusercontent.com/51878265/145022063-641fc0bb-bab5-4b6d-ab34-ae64dd53a863.png)

### Additional information

N/A

**Comment by krishguptadev** [comment]
I would like to work on this 🙂

**Comment by Pradumnasaraf** [comment]
> I would like to work on this slightly_smiling_face

In my opinion, It's very beginner-friendly. I think letting some newcomers resolve this issue :)

**Comment by krishguptadev** [comment]
> > I would like to work on this slightly_smiling_face
> 
> In my opinion, It's very beginner-friendly. I think letting some newcomers resolve this issue :)

oops, I've already made the PR now 😅

**Comment by Pradumnasaraf** [comment]
> > > I would like to work on this slightly_smiling_face
> > 
> > 
> > In my opinion, It's very beginner-friendly. I think letting some newcomers resolve this issue :)
> 
> oops, I've already made the PR now sweat_smile

Haha, No worries :nerd_face:
