### ISSUE TITLE
[OTHER] <Improve readability of search input >

### ISSUE THREAD

**Issue by Sahil-Choudhary-17** [EddieHubCommunity/LinkFree#7751]
### What would you like to share?

Current Behavaiour:
![currentSearchInput](https://github.com/EddieHubCommunity/LinkFree/assets/128586019/658a5e44-a34d-4b23-aff3-7058683d822d)

Space can be added after each comma of the tag to improve readability of the search input.

After adding space:
![img17](https://github.com/EddieHubCommunity/LinkFree/assets/128586019/f208f686-eb27-4ccd-b13d-158bd6af9630)

 I would like to work on the Issue once it has been triaged and label changed to status: ready for dev.

**Comment by SaraJaoude** [comment]
@Sahil-Choudhary-17 thank you for your suggestion - I have assigned this to you
