### ISSUE TITLE
[DOCS] Incomplete command to start docker for mongo

### ISSUE THREAD

**Issue by md-abid-hussain** [EddieHubCommunity/LinkFree#7766]
### Description

In automated test documentation **the command to start docker for mongo only is incomplete or does not work**
```
docker compose -f mongo-compose.yml
```
Running the above command does not start the container
It should be

```
docker compose -f mongo-compose.yml up
```

### Screenshots

![Screenshot (67)](https://github.com/EddieHubCommunity/LinkFree/assets/101964499/cbbebb13-793f-44a9-a895-6e5f7d1e8f21)

**Comment by SaraJaoude** [comment]
@md-abid-hussain so that maintainers can properly triage this issue can you please update the description to explain what is missing

**Comment by krishstwt** [comment]
It has to be changed to `docker compose -f mongo-compose.yml up` as they updated the message

**Comment by eddiejaoude** [comment]
Thanks @krishstwt 👍

**Comment by md-abid-hussain** [comment]
Can you assign me this issue

**Comment by amandamartin-dev** [comment]
@md-abid-hussain assigned you!
