### ISSUE TITLE
[DOCS] Adding the new supported icons in the README

### ISSUE THREAD

**Issue by Pradumnasaraf** [EddieHubCommunity/LinkFree#777]
### Adding the new supported icons to the README
Some Are
- Book
- Dollar

**Comment by krishguptadev** [comment]
The following icons are supported
https://github.com/EddieHubCommunity/LinkFree/blob/204f6c4e7f43d7fcc1dcae84e5ab70aa271d65a5/src/config/links.json#L1-L26

IE, the dollar is not supported 🙂 It is just that you can use all icons available in <https://www.primefaces.org/primereact/showcase/#/icons> if you don't want the colours 👍

**Comment by unnikrishnan2002** [comment]
Hey , I would love to contribute to this issue . Can you please brief the issue once more , I didn't understand it clearly 😄

**Comment by Pradumnasaraf** [comment]
#### You have to add the remaining icon (picture) which is supported in LinKFree

----

#### You have to add it here

![Screenshot from 2021-12-08 16-01-34](https://user-images.githubusercontent.com/51878265/145193140-7d355db7-54a2-46fa-b805-a83cbfaedcdf.png)

 If You still have a problem come on Discord and have an open discussion :)

**Comment by unnikrishnan2002** [comment]
Ahh! Got it thanks 👍

**Comment by unnikrishnan2002** [comment]
Hey @Pradumnasaraf I added the dollar and book icon. Rest of the icons are not there in Prime React

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf I added the dollar and book icon. Rest of the icons are not there in Prime React

No problem, add those only :)

**Comment by unnikrishnan2002** [comment]
> > Hey @Pradumnasaraf I added the dollar and book icon. Rest of the icons are not there in Prime React
> 
> No problem, add those only :)

Okay cool
