### ISSUE TITLE
Fixing Icons 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [EddieHubCommunity/LinkFree#7771]
### Description

The PR https://github.com/EddieHubCommunity/LinkFree/pull/7738/files is a great example of how we should import icons, in the `manage-forms` branch PR https://github.com/EddieHubCommunity/LinkFree/pull/6998/files the icons are imported in the old (wrong) way (used the documentation example but tree shaking not working)

**Comment by Pradumnasaraf** [comment]
Hey, @rohan-kulkarni-25.

The PR wasn't imported in the wrong way. This PR fixed the wrong imports.

**Comment by eddiejaoude** [comment]
PR merged
