### ISSUE TITLE
[BUG] Missing type parameter

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/LinkFree#779]
### Description

*If you've already forked this repository, skip to step 3*

1. Fork the repository [here](https://github.com/EddieHubCommunity/LinkFree/fork).
2. Make a new branch named `add_type_parameter`.
3. Go to [`public/data/taravis.json`](https://github.com/EddieHubCommunity/LinkFree/blob/main/public/data/taravis.json) (remember to open that file in your fork!).
4. After line 2, add the following content:

```json
  "type": "personal",
```

Now you should be ready to make your PR and get this fixed! 🚀

### Additional information

This is a good first issue. Please leave this open to beginners and first-time contributors. 🙂

**Comment by VaibhavUpreti** [comment]
Hi can i work on this.

**Comment by Vyvy-vi** [comment]
closed by 180c66b in #782
