### ISSUE TITLE
[BUG] List Item is not visible inside seacrh box on Dark mode

### ISSUE THREAD

**Issue by anikdhabal** [EddieHubCommunity/LinkFree#7792]
### Description

When the screen size is small and in dark mode, the search item is not visible. It working properly in light mode.
![Screenshot 2023-06-25 233943](https://github.com/EddieHubCommunity/LinkFree/assets/81948346/6dc16b3f-8011-4ac7-9b2c-d57af8ecd1ad)

### Screenshots

![Screenshot 2023-06-25 234610](https://github.com/EddieHubCommunity/LinkFree/assets/81948346/814be812-5684-4660-a7f0-3c7b624f3260)

### Additional information
I want to work on this.
_No response_

**Comment by eddiejaoude** [comment]
Good spot, thank you 👍

**Comment by md-abid-hussain** [comment]
If no one is assigned to work on this issue can you assign it to me?

**Comment by SaraJaoude** [comment]
@anikdhabal I have assigned this to you as you requested to work on it when raising the Issue.
