### ISSUE TITLE
[DOCS] Remove extra backward slash

### ISSUE THREAD

**Issue by Pradumnasaraf** [EddieHubCommunity/LinkFree#780]
### Remove extra backward slash

* Line Permanent [Link](https://github.com/EddieHubCommunity/LinkFree/blob/be46fba3fd551fd23cc089d7b6ea376b2e29e64f/README.md?plain=1#L131) 

Before Changes:

`For example: http://linkfree.eddiehub.org/eddiejaoude\`

After Changes:

`For example: http://linkfree.eddiehub.org/eddiejaoude`

### Screenshots

![Screenshot from 2021-12-08 08-21-44](https://user-images.githubusercontent.com/51878265/145141292-0abf3be4-b2f4-4a9e-b623-976101f68548.png)

### Additional information

N/A

**Comment by VaibhavUpreti** [comment]
Hey! Can i take this.

**Comment by Pradumnasaraf** [comment]
> Hey! Can i take this.
> 

Yes Go Ahead
