### ISSUE TITLE
[FEATURE] Animating the navlinks

### ISSUE THREAD

**Issue by rohan9024** [EddieHubCommunity/LinkFree#7810]
### Description

Adding an hover effect on the navlinks

### Screenshots

Before-->

https://github.com/EddieHubCommunity/LinkFree/assets/64919642/5b1de8be-8f76-43b8-8313-bcb5fe6efcc1

After -->

https://github.com/EddieHubCommunity/LinkFree/assets/64919642/d8803fc8-131d-4551-8a36-fe039c50f5ec

**Comment by SaraJaoude** [comment]
Thank you for your suggestion.  However as we will be redesigning the website in the near future I will close this issue.
