### ISSUE TITLE
[BUG] Events no more show the speaker status and topic

### ISSUE THREAD

**Issue by Pradumnasaraf** [EddieHubCommunity/LinkFree#7820]
### Description

The user status and topic are not being displayed on the event tile on the events page (https://linkfree.io/events). They used to appear when the user added the following properties:

```json
  "userStatus": "speaking",
  "speakingTopic": "Open Source"
```

### Screenshots

<img width="1323" alt="Screenshot 2023-06-28 at 1 42 34 PM" src="https://github.com/EddieHubCommunity/LinkFree/assets/51878265/e6a3be58-dee1-4419-abd8-101057cc1546">

### Additional information

We need to be careful while fixing this bug because now we group events, and what if two users are speaking at the same conference?

**Comment by amandamartin-dev** [comment]
if we are grouping events now, does it make sense to only show these fields on the person profile page and not the main events page?

**Comment by Pradumnasaraf** [comment]
> if we are grouping events now, does it make sense to only show these fields on the person profile page and not the main events page?

This is a great point, Amanda.

**Comment by eddiejaoude** [comment]
Thanks @Pradumnasaraf for noticing the bug 👍 

Great solution @amandamartin-dev 💯 

Also we would need to update the json docs to include these, as I think they got missed, plus we would need the event form updating as part of this issue also

TODO/NOTES
- json event docs
- reload script to include this data
- event form to give these options
- only show this information on the profile events section

**Comment by akash19coder** [comment]
I want to work on this issue.

**Comment by amandamartin-dev** [comment]
> I want to work on this issue.

Thank you, I have assigned you.
