### ISSUE TITLE
[BUG] Events CSS issue

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#7840]
### Description

Events in light mode are missing the top border color at each card, this is likely due to a recent deployment.

Dark mode is affected here as well as described by @dan-mba : 
The class border-l-3 is not being handled by Tailwind.
The reorg of the EventCard added a wrapper to the previous card which has a #e5e7eb border, so it only shows in dark mode.

https://linkfree.io/events

Now:
![no border](https://github.com/EddieHubCommunity/LinkFree/assets/97615019/d3ff447c-4e5b-4735-9ad5-13fc125e4b4c)

Previously:
![event duplicate](https://github.com/EddieHubCommunity/LinkFree/assets/97615019/cbc904ba-c811-4ef1-b716-c8c15a3f6a4d)

**Comment by dan-mba** [comment]
This problem is more complicated.

It affects dark mode as well.
The class `border-l-3` is not being handled by Tailwind.

The reorg of the EventCard added a wrapper to the previous card which has a `#e5e7eb` border, so it only shows in dark mode.

**Comment by amandamartin-dev** [comment]
Thanks @dan-mba for the additional details.  I couldn't remember what dark mode looked like previously. I will add your notes to the issue description

**Comment by dan-mba** [comment]
@anikdhabal please comment on this issue so I can assign it to you.

**Comment by anikdhabal** [comment]
> @anikdhabal please comment on this issue so I can assign it to you.

pls assign me this issue
