### ISSUE TITLE
[BUG] milstones with a date that doesn't convert to a JavaScript Date fail on import

### ISSUE THREAD

**Issue by dan-mba** [EddieHubCommunity/LinkFree#7843]
### Description

When connecting to `/api/system/reload`, the server console is displaying errors on milestones.

An example of the error message is:
```
Cast to date failed for value \"Jan '23 to April '23\" (type string) at path \"date\"
```

**Comment by eddiejaoude** [comment]
Possible solution to use todays date? Then the user can update using forms

**Comment by dan-mba** [comment]
> Possible solution to use todays date? Then the user can update using forms

I think omitting the date all together would be a better solution.
This should keep the order as is & avoid any attempt to sort by date.

**Comment by eddiejaoude** [comment]
Good point 👍
