### ISSUE TITLE
[BUG] edit icon covers brand icons

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/LinkFree#7844]
### Description

I noticed that the brand icons I used to add context about my Milestones are covered by the pencil icon.

### Screenshots

![737793CB-2E6C-4EC7-A891-F2A4A6E77397](https://github.com/EddieHubCommunity/LinkFree/assets/105683440/6f6574bb-628c-417b-9550-c1565ea706fc)

### Additional information

I’m open to collaborating with someone else on fixing this issue.

**Comment by SaraJaoude** [comment]
It would be good to come up with a temporary solution until the website is redesigned.

**Comment by CBID2** [comment]
> It would be good to come up with a temporary solution until the website is redesigned. 
> 
> 
> 
> 

And that's the part I'm stuck on lol 😆

**Comment by SaraJaoude** [comment]
> > It would be good to come up with a temporary solution until the website is redesigned.
> 
> And that's the part I'm stuck on...hmmm...maybe... the EddieHub mascot could be the icons for now until the issue is solved?

@CBID2 I am not sure what icon you are referring to in your message - the edit icon or the milestone icon.  Either way these should not change - the edit icon needs to be consistent throughout the forms and users need to be able to choose their own milestone icon. 

Introducing a third icon would in any event not solve the problem.  The problem as your issue states is not the icon itself but its positioning.

**Comment by CBID2** [comment]
> > > It would be good to come up with a temporary solution until the website is redesigned.
> 
> > 
> 
> > And that's the part I'm stuck on...hmmm...maybe... the EddieHub mascot could be the icons for now until the issue is solved?
> 
> 
> 
> @CBID2 I am not sure what icon you are referring to in your message - the edit icon or the milestone icon.  Either way these should not change - the edit icon needs to be consistent throughout the forms and users need to be able to choose their own milestone icon. 
> 
> 
> 
> Introducing a third icon would in any event not solve the problem.  The problem as your issue states is not the icon itself but its positioning. 

I'm referring to the pencil icons on my left. Yes, it's the postioning. I wonder if they could go to the right and be shrunken to a smaller size. Something like [!this](https://github.com/EddieHubCommunity/LinkFree/assets/105683440/d3da1fae-9760-42dd-b349-f5d52092b948)

**Comment by eddiejaoude** [comment]
The edit pencil was originally on the right, but then covered the date. I am not sure of the best temporary solution that would work on the other manage pages also

note: having the edit pencil button smaller would make it more difficult to use on mobile devices

**Comment by CBID2** [comment]
> The edit pencil was originally on the right, but then covered the date. I am not sure of the best temporary solution that would work on the other manage pages also
> 
> 
> 
> note: having the edit pencil button smaller would make it more difficult to use on mobile devices

Ooh then what do you recommend @eddiejaoude?

**Comment by eddiejaoude** [comment]
I am not sure, it will be resolved with the redesign, so not a big issue for now - people can preview the icon when in create or edit mode for that milestone, plus the pencil doesn't show on the public profile only when managing the milestones

**Comment by yoyoekta** [comment]
Can't we make the entire div smaller and add the pencil button to the right? (Like, wrapping it up in a div with display flex and two components in it, pencil and the content) It enhances user experience and UI design.

**Comment by Vishrut19** [comment]
Can I work on it??

**Comment by eddiejaoude** [comment]
> Can't we make the entire div smaller and add the pencil button to the right? (Like, wrapping it up in a div with display flex and two components in it, pencil and the content) It enhances user experience and UI design.

Yes I think that could work well @yoyoekta 👍

**Comment by vishalsingh2972** [comment]
@CBID2 can we work on this issue together if you're ok?

**Comment by hi-Kartik2004** [comment]
Is this issue still open to work?
was thinking if we could add a conditional margin left, if the user visits milestone.

**Comment by hi-Kartik2004** [comment]
Is this issue still open to work?
was thinking if we could add a conditional margin left, if the user visits milestone.

### Screenshot after the same in devtools
![image](https://github.com/EddieHubCommunity/LinkFree/assets/111000515/a6243680-6de3-4280-862d-54932820b4c0)

**Comment by eddiejaoude** [comment]
> Is this issue still open to work? was thinking if we could add a conditional margin left, if the user visits his milestone.
> 
> * After going throught the code base It seems that adding this line ${manage ? 'ml-12' : 'ml-0'}`} in the components/userMilestone.js line 26 should solve this issue.
> 
> ### Screenshot after the same
> ![image](https://user-images.githubusercontent.com/111000515/258564026-a6243680-6de3-4280-862d-54932820b4c0.png)

Give that a try 👍 I have assigned it to you
