### ISSUE TITLE
[DOCS] Capitalize `t` in the `Youtube` word

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/LinkFree#785]
### Description

*If you've already forked this repository, skip to step 3*

1. Fork the repository [here](https://github.com/EddieHubCommunity/LinkFree/fork).
2. Make a new branch named `capitalize_t`.
3. Go to [`README.md`](https://github.com/EddieHubCommunity/LinkFree/blob/main/README.md) (remember to open that file in your fork!).
4. In line 145, replace the current content with the following content:

```markdown
| Globe    | <img src="https://user-images.githubusercontent.com/32780232/143367620-5fe98cfa-7a18-4db7-95e4-0cd496acce7b.png" width=100% height=30%>  | YouTube   | <img 
```

### Additional information

This is a good first issue. Please leave this open to beginners and first-time contributors. 🙂

**Comment by kristin-wiseman** [comment]
Hi David,

I'd really like to try tackling this issue. I'm brand new to web development, but I did a short github tutorial and have already forked this repository. Thank you!

**Comment by Panquesito7** [comment]
Amazing! 🚀 Feel free to work on it. 😃

**Comment by krishguptadev** [comment]
@Panquesito7 I think this issue can be closed now 🙂
