### ISSUE TITLE
[FEATURE] Disable save button until changes are made to the profile through forms

### ISSUE THREAD

**Issue by ChinmayMhatre** [EddieHubCommunity/LinkFree#7853]
### Description

![image](https://github.com/EddieHubCommunity/LinkFree/assets/51131670/1a474484-7dce-4918-9aee-3921f274a2f9)
Can be done to save hits to the api till changes are made to the profile

### Additional information

Other forms should also have this feature
- profile form
- link form
- milestone form
- event form

**Comment by akash19coder** [comment]
I wanna work on it please assign it to me...

**Comment by mianakbarjan** [comment]
Hi there, I'd really love to work on this issue. Please assign it to me so that I can start working on it as soon as possible.

**Comment by SaraJaoude** [comment]
> I wanna work on it please assign it to me...

@akash19coder thank you for your enthusiasm, but as you recently had a PR merged it would be good to give someone else the opportunity to contribute.

**Comment by SaraJaoude** [comment]
> Hi there, I'd really love to work on this issue. Please assign it to me so that I can start working on it as soon as possible.

@mianakbarjan I have assigned this to you

**Comment by mianakbarjan** [comment]
Hi Sara! Before I create a PR, I wanted to ask if I should make this change to the other forms too as mentioned in the issue (link, milestone, and event) or just the profile form?

**Comment by eddiejaoude** [comment]
Closing due to accessibility concerns
