### ISSUE TITLE
[BUG] Ticket price not working correctly

### ISSUE THREAD

**Issue by Pradumnasaraf** [EddieHubCommunity/LinkFree#7854]
### Description

The event block looks different on the list and edit page. It stops adding a dollar sign on the preview on the right side. It should also it needs to show up correctly on the events page.
 

### Screenshots

![Screenshot_2023-06-28_at_3 47 19_PM](https://github.com/EddieHubCommunity/LinkFree/assets/51878265/aba35d94-3fd7-4666-b55d-97cd34f84c4c)![Screenshot_2023-06-28_at_3 36 01_PM](https://github.com/EddieHubCommunity/LinkFree/assets/51878265/cc4ae5d2-2827-4388-b6c5-75d481349f90)
![Screenshot_2023-06-28_at_3 37 02_PM](https://github.com/EddieHubCommunity/LinkFree/assets/51878265/2cde7c18-b5b5-47d1-8330-8952ea6147f2)

**Comment by akash19coder** [comment]
I wanna work on it please assign it to me :smile:

**Comment by itsdevdeepak** [comment]
i would like to work on it.

**Comment by SaraJaoude** [comment]
> I would like to work on this.

@itsdevdeepak I have assigned this to you
