### ISSUE TITLE
[BUG] Event Help not working -> 404 

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/LinkFree#7856]
### Description

Help link for events is not working.

https://linkfree.io/docs/how-to-guides/events

### Screenshots

<img width="505" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/30869493/aaec24bf-251f-4b7e-88aa-c478f6845cfc">

**Comment by eddiejaoude** [comment]
Good spot, thank you 👍
