### ISSUE TITLE
[BUG] Deleting a profile can add incorrect label

### ISSUE THREAD

**Issue by Pradumnasaraf** [EddieHubCommunity/LinkFree#7857]
### Description

Deleting the profile can also add https://github.com/EddieHubCommunity/LinkFree/labels/%E2%9C%8D%20chore%3A%20profile%20addition label because we trigger that when there is some change in data dir in review pad config.

https://github.com/EddieHubCommunity/LinkFree/blob/d2393f7989ea861b1c5ecee1f89eed5f8dc3478f/.github/config/reviewpad.yml#L17

**Comment by SaraJaoude** [comment]
We will rename the table so it is `chore: profile`
