### ISSUE TITLE
[BUG] A link not working in Readme.md

### ISSUE THREAD

**Issue by aj11anuj** [EddieHubCommunity/LinkFree#7858]
### Description

A link under GitHub Ui in the readme.md file that is redirecting the user to the LinkFree quickstart guideline is not working. 

I can fix it easily, can I work on that?

**Edit by Pradumna**
Correct link: https://linkfree.io/docs/quickstart-json

**Comment by Pradumnasaraf** [comment]
Hey, go ahead. The correct link is - https://linkfree.io/docs/quickstart-json. As it's part of the GitHub Section.

**Comment by Pradumnasaraf** [comment]
Hey @aj11anuj, go ahead. The correct link is - https://linkfree.io/docs/quickstart-json. As it's part of the GitHub Section.

**Comment by aj11anuj** [comment]
Ahm... when i got assigned this issue, it was 12:00AM in my country. So, at that time i went to sleep, in hope i will get assigned this issue, and i will fix it tommorow morning. but now it is already fixed by someone :(

**Comment by Pradumnasaraf** [comment]
> Ahm... when i got assigned this issue, it was 12:00AM in my country. So, at that time i went to sleep, in hope i will get assigned this issue, and i will fix it tommorow morning. but now it is already fixed by someone :(

Hey, 
Ya. someone fixed the issue by mistake.Please look for different issues
