### ISSUE TITLE
[BUG] Margin issue on linkfree homepage

### ISSUE THREAD

**Issue by Pradumnasaraf** [EddieHubCommunity/LinkFree#7860]
### Description

There should be some margin above the testimonials just like getting started

### Screenshots

<img width="1512" alt="Screenshot 2023-06-30 at 12 15 05 AM" src="https://github.com/EddieHubCommunity/LinkFree/assets/51878265/e968ce8c-ed64-45a4-a781-ca5aadfb657f">

**Comment by Ashish-simpleCoder** [comment]
Please assign me this issue.

**Comment by SaraJaoude** [comment]
> Please assign me this issue.

@Ashish-simpleCoder you already have one issue assigned to you (https://github.com/EddieHubCommunity/LinkFree/issues/7693) - we only assign one issue per person at any one time.

**Comment by CYBWEBALI** [comment]
I can fix this issue assign it to me.

**Comment by yassineatik** [comment]
Hi there , Can I work for this issue ?

**Comment by Shiv-2712** [comment]
Hi, can I work on this issue?

**Comment by SaraJaoude** [comment]
> I can fix this issue assign it to me.

@AlimurtuzaCodes I will assign this to you

**Comment by rajneesh-18** [comment]
Please assign this issue to me.

**Comment by eddiejaoude** [comment]
Please check if an issue is already assign first, as this was only assigned 3 hours ago (you can see directly above your comment), please read our contributing guide to learn more https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by rajneesh-18** [comment]
> Please check if an issue is already assign first, as this was only assigned 3 hours ago (you can see directly above your comment), please read our contributing guide to learn more https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

Ok sir

**Comment by AlimurtuzaCodes** [comment]
Done PR #7947 .
