### ISSUE TITLE
[DOCS] Replace long screenshot with a GIF

### ISSUE THREAD

**Issue by Pradumnasaraf** [EddieHubCommunity/LinkFree#787]
### Image that needs to be replaced

![Screenshot from 2021-12-09 08-36-24](https://user-images.githubusercontent.com/51878265/145327366-bcc9dbc4-2dcb-4fa9-8ec6-7879e3b88d15.png) 

### Additional information

Profile -  http://linkfree.eddiehub.org/eddiejaoude

For Video to GIF you can use - https://www.onlineconverter.com/video-to-gif

**Comment by RamK777-stack** [comment]
@Panquesito7 Can i work on this ?

**Comment by Vyvy-vi** [comment]
Go ahead, @RamK777-stack!
(maybe, we can get one that has consistent scroll speed?)

**Comment by LancelotHayward** [comment]
This is my first time using GitHub so I hope I haven't wasted @RamK777-stack 's time but I did this:
![linkfree 787](https://user-images.githubusercontent.com/82458069/145441873-258b4567-3a6f-45cf-a882-b545c111fbb3.gif)
(Sorry if this is is considered malpractice or rude)

**Comment by CodingSpecies** [comment]
@LancelotHayward thank you for contributing to this issue! 🎉
This is not malpracticing, but contributing to open source, and giving ideas and help to others! 
**This GIF is more smooth, but I think to make it better, please can we slow the scroll, so you can read the words on the screen.**
Maybe, after that is sorted, @RamK777-stack can use your gif, to make a pull request!
Thank you.

**Comment by LancelotHayward** [comment]
I slowed it down 50% and attempted to make a pull-request. Somehow I managed to mess that up though as there was an additional line I did not add. I also can't seem to edit or delete my pull request so I just left a comment. Overall, failure on my part ;(
I also failed to mention the issue id but I credited you both I think? 
https://github.com/EddieHubCommunity/LinkFree/commit/489882e5863d07f592d2ca8e20716e313bb1533f
Incase one of you knows how to override my pull request here's the gif:
![linkfree 787](https://user-images.githubusercontent.com/82458069/145475692-60ba916a-32f2-4af3-9859-56bc48e59dab.gif)

**Comment by Panquesito7** [comment]
> I slowed it down 50% and attempted to make a pull-request. Somehow I managed to mess that up though as there was an additional line I did not add. I also can't seem to edit or delete my pull request so I just left a comment. Overall, failure on my part ;( I also failed to mention the issue id but I credited you both I think? [489882e](https://github.com/EddieHubCommunity/LinkFree/commit/489882e5863d07f592d2ca8e20716e313bb1533f) Incase one of you knows how to override my pull request here's the gif: ![linkfree 787](https://user-images.githubusercontent.com/82458069/145475692-60ba916a-32f2-4af3-9859-56bc48e59dab.gif)

Looks better, but still too fast, can't read the text properly.

**Comment by LancelotHayward** [comment]
![linkfree 787 slow](https://user-images.githubusercontent.com/82458069/145483113-3eec620d-d3b4-41ff-9839-cf986bcd41cf.gif)
I slowed it down another 25%, how does that feel?

**Comment by Panquesito7** [comment]
What if you make it a little bit slower? That one looks good but still too quick, IMO.

**Comment by RamK777-stack** [comment]
> This is my first time using GitHub so I hope I haven't wasted @RamK777-stack 's time but I did this: ![linkfree 787](https://user-images.githubusercontent.com/82458069/145441873-258b4567-3a6f-45cf-a882-b545c111fbb3.gif) (Sorry if this is is considered malpractice or rude)

No problem, looks good. carry on

**Comment by LancelotHayward** [comment]
> What if you make it a little bit slower? That one looks good but still too quick, IMO.
![linkfree 787 slower](https://user-images.githubusercontent.com/82458069/145550608-d4b785a0-614a-446a-a7df-6707e72cf6af.gif)
Is this satisfactory?
