### ISSUE TITLE
[BUG] Negative ticket Price for an event 

### ISSUE THREAD

**Issue by Fly0w** [EddieHubCommunity/LinkFree#7871]
### Description

In the Create event form, it is possible to set up a negative ticket price, which shouldn't be possible.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/121224710/ee7b7127-3088-4e9e-8db0-7f267d02d280)

### Additional information

I can work on this.

**Comment by eddiejaoude** [comment]
Good spot, thank you for raising 👍

**Comment by Fly0w** [comment]
I would like to work on this issue please 👍

**Comment by SaraJaoude** [comment]
> I would like to work on this issue please 👍

@Fly0w I have assigned this to you

**Comment by EraKin575** [comment]
is this still open?

**Comment by SaraJaoude** [comment]
> is this still open?

@EraKin575 please refer to the conversation just above your comment or alternatively the `Assignee` box at the top of the page - this has been assigned to someone else.
