### ISSUE TITLE
[BUG] On profile page move tabs nav to top

### ISSUE THREAD

**Issue by ChinmayMhatre** [EddieHubCommunity/LinkFree#7875]
### Description

<img width="1333" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/51131670/40b2b9b5-a4f8-4165-a20d-1aecf3a0f017">
<img width="1333" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/51131670/59f1353c-4c6c-4a8f-9495-1efdfcbd61a1">

The tabs should always be in the same position

**Comment by eddiejaoude** [comment]
Good idea, my thoughts...

- Statistics page: move tab nav to the top
- Profile page: move alert to be under the tab nav

Then on all manage pages, the tab nav will be consistently at the same place at the top

**Comment by SaraJaoude** [comment]
> I can work on this issue, pls assign this issue to me.

@ZeeMonk-pixel I have assigned this to you.

**Comment by Meetcpatel** [comment]
Is this expected?

https://github.com/EddieHubCommunity/LinkFree/assets/26919832/84891664-f905-4eb4-a739-da5985d6f289

**Comment by eddiejaoude** [comment]
Looks good @Meetcpatel but the issue assigned to someone else - here we focus on collaboration not competition, please read our contributing guide, any questions let us know

PR for reference https://github.com/EddieHubCommunity/LinkFree/pull/7899

**Comment by Meetcpatel** [comment]
Oh Yes, Sorry for that

**Comment by ZeeMonk-pixel** [comment]
Yay!!! thank you. I'll start work on it now
