### ISSUE TITLE
[FEATURE] Bulk edit/delete links

### ISSUE THREAD

**Issue by loftwah** [EddieHubCommunity/LinkFree#7876]
### Description

I tested the delete feature and it works great. It gave me the idea that a user may want to be able to bulk edit/delete (whatever functionality works in bulk).

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/19922556/e4a67881-2bfb-4020-8462-69c12687d7fc)

If I could select and delete and even edit these links from here it would improve the user experience.

**Comment by eddiejaoude** [comment]
Bulk managing is a good and useful idea, but I think bulk editing would be very tricky. Bulk delete would be ok to do, however I think it is risky to make delete so easy - not sure if people would delete links that much anyway

I will close for now
