### ISSUE TITLE
[FEATURE] Import data from CSV

### ISSUE THREAD

**Issue by loftwah** [EddieHubCommunity/LinkFree#7877]
### Description

A great feature would be the ability to import from a CSV. It would enable users to manage their profile from Excel or Google Sheets etc, export as CSV and then import it into their LinkFree profile.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/19922556/92e04a1a-0f68-42df-b718-5a53f34962a3)

![image](https://github.com/EddieHubCommunity/LinkFree/assets/19922556/414b989b-972e-43e4-a91f-971d2addf26a)

![image](https://github.com/EddieHubCommunity/LinkFree/assets/19922556/c235ef9b-0f29-4dd4-988d-333a9879ba9c)

It could sit in either of these places.

**Comment by SaraJaoude** [comment]
Nice idea but we had a lot of challenges with managing the JSON and forms, so I don't think we want to introduce another input format at the moment - so I shall close this for now.
