### ISSUE TITLE
[DOCS] Make `C` to `c` in the word `Connects`

### ISSUE THREAD

**Issue by Kira272921** [EddieHubCommunity/LinkFree#788]
### Description

*If you have already forked the repository, skip to step 3*

1) Fork this [repository](https://github.com/EddieHubCommunity/LinkFree/fork)
2) Create a branch named `lowercase_c`
3) Open the [`README.md`](https://github.com/EddieHubCommunity/LinkFree/blob/main/README.md) file, make sure that you are opening the file in your fork
4) In line 2, replace the current content with the following content :
```
LinkFree connect audiences to all of your content with just one link. It is an open-source alternative to [Linktree](https://linktr.ee/) implemented in JavaScript.
```

### Additional information

This is a good first issue. Please leave this open to beginners and first-time contributors

**Comment by krishguptadev** [comment]
why is `C` supposed to be a cap? neither is it starting a sentence nor a proper noun

**Comment by Kira272921** [comment]
> why is `C` supposed to be a cap? neither is it starting a sentence nor a proper noun

🤔 I mentioned to make it lower case c

**Comment by krishguptadev** [comment]
> > why is `C` supposed to be a cap? neither is it starting a sentence nor a proper noun
> 
> 🤔 I have mentioned to make it lower case c

I thought that the code block you added was supposed to be edited 😅

**Comment by Kira272921** [comment]
> I thought that the code block you added was supposed to be edited 😅

It's the other way around 😄

**Comment by prahladjshenoy** [comment]
Please give feedback for PR. This is my first PR.

**Comment by Kira272921** [comment]
@prahladjshenoy Hey! I guess you haven't created a PR, but you have committed the changed to your fork 

Do these following steps to create a PR 😄 

- Open the `lowercase_c` branch in your fork
- You would see a button called `contribute`, click on that 
![image](https://user-images.githubusercontent.com/90365542/145359095-3d658fe7-d48c-4fc4-a359-6f95a4a8a799.png)

- Then fill in the details and create your first PR 🎉

**Comment by krishguptadev** [comment]
> @prahladjshenoy Hey! I guess you haven't created a PR, but you have committed the changed to your fork
> 
> Do these following steps to create a PR 😄
> 
> * Open the `lowercase_c` branch in your fork
> * You would see a button called `contribute`, click on that
>   ![image](https://user-images.githubusercontent.com/90365542/145359095-3d658fe7-d48c-4fc4-a359-6f95a4a8a799.png)
> * Then fill in the details and create your first PR 🎉

Wait there are 2 PRs already for this 😱

**Comment by Kira272921** [comment]
> Wait there are 2 PRs already for this 😱
😨 They could have could that they are working on this issue by commenting here
