### ISSUE TITLE
[BUG] Layout field's options are not visible in Dark theme

### ISSUE THREAD

**Issue by Ashish-simpleCoder** [EddieHubCommunity/LinkFree#7880]
### Description

When using the dark theme, In manage profile page, under the profile tab the Layout field's options are not visible. 

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/62009244/84344216-2f93-4276-928b-e172d7e11cbf)

**Comment by eddiejaoude** [comment]
Thank you for raising, but I can't not replicate, can you please recheck and share your OS and Browser

<img width="1099" alt="Screenshot 2023-07-01 at 09 26 50" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/b401f932-603c-473d-8a09-8b40ac201a4d">

**Comment by Ashish-simpleCoder** [comment]
It is windows 10 and browser is Chrome/Version 112.0.5615.50 (Official Build) (64-bit).
I think this issue is occuring only with my this device.
So i am closing this issue.
