### ISSUE TITLE
[FEATURE] Change the vertical Scrollbar ui

### ISSUE THREAD

**Issue by SubhamB2003** [EddieHubCommunity/LinkFree#7911]
### Description

Hey, I want to change the vertical scrollbar ui currently it was look like this 
![image](https://github.com/EddieHubCommunity/LinkFree/assets/94003231/cc22f45f-bd36-42ab-8f1a-9549fb3508eb)

after making changes it looks like this
![image](https://github.com/EddieHubCommunity/LinkFree/assets/94003231/bf7e8e1e-3a91-49fc-80a5-681fe21069f4)

**Comment by SaraJaoude** [comment]
I will close this issue as we cannot see how it adds value to the project, it will not work cross-browser and not good for accessibility.
