### ISSUE TITLE
[BUG] "GitHub Accelerator" and "GitHub Sponsors" buttons are not horizontally aligned - mobile devices

### ISSUE THREAD

**Issue by sandramsc** [EddieHubCommunity/LinkFree#7914]
### Description

The "GitHub Accelerator" and "GitHub Sponsors" buttons are not ("perfectly") horizontally aligned on mobile devices.

### Screenshots

![gacc](https://github.com/EddieHubCommunity/LinkFree/assets/19821445/6f91c245-1dc0-42e2-bfde-238303b60206)

**Comment by eddiejaoude** [comment]
Thanks for raising the issue 👍

**Comment by sandramsc** [comment]
Can I have this assigned to me, please✋?

**Comment by SaraJaoude** [comment]
> Can I have this assigned to me, please✋?

@sandramsc I have assigned this to you

**Comment by ChinmayMhatre** [comment]
Another issue related to github accelerator image https://github.com/EddieHubCommunity/LinkFree/issues/6658

**Comment by sandramsc** [comment]
> Another issue related to github accelerator image #6658

Eddie and discussed this on discord, it was decided this was a separate issue.

**Comment by Amar1432** [comment]
Hi @sandramsc, are you working on it?

**Comment by eddiejaoude** [comment]
> Hi @sandramsc, are you working on it?

@Amar1432 please read the comments directly above yours, also have a look at our contributing guide to learn more https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by eddiejaoude** [comment]
Closing as not achievable in a clean way and the process of the new design is starting next week with the agency
