### ISSUE TITLE
[BUG] Mobile UI alignment or sizing

### ISSUE THREAD

**Issue by loftwah** [EddieHubCommunity/LinkFree#7917]
### Description

When viewing LinkFree via mobile, the UI doesn't entirely take up the entire screen or isn't aligned to the centre.

### Screenshots

![Screenshot_20230702_134020_Chrome](https://github.com/EddieHubCommunity/LinkFree/assets/19922556/4cbd2c49-99d6-4eaa-be1c-6ff770fff72d)
![Screenshot_20230702_134025_Chrome](https://github.com/EddieHubCommunity/LinkFree/assets/19922556/7c1da53c-78bd-4033-bddb-2a138bb6e6af)
![Screenshot_20230702_134031_Chrome](https://github.com/EddieHubCommunity/LinkFree/assets/19922556/c9145747-a342-4e4b-9d82-04029451fa1f)

**Comment by eddiejaoude** [comment]
Oh wow thanks Dean!

**Comment by rajneesh-18** [comment]
Assign this issue to me.

**Comment by pushkaraj2007** [comment]
I would like to work on this issue, Can you please assign this to me?

**Comment by SaraJaoude** [comment]
> Assign this issue to me.

@rajneesh-18 I have assigned this to you.

**Comment by pushkaraj2007** [comment]
As @rajneesh-18 has removed his assignment.

Can you please assign this issue to me?

**Comment by SaraJaoude** [comment]
> As @rajneesh-18 has removed his assignment.
> 
> Can you please assign this issue to me?

@pushkaraj2007 I have assigned this to you

**Comment by pushkaraj2007** [comment]
> > As @rajneesh-18 has removed his assignment.
> > Can you please assign this issue to me?
> 
> @pushkaraj2007 I have assigned this to you

@SaraJaoude Thanks for assigning! I'll create a PR as soon as possible.

**Comment by pushkaraj2007** [comment]
Actually it's working fine on my end.

It's breaking only in screens less than ~300 viewport width.

I tried all the ways I can to make it the full screen but they didn't worked.

Here is the screenshot of Linkfree on my device:
![Screenshot_2023-07-12-21-50-56-524_com.android.chrome.jpg](https://github.com/EddieHubCommunity/LinkFree/assets/107422421/1bd234aa-79c7-43d9-8308-37166ba0d608)

**Comment by pushkaraj2007** [comment]
Hello,

I believe this problem only occurs on screens with a viewport width of less than ~300px.

I have attempted different approaches to resolve this issue, but I have been unable to find a solution.

**Comment by SaraJaoude** [comment]
> Hello,
> 
> I believe this problem only occurs on screens with a viewport width of less than ~300px.
> 
> I have attempted different approaches to resolve this issue, but I have been unable to find a solution.

@pushkaraj2007 if you have been unable to find a solution then I will unassign this from you for now

**Comment by ChinmayMhatre** [comment]
I just checked on my mobile device this seem to be fixed now. Can someone check once more?

**Comment by loftwah** [comment]
![image](https://github.com/EddieHubCommunity/LinkFree/assets/19922556/87b90e06-09e9-4812-81f7-733c8dd6935c)

You can recreate this problem within the Chrome dev-tools if you need.

**Comment by Tejasvp25** [comment]
I would like to work on this issue. I already have it fixed on my local machine. If assigned to me I'd be more than create pr.
![image](https://github.com/EddieHubCommunity/LinkFree/assets/66073053/86a0b9a7-9e4d-4452-8ad9-bf5d9c012ce7)

**Comment by SaraJaoude** [comment]
> I would like to pick this up.

@Tejasvp25 I will assign this to you

**Comment by eddiejaoude** [comment]
I can't replicate the bug, @loftwah could you test this PR? https://github.com/EddieHubCommunity/LinkFree/pull/8242

**Comment by Tejasvp25** [comment]
> I can't replicate the bug, @loftwah could you test this PR? #8242

The bug only occurs on screens with a viewport width <250-300px.

**Comment by eddiejaoude** [comment]
Thank you 👍

**Comment by Tejasvp25** [comment]
This issue seems to appear only on select devices. I've gone through the Tailwind docs i couldn't find any solution, Hence I've unassigned issue.

**Comment by hi-Kartik2004** [comment]
The issue seems to be with the mobile menu, as the mobile menu is overflown under the width of 300px.

## Screenshots proving the same
![image](https://github.com/EddieHubCommunity/LinkFree/assets/111000515/2a983c58-33e0-44e7-aead-ca06ca247f5b)

I would like to work on this issue if this issue is still open, seems like a simple one.

**Comment by SaraJaoude** [comment]
> I would like to work on this issue if this issue is still open, seems like a simple one.

@hi-Kartik2004 I have assigned this to you
