### ISSUE TITLE
[BUG] Quickstart-json page is not responsive

### ISSUE THREAD

**Issue by SubhamB2003** [EddieHubCommunity/LinkFree#7918]
### Description

Hey, https://linkfree.io/docs/quickstart-json this page is not properly responsive. You can check below

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/94003231/ce8fe1f4-e17f-49fb-ae63-5a39fe4c79ee)
![image](https://github.com/EddieHubCommunity/LinkFree/assets/94003231/cda32095-e647-4737-8aa1-83e13988ed16)

**Comment by eddiejaoude** [comment]
Thank you 👍  the images on other pages also have a similar bug

**Comment by SubhamB2003** [comment]
I want to work on it. Can you please assign it to me

**Comment by rajneesh-18** [comment]
Assign it to me. I'll work on it.

**Comment by SaraJaoude** [comment]
> Hey, I want to work on it. Can you please assign it to me

@SubhamB2003 I have assigned this to you.

**Comment by SaraJaoude** [comment]
@SubhamB2003 how are you getting on?

**Comment by SubhamB2003** [comment]
> @SubhamB2003 how are you getting on?

Hey, @SaraJaoude really sorry for the delay. Can you please tell me where I find this [Link](https://linkfree.io/docs/quickstart-json) file?
