### ISSUE TITLE
[DOCS] Fix commas

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/LinkFree#792]
### Description

*If you've already forked this repository, skip to step 3*

1. Fork the repository [here](https://github.com/EddieHubCommunity/LinkFree/fork).
2. Make a new branch named `missing_comma`.
3. Go to [`cypress/integration/search.feature`](https://github.com/EddieHubCommunity/LinkFree/blob/main/cypress/integration/search.feature) (remember to open that file in your fork!).
4. In line 21, replace the current content with the following content:

```feature
        Then I see "No users found, please try with another name." text in section "main"
```

5. Go to [`src/Components/Home/Users.js`](https://github.com/EddieHubCommunity/LinkFree/blob/main/src/Components/Home/Users.js) (remember to open that file in your fork!).
6. In line 51, replace the current content with the following content:

```javascript
            <Message severity="error" text="No users found, please try with another name." />
```

Now you should be ready to make your PR and get this fixed! 🚀

### Additional information

This is a good first issue. Please leave this open to beginners and first-time contributors. 🙂

**Comment by amm98d** [comment]
Hi, I would like to take this, if possible :)

**Comment by Panquesito7** [comment]
> Hi, I would like to take this, if possible :)

Sure, feel free to work on it! 😄
