### ISSUE TITLE
[FEATURE] Add an indicator when in reorder mode when managing testimonials

### ISSUE THREAD

**Issue by ChinmayMhatre** [EddieHubCommunity/LinkFree#7920]
### Description

Something like this
![](https://user-images.githubusercontent.com/51131670/250253097-b9a6fa7a-10e2-40d8-97c6-6119df614d21.png)

![](https://user-images.githubusercontent.com/624760/250265028-541fea2c-7fe8-480c-80b1-40b161901d47.png)
Can be added when reorder is clicked so that it is clear that users can rearrange the testimonials

**Comment by ArnabChatterjee20k** [comment]
Can I work on this issue?

**Comment by SaraJaoude** [comment]
> Can I work on this issue?

@ArnabChatterjee20k I have assigned this to you.
