### ISSUE TITLE
[BUG] testimonial username not visible in dark mode

### ISSUE THREAD

**Issue by ChinmayMhatre** [EddieHubCommunity/LinkFree#7921]
### Description

<img width="1333" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/51131670/9dd6c28f-19d7-4426-bd24-64c77cde0be9">
<img width="1333" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/51131670/bab96b49-4753-4aa1-8cce-f23f1da0e196">

**Comment by eddiejaoude** [comment]
Good spot 👍 I will fix now
