### ISSUE TITLE
[BUG] account tabs needs a darker colour when hovered

### ISSUE THREAD

**Issue by ChinmayMhatre** [EddieHubCommunity/LinkFree#7922]
### Description

<img width="1333" alt="Screenshot 2023-07-02 at 12 23 02 PM" src="https://github.com/EddieHubCommunity/LinkFree/assets/51131670/f9900419-f2f7-4018-8759-a73f7609222d">

**Comment by SaraJaoude** [comment]
Thanks for the suggestion @ChinmayMhatre but as we will be redesigning the website and this will be looked at then, I will close this issue for now.
