### ISSUE TITLE
[BUG] Text not appearing in the signup page

### ISSUE THREAD

**Issue by Bashamega** [EddieHubCommunity/LinkFree#7923]
### Description

Hello:)
I am new here, So I was signing up and I found that the layout dropdown option are white so I have to hover on them to make it appear.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/110662505/c1db41fe-7665-4aa9-8593-d902df3238fb)

**Comment by eddiejaoude** [comment]
This has been raised before but got closed. I still can't replicate the issue...

<img width="1502" alt="Screenshot 2023-07-03 at 09 50 02" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/3bd410ed-cf10-4a68-9ebb-2a7089569df7">
