### ISSUE TITLE
Redirect to list page after save

### ISSUE THREAD

**Issue by sumitunique777** [EddieHubCommunity/LinkFree#7929]
### What would you like to share?

When we add a new milestone or link or event or edit any of them I think it should redirect back to the listing of that particular tab e.g if we are editing a milestone  after updating it we should redirect back to the  milestones listing and so for another like events to events listing 

### Additional information

![image](https://github.com/EddieHubCommunity/LinkFree/assets/105304243/44df9308-f64c-4a88-be1b-ab42826d96e8)

---

EDIT

- [ ] link: after successful save on add/edit, redirect back to manage link list page with successful message
- [ ] event: after successful save on add/edit, redirect back to manage event list page with successful message
- [ ] milestone: after successful save on add/edit, redirect back to milestone link list page with successful message
- [ ] if error or not saved, do not redirect and display error message

**Comment by ManishBisht777** [comment]
I would like to take this up

**Comment by sumitunique777** [comment]
I can work on this issue if it is fine for you guys

**Comment by sumitunique777** [comment]
I am a newcomer here for the open source contribution.I am willing to take up this issue @eddiejaoude

**Comment by ChinmayMhatre** [comment]
@ManishBisht777 @sumitunique777 Please refrain from tagging the maintainers, creates additional notifications. Thank you.

**Comment by SaraJaoude** [comment]
> I would like to take this up

@ManishBisht777 as you were the first to request, I have assigned this issue to you.
