### ISSUE TITLE
[BUG] Profile UI Fix

### ISSUE THREAD

**Issue by ManishBisht777** [EddieHubCommunity/LinkFree#7940]
### Description

`account/manage/profile` is looking like this on mobile screen and dark mode 

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/89926834/fa493d85-3a82-41ae-b908-709080a03959)

**Comment by eddiejaoude** [comment]
Good spot 👍 It works on desktop fine, but on mobile it doesn't
