### ISSUE TITLE
[BUG] milestones tab ui is not consistent with others 

### ISSUE THREAD

**Issue by 1010nishant** [EddieHubCommunity/LinkFree#7945]
### Description

in milestones tab: there is no padding between add milestone button and alert.

### Screenshots

currently:
<img width="1393" alt="Screenshot 2023-07-03 at 4 47 20 PM" src="https://github.com/EddieHubCommunity/LinkFree/assets/88904952/960d59cb-5a73-45e9-865f-baf3451ea3e2">

it should be like event tab:
<img width="1380" alt="Screenshot 2023-07-03 at 4 47 29 PM" src="https://github.com/EddieHubCommunity/LinkFree/assets/88904952/c07e389c-2740-4cd9-9d14-be86fa4b8c03">

**Comment by eddiejaoude** [comment]
Thank you for raising the issue  👍

**Comment by ZeeMonk-pixel** [comment]
Hi. I can work on this issue. Please assign it to me

**Comment by eddiejaoude** [comment]
Sure, assigned to you @ZeeMonk-pixel

**Comment by ZeeMonk-pixel** [comment]
Thank you. I was looking at the picture for the events above, there's margin to the left and right of the alert, should I add that to the milestone or just give a margin top and bottom. Which of the frames below works? 1 or 2?
FRAME 1
![Screenshot 2023-07-04 034810](https://github.com/EddieHubCommunity/LinkFree/assets/110388816/edf6c41d-ff76-43cd-b2c1-01c3406dec74)
FRAME 2
![Screenshot 2023-07-04 034619](https://github.com/EddieHubCommunity/LinkFree/assets/110388816/9b1e8751-b566-4576-8cc0-6a7b90e5f251)

**Comment by eddiejaoude** [comment]
Good question 👍  We should be consistent, where do the existing margins come from and I would do the same

**Comment by ZeeMonk-pixel** [comment]
Great
