### ISSUE TITLE
Datetime issue on Edit Event

### ISSUE THREAD

**Issue by sumitunique777** [EddieHubCommunity/LinkFree#7948]
### Description

Start date time and End DateTime is empty on the edit 

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/105304243/52a7f309-e387-4a3f-92bd-e9906cabcd92)

**Comment by eddiejaoude** [comment]
Thank you for raising, I can't replicate 🤔 This is what I get when I go to edit an event...

<img width="1675" alt="Screenshot 2023-07-04 at 07 10 45" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/b0cc0c4b-7418-4ae3-adf4-d714fc7697ec">

**Comment by yoyoekta** [comment]
I guess this is so as it is supposed to be filled by the user itself.

**Comment by SaraJaoude** [comment]
As we cannot replicate this, I will close for now.  This can always be re-raised in the future if required.
