### ISSUE TITLE
Delete icon on the listing iteself

### ISSUE THREAD

**Issue by sumitunique777** [EddieHubCommunity/LinkFree#7949]
### Description

We can add the delete icon on the listing itself (milestones listing, events listing, or links listing) instead of navigating into a particular event or milestone, or link and then deleting it.

### Screenshots

<img width="960" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/105304243/7d64e16c-60c5-43de-8a03-22e453ef4375">

**Comment by SaraJaoude** [comment]
@sumitunique777 thank you for your suggestion. However as the type of information input for milestones, events and links is not such that the majority of users are looking to delete this on a daily or even weekly basis, we do not believe that this adds enough value to the project so we will close this for now.
