### ISSUE TITLE
[BUG] Missing pages

### ISSUE THREAD

**Issue by Olaleye-Blessing** [EddieHubCommunity/LinkFree#7952]
### Description

Some of the pages on the [docs page](https://linkfree.io/docs) are missing.

### Screenshots

![Screenshot (714)](https://github.com/EddieHubCommunity/LinkFree/assets/70102539/4c43d226-845b-4c29-9bbd-5d68232d06c1)

**Comment by eddiejaoude** [comment]
Thank you for raising the issue, I will fix now 👍
