### ISSUE TITLE
[BUG] Inputs Values

### ISSUE THREAD

**Issue by yassineatik** [EddieHubCommunity/LinkFree#7962]
### Description

when trying to create a Milestones or an Event , the form has input that actually have a default value , like the one below .
Instead , it should have placeholders .
I hope I can work on this issue and solve it .

### Screenshots

<img width="960" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/77692478/f335de92-f525-4703-921d-d42d62330a7f">

**Comment by SaraJaoude** [comment]
@yassineatik thank you for raising - I have assigned this to you.

**Comment by yassineatik** [comment]
Thanks for assigning this to me , I will start working on it .
However on the Assignees section , it still says "No one assigned"

**Comment by SaraJaoude** [comment]
> Thanks for assigning this to me , I will start working on it.
> However , the Assignees section still says "No one assigned"
> I wanted to post this comment and I accidentally closed the issue

@yassineatik this should now be assigned to you
