### ISSUE TITLE
Only "0" is displayed when there are no links added. 

### ISSUE THREAD

**Issue by MeenakshiKathiresan** [EddieHubCommunity/LinkFree#7968]
### Description

Just the number 0 is displayed - (indicating the number of links added without context). It may not be necessary. Please assign it to me and I can fix it. 

### Screenshots

<img width="1409" alt="Screenshot 2023-07-04 at 12 21 24 PM" src="https://github.com/EddieHubCommunity/LinkFree/assets/26730019/8f471bba-30f8-47b7-8529-d7994bdb9652">

**Comment by eddiejaoude** [comment]
Thank you for raising the issue 👍 I have assigned it to you @MeenakshiKathiresan
