### ISSUE TITLE
Description should be a textarea

### ISSUE THREAD

**Issue by sumitunique777** [EddieHubCommunity/LinkFree#7970]
### Description

We can change make the description as a text area on both the Milestone and Events form pages instead of a text box. Please assign it to me and I can fix it.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/105304243/c05cf730-6a22-4229-81fd-ea8b28b58f32)

**Comment by eddiejaoude** [comment]
Thanks @sumitunique777 I have assigned it to you. Could you also include the profile bio as a textarea - we have a textarea in another branch, but you can copy the code from there as that branch will not be merged for a while (and when it is ready to be merged we can use your new component and remove the duplication - I hope that makes sense)
https://github.com/EddieHubCommunity/LinkFree/pull/7915/files#diff-951cfe2227b457f773144c90185291698eabdee00f64d5e102f19cc6352f716a

**Comment by sumitunique777** [comment]
okay I will start working on it
