### ISSUE TITLE
[BUG] Mobile - "In the works" button UI alignment or sizing

### ISSUE THREAD

**Issue by sandramsc** [EddieHubCommunity/LinkFree#7971]
### Description

The heading text "In the works" appears squashed to the left by the size or alignment of the button to its right. The text within the button itself is not center aligned (which might look better). As a result the current top layout of this block does not complement the other two on the same page (**roadmap** on mobile).

### Screenshots

**Before:**
![before](https://github.com/EddieHubCommunity/LinkFree/assets/19821445/ab21c64b-ba52-415d-8b6e-218699af655f)
**Proposed change**
![after](https://github.com/EddieHubCommunity/LinkFree/assets/19821445/bfd10a08-b471-4d55-8d9f-44ec1c14571b)

**Comment by SaraJaoude** [comment]
@sandramsc thanks for spotting this.  It was a little difficult for us to replicate at first as your screenshots were very focused and didn't give context. We thought at first this referred to the smallest screen resolution (where this works ok) but it is in fact on the medium screen size. 

The text has also been updated to reflect that that some of the features have moved over from "Coming Soon" to "Recently Released".

<img width="1051" alt="Screenshot 2023-07-07 at 07 46 15" src="https://github.com/EddieHubCommunity/LinkFree/assets/82668196/2ec90cf8-adc3-429e-bdde-6cc1448316fc">

**Comment by bupd** [comment]
@SaraJaoude I am ready to work on this issue. Please assign it to me.

**Comment by sandramsc** [comment]
> @sandramsc thanks for spotting this. It was a little difficult for us to replicate at first as your screenshots were very focused and didn't give context. We thought at first this referred to the smallest screen resolution (where this works ok) but it is in fact on the medium screen size.
> 
> The text has also been updated to reflect that that some of the features have moved over from "Coming Soon" to "Recently Released".
> <img alt="Screenshot 2023-07-07 at 07 46 15" width="1051" src="https://user-images.githubusercontent.com/82668196/251660542-2ec90cf8-adc3-429e-bdde-6cc1448316fc.png">

Thanks Sara, happy to learn that there was an opportunity to give more context for future issues.

**Comment by eddiejaoude** [comment]
Great collaboration everyone 💪 

sorry @bupd I already fixed this as I updated the content for the page

**Comment by bupd** [comment]
That's fine. I am a front-end Developer and I am always looking for new challenges. If there are any upcoming issues that need some front-end work.
Please feel free to tag me. I am happy to help out in any way that I can.
