### ISSUE TITLE
[BUG] Options for layout field aren't visible.

### ISSUE THREAD

**Issue by DarshanDixit05** [EddieHubCommunity/LinkFree#7972]
### Description

While selecting layouts the options (classic and inline) available aren't visible due to bg color and text color. If it's a valid issue, please assign it to me I'll fix it in no time.

### Screenshots

<img width="948" alt="Screenshot 2023-07-05 030252" src="https://github.com/EddieHubCommunity/LinkFree/assets/76871537/945f900e-12e6-427f-a6ba-9e6a0dd97f75">

**Comment by eddiejaoude** [comment]
Thank you for raising, but I will close as this is a duplicate https://github.com/EddieHubCommunity/LinkFree/issues/7939
