### ISSUE TITLE
Different spacing found between "add event" and "no events"

### ISSUE THREAD

**Issue by DarshanDixit05** [EddieHubCommunity/LinkFree#7973]
### Description

I went through all the sections, and I found an unusual spacing in the "Events" section. While other sections have no spacing between "add" and "no" containers. If it's a valid issue, then please assign it to me I'll fix this.

### Screenshots

-> **In events section :**
<img width="947" alt="Screenshot 2023-07-05 030406" src="https://github.com/EddieHubCommunity/LinkFree/assets/76871537/69f5d6bb-f9a3-4b9c-97bc-a9b1d0178ba3">

-> **In other section**
<img width="953" alt="Screenshot 2023-07-05 030351" src="https://github.com/EddieHubCommunity/LinkFree/assets/76871537/3fc46241-81ed-4e23-942e-5cc8e1f4cbb9">

**Comment by eddiejaoude** [comment]
Thank you for raising, it is a valid issue but we should solve it as part of an existing issue https://github.com/EddieHubCommunity/LinkFree/issues/7945 - so I will close this
