### ISSUE TITLE
Hacktoberfest info on README.md

### ISSUE THREAD

**Issue by CodingSpecies** [EddieHubCommunity/LinkFree#798]
### What would you like to share?

I was wondering if it is neccessary to keep the hacktoberfest notice on the readme, right now, as it is not hacktoberfest until next year.
![image](https://user-images.githubusercontent.com/70807500/145680138-0bf2d637-e7ff-4469-a3b5-24f1ad678fa3.png)

Maybe, we could make it a dropdown, like this: 

<details close>
  <summary> Note for Hacktoberfest</summary>
  <br>

> A note for Hacktoberfest Participants:
>
> Pull requests which add or edit your information in a `public/data/${yourname}.json` file will NOT be counted for Hacktoberfest.
>
> Pull requests which improve the codebase, documentation, or other aspects of the project and are in line with the core values
> of the event will count - maintainers will opt-in these PRs by applying the `hacktoberfest-accepted` label.
  </details>

The code:

```
<details close>
  <summary> Note for Hacktoberfest</summary>
  <br>

> A note for Hacktoberfest Participants:
>
> Pull requests which add or edit your information in a `public/data/${yourname}.json` file will NOT be counted for Hacktoberfest.
>
> Pull requests which improve the codebase, documentation, or other aspects of the project and are in line with the core values
> of the event will count - maintainers will opt-in these PRs by applying the `hacktoberfest-accepted` label.
  </details>
```

### Additional information

I don't know is this is needed, but, this is an idea, for first time contributors.
Thank you.

**Comment by krishguptadev** [comment]
This looks like a good-first-issue, let's let first times contribute!

**Comment by arghyab0** [comment]
Hey, can I take this issue up ?

**Comment by krishguptadev** [comment]
> Hey, can I take this issue up ?

Sure!
