### ISSUE TITLE
[BUG] 404 page button doesn't look good in small screen

### ISSUE THREAD

**Issue by badrivlog** [EddieHubCommunity/LinkFree#7981]
### Description

In small screen 404 page button wrapped into two lines this doesn't look good. 

To address this issue, it is recommended to adjust the button design or the text content to ensure that the text fits within the width of the button without wrapping. This can be achieved by shortening the button text, changing the font size, or increasing the width of the button if possible. Alternatively, consider using icons or symbols alongside the text to convey the button's purpose in a more concise manner.

**Edit: button text to be shortened to `Home` and `Docs`**

### Screenshots

![IMG_20230705_120741](https://github.com/EddieHubCommunity/LinkFree/assets/73095526/0819b2af-4b08-4a04-bcb6-3fceea86dee3)

**Comment by SaraJaoude** [comment]
Good idea @badrivlog  - my thoughts are that the button text should be shortened to `Home` and `Docs` respectively. 

I will update the description of the Issue to reflect this.

**Comment by ArnabChatterjee20k** [comment]
Can I work on this?

**Comment by SaraJaoude** [comment]
> Can I work on this?

@ArnabChatterjee20k I will assign this to you.
