### ISSUE TITLE
[BUG]Alert components should start with capital letter

### ISSUE THREAD

**Issue by badrivlog** [EddieHubCommunity/LinkFree#7983]
### Description

The current codebase contains `alert` components that do not adhere to the proper capitalization convention. According to the coding standards and best practices, all component names should begin with a capital letter.

**Comment by eddiejaoude** [comment]
Good spot, thank you 👍

**Comment by badrivlog** [comment]
Hey Eddie, please review my pull request I submitted #7748 . I have done the work as you suggested.

**Comment by eddiejaoude** [comment]
> Hey Eddie, please review my pull request I submitted #7748 . I have done the work as you suggested.

Sure @badrivlog 👍 It is on my list of things to do, it might take me a couple of days as I am travelling (note: please don't comment about your PR that on issues that are unrelated as this creates extra noise and confusion)

**Comment by amanpreet-dev** [comment]
@eddiejaoude Can I be assigned to this issue?

**Comment by SagarBawanthade** [comment]
Please assign this issue to me

**Comment by khanalashim** [comment]
assign this to me

**Comment by SaraJaoude** [comment]
> Can I be assigned to this issue?

@amanpreet-dev as you were the first to request this I have assigned it to you.
