### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by FayasNoushad** [EddieHubCommunity/LinkFree#80]
Please create a group on telegram ( instant messaging application ).

**Comment by FayasNoushad** [comment]
telegram.org/apps
web.telegram.org

**Comment by rohan-kulkarni-25** [comment]
Hey @FayasNoushad , I don't exactly get what you are trying to say ! Can you please ellaborate

**Comment by FayasNoushad** [comment]
A support group needed in telegram like discord community.
