### ISSUE TITLE
[DOCS] Change the available Icon table structure.

### ISSUE THREAD

**Issue by Pradumnasaraf** [EddieHubCommunity/LinkFree#800]
### Description

In recent changes, the list of icons becomes too long as well as the README.

### Changes
- Have 3 columns instead of 2 column

### Screenshots

Before Changes:

![Screenshot from 2021-12-12 09-30-02](https://user-images.githubusercontent.com/51878265/145700055-6ebf29f0-2f07-4fa4-ae18-a38011cb5f9b.png)

After Changes:

![Screenshot from 2021-12-12 09-37-48](https://user-images.githubusercontent.com/51878265/145700090-15a83bef-b968-43df-b0f8-ff1b78b3bc74.png)

**Comment by Pradumnasaraf** [comment]
I will be working on this issue :)

**Comment by schmelto** [comment]
closed in #801
