### ISSUE TITLE
[FEATURE] Show Less Data use  pagination or use react-infinite-scroll-component package 

### ISSUE THREAD

**Issue by biplavmz** [EddieHubCommunity/LinkFree#8003]
### Description

Here we can show the limited data let's say 15-20 we can use pagination or use react-infinite-scroll-component package 

### Screenshots

<img width="893" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/68702055/b533cc80-545d-452f-91dc-a3e28775eb46">

**Comment by eddiejaoude** [comment]
Thank you for raising the issue. There is already an issue for search pagination already, so I will close this issue as it is a duplicate https://github.com/EddieHubCommunity/LinkFree/issues/7599
