### ISSUE TITLE
[BUG] UI Improvements in Form

### ISSUE THREAD

**Issue by yoyoekta** [EddieHubCommunity/LinkFree#8004]
### Description

There are some style mismatch which can be improved to maintain consistency.

### Screenshots

Such as :- 

![image](https://github.com/EddieHubCommunity/LinkFree/assets/92643605/05975c76-c574-4eb4-8387-9a978c30be1d)

![image](https://github.com/EddieHubCommunity/LinkFree/assets/92643605/32ee052f-d765-4b31-99bb-ca67e82a5bb7)

### Additional information

I would like to work on the same.

**Comment by SaraJaoude** [comment]
@yoyoekta thank you for raising - I have assigned this to you.
