### ISSUE TITLE
[BUG] <Profile does not exist error on windows localhost>

### ISSUE THREAD

**Issue by BDFL669** [EddieHubCommunity/LinkFree#8008]
### Description

I have installed the LinkFree repo on my local windows environment but it fails to load my profile even though I am currently able to view it on the official https://t.co/OqUKw4vpX7 site.

### Additional information

![image](https://github.com/EddieHubCommunity/LinkFree/assets/62002130/f0803ec9-d770-41c4-b776-6078c7c8124a)
![image](https://github.com/EddieHubCommunity/LinkFree/assets/62002130/bc5355c1-699c-4c03-9ce6-177f8140c2e5)
![image](https://github.com/EddieHubCommunity/LinkFree/assets/62002130/366c25f9-ce03-45b2-ab52-e03f6d29e419)

**Comment by eddiejaoude** [comment]
Thank you for raising the issue. In the docs for local development, it has a message at the top, to load the json data, you need to visit a url https://linkfree.io/docs/environments/local-development - so I will close for now

Please give this a try and let us know if you have any issues 

<img width="1664" alt="Screenshot 2023-07-06 at 18 51 21" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/574c05a8-7a47-45f4-a47c-ce98a379a9a6">

**Comment by BDFL669** [comment]
![Uploading image.png…]()

Hey still getting the same error after reloading the json files.

Sorry about the back and forth.

**Comment by eddiejaoude** [comment]
Your image didn't upload, I can't see it. It would be easier for us to help debug if we chat in EddieHub Discord, here it is creating extra notifications for the project. You can join our Discord here and we have a `help` channel http://discord.eddiehub.org

**Comment by BDFL669** [comment]
![image](https://github.com/EddieHubCommunity/LinkFree/assets/62002130/3850945f-80d2-4628-90da-b219278ba48c)

**Comment by eddiejaoude** [comment]
Great, all the data got loaded 👍 - share your error in Discord and we can debug it further. I am going to lock this issue as mentioned before this is not the place to debug your local environment - see you in the EddieHub Discord, link shared above
