### ISSUE TITLE
[BUG] colour of Delete button in delete link alert should be white in dark mode

### ISSUE THREAD

**Issue by 1010nishant** [EddieHubCommunity/LinkFree#8029]
### Description

When we delete a link, an alert pops up. It would be preferable if the delete button's color is white even in dark mode.

### Screenshots

alert now:
<img width="747" alt="Screenshot 2023-07-06 at 8 57 37 PM" src="https://github.com/EddieHubCommunity/LinkFree/assets/88904952/51541212-4bcd-4400-ba2e-bb7031389da6">

alert after change:
<img width="690" alt="Screenshot 2023-07-07 at 4 19 47 PM" src="https://github.com/EddieHubCommunity/LinkFree/assets/88904952/992e46da-9ab4-4cd8-8399-12da211d5f5f">

### Additional information

If you find it relevant, please assign it to me. I have already completed it in my local environment.

**Comment by kumarsonsoff3** [comment]
Good Spot @1010nishant, Thanks for raising the issue!! 👍 

I'll assign it to you! :)

**Comment by RajsekharPanda** [comment]
can I fix the bug ? it's my first ever contribution so I think this will be a good start or someone is doing it ?

**Comment by SaraJaoude** [comment]
> can I fix the bug ? it's my first ever contribution so I think this will be a good start or someone is doing it ?

@RajsekharPanda please read the conversation history - this has been assigned to someone else.  If you are looking for `good first issues` you can take a look at unassigned issues [here](https://github.com/EddieHubCommunity/LinkFree/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee+label%3A%22good+first+issue%22).
