### ISSUE TITLE
[DOCS] Available icons names are misleading

### ISSUE THREAD

**Issue by nathgoutam93** [EddieHubCommunity/LinkFree#805]
### Description

I found many users has their icon's key value first letter in uppercase, which causing a problem of not showing icons in milestone 

### Screenshots

![firefox_Twn30Smhuc](https://user-images.githubusercontent.com/91387097/145808204-e5df95f2-c86b-475b-9ec8-620d26e31b99.png)
before fixing the issue

![firefox_b2glkj4bC8](https://user-images.githubusercontent.com/91387097/145808194-84151c51-2af3-4b55-b7a6-dc3ab97a16b0.png)
after fixed

### Additional information

it can be solved either by converting icon value into lowercase on runtime or just by correcting the available icons name on ReadME

**Comment by krishguptadev** [comment]
I think we should update the readme

**Comment by nathgoutam93** [comment]
yup that would be easier way but if you want the issue fixed by code . i had already fixed the issue . so i can make a pull request
