### ISSUE TITLE
[FEATURE] Social Share Button improvement idea

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/LinkFree#8053]
### Description

currently the social share button is the QR-code button next to the profile picture.
<img width="459" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/30869493/3ebaf233-0052-4bbf-bd5c-ea74d4764430">

In my point of view it is missing lack of clarity due it is not only the QR code rather than a sharing the profile via link, qr code etc.

Therefore I would suggest to change the icon from QR code to a share icon. (maybe reposition the icon on the top right as well so that the profile itself looks clean).

**Comment by eddiejaoude** [comment]
Good idea 👍

**Comment by anirudhp26** [comment]
I would to work on this feature

**Comment by sital002** [comment]
can you assign this issue to me

**Comment by akkshitgupta** [comment]
Hey @schmelto, this is how the changes you suggested looks like. can you confirm if this is what you meant

![image](https://github.com/EddieHubCommunity/LinkFree/assets/96991785/ae6db1cf-1aed-40d0-8476-62c55699d562)

**Comment by SaraJaoude** [comment]
> I would like to work on this feature

@anirudhp26 as you were the first to request this, I have assigned this issue to you.

**Comment by anirudhp26** [comment]
@akkshitgupta Hey mate looks like you already implemented the feature, can I use your implemented changes ( code ) ? 
The changes are good and on par with the requirements so no edits would be necessary

**Comment by anirudhp26** [comment]
@SaraJaoude can this issue get reassigned to @akkshitgupta as he already completed the feature and the changes also looks great

**Comment by akkshitgupta** [comment]
@anirudhp26 You can pick my changes and I have no objection with that. Please confirm with maintainers first as in the contributing guidelines it is clearly mentioned that the code must not be taken from others.

**Comment by anirudhp26** [comment]
that's why I asked to get you assigned instead, I'll unassign myself

**Comment by akkshitgupta** [comment]
My apologies for all the problems. I will follow the guidelines strictly.
