### ISSUE TITLE
chore: remove AliMora83.json

### ISSUE THREAD

**Issue by AliMora83** [EddieHubCommunity/LinkFree#8054]
### Description

no longer needed due to new design

### Screenshots

<img width="1271" alt="Screenshot 2023-07-08 at 12 10 53" src="https://github.com/EddieHubCommunity/LinkFree/assets/56822813/87d239b9-873a-442d-87ec-34a4e15c7876">

**Comment by kumarsonsoff3** [comment]
Hey @AliMora83, You can delete your `json` by creating a PR on your own. Or **approve** this PR #8059 created by someone, so that we can merge it! 

Feel free to comment on #8059
