### ISSUE TITLE
[DOCS] Adding docs to remove JSON file if using forms

### ISSUE THREAD

**Issue by yoyoekta** [EddieHubCommunity/LinkFree#8057]
### Description

As per the new update, `.json` file is no more needed if one has switched to forms.

![image](https://github.com/EddieHubCommunity/LinkFree/assets/92643605/5639c616-af8f-44ba-ade2-752b9213ef8a)

So, docs can be updated with the steps to be followed to delete the `.json` file and folder(if any).

**Comment by eddiejaoude** [comment]
Good idea, thank you 👍

**Comment by yoyoekta** [comment]
Can I work on the same?

**Comment by eddiejaoude** [comment]
<img width="1271" alt="Screenshot 2023-07-11 at 14 03 53" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/b308cbba-ec63-4e92-b3ed-83ed0e86d01f">
