### ISSUE TITLE
Hide  link button on link form when no link is added

### ISSUE THREAD

**Issue by sumitunique777** [EddieHubCommunity/LinkFree#8061]
### Description

When there is no link added or edited, I think we don't need to show the link button on  the right side you can see the snapshots for reference, as when we click on the button it redirects us to on this URL 

https://linkfree.io/api/profiles/sumitunique777/links/undefined

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/105304243/032cd8ac-e25b-4dfc-935b-0d724a61ab93)
![image](https://github.com/EddieHubCommunity/LinkFree/assets/105304243/43f331ca-b3d3-48c2-9721-edc552308a65)

**Comment by eddiejaoude** [comment]
Thank you for raising 👍  But then we can only show the preview after a URL has been entered, but people will want to see how their link name is displayed before they add a url - I am not sure what the solution is, so for now I will close this issue  - hopefully they will realise if they event entered a link they can't click it to go to a link lol
