### ISSUE TITLE
Optimize spacing

### ISSUE THREAD

**Issue by vasnt** [EddieHubCommunity/LinkFree#8071]
### Description

spacing needs to be optimized to make it visually appealing. lot of space remains after text.

### Screenshots

<img width="864" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/117589240/e931bb12-8047-41bf-9d9f-53a10c4fc6bb">

**Comment by eddiejaoude** [comment]
Thank you for raising the issue. But as no solution is proposed, I will close this issue.

**Comment by vasnt** [comment]
solution should be proposed by issue raiser, only?
