### ISSUE TITLE
[BUG] Broken Link in Testimonial GitHub Action

### ISSUE THREAD

**Issue by verma-kunal** [EddieHubCommunity/LinkFree#8074]
### Description

The link to the testimonial guide in the github action leads to an incorrect page! I believe the the correct link to the guide is: https://linkfree.io/docs/how-to-guides/testimonials-json

### Screenshots

![Screenshot 2023-07-09 at 1 09 41 PM](https://github.com/EddieHubCommunity/LinkFree/assets/72245772/adcf3c74-12e5-4140-a8fc-d4babd49a7cf)

![image](https://github.com/EddieHubCommunity/LinkFree/assets/72245772/54d67022-2936-42ab-b317-c214868bf256)

**Comment by eddiejaoude** [comment]
Good spot, thank you 👍

**Comment by sital002** [comment]
can u assign this to me

**Comment by sumitunique777** [comment]
I would like to take up this issue

**Comment by AlimurtuzaCodes** [comment]
I can fix this issue.

**Comment by SaraJaoude** [comment]
> I would like to take up this issue

@sumitunique777 you already have an issue assigned to you.  In accordance with our [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) we only assign one issue per person.

**Comment by SaraJaoude** [comment]
> I can fix this issue.

@AlimurtuzaCodes I have assigned this to you.
