### ISSUE TITLE
[BUG] : Github accelerator image overflows on mobile screen

### ISSUE THREAD

**Issue by abhiraj-ku** [EddieHubCommunity/LinkFree#8080]
### Description

While browsing the link-free site on mobile the GitHub accelerator image banner overflows from the screen.

### Screenshots

This is before 
![linkfree prob](https://github.com/EddieHubCommunity/LinkFree/assets/113116498/ad17cf9e-976a-4650-86a8-fd4f581c78a7)

this is after I applied object-fit: contain on this image so that it contains within the specified width
![linkfree sol](https://github.com/EddieHubCommunity/LinkFree/assets/113116498/6deb3758-3ff0-403f-b6ec-2ba5a7344c19)

**Comment by amandamartin-dev** [comment]
Confirmed. Able to recreate. I will open this issue up

**Comment by Durrani123** [comment]
Can you please assign this to me?

**Comment by SaraJaoude** [comment]
> Can you please assign this to me?

@Durrani123 I have assigned this to you.
