### ISSUE TITLE
[BUG] Events are not displayed in date ascending order

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#8089]
### Description

Events page should show the next event, currently they seem to be random

<img width="1284" alt="Screenshot 2023-07-09 at 18 14 47" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/343bf8c6-e80b-4101-8448-2c574957ee18">

**Comment by dan-mba** [comment]
This might be caused because the sort operation is not he last stage of the aggregation pipeline.

https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/api/events.js#L18-L37

**Comment by eddiejaoude** [comment]
> This might be caused because the sort operation is not he last stage of the aggregation pipeline.
> 
> https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/api/events.js#L18-L37

oh good spot 👍

**Comment by tanbirali** [comment]
Can you please assign this to me?

**Comment by SaraJaoude** [comment]
> Can you please assign this to me?

@tanbirali I have assigned this to you.

**Comment by DhirajGilda** [comment]
@tanbirali  just out of curiosity how are u getting the events in your local environment

**Comment by Sahilll15** [comment]
I am working on this one..

**Comment by Sahilll15** [comment]
can you assign this to me??

**Comment by accodes21** [comment]
@Sahilll15 As you can see this issue was already assigned to someone who has raised a PR for it. You can work on other issues.

**Comment by dan-mba** [comment]
Fixed by #8158
