### ISSUE TITLE
[FEATURE] Remove Json file automatically on forms save

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#8090]
### Description

Currently when a profile creator switches to forms, they have to manually create a PR to remove their json file.  This is time consuming for the user and maintainers.  Reccomending automatic deletion of json profile file (when they exist) on successful form save event.

If implemented, in this issue (or a separate one) a warnign or modal should be shown to a new forms user on first save event letting them know that their json will be deleted and having them confirm that they are sure they want to swap to forms.

**Comment by eddiejaoude** [comment]
I think this would be a lot of work, unless I am missing something? The flow would be something like..

1. user saves form and writes to db
2. this would need to trigger a GitHub Action to remove the file and make a commit

Another option, would be to have them raise an issue, similar to testimonials and it would delete their file based on their username

**Comment by amandamartin-dev** [comment]
I was thinking to avoid having to rely on the forms users to remember to create any issue related to this/decrease number of deletion PR's

But, yes - if the workload is not worth it, can close.  Definitely not a need to have feature and I would assume over time there will be less and less deletion PR's as most will likely use forms.

**Comment by eddiejaoude** [comment]
yep I think the need will reduce over time also
