### ISSUE TITLE
[IMPROVEMENT] mentioning search supports location search

### ISSUE THREAD

**Issue by akash19coder** [EddieHubCommunity/LinkFree#8118]
### What would you like to share?

Since the Search bar allows us to search users based on their location we should update the placeholder to mention it for the sake of user information so that search using locations

### Additional information

<img width="1349" alt="searchbar" src="https://github.com/EddieHubCommunity/LinkFree/assets/72060440/ddc92ac0-f1e9-4ba9-bfde-090f0e3a517f">

**Comment by devraj4522** [comment]
Can I take this Issue?

Will it be fine if we say: 
Search user by name, tags or places; eg: open source, reactjs

**Comment by akash19coder** [comment]
How about it - `Search by name, tags; eg: open source, reactjs or places: eg; london, new york`

**Comment by devraj4522** [comment]
Yes, seems good. Can it be assigned to me?

**Comment by SaraJaoude** [comment]
@devraj4522 I have assigned this to you
