### ISSUE TITLE
[OTHER] Rename docker-compose.yml to compose.yml

### ISSUE THREAD

**Issue by loftwah** [EddieHubCommunity/LinkFree#8122]
### What would you like to share?

Docker Compose (and compatible) will accept `compose.yml` by default for the filename. We should rename ours to be less vendor specific.

**Comment by dan-mba** [comment]
Do you have any info on when this feature was added?

I searched the docs for Docker & found this mention of the [new default](https://docs.docker.com/compose/compose-file/03-compose-file/).
But other areas of the docs still mention `docker-compose.yml`.

I think if we could find a version number of compose that added this feature and it has been GA for over 3 months, this change would make sense.

**Comment by loftwah** [comment]
I found out about it around the same time as it started supporting `docker compose` as well as `docker-compose` and that `docker compose` was the preferred method. I started using it and have been using it since. You will come by some repos that are using `Containerfile` instead of `Dockerfile` too.

**Comment by loftwah** [comment]
I assume it is the right way to progress but I could be wrong.

**Comment by GaryHilares** [comment]
Hello. My name is Gary. I would like to work in this issue. Would you mind assigning it to me?
