### ISSUE TITLE
[FEATURE] Community resources to array

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#8125]
### Description

Community resource page https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/docs/community-resources.mdx

- instead of changing markdown, best to have an array of objects
- then loop over these to display them
- display in descending order (newest at the top)

CONTRIBUTOR                                                   | CONTRIBUTION               | DATE (YYYY/MM/DD) | RESOURCE LINK (PR, Blog, Video)     
```js
[
   {
      name: "Eddie Jaoude",
      username: "eddiejaoude",
      contribution: "Blog on getting started",
      date: "2022-01-01",
      resource: "http:// ...",
   }
]
```

**Comment by rizahmeds** [comment]
Please provide more context(code link/screenshot) to this issue.

**Comment by sital002** [comment]
I would like to work on this issue. Can you assign this to me.

**Comment by SaraJaoude** [comment]
> I would like to work on this issue. Can you assign this to me.

@sital002 I have assigned this to you
