### ISSUE TITLE
[BUG] Duplicate select form element

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#8147]
### Description

These 2 components should be combined into 1

- `components/form/DropDown.js`
- `components/form/Select.js`

**Comment by Snach13** [comment]
I check the code they are pretty similar and doesnt depend on each other so when we combined 2 components what will be the name of newly created component any suggestions ?

**Comment by Snach13** [comment]
Also help me to understand were this code is affecting in website so i can check the behaviour of the code when we combined this 2 component

**Comment by ChinmayMhatre** [comment]
> Also help me to understand were this code is affecting in website so i can check the behaviour of the code when we combined this 2 component

You can do a search in VScode to check this

**Comment by Snach13** [comment]
I found the code and I'm making the necessary changes but were that code is affecting in the website how can i check that i want to check the behavior of the code

**Comment by SaraJaoude** [comment]
@Snach13 do you want this issue assigned to you? Please familiarise yourself with this project's [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) before - as you mention - "making the necessary changes".

**Comment by eddiejaoude** [comment]
> 1. were combining 2 component did u have any suggestion for whats the name of new component
> 2. another one is I dont get were that component is using in website so need help regarding that so i can see the changes that i
>    made in my local environment but i coulnt fine were this code used in website were it is appearing is it some kind of sign up section or anything like that or something different forms

@Snach13 here are my thoughts to your questions

1. We can call it `Select`
2. Here are the 2 search results for each component (please also update the standard html `select` also to use the new `Select` component)...

<img width="687" alt="Screenshot 2023-07-13 at 07 32 57" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/207ee2ef-3ec4-4594-8eb1-c2b529e04574">

<img width="684" alt="Screenshot 2023-07-13 at 07 33 08" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/8f720b9b-84f0-4ea8-9500-267ba0857ba1">

**Comment by ChinmayMhatre** [comment]
@Snach13 do you wish to be assigned to this issue?

**Comment by mianakbarjan** [comment]
Hi, please assign this issue to me so that I can start working on it.

**Comment by ChinmayMhatre** [comment]
@Snach13 Assigned you the issue

**Comment by Snach13** [comment]
@ChinmayMhatre I'm working on another issue if anybody wants to contribute to this assign it to them otherwise I'll work on it after my current Issues being resolve

**Comment by ChinmayMhatre** [comment]
> @ChinmayMhatre I'm working on another issue if anybody wants to contribute to this assign it to them otherwise I'll work on it after my current Issues being resolve 

Okay I'll be unassigning you from this issue

**Comment by mianakbarjan** [comment]
I'd love to work on this issue if it hasn't been assigned to anyone else yet.

**Comment by Manav-016** [comment]
@ChinmayMhatre I would like to work on this issue, if it is possible then can you kindly assign this to me??

**Comment by SaraJaoude** [comment]
> I'd love to work on this issue if it hasn't been assigned to anyone else yet.

@mianakbarjan I have assigned this to you.
