### ISSUE TITLE
[BUG] Docs side nav needs to have a select/dropdown for mobile

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#8168]
### Description

Currently the side nav is hidden for mobile and there is limited horizontal space. There needs to be a select/dropdown added for mobile on the docs pages

**Comment by IxBahy** [comment]
I can work on it

**Comment by eddiejaoude** [comment]
We don't need 2 drop downs 👍 

When the side nav is hidden due to the screen size being small, the existing `Select` component should be shown with a list of doc pages at the top of the page

Sure I will assign it to you @IxBahy
