### ISSUE TITLE
[BUG] Profile Card Hover in Dark Mode should have orange border

### ISSUE THREAD

**Issue by adarshmalviya12** [EddieHubCommunity/LinkFree#8176]
### Description

**Description:**
When the user is in dark mode and hovers over the profile card, the expected behaviour is for the card to display an orange border similar to search bar

**Steps to Reproduce:**
1. Enable dark mode in the application.
2. Navigate to a page where the profile card is displayed.
3. Hover over the profile card.

https://github.com/EddieHubCommunity/LinkFree/assets/96465597/402266c2-b87b-480b-aa87-2ccf20847454

**Comment by eddiejaoude** [comment]
Great suggestion 👍 I have assigned it to you

**Comment by faizi-7** [comment]
Where can i solve issue, i am new to open source

**Comment by faizi-7** [comment]
Please assign it to me

**Comment by SaraJaoude** [comment]
@faizi-7 before requesting that an issue be assigned to you please check the conversation and/or the Assignees box that can be found at the top of the page. As you can see this Issue has been assigned to someone else.  

I would suggest that you read this project's [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) first.

**Comment by alok197** [comment]
Hey, is this issue fixed or not ? 
Can i try to fix it ?

**Comment by AryanChopraa** [comment]
hey i want to work on this issue can you assign it to me !

**Comment by eddiejaoude** [comment]
@AryanChopraa please see the reply directly above yours 😉
