### ISSUE TITLE
[FEATURE] Delete item redirects to list page

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#8185]
### Description

Recent changes to update link/milestone/events now redirects to the manage list page, we should do the same for when deleting 

Note: message needs to be more custom "successfully updated" or "successful deleted"

See merged PR https://github.com/EddieHubCommunity/LinkFree/pull/7966

**Comment by sajdakabir** [comment]
Hey, @eddiejaoude I would like to work on this issue. can you assign it to me?

**Comment by MeenuyD** [comment]
I would like to work on this issue can you please assign it to me

**Comment by Sahilll15** [comment]
Hey,please assign this to me!!!

**Comment by SaraJaoude** [comment]
> Hey, eddiejaoude I would like to work on this issue. can you assign it to me?

@sajdakabir I have assigned this to you. In future please avoid tagging a specific maintainer - all maintainers receive notifications and can assign issues.

**Comment by MeenuyD** [comment]
Hello anyone working on this issue

**Comment by SaraJaoude** [comment]
> Hello anyone working on this issue

@MeenuyD in future before asking in the comments please check the top right of the page which shows whether an issue has been assigned.  In this case this issue has been assigned to a contributor. You may wish to take a look at this project's [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md).

**Comment by SaraJaoude** [comment]
> > Hey, eddiejaoude I would like to work on this issue. can you assign it to me?
> 
> @sajdakabir I have assigned this to you. In future please avoid tagging a specific maintainer - all maintainers receive notifications and can assign issues.

@sajdakabir how are you getting on?

**Comment by SaraJaoude** [comment]
Due to lack of activity I have unassigned this from you @sajdakabir

**Comment by babblebey** [comment]
Hi Sara, new here.. I see you just unassigned a contributor, kindly assign me if you may. I can patch a fix for this quickly as my first contribution.

Thank you.

**Comment by SaraJaoude** [comment]
> Hi Sara, new here.. I see you just unassigned a contributor, kindly assign me if you may. I can patch a fix for this quickly as my first contribution.
> 
> Thank you.

@babblebey thank you for your enthusiasm.  As mentioned, I cannot assign this one to you at this time as you already have an issue assigned to you. I have sent you a link to our Contributing Guide but let me know if you have any questions.  In future, it would be best not to request to be assigned to multiple issues (in the expectation of being assigned one) as this does add to maintainers' notifications and we will have to keep repeating the same message.  It would be preferable if you ask for one issue, if this is not assigned to you then move on to the next.

**Comment by mianakbarjan** [comment]
Hi, I'd like to work on this issue. Please assign it to me so I can start working on it asap. 
P.S. It might look like I've already been assigned an issue, but I've worked on that, and it has already been merged.
