### ISSUE TITLE
[FEATURE]: Integrate React-Icons with the project

### ISSUE THREAD

**Issue by Vyvy-vi** [EddieHubCommunity/LinkFree#819]
### Description

There's been a long delay in the choice of icon package used, and this can be mitigated by choosing something like react-icons, which makes it easier to swap through different icon packs, without needing to change the supporting library used.

What does success look like?:
- [ ] Having react-icons included amongst the packages installed on running `npm install`
- [ ] Replacement of primereact icons (or integrating those with react-icons, if possible), wherever we're using them.
- [ ] Adding support for the social link types that don't have any icons at the moment.

### Screenshots

NA

### Additional information

This issue is related to #242 and #417

**Comment by Tejas-Teju** [comment]
I can work on this once I finish [feature-616](https://github.com/EddieHubCommunity/LinkFree/issues/616)

**Comment by Rupesh-1302** [comment]
I would like to work on this issue

**Comment by Rupesh-1302** [comment]
What icon should i use if the icon is not on the valid list (Default Icon)

**Comment by Rupesh-1302** [comment]
Which icon should I use if the icon is not on the valid list (Default Icon)
