### ISSUE TITLE
[BUG] <Console log of properties on clicking of user card>

### ISSUE THREAD

**Issue by accodes21** [EddieHubCommunity/LinkFree#8193]
### Description

On clicking any user card, a set of properties is being console logged which is not required.
In my opinion, such console logs should be removed if deemed unnecessary.

### Screenshots

https://github.com/EddieHubCommunity/LinkFree/assets/101868279/abc4664a-d0d0-46f3-bb88-4d1df16b28ee

**Comment by dan-mba** [comment]
A `console.log` was left in the [UserPage](https://github.com/EddieHubCommunity/LinkFree/blob/main/components/user/UserPage.js#L9) component.

**Comment by Dobariya-Nishant** [comment]
i want to work in this issue.
