### ISSUE TITLE
[BUG] Improve Styling on Map

### ISSUE THREAD

**Issue by kumarankit999** [EddieHubCommunity/LinkFree#8194]
### Description

The Clear/ Reset and the Notification of it has been clashed, Which looks to be very bad.

Add some Margin & Padding on the box and the notification popup both.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/111564362/7b4b6da2-3ba1-4f34-a1d2-dd17e45a36c6)

**Comment by amandamartin-dev** [comment]
Able to recreate, will unlock

**Comment by akshajb** [comment]
Hey, I would like to pick this up.

**Comment by Snach13** [comment]
@kumarankit999 what about this behviour ? is it okay 

![Linkfree](https://github.com/EddieHubCommunity/LinkFree/assets/97365258/ed7b716e-e3cc-4510-92fb-0c8321cc604f)

**Comment by akshajb** [comment]
Is this the desired UI that we are going after?

<img width="349" alt="Screenshot 2023-07-17 at 10 55 13 PM" src="https://github.com/EddieHubCommunity/LinkFree/assets/19529446/f00bb396-2816-4920-931b-b45f1d0bc1e8">

**Comment by SaraJaoude** [comment]
> Is this the desired UI that we are going after?
> 
> <img alt="Screenshot 2023-07-17 at 10 55 13 PM" width="349" src="https://user-images.githubusercontent.com/19529446/254021053-f00bb396-2816-4920-931b-b45f1d0bc1e8.png">

@akshajb looks good but please check that the badge looks good in other places it is used.

**Comment by akshajb** [comment]
@SaraJaoude I will do that. However this current implementation does not affect the `Badge` component or the `Button` component, It is specific to the place where the above `Clear/ Reset Filters` button is used.
