### ISSUE TITLE
[BUG] Milestone, Events and Links section needs some margin top

### ISSUE THREAD

**Issue by sital002** [EddieHubCommunity/LinkFree#8210]
### Description

Steps to reproduce : 
In Dark Mode Go to account section and click on events and milestone section on mobile view 
The No Event found message is missing some margin. I will attach some of the images below.
I would like to work on this issue this is a simple fix. Can you assign rhis to me.

- milestone
- events
- links

### Screenshots

![Screenshot_20230715-211223_Chrome](https://github.com/EddieHubCommunity/LinkFree/assets/93700622/70f795d8-5d8d-453a-a46f-f800e726fe7a)
![Screenshot_20230715-211229_Chrome](https://github.com/EddieHubCommunity/LinkFree/assets/93700622/2e3df6f9-945b-4f32-a4c5-35f7ce3ee86d)

**Comment by SaraJaoude** [comment]
Thank you for raising.  A few comments:

1. This will also apply to light mode and desktop view (not just dark mode and mobile). 
2. I see you have already raised a PR for this: https://github.com/EddieHubCommunity/LinkFree/pull/8212 As mentioned to you previously please do not work on an Issue and raise a PR until the Issue has been marked `status: ready for dev` and assigned to you. I am including a link to the [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) again which I would encourage you to read through.

**Comment by sital002** [comment]
i will keep that in mind next time can you look into my pr

**Comment by vishalsingh2972** [comment]
@SaraJaoude can you assign this to me!

**Comment by sital002** [comment]
@vishalsingh2972 i have already sent the pr and never mention any maintainers.

**Comment by Snach13** [comment]
@sital002  did your PR get merge I'm seeing that nobody is assigned this issue to you and you created PR directly

**Comment by sital002** [comment]
@Snach13 its under review but the pr solves this issue

**Comment by sital002** [comment]
thanks for assingning this issue to me I know I did sent the pr  without being assigned this won't happen again.
