### ISSUE TITLE
[DOCS] there is a small typo error in docs local-development page

### ISSUE THREAD

**Issue by sital002** [EddieHubCommunity/LinkFree#8213]
### Description

There is a small typo error in docs local development page for  installing dependencies the code should be npm i or npm install but there is npm ci.
The docs page link :  https://linkfree.io/docs/environments/local-development

I will attach the images below .
can you assign this to me this is just a small fix. I am new to open source contributions.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/93700622/e861c094-a45c-4b09-bc6c-d5cb88f8fc00)

**Comment by eddiejaoude** [comment]
Thank you for raising the issue, but `npm i` or `npm install` is incorrect way to get the dependencies to run the project

`npm ci` is the correct way to run any node project, this will use the lock file and not update it - you can learn more about why in my video about it https://www.youtube.com/watch?v=jHkIXYVpMTo

**Comment by sital002** [comment]
ooh i didnot know that thanks.
