### ISSUE TITLE
[FEATURE] Add tags to user cards on search page

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#8217]
### Description

From a conversation in Discord...

Searching by tag often produces confusion in the results as the tags are not visible in the cards.  This creates the perception that the search may be functioning incorrectly.

Solution:
Add tags to the profile cards

**Comment by eddiejaoude** [comment]
> @eddiejaoude I'm working on this now and what I want to do potentially is create a new Tag component that isn't a button and is styled smaller. Wdyt about this approach? Something like TagStatic, TagSimple, TagReadOnly ?? whatever makes the most sense for naming...
> 
> My issue with the current Tag component is that it is a button so even if I don't pass an onClick parameter, it still "acts" like a button in the UI and is confusing. I also need to massage the styling a bit to better utilize the UserCard space.
> 
> Let me know your thoughts of if you prefer a different approach

Thank you Amanda 👍 Yes sure that makes sense
