### ISSUE TITLE
Searching by Community or Personal profile 

### ISSUE THREAD

**Issue by JKirito** [EddieHubCommunity/LinkFree#822]
### Description

I think we can improve search function without changing much of the Search bar UI, we can use something like type:community|personal, just like github search functionality __is:open__, etc... .Also, to make the search work either we have to make two seperate folders for containing personal profiles and other with community profile __OR__ we can decide to have a better naming syntax for the json data files like community profiles starting with __comm-username.json__ or any other suggested by the community.

**Comment by Vyvy-vi** [comment]
that would be great, and maybe we can combine the functionality with the discussion on tags: https://github.com/EddieHubCommunity/LinkFree/issues/802#issuecomment-995477598

**Comment by JKirito** [comment]
yes, also i just realised that the user data filtering is done from a file list.json, we can change it to include __type__ and then the changes can be done on searching part for filtering by type

**Comment by Cahllagerfeld** [comment]
I like this idea!!
