### ISSUE TITLE
[Hover on github links] <change it to text-primary>

### ISSUE THREAD

**Issue by Sahilll15** [EddieHubCommunity/LinkFree#8234]
### Description

I think the links will look better with text-primary as the whole website looks good with it

### Screenshots

![Screenshot 2023-07-17 at 10 57 30 PM](https://github.com/EddieHubCommunity/LinkFree/assets/109215419/dfb0e12e-07ac-45ef-9e8f-f943752821f8)

it can look like
<img width="169" alt="Screenshot 2023-07-16 at 11 56 14 PM" src="https://github.com/EddieHubCommunity/LinkFree/assets/109215419/9e5a3352-2735-4686-8f37-847791f1f075">

**Comment by eddiejaoude** [comment]
Not sure I understand. The colours need to match the rest of the app. I will close this as we are rebranding and design the whole site at the moment, so this will all change soon
