### ISSUE TITLE
[FEATURE]: Documentation menu for smaller devices

### ISSUE THREAD

**Issue by ashrafchowdury** [EddieHubCommunity/LinkFree#8245]
### Description

Currently, the **documentation is not optimized for smaller devices**. This makes it difficult to navigate, especially when you're trying to find a specific topic. 

To improve the user experience, we have to **add a dedicated documentation menu for smaller devices**. This will make it easier to find the information we need, no matter what device you're using.

### Screenshots

https://github.com/EddieHubCommunity/LinkFree/assets/87828904/4514897a-a4f4-4813-8a57-15f2e59a7785

**Comment by eddiejaoude** [comment]
Thank you for raising the issue and the great example 👍 

But there is already an issue for this, so I will close https://github.com/EddieHubCommunity/LinkFree/issues/8168
