### ISSUE TITLE
[BUG] Text content overflow in UserCard

### ISSUE THREAD

**Issue by bikrantjajware** [EddieHubCommunity/LinkFree#8248]
### Description

 When user bio contains a long word (without spaces). The bio text will overflow outside the UserCard width.
 Attached screenshot of my profile card after updating my bio with long no spaced "zzz..."  as bio.

 Possibly a simple css rule could solve the bug `word-break: break-all`

### Screenshots

![](https://cdn.discordapp.com/attachments/946056449375744110/1130836630459121684/image.png)

**Comment by eddiejaoude** [comment]
Thank for raising the issue 👍 

> Hello, do you have an example of this with a word that would be this long? I see what you mean, but cannot think of a realistic profile case in which this would happen.

Good point, I will close for now 👍
