### ISSUE TITLE
[BUG] Difficult-to-see horizontal line at top of doc page in light mode

### ISSUE THREAD

**Issue by ahtesham007** [EddieHubCommunity/LinkFree#8249]
### Description

The horizontal line at the top of a doc page is very faint and difficult to see when viewing the page in light mode. This makes it difficult to distinguish.

**Expected behavior:**

The horizontal line at the top of the page should be clearly visible in light mode.

**Actual behavior:**

The horizontal line at the top of the page is very faint and difficult to see in light mode.

### Screenshots

<img width="946" alt="l-mode" src="https://github.com/EddieHubCommunity/LinkFree/assets/42631795/81e64c78-9433-4cbd-bfda-f54c5d085796">
<img width="949" alt="d-mode" src="https://github.com/EddieHubCommunity/LinkFree/assets/42631795/299654a0-ae43-4650-8bad-8835d5efb455">

**Comment by amandamartin-dev** [comment]
The border right now is set to transparent, I believe this was a choice so I will let others weigh in first before unlocking. Thanks for your contribution and discussion!

**Comment by eddiejaoude** [comment]
Thanks for raising the issue 👍 this will change as part of the redesign that will happen very soon. So I will close for now
