### ISSUE TITLE
Github accelerator button <Is not visible in light mode>

### ISSUE THREAD

**Issue by ManashAnand** [EddieHubCommunity/LinkFree#8261]
### Description

![Screenshot (2)](https://github.com/EddieHubCommunity/LinkFree/assets/91553087/61ff0819-7bc5-4f20-8210-4b2554c94084)
In dark mode the github accelerator button with it's adjacent button have a small hover effect that looks quite good.
But when we see it in light mode
![Screenshot (1)](https://github.com/EddieHubCommunity/LinkFree/assets/91553087/a3c43c46-9d0b-443d-93f7-8c6e0181f3cc)
The effect is resolved with the previous screen making visual confusion as it's a image along github accelerator.

We should use a little vibrant color to make it more visible.

I would like to work on this issue if it's get verified .
Thanks.

### Screenshots

![Screenshot (2)](https://github.com/EddieHubCommunity/LinkFree/assets/91553087/7817c96e-2fbb-47eb-ae8b-cae737dd26ea)
![Screenshot (1)](https://github.com/EddieHubCommunity/LinkFree/assets/91553087/17ecc08e-d05f-4d90-b5e6-c0455b0b03e2)

### Additional information

Feel free to correct me at any step and
Thanks for giving the time .

**Comment by eddiejaoude** [comment]
@ManashAnand I have unlocked the issue, you can edit your description or reply now

**Comment by ManashAnand** [comment]
Thanks , 
I would really like to work on the styling part  of button to make them a little bold
as the issue I think is it too similar with github accelarator button that it's almost look like an image in light mode.

please assign this issue to me

**Comment by eddiejaoude** [comment]
Thank you for raising Manash 👍 the redesign will be starting soon, so I think we can revisit this after that
