### ISSUE TITLE
[BUG] Doc menu highlighting feature not working properly

### ISSUE THREAD

**Issue by ashrafchowdury** [EddieHubCommunity/LinkFree#8262]
## Description

The **documentation menu active page highlighting feature is not working**. When I open the documentation menu, the active page is not highlighted. This makes it difficult to know which page I am currently viewing.

And also we can refactor some of the code and can enhance it further.

**I would like to work on this issue if all sounds good.**

### **Before**

The highlighting function does not work properly.

![image](https://github.com/EddieHubCommunity/LinkFree/assets/87828904/cc5052d1-f7fc-4b01-817d-b2def812205e)

### **After**
After improvement and refactoring multiple lines of code.

![image](https://github.com/EddieHubCommunity/LinkFree/assets/87828904/f2bacfbd-529a-4d25-ba06-ed660f1b892e)

### Additional information

**I would like to work on this issue if all sounds good.**

**Comment by eddiejaoude** [comment]
Yes this feature was not implemented yet - I have assigned it to you @ashrafchowdury
