### ISSUE TITLE
Hide Reorder button when there is no link added

### ISSUE THREAD

**Issue by sumitunique777** [EddieHubCommunity/LinkFree#8282]
### Description

We can hide the reorder button when there is no link added.

### Screenshots

<img width="953" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/105304243/2d9f93d2-71b9-4f72-882a-2e890fade5c0">

**Comment by eddiejaoude** [comment]
Good spot, thank you 👍

**Comment by jesliu-27** [comment]
> Good spot, thank you 👍

Hey, is this task assigned to someone yet? if not, can I get this one :)

**Comment by SaraJaoude** [comment]
> > Good spot, thank you 👍
> 
> Hey, is this task assigned to someone yet? if not, can I get this one :)

@jesliu-27 I have assigned this to you

**Comment by RuchirDixit** [comment]
Hey @jesliu-27, are you sure you have verified this changes and are working as expected...because I tried them at my end locally and this changes do not work for me.

**Comment by jesliu-27** [comment]
> Hey @jesliu-27, are you sure you have verified this changes and are working as expected...because I tried them at my end locally and this changes do not seem to work as expected for me.
> 
> Please make following changes in your PR to make if work:
> 
> ```diff
> - {!linkList.length && !reorder && (
> + {!linkList.length == 0 && !reorder && (
> ```

Thank you so much for your suggestions. I had change with that. However, I am wondering what's the difference between those two line of code. I thought they would execute the same. 

>

**Comment by RuchirDixit** [comment]
Not sure but it just wasn't working at my end with the changes in your PR, started working after modifying it with 2nd line.
But if its working, no issues. Sorry for the confusion and for the notifications! :)

**Comment by sanyamx** [comment]
@SaraJaoude i think you have missed closing this issue! if not then please provide the information about the issue that still persists. Thank You!

**Comment by SaraJaoude** [comment]
> @SaraJaoude i think you have missed closing this issue! if not then please provide the information about the issue that still persists. Thank You!

@sanyamx why do you feel this issue should be closed?  There is an open pull request on this.

**Comment by sanyamx** [comment]
> > @SaraJaoude i think you have missed closing this issue! if not then please provide the information about the issue that still persists. Thank You!
> 
> @sanyamx why do you feel this issue should be closed? There is an open pull request on this.
my bad for not checking it properly! sorry

**Comment by sanyamx** [comment]
Can I pick the issue if there is no one working on it currently?

**Comment by sanyamx** [comment]
Please check PR #8505

**Comment by eddiejaoude** [comment]
No assignee activity for 2 weeks on the issue or PR, so going to unassign

**Comment by eddiejaoude** [comment]
@sanyamx as it has been 2 weeks with activity, we will reassign it to you

**Comment by sanyamx** [comment]
@eddiejaoude @SaraJaoude any updates on PR cause i wanna try solving other issue but i cannot since this one is open

**Comment by SaraJaoude** [comment]
> eddiejaoude @SaraJaoude any updates on PR cause i wanna try solving other issue but i cannot since this one is open

@sanyamx you have chased here and on the PR  - this is not helpful for several reasons. Firstly, please do not tag specific maintainers as reflected in our Contributing Guide (all maintainers receive notifications and can review), second extra notifications do not make maintainers go faster - quite the opposite.  Please take into consideration that we are going through notifications and will get to yours in due course. If your concern is to move on to the next issue, you may wish to consider adding value to other PRs in the meantime by reviewing these - this will help maintainers.
