### ISSUE TITLE
[DOCS] docs - update icons in readme

### ISSUE THREAD

**Issue by nathgoutam93** [EddieHubCommunity/LinkFree#829]
### Description

As prime icons got replaced with react icons,
Some new icons got added as well .
But docs are  still not updated yet , These are the newly added icons :

1.instagram   
2.linkedin 
3.twitch
4.dev.to
5.codewars
6.hashnode
7.graduation-hat

**Comment by emmalearnscode** [comment]
I think we also need to add ticktok to the list.
