### ISSUE TITLE
[BUG] Testimonials 0 is displayed

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/LinkFree#8294]
### Description

When having no testimonials there is displayed a "0" on the page.

### Screenshots

<img width="794" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/30869493/31ce4868-d04c-4d1d-b2e5-4bbb109f3bed">

**Comment by dan-mba** [comment]
Duplicate of #8235
