### ISSUE TITLE
[FEATURE] Add more icons

### ISSUE THREAD

**Issue by krishguptadev** [EddieHubCommunity/LinkFree#830]
### Description

react-icons supports a lot of icons, add all the font awesome icons that you think should be added.

### Additional information

I would like to work on this

**Comment by emmalearnscode** [comment]
Please be more specific in which icons you want to add. These would actually be great first time issues if there was one issue per icon, instead of lumping it into one.

**Comment by krishguptadev** [comment]
> Please be more specific in which icons you want to add. These would actually be great first time issues if there was one issue per icon, instead of lumping it into one.

Have a look at https://fontawesome.com/v5.15/icons?d=gallery&p=2&s=brands&m=free I want the social platform icons from these to be filtered out and used

**Comment by emmalearnscode** [comment]
Please be specific, which of the 400+ icons do you want?

**Comment by krishguptadev** [comment]
> Please be specific, which of the 400+ icons do you want?

The social media platforms like DEV, Dribble, gitlab

**Comment by Vyvy-vi** [comment]
I would recommend opening a new issue with more specifics or editing this one with a markdown list of the icons you would like to add.
(closing it for now...)
