### ISSUE TITLE
[BUG] event hos image disappear in small screens

### ISSUE THREAD

**Issue by Medmly20208** [EddieHubCommunity/LinkFree#8316]
### Description

the image of event host disappear in small screens , the solution maybe would be to remove the hidden class from image and add flex wrap to container 

### Screenshots

![picOne](https://github.com/EddieHubCommunity/LinkFree/assets/69359301/ac468dcb-6d9e-413b-9f74-4d3d75b66d6f)
![picTwo](https://github.com/EddieHubCommunity/LinkFree/assets/69359301/920386ed-7fa8-4e24-a9e7-f08ee8c64061)

### Additional information

I want to work on this issue , can you assign it to me

**Comment by eddiejaoude** [comment]
Thank you for the feedback 👍 

We hide the profile picture because we have limited space on smaller screens. The redesign will be soon and this can be improved then
