### ISSUE TITLE
[BUG] profile photo and no of links is not changed

### ISSUE THREAD

**Issue by anikdhabal** [EddieHubCommunity/LinkFree#8326]
### Description

When opened someone's profile and then clicked on the profile button in the navbar to view my profile, photo and no. of links is not changed. It should show my details.
 loom video:- https://www.loom.com/share/3869bc5892fc4ab896c99de9f253ddc6?sid=acc91148-3fdd-4c95-b4e9-8428d18a01db
### Screenshots

My profile:-
![Screenshot 2023-07-23 195947](https://github.com/EddieHubCommunity/LinkFree/assets/81948346/f7a33e12-a5a5-4bed-91ae-ebae5f506fde)

One person's profile :-
![Screenshot 2023-07-23 200010](https://github.com/EddieHubCommunity/LinkFree/assets/81948346/3e46817e-8d5c-4a46-b37d-64578e45ec0b)

result:-
![Screenshot 2023-07-23 200024](https://github.com/EddieHubCommunity/LinkFree/assets/81948346/751f46e7-5691-4663-b80a-5a1286ea6627)

### Additional information
environment:- prod
browser:- Microsoft Edge
Version 115.0.1901.183 (Official build) (64-bit)
_No response_

**Comment by eddiejaoude** [comment]
Not sure I understand, I tried but I cannot replicate. Please include this information...

- record your screen
- what environment are you using? prod, local (of local what setup)
- what browser?

**Comment by anikdhabal** [comment]
> Not sure I understand, I tried but I cannot replicate. Please include this information...
> 
> * record your screen
> * what environment are you using? prod, local (of local what setup)
> * what browser?

okk let me share a loom video.

**Comment by anikdhabal** [comment]
> Not sure I understand, I tried but I cannot replicate. Please include this information...
> 
> * record your screen
> * what environment are you using? prod, local (of local what setup)
> * what browser?

check it once ,done.

**Comment by eddiejaoude** [comment]
Thank you for including the information 👍

**Comment by ghoshRitesh12** [comment]
I would like to work on this issue.

**Comment by eddiejaoude** [comment]
> Hey, I would like to work on this issue.

I have assigned it to you @ghoshRitesh12 - please note this is a high priority issue

**Comment by eddiejaoude** [comment]
@ghoshRitesh12 as this is a **critical** bug, the maintainers have worked on a solution - sorry for the confusion, but I will reassign the issue
