### ISSUE TITLE
[FEATURE] Navlinks Hover Transition

### ISSUE THREAD

**Issue by ghoshRitesh12** [EddieHubCommunity/LinkFree#8328]
## Description
To add a hover effect transition on the navlinks.

### Screenshots

https://github.com/EddieHubCommunity/LinkFree/assets/101876769/9dadfde9-bd45-4465-a2b9-d17d79064de8

**Comment by eddiejaoude** [comment]
Thank you for the suggestion 👍  the new rebranding and design are happening soon, so I think we do not need to make any design changes like this at the moment, so I will close the issue
