### ISSUE TITLE
How to make a distinct difference between organisation profiles, and personal.

### ISSUE THREAD

**Issue by CodingSpecies** [EddieHubCommunity/LinkFree#833]
### As said by @eddiejaoude : 

I think if we have an optional type field in the json for community | personal

There could be multiple PRs

1. Updating `community` profiles with the `type: community`
2. [optional] updating the `personal` to `type: community`
3. On homepage display the type in each chip
4. On the profile page display type at the top
5. Filter search by type using dropdown

### As @Vyvy-vi explained:

Imo, I think there needs to be some form of distinction atleast in the JSON schema for the org profile.
Maybe we can add some text about this being an org, in the profile(if we want).

From a maintenance point of view, it would be easier to out-right see it as an org., so that anyone can edit it's data..
(Also, in future we might want to make these open-accessed, instead of being linked through the discord)

### Additional information

Originally from:
#696

**Comment by CodingSpecies** [comment]
@emmalearnscode is this a good issue to close the other one? #696

**Comment by emmalearnscode** [comment]
> @emmalearnscode is this a good issue to close the other one? #696

I actually meant that 1 - 5 could each be 5 separate  issues so that different people could work on them and when they’re done the pr would close the specific issue. As it is now all 5 would have to be complete to close the issue. I’ll close this one for now so we can make 5 separate ones.

**Comment by CodingSpecies** [comment]
Ok, I will create 5 seperate @emmalearnscode

**Comment by emmalearnscode** [comment]
@CodingSpecies no need, it’s already done 😊

**Comment by CodingSpecies** [comment]
Thank you  @emmalearnscode
