### ISSUE TITLE
[FEATURE] differentiate between communities and personal profiles on homepage

### ISSUE THREAD

**Issue by emmalearnscode** [EddieHubCommunity/LinkFree#834]
### Description

It is now possible to add profile types, either community or personal. These should be differentiated on the homepage in some way (accessible, not just by colour) so that it’s easy to see which profiles are communities. This could be in the form of a badge/icon added to the chip of community profiles as an example.

**Comment by Vyvy-vi** [comment]
I think to keep things concise, we can use the word `org` in the badge

**Comment by code3z** [comment]
How about this? @Vyvy-vi 
![image](https://user-images.githubusercontent.com/77302900/149043117-3b4e01c1-b424-4575-8ad5-4cf9e7b2f23d.png)

**Comment by KendallDoesCoding** [comment]
You can filter profiles by personal and community right? But a badge would still be good ig.

**Comment by KendallDoesCoding** [comment]
> How about this? @Vyvy-vi ![image](https://user-images.githubusercontent.com/77302900/149043117-3b4e01c1-b424-4575-8ad5-4cf9e7b2f23d.png)

Yes this looks good!

**Comment by eddiejaoude** [comment]
This looks great! However the home page is too large now and slow, plus hits GitHub's rate limit

We are looking to redo the home page, I will close this, but please leave ideas here https://github.com/EddieHubCommunity/LinkFree/issues/1264
