### ISSUE TITLE
[FEATURE] Add an autocomplete of existing groups when adding a new link

### ISSUE THREAD

**Issue by Elijah-trillionz** [EddieHubCommunity/LinkFree#8343]
### Description

I'm suggesting adding an autocomplete of existing groups of a user in the input for grouping links when adding a new link:

<img width="938" alt="linkfree-issues2" src="https://github.com/EddieHubCommunity/LinkFree/assets/60356516/fbc36e67-dd70-4ad8-8942-623e066b589e">

Using Headless UI autocomplete component will make it look better:

<img width="525" alt="linkfree-solution1" src="https://github.com/EddieHubCommunity/LinkFree/assets/60356516/99e464b9-4f25-4401-b1d3-0b307c089de2">

### Additional information

I'd like to be assigned to this.

**Comment by SaraJaoude** [comment]
@Elijah-trillionz thank you for the suggestion, I have assigned this to you.

**Comment by Elijah-trillionz** [comment]
Alright thanks

**Comment by eddiejaoude** [comment]
@Elijah-trillionz did you mean to close this issue? it hasn't been completed yet
