### ISSUE TITLE
[FEATURE] Academic Achievements Section

### ISSUE THREAD

**Issue by SaketKaswa20** [EddieHubCommunity/LinkFree#8353]
### Description

User should be able to add a  Academic Achievements Section in his LinkFree.

### Additional information

Also we can add Volunteering Positions, Publications etc. LinkFree should be a one stop solution for all the information about the specific user.

**Comment by eddiejaoude** [comment]
Thank you for the suggestion, but I think this comes into the milestone section, so I will close https://linkfree.io/docs/how-to-guides/milestones-forms
