### ISSUE TITLE
[FEATURE] community profile pages marked as community 

### ISSUE THREAD

**Issue by emmalearnscode** [EddieHubCommunity/LinkFree#836]
### Description

It is now possible to add types community or personal to profiles. Community profiles should clearly mark somewhere at the top of the profile page that it belongs a community, in order to differentiate it from personal pages.

**Comment by MadhaviMandalia** [comment]
Hello @emmalearnscode ,

Can you explain a bit more?

Thanks & Regards.

**Comment by emmalearnscode** [comment]
This is a bad example as it's the only community we have currently listed and it has the word community in the title but imagine it only stood 'EddieHub' as the title. We would want something at the top to mark that this is a community page and not just a personal page.
<img width="942" alt="Screenshot 2022-01-08 215128" src="https://user-images.githubusercontent.com/57045550/148659666-9edf2d41-55ff-421a-b9ad-5333fd53684a.png">

**Comment by ChuksMbanaso** [comment]
uhm, so you want the Eddiehubcommunity to be replaced by just community, so folks will know it not a personal page???

**Comment by MadhaviMandalia** [comment]
Hello @emmalearnscode ,
I want to contribute on this issue please assign me

Thanks & Regards.

**Comment by emmalearnscode** [comment]
> uhm, so you want the Eddiehubcommunity to be replaced by just community, so folks will know it not a personal page???

No, we shouldn't replace it but have an extra banner somewhere in the header that points out that this is a community profile. I will try to do some mock ups later to show what I mean more clearly.

**Comment by emmalearnscode** [comment]
@MadhaviMandalia Sure, you are now assigned.

**Comment by MadhaviMandalia** [comment]
@emmalearnscode can we use an icon which only represents a Community

**Comment by KendallDoesCoding** [comment]
Good idea!

**Comment by eddiejaoude** [comment]
@MadhaviMandalia I have unassigned it for now, let us know if you wish to make the changes and we can reassign it again
