### ISSUE TITLE
[OTHER] add type community to community profiles

### ISSUE THREAD

**Issue by emmalearnscode** [EddieHubCommunity/LinkFree#837]
### What would you like to share?

It is now possible to create community profiles with type: community. Check through all the profiles and see if any look like communities that need the type: community adding to their json data.

**Comment by krishguptadev** [comment]
> ### What would you like to share?
> It is now possible to create community profiles with type: community. Check through all the profiles and see if any look like communities that need the type: community adding to their json data.
> 
> ### Additional information
> _No response_

I've already added them 🙂

**Comment by emmalearnscode** [comment]
If you’re sure they’re all up to date then I’ll close this issue 👍
