### ISSUE TITLE
[BUG] Issue With Mobile Responsiveness 

### ISSUE THREAD

**Issue by 0rigin-c0de** [EddieHubCommunity/LinkFree#8373]
### Description

When I open this Beautiful website on a mobile device i look there is a text overlapping as i shown in the below screenshot

### Screenshots

![Screenshot 2023-07-27 232539](https://github.com/EddieHubCommunity/LinkFree/assets/106311923/72bba3cb-9e9a-4e76-a75d-47e26a8d1a47)

### Additional information

Kindly assign it to me

**Comment by SaraJaoude** [comment]
Thank you for your suggestion @0rigin-c0de  - I have assigned this to you.

**Comment by avinashji1302** [comment]
is this still open?
