### ISSUE TITLE
[OTHER]: classNames function code refactoring

### ISSUE THREAD

**Issue by ashrafchowdury** [EddieHubCommunity/LinkFree#8392]
### What would you like to share?

The function called "classNames" appears on multiple pages and components. It would be more efficient to refactor the code and declare it in a single location, allowing it to be used whenever needed.

We can create a `utils/functions/classNames.js` file path in the root of the project to store the classNames function.

### The function

```
const classNames = (...classes) => {
  return classes.filter(Boolean).join(" ");
};
```

### Additional information

**If all sounds good, I would like to work on it 👍**

**Comment by eddiejaoude** [comment]
Good idea 👍 I have assigned it to you

**Comment by ashrafchowdury** [comment]
We have a `classNames function` to add logical styles in elements, but there are a lot of elements in a project which use template literal to add logical styles. I think it will be a great approach to use one-way to logical styles instead of multiple, this way we can maintain the style of the project.

**And also we have to add a style guide for contributors to write code in a sequence.**

### Example of not using the classNames function
![image](https://github.com/EddieHubCommunity/LinkFree/assets/87828904/cd09212f-6ce1-4833-b3b1-3111edee5bdc)

**Comment by eddiejaoude** [comment]
Yes good point 👍 I recommend to do this issue first and then raise another issue for the reactor of the other uses
