### ISSUE TITLE
[BUG] mobile view / white space on right side

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/LinkFree#8393]
### Description

There seems to be a problem on mobile view. There is white space on the right side. 

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/30869493/f9ba52b5-cee2-4029-ac99-76c337711411)

### Additional information

Safari
iPhone 13 mini
IOS 16.6

**Comment by SaraJaoude** [comment]
Thanks for raising!

**Comment by azizChebbi** [comment]
can you assign it to me ?

**Comment by SaraJaoude** [comment]
> can you assign it to me ?

@azizChebbi I have assigned this to you

**Comment by schmelto** [comment]
![image](https://github.com/EddieHubCommunity/LinkFree/assets/30869493/b6a7cdea-2bae-4155-a22f-d6e492c576b8)
I think it is coming from the logout button.

**Comment by Bhuminandan** [comment]
@SaraJaoude hey, there is an similar issue causing in another section of linkfree.io, should i raise another issue for that or i can mention it here ?

**Comment by schmelto** [comment]
duplicate with #7917
resolved with #8552
