### ISSUE TITLE
[OTHER] <Updating social icon>

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/LinkFree#8403]
### What would you like to share?

Since Twitter changed its name and icon, I think would be a good idea to replace the old logo with the new one([here's a link to it](https://freebiehive.com/twitter-x-logo-png/) ). Doing so would make it easier to find Linkfree users who have their X accounts posted in the Links section of their profile.  

### Additional information

I'm eager to collaborate on this issue.

**Comment by SaraJaoude** [comment]
We are using React Icons to collect a variety of icon sets together. As the icon libraries do not contain this new icon yet, this update to LinkFree cannot be done.

You may want to raise an issue on the relevant icon library, here is the React Icon Repo where you can see the multiple icon sets: https://github.com/react-icons/react-icons
