### ISSUE TITLE
[BUG] Issue with label in dark mode

### ISSUE THREAD

**Issue by md-abid-hussain** [EddieHubCommunity/LinkFree#8413]
### Description

label in event section of profile does not appear in dark mode.

### Screenshots

![Screenshot (1)](https://github.com/EddieHubCommunity/LinkFree/assets/101964499/402c2cee-7d17-4658-96d6-6a97ff20738c)
![Screenshot (2)](https://github.com/EddieHubCommunity/LinkFree/assets/101964499/dfca3d46-f2c4-488c-b8fd-db7ff86164b7)

**Comment by llii0046** [comment]
I would like to work on this issue, could it be assigned to me?
