### ISSUE TITLE
[BUG] <Text not visible in Input field of Search For Icons page>

### ISSUE THREAD

**Issue by Rahul-Kumar-prog** [EddieHubCommunity/LinkFree#8424]
### Description

Can't able to see test by typing in Input field of Search For Icons page. 
its causing in dark mode not in light mode.

### Screenshots

![Screenshot 2023-07-31 at 5 45 11 PM](https://github.com/EddieHubCommunity/LinkFree/assets/68837569/3fa1afdb-11b8-4329-932e-2178d0da21ba)

**Comment by Ashish-simpleCoder** [comment]
Pls assign me this issue

**Comment by Rahul-Kumar-prog** [comment]
Hey, can you assign me this issue please. I want to work on this.

**Comment by SaraJaoude** [comment]
> Pls assign me this issue

@Ashish-simpleCoder as you requested this first I will assign this to you

**Comment by SaraJaoude** [comment]
> Hey, can you assign me this issue please. I want to work on this.

@Rahul-Kumar-prog can I suggest that in future, if you would like to work on the Issue that you raised that you mention this in the `Additional Information` section of the Issue description.  That way a maintainer can assign this immediately to you when changing the status of the Issue.

**Comment by Rahul-Kumar-prog** [comment]
@SaraJaoude Thanks for letting me know, I'll keep that in mind
