### ISSUE TITLE
[BUG] Add spaces between the missing sections in profile page

### ISSUE THREAD

**Issue by ThomasCode92** [EddieHubCommunity/LinkFree#8433]
### Description

On the statistics page of your profile, the missing sections aren't seperated with a space.
E.g., on my personal page the list says: _tags,socials,testimonials_. But this should be _tags, socials, testimonials_.

I would like to work on this issue.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/108367944/35b001c6-5acf-4e0b-86a0-0c7e9d1ea2e7)

**Comment by SaraJaoude** [comment]
@ThomasCode92 I have assigned this to you.
