### ISSUE TITLE
[BUG] Date and time are only visible on hover in a dark mode on repos page

### ISSUE THREAD

**Issue by ArthVhanesa** [EddieHubCommunity/LinkFree#8436]
### Description

Date and time are only visible on hover in a dark mode on repos page

### Screenshots

Light mode
<img width="960" alt="Screenshot 2023-08-01 174021" src="https://github.com/EddieHubCommunity/LinkFree/assets/77712031/73486693-2e47-4162-99f8-815404264e4a">

Dark mode
<img width="960" alt="Screenshot 2023-08-01 174100" src="https://github.com/EddieHubCommunity/LinkFree/assets/77712031/76facbbd-665c-47fb-9bf3-e67bb3ea0285">

With hover
<img width="944" alt="Screenshot 2023-08-01 175155" src="https://github.com/EddieHubCommunity/LinkFree/assets/77712031/29f53a7c-0256-4b82-856a-2fc7cf95eecd">

**Comment by ChinmayMhatre** [comment]
Thank you for raising the issue. I'll be looking into this

**Comment by ChinmayMhatre** [comment]
Closing this issue, will be addressing this in #8441
