### ISSUE TITLE
[FEATURE] <About Us page>

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/LinkFree#8438]
## Issue 
Even though Linkfree’s website describes its features and testimonials, people might wonder what the products story is.

## Suggested Solution
An About Us page with the following information:
- How and why Linkfree is created 
- Key milestones that the product has achieved since it’s inception 

### Screenshots

[Page of reference](https://www.chubbiesshorts.com/pages/about-us)

### Additional information

I’d love to write the content for this page but I would need help with the design part

**Comment by SaraJaoude** [comment]
Thank you for raising @CBID2.  We already have a video which talks about how LinkFree started and we are currently thinking about whether to embed this into the website or alternatively use the script itself.  However this will all be done as part of the redesign/rebranding exercise which is currently taking place, so I will close this issue for now. 

As to the key milestones, you can already find these in the Changelog, which is also currently being updated.
