### ISSUE TITLE
[BUG] Light/Dark mode for new pages

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#8441]
### Description

Light/Dark mode has not been added to new pages

- manage repos `pages/manage/repos.js`
- admin section `pages/admin/*`
- profile repo list `components/user/UserRepos.js`

**Comment by sreyaarc** [comment]
Can you assign this to me?

**Comment by sital002** [comment]
@sreyaarc We would appreciate that you want to work on this issue but please check the assignees tab to see if someone is already assigned or not.

**Comment by sreyaarc** [comment]
@ChinmayMhatre Are you working on it? Do you mind assigning this to me?

**Comment by eddiejaoude** [comment]
@sreyaarc it was just assigned less than 1 day ago, please look for another issue that is unassigned as mentioned by @sital002 ! You can learn more on how to contribute in our projects contributing guide https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md
