### ISSUE TITLE
[BUG] <Profile Vi>

### ISSUE THREAD

**Issue by abhijivani3001** [EddieHubCommunity/LinkFree#8443]
### Description

While hovering into the graph of profile views section, the number of views shown in box is not in horizontally center.

### Screenshots

![Screenshot 2023-08-01 220316](https://github.com/EddieHubCommunity/LinkFree/assets/117305467/bd29b463-d3b7-46f3-866a-c82ad2a77e75)

**Comment by SaraJaoude** [comment]
Thank you for raising, but this will be addressed as part of the redesign process, so I will close this issue for now.

**Comment by abhijivani3001** [comment]
Okay👍
