### ISSUE TITLE
[FEATURE] For tags - allow the similar behaviors like YouTube Tags

### ISSUE THREAD

**Issue by santoshyadavdev** [EddieHubCommunity/LinkFree#8449]
### Description

For adding tags, we can use the behavior which YouTube has, where tags become not editable on enter, and there is a small close icon to delete the existing one, below is the video for reference,

https://github.com/EddieHubCommunity/LinkFree/assets/11923975/170db7ec-4846-4628-bfd5-1818a6fdb23e

### Additional information

Used it on YouTube and many other places, and I like the UX.

**Comment by SaraJaoude** [comment]
Thank you for the suggestion.  Currently we are looking into keep this super simple but we will look into this as part of the rebrand and UX improvements, so I shall close this Issue for now.
