### ISSUE TITLE
[BUG] <Hovering into Profile, Account, Logout box>

### ISSUE THREAD

**Issue by abhijivani3001** [EddieHubCommunity/LinkFree#8452]
### Description

After hovering into **Profile, Account, Logout** box, the _white line_ is stayed until you click on other area of that page.

### Screenshots

![Screenshot 2023-08-02 093146](https://github.com/EddieHubCommunity/LinkFree/assets/117305467/407b1589-6473-48e4-a239-88ee308576fb)

**Comment by SaraJaoude** [comment]
Thank you for raising.  I cannot seem to replicate this.  As we are going through the redesign process, this should be fixed as part of that so I will close this issue for now.
