### ISSUE TITLE
[OTHER]: Add a consistent style on className

### ISSUE THREAD

**Issue by ashrafchowdury** [EddieHubCommunity/LinkFree#8454]
### What would you like to share?

Consistently using a particular style can significantly enhance the comprehensibility of the codebase. 

**When it comes to adding conditional style** in the `className`, it is advisable to use the `classNames` function instead of template literals as it is much more readable.

## Example

Instead of using template literals to add conditional style 
![image](https://github.com/EddieHubCommunity/LinkFree/assets/87828904/cb47a575-2b33-4c1d-996f-f29bd6c198f9)

We can use this
![image](https://github.com/EddieHubCommunity/LinkFree/assets/87828904/8df62641-5541-4e71-ae3d-0a92ef82dd85)

### Additional information

**If all sounds good, I would like to work on it. 👍**

**Comment by eddiejaoude** [comment]
Good idea, I have assigned it to you @ashrafchowdury
