### ISSUE TITLE
[BUG] <Download QR code>

### ISSUE THREAD

**Issue by abhijivani3001** [EddieHubCommunity/LinkFree#8455]
### Description

- Inside the user profile section, after clicking the orange arrow(resides in front of profile pic) we go to the Download QR code section.
- In Download QR code section, the close tab is highlighted already.

### Solution 
- It should not be highlighted.

### Screenshots

![Screenshot 2023-08-02 122831](https://github.com/EddieHubCommunity/LinkFree/assets/117305467/9e28e53b-d3d0-49e7-ba8e-9300944e00fc)
Orange arrow in front of user profile picture

![Screenshot 2023-08-02 122644](https://github.com/EddieHubCommunity/LinkFree/assets/117305467/93914e22-53f0-4f33-b9e4-e39193e19cfa)
Download QR code

**Comment by SaraJaoude** [comment]
> @SaraJaoude I would like to work on this. Would you please assign this to me?

@ArthVhanesa I have assigned this to you.  

In future, please avoid tagging specific maintainers - all maintainers receive notifications and can assign Issues.  I suggest you might want to take a look at our [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) to see how the project is run.

**Comment by ArthVhanesa** [comment]
Thanks for assigning this to me.
I'll avoid tagging maintainers in future.
