### ISSUE TITLE
[BUG] GitHub Label Action not working

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#8458]
### Description

We are using https://github.com/srvaroa/labeler to add labels for profiles in the Action https://github.com/srvaroa/labeler with config https://github.com/EddieHubCommunity/LinkFree/blob/main/.github/config/labeler.yml but these are not getting added

**Comment by dan-mba** [comment]
It seems to be related to this Go code working different than expected.
https://github.com/srvaroa/labeler/blob/master/pkg/condition_files.go#L40-L50
