### ISSUE TITLE
[BUG] <Dotted underline shown in Repos section>

### ISSUE THREAD

**Issue by abhijivani3001** [EddieHubCommunity/LinkFree#8462]
### Description

- In user **Repos** section inside the User Profile, the link of the repositories uploaded by the user is underlined by the dotted line. 
- To resolve this issue, dotted line should be removed or it should be underlined by solid line with specific gap. 

### Screenshots

![Screenshot 2023-08-02 213745](https://github.com/EddieHubCommunity/LinkFree/assets/117305467/81f9aa35-598d-4b02-9075-bcfe0b469a6b)

**Comment by SaraJaoude** [comment]
Thank you for raising. This will be looked at as part of the redesign process so I will close this issue for now.
