### ISSUE TITLE
[FEATURE] Repos page to only show active repos

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#8475]
### Description

Repos page to only show repos who have been active in the last 30 days

Update mongo query in `pages/api/repos.js` to check for `repos.dates.pushedAt` > the last 30 days

**Comment by rizahmeds** [comment]
Hello @eddiejaoude 
I would like to work on this issue. Please assign it to me.

**Comment by SaraJaoude** [comment]
> Hello,
> I would like to work on this issue. Please assign it to me.

@rizahmeds I have assigned this to you.
