### ISSUE TITLE
[BUG] Description written in Community Events

### ISSUE THREAD

**Issue by abhijivani3001** [EddieHubCommunity/LinkFree#8482]
### Description

- Inside **Event** section, the description written for specific event is override by profile pic of that user.

### Screenshots

![Screenshot 2023-08-03 192221](https://github.com/EddieHubCommunity/LinkFree/assets/117305467/708cab5b-07b1-481e-a354-1fbaf904ed12)

**Comment by SaraJaoude** [comment]
I cannot replicate this so I will close this Issue for now

<img width="1334" alt="Screenshot 2023-08-04 at 13 07 40" src="https://github.com/EddieHubCommunity/LinkFree/assets/82668196/8b72e712-7763-4165-9e10-6f0621dab797">
