### ISSUE TITLE
[BUG] The edit-milestone-icon comes over the mobile menu.

### ISSUE THREAD

**Issue by hi-Kartik2004** [EddieHubCommunity/LinkFree#8507]
### Description

The Z-index of the Edit-milestone-icon is greater than the mobile menu.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/111000515/5fa14a47-ed3d-46f1-87e0-18687863e5b0)

### Additional information

I would like to work on this issue, could you assign it to me?

**Comment by SaraJaoude** [comment]
Thank you for raising. At this time @hi-Kartik2004 we cannot assign this to you as you already have another issue assigned: https://github.com/EddieHubCommunity/LinkFree/issues/7844.  As referenced in our [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) we assign one issue per person.

**Comment by mishra-nikhil0110** [comment]
hi, I would like to work on this issue. Please assign this to me

**Comment by SaraJaoude** [comment]
> hi, I would like to work on this issue. Please assign this to me

@mishra-nikhil0110 I have assigned this to you

**Comment by mishra-nikhil0110** [comment]
> > hi, I would like to work on this issue. Please assign this to me
> 
> @mishra-nikhil0110 I have assigned this to you

hi, please help me in login

**Comment by eddiejaoude** [comment]
> hi, please help me in login

@mishra-nikhil0110 set the environments variables to login, here are the docs https://linkfree.io/docs/environments/environment-variables - if you need any help please ask in Discord

**Comment by mishra-nikhil0110** [comment]
Thanks😊
