### ISSUE TITLE
[DOCS] Improve wording in roadmap

### ISSUE THREAD

**Issue by TomMirfin** [EddieHubCommunity/LinkFree#8512]
### Description

Change the wording in roadmap.js to "Features that are currently being worked on or will be soon.",

**Comment by SaraJaoude** [comment]
As mentioned in https://github.com/EddieHubCommunity/LinkFree/pull/8499 by another contributor, in future please follow this project's [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md). This makes it easier for maintainers to run the project and ensure consistency with our contributions. On this occasion I have reviewed and merged the PR. 

It would also helpful if you could please ensure the title to the Issue has context and is a little more descriptive.

**Comment by TomMirfin** [comment]
Hi Sara.

Apologies it was my first pull. I will from now on 😊. Thank you for your
help.

Tom Mirfin
