### ISSUE TITLE
[BUG] Outdated node version in GitPod

### ISSUE THREAD

**Issue by Deveesh-Shetty** [EddieHubCommunity/LinkFree#8513]
### Description

GitPod is giving an error while running the dev server, after some discussion in Discord it is because the function `structuredClone()` requires Node version 17+ while GitPod is using Node 16.

The fix was using nvm in the `.gitpod.yml` to use node 18 version... which resolves the error

*Note: It can be done manually as well after running the server run the command but it is repetitive*
```bash
nvm install 18
```

### Screenshots

Screenshot of the error
![Screenshot_740](https://github.com/EddieHubCommunity/LinkFree/assets/89470104/ac4d023f-08df-4636-af99-34618c936189)

### Additional information

I would like to work on the issue and update the yml file... Thank you! :)

**Comment by SaraJaoude** [comment]
@Deveesh-Shetty thank you for raising.  Unfortunately I cannot assign this to you at this time as you are already assigned to another Issue (https://github.com/EddieHubCommunity/LinkFree/issues/8457).  As reflected in our [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) we look to assign one issue per person.

**Comment by Deveesh-Shetty** [comment]
I have resolved that issue the PR is up!

**Comment by SaraJaoude** [comment]
> Oh is it... but I have resolved that issue the PR is up!

@Deveesh-Shetty on this occasion as this has been assigned to you we will make an exception.  However, to clarify our Contributing Guide: just because a PR is "up" does not mean you can move on to the next.  Please wait for a PR to be merged/closed before asking to be assigned another, whilst being mindful of maintainers' time and other commitments during this process.

**Comment by Deveesh-Shetty** [comment]
Sorry didn't know about it 😅
Will take care about it next time.... 😄

**Comment by Aarav238** [comment]
I want to work on it. Please assign this to me . As I want to contribute but I can't get issue assigned

**Comment by SaraJaoude** [comment]
> I want to work on it. Please assign this to me . As I want to contribute but I can't get issue assigned

@Aarav238 please check the assignees box and/or comment history before requesting something to be assigned to you - this issue has been assigned to someone else.

**Comment by Deveesh-Shetty** [comment]
Fixed in PR #8559
