### ISSUE TITLE
Add icons in the Linkfree

### ISSUE THREAD

**Issue by edsondsouza** [EddieHubCommunity/LinkFree#8515]
### Description

# Issue
I was updating my LinkFree account and I got to know that there is no icon for [OpenSauced](https://opensauced.pizza/). It would be better if we get the OpenSauced icon in the [LinkFree icons](https://linkfree.io/icons) page.

# What is OpenSauced
> During the most challenging hiring season in history, we are building a platform to help engineers to expand their resume through open source contributions. ~ OpenSauced.pizza

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/93525771/9974ef9d-213e-41e0-9e94-b185b2bca8a5)

### Additional information

https://opensauced.pizza/

**Comment by SaraJaoude** [comment]
Thank you for raising. We use a library for the icons called `React Icons`.  It would be best to raise this on the appropriate icon set library.  Here is a link to their repo: https://github.com/react-icons/react-icons

Therefore I will close this Issue.
