### ISSUE TITLE
Error in Icon

### ISSUE THREAD

**Issue by abdussalam02** [EddieHubCommunity/LinkFree#852]
### Description

In my JSON file, I have added a telegram icon but in the gitpod it's rendering globe icon.

**Comment by emmalearnscode** [comment]
More info: The icon telegram-plane needs importing into the getIcons file and adding to the switch statement.

**Comment by nathgoutam93** [comment]
> More info: The icon telegram-plane needs importing into the getIcons file and adding to the switch statement.

I think it's already added but the name is currently set to "send"

**Comment by emmalearnscode** [comment]
I think it would be best to use the official one from font awesome so it matches all the others

**Comment by abdussalam02** [comment]
> 

I agree with her

**Comment by krishguptadev** [comment]
#851 fixes this AFAIK

**Comment by Rupesh-1302** [comment]
> > More info: The icon telegram-plane needs importing into the getIcons file and adding to the switch statement.
> 
> I think it's already added but the name is currently set to "send"

No I have not added the telegram link. I have added only those links mentioned in the config/icons.json because I was not sure about the colours of the icon.

**Comment by Rupesh-1302** [comment]
> ### Description
> 
> In my JSON file, I have added a telegram icon but in the gitpod it's rendering globe icon.
> 

Due to the absence of telegram icon it's rendering the default icon. (I.e. globe)

**Comment by krishguptadev** [comment]
fixed by #851
