### ISSUE TITLE
[BUG] QR Code link paragraf width

### ISSUE THREAD

**Issue by yassineatik** [EddieHubCommunity/LinkFree#8526]
### Description

When trying to share your profile link , the input that has the URL and the "Copy" button is not well designed as it doesn't show full content, as in the screenshot below :

## BUG : 
<img width="670" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/77692478/f2b485e3-6805-460c-866c-1408cd50c044">

## SOLUTION :
 increase the with of the parent , and set the width of the <p> tag to at least 50% and make it look like this : 
<img width="671" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/77692478/73148be5-a9b3-4880-8a0f-9d1bd33271c6">

### Additional information

I can work on this issue and fix it , or if there's anyone wants to get started with Open Source by this issue he/she can take it :)

**Comment by SaraJaoude** [comment]
> @yassineatik Can I work on this issue, I am just starting to do contributions

@Shiraz-2022 this has been assigned to @yassineatik so please look at other issues marked with the label `status: ready for dev`.

**Comment by Shiraz-2022** [comment]
@SaraJaoude Sure
