### ISSUE TITLE
Icon and text isn't visible on hover

### ISSUE THREAD

**Issue by abdussalam02** [EddieHubCommunity/LinkFree#853]
### Description

When I hover on the Telegram link the icon and text become invisible. I have attached some screenshots have a look.

### Screenshots

![Screenshot (32)](https://user-images.githubusercontent.com/87809119/147291209-618b076a-e689-449e-ac31-5ce84000c747.png)
![Screenshot (33)](https://user-images.githubusercontent.com/87809119/147291213-b2c812f3-e1ac-405d-afbb-1bc7b3f07dd5.png)

**Comment by emmalearnscode** [comment]
Thanks for raising the issue, this is probably linked to the missing telegram icon as this issue was happening before for linked in. We can check it once that issue is resolved to see if it is still a problem

**Comment by emmalearnscode** [comment]
Telegram needs adding to the list in config/icons.json and we also need a fallback hover state for when the icon doesn’t exist

**Comment by Shivansh-yadav13** [comment]
It is not invisible but it changes to white color.
