### ISSUE TITLE
[OTHER]: Transfer all list of arrays to another folder

### ISSUE THREAD

**Issue by ashrafchowdury** [EddieHubCommunity/LinkFree#8543]
### What would you like to share?

The current pages are cluttered with a lot of lists of arrays. I would like to request that all of these arrays be transferred to a separate folder. This will help to keep the main pages clean and organized.

**We can create a** `utils/queries` **folder to store all the arrays.**

## Code example 

**We can create a separate folder to store all of those types of arrays**

![image](https://github.com/EddieHubCommunity/LinkFree/assets/87828904/5bfd7a84-f7df-4bc9-830a-8252f350be25)

### Additional information

**If all sounds good, I would like to work on it.**

**Comment by SaraJaoude** [comment]
Thank you for raising but this is not something that we are looking to change at the moment given our roadmap, so I will close this for now.
