### ISSUE TITLE
[FEATURE] Search bar in documentation

### ISSUE THREAD

**Issue by adityaraute** [EddieHubCommunity/LinkFree#8546]
### Description

It would be very convenient if we could navigate the documentation with search functionality.

Currently we have to go through the left hand dropdowns to access sections

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/43912470/30e9029c-2f13-49d0-9124-e69a9c9cf7e9)

### Additional information

There may be plugins or other libraries available in JS which can be used to onboard this functionality easily.

**Comment by SaraJaoude** [comment]
This is a good suggestion but as our documentation is small, this is something to be looked at at a later stage - so I will close this issue for now.
