### ISSUE TITLE
[BUG] <Profile update notification remains on screen>

### ISSUE THREAD

**Issue by webAbhi** [EddieHubCommunity/LinkFree#8554]
### Description

When user updates anything on profile page and saves the data. the expected success notification shows up but it remains on screen  until user manually closes the notification.  i feel that user experience will be much better if we remove the notification after few seconds.

### Screenshots

![Screenshot 2023-08-07 at 3 43 35 PM](https://github.com/EddieHubCommunity/LinkFree/assets/25529176/a29a68ec-5bf3-4823-891c-b2542105e34b)

### Additional information

Edit: This should be applied to all notifications.

**Comment by mishra-nikhil0110** [comment]
hi, I would like to work on this issue, Please assign me.

**Comment by Vishrut19** [comment]
Can I work on it?

**Comment by SaraJaoude** [comment]
> hi, I would like to work on this issue, Please assign me.

@mishra-nikhil0110 I have assigned this to you. Please see the section in `Additional Information` that I added.

**Comment by webAbhi** [comment]
@SaraJaoude i think by mistake you have assigned this to me 🙂

**Comment by mishra-nikhil0110** [comment]
> > hi, I would like to work on this issue, Please assign me.
> 
> @mishra-nikhil0110 I have assigned this to you. Please see the section in `Additional Information` that I added.

This issue hasn't assigned to me. Should I work on that?

**Comment by SaraJaoude** [comment]
> > > hi, I would like to work on this issue, Please assign me.
> > 
> > 
> > @mishra-nikhil0110 I have assigned this to you. Please see the section in `Additional Information` that I added.
> 
> This issue hasn't assigned to me. Should I work on that?

@webAbhi thanks - @mishra-nikhil0110 I have now assigned this to you

**Comment by mishra-nikhil0110** [comment]
@SaraJaoude I have raised a PR for this issue, please merge it if it doesn't have any problem.
