### ISSUE TITLE
[BUG] Failed to add Github Repo

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [EddieHubCommunity/LinkFree#8560]
### Description

After successful logging in to my account, when I try to add GitHub repo in the repos section, LinkFree fails to add it.
I want to add an Open-Source project of mine. It's called [Drifty](https://github.com/SaptarshiSarkar12/Drifty/).
See the below screenshot to learn more about the error.

edit: remove trailing slash from url 
- from https://github.com/SaptarshiSarkar12/Drifty/
- to https://github.com/SaptarshiSarkar12/Drifty

### Screenshots

![Screenshot from 2023-08-07 23-32-30](https://github.com/EddieHubCommunity/LinkFree/assets/105960032/26a6b7ef-af5d-4991-beaa-7b4495c7ce6c)

**Comment by eddiejaoude** [comment]
It looks like the trailing `/` causes the GitHub API to reject the request

**Comment by SaptarshiSarkar12** [comment]
> Thank you for raising :+1: It looks like the trailing `/` causes the GitHub API to reject the request

Yes, I tried later with the trailing `/` slash removed, and it worked.
@eddiejaoude Can we have this as a warning message for the user? When the user enters a trailing slash, he/she will be notified to remove the trailing slash, instead of just showing **`Repo add failed. Not Found!`**.
_@eddiejaoude If you would like this idea, then, may I work on it?_

**Comment by eddiejaoude** [comment]
thanks for the suggestions, but I think it would be a better user experience if we just remove any trailing slash on our api before sending it to github

**Comment by SaptarshiSarkar12** [comment]
> thanks for the suggestions, but I think it would be a better user experience if we just remove any trailing slash on our api before sending it to github

Yes, that is more better @eddiejaoude

**Comment by eddiejaoude** [comment]
Would you still like this issue assigned to you @SaptarshiSarkar12 ?

**Comment by SaptarshiSarkar12** [comment]
Yes, I would like to work on this @eddiejaoude.

**Comment by SaptarshiSarkar12** [comment]
@eddiejaoude I am facing error regarding setting up the local environment using docker.
When I run `docker compose up` and open the localhost on port 3000 (`localhost:3000`), I am getting the below error.
```js
linkfree  | - error Error [MongooseServerSelectionError]: connect ECONNREFUSED 127.0.0.1:27017
linkfree  |     at _handleConnectionErrors (/usr/src/app/node_modules/mongoose/lib/connection.js:788:11)
linkfree  |     at NativeConnection.openUri (/usr/src/app/node_modules/mongoose/lib/connection.js:763:11)
linkfree  |     at async connectMongo (webpack-internal:///(api)/./config/mongo.js:28:22)
linkfree  |     at async handler (webpack-internal:///(api)/./pages/api/system/reload.js:31:5) {
linkfree  |   digest: undefined
linkfree  | }
linkfree  | [10:36:38.133] ERROR (48): DB connection failed:
```

**Comment by eddiejaoude** [comment]
Please come and discuss in EddieHub Discord http://discord.eddiehub.org

**Comment by SaptarshiSarkar12** [comment]
> Please come and discuss in EddieHub Discord http://discord.eddiehub.org

Thank you for assigning!
Sure @eddiejaoude, I shall discuss this on Discord.

**Comment by SaptarshiSarkar12** [comment]
@eddiejaoude I have opened a PR (#8636) fixing this issue. Please review it.
