### ISSUE TITLE
[BUG] Missing sections info overflows Profile Completion component

### ISSUE THREAD

**Issue by ghoshRitesh12** [EddieHubCommunity/LinkFree#8564]
### Description

In `/account/statistics` page, it shows how much the profile is completed and what sections are missing. The missing sections information overflows the Profile Completion component.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/101876769/5ea0ee47-a869-4369-ab18-5a1a1a14f756)

### Additional information

I would like to work on this bug and fix it.

**Comment by SaraJaoude** [comment]
@ghoshRitesh12 thank you for raising - I have assigned this to you.
