### ISSUE TITLE
[BUG] LinkFree Search Icons' text color

### ISSUE THREAD

**Issue by kaisunoo** [EddieHubCommunity/LinkFree#8578]
### Description

When searching for icons in dark mode, the text is white-on-white. I purposely include misspelled word to demonstrate that the content was typed, and highlighted it after.

### Screenshots

![bug1](https://github.com/EddieHubCommunity/LinkFree/assets/100037842/62f1f0b6-462c-4bda-b690-2527e0819089)
![bug2](https://github.com/EddieHubCommunity/LinkFree/assets/100037842/b5e71522-00da-40cd-9ce3-415fd7e759ef)

**Comment by SaraJaoude** [comment]
Thank you for raising.  This is a duplicate of #8424  which has now been fixed and merged, so I will close this issue.

**Comment by kaisunoo** [comment]
Sorry, I should've looked better in the raised issues to avoid duplicating it. Thank you for letting me be aware!
