### ISSUE TITLE
[BUG] navbar not properly aligned on a mobile environment 

### ISSUE THREAD

**Issue by sanyamx** [EddieHubCommunity/LinkFree#8589]
### Description

Navbar have some gap from the right most edge of the screen when used on the mobile. Left edge is fine.
![IMG_2041](https://github.com/EddieHubCommunity/LinkFree/assets/105167793/d3c1dfcc-02f4-4656-93b8-cb08e9c420f4)
![IMG_2042](https://github.com/EddieHubCommunity/LinkFree/assets/105167793/944d2aae-efca-44c6-a3bd-1865ea4a62ae)

How to reproduce the bug - 
- use the app on a mobile device
- Device used for this bug is iphone 11 pro max, so i think any phone around this size or equivalent would be able to produce the bug.

**Comment by SaraJaoude** [comment]
Thank you for raising, but as we are in the process of redesigning this will be addressed then so I will be closing this issue for now.
