### ISSUE TITLE
[OTHER] Changing Username On GitHub

### ISSUE THREAD

**Issue by orbitalmartian8** [EddieHubCommunity/LinkFree#8590]
### What would you like to share?

I have recently changed my username here on GitHub and I didn't know how I would go about changing my page on Linkfree, or if it affects anything (which it seems to). Any insights would be great! :)

**Comment by eddiejaoude** [comment]
Closing as a duplicate of https://github.com/EddieHubCommunity/LinkFree/issues/8435
