### ISSUE TITLE
[OTHER] Universal formatting in the codebase (Prettier configuration )

### ISSUE THREAD

**Issue by sital002** [EddieHubCommunity/LinkFree#8596]
### What would you like to share?

We should have a universal formatting for the linkfree code so when the contribytor uses prettier they will all follow the same configuration instead of having their cuwtom formatter. I saw that the .prettierrc file is empty we can write the formatting rules so that we have a better format.

**Comment by SaraJaoude** [comment]
As the `.prettierrc` file is empty this defaults to the Prettier recommended settings and we do not need to customise at this time.
