### ISSUE TITLE
Text not showing when hover

### ISSUE THREAD

**Issue by iason9** [EddieHubCommunity/LinkFree#860]
### Description

an issue about the text on the links not showing when hovering with the mouse (see screen shot below)

### Screenshots

![Screen Shot 2021-12-26 at 2 58 11 PM](https://user-images.githubusercontent.com/19413521/147411392-ec1121a7-67e7-4548-b70b-de16addf5989.png)

### Additional information

its for the website link the other links work

**Comment by BSlaven** [comment]
In <profilename>.json file for this profile as icon value is set to "website". Other profiles which have links to their websites used "globe".

There is no designated color for that value in config/links.json file.

I assume the problem is here somewhere.

**Comment by iason9** [comment]
> In .json file for this profile icon value is set to "website". Other profiles which have links to their websites used "globe".
> 
> There is no designated color for that value in config/links.json file.
> 
> I assume the problem is here somewhere.

Yes i think thats the issue as well

**Comment by emmalearnscode** [comment]
Yes, we need to add a default value for the button hover if links.icon doesn't exist in the icon config file. I noticed this the other day, just hadn't got round to raising an issue so thanks for raising it @iason9
