### ISSUE TITLE
[BUG] Space between Add Repo button and list of repo

### ISSUE THREAD

**Issue by abhijivani3001** [EddieHubCommunity/LinkFree#8606]
### Description

- Some space should be added between **Add Repo** button & All the added repositories of the user.

### Screenshots

![Screenshot 2023-08-10 224102](https://github.com/EddieHubCommunity/LinkFree/assets/117305467/ee68ef89-1f38-47d8-bf45-37693729b0a0)

**Comment by Rosh008** [comment]
Can I take this up

**Comment by VivekBaldha0712** [comment]
please assign this task to me. I would like to work on it

**Comment by asyncasad** [comment]
Hi I would like to work on this please. Thankyou.

**Comment by SaraJaoude** [comment]
> Can I take this up

@Rosh008 as you were the first to request this I have assigned this to you.

**Comment by vedantnaik1008** [comment]
I will quickly fix this issue if you let me work on it

**Comment by Rosh008** [comment]
I was setting up my local as a first time contributor, will push changes by tommorrow. Also according to guidelines I don't think this counts as issue is assigned to me. All the best !

**Comment by SaraJaoude** [comment]
> I was setting up my local as a first time contributor, will push changes by tommorrow. Also according to guidelines I don't think this counts as issue is assigned to me. All the best !

@Rosh008 it seems the person that asked for this to be assigned to them has removed the message - I just want to confirm that this issue is assigned to you so please do disregard any other conversation, which unfortunately just creates noise!

**Comment by Rosh008** [comment]
@SaraJaoude PR raised for the issue
