### ISSUE TITLE
[BUG] Mascot image should be centered

### ISSUE THREAD

**Issue by tausiq2003** [EddieHubCommunity/LinkFree#8616]
### Description

When you visit the 404 page, or on 404.js you will see that the mascot image is left-aligned, whereas it should be centered for good looking. You can visit 404 page by going to any pages and adding random text to the URL.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/80088029/1971779a-2d1c-4a3d-a1ea-8eaad19c2809)

**Comment by sandramsc** [comment]
I see that the auther of this issue did not request to work on it, so I ask it to be assigned to me please?
