### ISSUE TITLE
[FEATURE] Birthday Mode

### ISSUE THREAD

**Issue by xkrishguptaa** [EddieHubCommunity/LinkFree#8619]
### Description

We can have a birthday field for the person (optional)

there will be a list of birthdays on discover page (in the side)

AND **CONFETTTTIIIIIII ON THEIR PROFILES** [TOP CLASS IMPORTANCE]

**Comment by SaraJaoude** [comment]
Whilst it would be great to celebrate the birthdays of the LinkFree users, this does begin to fall into the realm of personal information that we are not looking to store (and could potentially present a security risk) so I will close this issue for now.

**Comment by xkrishguptaa** [comment]
@SaraJaoude I was hoping it would be a "optional" information to disclose to us, so it shouldn't be a big issue, since they willingly give us that information
