### ISSUE TITLE
[Feature] Option to elaborate about repo 

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/LinkFree#8620]
### Description

When adding a repo, it would be beneficial to have a text input where people can write about them, especially if they maintain an OSS

### Additional information

I’d like to work on this with someone

**Comment by SaraJaoude** [comment]
Thank you for the suggestion. Given that when a Repo is added to your Profile the description is also displayed, to have the suggested text input field would end up being a duplication, as well as run the risk of becoming out of date so I will close this.
