### ISSUE TITLE
[OTHER] Modification - Adding X logo & Name instead of Twitter 

### ISSUE THREAD

**Issue by scikido** [EddieHubCommunity/LinkFree#8631]
### What would you like to share?

As we all know twitter has been rebranded as X, it would be better if there is logo & name of X instead of twitter.

Screenshot:
<img width="806" alt="Screenshot 2023-08-13 141443" src="https://github.com/EddieHubCommunity/LinkFree/assets/82273027/02cd08b4-25b8-4f37-bf98-272619dfaf89">

### Additional information

I'd like to add logo of X, and change the name of twitter to X.

**Comment by SaraJaoude** [comment]
This has been previously raised and will be closed for the reasons mentioned here: https://github.com/EddieHubCommunity/LinkFree/issues/8403
