### ISSUE TITLE
[BUG] In search icon Input page BackgroundColor and text color both are white so what we type we are not able to see..

### ISSUE THREAD

**Issue by Madankh** [EddieHubCommunity/LinkFree#8635]
### Description

In search for icons input placeholder when we type some word the BackgroundColor and text color both become a white so what we typing on that placeholder we are not able to see so we need to update that placeholder color

### Screenshots

![issure](https://github.com/EddieHubCommunity/LinkFree/assets/84616682/44026041-f85e-47fa-b871-575c38c5f6f7)
![issure image 2](https://github.com/EddieHubCommunity/LinkFree/assets/84616682/590c443a-1704-47c8-81fb-fcb2453c14fb)

**Comment by SaraJaoude** [comment]
Thank you for raising, but this is a duplicate which has already been fixed under the following: https://github.com/EddieHubCommunity/LinkFree/issues/8424 so I will close.
