### ISSUE TITLE
[BUG] Empty link group shows as Other

### ISSUE THREAD

**Issue by loftwah** [EddieHubCommunity/LinkFree#8639]
### Description

If I create a LinkFree profile with the following configuration:

Group 1
  Link 1
Group 2
  Link 2
  
  Link 3
  
It will display as

Other
  Link 3

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/19922556/a47d7735-f59b-4991-984a-a6a94d0f7b85)

### Additional information

We probably don't need to see the number of links in the group, or the name of the other group.

**Comment by eddiejaoude** [comment]
Thanks for the suggestion Dean 👍 

I think if we don't use `other` then `Link 3` will appear as part of the previous group above it and cause confusion.

I will close for now, but the issue unlocked feel free to add more thoughts
