### ISSUE TITLE
[BUG] The Profile Pictures On Testimonials And Profiles Don't Match

### ISSUE THREAD

**Issue by xkrishguptaa** [EddieHubCommunity/LinkFree#8642]
### Description

On a particular profile page (linked below), under the testimonials in the person's profile, there is a testimonial from the name "CJ LinuxGamer" in LinkFree, with the username being "LinuxGamer", their placeholder shows "AA" while on their profile page, it shows "Li"

The links to these pages:

- The profile with the testimonial: https://linkfree.io/krishstwt
- The link to the profile: https://linkfree.io/LinuxGamer

### Screenshots

This is the screenshot of the testimonial, where the profile picture is a placeholder saying "AA"

![a screenshot of a testimonial on linkfree with special emphasis on the profile picture/avatar](https://github.com/EddieHubCommunity/LinkFree/assets/135469703/c7ca5309-0285-43ed-b428-09244b375f39)

This is the screenshot of the same person's profile on Linkfree:

![a screenshot of a profile on Linkfree with particular emphasis on the profile picture/avatar](https://github.com/EddieHubCommunity/LinkFree/assets/135469703/2f7a2aa3-f757-4102-b782-93a8a03fb66f)

### Additional information

~~We should have a standard helper function to generate these so there is no inconsistency.~~

Edit: I noticed there is a helper function, it is just not being used properly in the testimonial component

## Solution

https://github.com/EddieHubCommunity/LinkFree/blob/44e67d806f690299782e24e68cd1ad090189444d/components/user/UserTestimonials.js#L19-L27

This code will have to be changed:

```diff
<FallbackImage
  width={100} // just to pass nextjs error
  height={100}
  src={`https://github.com/${testimonial.username}.png`}
  alt={testimonial.username}
+ fallback={testimonial.username}
  className="rounded-full bg-primary-low"
  />
```

But because the UserPage component has access to the username, we might want to change:

https://github.com/EddieHubCommunity/LinkFree/blob/44e67d806f690299782e24e68cd1ad090189444d/components/user/UserProfile.js#L46 to:

```diff
- fallback={data.name}
+ fallback={data.username}
```

**Comment by SaraJaoude** [comment]
Thanks for raising such a good issue!

**Comment by SaraJaoude** [comment]
@Pravesh-Sudha please see my comments on here: https://github.com/EddieHubCommunity/LinkFree/pull/8644 

I will assign this to you.

**Comment by donishyar** [comment]
Hi , i want to work on this issue  please assign me.

**Comment by kumarsonsoff3** [comment]
Hey @donishyar, this issue has already been closed as completed on **Aug 15, 2023**. Please look for other [open issues here](https://github.com/EddieHubCommunity/BioDrop/issues) with label `🏁 status: ready for dev`. 

Also, get yourself with [Contributing guidelines here](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md)!
