### ISSUE TITLE
Multiple line break issue in description

### ISSUE THREAD

**Issue by sumitunique777** [EddieHubCommunity/LinkFree#8650]
### Description

when we press enter button multiple times in the description textarea it doesn't reflect in the output. I can take up this issue if it is valid

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/105304243/25132480-ddd3-4abd-b209-d1243181bdcf)

**Comment by SaraJaoude** [comment]
Thank you for raising. 

GitHub also only displays one blank line so we will stick to this standard, so I will close this issue for now.
