### ISSUE TITLE
Hide Success taost

### ISSUE THREAD

**Issue by sumitunique777** [EddieHubCommunity/LinkFree#8651]
### Description

We can hide the message toast after some time or we can give the cross icon on the top right corner of the toast div to close it manually.I can takeup this issue if it is valid

### Screenshots

<img width="960" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/105304243/a855b405-e256-438f-bb07-3e5159c2216d">

**Comment by SaraJaoude** [comment]
Thank you for raising.  As we are currently going through the rebranding process this will be looked at then, so I will close this issue for now.
