### ISSUE TITLE
Improvement:  Icons text box a searchable dropdown? 

### ISSUE THREAD

**Issue by sumitunique777** [EddieHubCommunity/LinkFree#8652]
### Description

Can we make Icons text box as a searchable dropdown?

### Screenshots

<img width="936" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/105304243/53f1c4bb-83dc-4301-a6b0-018354479251">

**Comment by SaraJaoude** [comment]
Thank you for raising but this is a duplicate of https://github.com/EddieHubCommunity/LinkFree/issues/8350 so I will close this issue.
