### ISSUE TITLE
[UI/UX Bug] <The Profile Page Looks Scattred >

### ISSUE THREAD

**Issue by yytambaya** [EddieHubCommunity/LinkFree#8656]
### Description

I think there's an inconsistency in the spacing of the components. I want to try and make it more beautiful with the styling of the project. The input fields look scattered and the profile view is not structured best with the text.

### Screenshots

![Uploading Screenshot (286).png…]()

**Comment by amandamartin-dev** [comment]
@yytambaya Hello! Your screenshot did not attach to the issue.  I opened so this issues can be a discussion.  Please add more detail including your proposal to address the issues you are seeing and folks can discuss here.

**Comment by SaraJaoude** [comment]
@yytambaya thank you for raising - we agree that the profile page does need some improving, but as we are currently going through a rebranding process this will be covered at this stage - so I will close this issue for now.
