### ISSUE TITLE
Input and version span weird position on small screen

### ISSUE THREAD

**Issue by BSlaven** [EddieHubCommunity/LinkFree#866]
### Description

On small screens tag showing version ends just underneath the input element.

This happens on screens with less than 340px in width, so I am not sure we really need to address this.

Thoughts?

### Screenshots

![Screenshot (49)](https://user-images.githubusercontent.com/55027209/147471579-75368ee8-1fa9-4986-b17a-4af9a6421d8b.png)

**Comment by krishguptadev** [comment]
Small q: the smallest device is 350px right? So why do we need to fix this?

**Comment by BSlaven** [comment]
Yeah, I said I am not sure we need to addresss this. 
But I have a phone that displays this 'issue'. That is how i found it.

**Comment by Vyvy-vi** [comment]
though, ideally we can probably write a fix for it?
(maybe center the text whenever screen gets too small?)

**Comment by krishguptadev** [comment]
> though, we can probably write a fix for it? (maybe centre the text whenever the screen gets too small?)

maybe remove the text?

**Comment by Vyvy-vi** [comment]
Either can work...
Personally, I'd prefer for it to be centered below the searchbar on smaller screens. (It takes away some of the sleek-ness, but the version number and the github link are important)

**Comment by piyush-1234** [comment]
![ff](https://user-images.githubusercontent.com/76208964/147868064-ff60991b-c644-4501-ba25-41a20ee83d04.PNG)

**Comment by Zishan-7** [comment]
Hey @Vyvy-vi , 
I would love to work on this issue, can you assign it to me?
