### ISSUE TITLE
[FEATURE] Create a Icon For Threads 

### ISSUE THREAD

**Issue by kumarankit999** [EddieHubCommunity/LinkFree#8674]
### Description

There is not icon for Thread, it should also be there because many developers are using it like twitter, but there isn't any icon for this in the Eddiehub icons section.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/111564362/b9d25241-9f28-4b4d-942f-d300471fde63)

**Comment by SaraJaoude** [comment]
Thank you for raising. We are using React Icons to collect a variety of icon sets together. As the icon libraries do not contain this new icon yet, this update to LinkFree cannot be done.

You may want to raise an issue on the relevant icon library, here is the React Icon Repo where you can see the multiple icon sets: https://github.com/react-icons/react-icons

I will therefore close this issue for now.
