### ISSUE TITLE
[BUG] My PR is merged 2 days ago but it's not reflected in my Linkfree Profile

### ISSUE THREAD

**Issue by chetannada** [EddieHubCommunity/LinkFree#8697]
### Description

I have Updated my [Linkfree profile ](https://linkfree.io/chetannada) by creating [PR #8659](https://github.com/EddieHubCommunity/LinkFree/pull/8659) and it's merged 2 days ago but it's not reflected in my [Linkfree profile ](https://linkfree.io/chetannada)

### Screenshots

This is my [PR #8659](https://github.com/EddieHubCommunity/LinkFree/pull/8659) that merged.
![Update chetannada json by chetannada · Pull Request #8659 · EddieHubCommunity_LinkFree](https://github.com/EddieHubCommunity/LinkFree/assets/83969719/edcb9cce-a77e-4926-aa74-a3a53b6cb02b)

This is my [Linkfree profile ](https://linkfree.io/chetannada), I have updated `"group": "Socials Secondary"`, and some `"milestones"` also in [PR #8659](https://github.com/EddieHubCommunity/LinkFree/pull/8659) but it's not reflected 
![Chetan Nada](https://github.com/EddieHubCommunity/LinkFree/assets/83969719/80935a1f-1909-4b92-a605-027e081ce752)

![Chetan Nada (1)](https://github.com/EddieHubCommunity/LinkFree/assets/83969719/598de974-fa9f-4d01-98ca-a55b6baa98b5)

### Additional information

All the data that i have added through [PR #8659](https://github.com/EddieHubCommunity/LinkFree/pull/8659) it's not reflected in my [Linkfree profile ](https://linkfree.io/chetannada)

**Comment by ChinmayMhatre** [comment]
Hi @chetannada , have you updated your profile using the forms on LinkFree? you can check this by going to https://linkfree.io/account/manage/profile . Check if you have an alert something like this 
<img width="1292" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/51131670/f7c8cce7-2500-4f0b-9216-69afb5961914">

**Comment by eddiejaoude** [comment]
Good spot @ChinmayMhatre , they have used the forms, so their profile is now managed by forms and the json is ignore - so I will close this issue

@chetannada please send a PR removing your json file as it is no longer needed

<img width="642" alt="Screenshot 2023-08-19 at 07 51 35" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/4578cba3-5ab7-443f-ac7f-2dff444c448d">

**Comment by ChinmayMhatre** [comment]
@chetannada Once you edit your profile using form, you cannot edit it using the json file. You can add the milestones and make the update to your bio using forms. And as Eddie suggested you can raise a PR to delete the json file to make the alert go away. Let me know if you have any more doubts!

**Comment by chetannada** [comment]
> Hi @chetannada , have you updated your profile using the forms on LinkFree? you can check this by going to https://linkfree.io/account/manage/profile . Check if you have an alert something like this <img alt="image" width="1292" src="https://user-images.githubusercontent.com/51131670/261781932-f7c8cce7-2500-4f0b-9216-69afb5961914.png">

Hi @ChinmayMhatre I have seen an alert before creating PR but i have not updated my Profile using the forms on LinkFree. I have only added Repo using LinkFree website

Hi @eddiejaoude but i have not updated my Profile using the forms on LinkFree. I have only added Repo using LinkFree website so it count as using update using forms? Please confirm so i can create PR regarding removing my json file. Thanks.

Please find screen shot of Repo that i have added before PR merged

![Manage Repositories (repos)](https://github.com/EddieHubCommunity/LinkFree/assets/83969719/a635c1c9-860b-452e-a327-59e40b6291e0)

**Comment by chetannada** [comment]
> 

@ChinmayMhatre Thanks for the info.

**Comment by eddiejaoude** [comment]
> but i have not updated my Profile using the forms on LinkFree. I have only added Repo using LinkFree website so it count as using update using forms? Please confirm so i can create PR regarding removing my json file. Thanks.

yes @chetannada using any form to manage your profile even repos will no longer use the json so you can safely remove the file in a new pull request

**Comment by chetannada** [comment]
> > but i have not updated my Profile using the forms on LinkFree. I have only added Repo using LinkFree website so it count as using update using forms? Please confirm so i can create PR regarding removing my json file. Thanks.
> 
> yes @chetannada using any form to manage your profile even repos will no longer use the json so you can safely remove the file in a new pull request

Thanks @eddiejaoude for the confirmation.
