### ISSUE TITLE
[OTHER] Automated test search.spec.js 

### ISSUE THREAD

**Issue by kbventures** [EddieHubCommunity/LinkFree#8699]
### What would you like to share?

I created a automoated test "After search click profile" in ./test/search.spec.js

`test("After search click profile", async ({ page }) => {
  // 1. Perform search
  await page.goto("/search");
  const input = page.locator("[name='keyword']");
  await input.type("eddiejaoude");
  
  // 2. Click on the searched profile
  const profileLinkSelector = 'a[href="/eddiejaoude"]';
  const profileLink = page.locator(profileLinkSelector);
  await profileLink.click();
  await page.waitForLoadState("networkidle");

  // 3. Check if the profile is displayed
  const profileHeader = page.locator("h1");
  const profileHeaderText = await profileHeader.innerText();
  await expect(profileHeaderText).toContain("Eddie Jaoude"); 
});`

### Additional information

Please assign issue to me so I can make a pull requests.

**Comment by SaraJaoude** [comment]
@kbventures Eddie has assigned this to you

**Comment by sital002** [comment]
The PR is already merged you can close this issue as completed.

**Comment by SaraJaoude** [comment]
Good spot @sital002  - I will close
