### ISSUE TITLE
[FEATURE] Centering the search bar

### ISSUE THREAD

**Issue by Abjcodes** [EddieHubCommunity/LinkFree#871]
### Description

The search bar is currently placed on the left-most side, but it would be better if it's centered since it's easier to notice and reach.

### Screenshots

![Center search bar](https://user-images.githubusercontent.com/42151354/147729896-3230ac92-061d-4a9a-b371-3949748d6904.png)

**Comment by JayTailor45** [comment]
Hello, I can work on this. Can you assign it to me?

**Comment by Shivansh-yadav13** [comment]
![147729896-3230ac92-061d-4a9a-b371-3949748d6904](https://user-images.githubusercontent.com/87603425/147810486-7491ddbf-941f-42e8-a849-ff943f175e42.png)

what do you think about this? ^^^

**Comment by emmalearnscode** [comment]
I actually prefer the search bar to the left. Maybe we can wait for more discussion to see what others prefer before assigning this

**Comment by ChuksMbanaso** [comment]
left is better tho. I havent seen a search bar in the middle. The left side is much better

**Comment by Shivansh-yadav13** [comment]
Left is good :+1:

**Comment by abhishekgite446** [comment]
Left is good from my perspective as well :)

**Comment by Ash-KODES** [comment]
I think Left is better for a search bar so,I think you can close this issue

**Comment by alokVerma749** [comment]
left is fine
