### ISSUE TITLE
[OTHER] Expose compose mongodb container port and update documentation accordingly

### ISSUE THREAD

**Issue by dmitrykulakovfrontend** [EddieHubCommunity/LinkFree#8716]
### What would you like to share?

Apparently compose.yml exposes only port 3000 which is allowing to connect for us to linkfree app, but to use MongoDB Compass right now we are running separate container, we could fix that if we expose port 27017 in compose.yml the same way like linkfree does, that would allow external tools such as MongoDB Compass connect to mongo to view database.

![image](https://github.com/EddieHubCommunity/LinkFree/assets/36533957/1fc878fd-87b1-4f54-ac2b-3e4364babf6c)

### Additional information

We would also need to change documentation part "Local development with Docker Compose", because now we don't need to run a separate mongo container for MongoDB Compass

![docs](https://github.com/EddieHubCommunity/LinkFree/assets/36533957/5c66adeb-32aa-490e-b45d-22ab8ef9689b)

**Comment by eddiejaoude** [comment]
thank you 👍 I have assigned it to you @dmitrykulakovfrontend as I know you have done the investigation
