### ISSUE TITLE
[BUG] Updating user bio in map view

### ISSUE THREAD

**Issue by maelstrom0x8** [EddieHubCommunity/LinkFree#8731]
### Description

I noticed that after updating my bio the changes are not reflected in the map view. Even after updating it multiple times it still has no effect there.

**Comment by amandamartin-dev** [comment]
@maelstrom0x8 The map data is cached and changes to your bio will not be reflected immediately.  If you have made a change AND it has been longer than 7 days, please let us know.  If you do open a bug after the 7 days window as passed, be sure to link your profile and share screenshots of the difference so it is easier for folks to confirm.

Here is the documentation on how the map works for more information: https://linkfree.io/docs/map

Closing this for now.

**Comment by maelstrom0x8** [comment]
It's updated! Thanks

**Comment by eddiejaoude** [comment]
Great! Thanks for letting us know @maelstrom0x8 👍
