### ISSUE TITLE
[FEATURE] Rebrand: name, colours, logo

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#8748]
### Description

PRE launch

- [x] Update app with new name, logo and colours - @azhechkova
- [x] ~~Create new Vercel app with new domain (use existing db)~~ decided to reuse existing app
- [x] Create Vercel envars with new names
- [x] Uptime for new name (`monitoring` repo)

POST launch

- [ ] Merge PR
- [ ] linkfree.eddiehub.org redirect to biodrop.io
- [ ] linkfree.io to redirect to biodrop.io
- [ ] GitHub OAuth update url, name and logo
- [ ] Rename the repo + update repo description and url
- [ ] Explain the rename in the README

**Comment by eddiejaoude** [comment]
<img width="1275" alt="Screenshot 2023-08-25 at 22 17 07" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/1f60752c-00d2-4e41-bf74-fe598b14e9fa">

**Comment by CBID2** [comment]
Hey @eddiejaoude! :)  Congrats on getting the rebrand name! :) Biodrop is catchy and bit more catchy! :) If possible, I’d love to do a PR that updates [the documentation](https://linkfree.io/docs/quickstart-json) with the new name. It’ll keep things moving fast.

**Comment by eddiejaoude** [comment]
> Hey @eddiejaoude! :) Congrats on getting the rebrand name! :) Biodrop is catchy and something I’ve never heard before! :) If possible, I’d love to do a PR that updates [the documentation](https://linkfree.io/docs/quickstart-json) with the new name. It’ll keep things moving fast.

Thank you Chrissy! Everything should already be updated in the PR  https://github.com/EddieHubCommunity/LinkFree/pull/8757
