### ISSUE TITLE
Add mastodon Icon

### ISSUE THREAD

**Issue by varghesejose2020** [EddieHubCommunity/LinkFree#886]
### Description

https://mastodon.social/about

**Comment by piyush-1234** [comment]
i ll work on this.

**Comment by KendallDoesCoding** [comment]
I haven't heard of mastodon and don't think many people use it.

**Comment by schmelto** [comment]
@piyush-1234 you still up for this?

**Comment by eddiejaoude** [comment]
This is now done 👍 so I will close this issue
