### ISSUE TITLE
[FEATURE] Add a share profile function to the Linkfree profiles

### ISSUE THREAD

**Issue by unnikrishnan2002** [EddieHubCommunity/LinkFree#901]
### Description

The basic idea is to implement a share function which will copy the url of the profile to the clipboard so that you can share it with anyone .

**Comment by emmalearnscode** [comment]
It would be great to see a mock up of this and #902 to get some ideas of how it could look

**Comment by unnikrishnan2002** [comment]
> It would be great to see a mock up of this and #902 to get some ideas of how it could look

We can simply add a button which will copy the link of your profile to the clipboard. We could just place it below the links . But for that we need to shift the milestone section to bottom. I feel that we would need a discussion to find where should we place the button. But anyway the idea is to copy the message to clipboard and also display a message to the user telling that the link has been copied

![image](https://user-images.githubusercontent.com/76985777/148018795-2315f8e1-4d5a-4900-8bc4-43d937363099.png)

**Comment by avneesh0612** [comment]
I was thinking icon-based, so it goes with social media 🤔

**Comment by unnikrishnan2002** [comment]
> I was thinking icon-based, so it goes with social media 🤔

Yeah of course we can customise accordingly. I jus put it for demonstration purpose 👍

**Comment by avneesh0612** [comment]
ah cool!
