### ISSUE TITLE
[FEATURE] share to socials icon

### ISSUE THREAD

**Issue by avneesh0612** [EddieHubCommunity/LinkFree#902]
### Description

Add options to share profiles to social media like Facebook, Twitter, etc. in profiles easily.

**Comment by emmalearnscode** [comment]
It would be great to see a mock up of this and #901 to get some ideas of how it could look

**Comment by avneesh0612** [comment]
Yeah maybe just add a clipboard or link icon too for copying?

**Comment by Kira272921** [comment]
👀 Maybe a button which would create a tweet, just like the tweet button in hashnode

**Comment by avneesh0612** [comment]
Yeah that is what I meant @Kira272921 👀
