### ISSUE TITLE
[OTHER] Center when only one milestone (on large screen)

### ISSUE THREAD

**Issue by EmmaDawsonDev** [EddieHubCommunity/LinkFree#911]
### What would you like to share?

If someone includes only one milestone on larger screens eg desktops it's positioned to the right which looks slightly odd (IMO). I suggest we add a check to see how many milestones there are and if there's only one then the milestone should be centered, more than one the styling can remain as it is currently.

<img width="941" alt="Screenshot 2022-01-04 160238" src="https://user-images.githubusercontent.com/57045550/148081420-48225ae5-24b2-4eb1-8b9e-73eff8f40f22.png">

**Comment by developer-diganta** [comment]
@emmalearnscode 
Hello! Would this look OK?
![image](https://user-images.githubusercontent.com/65999534/148115770-3382ec87-74e5-4178-8308-58d058fc7e1e.png)

**Comment by emmalearnscode** [comment]
Maybe keep it the same width as the buttons? But otherwise, yes, that's what I was thinking.

**Comment by developer-diganta** [comment]
![image](https://user-images.githubusercontent.com/65999534/148208200-fb9e324c-912f-42fa-bad3-99f9c0c0d0ea.png)
This one is for large screen sizes.
But if the screen gets smaller, the width decrease (until Timeline corrects itself). I tried using w-70 class but it does not seem to work.
![image](https://user-images.githubusercontent.com/65999534/148208384-6b3598c8-8008-46fa-930f-4fe3ed97765c.png)
(A bit smaller screen)
![image](https://user-images.githubusercontent.com/65999534/148208449-751cdc7d-4bb1-457f-92a6-a06baccead14.png)
(For XS and mobile screens)

**Comment by Vyvy-vi** [comment]
Hey @developer-diganta!
Since you tweaked around with this for a bit, I assigned this issue to you (if you'd like to work on this?)

**Comment by developer-diganta** [comment]
@emmalearnscode @Vyvy-vi Shall I open a PR for this?

**Comment by Yoshemith** [comment]
Hi @emmalearnscode, Is this issue still active? Can I work on this one?

**Comment by vaib1343** [comment]
Hi @EmmaDawsonDev can raise PR for this issue?
