### ISSUE TITLE
[FEATURE] A Back to top button

### ISSUE THREAD

**Issue by digambar-t7** [EddieHubCommunity/LinkFree#912]
### Description

The site has a lot many profiles which makes it too lengthier. On scrolling the page, we can go deep down. In this case, it would become easier to get back to the top by clicking on this BACK TO TOP button.

**Comment by emmalearnscode** [comment]
Good idea!

**Comment by digambar-t7** [comment]
> Good idea!

------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Hey there,
             I have created the Back-to-top-btn & made the required changes. But, I am not able to push it to my custom-made git-branch.
I am facing errors related to eslint. I have added the error below. I tried a lot to fix it but was unable to do so. Please, can you help me fix this error.
By the way, this is my first ever contibution to any open source project :).

------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Code/OpenSource/LinkFree$ git commit -m "Created a BackToTopBtn which scrolls the page back to the top"

✔ Preparing...
✔ Hiding unstaged changes to partially staged files...
⚠ Running tasks...
  ❯ Running tasks for *.{js,css,md,json}
    ✔ prettier --write
    ✖ eslint --ext [.json,.js] --fix [FAILED]                                 <-------------here is the error
↓ Skipped because of errors from tasks. [SKIPPED]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up...

✖ eslint --ext [.json,.js] --fix:

Code/OpenSource/LinkFree/src/Components/Home/Home.css
  1:3  error  Parsing error: Unexpected token {

✖ 1 problem (1 error, 0 warnings)

husky - pre-commit hook exited with code 1 (error)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by emmalearnscode** [comment]
@digambar-t7 try running this in your terminal ```npm run lint -- --fix``` If it doesn't fix it then please share a screenshot of your code, it looks like you may have a missing bracket somewhere according to the error

**Comment by digambar-t7** [comment]
@emmalearnscode
It points to having an error in a css file.
![Screenshot from 2022-01-05 01-42-31](https://user-images.githubusercontent.com/92970968/148118282-74c8b9ca-ccd9-49b4-a4a0-7ba3ef13088b.png)

**Comment by emmalearnscode** [comment]
Try commenting out the css you added to see if it actually is the css file or something else

**Comment by digambar-t7** [comment]
@emmalearnscode 
Yes, without css it works fine.
But whenever I add css and try to commit, the error appears again.

**Comment by emmalearnscode** [comment]
@digambar-t7 ok, can you take a screenshot of the css code and share it?

**Comment by digambar-t7** [comment]
![Screenshot from 2022-01-05 02-30-49](https://user-images.githubusercontent.com/92970968/148123520-3a29130c-6ccf-4b9d-a269-2059a1ed02b7.png)

**Comment by emmalearnscode** [comment]
Ok, I can't see any errors but it could be that you accidentally deleted a semi-colon somewhere else in the css. My suggestion to narrow it down is to go through and comment out one CSS block at a time. When the error goes away then you've found which block is causing issues, then if you can't see the error comment out line by line until the error goes away.

**Comment by digambar-t7** [comment]
Actually, I just fixed it by creating js objects for style & using them in the inline way.

**Comment by emmalearnscode** [comment]
Just another tip too - we are using a CSS library in this project called Prime React so things like margins and padding, flex etc you should use prime react classes. Inline styling is not recommended.

**Comment by digambar-t7** [comment]
Ok I will change it to this :)
