### ISSUE TITLE
[DOCS] need improvement in avatar part of docs

### ISSUE THREAD

**Issue by Rahulbaran** [EddieHubCommunity/LinkFree#917]
### Description

In the avatar part of the docs , It should be clearly mentioned that one just have to add his/her **Github username** with `.png` extension and the website will automatically fetch your Github avatar.

**Comment by Rahulbaran** [comment]
Please assign me this, so I can work on it

**Comment by krishguptadev** [comment]
Sure! @Rahulbaran feel free to work on it :D
