### ISSUE TITLE
[BUG] Mascot/ Logo incorrectly aligned

### ISSUE THREAD

**Issue by Abhijit-Dixit** [EddieHubCommunity/LinkFree#923]
### Description

In the "Profile not found" error page, the mascot is incorrectly aligned to the left, center alignment seems more natural and symmetrical.

### Screenshots

![bug1](https://user-images.githubusercontent.com/41284892/148341339-b4ff30aa-f278-4663-8afb-2cfb60cef484.PNG)

**Comment by ishaanbedi** [comment]
Hi! I'd like to work on this issue! Can you assign it to me?

**Comment by emmalearnscode** [comment]
@ishaanbedi sorry, the person who raised the issue has already submitted a pull request
