### ISSUE TITLE
[FEATURE] Add a test to check the URL links are not broken

### ISSUE THREAD

**Issue by abhishekgite446** [EddieHubCommunity/LinkFree#934]
### Description

Add one more test in user.feature to check if the url(s) mentioned on the user page are in correct format. 

### Additional information

Happy to pick up this task :)

**Comment by abhishekgite446** [comment]
I tried investigating if this can be done using Cypress, but unfortunately I was not able to find a solution. Just for the the reason Cypress explicitly does not support testing in multiple tabs, there are workaround if you have **target** property but in our application all the buttons in the user page dow not have href, target properties hence it is difficult to do this using Cypress. If anyone is aware of the solution I would request to pick this issue up. I will un-assign this feature from my name.

**Comment by KendallDoesCoding** [comment]
To enhance the idea, sites exist like downdetector I think, where you can see if the site is down, someone can even make a script to do this, so if the site on any profile is down, github-actions automatically makes a issue thread in this repo and when it comes back it will auto-close the issue

**Comment by krshkun** [comment]
Hi, it's been so long, any updates? If not let me know, I figured out how to write the test :smile:

**Comment by eddiejaoude** [comment]
I will close this, because I think people can test their own links that they add
