### ISSUE TITLE
[OTHER] Use prime-react classes on chip

### ISSUE THREAD

**Issue by emmalearnscode** [EddieHubCommunity/LinkFree#940]
### What would you like to share?

Instead of using custom CSS, where possible we should change to prime react.

Task: 
1. Remove the following 3 lines of css from Home.css:
<img width="238" alt="Screenshot 2022-01-08 212923" src="https://user-images.githubusercontent.com/57045550/148659380-949af743-94b8-4ed5-99c5-aaa9e35ee625.png">

2. Add the following classes to the <Chip> component in User.js:
<img width="469" alt="Screenshot 2022-01-08 212951" src="https://user-images.githubusercontent.com/57045550/148659410-cd06995e-8336-4f40-81a7-d8ecccd29b0b.png">

**Comment by Hat52** [comment]
Hi, I would link to work on this issue.

**Comment by emmalearnscode** [comment]
Hi @Hat52 someone already made a pull request for this issue but I’ll post some more similar issues soon so keep an eye out 😊
