### ISSUE TITLE
[OTHER] Use prime react classes on chip text

### ISSUE THREAD

**Issue by emmalearnscode** [EddieHubCommunity/LinkFree#941]
### What would you like to share?

As we are using prime react we should remove the custom css and replace with prime react classes.

1. Remove the following CSS from Home.css:
<img width="215" alt="Screenshot 2022-01-08 220523" src="https://user-images.githubusercontent.com/57045550/148660042-c94d2cb5-d431-4c04-9357-4f6e42794c71.png">

2. Replace with these prime react classes in the User.js component
<img width="488" alt="Screenshot 2022-01-08 220542" src="https://user-images.githubusercontent.com/57045550/148660050-27f62406-fae0-4a6d-907f-732bbb6aefec.png">

**Comment by Abhi-paul16** [comment]
I want to work on this issue can you please assign me

**Comment by emmalearnscode** [comment]
Hi @Abhi-paul16 someone has already made a pull request for this one but keep an eye out as I will be listing similar ones soon
