### ISSUE TITLE
[OTHER] Use prime react classes for button container width

### ISSUE THREAD

**Issue by emmalearnscode** [EddieHubCommunity/LinkFree#948]
### What would you like to share?

1. Remove the following CSS from Links.css: 
<img width="229" alt="Screenshot 2022-01-09 161100" src="https://user-images.githubusercontent.com/57045550/148688461-efae8a09-e7df-41f0-b003-e6fbef402e23.png">

2. Replace with sm:w-9 md:w-7 on line 23 of Links.js 
<img width="332" alt="Screenshot 2022-01-09 161125" src="https://user-images.githubusercontent.com/57045550/148688485-54d1f9ae-5859-4b4a-a921-e6ee23871cae.png">

**Comment by git-devansh** [comment]
Hi, I would like to work on this issue

**Comment by snehaljos** [comment]
Hi, @emmalearnscode is the issue still open?

**Comment by emmalearnscode** [comment]
@snehaljos thanks for asking! It’s already being worked on but similar issues remain so keep an eye out for when they are posted

**Comment by vish-han** [comment]
Hey @emmalearnscode!! If this is issue is still open , can u please assign me.....😊

**Comment by vish-han** [comment]
Thanks for assigning 😁

**Comment by emmalearnscode** [comment]
> Thanks for assigning 😁

No problem, have fun and let us know if you need help with anything
