### ISSUE TITLE
[FEATURE]Hovering the social media icons

### ISSUE THREAD

**Issue by digambar-t7** [EddieHubCommunity/LinkFree#951]
### Description

The icons shown in the ss are not having any hovering styles.

### Screenshots

![Screenshot from 2022-01-10 00-04-15](https://user-images.githubusercontent.com/92970968/148695808-6eeee8cc-b0e1-4460-89bf-e6f0c7fbe311.png)

**Comment by Hat52** [comment]
Hi, I would like to take up this challenge.

**Comment by digambar-t7** [comment]
Hey @Vyvy-vi @emmalearnscode I have made the required changes in the code & made a pr #952.
Please review it & let me know if some changes are needed.
