### ISSUE TITLE
[OTHER] <Click link click increase tests> /tests/profile.spec.js #9384

### ISSUE THREAD

**Issue by kbventures** [EddieHubCommunity/LinkFree#9537]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

We want to tests if the persisting click count is correct in the profile links. 

### Proposed Solution

`import { Profile, Link } from "@models/index";

test("Link clicks increase", async ({page}) => {
  await connectMongo();
  await page.goto("/eddiejaoude");
  
  const startingLink = await Link.findOne({  url: "https://twitter.com/eddiejaoude" })

  const previousClickCount = startingLink.clicks; 
  console.log("previousClickCount", previousClickCount)

  const profileLink = page.locator('a').filter({ hasText: 'Twitter: Follow me' })

  await profileLink.click();
  await page.waitForTimeout(1000);
  const currentLink = await Link.findOne({ url: "https://twitter.com/eddiejaoude" })

  expect(currentLink.clicks).toEqual((previousClickCount + 1));
});
`

### Do you want to work on this issue?

Yes

### If you want to work on this issue...

The following tests confirms that the click count that is persisted actually updates and is correct by simulating real user interaction with our application. 

````import { Profile, Link } from "@models/index";

test("Link clicks increase", async ({page}) => {
  await connectMongo();
  await page.goto("/eddiejaoude");
  
  const startingLink = await Link.findOne({  url: "https://twitter.com/eddiejaoude" })

  const previousClickCount = startingLink.clicks; 
  console.log("previousClickCount", previousClickCount)

  const profileLink = page.locator('a').filter({ hasText: 'Twitter: Follow me' })

  await profileLink.click();
  await page.waitForTimeout(1000);
  const currentLink = await Link.findOne({ url: "https://twitter.com/eddiejaoude" })

  expect(currentLink.clicks).toEqual((previousClickCount + 1));
});
```

**Comment by SaraJaoude** [comment]
I am closing this Issue as the PR for it has been merged.
