### ISSUE TITLE
[DOCS] update the demonstration gif 

### ISSUE THREAD

**Issue by unnikrishnan2002** [EddieHubCommunity/LinkFree#955]
### Description

Since the Linkfree profile had some UI changes like share feature etc . I think the gif should be updated to show the latest version of the app.

**Comment by ChuksMbanaso** [comment]
yeah, that will be convenience

**Comment by schmelto** [comment]
sure @khushbooag4

**Comment by gefgu** [comment]
Hi! Can I work on this issue?
