### ISSUE TITLE
Tooltip for Homepage-Avatars

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/LinkFree#96]
When hovering a Avatar, the username of the hubber could be displayed with a tooltip

**Comment by ShlokMohanty** [comment]
@Cahllagerfeld so we dont have have a code for this hovering effect ? so without this if we use the tooltip we are able to see the name of the user when hovered over right?

**Comment by Cahllagerfeld** [comment]
We are using PrimeReact as Component Framework. You can take a look at the [Tooltips](https://primefaces.org/primereact/showcase/#/tooltip) they provide

**Comment by Sejal-16** [comment]
Can i work on this issue ?
