### ISSUE TITLE
[FEATURE] Better Homepage Buttons/Cards

### ISSUE THREAD

**Issue by code3z** [EddieHubCommunity/LinkFree#961]
### Description

The homepage is filled with fancy button-like links to showcase the people using linktree. However, I thought they could use some improvement. I made a Figma design for buttons that I think are better than the current ones.

Figma link:
https://www.figma.com/file/2CF0qrDUGWwDZSwT1sjag4/Untitled?node-id=0%3A1

### Screenshots

![image](https://user-images.githubusercontent.com/77302900/148868290-24d0a922-1e1e-4180-a45b-b6779604b8a9.png)

### Additional information

Here are the improvements:
- "Correct" color hierarchy - background is darker than foreground
- No number bubbles - they are somewhat confusing, I thought it would be more clear to list the links that have been added in the form of icons
- I added the github username to the buttons
- Improved borders - instead of a wide padding around the image there is now a slight transparent border. The images can now be slightly larger
- Removed zoom on hover - this can be somewhat distracting and has scaling issues
- Possible rectangular version - I made a circular and rounded rectangle version, for your consideration

**Comment by ChuksMbanaso** [comment]
Your figma designs are better. i'd def go with the round-hover type

**Comment by TakshakRamteke** [comment]
@code3z  The design is great , 

although i think you could have added a bit more white space to it because it kinda looks crammed as it is right now, 
also in my opinion having those social media icon's there is just adding extra bit of details to the design. 
As the card's are not that big so legibility might become a issue on some devices (not quite sure), another point to be noted is that all the user's don't have the same number of socials so adding those icons according to every user means adding that much complexity which may affect the performance

**Comment by emmalearnscode** [comment]
Thanks for your ideas @code3z however, I think this is going to make the homepage look way too cluttered. Less is definitely more, especially when there are so many profiles being shown at once.

**Comment by schmelto** [comment]
Could we provide this as a quick embedded link for implementing in other websites?

**Comment by code3z** [comment]
> although i think you could have added a bit more white space to it because it kinda looks crammed as it is right now

Noted.

> another point to be noted is that all the user's don't have the same number of socials

I know, that was the point - to tell what has been added without the buttons.

> means adding that much complexity which may affect the performance

I think it could be done efficiently without affecting performance. I might just remove the social icons though, I’ll make a new version tonight.

> Could we provide this as a quick embedded link for implementing in other websites

Yeah, but maybe it would look a little different on other websites. Like with a “view on linkfree” text. Maybe open another issue for this?

**Comment by code3z** [comment]
@ChuksMbanaso I'm glad you like it :smiley: 

@TakshakRamteke @emmalearnscode How about this version without the social icons:
![image](https://user-images.githubusercontent.com/77302900/149031370-8fde0071-d6dc-448f-9a03-32b13c915a26.png)

@schmelto How about this larger version with more information for embedding on other sites?
![image](https://user-images.githubusercontent.com/77302900/149031523-3e9d3a30-a05f-4f8e-b3ab-98b43e4890f1.png)

The updated versions are at the same Figma link along with the old versions:
https://www.figma.com/file/2CF0qrDUGWwDZSwT1sjag4/Linkfree-Profile-Buttons?node-id=0%3A1
https://www.figma.com/proto/2CF0qrDUGWwDZSwT1sjag4/Linkfree-Profile-Buttons?node-id=23%3A2&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=23%3A2&show-proto-sidebar=1

**Comment by emmalearnscode** [comment]
I still personally think that it's going to make the homepage look more cluttered. I would like to see a mockup of a whole page of these chips compared to how it looks now.

**Comment by code3z** [comment]
> I still personally think that it's going to make the homepage look more cluttered. I would like to see a mockup of a whole page of these chips compared to how it looks now.

Ok, do you have a figma design for the homepage I can edit?

**Comment by KendallDoesCoding** [comment]
> I still personally think that it's going to make the homepage look more cluttered. I would like to see a mockup of a whole page of these chips compared to how it looks now.

I think this too, but it's still worth a try and let's see how it looks, coz overall it looks better. Although, if the profile has lots of links, it will look bad.

**Comment by eddiejaoude** [comment]
Great idea and discussion! As the homepage is so big now, we are looking to remove this from the homepage, please see https://github.com/EddieHubCommunity/LinkFree/issues/1264

So I will close for now, please add suggestions to #1264
