### ISSUE TITLE
[FEATURE] Custom Title

### ISSUE THREAD

**Issue by digambar-t7** [EddieHubCommunity/LinkFree#964]
### Description

Hey there,
             Can we change the title dynamically. Like if someone lands on the profile page then the title would be something related to the Profile itself. 

For Example:    'Profile name' | LinkFree

**Comment by aliraza944** [comment]
Is this dynamic title change only for the profile page or for all the pages?

**Comment by emmalearnscode** [comment]
Which title do you mean?

**Comment by aliraza944** [comment]
page title or document title

**Comment by digambar-t7** [comment]
I mean the document title which appears on the tabs of the browser.

**Comment by digambar-t7** [comment]
Is it right if someone's  issue is being addressed by someone else's pull request.

**Comment by emmalearnscode** [comment]
Usually it’s best to ask to be assigned, even if you are opening the issue and intend to fix it yourself, otherwise it’s not clear that it’s being worked on and others can think it’s up for grabs. Not everyone who opens an issue intends to fix it themselves (or knows how) so it’s quite common in open source that the person making the pull request is not the same person that opened the issue.

**Comment by KendallDoesCoding** [comment]
> Usually it’s best to ask to be assigned, even if you are opening the issue and intend to fix it yourself, otherwise it’s not clear that it’s being worked on and others can think it’s up for grabs. Not everyone who opens an issue intends to fix it themselves (or knows how) so it’s quite common in open source that the person making the pull request is not the same person that opened the issue.

@digambar-t7 If you still want to fix the issue, feel free to suggest changes, etc or ask @aliraza944 if he's fine with you making another PR on this as #968 hasnt been merged yet.

**Comment by digambar-t7** [comment]
Thanks but I already moved on.
And as he has already raised a PR then there is no sense in doing it again.

**Comment by KendallDoesCoding** [comment]
> 

Ok, just informed you coz #968 anyway hasn't been merged.

**Comment by emmalearnscode** [comment]
Closed via #1475
