### ISSUE TITLE
[FEATURE] Adding a Docker Compose file

### ISSUE THREAD

**Issue by RishiKumarRay** [EddieHubCommunity/LinkFree#965]
### Description

Adding a Docker Compose file

**Comment by RishiKumarRay** [comment]
Can you assign me this and I can work on this

**Comment by emmalearnscode** [comment]
Can you explain why this would be beneficial to the project? I don't know anything about docker - what does a docker compose file do? Why should we have one in this project?

**Comment by RishiKumarRay** [comment]
This project already has Dockerfile , now if you want to run this in a container first you have to build a image then run which is a time consuming. Now if we add a docker compose here , it will run this application in a single command . Also if your priority is not running this in Dockerized environment do let me know , I am happy to close this issue.

**Comment by emmalearnscode** [comment]
I have no idea, but there may be other maintainers who think this is a good idea. Leave the issue open and collect some more opinions on it from others :)

**Comment by eddiejaoude** [comment]
I use Docker Composer when I have multiple containers, I have not used it for when there is just 1 file.

Adding the file won't hurt though and will help when we adda DB etc

**Comment by rohitdasu** [comment]
hi @eddiejaoude can you assign this ticket to me?

**Comment by eddiejaoude** [comment]
@rohitdasu sure, just to let you know, we have started a docker composer file in the new version of LinkFree here https://github.com/EddieHubCommunity/LinkFree/blob/nextjs/docker-compose.yml

Let me know if yo still want the ticket

**Comment by rohitdasu** [comment]
Hi @eddiejaoude i've checked the [docker-compose.yml file](https://github.com/EddieHubCommunity/LinkFree/blob/nextjs/docker-compose.yml). I think it's not completed, if we docker-compose up it won't run the Next.js image file and also i've seen that there is a mongodb service issues. As you know in docker database data will be deleted after we stop the container. so i can prevent it by adding volumes. If you think this will help then let me know. Thanks 😊 🙏

**Comment by FrancescoXX** [comment]
let me know if you need me on this one

**Comment by eddiejaoude** [comment]
thanks @FrancescoXX 👍 

I think this is taken care of now, in the latest version. A new issue can be raised with specific information if it is still required
