### ISSUE TITLE
[DOCS] Add warning about not adding package.json To contributing.md

### ISSUE THREAD

**Issue by emmalearnscode** [EddieHubCommunity/LinkFree#969]
### Description

Many people accidentally add and commit their package.json and package-lock.json files when contributing their profile. I suggest making the contribution guidelines clearer, maybe with a warning not to add these files and not to use git add . 

It could be added somewhere here in the contributing.md file:
![286BDA27-C849-423A-A31D-4EE40826EC35](https://user-images.githubusercontent.com/57045550/148987759-bd306b9e-fd1d-4940-b6b1-04f402f5c2ee.jpeg)

**Comment by nathgoutam93** [comment]
would like add this point :
Only if any changes made to the installed packages then package.lock.json  files are allowed to push.

**Comment by Hat52** [comment]
I would like to add this point in the documentation.
