### ISSUE TITLE
[FEATURE] Small Design Improvement for selecting between community/personal/all

### ISSUE THREAD

**Issue by code3z** [EddieHubCommunity/LinkFree#972]
### Description

I made a mockup to show how styled radio buttons could provide a nicer-looking and easier to use alternative to the current select box. It will take one click to select instead of two, and it will make better use of the space.

### Screenshots

![image](https://user-images.githubusercontent.com/77302900/149045071-31cd8090-b9b5-43c6-b719-d59bec172026.png)
![image](https://user-images.githubusercontent.com/77302900/149045089-9496c577-85b3-4b8f-987e-56e910fc48a1.png)

### Additional information

Figma link:
https://www.figma.com/file/M9vnoWZO4Ci8xm3AwJrxJ4/LinkFree-Communities%2FPeople-Selector?node-id=0%3A1

**Comment by MadhaviMandalia** [comment]
Hello @code3z ,
Are you making a PR for it if not let me contribute on this issue
Please let me know

Thanks & Regards.

**Comment by code3z** [comment]
@MadhaviMandalia I haven’t started any code, feel free to work on it.

**Comment by rohan-kulkarni-25** [comment]
Nice Addition @code3z  !! The UI actually looks so clean ! 

- @MadhaviMandalia Once we get the design accepted by Team let's work on this ! This will avoid wastage of your time. 
- I think the design is good and we can go with that !!

**Comment by schmelto** [comment]
Like the design 👍

**Comment by emmalearnscode** [comment]
Yes, nice design 👍

**Comment by Zishan-7** [comment]
Hey @MadhaviMandalia ,
Are you still working on this issue?
If not, please let me know I would love to contribute.
Thanks.

**Comment by eddiejaoude** [comment]
Great discussion everyone! Remember we use PrimeReact, there are many pre-built components available, for example https://www.primefaces.org/primereact/toolbar/

**Comment by Niravprajapati1** [comment]
we can do this with this component https://www.primefaces.org/primereact/tabview/

**Comment by eddiejaoude** [comment]
We now have a new version of the app using new technology, NExtJS and TailWind - I will close this issue but a new one can be raised if still required
