### ISSUE TITLE
[OTHER]

### ISSUE THREAD

**Issue by whoiskekeanyway** [EddieHubCommunity/LinkFree#978]
### What would you like to share?

The SSL Certificate at http://linkfree.eddiehub.org/ has expired. Please look into it.
@eddiejaoude 
Thanks

<img width="318" alt="Screenshot 2022-01-12 at 15 51 51" src="https://user-images.githubusercontent.com/71834585/149160946-8b083d0b-7c34-4acb-b11e-6dac0b7baec1.png">

**Comment by krishguptadev** [comment]
Duplicate of #197

**Comment by emmalearnscode** [comment]
I'll close this as it's a duplicate but thanks for flagging the issue!

**Comment by eddiejaoude** [comment]
Thanks all for collaborating 👍 we will fix soon
