### ISSUE TITLE
Add Social icon

### ISSUE THREAD

**Issue by lavakush07** [EddieHubCommunity/LinkFree#982]
## In the social icon section we can add  the icon of [Medium](https://medium.com/) too..

- Medium is mostly used by the programmers these days to blog their posts..

**Comment by MadhaviMandalia** [comment]
Hello @lavakush07 ,
Can I raise PR for this issue?

Thanks & Regards.

**Comment by emmalearnscode** [comment]
Sure @MadhaviMandalia When adding an icon it needs to be added in three files. First import it from react icons into the components/Icons/GetIcons.js file and add it to the switch statement. Then in config/links.json add a hex color code for the icon. Finally, update the available icons table in the readme. Feel free to ask any questions if you need help.

**Comment by lavakush07** [comment]
> Hello @lavakush07 , Can I raise PR for this issue?
> 
> Thanks & Regards.

Yeah,Go ahead.. 😊
- I wanted to do it.,but np

**Comment by emmalearnscode** [comment]
@lavakush07 Oh sorry, next time you raise an issue write in the additional info that you want to be assigned and that'll help to know not to assign someone else :)

**Comment by lavakush07** [comment]
Yeah cool.. looking forward to contribute more to the eddiehub organisation🚩.
