### ISSUE TITLE
[BUG] Copy to Clipboard not working in Firefox Browser

### ISSUE THREAD

**Issue by vikasganiga05** [EddieHubCommunity/LinkFree#983]
### Description

When the copy to clipboard button is clicked it throws the error `navigator.clipboard is undefined`. I am using Firefox v95.0.2 browser. I did some [research](https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined), I found that `navigator.clipboard` is only available when the site you're browsing has a secure origin (HTTPS). [http://linkfree.eddiehub.org/](http://linkfree.eddiehub.org/) is using (HTTP). I think because of that copy to clipboard is not working.

### Screenshots

![Error Screenshot](https://user-images.githubusercontent.com/74750414/149356358-a7842489-0fc9-4907-b74e-d3b096933dda.png)

### Additional information

My suggestion is to use old-school copy to clipboard using the [out of viewport hidden textarea trick](https://stackoverflow.com/a/60292243).
```js
const CopyLink = () => {
  if (typeof(navigator.clipboard) == 'undefined') {
    // Do the out of viewport hidden textarea trick.
  }
  navigator.clipboard.writeText(`http://linkfree.eddiehub.org/${username}`)
  toast.current.show({
    severity: 'success',
    summary: 'Link copied to clipboard.',
  })
}
```

**Comment by ramanjitsingh-hub** [comment]
I would like to work on this issue. I am new to open source but familiar with PR . Can anyone help me with this issue?
Any suggestions are appreciated

**Comment by emmalearnscode** [comment]
Duplicate #946 

Please continue the discussion in the open thread.

**Comment by vikasganiga05** [comment]
> Duplicate #946
> 
> Please continue the discussion in the open thread.

Sorry, I thought it's a new issue. I will add this to #946 issue.
