### ISSUE TITLE
Arranging the icons of readme in order

### ISSUE THREAD

**Issue by RishiKumarRay** [EddieHubCommunity/LinkFree#996]
### Description

The ICONS are not in order

**Comment by RishiKumarRay** [comment]
@emmalearnscode please assign me

**Comment by rohan-kulkarni-25** [comment]
Hey @RishiKumarRay !! 
- Thanks for showing interest. 
- Please mention the snap of icons which you want to add space between. 
- This will help moderators to review the PR

**Comment by KendallDoesCoding** [comment]
@emmalearnscode @rohan-kulkarni-25 I'm down to do this if @RishiKumarRay needs help. Can you assign me on this too?

**Comment by emmalearnscode** [comment]
Let’s give @RishiKumarRay a couple of days to respond, then if they’re no longer interested or don’t answer you can take over this issue @KendallDoesCoding

**Comment by KendallDoesCoding** [comment]
> Let’s give @RishiKumarRay a couple of days to respond, then if they’re no longer interested or don’t answer you can take over this issue @KendallDoesCoding

Ok. Thanks!

**Comment by RishiKumarRay** [comment]
@emmalearnscode Sorry , I got busy with some other stuff , i forgot about this issue , please assign @KendallDoesCoding , I will do something else later on. Thanks

**Comment by KendallDoesCoding** [comment]
> @emmalearnscode Sorry , I got busy with some other stuff , i forgot about this issue , please assign @KendallDoesCoding , I will do something else later on. Thanks

👍 , No problem!

**Comment by emmalearnscode** [comment]
> @emmalearnscode Sorry , I got busy with some other stuff , i forgot about this issue , please assign @KendallDoesCoding , I will do something else later on. Thanks

No problem, thanks for letting us know.

**Comment by KendallDoesCoding** [comment]
@emmalearnscode Thanks for assigning me.

**Comment by KendallDoesCoding** [comment]
Icons in alphabetical order:
Android	
Microsoft		
Apple	
PayPal		
Discord		
Slack	
Envelope		
Telegram		
Facebook	
Twitter		
GitHub		
Vimeo	
Globe		
YouTube		
Link	
Book		
Dollar		
Instagram	
LinkedIn		
Twitch		
DEV.to	
Hashnode		
Codewars		
Graduation Hat	
TikTok		
Send		
Search	
Left Arrow		
Snapchat		
Codeforces	
Medium		
Polywork		
GitLab

**Comment by KendallDoesCoding** [comment]
Icons in alphabetical order:
Android	
Apple	
Book		
Codeforces	
Codewars		
DEV.to	
Discord		
Dollar		
Envelope		
Facebook	
GitHub		
GitLab	
Globe		
Graduation Hat	
Hashnode		
Instagram	
Left Arrow		
Link	
LinkedIn		
Medium		
Microsoft		
PayPal		
Polywork		
Search	
Send		
Slack	
Snapchat		
Telegram		
TikTok		
Twitch		
Twitter		
Vimeo	
YouTube

**Comment by KendallDoesCoding** [comment]
This is more hard to do than I thought lol

**Comment by Ash-KODES** [comment]
Can I do this @KendallDoesCoding ?

**Comment by emmalearnscode** [comment]
Go ahead @Ash-KODES

**Comment by frankiefab100** [comment]
@emmalearnscode can I work resolve this? I make a PR now

**Comment by Ash-KODES** [comment]
> @emmalearnscode can I work resolve this? I make a PR now

Sorry for the delay guys,I was busy with my university exams,,,I will make a PR in next one day if i fail to do that then you can definetly work on it:))

**Comment by frankiefab100** [comment]
> > @emmalearnscode can I work resolve this? I make a PR now
> 
> Sorry for the delay guys,I was busy with my university exams,,,I will make a PR in next one day if i fail to do that then you can definetly work on it:))

Alright

**Comment by Ash-KODES** [comment]
> Icons in alphabetical order: Android Apple Book Codeforces Codewars DEV.to Discord Dollar Envelope Facebook GitHub GitLab Globe Graduation Hat Hashnode Instagram Left Arrow Link LinkedIn Medium Microsoft PayPal Polywork Search Send Slack Snapchat Telegram TikTok Twitch Twitter Vimeo YouTube

Thankyou for sorting it @KendallDoesCoding,It helped:)
